dqm4hep::DQMGuiMonitorElement Class Reference
DQMGuiMonitorElement class.
#include <DQMGuiMonitorElement.h>
Signals
void updated ()
Signal emitted when the properties of the monitor element or the monitor element pointer have been updated.
Public Member Functions
DQMGuiMonitorElement (DQMMonitorElement *pMonitorElement)
Constructor with a monitoring instance.
virtual ~DQMGuiMonitorElement ()
Destructor.
DQMMonitorElement * getMonitorElement () const
Get the wrapped monitor element.
void update (DQMMonitorElement *pMonitorElement)
Update the gui monitor element with a new monitor element.
bool equals (DQMMonitorElement *pMonitorElement) const
Whether the two monitor elements area equal.
bool equals (DQMGuiMonitorElement *pGuiMonitorElement) const
Whether the two monitor elements area equal.
void setDrawOption (const std::string &drawOption)
Set the monitor element draw option.
void setDescription (const std::string &description)
Set the monitor element description.
void setQuality (DQMQuality quality)
Set the monitor element quality.
Protected Attributes
DQMMonitorElement * m_pMonitorElement
Friends
class DQMMonitoringModel
Detailed Description
DQMGuiMonitorElement class.
Definition at line 44 of file DQMGuiMonitorElement.h.
Constructor & Destructor Documentation
dqm4hep::DQMGuiMonitorElement::DQMGuiMonitorElement (DQMMonitorElement * pMonitorElement)
Constructor with a monitoring instance.
Definition at line 37 of file DQMGuiMonitorElement.cc.
                                                                             :
    m_pMonitorElement(pMonitorElement)
{
  /* nop */
}
dqm4hep::DQMGuiMonitorElement::~DQMGuiMonitorElement () [virtual]
Destructor.
Definition at line 45 of file DQMGuiMonitorElement.cc.
References m_pMonitorElement.
{
  if(NULL != m_pMonitorElement)
    delete m_pMonitorElement;
}
Member Function Documentation
bool dqm4hep::DQMGuiMonitorElement::equals (DQMMonitorElement * pMonitorElement) const
Whether the two monitor elements area equal.
Definition at line 77 of file DQMGuiMonitorElement.cc.
References getMonitorElement(), and m_pMonitorElement.
Referenced by dqm4hep::DQMCanvasArea::getCanvas().
{
  if(NULL == pMonitorElement)
    return false;
  if(NULL == m_pMonitorElement)
    return false;
  const DQMPath &path = pMonitorElement->getPath();
  const std::string &moduleName = pMonitorElement->getModuleName();
  const std::string &name = pMonitorElement->getName();
  const std::string &collectorName = pMonitorElement->getCollectorName();
  bool samePath = (path == this->getMonitorElement()->getPath());
  bool sameModuleName = (moduleName == this->getMonitorElement()->getModuleName());
  bool sameName = (name == this->getMonitorElement()->getName());
  bool sameCollectorName = (collectorName == this->getMonitorElement()->getCollectorName());
  return (samePath && sameModuleName && sameName && sameCollectorName);
}
bool dqm4hep::DQMGuiMonitorElement::equals (DQMGuiMonitorElement * pGuiMonitorElement) const
Whether the two monitor elements area equal.
Definition at line 100 of file DQMGuiMonitorElement.cc.
References getMonitorElement().
{
  if(NULL == pGuiMonitorElement)
    return false;
  const DQMPath &path = pGuiMonitorElement->getMonitorElement()->getPath();
  const std::string &moduleName = pGuiMonitorElement->getMonitorElement()->getModuleName();
  const std::string &name = pGuiMonitorElement->getMonitorElement()->getName();
  const std::string &collectorName = pGuiMonitorElement->getMonitorElement()->getCollectorName();
  bool samePath = (path == this->getMonitorElement()->getPath());
  bool sameModuleName = (moduleName == this->getMonitorElement()->getModuleName());
  bool sameName = (name == this->getMonitorElement()->getName());
  bool sameCollectorName = (collectorName == this->getMonitorElement()->getCollectorName());
  return (samePath && sameModuleName && sameName && sameCollectorName);
}
DQMMonitorElement * dqm4hep::DQMGuiMonitorElement::getMonitorElement () const
Get the wrapped monitor element.
Definition at line 120 of file DQMGuiMonitorElement.cc.
References m_pMonitorElement.
Referenced by dqm4hep::DQMRootWidget::draw(), equals(), dqm4hep::DQMMonitorElementInfoWidget::fillInfos(), dqm4hep::DQMMonitoringModel::findMonitorElement(), dqm4hep::DQMMonitoringModel::getOrCreateGuiMonitorElement(), dqm4hep::DQMMonitoringModel::loadMonitorElementInfoList(), dqm4hep::DQMMonitoringController::openInROOTWindow(), dqm4hep::DQMMonitoringController::openMonitorElementInfo(), dqm4hep::DQMMonitoringController::openQualityTestResults(), dqm4hep::DQMMonitoringController::queryUpdate(), dqm4hep::DQMMonitorElementNavigator::removeMonitorElement(), dqm4hep::DQMMonitorElementView::removeMonitorElement(), dqm4hep::DQMMonitoringController::saveAs(), dqm4hep::DQMRootWidget::setDrawOptionFromDialog(), dqm4hep::DQMCanvasView::toXml(), dqm4hep::DQMRootWidget::unzoom(), dqm4hep::DQMMonitoringModel::updateMonitorElement(), dqm4hep::DQMMonitorElementNavigator::updateMonitorElement(), dqm4hep::DQMRootWidget::updateMonitorElement(), and dqm4hep::DQMMonitorElementView::updateMonitorElement().
{
  return m_pMonitorElement;
}
void dqm4hep::DQMGuiMonitorElement::setDescription (const std::string & description)
Set the monitor element description.
Definition at line 138 of file DQMGuiMonitorElement.cc.
References m_pMonitorElement, and updated().
{
  if(m_pMonitorElement)
  {
    m_pMonitorElement->setDescription(description);
    emit updated();
  }
}
void dqm4hep::DQMGuiMonitorElement::setDrawOption (const std::string & drawOption)
Set the monitor element draw option.
Definition at line 127 of file DQMGuiMonitorElement.cc.
References m_pMonitorElement, and updated().
Referenced by dqm4hep::DQMRootWidget::setDrawOption(), and dqm4hep::DQMRootWidget::setDrawOptionFromDialog().
{
  if(m_pMonitorElement)
  {
    m_pMonitorElement->setDrawOption(drawOption);
    emit updated();
  }
}
void dqm4hep::DQMGuiMonitorElement::setQuality (DQMQuality quality)
Set the monitor element quality.
Definition at line 149 of file DQMGuiMonitorElement.cc.
References m_pMonitorElement, and updated().
{
  if(m_pMonitorElement)
  {
    m_pMonitorElement->setQuality(quality);
    emit updated();
  }
}
void dqm4hep::DQMGuiMonitorElement::update (DQMMonitorElement * pMonitorElement)
Update the gui monitor element with a new monitor element.
Definition at line 53 of file DQMGuiMonitorElement.cc.
References m_pMonitorElement, and updated().
Referenced by dqm4hep::DQMMonitoringModel::updateMonitorElement().
{
  if(m_pMonitorElement == pMonitorElement)
    return;
  if(m_pMonitorElement)
  {
    if(pMonitorElement)
    {
      // save previous state
      const std::string &drawOption(m_pMonitorElement->getDrawOption());
      pMonitorElement->setDrawOption(drawOption);
    }
    delete m_pMonitorElement;
  }
  m_pMonitorElement = pMonitorElement;
  emit updated();
}
void dqm4hep::DQMGuiMonitorElement::updated () [signal]
Signal emitted when the properties of the monitor element or the monitor element pointer have been updated.
Referenced by setDescription(), setDrawOption(), setQuality(), and update().
Friends And Related Function Documentation
friend class DQMMonitoringModel [friend]
Definition at line 48 of file DQMGuiMonitorElement.h.
Member Data Documentation
DQMMonitorElement* dqm4hep::DQMGuiMonitorElement::m_pMonitorElement [protected]
Definition at line 94 of file DQMGuiMonitorElement.h.
Referenced by equals(), getMonitorElement(), setDescription(), setDrawOption(), setQuality(), update(), and ~DQMGuiMonitorElement().
The documentation for this class was generated from the following files:
DQMGuiMonitorElement.h
DQMGuiMonitorElement.cc