dqm4hep::DQMMonitoring Class Reference
DQMMonitoring class.
#include <DQMMonitoring.h>
Public Member Functions
DQMMonitoring ()
Constructor.
virtual ~DQMMonitoring ()
Destructor.
void setController (DQMMonitoringController *pController)
Set the monitoring controller.
DQMMonitoringController * getController () const
Get the monitoring controller.
void setModel (DQMMonitoringModel *pModel)
Set the monitoring model.
DQMMonitoringModel * getModel () const
Get the monitoring model.
void setView (DQMMonitoringView *pView)
Set the monitoring view.
DQMMonitoringView * getView () const
get the monitoring controller
Protected Attributes
DQMMonitoringController * m_pController
The monitoring controller.
DQMMonitoringModel * m_pModel
The monitoring model.
DQMMonitoringView * m_pView
The monitoring view.
Detailed Description
DQMMonitoring class.
Definition at line 44 of file DQMMonitoring.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitoring::DQMMonitoring ()
Constructor.
Definition at line 37 of file DQMMonitoring.cc.
                             :
  m_pController(NULL),
  m_pModel(NULL),
  m_pView(NULL)
{
  /* nop */
}
dqm4hep::DQMMonitoring::~DQMMonitoring () [virtual]
Destructor.
Definition at line 47 of file DQMMonitoring.cc.
References m_pController, m_pModel, and m_pView.
{
  if(m_pController)
    delete m_pController;
  if(m_pModel)
    delete m_pModel;
  if(m_pView)
    delete m_pView;
}
Member Function Documentation
DQMMonitoringController * dqm4hep::DQMMonitoring::getController () const
Get the monitoring controller.
Definition at line 74 of file DQMMonitoring.cc.
References m_pController.
Referenced by dqm4hep::DQMMonitoringMainWindow::closeEvent(), dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements(), dqm4hep::DQMCanvasArea::dropEvent(), dqm4hep::DQMMonitoringView::handleAutoUpdateButtonClicked(), dqm4hep::DQMBrowserWidget::handleCollectorSelection(), dqm4hep::DQMMonitorElementNavigator::handleItemDoubleClick(), dqm4hep::DQMBrowserWidget::handleReplaceButtonClicked(), dqm4hep::DQMCanvasView::handleSaveAsActionTriggered(), dqm4hep::DQMBrowserWidget::handleUpdateButtonClicked(), dqm4hep::DQMRootWidget::openROOTPanel(), dqm4hep::DQMRootWidget::queryUpdate(), dqm4hep::DQMMonitorElementNavigator::queryUpdate(), dqm4hep::DQMRootWidget::saveAs(), dqm4hep::TreeWidgetItem::setData(), dqm4hep::DQMRootWidget::showMonitorElementInfo(), dqm4hep::DQMRootWidget::showQTestResults(), dqm4hep::DQMMonitorElementNavigator::startDrag(), dqm4hep::DQMMonitorElementNavigator::updateMonitorElement(), and dqm4hep::DQMRootWidget::updateMonitorElement().
{
  return m_pController;
}
DQMMonitoringModel * dqm4hep::DQMMonitoring::getModel () const
Get the monitoring model.
Definition at line 94 of file DQMMonitoring.cc.
References m_pModel.
Referenced by dqm4hep::DQMMonitoringController::clearMonitoring(), dqm4hep::DQMMonitoringController::clearViewAndModel(), dqm4hep::DQMMonitoringController::createEmptyMonitorElements(), dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements(), dqm4hep::DQMCanvasArea::dropEvent(), dqm4hep::DQMCanvasView::fromXml(), dqm4hep::DQMMonitorElementNavigator::handleItemDoubleClick(), dqm4hep::DQMMonitorElementNavigator::keyPressEvent(), dqm4hep::DQMMonitoringController::openFile(), dqm4hep::DQMMonitorElementNavigator::queryUpdate(), and dqm4hep::DQMMonitoringController::receiveMonitorElementPublication().
{
  return m_pModel;
}
DQMMonitoringView * dqm4hep::DQMMonitoring::getView () const
get the monitoring controller
Definition at line 114 of file DQMMonitoring.cc.
References m_pView.
Referenced by dqm4hep::DQMMonitoringModel::clear(), dqm4hep::DQMMonitoringController::clearMonitoring(), dqm4hep::DQMMonitoringController::clearViewAndModel(), dqm4hep::DQMRootWidget::createContextMenu(), dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements(), dqm4hep::DQMMonitoringModel::getOrCreateGuiMonitorElement(), dqm4hep::DQMMonitorElementNavigator::handleItemDoubleClick(), dqm4hep::DQMMonitoringController::handleServerShutdown(), dqm4hep::DQMMonitoringController::handleServerStartup(), dqm4hep::DQMMonitorElementNavigator::keyPressEvent(), dqm4hep::DQMMonitoringModel::loadMonitorElementInfoList(), dqm4hep::DQMMonitoringController::log(), dqm4hep::DQMRootWidget::moveCanvas(), dqm4hep::DQMMonitoringController::openFile(), dqm4hep::DQMRootWidget::removeCanvas(), dqm4hep::DQMMonitoringModel::removeMonitorElement(), dqm4hep::DQMMonitoringController::saveAs(), dqm4hep::DQMMonitorElementNavigator::showContextMenu(), and dqm4hep::DQMMonitoringModel::updateMonitorElement().
{
  return m_pView;
}
void dqm4hep::DQMMonitoring::setController (DQMMonitoringController * pController)
Set the monitoring controller.
Definition at line 61 of file DQMMonitoring.cc.
References m_pController.
Referenced by dqm4hep::DQMMonitoringController::DQMMonitoringController().
{
  if(m_pController == pController)
    return;
  if(NULL != m_pController)
    delete m_pController;
  m_pController = pController;
}
void dqm4hep::DQMMonitoring::setModel (DQMMonitoringModel * pModel)
Set the monitoring model.
Definition at line 81 of file DQMMonitoring.cc.
References m_pModel.
Referenced by dqm4hep::DQMMonitoringModel::DQMMonitoringModel().
{
  if(m_pModel == pModel)
    return;
  if(NULL != m_pModel)
    delete m_pModel;
  m_pModel = pModel;
}
void dqm4hep::DQMMonitoring::setView (DQMMonitoringView * pView)
Set the monitoring view.
Definition at line 101 of file DQMMonitoring.cc.
References m_pView.
Referenced by dqm4hep::DQMMonitoringView::DQMMonitoringView().
{
  if(m_pView == pView)
    return;
  if(NULL != m_pView)
    delete m_pView;
  m_pView = pView;
}
Member Data Documentation
DQMMonitoringController* dqm4hep::DQMMonitoring::m_pController [protected]
The monitoring controller.
Definition at line 81 of file DQMMonitoring.h.
Referenced by getController(), setController(), and ~DQMMonitoring().
DQMMonitoringModel* dqm4hep::DQMMonitoring::m_pModel [protected]
The monitoring model.
Definition at line 82 of file DQMMonitoring.h.
Referenced by getModel(), setModel(), and ~DQMMonitoring().
DQMMonitoringView* dqm4hep::DQMMonitoring::m_pView [protected]
The monitoring view.
Definition at line 83 of file DQMMonitoring.h.
Referenced by getView(), setView(), and ~DQMMonitoring().
The documentation for this class was generated from the following files:
DQMMonitoring.h
DQMMonitoring.cc