dqm4hep::DQMJobInterface Class Reference
DQMJobInterface class.
#include <DQMJobInterface.h>
Public Slots
void startUpdate (int nSeconds)
Start update.
void stopUpdate ()
Stop update.
Signals
void statusReceived (const QString &hostName)
Signal emitted when job status are received.
Public Member Functions
DQMJobInterface ()
Constructor.
virtual ~DQMJobInterface ()
Destructor.
bool started () const
Whether the automatic update mode has been started.
Private Member Functions
void statusReceived (const std::string &hostName)
Call back method when jobs status are received.
Private Attributes
bool m_started
Detailed Description
DQMJobInterface class.
Definition at line 43 of file DQMJobInterface.h.
Constructor & Destructor Documentation
dqm4hep::DQMJobInterface::DQMJobInterface ()
Constructor.
Definition at line 34 of file DQMJobInterface.cc.
                                 :
    DimJobInterface(),
    m_started(false)
{
  /* nop */
}
dqm4hep::DQMJobInterface::~DQMJobInterface () [virtual]
Destructor.
Definition at line 43 of file DQMJobInterface.cc.
{
  /* nop */
}
Member Function Documentation
bool dqm4hep::DQMJobInterface::started () const
Whether the automatic update mode has been started.
Definition at line 50 of file DQMJobInterface.cc.
References m_started.
Referenced by dqm4hep::DQMJobInterfaceWidget::handleAutomaticModeButtonClicked(), and dqm4hep::DQMJobInterfaceWidget::handleAutomaticModeValueChanged().
{
  return m_started;
}
void dqm4hep::DQMJobInterface::startUpdate (int nSeconds) [slot]
Start update.
Alias slot function for startTimer(nSeconds)
Definition at line 57 of file DQMJobInterface.cc.
References m_started.
Referenced by dqm4hep::DQMJobInterfaceWidget::handleAutomaticModeButtonClicked(), and dqm4hep::DQMJobInterfaceWidget::handleAutomaticModeValueChanged().
{
  if(m_started)
    DimJobInterface::stopTimer();
  DimJobInterface::startTimer(nSeconds);
  m_started = true;
}
void dqm4hep::DQMJobInterface::statusReceived (const std::string & hostName) [private]
Call back method when jobs status are received.
Definition at line 78 of file DQMJobInterface.cc.
{
  emit statusReceived(QString(hostName.c_str()));
}
void dqm4hep::DQMJobInterface::statusReceived (const QString & hostName) [signal]
Signal emitted when job status are received.
void dqm4hep::DQMJobInterface::stopUpdate () [slot]
Stop update.
Alias slot function for stopTimer()
Definition at line 68 of file DQMJobInterface.cc.
References m_started.
Referenced by dqm4hep::DQMJobInterfaceWidget::handleAutomaticModeButtonClicked(), and dqm4hep::DQMJobInterfaceWidget::handleAutomaticModeValueChanged().
{
  if(m_started)
    DimJobInterface::stopTimer();
  m_started = false;
}
Member Data Documentation
bool dqm4hep::DQMJobInterface::m_started [private]
Definition at line 83 of file DQMJobInterface.h.
Referenced by started(), startUpdate(), and stopUpdate().
The documentation for this class was generated from the following files:
DQMJobInterface.h
DQMJobInterface.cc