dqm4hep::DQMCanvasView Class Reference
DQMCanvasView class.
#include <DQMCanvasView.h>
Public Slots
virtual void createCanvasArea (const std::string &areaName=``)
Create a canvas area.
virtual void createCanvasAreaAndSetCurrent (const std::string &areaName=``)
Create a canvas area and set it as current.
virtual void drawInCurrentArea (DQMGuiMonitorElement *pMonitorElement)
Draw the monitor element in the current area.
virtual void drawInArea (DQMGuiMonitorElement *pMonitorElement, int index)
Draw the monitor element in area indexed by 'index'.
virtual void drawInNewArea (DQMGuiMonitorElement *pMonitorElement, const std::string &areaName=``)
Draw the monitor element in a new area.
virtual void removeCanvasArea (int index)
Remove the canvas area by index.
virtual void renameCanvasArea (int index, const std::string &newAreaName)
Rename the canvas area indexed by 'index' with name 'newAreaName'.
virtual void clearArea (int index)
Clear the area indexed by 'index'.
virtual void clear ()
Clear and remove all canvas areas.
virtual void showContextMenu (const QPoint &point)
Show the context menu of this widget.
virtual void setCurrentCanvasArea (int index)
Set the current canvas area by index.
virtual void moveCanvas (DQMCanvas *pCanvas, int newAreaIndex)
Move the canvas from the current area to the area indexed by 'index'.
Public Member Functions
DQMCanvasView (DQMMonitoring *pMonitoring, QWidget *pParent=0)
Constructor.
virtual ~DQMCanvasView ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
TiXmlElement * toXml () const
Export settings to xml element.
void fromXml (TiXmlElement *const pXmlElement)
Import settings from xml element.
virtual DQMCanvasArea * getCurrentCanvasArea () const
Get the current canvas area.
virtual std::string getCurrentCanvasAreaName () const
Get the current canvas area name.
virtual DQMCanvasArea * getCanvasArea (int index) const
Get the canvas area by index.
virtual int getCanvasAreaIndex (DQMCanvasArea *pCanvasArea) const
Get the canvas area index using an instance of canvas area.
virtual std::string getCanvasAreaName (int index) const
Get the canvas area name by index.
virtual int canvasAreaCount () const
Get the number of canvas areas.
virtual QList< DQMCanvasArea * > canvasAreaList () const
Get the canvas area list.
Protected Member Functions
virtual bool eventFilter (QObject *pObject, QEvent *pEvent)
Event filter mainly used to process the context menu.
virtual QMenu * createContextMenu () const
Create the context menu.
void renameCanvasAreaFromInputDialog (int index)
Rename the canvas area given by 'index'.
Private Slots
void handleRenameAreaActionTriggered ()
Handle rename area action triggered by context menu.
void handleRemoveAreaActionTriggered ()
Handle remove area action triggered by context menu.
void handleClearAreaActionTriggered ()
Handle clear area action triggered by context menu.
void handleSaveAsActionTriggered ()
Handle save as action triggered by context menu.
Private Attributes
DQMMonitoring * m_pMonitoring
DQMTabWidget * m_pTabWidget
Detailed Description
DQMCanvasView class.
Definition at line 51 of file DQMCanvasView.h.
Constructor & Destructor Documentation
dqm4hep::DQMCanvasView::DQMCanvasView (DQMMonitoring * pMonitoring, QWidget * pParent = 0)
Constructor.
Definition at line 84 of file DQMCanvasView.cc.
References createCanvasArea(), m_pTabWidget, and removeCanvasArea().
                                                                         :
    QWidget(pParent),
    m_pMonitoring(pMonitoring)
{
  setLayout(new QHBoxLayout());
  m_pTabWidget = new DQMTabWidget(this);
  layout()->addWidget(m_pTabWidget);
  m_pTabWidget->installEventFilter(this);
  m_pTabWidget->setMovable(true);
  m_pTabWidget->setTabsClosable(true);
    QToolButton *pButton = new QToolButton(m_pTabWidget);
    pButton->setText("+");
    pButton->setAutoRaise(true);
    m_pTabWidget->setCornerWidget(pButton);
  this->createCanvasArea("Canvas area");
  connect(m_pTabWidget, SIGNAL(tabCloseRequested(int)), this, SLOT(
      removeCanvasArea(int)));
  connect(pButton, SIGNAL(clicked()), this, SLOT(createCanvasArea()));
  installEventFilter(this);
}
dqm4hep::DQMCanvasView::~DQMCanvasView () [virtual]
Destructor.
Definition at line 111 of file DQMCanvasView.cc.
References getCanvasArea(), and m_pTabWidget.
{
  while(m_pTabWidget->count() != 0)
  {
    DQMCanvasArea *pCanvasArea = this->getCanvasArea(0);
    m_pTabWidget->removeTab(0);
    pCanvasArea->deleteLater();
  }
}
Member Function Documentation
int dqm4hep::DQMCanvasView::canvasAreaCount () const [virtual]
Get the number of canvas areas.
Definition at line 335 of file DQMCanvasView.cc.
References m_pTabWidget.
Referenced by dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements(), dqm4hep::DQMMonitorElementNavigator::showContextMenu(), and toXml().
{
  return m_pTabWidget->count();
}
QList< DQMCanvasArea * > dqm4hep::DQMCanvasView::canvasAreaList () const [virtual]
Get the canvas area list.
Definition at line 342 of file DQMCanvasView.cc.
References getCanvasArea(), and m_pTabWidget.
Referenced by dqm4hep::DQMRootWidget::createContextMenu().
{
  QList<DQMCanvasArea*> list;
  for(int i=0 ; i<m_pTabWidget->count() ; i++)
  {
    DQMCanvasArea *pCanvasArea = this->getCanvasArea(i);
    if(!pCanvasArea)
      continue;
    list.append(pCanvasArea);
  }
  return list;
}
void dqm4hep::DQMCanvasView::clear () [virtual], [slot]
Clear and remove all canvas areas.
Definition at line 445 of file DQMCanvasView.cc.
References createCanvasArea(), getCanvasArea(), and m_pTabWidget.
Referenced by dqm4hep::DQMMonitoringView::clear(), and createContextMenu().
{
  while(m_pTabWidget->count() != 0)
  {
    DQMCanvasArea *pCanvasArea = this->getCanvasArea(0);
    m_pTabWidget->removeTab(0);
    pCanvasArea->deleteLater();
  }
  this->createCanvasArea();
}
void dqm4hep::DQMCanvasView::clearArea (int index) [virtual], [slot]
Clear the area indexed by 'index'.
Definition at line 433 of file DQMCanvasView.cc.
References dqm4hep::DQMCanvasArea::clear(), and getCanvasArea().
Referenced by handleClearAreaActionTriggered().
{
  DQMCanvasArea *pCanvasArea = this->getCanvasArea(index);
  if(!pCanvasArea)
    return;
  pCanvasArea->clear();
}
void dqm4hep::DQMCanvasView::createCanvasArea (const std::string & areaName = ``) [virtual], [slot]
Create a canvas area.
Definition at line 361 of file DQMCanvasView.cc.
References getMonitoring(), and m_pTabWidget.
Referenced by clear(), createCanvasAreaAndSetCurrent(), createContextMenu(), DQMCanvasView(), and removeCanvasArea().
{
  QString name;
  if(areaName.empty())
    name = "Canvas area";
  else
    name = areaName.c_str();
  DQMCanvasArea *pCanvasArea = new DQMCanvasArea(this->getMonitoring());
  m_pTabWidget->addTab(pCanvasArea, name);
}
void dqm4hep::DQMCanvasView::createCanvasAreaAndSetCurrent (const std::string & areaName = ``) [virtual], [slot]
Create a canvas area and set it as current.
Definition at line 376 of file DQMCanvasView.cc.
References createCanvasArea(), m_pTabWidget, and setCurrentCanvasArea().
Referenced by drawInNewArea(), dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements(), and fromXml().
{
  this->createCanvasArea(areaName);
  this->setCurrentCanvasArea(m_pTabWidget->count()-1);
}
QMenu * dqm4hep::DQMCanvasView::createContextMenu () const [protected], [virtual]
Create the context menu.
Definition at line 497 of file DQMCanvasView.cc.
References clear(), createCanvasArea(), handleClearAreaActionTriggered(), handleRemoveAreaActionTriggered(), handleRenameAreaActionTriggered(), handleSaveAsActionTriggered(), m_pTabWidget, and dqm4hep::DQMTabWidget::tabBar().
Referenced by showContextMenu().
{
  QMenu *pContextMenu = new QMenu();
    QPoint point = m_pTabWidget->tabBar()->mapFromGlobal(QCursor::pos());
    int tabIndex = m_pTabWidget->tabBar()->tabAt(point);
  QAction *pRenameAreaAction = pContextMenu->addAction("Rename area", this, SLOT(
      handleRenameAreaActionTriggered()));
  QAction *pRemoveAreaAction = pContextMenu->addAction("Remove area", this, SLOT(
      handleRemoveAreaActionTriggered()));
  QAction *pRemoveAllAreasAction = pContextMenu->addAction("Remove all areas", this, SLOT(
      clear()));
  QAction *pCreateNewAreaAction = pContextMenu->addAction("Create new area", this, SLOT(
      createCanvasArea()));
  QAction *pClearAreaAction = pContextMenu->addAction("Clear area", this, SLOT(
      handleClearAreaActionTriggered()));
  QAction *pSaveAsAction = pContextMenu->addAction("Save as", this, SLOT(
      handleSaveAsActionTriggered()));
  if(tabIndex < 0)
  {
    pRenameAreaAction->setEnabled(false);
    pRemoveAreaAction->setEnabled(false);
    pClearAreaAction->setEnabled(false);
    pSaveAsAction->setEnabled(false);
  }
  else
  {
    pRenameAreaAction->setData(tabIndex);
    pRemoveAreaAction->setData(tabIndex);
    pClearAreaAction->setData(tabIndex);
    pSaveAsAction->setData(tabIndex);
  }
    return pContextMenu;
}
void dqm4hep::DQMCanvasView::drawInArea (DQMGuiMonitorElement * pMonitorElement, int index) [virtual], [slot]
Draw the monitor element in area indexed by 'index'.
Update it if already drawn
Definition at line 392 of file DQMCanvasView.cc.
References dqm4hep::DQMCanvasArea::draw(), and getCanvasArea().
Referenced by dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements().
{
  DQMCanvasArea *pCanvasArea = this->getCanvasArea(index);
  if(pCanvasArea)
    pCanvasArea->draw(pMonitorElement);
}
void dqm4hep::DQMCanvasView::drawInCurrentArea (DQMGuiMonitorElement * pMonitorElement) [virtual], [slot]
Draw the monitor element in the current area.
Update it if already drawn
Definition at line 384 of file DQMCanvasView.cc.
References dqm4hep::DQMCanvasArea::draw(), and getCurrentCanvasArea().
Referenced by drawInNewArea(), dqm4hep::DQMMonitorElementNavigator::handleItemDoubleClick(), and dqm4hep::DQMMonitorElementNavigator::keyPressEvent().
{
  DQMCanvasArea *pCanvasArea = this->getCurrentCanvasArea();
  pCanvasArea->draw(pMonitorElement);
}
void dqm4hep::DQMCanvasView::drawInNewArea (DQMGuiMonitorElement * pMonitorElement, const std::string & areaName = ``) [virtual], [slot]
Draw the monitor element in a new area.
Definition at line 402 of file DQMCanvasView.cc.
References createCanvasAreaAndSetCurrent(), and drawInCurrentArea().
{
  this->createCanvasAreaAndSetCurrent(areaName);
  this->drawInCurrentArea(pMonitorElement);
}
bool dqm4hep::DQMCanvasView::eventFilter (QObject * pObject, QEvent * pEvent) [protected], [virtual]
Event filter mainly used to process the context menu.
Definition at line 531 of file DQMCanvasView.cc.
References m_pTabWidget, renameCanvasAreaFromInputDialog(), showContextMenu(), and dqm4hep::DQMTabWidget::tabBar().
{
    if(pEvent->type() == QEvent::ContextMenu)
    {
        this->showContextMenu(this->cursor().pos());
        return true;
    }
    // Rename a tab if DoubleClick on it
    else if (pObject == m_pTabWidget->tabBar() && pEvent->type() == QEvent::MouseButtonDblClick)
    {
        QTabBar *pTabBar = m_pTabWidget->tabBar();
        QPoint p = pTabBar->mapFromGlobal(QCursor::pos());
        int index = pTabBar->tabAt(p);
        this->renameCanvasAreaFromInputDialog(index);
    }
    return QObject::eventFilter(pObject, pEvent);
}
void dqm4hep::DQMCanvasView::fromXml (TiXmlElement *const pXmlElement)
Import settings from xml element.
Definition at line 189 of file DQMCanvasView.cc.
References dqm4hep::DQMCanvasArea::createCanvas(), createCanvasAreaAndSetCurrent(), dqm4hep::DQMMonitoringModel::createGuiMonitorElement(), dqm4hep::DQMMonitoringModel::findMonitorElement(), getCanvasArea(), getCurrentCanvasArea(), dqm4hep::DQMMonitoring::getModel(), getMonitoring(), m_pTabWidget, and dqm4hep::DQMMonitoringModel::updateMonitorElement().
Referenced by dqm4hep::DQMMonitoringView::fromXml().
{
  if(!pXmlElement)
    return;
  // manual clear
  while(m_pTabWidget->count() != 0)
  {
    DQMCanvasArea *pCanvasArea = this->getCanvasArea(0);
    m_pTabWidget->removeTab(0);
    pCanvasArea->deleteLater();
  }
  int nCreatedCanvaAreas = 0;
    TiXmlHandle elementHandle(pXmlElement);
    for (TiXmlElement *pCanvasAreaElement = elementHandle.FirstChild("canvasArea").Element(); NULL !=
      pCanvasAreaElement;
        pCanvasAreaElement = pCanvasAreaElement->NextSiblingElement("canvasArea"))
    {
      std::string canvasAreaName;
        if(pCanvasAreaElement->QueryStringAttribute("name", &canvasAreaName))
            continue;
        this->createCanvasAreaAndSetCurrent(canvasAreaName);
        DQMCanvasArea *pCanvasArea = this->getCurrentCanvasArea();
        TiXmlHandle canvasAreaHandle(pCanvasAreaElement);
        for (TiXmlElement *pCanvasElement = canvasAreaHandle.FirstChild("canvas").Element(); NULL !=
      pCanvasElement;
            pCanvasElement = pCanvasElement->NextSiblingElement("canvas"))
        {
            TiXmlHandle canvasHandle(pCanvasElement);
            TiXmlElement *pMeElement = canvasHandle.FirstChild("monitorElement").Element();
            if(!pMeElement)
              continue;
          int x;
          int y;
          int width;
          int height;
          bool maximized = false;
            if(pCanvasElement->QueryIntAttribute("x", &x))
                continue;
            if(pCanvasElement->QueryIntAttribute("y", &y))
                continue;
            if(pCanvasElement->QueryIntAttribute("w", &width))
                continue;
            if(pCanvasElement->QueryIntAttribute("h", &height))
                continue;
            if(pCanvasElement->QueryValueAttribute("maximized", &maximized))
              maximized = false;
            std::string collectorName;
            std::string moduleName;
            std::string path;
            std::string name;
            if(pMeElement->QueryStringAttribute("collector", &collectorName))
              continue;
            if(pMeElement->QueryStringAttribute("module", &moduleName))
              continue;
            if(pMeElement->QueryStringAttribute("path", &path))
              continue;
            if(pMeElement->QueryStringAttribute("name", &name))
              continue;
            DQMGuiMonitorElement *pMonitorElement =
                this->getMonitoring()->getModel()->findMonitorElement(
                    collectorName,
                    moduleName,
                    path,
                    name);
            if(!pMonitorElement)
            {
              // create a default one that will be updated afterward
        pMonitorElement =
            this->getMonitoring()->getModel()->createGuiMonitorElement(
                collectorName,
                moduleName,
                path,
                name);
        this->getMonitoring()->getModel()->updateMonitorElement(pMonitorElement);
            }
            DQMCanvas *pCanvas = pCanvasArea->createCanvas(pMonitorElement);
            pCanvas->move(x, y);
            pCanvas->resize(width, height);
            if(maximized)
              pCanvas->showMaximized();
        }
    }
}
DQMCanvasArea * dqm4hep::DQMCanvasView::getCanvasArea (int index) const [virtual]
Get the canvas area by index.
Definition at line 314 of file DQMCanvasView.cc.
References m_pTabWidget.
Referenced by canvasAreaList(), clear(), clearArea(), drawInArea(), fromXml(), handleSaveAsActionTriggered(), moveCanvas(), removeCanvasArea(), toXml(), and ~DQMCanvasView().
{
  return (DQMCanvasArea *) m_pTabWidget->widget(index);
}
int dqm4hep::DQMCanvasView::getCanvasAreaIndex (DQMCanvasArea * pCanvasArea) const [virtual]
Get the canvas area index using an instance of canvas area.
Definition at line 321 of file DQMCanvasView.cc.
References m_pTabWidget.
Referenced by dqm4hep::DQMMonitorElementNavigator::showContextMenu().
{
  return m_pTabWidget->indexOf(pCanvasArea);
}
std::string dqm4hep::DQMCanvasView::getCanvasAreaName (int index) const [virtual]
Get the canvas area name by index.
Definition at line 328 of file DQMCanvasView.cc.
References m_pTabWidget.
Referenced by dqm4hep::DQMRootWidget::createContextMenu(), dqm4hep::DQMMonitorElementNavigator::showContextMenu(), and toXml().
{
  return m_pTabWidget->tabText(index).toStdString();
}
DQMCanvasArea * dqm4hep::DQMCanvasView::getCurrentCanvasArea () const [virtual]
Get the current canvas area.
Definition at line 297 of file DQMCanvasView.cc.
References m_pTabWidget.
Referenced by dqm4hep::DQMRootWidget::createContextMenu(), drawInCurrentArea(), fromXml(), moveCanvas(), dqm4hep::DQMRootWidget::removeCanvas(), and dqm4hep::DQMMonitorElementNavigator::showContextMenu().
{
  return (DQMCanvasArea *) m_pTabWidget->currentWidget();
}
std::string dqm4hep::DQMCanvasView::getCurrentCanvasAreaName () const [virtual]
Get the current canvas area name.
Definition at line 304 of file DQMCanvasView.cc.
References m_pTabWidget.
{
  int currentIndex = m_pTabWidget->currentIndex();
  QString name = m_pTabWidget->tabText(currentIndex);
  return name.toStdString();
}
DQMMonitoring * dqm4hep::DQMCanvasView::getMonitoring () const
Get the monitoring instance.
Definition at line 123 of file DQMCanvasView.cc.
References m_pMonitoring.
Referenced by createCanvasArea(), fromXml(), and handleSaveAsActionTriggered().
{
  return m_pMonitoring;
}
void dqm4hep::DQMCanvasView::handleClearAreaActionTriggered () [private], [slot]
Handle clear area action triggered by context menu.
Definition at line 595 of file DQMCanvasView.cc.
References clearArea().
Referenced by createContextMenu().
{
  QAction *pAction = (QAction *) sender();
  if(!pAction)
    return;
  int index = pAction->data().toInt();
  this->clearArea(index);
}
void dqm4hep::DQMCanvasView::handleRemoveAreaActionTriggered () [private], [slot]
Handle remove area action triggered by context menu.
Definition at line 582 of file DQMCanvasView.cc.
References removeCanvasArea().
Referenced by createContextMenu().
{
  QAction *pAction = (QAction *) sender();
  if(!pAction)
    return;
  int index = pAction->data().toInt();
  this->removeCanvasArea(index);
}
void dqm4hep::DQMCanvasView::handleRenameAreaActionTriggered () [private], [slot]
Handle rename area action triggered by context menu.
Definition at line 568 of file DQMCanvasView.cc.
References renameCanvasAreaFromInputDialog().
Referenced by createContextMenu().
{
  QAction *pAction = (QAction *) sender();
  if(!pAction)
    return;
  int index = pAction->data().toInt();
  this->renameCanvasAreaFromInputDialog(index);
}
void dqm4hep::DQMCanvasView::handleSaveAsActionTriggered () [private], [slot]
Handle save as action triggered by context menu.
Definition at line 608 of file DQMCanvasView.cc.
References getCanvasArea(), dqm4hep::DQMMonitoring::getController(), getMonitoring(), and dqm4hep::DQMMonitoringController::saveAs().
Referenced by createContextMenu().
{
  QAction *pAction = (QAction *) sender();
  if(!pAction)
    return;
  int index = pAction->data().toInt();
  DQMCanvasArea *pCanvasArea = this->getCanvasArea(index);
  if(!pCanvasArea)
    return;
  this->getMonitoring()->getController()->saveAs(pCanvasArea);
}
void dqm4hep::DQMCanvasView::moveCanvas (DQMCanvas * pCanvas, int newAreaIndex) [virtual], [slot]
Move the canvas from the current area to the area indexed by 'index'.
Definition at line 480 of file DQMCanvasView.cc.
References dqm4hep::DQMCanvasArea::addCanvas(), dqm4hep::DQMCanvasArea::contains(), getCanvasArea(), getCurrentCanvasArea(), and dqm4hep::DQMCanvasArea::removeCanvas().
Referenced by dqm4hep::DQMRootWidget::moveCanvas().
{
  if(!pCanvas)
    return;
  DQMCanvasArea *pCurrentCanvasArea = this->getCurrentCanvasArea();
  DQMCanvasArea *pMoveCanvasArea = this->getCanvasArea(newAreaIndex);
  if(!pMoveCanvasArea || !pCurrentCanvasArea->contains(pCanvas) || pCurrentCanvasArea == pMoveCanvasArea)
    return;
  pCurrentCanvasArea->removeCanvas(pCanvas, false);
  pMoveCanvasArea->addCanvas(pCanvas);
}
void dqm4hep::DQMCanvasView::removeCanvasArea (int index) [virtual], [slot]
Remove the canvas area by index.
Definition at line 410 of file DQMCanvasView.cc.
References createCanvasArea(), getCanvasArea(), and m_pTabWidget.
Referenced by DQMCanvasView(), and handleRemoveAreaActionTriggered().
{
  DQMCanvasArea *pCanvasArea = this->getCanvasArea(index);
  if(!pCanvasArea)
    return;
  m_pTabWidget->removeTab(index);
  pCanvasArea->deleteLater();
  if(m_pTabWidget->count() == 0)
    this->createCanvasArea();
}
void dqm4hep::DQMCanvasView::renameCanvasArea (int index, const std::string & newAreaName) [virtual], [slot]
Rename the canvas area indexed by 'index' with name 'newAreaName'.
Definition at line 426 of file DQMCanvasView.cc.
References m_pTabWidget.
Referenced by renameCanvasAreaFromInputDialog().
{
  m_pTabWidget->setTabText(index, newAreaName.c_str());
}
void dqm4hep::DQMCanvasView::renameCanvasAreaFromInputDialog (int index) [protected]
Rename the canvas area given by 'index'.
Get the area name from an input text dialog
Definition at line 553 of file DQMCanvasView.cc.
References m_pTabWidget, and renameCanvasArea().
Referenced by eventFilter(), and handleRenameAreaActionTriggered().
{
    bool ok = false;
    QString oldAreaName = m_pTabWidget->tabText(index);
    QString newAreaName = QInputDialog::getText(this, "New canvas area name",
                                               "", QLineEdit::Normal,
                                               oldAreaName, &ok);
    if(ok)
        this->renameCanvasArea(index, newAreaName.toStdString());
}
void dqm4hep::DQMCanvasView::setCurrentCanvasArea (int index) [virtual], [slot]
Set the current canvas area by index.
Definition at line 473 of file DQMCanvasView.cc.
References m_pTabWidget.
Referenced by createCanvasAreaAndSetCurrent().
{
  m_pTabWidget->setCurrentIndex(index);
}
void dqm4hep::DQMCanvasView::showContextMenu (const QPoint & point) [virtual], [slot]
Show the context menu of this widget.
Definition at line 459 of file DQMCanvasView.cc.
References createContextMenu().
Referenced by eventFilter().
{
    QWidget *pSelectedWidget = qApp->widgetAt(point);
    if(!pSelectedWidget)
        return;
    QMenu *pContextMenu = this->createContextMenu();
    pContextMenu->exec(point);
    pContextMenu->deleteLater();
}
TiXmlElement * dqm4hep::DQMCanvasView::toXml () const
Export settings to xml element.
Definition at line 130 of file DQMCanvasView.cc.
References canvasAreaCount(), dqm4hep::DQMCanvasArea::canvasCount(), dqm4hep::DQMCanvasArea::getCanvas(), getCanvasArea(), getCanvasAreaName(), dqm4hep::DQMCanvas::getCurrentMonitorElement(), and dqm4hep::DQMGuiMonitorElement::getMonitorElement().
Referenced by dqm4hep::DQMMonitoringView::toXml().
{
  TiXmlElement *pXmlElement = new TiXmlElement("canvasView");
  for(int c=0 ; c<this->canvasAreaCount() ; c++)
  {
    DQMCanvasArea *pCanvasArea = this->getCanvasArea(c);
    std::string canvasAreaName = this->getCanvasAreaName(c);
    TiXmlElement *pCanvasAreaElement = new TiXmlElement("canvasArea");
    pXmlElement->LinkEndChild(pCanvasAreaElement);
    pCanvasAreaElement->SetAttribute("name", canvasAreaName);
    for(int i=0 ; i<pCanvasArea->canvasCount() ; i++)
    {
      DQMCanvas *pCanvas = pCanvasArea->getCanvas(i);
      int x = pCanvas->x();
      int y = pCanvas->y();
      int width = pCanvas->width();
      int height = pCanvas->height();
      TiXmlElement *pCanvasElement = new TiXmlElement("canvas");
      pCanvasAreaElement->LinkEndChild(pCanvasElement);
      pCanvasElement->SetAttribute("x", x);
      pCanvasElement->SetAttribute("y", y);
      pCanvasElement->SetAttribute("w", width);
      pCanvasElement->SetAttribute("h", height);
      if(pCanvas->isMaximized())
        pCanvasElement->SetAttribute("maximized", true);
      DQMGuiMonitorElement *pGuiMonitorElement = pCanvas->getCurrentMonitorElement();
      if(pGuiMonitorElement)
      {
        std::string collectorName = pGuiMonitorElement->getMonitorElement()->getCollectorName();
        std::string moduleName = pGuiMonitorElement->getMonitorElement()->getModuleName();
        std::string path = pGuiMonitorElement->getMonitorElement()->getPath().getPath();
        std::string name = pGuiMonitorElement->getMonitorElement()->getName();
        TiXmlElement *pMeElement = new TiXmlElement("monitorElement");
        pCanvasElement->LinkEndChild(pMeElement);
        pMeElement->SetAttribute("collector", collectorName);
        pMeElement->SetAttribute("module", moduleName);
        pMeElement->SetAttribute("path", path);
        pMeElement->SetAttribute("name", name);
      }
    }
  }
  return pXmlElement;
}
Member Data Documentation
DQMMonitoring* dqm4hep::DQMCanvasView::m_pMonitoring [private]
Definition at line 188 of file DQMCanvasView.h.
Referenced by getMonitoring().
DQMTabWidget* dqm4hep::DQMCanvasView::m_pTabWidget [private]
Definition at line 189 of file DQMCanvasView.h.
Referenced by canvasAreaCount(), canvasAreaList(), clear(), createCanvasArea(), createCanvasAreaAndSetCurrent(), createContextMenu(), DQMCanvasView(), eventFilter(), fromXml(), getCanvasArea(), getCanvasAreaIndex(), getCanvasAreaName(), getCurrentCanvasArea(), getCurrentCanvasAreaName(), removeCanvasArea(), renameCanvasArea(), renameCanvasAreaFromInputDialog(), setCurrentCanvasArea(), and ~DQMCanvasView().
The documentation for this class was generated from the following files:
DQMCanvasView.h
DQMCanvasView.cc