dqm4hep::DQMCanvas Class Reference
DQMCanvas class.
#include <DQMCanvas.h>
Public Slots
void draw (DQMGuiMonitorElement *pMonitorElement)
Draw the monitor element on the root widget.
Public Member Functions
DQMCanvas (DQMMonitoring *pMonitoring)
Constructor.
virtual ~DQMCanvas ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
DQMGuiMonitorElement * getCurrentMonitorElement () const
Get the monitor element currently drawn.
DQMRootWidget * getRootWidget () const
Get the embedded root widget.
Protected Attributes
DQMMonitoring * m_pMonitoring
DQMRootWidget * m_pRootWidget
Detailed Description
DQMCanvas class.
Definition at line 46 of file DQMCanvas.h.
Constructor & Destructor Documentation
dqm4hep::DQMCanvas::DQMCanvas (DQMMonitoring * pMonitoring)
Constructor.
Definition at line 36 of file DQMCanvas.cc.
References getMonitoring(), m_pRootWidget, and dqm4hep::DQMRootWidget::setCanvas().
                                               :
    m_pMonitoring(pMonitoring)
{
  m_pRootWidget = new DQMRootWidget(this->getMonitoring());
  m_pRootWidget->setCanvas(this);
  setWidget(m_pRootWidget);
  resize(400, 250);
}
dqm4hep::DQMCanvas::~DQMCanvas () [virtual]
Destructor.
Definition at line 49 of file DQMCanvas.cc.
{
  /* nop */
}
Member Function Documentation
void dqm4hep::DQMCanvas::draw (DQMGuiMonitorElement * pMonitorElement) [slot]
Draw the monitor element on the root widget.
Definition at line 77 of file DQMCanvas.cc.
References dqm4hep::DQMRootWidget::draw(), and m_pRootWidget.
Referenced by dqm4hep::DQMCanvasArea::createCanvas(), and dqm4hep::DQMCanvasArea::draw().
{
  m_pRootWidget->draw(pMonitorElement);
}
DQMGuiMonitorElement * dqm4hep::DQMCanvas::getCurrentMonitorElement () const
Get the monitor element currently drawn.
Definition at line 63 of file DQMCanvas.cc.
References dqm4hep::DQMRootWidget::getCurrentMonitorElement(), and m_pRootWidget.
Referenced by dqm4hep::DQMCanvasArea::getCanvas(), dqm4hep::DQMMonitoringController::saveAs(), and dqm4hep::DQMCanvasView::toXml().
{
  return m_pRootWidget->getCurrentMonitorElement();
}
DQMMonitoring * dqm4hep::DQMCanvas::getMonitoring () const
Get the monitoring instance.
Definition at line 56 of file DQMCanvas.cc.
References m_pMonitoring.
Referenced by DQMCanvas(), and dqm4hep::DQMRootWidget::updateMonitorElement().
{
  return m_pMonitoring;
}
DQMRootWidget * dqm4hep::DQMCanvas::getRootWidget () const
Get the embedded root widget.
Definition at line 70 of file DQMCanvas.cc.
References m_pRootWidget.
Referenced by dqm4hep::DQMMonitoringController::saveAs().
{
  return m_pRootWidget;
}
Member Data Documentation
DQMMonitoring* dqm4hep::DQMCanvas::m_pMonitoring [protected]
Definition at line 78 of file DQMCanvas.h.
Referenced by getMonitoring().
DQMRootWidget* dqm4hep::DQMCanvas::m_pRootWidget [protected]
Definition at line 79 of file DQMCanvas.h.
Referenced by DQMCanvas(), draw(), getCurrentMonitorElement(), and getRootWidget().
The documentation for this class was generated from the following files:
DQMCanvas.h
DQMCanvas.cc