dqm4hep::DQMCanvasArea Class Reference
DQMCanvasArea class.
#include <DQMCanvasArea.h>
Public Slots
DQMCanvas * draw (DQMGuiMonitorElement *pMonitorElement)
Draw the monitor element.
void clear ()
Clear the canvas area.
Public Member Functions
DQMCanvasArea (DQMMonitoring *pMonitoring)
Constructor.
virtual ~DQMCanvasArea ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
bool isDrawn (DQMGuiMonitorElement *pMonitorElement) const
Whether the monitor elemnt is drawn.
bool removeCanvas (DQMCanvas *pCanvas, bool deleteLater=false)
Remove a canvas from the area.
void addCanvas (DQMCanvas *pCanvas)
Add a canvas on the area.
int canvasCount () const
Get the number of drawn canvases.
DQMCanvas * createCanvas (DQMGuiMonitorElement *pMonitorElement)
Create a canvas, add it to the area, draw the monitor element on the root canvas and return it back.
DQMCanvas * getCanvas (DQMGuiMonitorElement *pMonitorElement) const
Get the canvas on which the monitor element is drawn.
DQMCanvas * getCanvas (int index) const
Get canvas at given index.
bool contains (DQMCanvas *pCanvas) const
Whether the area contains the given canvas.
Protected Attributes
DQMMonitoring * m_pMonitoring
Private Member Functions
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
Detailed Description
DQMCanvasArea class.
Definition at line 43 of file DQMCanvasArea.h.
Constructor & Destructor Documentation
dqm4hep::DQMCanvasArea::DQMCanvasArea (DQMMonitoring * pMonitoring)
Constructor.
Definition at line 39 of file DQMCanvasArea.cc.
                                                       :
    m_pMonitoring(pMonitoring)
{
  setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
  setAcceptDrops(true);
}
dqm4hep::DQMCanvasArea::~DQMCanvasArea () [virtual]
Destructor.
Definition at line 48 of file DQMCanvasArea.cc.
{
  /* nop */
}
Member Function Documentation
void dqm4hep::DQMCanvasArea::addCanvas (DQMCanvas * pCanvas)
Add a canvas on the area.
No action performed if the canvas is already own by the area
Definition at line 94 of file DQMCanvasArea.cc.
Referenced by createCanvas(), draw(), and dqm4hep::DQMCanvasView::moveCanvas().
{
  if(NULL == pCanvasToAdd)
    return;
  QList<QMdiSubWindow*> subWindowList = this->subWindowList();
  if(!subWindowList.contains(pCanvasToAdd))
    this->addSubWindow(pCanvasToAdd);
}
int dqm4hep::DQMCanvasArea::canvasCount () const
Get the number of drawn canvases.
Definition at line 191 of file DQMCanvasArea.cc.
Referenced by dqm4hep::DQMCanvasView::toXml().
{
  return subWindowList().count();
}
void dqm4hep::DQMCanvasArea::clear () [slot]
Clear the canvas area.
Definition at line 242 of file DQMCanvasArea.cc.
Referenced by dqm4hep::DQMCanvasView::clearArea().
{
  QList<QMdiSubWindow*> subWindowList = this->subWindowList();
  for(int i=0 ; i<subWindowList.count() ; i++)
  {
    QMdiSubWindow *pSubWindow = subWindowList.at(i);
    this->removeSubWindow(pSubWindow);
    pSubWindow->deleteLater();
  }
}
bool dqm4hep::DQMCanvasArea::contains (DQMCanvas * pCanvas) const
Whether the area contains the given canvas.
Definition at line 168 of file DQMCanvasArea.cc.
Referenced by dqm4hep::DQMCanvasView::moveCanvas().
{
  if(!pCanvas)
    return false;
  QList<QMdiSubWindow*> subWindowList = this->subWindowList();
  for(int i=0 ; subWindowList.count() ; i++)
  {
    DQMCanvas *pSubWindow = (DQMCanvas*) subWindowList.at(i);
    if(!pSubWindow)
      continue;
    if(pSubWindow == pCanvas)
      return true;
  }
  return false;
}
DQMCanvas * dqm4hep::DQMCanvasArea::createCanvas (DQMGuiMonitorElement * pMonitorElement)
Create a canvas, add it to the area, draw the monitor element on the root canvas and return it back.
Definition at line 138 of file DQMCanvasArea.cc.
References addCanvas(), dqm4hep::DQMCanvas::draw(), getCanvas(), and getMonitoring().
Referenced by dqm4hep::DQMCanvasView::fromXml().
{
  // find if this monitor element is drawn an a canvas
  DQMCanvas *pCanvas = this->getCanvas(pMonitorElement);
  if(!pCanvas)
  {
    pCanvas = new DQMCanvas(this->getMonitoring());
    pCanvas->setAttribute(Qt::WA_DeleteOnClose);
    this->addCanvas(pCanvas);
    pCanvas->show();
  }
  pCanvas->show();
  // draw it
  pCanvas->draw(pMonitorElement);
  return pCanvas;
}
void dqm4hep::DQMCanvasArea::dragEnterEvent (QDragEnterEvent * event) [private]
Definition at line 257 of file DQMCanvasArea.cc.
{
  // check mime type
    if (pEvent->mimeData()->hasFormat("dqm4hep/me-item-list"))
      pEvent->acceptProposedAction();
}
DQMCanvas * dqm4hep::DQMCanvasArea::draw (DQMGuiMonitorElement * pMonitorElement) [slot]
Draw the monitor element.
Create a new canvas if not already drawn. Return the canvas on which the element is drawn
Definition at line 198 of file DQMCanvasArea.cc.
References addCanvas(), dqm4hep::DQMCanvas::draw(), getCanvas(), and getMonitoring().
Referenced by dqm4hep::DQMCanvasView::drawInArea(), dqm4hep::DQMCanvasView::drawInCurrentArea(), and dropEvent().
{
  // find if this monitor element is drawn an a canvas
  DQMCanvas *pCanvas = this->getCanvas(pMonitorElement);
  DQMCanvas *pCurrentCanvas = qobject_cast<DQMCanvas *>(this->currentSubWindow());
  bool showMaximized = false;
  bool canvasCreated = false;
  if(NULL != pCurrentCanvas && pCurrentCanvas->isMaximized())
    showMaximized = true;
  // if not, create it
  if(NULL == pCanvas)
  {
    pCanvas = new DQMCanvas(this->getMonitoring());
    pCanvas->setAttribute(Qt::WA_DeleteOnClose);
    this->addCanvas(pCanvas);
    canvasCreated = true;
  }
  if(canvasCreated)
  {
    if(showMaximized)
      pCanvas->showMaximized();
    else
      pCanvas->show();
  }
  else
  {
    if(showMaximized)
      pCanvas->showMaximized();
    else
      this->setActiveSubWindow(pCanvas);
  }
  // draw it
  pCanvas->draw(pMonitorElement);
  return pCanvas;
}
void dqm4hep::DQMCanvasArea::dropEvent (QDropEvent * event) [private]
Definition at line 266 of file DQMCanvasArea.cc.
References draw(), dqm4hep::DQMMonitoringModel::findMonitorElement(), dqm4hep::DQMMonitoring::getController(), dqm4hep::DQMMonitoring::getModel(), getMonitoring(), and dqm4hep::DQMMonitoringController::log().
{
  if(pEvent->proposedAction() != Qt::CopyAction)
    return;
  const QByteArray &byteArray(pEvent->mimeData()->data("dqm4hep/me-item-list"));
  QDataStream dataStream(byteArray);
  qint32 nElements = 0;
  dataStream >> nElements;
  if(nElements == 0)
    return;
  // accept action only if correct type
  // and byte array is not empty
  pEvent->acceptProposedAction();
  int nDrawElements = 0;
  // deserialize the items, query the element
  // to model and draw them on the fly
  for(int i=0 ; i < nElements ; i++)
  {
    QString collectorName;
    QString moduleName;
    QString fullPathName;
    QString monitorElementName;
    dataStream >> collectorName >> moduleName >> fullPathName >> monitorElementName;
    DQMGuiMonitorElement *pMonitorElement =
        this->getMonitoring()->getModel()->findMonitorElement(
            collectorName.toStdString(),
            moduleName.toStdString(),
            fullPathName.toStdString(),
            monitorElementName.toStdString());
    if(!pMonitorElement)
      continue;
    this->draw(pMonitorElement);
    nDrawElements++;
  }
  if(nDrawElements == nElements)
    this->getMonitoring()->getController()->log(MESSAGE, QString("Number of drawn monitor elements : %1").
      arg(nDrawElements).toStdString());
  else if(nDrawElements < nElements && nDrawElements != 0)
    this->getMonitoring()->getController()->log(WARNING, QString("Monitor elements drawn (%1 success, %2
       failed)").arg(nDrawElements).arg(nElements-nDrawElements).toStdString());
  else
    this->getMonitoring()->getController()->log(ERROR, QString("No monitor elements drawn ! (%1 requested)"
      ).arg(nElements).toStdString());
}
DQMCanvas * dqm4hep::DQMCanvasArea::getCanvas (DQMGuiMonitorElement * pMonitorElement) const
Get the canvas on which the monitor element is drawn.
Definition at line 107 of file DQMCanvasArea.cc.
References dqm4hep::DQMGuiMonitorElement::equals(), and dqm4hep::DQMCanvas::getCurrentMonitorElement().
Referenced by createCanvas(), draw(), isDrawn(), and dqm4hep::DQMCanvasView::toXml().
{
  if(NULL == pMonitorElement)
    return NULL;
  QList<QMdiSubWindow*> subWindowList = this->subWindowList();
  for(int i=0 ; i<subWindowList.count() ; i++)
  {
    DQMCanvas *pCanvas = (DQMCanvas *) subWindowList.at(i);
    if(!pCanvas)
      continue;
    DQMGuiMonitorElement *pCurrentMonitorElement = pCanvas->getCurrentMonitorElement();
    if(NULL == pCurrentMonitorElement)
      continue;
    if(pMonitorElement == pCurrentMonitorElement)
      return pCanvas;
    if(pMonitorElement->equals(pCurrentMonitorElement))
      return pCanvas;
  }
  return NULL;
}
DQMCanvas * dqm4hep::DQMCanvasArea::getCanvas (int index) const
Get canvas at given index.
Definition at line 161 of file DQMCanvasArea.cc.
{
  return (DQMCanvas *) this->subWindowList().at(index);
}
DQMMonitoring * dqm4hep::DQMCanvasArea::getMonitoring () const
Get the monitoring instance.
Definition at line 55 of file DQMCanvasArea.cc.
References m_pMonitoring.
Referenced by createCanvas(), draw(), and dropEvent().
{
  return m_pMonitoring;
}
bool dqm4hep::DQMCanvasArea::isDrawn (DQMGuiMonitorElement * pMonitorElement) const
Whether the monitor elemnt is drawn.
Comparison done by ptr or full name (path + name)
Definition at line 62 of file DQMCanvasArea.cc.
References getCanvas().
{
  return (NULL == this->getCanvas(pMonitorElement));
}
bool dqm4hep::DQMCanvasArea::removeCanvas (DQMCanvas * pCanvas, bool deleteLater = false)
Remove a canvas from the area.
The canvas is not deleted. No action performed if the area does not own the canvas Return whether the canvas has been removed
Definition at line 69 of file DQMCanvasArea.cc.
Referenced by dqm4hep::DQMCanvasView::moveCanvas(), and dqm4hep::DQMRootWidget::removeCanvas().
{
  if(NULL == pCanvasToRemove)
    return false;
  QList<QMdiSubWindow*> subWindowList = this->subWindowList();
  for(int i=0 ; subWindowList.count() ; i++)
  {
    if(pCanvasToRemove == subWindowList.at(i))
    {
      this->removeSubWindow(pCanvasToRemove);
      if(deleteLater)
        pCanvasToRemove->deleteLater();
      return true;
    }
  }
  return false;
}
Member Data Documentation
DQMMonitoring* dqm4hep::DQMCanvasArea::m_pMonitoring [protected]
Definition at line 118 of file DQMCanvasArea.h.
Referenced by getMonitoring().
The documentation for this class was generated from the following files:
DQMCanvasArea.h
DQMCanvasArea.cc