dqm4hep::DQMLoggerWidget Class Reference
DQMLoggerWidget class.
#include <DQMLoggerWidget.h>
Public Member Functions
DQMLoggerWidget (QWidget *pParent=0)
Constructor.
void log (const std::string &message)
Log a message with the default level (MESSAGE)
void log (LogLevel level, const std::string &message)
Log a message with a log level.
Private Member Functions
Qt::GlobalColor getColor (LogLevel level) const
std::string getLogMessageHead (LogLevel level) const
Private Attributes
QTextEdit * m_pLoggingWidget
the text widget used for logging
Detailed Description
DQMLoggerWidget class.
Definition at line 46 of file DQMLoggerWidget.h.
Constructor & Destructor Documentation
dqm4hep::DQMLoggerWidget::DQMLoggerWidget (QWidget * pParent = 0)
Constructor.
Definition at line 38 of file DQMLoggerWidget.cc.
References m_pLoggingWidget.
                                                 :
    QGroupBox("Logging", pParent)
{
  setMaximumHeight(200);
  QHBoxLayout *pLoggingLayout = new QHBoxLayout();
  setLayout(pLoggingLayout);
  m_pLoggingWidget = new QTextEdit();
  m_pLoggingWidget->setReadOnly(true);
  pLoggingLayout->addWidget(m_pLoggingWidget);
}
Member Function Documentation
Qt::GlobalColor dqm4hep::DQMLoggerWidget::getColor (LogLevel level) const [private]
Definition at line 85 of file DQMLoggerWidget.cc.
Referenced by log().
{
  switch (level)
  {
  case DEBUG :
    return Qt::darkBlue;
  case MESSAGE :
    return Qt::darkGreen;
  case WARNING :
    return Qt::darkYellow;
  case ERROR :
    return Qt::darkRed;
  default:
    return Qt::black;
  }
}
std::string dqm4hep::DQMLoggerWidget::getLogMessageHead (LogLevel level) const [private]
Definition at line 104 of file DQMLoggerWidget.cc.
Referenced by log().
{
  switch (level)
  {
  case DEBUG :
    return "[DEBUG] ";
  case MESSAGE :
    return "[MESSAGE] ";
  case WARNING :
    return "[WARNING] ";
  case ERROR :
    return "[ERROR] ";
  default:
    return "";
  }
}
void dqm4hep::DQMLoggerWidget::log (const std::string & message)
Log a message with the default level (MESSAGE)
Definition at line 53 of file DQMLoggerWidget.cc.
{
  log(MESSAGE, message);
}
void dqm4hep::DQMLoggerWidget::log (LogLevel level, const std::string & message)
Log a message with a log level.
Definition at line 60 of file DQMLoggerWidget.cc.
References getColor(), getLogMessageHead(), and m_pLoggingWidget.
{
  Qt::GlobalColor color = getColor(level);
  QString messageHead(getLogMessageHead(level).c_str());
  // scroll to the end of text edit
  m_pLoggingWidget->horizontalScrollBar()->setValue(m_pLoggingWidget->horizontalScrollBar()->maximum());
  // set the cursor at the end
  QTextCursor cursor = m_pLoggingWidget->textCursor();
  cursor.movePosition(QTextCursor::End, QTextCursor::MoveAnchor);
  m_pLoggingWidget->setTextCursor(cursor);
  // put the message
  m_pLoggingWidget->setTextColor(QColor(color));
  m_pLoggingWidget->insertPlainText(messageHead);
  m_pLoggingWidget->setTextColor(QColor(Qt::black));
  m_pLoggingWidget->insertPlainText(" ");
  m_pLoggingWidget->insertPlainText(QString(message.c_str()));
  m_pLoggingWidget->insertPlainText("\n");
}
Member Data Documentation
QTextEdit* dqm4hep::DQMLoggerWidget::m_pLoggingWidget [private]
the text widget used for logging
Definition at line 66 of file DQMLoggerWidget.h.
Referenced by DQMLoggerWidget(), and log().
The documentation for this class was generated from the following files:
DQMLoggerWidget.h
DQMLoggerWidget.cc