dqm4hep::DQMMonitorElementNavigator Class Reference
DQMMonitorElementNavigator class.
#include <DQMMonitorElementView.h>
Public Types
enum ItemType { DIRECTORY_ITEM = 1,
MONITOR_ELEMENT_ITEM = 2
 }
ItemType enumerator.
Public Slots
void checkAllMonitorElements ()
Check all monitor element items.
void uncheckAllMonitorElements ()
Uncheck all monitor element items.
void checkSelectedMonitorElements ()
Check selected monitor element items.
void uncheckSelectedMonitorElements ()
Uncheck selected monitor element items.
Public Member Functions
DQMMonitorElementNavigator (const QString &collectorName, DQMMonitoring *pMonitoring, QWidget *pParent=0)
Constructor.
~DQMMonitorElementNavigator ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
const QString & getCollectorName () const
Get the collector name.
QStringList getModuleNames () const
Get the module name list.
QTreeWidgetItem * mkdir (const QString &moduleName)
Create a directory and return the directory.
QTreeWidgetItem * mkdir (const QString &moduleName, const QString &fullPathDirName)
Create a directory and return the directory.
bool rmdir (const QString &moduleName)
Remove the directory.
bool rmdir (const QString &moduleName, const QString &fullPathDirName)
Remove the directory.
bool dirExists (const QString &moduleName)
Whether the directory exists.
bool dirExists (const QString &moduleName, const QString &fullPathDirName)
Whether the directory exists.
void clear ()
Clear the tree structure.
void updateMonitorElement (DQMGuiMonitorElement *pMonitorElement)
Create an entry (if doesn't exists) from the monitor element.
void updateMonitorElements (const DQMGuiMonitorElementList &monitorElementList)
Create an entry (if doesn't exists) for each of the monitor elements.
void removeMonitorElement (DQMGuiMonitorElement *pMonitorElement)
Remove the monitor element from the tree widget.
QTreeWidgetItem * addMonitorElement (QTreeWidgetItem *pTreeItem, const QString &name)
Add a monitor element item and set pTreeItem as its parent item.
QString getFullPathName (QTreeWidgetItem *pTreeItem) const
Get the full path name of the tree item.
QString getModuleName (QTreeWidgetItem *pTreeItem) const
Get the module name of the tree item.
bool isDirectoryItem (QTreeWidgetItem *pTreeItem) const
Whether the tree item is a directory.
bool isMonitorElementItem (QTreeWidgetItem *pTreeItem) const
Whether the tree item is a monitor element item.
QList< QTreeWidgetItem * > getSelectedMonitorElementItems () const
Get the selected monitor element items.
QList< QTreeWidgetItem * > getSelectedDirectoryItems () const
Get the selected directory items.
QList< QTreeWidgetItem * > getCheckedMonitorElements () const
Get the checked monitor element items.
QList< QTreeWidgetItem * > getAllMonitorElementItems (const QString &moduleName) const
Get all monitor element items for a given module.
void enableSubscription (bool enable=true)
Enable/Disable subscription for each element.
Private Slots
void showContextMenu (const QPoint &point)
void drawSelectedMonitorElements ()
void handleItemDoubleClick (QTreeWidgetItem *pTreeWidgetItem, int column)
void handleItemExpanded (QTreeWidgetItem *pTreeWidgetItem)
void handleItemCollapsed (QTreeWidgetItem *pTreeWidgetItem)
void startDrag ()
void queryUpdate ()
Private Member Functions
QTreeWidgetItem * mkdir (QTreeWidgetItem *pTreeItem, const QString &dirName)
Create a directory and set pTreeItem as parent item.
bool dirExists (QTreeWidgetItem *pTreeItem, const QString &name) const
void clear (QTreeWidgetItem *pTreeItem) const
void getRecursiveMonitorElements (QTreeWidgetItem *pTreeItem, QList< QTreeWidgetItem * > &monitorElementItems, bool onlyChecked=false) const
void keyPressEvent (QKeyEvent *pKeyEvent)
void mousePressEvent (QMouseEvent *pMouseEvent)
Private Attributes
DQMMonitoring * m_pMonitoring
QString m_collectorName
QList< QTreeWidgetItem * > m_dragItemList
bool m_subscriptionEnabled
Detailed Description
DQMMonitorElementNavigator class.
Definition at line 47 of file DQMMonitorElementView.h.
Member Enumeration Documentation
enum dqm4hep::DQMMonitorElementNavigator::ItemType
ItemType enumerator.
Enumerator
DIRECTORY_ITEM
MONITOR_ELEMENT_ITEM
Definition at line 54 of file DQMMonitorElementView.h.
  {
    DIRECTORY_ITEM = 1,
    MONITOR_ELEMENT_ITEM = 2
  };
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElementNavigator::DQMMonitorElementNavigator (const QString & collectorName, DQMMonitoring * pMonitoring, QWidget * pParent = 0)
Constructor.
Definition at line 177 of file DQMMonitorElementView.cc.
References handleItemCollapsed(), handleItemDoubleClick(), handleItemExpanded(), and showContextMenu().
                                                                                                           
                            :
    m_collectorName(collectorName),
    QTreeWidget(pParent),
    m_pMonitoring(pMonitoring),
    m_subscriptionEnabled(true)
{
  setHeaderLabel("Monitor elements");
  setContextMenuPolicy(Qt::CustomContextMenu);
  setSelectionMode(QAbstractItemView::ExtendedSelection);
  setSelectionBehavior(QAbstractItemView::SelectRows);
  setFocusPolicy(Qt::StrongFocus);
  connect(this, SIGNAL(customContextMenuRequested(const QPoint &)),
      this, SLOT(showContextMenu(const QPoint &)));
    connect(this, SIGNAL(itemDoubleClicked(QTreeWidgetItem *, int)),
            this, SLOT(handleItemDoubleClick(QTreeWidgetItem *, int)));
    connect(this, SIGNAL(itemExpanded(QTreeWidgetItem *)),
        this, SLOT(handleItemExpanded(QTreeWidgetItem *)));
    connect(this, SIGNAL(itemCollapsed(QTreeWidgetItem *)),
        this, SLOT(handleItemCollapsed(QTreeWidgetItem *)));
}
dqm4hep::DQMMonitorElementNavigator::~DQMMonitorElementNavigator ()
Destructor.
Definition at line 206 of file DQMMonitorElementView.cc.
{
  /* nop */
}
Member Function Documentation
QTreeWidgetItem * dqm4hep::DQMMonitorElementNavigator::addMonitorElement (QTreeWidgetItem * pTreeItem, const QString & name)
Add a monitor element item and set pTreeItem as its parent item.
If the monitor element item already exists in child items of pTreeItem, it is not created.
Returns the created/existing monitor element item
Definition at line 711 of file DQMMonitorElementView.cc.
References isDirectoryItem(), isMonitorElementItem(), m_subscriptionEnabled, MONITOR_ELEMENT_ITEM, dqm4hep::TreeWidgetItem::setCheckable(), and dqm4hep::TreeWidgetItem::setData().
Referenced by dqm4hep::DQMMonitorElementView::fromXml(), and updateMonitorElement().
{
  if(!this->isDirectoryItem(pTreeItem))
    return 0;
  for(int i=0 ; i<pTreeItem->childCount() ; i++)
  {
    if(name == pTreeItem->child(i)->text(0) && this->isMonitorElementItem(pTreeItem->child(i)))
      return pTreeItem->child(i);
  }
  TreeWidgetItem *pMonitorElementItem = new TreeWidgetItem(pTreeItem);
  pMonitorElementItem->setText(0, name);
  pMonitorElementItem->setData(0, Qt::UserRole, static_cast<int>(
      MONITOR_ELEMENT_ITEM));
  pMonitorElementItem->setCheckState(0, Qt::Unchecked);
  pMonitorElementItem->setCheckable(m_subscriptionEnabled);
  pTreeItem->addChild(pMonitorElementItem);
  return pMonitorElementItem;
}
void dqm4hep::DQMMonitorElementNavigator::checkAllMonitorElements () [slot]
Check all monitor element items.
Definition at line 592 of file DQMMonitorElementView.cc.
References getRecursiveMonitorElements().
Referenced by showContextMenu().
{
  for(int i=0 ; i<topLevelItemCount() ; i++)
  {
    QTreeWidgetItem *pModuleItem = topLevelItem(i);
    QList<QTreeWidgetItem*> uncheckedMonitorElements;
    this->getRecursiveMonitorElements(pModuleItem, uncheckedMonitorElements, false);
    for(int j=0 ; j<uncheckedMonitorElements.count() ; j++)
      uncheckedMonitorElements.at(j)->setCheckState(0, Qt::Checked);
  }
}
void dqm4hep::DQMMonitorElementNavigator::checkSelectedMonitorElements () [slot]
Check selected monitor element items.
Definition at line 624 of file DQMMonitorElementView.cc.
References getRecursiveMonitorElements(), and isDirectoryItem().
Referenced by showContextMenu().
{
  // Handle selected items instead of only the current item
  QList<QTreeWidgetItem *> selectedItems = this->selectedItems();
  QSet<QTreeWidgetItem *> monitorElementItems;
  // first, get all monitor elements
  for(int i = 0; i < selectedItems.count(); i++)
  {
    QTreeWidgetItem *pTreeWidgetItem = selectedItems.at(i);
    if(this->isDirectoryItem(pTreeWidgetItem))
    {
      QList<QTreeWidgetItem *> monitorElementItemList;
      this->getRecursiveMonitorElements(pTreeWidgetItem, monitorElementItemList, false);
      monitorElementItems += QSet<QTreeWidgetItem *>::fromList(monitorElementItemList);
    }
    else
      monitorElementItems << pTreeWidgetItem;
  }
  QSet<QTreeWidgetItem*>::iterator iter = monitorElementItems.begin();
  while(iter != monitorElementItems.end())
  {
    QTreeWidgetItem *pTreeWidgetItem = *iter;
    pTreeWidgetItem->setCheckState(0, Qt::Checked);
    ++iter;
  }
}
void dqm4hep::DQMMonitorElementNavigator::clear ()
Clear the tree structure.
Definition at line 371 of file DQMMonitorElementView.cc.
Referenced by clear(), dqm4hep::DQMMonitorElementView::clear(), and rmdir().
{
  while(this->topLevelItemCount() != 0)
  {
    QTreeWidgetItem *pTopLevelItem = this->topLevelItem(0);
    this->clear(pTopLevelItem);
    delete this->takeTopLevelItem(0);
  }
}
void dqm4hep::DQMMonitorElementNavigator::clear (QTreeWidgetItem * pTreeItem) const [private]
Definition at line 747 of file DQMMonitorElementView.cc.
References clear().
{
  NOTIFY_METHOD_CALLED
  while(pTreeItem->childCount() != 0)
  {
    QTreeWidgetItem *pChildItem = pTreeItem->child(0);
    this->clear(pChildItem);
    pTreeItem->removeChild(0);
    delete pChildItem;
  }
}
bool dqm4hep::DQMMonitorElementNavigator::dirExists (const QString & moduleName)
Whether the directory exists.
Definition at line 318 of file DQMMonitorElementView.cc.
Referenced by dirExists(), removeMonitorElement(), and rmdir().
{
  QTreeWidgetItem *pModuleDirectoryItem = NULL;
  for(int i=0 ; i<topLevelItemCount() ; i++)
  {
    if(moduleName == this->topLevelItem(i)->text(0))
    {
      pModuleDirectoryItem = this->topLevelItem(i);
      break;
    }
  }
  return (NULL != pModuleDirectoryItem);
}
bool dqm4hep::DQMMonitorElementNavigator::dirExists (const QString & moduleName, const QString & fullPathDirName)
Whether the directory exists.
Definition at line 336 of file DQMMonitorElementView.cc.
References dirExists(), and mkdir().
{
  QTreeWidgetItem *pModuleDirectoryItem = NULL;
  for(int i=0 ; i<topLevelItemCount() ; i++)
  {
    if(moduleName == this->topLevelItem(i)->text(0))
    {
      pModuleDirectoryItem = this->topLevelItem(i);
      break;
    }
  }
  if(NULL == pModuleDirectoryItem)
    return false;
  std::string path = fullPathDirName.toStdString();
  std::vector<std::string> tokens;
  DQM4HEP::tokenize(path, tokens, "/");
  QTreeWidgetItem *pCurrentDirectory = pModuleDirectoryItem;
  for(unsigned int i=0 ; i<tokens.size() ; i++)
  {
    if(this->dirExists(pCurrentDirectory, tokens.at(i).c_str()))
      pCurrentDirectory = this->mkdir(pCurrentDirectory, tokens.at(i).c_str());
    else
      return false;
  }
  return true;
}
bool dqm4hep::DQMMonitorElementNavigator::dirExists (QTreeWidgetItem * pTreeItem, const QString & name) const [private]
Definition at line 734 of file DQMMonitorElementView.cc.
References isMonitorElementItem().
{
  for(int i=0 ; i<pTreeItem->childCount() ; i++)
  {
    if(name == pTreeItem->child(i)->text(0) && this->isMonitorElementItem(pTreeItem->child(i)))
      return true;
  }
  return false;
}
void dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements () [private], [slot]
Definition at line 842 of file DQMMonitorElementView.cc.
References dqm4hep::DQMCanvasView::canvasAreaCount(), dqm4hep::DQMCanvasView::createCanvasAreaAndSetCurrent(), dqm4hep::DQMCanvasView::drawInArea(), dqm4hep::DQMMonitoringModel::findMonitorElement(), dqm4hep::DQMMonitoringView::getCanvasView(), getCollectorName(), dqm4hep::DQMMonitoring::getController(), getFullPathName(), dqm4hep::DQMMonitoring::getModel(), getModuleName(), getMonitoring(), getSelectedMonitorElementItems(), dqm4hep::DQMMonitoring::getView(), and dqm4hep::DQMMonitoringController::log().
Referenced by showContextMenu().
{
  QAction *pAction = qobject_cast<QAction*>(sender());
  if(!pAction)
    return;
  int areaIndex = pAction->data().toInt();
  QList<QTreeWidgetItem*> selectedMonitorElements(this->
      getSelectedMonitorElementItems());
  DQMCanvasView *pCanvasView = this->getMonitoring()->getView()->getCanvasView();
  if(areaIndex < 0)
  {
    pCanvasView->createCanvasAreaAndSetCurrent();
    areaIndex = pCanvasView->canvasAreaCount()-1;
  }
  if(areaIndex > pCanvasView->canvasAreaCount()-1)
  {
    this->getMonitoring()->getController()->log(ERROR, QString("Canvas area not found ! (index = %1)").arg(
      areaIndex).toStdString());
    return;
  }
  int nDrawElements = 0;
  for(int i=0 ; i<selectedMonitorElements.count() ; i++)
  {
    QTreeWidgetItem *pMonitorElementItem = selectedMonitorElements.at(i);
    QString collectorName(this->getCollectorName());
    QString moduleName(this->getModuleName(pMonitorElementItem));
    QString fullPathName(this->getFullPathName(pMonitorElementItem));
    QString monitorElementName(pMonitorElementItem->text(0));
    DQMGuiMonitorElement *pMonitorElement =
        this->getMonitoring()->getModel()->findMonitorElement(
            collectorName.toStdString(),
            moduleName.toStdString(),
            fullPathName.toStdString(),
            monitorElementName.toStdString());
    if(!pMonitorElement)
      continue;
    pCanvasView->drawInArea(pMonitorElement, areaIndex);
    nDrawElements++;
  }
  if(nDrawElements == selectedMonitorElements.count())
  {
    this->getMonitoring()->getController()->log(MESSAGE, QString("Number of drawn monitor elements : %1").
      arg(nDrawElements).toStdString());
  }
  else if(nDrawElements < selectedMonitorElements.count() && nDrawElements != 0)
  {
    this->getMonitoring()->getController()->log(WARNING, QString("Monitor elements drawn (%1 success, %2
       failed)").arg(nDrawElements).arg(selectedMonitorElements.count()-nDrawElements).toStdString());
  }
  else
  {
    this->getMonitoring()->getController()->log(ERROR, QString("No monitor elements drawn ! (%1 requested)"
      ).arg(selectedMonitorElements.count()).toStdString());
  }
}
void dqm4hep::DQMMonitorElementNavigator::enableSubscription (bool enable = true)
Enable/Disable subscription for each element.
Definition at line 570 of file DQMMonitorElementView.cc.
References getRecursiveMonitorElements(), m_subscriptionEnabled, and dqm4hep::TreeWidgetItem::setCheckable().
Referenced by dqm4hep::DQMMonitorElementView::enableSubscription().
{
  if(m_subscriptionEnabled == enable)
    return;
  m_subscriptionEnabled = enable;
  for(int i=0 ; i<topLevelItemCount() ; i++)
  {
    QList<QTreeWidgetItem*> monitorElementItems;
    this->getRecursiveMonitorElements(this->topLevelItem(i), monitorElementItems, false);
    for(int j=0 ; j<monitorElementItems.size() ; j++)
    {
      TreeWidgetItem *pMonitorElementItem = dynamic_cast<TreeWidgetItem *>(monitorElementItems.at(j));
      pMonitorElementItem->setCheckable(m_subscriptionEnabled);
    }
  }
}
QList< QTreeWidgetItem * > dqm4hep::DQMMonitorElementNavigator::getAllMonitorElementItems (const QString & moduleName) const
Get all monitor element items for a given module.
Definition at line 552 of file DQMMonitorElementView.cc.
References getRecursiveMonitorElements().
Referenced by dqm4hep::DQMMonitorElementView::toXml().
{
  QList<QTreeWidgetItem*> monitorElementItems;
  for(int i=0 ; i<topLevelItemCount() ; i++)
  {
    if(this->topLevelItem(i)->text(0) == moduleName)
    {
      this->getRecursiveMonitorElements(this->topLevelItem(i), monitorElementItems, false);
      break;
    }
  }
  return monitorElementItems;
}
QList< QTreeWidgetItem * > dqm4hep::DQMMonitorElementNavigator::getCheckedMonitorElements () const
Get the checked monitor element items.
Definition at line 537 of file DQMMonitorElementView.cc.
References getRecursiveMonitorElements().
Referenced by dqm4hep::DQMMonitorElementView::getCheckedMonitorElements().
{
  QList<QTreeWidgetItem*> checkedMonitorElements;
  for(int i=0 ; i<topLevelItemCount() ; i++)
  {
    QTreeWidgetItem *pModuleItem = topLevelItem(i);
    this->getRecursiveMonitorElements(pModuleItem, checkedMonitorElements, true);
  }
  return checkedMonitorElements;
}
const QString & dqm4hep::DQMMonitorElementNavigator::getCollectorName () const
Get the collector name.
Definition at line 220 of file DQMMonitorElementView.cc.
References m_collectorName.
Referenced by drawSelectedMonitorElements(), handleItemDoubleClick(), keyPressEvent(), queryUpdate(), dqm4hep::TreeWidgetItem::setData(), and startDrag().
{
  return m_collectorName;
}
QString dqm4hep::DQMMonitorElementNavigator::getFullPathName (QTreeWidgetItem * pTreeItem) const
Get the full path name of the tree item.
Can be a monitor element item or a simple directory
Definition at line 435 of file DQMMonitorElementView.cc.
References isMonitorElementItem().
Referenced by drawSelectedMonitorElements(), handleItemDoubleClick(), dqm4hep::DQMMonitoringController::handleServerStartup(), keyPressEvent(), queryUpdate(), dqm4hep::TreeWidgetItem::setData(), startDrag(), and dqm4hep::DQMMonitorElementView::toXml().
{
  if(!pTreeItem)
    return QString();
  // "/mod/dir1/dir2"
  // "/"
  // "/mod"
  QString fullPathName;
  QTreeWidgetItem *pCurrentItem = pTreeItem;
  // do not put the me name in the full path
  if(this->isMonitorElementItem(pTreeItem))
    pCurrentItem = pCurrentItem->parent();
  while(1)
  {
    bool isTopLevelItem = (pCurrentItem->parent() == 0);
    if(isTopLevelItem)
      break;
    fullPathName = pCurrentItem->text(0) + "/" + fullPathName;
    pCurrentItem = pCurrentItem->parent();
  }
  fullPathName = "/" + fullPathName;
  return fullPathName;
}
QString dqm4hep::DQMMonitorElementNavigator::getModuleName (QTreeWidgetItem * pTreeItem) const
Get the module name of the tree item.
Definition at line 469 of file DQMMonitorElementView.cc.
Referenced by drawSelectedMonitorElements(), handleItemDoubleClick(), dqm4hep::DQMMonitoringController::handleServerStartup(), keyPressEvent(), queryUpdate(), dqm4hep::TreeWidgetItem::setData(), and startDrag().
{
  if(!pTreeItem)
    return QString();
  QTreeWidgetItem *pCurrentItem = pTreeItem;
  while(1)
  {
    pCurrentItem = pCurrentItem->parent();
    bool isTopLevelItem = (pCurrentItem->parent() == 0);
    if(isTopLevelItem)
      break;
  }
  return pCurrentItem->text(0);
}
QStringList dqm4hep::DQMMonitorElementNavigator::getModuleNames () const
Get the module name list.
Definition at line 227 of file DQMMonitorElementView.cc.
Referenced by dqm4hep::DQMMonitorElementView::toXml().
{
  QStringList moduleNameList;
  for(int i=0 ; i<topLevelItemCount() ; i++)
    moduleNameList << this->topLevelItem(i)->text(0);
  return moduleNameList;
}
DQMMonitoring * dqm4hep::DQMMonitorElementNavigator::getMonitoring () const
Get the monitoring instance.
Definition at line 213 of file DQMMonitorElementView.cc.
References m_pMonitoring.
Referenced by drawSelectedMonitorElements(), handleItemDoubleClick(), keyPressEvent(), queryUpdate(), dqm4hep::TreeWidgetItem::setData(), showContextMenu(), startDrag(), and updateMonitorElement().
{
  return m_pMonitoring;
}
void dqm4hep::DQMMonitorElementNavigator::getRecursiveMonitorElements (QTreeWidgetItem * pTreeItem, QList< QTreeWidgetItem * > & monitorElementItems, bool onlyChecked = false) const [private]
Definition at line 764 of file DQMMonitorElementView.cc.
References isDirectoryItem(), and isMonitorElementItem().
Referenced by checkAllMonitorElements(), checkSelectedMonitorElements(), enableSubscription(), getAllMonitorElementItems(), getCheckedMonitorElements(), keyPressEvent(), mousePressEvent(), uncheckAllMonitorElements(), and uncheckSelectedMonitorElements().
{
  for(int i=0 ; i<pTreeItem->childCount() ; i++)
  {
    if(this->isMonitorElementItem(pTreeItem->child(i)))
    {
      if(onlyChecked && pTreeItem->child(i)->checkState(0) != Qt::Checked)
        continue;
      monitorElementItems.append(pTreeItem->child(i));
    }
    else if(this->isDirectoryItem(pTreeItem->child(i)))
    {
      this->getRecursiveMonitorElements(pTreeItem->child(i), monitorElementItems, onlyChecked);
    }
  }
}
QList< QTreeWidgetItem * > dqm4hep::DQMMonitorElementNavigator::getSelectedDirectoryItems () const
Get the selected directory items.
Definition at line 521 of file DQMMonitorElementView.cc.
References isDirectoryItem().
{
  QList<QTreeWidgetItem*> selectedItems = this->selectedItems();
  QList<QTreeWidgetItem*> selectedDirectoryItems;
  for(int i=0 ; i<selectedItems.count() ; i++)
  {
    if(this->isDirectoryItem(selectedItems.at(i)))
      selectedDirectoryItems.append(selectedItems.at(i));
  }
  return selectedDirectoryItems;
}
QList< QTreeWidgetItem * > dqm4hep::DQMMonitorElementNavigator::getSelectedMonitorElementItems () const
Get the selected monitor element items.
Definition at line 505 of file DQMMonitorElementView.cc.
References isMonitorElementItem().
Referenced by drawSelectedMonitorElements(), handleItemDoubleClick(), and queryUpdate().
{
  QList<QTreeWidgetItem*> selectedItems = this->selectedItems();
  QList<QTreeWidgetItem*> selectedMonitorElementItems;
  for(int i=0 ; i<selectedItems.count() ; i++)
  {
    if(this->isMonitorElementItem(selectedItems.at(i)))
      selectedMonitorElementItems.append(selectedItems.at(i));
  }
  return selectedMonitorElementItems;
}
void dqm4hep::DQMMonitorElementNavigator::handleItemCollapsed (QTreeWidgetItem * pTreeWidgetItem) [private], [slot]
Definition at line 1092 of file DQMMonitorElementView.cc.
References isDirectoryItem().
Referenced by DQMMonitorElementNavigator().
{
  if(this->isDirectoryItem(pTreeWidgetItem))
  {
    QCommonStyle style;
    pTreeWidgetItem->setIcon(0, style.standardIcon(QStyle::SP_DirClosedIcon));
  }
}
void dqm4hep::DQMMonitorElementNavigator::handleItemDoubleClick (QTreeWidgetItem * pTreeWidgetItem, int column) [private], [slot]
Definition at line 906 of file DQMMonitorElementView.cc.
References dqm4hep::DQMCanvasView::drawInCurrentArea(), dqm4hep::DQMMonitoringModel::findMonitorElement(), dqm4hep::DQMMonitoringView::getCanvasView(), getCollectorName(), dqm4hep::DQMMonitoring::getController(), getFullPathName(), dqm4hep::DQMMonitoring::getModel(), getModuleName(), getMonitoring(), getSelectedMonitorElementItems(), dqm4hep::DQMMonitoring::getView(), isMonitorElementItem(), and dqm4hep::DQMMonitoringController::log().
Referenced by DQMMonitorElementNavigator().
{
  if(!this->isMonitorElementItem(pTreeWidgetItem))
    return;
  QList<QTreeWidgetItem*> selectedMonitorElements(this->
      getSelectedMonitorElementItems());
    DQMCanvasView *pCanvasView = this->getMonitoring()->getView()->getCanvasView();
  int nDrawElements = 0;
  for(int i=0 ; i<selectedMonitorElements.count() ; i++)
  {
    QTreeWidgetItem *pMonitorElementItem = selectedMonitorElements.at(i);
    QString collectorName(this->getCollectorName());
    QString moduleName(this->getModuleName(pMonitorElementItem));
    QString fullPathName(this->getFullPathName(pMonitorElementItem));
    QString monitorElementName(pMonitorElementItem->text(0));
    DQMGuiMonitorElement *pMonitorElement =
        this->getMonitoring()->getModel()->findMonitorElement(
            collectorName.toStdString(),
            moduleName.toStdString(),
            fullPathName.toStdString(),
            monitorElementName.toStdString());
    if(!pMonitorElement)
      continue;
    pCanvasView->drawInCurrentArea(pMonitorElement);
    pMonitorElementItem->setCheckState(0, Qt::Checked);
    nDrawElements++;
  }
  if(nDrawElements == selectedMonitorElements.count())
  {
    this->getMonitoring()->getController()->log(MESSAGE, QString("Number of drawn monitor elements : %1").
      arg(nDrawElements).toStdString());
  }
  else if(nDrawElements < selectedMonitorElements.count() && nDrawElements != 0)
  {
    this->getMonitoring()->getController()->log(WARNING, QString("Monitor elements drawn (%1 success, %2
       failed)").arg(nDrawElements).arg(selectedMonitorElements.count()-nDrawElements).toStdString());
  }
  else
  {
    this->getMonitoring()->getController()->log(ERROR, QString("No monitor elements drawn ! (%1 requested)"
      ).arg(selectedMonitorElements.count()).toStdString());
  }
}
void dqm4hep::DQMMonitorElementNavigator::handleItemExpanded (QTreeWidgetItem * pTreeWidgetItem) [private], [slot]
Definition at line 1081 of file DQMMonitorElementView.cc.
References isDirectoryItem().
Referenced by DQMMonitorElementNavigator().
{
  if(this->isDirectoryItem(pTreeWidgetItem))
  {
    QCommonStyle style;
    pTreeWidgetItem->setIcon(0, style.standardIcon(QStyle::SP_DirOpenIcon));
  }
}
bool dqm4hep::DQMMonitorElementNavigator::isDirectoryItem (QTreeWidgetItem * pTreeItem) const
Whether the tree item is a directory.
Definition at line 491 of file DQMMonitorElementView.cc.
References DIRECTORY_ITEM.
Referenced by addMonitorElement(), checkSelectedMonitorElements(), getRecursiveMonitorElements(), getSelectedDirectoryItems(), handleItemCollapsed(), handleItemExpanded(), keyPressEvent(), mkdir(), mousePressEvent(), and uncheckSelectedMonitorElements().
{
  return (pTreeItem->data(0, Qt::UserRole).toInt() == DIRECTORY_ITEM);
}
bool dqm4hep::DQMMonitorElementNavigator::isMonitorElementItem (QTreeWidgetItem * pTreeItem) const
Whether the tree item is a monitor element item.
Definition at line 498 of file DQMMonitorElementView.cc.
References MONITOR_ELEMENT_ITEM.
Referenced by addMonitorElement(), dirExists(), getFullPathName(), getRecursiveMonitorElements(), getSelectedMonitorElementItems(), handleItemDoubleClick(), removeMonitorElement(), and dqm4hep::TreeWidgetItem::setData().
{
  return (pTreeItem->data(0, Qt::UserRole).toInt() == MONITOR_ELEMENT_ITEM);
}
void dqm4hep::DQMMonitorElementNavigator::keyPressEvent (QKeyEvent * pKeyEvent) [private]
Definition at line 957 of file DQMMonitorElementView.cc.
References dqm4hep::DQMCanvasView::drawInCurrentArea(), dqm4hep::DQMMonitoringModel::findMonitorElement(), dqm4hep::DQMMonitoringView::getCanvasView(), getCollectorName(), getFullPathName(), dqm4hep::DQMMonitoring::getModel(), getModuleName(), getMonitoring(), getRecursiveMonitorElements(), dqm4hep::DQMMonitoring::getView(), and isDirectoryItem().
{
    if(pKeyEvent->key() == Qt::Key_Space || pKeyEvent->key() == Qt::Key_Return)
    {
    // Handle selected items instead of only the current item
    QList<QTreeWidgetItem *> selectedItems = this->selectedItems();
    QSet<QTreeWidgetItem *> monitorElementItems;
    // first, get all monitor elements
    for(int i = 0; i < selectedItems.count(); i++)
    {
      QTreeWidgetItem *pTreeWidgetItem = selectedItems.at(i);
      if(this->isDirectoryItem(pTreeWidgetItem))
      {
        QList<QTreeWidgetItem *> monitorElementItemList;
        this->getRecursiveMonitorElements(pTreeWidgetItem, monitorElementItemList, false);
        monitorElementItems += QSet<QTreeWidgetItem *>::fromList(monitorElementItemList);
      }
      else
        monitorElementItems << pTreeWidgetItem;
    }
    DQMCanvasView *pCanvasView = this->getMonitoring()->getView()->getCanvasView();
    QSet<QTreeWidgetItem*>::iterator iter = monitorElementItems.begin();
    while(iter != monitorElementItems.end())
    {
      QTreeWidgetItem *pTreeWidgetItem = *iter;
      QString collectorName(this->getCollectorName());
      QString moduleName(this->getModuleName(pTreeWidgetItem));
      QString fullPathName(this->getFullPathName(pTreeWidgetItem));
      QString monitorElementName(pTreeWidgetItem->text(0));
      DQMGuiMonitorElement *pMonitorElement =
          this->getMonitoring()->getModel()->findMonitorElement(
              collectorName.toStdString(),
              moduleName.toStdString(),
              fullPathName.toStdString(),
              monitorElementName.toStdString());
      if(!pMonitorElement)
        continue;
      pCanvasView->drawInCurrentArea(pMonitorElement);
      pTreeWidgetItem->setCheckState(0, Qt::Checked);
      this->setFocus(Qt::OtherFocusReason);
      ++iter;
    }
    }
    else
    {
        return QTreeView::keyPressEvent(pKeyEvent);
    }
}
QTreeWidgetItem * dqm4hep::DQMMonitorElementNavigator::mkdir (const QString & moduleName)
Create a directory and return the directory.
If the directory exists, the function just returns the existing directory
Definition at line 239 of file DQMMonitorElementView.cc.
References DIRECTORY_ITEM.
Referenced by dirExists(), dqm4hep::DQMMonitorElementView::fromXml(), mkdir(), removeMonitorElement(), rmdir(), and updateMonitorElement().
{
  for(int i=0 ; i<topLevelItemCount() ; i++)
  {
    if(moduleName == this->topLevelItem(i)->text(0))
      return topLevelItem(i);
  }
  QTreeWidgetItem *pModuleDirectoryItem = new TreeWidgetItem(this);
  QCommonStyle style;
  pModuleDirectoryItem->setText(0, moduleName);
  pModuleDirectoryItem->setData(0, Qt::UserRole, static_cast<int>(DIRECTORY_ITEM));
  pModuleDirectoryItem->setIcon(0, style.standardIcon(QStyle::SP_DirOpenIcon));
  this->addTopLevelItem(pModuleDirectoryItem);
  return pModuleDirectoryItem;
}
QTreeWidgetItem * dqm4hep::DQMMonitorElementNavigator::mkdir (const QString & moduleName, const QString & fullPathDirName)
Create a directory and return the directory.
If the directory exists, the function just returns the existing directory
Definition at line 260 of file DQMMonitorElementView.cc.
References mkdir().
{
  QTreeWidgetItem *pModuleDirectoryItem = mkdir(moduleName);
  std::vector<std::string> tokens;
  DQM4HEP::tokenize(fullPathDirName.toStdString(), tokens, "/");
  QTreeWidgetItem *pCurrentParentItem = pModuleDirectoryItem;
  for(unsigned int i=0 ; i<tokens.size() ; i++)
  {
    QString dirName = tokens.at(i).c_str();
    pCurrentParentItem = this->mkdir(pCurrentParentItem, dirName);
  }
  return pCurrentParentItem;
}
QTreeWidgetItem * dqm4hep::DQMMonitorElementNavigator::mkdir (QTreeWidgetItem * pTreeItem, const QString & dirName) [private]
Create a directory and set pTreeItem as parent item.
If the directory already exists in child items of pTreeItem, it is not created.
Returns the created/existing directory item
Definition at line 690 of file DQMMonitorElementView.cc.
References DIRECTORY_ITEM, and isDirectoryItem().
{
  for(int i=0 ; i<pTreeItem->childCount() ; i++)
  {
    if(dirName == pTreeItem->child(i)->text(0) && this->isDirectoryItem(pTreeItem->child(i)))
      return pTreeItem->child(i);
  }
  QTreeWidgetItem *pDirectoryItem = new TreeWidgetItem(pTreeItem);
  QCommonStyle style;
  pDirectoryItem->setText(0, dirName);
  pDirectoryItem->setData(0, Qt::UserRole, static_cast<int>(DIRECTORY_ITEM));
  pDirectoryItem->setIcon(0, style.standardIcon(QStyle::SP_DirOpenIcon));
  pTreeItem->addChild(pDirectoryItem);
  return pDirectoryItem;
}
void dqm4hep::DQMMonitorElementNavigator::mousePressEvent (QMouseEvent * pMouseEvent) [private]
Definition at line 1019 of file DQMMonitorElementView.cc.
References getRecursiveMonitorElements(), isDirectoryItem(), m_dragItemList, and startDrag().
{
  if (pMouseEvent->button() == Qt::LeftButton
      && pMouseEvent->type() == QEvent::MouseButtonPress)
  {
    // find me item at this position
    QPoint point(pMouseEvent->pos());
    QTreeWidgetItem *pItem = this->itemAt(point);
    // if no item, then process at least the mousePressEvent of the super class
    if(!pItem)
    {
      QTreeView::mousePressEvent(pMouseEvent);
      return;
    }
    QList<QTreeWidgetItem *> selectedItems;
    // if the clicked item is selected, get all the selection
    // to drag and drop in a canvas area
    if(pItem->isSelected())
      selectedItems = this->selectedItems();
    // else just use the clicked item (maybe a directory)
    else
      selectedItems << pItem;
    // clear and rebuild the drag item list
    QSet<QTreeWidgetItem *> monitorElementItems;
    m_dragItemList.clear();
    // first, get all monitor elements
    for(int i = 0; i < selectedItems.count(); i++)
    {
      QTreeWidgetItem *pTreeWidgetItem = selectedItems.at(i);
      if(this->isDirectoryItem(pTreeWidgetItem))
      {
        QList<QTreeWidgetItem *> monitorElementItemList;
        this->getRecursiveMonitorElements(pTreeWidgetItem, monitorElementItemList, false);
        monitorElementItems += QSet<QTreeWidgetItem *>::fromList(monitorElementItemList);
      }
      else
        monitorElementItems << pTreeWidgetItem;
    }
    m_dragItemList = monitorElementItems.toList();
    // trigger the drag action only if ths list is not empty.
    // the drag action start after the double click interval
    // startDrag() check is the left mouse button is still
    // pressed at this time.
    // this is needed to differentiate a double click and a simple click
    // for the drag and process
    if(!m_dragItemList.isEmpty())
      QTimer::singleShot(QApplication::doubleClickInterval(), this, SLOT(
      startDrag()));
  }
  QTreeView::mousePressEvent(pMouseEvent);
}
void dqm4hep::DQMMonitorElementNavigator::queryUpdate () [private], [slot]
Definition at line 1160 of file DQMMonitorElementView.cc.
References dqm4hep::DQMMonitoringModel::findMonitorElement(), getCollectorName(), dqm4hep::DQMMonitoring::getController(), getFullPathName(), dqm4hep::DQMMonitoring::getModel(), getModuleName(), getMonitoring(), getSelectedMonitorElementItems(), and dqm4hep::DQMMonitoringController::queryUpdate().
Referenced by showContextMenu().
{
  QSet<QTreeWidgetItem*> selectedItems = QSet<QTreeWidgetItem*>::fromList(this->
      getSelectedMonitorElementItems());
  DQMGuiMonitorElementList monitorElementList;
  QString collectorName(this->getCollectorName());
  for(QSet<QTreeWidgetItem*>::iterator iter = selectedItems.begin(), endIter = selectedItems.end() ;
      endIter != iter ; ++iter)
  {
    QTreeWidgetItem *pTreeWidgetItem = *iter;
    QString moduleName(this->getModuleName(pTreeWidgetItem));
    QString fullPathName(this->getFullPathName(pTreeWidgetItem));
    QString monitorElementName(pTreeWidgetItem->text(0));
    DQMGuiMonitorElement *pMonitorElement =
        this->getMonitoring()->getModel()->findMonitorElement(
            collectorName.toStdString(),
            moduleName.toStdString(),
            fullPathName.toStdString(),
            monitorElementName.toStdString());
    if(NULL == pMonitorElement)
      continue;
    monitorElementList.push_back(pMonitorElement);
  }
  this->getMonitoring()->getController()->queryUpdate(monitorElementList);
}
void dqm4hep::DQMMonitorElementNavigator::removeMonitorElement (DQMGuiMonitorElement * pMonitorElement)
Remove the monitor element from the tree widget.
Definition at line 409 of file DQMMonitorElementView.cc.
References dirExists(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), isMonitorElementItem(), and mkdir().
Referenced by dqm4hep::DQMMonitorElementView::removeMonitorElement().
{
  QString moduleName = pMonitorElement->getMonitorElement()->getModuleName().c_str();
  QString fullPath = pMonitorElement->getMonitorElement()->getPath().getPath().c_str();
  QString name = pMonitorElement->getMonitorElement()->getName().c_str();
  if(this->dirExists(moduleName, fullPath))
  {
    QTreeWidgetItem *pTreeItem = this->mkdir(moduleName, fullPath);
    for(int i=0 ; i<pTreeItem->childCount() ; i++)
    {
      if(name == pTreeItem->child(i)->text(0) && this->isMonitorElementItem(pTreeItem->child(i)))
      {
        QTreeWidgetItem *pMonitorElementItem = pTreeItem->child(i);
        pTreeItem->removeChild(pMonitorElementItem);
        delete pMonitorElementItem;
        return;
      }
    }
  }
}
bool dqm4hep::DQMMonitorElementNavigator::rmdir (const QString & moduleName)
Remove the directory.
Return whether the directory was found and deleted
Definition at line 280 of file DQMMonitorElementView.cc.
References clear(), dirExists(), and mkdir().
{
  if(!this->dirExists(moduleName))
    return false;
  QTreeWidgetItem *pModuleDirectoryItem = this->mkdir(moduleName);
  // clear the directory
  this->clear(pModuleDirectoryItem);
  // and remove it from the tree
  delete this->takeTopLevelItem(this->indexOfTopLevelItem(pModuleDirectoryItem));
  return true;
}
bool dqm4hep::DQMMonitorElementNavigator::rmdir (const QString & moduleName, const QString & fullPathDirName)
Remove the directory.
Return whether the directory was found and deleted
Definition at line 298 of file DQMMonitorElementView.cc.
References clear(), dirExists(), and mkdir().
{
  if(!this->dirExists(moduleName, fullPathDirName))
    return false;
  QTreeWidgetItem *pDirectoryItem = this->mkdir(moduleName, fullPathDirName);
  QTreeWidgetItem *pParentWidget = pDirectoryItem->parent();
  // clear the directory
  this->clear(pDirectoryItem);
  // and remove it from its parent
  pParentWidget->removeChild(pDirectoryItem);
  delete pDirectoryItem;
  return true;
}
void dqm4hep::DQMMonitorElementNavigator::showContextMenu (const QPoint & point) [private], [slot]
Definition at line 784 of file DQMMonitorElementView.cc.
References dqm4hep::DQMCanvasView::canvasAreaCount(), checkAllMonitorElements(), checkSelectedMonitorElements(), drawSelectedMonitorElements(), dqm4hep::DQMCanvasView::getCanvasAreaIndex(), dqm4hep::DQMCanvasView::getCanvasAreaName(), dqm4hep::DQMMonitoringView::getCanvasView(), dqm4hep::DQMCanvasView::getCurrentCanvasArea(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), queryUpdate(), uncheckAllMonitorElements(), and uncheckSelectedMonitorElements().
Referenced by DQMMonitorElementNavigator().
{
    QPoint globalPos = this->mapToGlobal(point);
    QMenu contextMenu;
    QMenu *pExportToRootMenu = contextMenu.addMenu("Export to ROOT File");
    QAction *pExportAllAction = pExportToRootMenu->addAction("Export all");
    QAction *pExportCheckedAction = pExportToRootMenu->addAction("Export checked");
    QAction *pExportSelectedAction = pExportToRootMenu->addAction("Export selected");
    contextMenu.addSeparator();
    QAction *pUpdateAction = contextMenu.addAction("Update", this, SLOT(
      queryUpdate()));
    contextMenu.addSeparator();
    QMenu *pDrawInTabMenu = contextMenu.addMenu("Draw in ...");
    QAction *pDrawInTabAction = 0;
    QList<QAction *> drawInTabActionList;
    DQMCanvasView *pCanvasView = this->getMonitoring()->getView()->getCanvasView();
    int currentIndex = pCanvasView->getCanvasAreaIndex(pCanvasView->getCurrentCanvasArea());
    QAction *pDrawInNewTabAction = pDrawInTabMenu->addAction("New area", this, SLOT(
      drawSelectedMonitorElements()));
    pDrawInNewTabAction->setData(-1);
    pDrawInTabMenu->addSeparator();
    pDrawInTabAction = pDrawInTabMenu->addAction((pCanvasView->getCanvasAreaName(currentIndex) + "
       (current)").c_str(), this, SLOT(drawSelectedMonitorElements()));
    pDrawInTabAction->setData(currentIndex);
    drawInTabActionList << pDrawInTabAction;
    for(int i=0 ; i<pCanvasView->canvasAreaCount() ; i++)
    {
        if(i == currentIndex)
            continue;
        pDrawInTabAction = pDrawInTabMenu->addAction(pCanvasView->getCanvasAreaName(i).c_str(), this, SLOT(
      drawSelectedMonitorElements()));
        pDrawInTabAction->setData(i);
        drawInTabActionList << pDrawInTabAction;
    }
    QAction *pShowInfoAction = contextMenu.addAction("Show info");
    contextMenu.addSeparator();
    QAction *pCompareWithAction = contextMenu.addAction("Compare with ...");
    contextMenu.addSeparator();
    QAction *pCheckAllAction = contextMenu.addAction("Check all", this, SLOT(
      checkAllMonitorElements()));
    QAction *pCheckSelectedAction = contextMenu.addAction("Check selected", this, SLOT(
      checkSelectedMonitorElements()));
    contextMenu.addSeparator();
    QAction *pUncheckAllAction = contextMenu.addAction("Un-check all", this, SLOT(
      uncheckAllMonitorElements()));
    QAction *pUncheckSelectedAction = contextMenu.addAction("Un-check selected", this, SLOT(
      uncheckSelectedMonitorElements()));
    // process context menu
    contextMenu.exec(globalPos);
}
void dqm4hep::DQMMonitorElementNavigator::startDrag () [private], [slot]
Definition at line 1103 of file DQMMonitorElementView.cc.
References getCollectorName(), dqm4hep::DQMMonitoring::getController(), getFullPathName(), getModuleName(), getMonitoring(), dqm4hep::DQMMonitoringController::log(), and m_dragItemList.
Referenced by mousePressEvent().
{
  if(QApplication::mouseButtons().testFlag(Qt::LeftButton)
  && !m_dragItemList.isEmpty())
  {
    // serialize the item list in a byte array
    QByteArray byteArray;
    QDataStream dataStream(&byteArray, QIODevice::WriteOnly);
    QList<QTreeWidgetItem*>::iterator iter = m_dragItemList.begin();
    dataStream << qint32(m_dragItemList.count());
    while(iter != m_dragItemList.end())
    {
      QTreeWidgetItem *pTreeWidgetItem = *iter;
      QString collectorName(this->getCollectorName());
      QString moduleName(this->getModuleName(pTreeWidgetItem));
      QString fullPathName(this->getFullPathName(pTreeWidgetItem));
      QString monitorElementName(pTreeWidgetItem->text(0));
      dataStream << collectorName << moduleName << fullPathName << monitorElementName;
      ++iter;
    }
    QDrag *pDrag = new QDrag(this);
    // embed the serialized items in a QMimeData
    QMimeData *pMimeData = new QMimeData();
    pMimeData->setData("dqm4hep/me-item-list", byteArray);
    pDrag->setMimeData(pMimeData);
    // process the drag and drop
    Qt::DropAction dropAction = pDrag->exec(Qt::CopyAction);
    // successful ?
    if(dropAction == Qt::CopyAction)
    {
      // check all elements
      QList<QTreeWidgetItem*>::iterator iter = m_dragItemList.begin();
      while(iter != m_dragItemList.end())
      {
        (*iter)->setCheckState(0, Qt::Checked);
        ++iter;
      }
    }
    else
      this->getMonitoring()->getController()->log(ERROR, QString("No monitor elements drawn ! (%1
       requested)").arg(m_dragItemList.count()).toStdString());
  }
}
void dqm4hep::DQMMonitorElementNavigator::uncheckAllMonitorElements () [slot]
Uncheck all monitor element items.
Definition at line 608 of file DQMMonitorElementView.cc.
References getRecursiveMonitorElements().
Referenced by showContextMenu(), and dqm4hep::DQMMonitorElementView::uncheckAllMonitorElements().
{
  for(int i=0 ; i<topLevelItemCount() ; i++)
  {
    QTreeWidgetItem *pModuleItem = topLevelItem(i);
    QList<QTreeWidgetItem*> checkedMonitorElements;
    this->getRecursiveMonitorElements(pModuleItem, checkedMonitorElements, false);
    for(int j=0 ; j<checkedMonitorElements.count() ; j++)
      checkedMonitorElements.at(j)->setCheckState(0, Qt::Unchecked);
  }
}
void dqm4hep::DQMMonitorElementNavigator::uncheckSelectedMonitorElements () [slot]
Uncheck selected monitor element items.
Definition at line 657 of file DQMMonitorElementView.cc.
References getRecursiveMonitorElements(), and isDirectoryItem().
Referenced by showContextMenu().
{
  // Handle selected items instead of only the current item
  QList<QTreeWidgetItem *> selectedItems = this->selectedItems();
  QSet<QTreeWidgetItem *> monitorElementItems;
  // first, get all monitor elements
  for(int i = 0; i < selectedItems.count(); i++)
  {
    QTreeWidgetItem *pTreeWidgetItem = selectedItems.at(i);
    if(this->isDirectoryItem(pTreeWidgetItem))
    {
      QList<QTreeWidgetItem *> monitorElementItemList;
      this->getRecursiveMonitorElements(pTreeWidgetItem, monitorElementItemList, false);
      monitorElementItems += QSet<QTreeWidgetItem *>::fromList(monitorElementItemList);
    }
    else
      monitorElementItems << pTreeWidgetItem;
  }
  QSet<QTreeWidgetItem*>::iterator iter = monitorElementItems.begin();
  while(iter != monitorElementItems.end())
  {
    QTreeWidgetItem *pTreeWidgetItem = *iter;
    pTreeWidgetItem->setCheckState(0, Qt::Unchecked);
    ++iter;
  }
}
void dqm4hep::DQMMonitorElementNavigator::updateMonitorElement (DQMGuiMonitorElement * pMonitorElement)
Create an entry (if doesn't exists) from the monitor element.
The monitor element itself is not stored
Definition at line 385 of file DQMMonitorElementView.cc.
References addMonitorElement(), dqm4hep::DQMMonitoring::getController(), dqm4hep::DQMMonitoringController::getIcon(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), getMonitoring(), and mkdir().
Referenced by dqm4hep::DQMMonitorElementView::updateMonitorElement(), and updateMonitorElements().
{
  QString moduleName = pMonitorElement->getMonitorElement()->getModuleName().c_str();
  QString fullPath = pMonitorElement->getMonitorElement()->getPath().getPath().c_str();
  QString name = pMonitorElement->getMonitorElement()->getName().c_str();
  DQMQuality quality = pMonitorElement->getMonitorElement()->getQuality();
  QTreeWidgetItem *pDirectoryItem = this->mkdir(moduleName, fullPath);
  QTreeWidgetItem *pMonitorElementItem = this->addMonitorElement(pDirectoryItem, name);
  QIcon qualityIcon = this->getMonitoring()->getController()->getIcon(quality);
  pMonitorElementItem->setIcon(0, qualityIcon);
}
void dqm4hep::DQMMonitorElementNavigator::updateMonitorElements (const DQMGuiMonitorElementList & monitorElementList)
Create an entry (if doesn't exists) for each of the monitor elements.
Each of the monitor element itself is not stored
Definition at line 401 of file DQMMonitorElementView.cc.
References updateMonitorElement().
{
  for(unsigned int i=0 ; i<monitorElementList.size() ; i++)
    this->updateMonitorElement(monitorElementList.at(i));
}
Member Data Documentation
QString dqm4hep::DQMMonitorElementNavigator::m_collectorName [private]
Definition at line 253 of file DQMMonitorElementView.h.
Referenced by getCollectorName().
QList<QTreeWidgetItem*> dqm4hep::DQMMonitorElementNavigator::m_dragItemList [private]
Definition at line 254 of file DQMMonitorElementView.h.
Referenced by mousePressEvent(), and startDrag().
DQMMonitoring* dqm4hep::DQMMonitorElementNavigator::m_pMonitoring [private]
Definition at line 252 of file DQMMonitorElementView.h.
Referenced by getMonitoring().
bool dqm4hep::DQMMonitorElementNavigator::m_subscriptionEnabled [private]
Definition at line 255 of file DQMMonitorElementView.h.
Referenced by addMonitorElement(), and enableSubscription().
The documentation for this class was generated from the following files:
DQMMonitorElementView.h
DQMMonitorElementView.cc