dqm4hep::DQMMonitoringModel Class Reference
DQMMonitoringModel class.
#include <DQMMonitoringModel.h>
Public Slots
virtual void updateMonitorElement (DQMMonitorElement *pMonitorElement)
Update the monitor element in the model Add or replace if exists.
virtual void updateMonitorElement (DQMGuiMonitorElement *pMonitorElement)
Update the monitor element in the model Add or replace if exists.
virtual void removeMonitorElement (DQMGuiMonitorElement *pMonitorElement)
Remove the monitor element form the model.
void clear ()
Clear all the model contents.
void clear (const std::string &collectorName)
Clear all the elements of the given collector.
void clear (const std::string &collectorName, const std::string &moduleName)
Clear all the elements of the given collector and module.
Signals
void monitorElementAdded (DQMGuiMonitorElement *pMonitorElement)
Signal emitted when a monitor element is added to the model.
Public Member Functions
DQMMonitoringModel (DQMMonitoring *pMonitoring)
Constructor.
virtual ~DQMMonitoringModel ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
virtual bool monitorElementExists (DQMGuiMonitorElement *pMonitorElement) const
Whether the monitor element exists.
virtual DQMGuiMonitorElement * createGuiMonitorElement (DQMMonitorElement *pMonitorElement) const
Factory method that create a wrapper around a monitor element in the Qt framework.
DQMGuiMonitorElement * getOrCreateGuiMonitorElement (const std::string &collectorName, const std::string &moduleName, const std::string &fullPath, const std::string &name)
void loadMonitorElementInfoList (const std::string &collectorName, const DQMMonitorElementInfoList &nameList)
virtual DQMGuiMonitorElement * createGuiMonitorElement (const std::string &collectorName, const std::string &moduleName, const std::string &fullPath, const std::string &name) const
Factory method that create a wrapper around a monitor element in the Qt framework.
virtual DQMGuiMonitorElement * findMonitorElement (const std::string &collectorName, const std::string &moduleName, const std::string &fullPath, const std::string &name) const
Find and return a monitor element identified by its collector name, module name, full path and name Return NULL if not found.
Protected Attributes
DQMMonitoring * m_pMonitoring
DQMGuiMonitorElementList m_monitorElementList
Private Types
typedef std::vector
*
< DQMGuiMonitorElement * > DQMGuiMonitorElementList
Detailed Description
DQMMonitoringModel class.
Definition at line 49 of file DQMMonitoringModel.h.
Member Typedef Documentation
typedef std::vector<DQMGuiMonitorElement*> dqm4hep::DQMMonitoringModel::DQMGuiMonitorElementList [private]
Definition at line 53 of file DQMMonitoringModel.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitoringModel::DQMMonitoringModel (DQMMonitoring * pMonitoring)
Constructor.
Definition at line 46 of file DQMMonitoringModel.cc.
References m_pMonitoring, and dqm4hep::DQMMonitoring::setModel().
                                                                 :
    m_pMonitoring(pMonitoring)
{
  m_pMonitoring->setModel(this);
}
dqm4hep::DQMMonitoringModel::~DQMMonitoringModel () [virtual]
Destructor.
Definition at line 54 of file DQMMonitoringModel.cc.
References clear().
{
  clear();
}
Member Function Documentation
void dqm4hep::DQMMonitoringModel::clear () [slot]
Clear all the model contents.
Definition at line 157 of file DQMMonitoringModel.cc.
References dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), m_monitorElementList, and dqm4hep::DQMMonitorElementView::removeMonitorElement().
Referenced by dqm4hep::DQMMonitoringController::clearMonitoring(), dqm4hep::DQMMonitoringController::clearViewAndModel(), dqm4hep::DQMMonitoringController::openFile(), and ~DQMMonitoringModel().
{
  for(DQMGuiMonitorElementList::iterator iter = m_monitorElementList.begin(), endIter =
      m_monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    DQMGuiMonitorElement *pGuiMonitorElement = *iter;
    this->getMonitoring()->getView()->getMonitorElementView()->
      removeMonitorElement(pGuiMonitorElement);
    pGuiMonitorElement->deleteLater();
  }
  m_monitorElementList.clear();
}
void dqm4hep::DQMMonitoringModel::clear (const std::string & collectorName) [slot]
Clear all the elements of the given collector.
Definition at line 173 of file DQMMonitoringModel.cc.
References dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), m_monitorElementList, and dqm4hep::DQMMonitorElementView::removeMonitorElement().
{
  for(DQMGuiMonitorElementList::iterator iter = m_monitorElementList.begin(), endIter =
      m_monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    const std::string &thisCollectorName = (*iter)->getMonitorElement()->getCollectorName();
    if(thisCollectorName == collectorName)
    {
      DQMGuiMonitorElement *pGuiMonitorElement = *iter;
      // remove it
      m_monitorElementList.erase(iter);
      iter--;
      // notify view
      this->getMonitoring()->getView()->getMonitorElementView()->
      removeMonitorElement(pGuiMonitorElement);
      // delete it
      pGuiMonitorElement->deleteLater();
    }
  }
}
void dqm4hep::DQMMonitoringModel::clear (const std::string & collectorName, const std::string & moduleName) [slot]
Clear all the elements of the given collector and module.
Definition at line 199 of file DQMMonitoringModel.cc.
References dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), m_monitorElementList, and dqm4hep::DQMMonitorElementView::removeMonitorElement().
{
  for(DQMGuiMonitorElementList::iterator iter = m_monitorElementList.begin(), endIter =
      m_monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    const std::string &thisCollectorName = (*iter)->getMonitorElement()->getCollectorName();
    const std::string &thisModuleName = (*iter)->getMonitorElement()->getModuleName();
    if(thisCollectorName == collectorName && thisModuleName == moduleName)
    {
      DQMGuiMonitorElement *pGuiMonitorElement = *iter;
      // remove it
      m_monitorElementList.erase(iter);
      iter--;
      // notify view
      this->getMonitoring()->getView()->getMonitorElementView()->
      removeMonitorElement(pGuiMonitorElement);
      // delete it
      pGuiMonitorElement->deleteLater();
    }
  }
}
DQMGuiMonitorElement * dqm4hep::DQMMonitoringModel::createGuiMonitorElement (DQMMonitorElement * pMonitorElement) const [virtual]
Factory method that create a wrapper around a monitor element in the Qt framework.
The created monitor element is not registered in the model. Use updateMonitorElement(elt) to register it
Definition at line 243 of file DQMMonitoringModel.cc.
Referenced by createGuiMonitorElement(), dqm4hep::DQMCanvasView::fromXml(), getOrCreateGuiMonitorElement(), loadMonitorElementInfoList(), and updateMonitorElement().
{
  if(!pMonitorElement)
    return NULL;
  DQMGuiMonitorElement *pGuiMonitorElement = new DQMGuiMonitorElement(pMonitorElement);
  return pGuiMonitorElement;
}
DQMGuiMonitorElement * dqm4hep::DQMMonitoringModel::createGuiMonitorElement (const std::string & collectorName, const std::string & moduleName, const std::string & fullPath, const std::string & name) const [virtual]
Factory method that create a wrapper around a monitor element in the Qt framework.
The created monitor element is not registered in the model. Use updateMonitorElement(elt) to register it
Definition at line 345 of file DQMMonitoringModel.cc.
References createGuiMonitorElement().
{
  DQMMonitorElement *pMonitorElement = new DQMMonitorElement(NO_ELEMENT_TYPE, name, "", moduleName);
  pMonitorElement->setCollectorName(collectorName);
  pMonitorElement->setPath(DQMPath(fullPath));
  return this->createGuiMonitorElement(pMonitorElement);
}
DQMGuiMonitorElement * dqm4hep::DQMMonitoringModel::findMonitorElement (const std::string & collectorName, const std::string & moduleName, const std::string & fullPath, const std::string & name) const [virtual]
Find and return a monitor element identified by its collector name, module name, full path and name Return NULL if not found.
Definition at line 357 of file DQMMonitoringModel.cc.
References dqm4hep::DQMGuiMonitorElement::getMonitorElement(), and m_monitorElementList.
Referenced by dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements(), dqm4hep::DQMCanvasArea::dropEvent(), dqm4hep::DQMCanvasView::fromXml(), dqm4hep::DQMMonitorElementNavigator::handleItemDoubleClick(), dqm4hep::DQMMonitorElementNavigator::keyPressEvent(), dqm4hep::DQMMonitorElementNavigator::queryUpdate(), and updateMonitorElement().
{
  DQMPath path = fullPath;
  for(DQMGuiMonitorElementList::const_iterator iter = m_monitorElementList.begin(), endIter =
      m_monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    const std::string &meCollectorName = (*iter)->getMonitorElement()->getCollectorName();
    const DQMPath &mePath = (*iter)->getMonitorElement()->getPath();
    const std::string &meModuleName = (*iter)->getMonitorElement()->getModuleName();
    const std::string &meName = (*iter)->getMonitorElement()->getName();
    bool sameCollectorName = (collectorName == meCollectorName);
    bool samePath = (path == mePath);
    bool sameModuleName = (moduleName == meModuleName);
    bool sameName = (name == meName);
    if(sameCollectorName && samePath && sameModuleName && sameName)
    {
      return (*iter);
    }
  }
  return NULL;
}
DQMMonitoring * dqm4hep::DQMMonitoringModel::getMonitoring () const
Get the monitoring instance.
Definition at line 61 of file DQMMonitoringModel.cc.
References m_pMonitoring.
Referenced by clear(), getOrCreateGuiMonitorElement(), loadMonitorElementInfoList(), removeMonitorElement(), and updateMonitorElement().
{
  return m_pMonitoring;
}
DQMGuiMonitorElement * dqm4hep::DQMMonitoringModel::getOrCreateGuiMonitorElement (const std::string & collectorName, const std::string & moduleName, const std::string & fullPath, const std::string & name)
Definition at line 255 of file DQMMonitoringModel.cc.
References dqm4hep::DQMMonitorElementView::addMonitorElement(), createGuiMonitorElement(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), and m_monitorElementList.
{
  DQMPath path = fullPath;
  DQMGuiMonitorElement *pMonitorElement = NULL;
  for(DQMGuiMonitorElementList::const_iterator iter = m_monitorElementList.begin(), endIter =
      m_monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    const std::string &meCollectorName = (*iter)->getMonitorElement()->getCollectorName();
    const DQMPath &mePath = (*iter)->getMonitorElement()->getPath();
    const std::string &meModuleName = (*iter)->getMonitorElement()->getModuleName();
    const std::string &meName = (*iter)->getMonitorElement()->getName();
    bool sameCollectorName = (collectorName == meCollectorName);
    bool samePath = (path == mePath);
    bool sameModuleName = (moduleName == meModuleName);
    bool sameName = (name == meName);
    if(sameCollectorName && samePath && sameModuleName && sameName)
    {
      pMonitorElement = (*iter);
      break;
    }
  }
  if(NULL == pMonitorElement)
  {
    pMonitorElement = this->createGuiMonitorElement(collectorName, moduleName, fullPath, name);
    // register it
    m_monitorElementList.push_back(pMonitorElement);
    // notify view
    this->getMonitoring()->getView()->getMonitorElementView()->addMonitorElement(pMonitorElement);
  }
  return pMonitorElement;
}
void dqm4hep::DQMMonitoringModel::loadMonitorElementInfoList (const std::string & collectorName, const DQMMonitorElementInfoList & nameList)
Definition at line 297 of file DQMMonitoringModel.cc.
References dqm4hep::DQMMonitorElementView::addMonitorElement(), createGuiMonitorElement(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), and m_monitorElementList.
Referenced by dqm4hep::DQMMonitoringController::createEmptyMonitorElements().
{
  DQMGuiMonitorElementList addedMonitorElement;
  for(DQMMonitorElementInfoList::const_iterator meIter = nameList.begin(), meEndIter = nameList.end() ;
      meEndIter != meIter ; ++meIter)
  {
    DQMPath path = meIter->m_monitorElementFullPath;
    DQMGuiMonitorElement *pMonitorElement = NULL;
    for(DQMGuiMonitorElementList::const_iterator iter = m_monitorElementList.begin(), endIter =
      m_monitorElementList.end() ;
        endIter != iter ; ++iter)
    {
      const std::string &meCollectorName = (*iter)->getMonitorElement()->getCollectorName();
      const DQMPath &mePath = (*iter)->getMonitorElement()->getPath();
      const std::string &meModuleName = (*iter)->getMonitorElement()->getModuleName();
      const std::string &meName = (*iter)->getMonitorElement()->getName();
      bool sameCollectorName = (collectorName == meCollectorName);
      bool samePath = (path == mePath);
      bool sameModuleName = (meIter->m_moduleName == meModuleName);
      bool sameName = (meIter->m_monitorElementName == meName);
      if(sameCollectorName && samePath && sameModuleName && sameName)
      {
        pMonitorElement = (*iter);
        break;
      }
    }
    if(NULL == pMonitorElement)
    {
      pMonitorElement = this->createGuiMonitorElement(collectorName, meIter->m_moduleName, meIter->
      m_monitorElementFullPath, meIter->m_monitorElementName);
      // add it to tmp list
      addedMonitorElement.push_back(pMonitorElement);
      // notify view
      this->getMonitoring()->getView()->getMonitorElementView()->
      addMonitorElement(pMonitorElement);
    }
  }
  // register new content !
  m_monitorElementList.insert(m_monitorElementList.end(), addedMonitorElement.begin(), addedMonitorElement.
      end());
}
void dqm4hep::DQMMonitoringModel::monitorElementAdded (DQMGuiMonitorElement * pMonitorElement) [signal]
Signal emitted when a monitor element is added to the model.
bool dqm4hep::DQMMonitoringModel::monitorElementExists (DQMGuiMonitorElement * pMonitorElement) const [virtual]
Whether the monitor element exists.
Definition at line 226 of file DQMMonitoringModel.cc.
References m_monitorElementList.
{
  if(!pMonitorElement)
    return false;
  for(DQMGuiMonitorElementList::const_iterator iter = m_monitorElementList.begin(), endIter =
      m_monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    if((*iter)->equals(pMonitorElement))
      return true;
  }
  return false;
}
void dqm4hep::DQMMonitoringModel::removeMonitorElement (DQMGuiMonitorElement * pMonitorElement) [virtual], [slot]
Remove the monitor element form the model.
Definition at line 130 of file DQMMonitoringModel.cc.
References dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), m_monitorElementList, and dqm4hep::DQMMonitorElementView::removeMonitorElement().
{
  if(!pMonitorElement)
    return;
  for(DQMGuiMonitorElementList::iterator iter = m_monitorElementList.begin(), endIter =
      m_monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    DQMGuiMonitorElement *pGuiMonitorElement = *iter;
    if((*iter)->equals(pMonitorElement))
    {
      // remove it
      m_monitorElementList.erase(iter);
      // notify view
      this->getMonitoring()->getView()->getMonitorElementView()->
      removeMonitorElement(pGuiMonitorElement);
      break;
    }
  }
  pMonitorElement->deleteLater();
}
void dqm4hep::DQMMonitoringModel::updateMonitorElement (DQMMonitorElement * pMonitorElement) [virtual], [slot]
Update the monitor element in the model Add or replace if exists.
Definition at line 68 of file DQMMonitoringModel.cc.
References dqm4hep::DQMMonitorElementView::addMonitorElement(), createGuiMonitorElement(), dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), m_monitorElementList, dqm4hep::DQMGuiMonitorElement::update(), and dqm4hep::DQMMonitorElementView::updateMonitorElement().
Referenced by dqm4hep::DQMCanvasView::fromXml(), and dqm4hep::DQMMonitoringController::receiveMonitorElementPublication().
{
  if(!pMonitorElement)
    return;
  for(DQMGuiMonitorElementList::iterator iter = m_monitorElementList.begin(), endIter =
      m_monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    if((*iter)->equals(pMonitorElement))
    {
      // replace it (swap)
      DQMGuiMonitorElement *pGuiMonitorElement = *iter;
      pGuiMonitorElement->update(pMonitorElement);
      // notify view
      this->getMonitoring()->getView()->getMonitorElementView()->
      updateMonitorElement(pGuiMonitorElement);
      return;
    }
  }
  // create a new one
  DQMGuiMonitorElement *pGuiMonitorElement = this->createGuiMonitorElement(pMonitorElement);
  // register it
  m_monitorElementList.push_back(pGuiMonitorElement);
  // notify view
  this->getMonitoring()->getView()->getMonitorElementView()->addMonitorElement(pGuiMonitorElement);
}
void dqm4hep::DQMMonitoringModel::updateMonitorElement (DQMGuiMonitorElement * pMonitorElement) [virtual], [slot]
Update the monitor element in the model Add or replace if exists.
Definition at line 101 of file DQMMonitoringModel.cc.
References dqm4hep::DQMMonitorElementView::addMonitorElement(), findMonitorElement(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), m_monitorElementList, dqm4hep::DQMGuiMonitorElement::update(), and dqm4hep::DQMMonitorElementView::updateMonitorElement().
{
  if(!pMonitorElement)
    return;
  DQMGuiMonitorElement *pFindMonitorElement = this->findMonitorElement(pMonitorElement->getMonitorElement()
      ->getCollectorName(),
      pMonitorElement->getMonitorElement()->getModuleName(),
      pMonitorElement->getMonitorElement()->getPath().getPath(),
      pMonitorElement->getMonitorElement()->getName());
  if(!pFindMonitorElement)
  {
    // register it
    m_monitorElementList.push_back(pMonitorElement);
    // notify view
    this->getMonitoring()->getView()->getMonitorElementView()->addMonitorElement(pMonitorElement);
  }
  else
  {
    pFindMonitorElement->update(pMonitorElement->getMonitorElement());
    // notify view
    this->getMonitoring()->getView()->getMonitorElementView()->
      updateMonitorElement(pMonitorElement);
  }
}
Member Data Documentation
DQMGuiMonitorElementList dqm4hep::DQMMonitoringModel::m_monitorElementList [protected]
Definition at line 136 of file DQMMonitoringModel.h.
Referenced by clear(), findMonitorElement(), getOrCreateGuiMonitorElement(), loadMonitorElementInfoList(), monitorElementExists(), removeMonitorElement(), and updateMonitorElement().
DQMMonitoring* dqm4hep::DQMMonitoringModel::m_pMonitoring [protected]
Definition at line 135 of file DQMMonitoringModel.h.
Referenced by DQMMonitoringModel(), and getMonitoring().
The documentation for this class was generated from the following files:
DQMMonitoringModel.h
DQMMonitoringModel.cc