dqm4hep::DQMMonitoringView Class Reference
DQMMonitoringView class.
#include <DQMMonitoringView.h>
Public Member Functions
DQMMonitoringView (DQMMonitoring *pMonitoring)
Constructor.
~DQMMonitoringView ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
TiXmlElement * toXml () const
Export settings to xml element.
void fromXml (TiXmlElement *const pXmlElement)
Import settings from xml element.
void buildView ()
Build the view.
void showView ()
void hideView ()
DQMCanvasView * getCanvasView () const
DQMMonitorElementView * getMonitorElementView () const
QMainWindow * getMainWindow () const
void clear ()
Protected Member Functions
void buildMenus ()
void buildCentralView ()
void buildStatusBar ()
Protected Attributes
bool m_viewBuilt
Whether the view has been built.
DQMMonitoring * m_pMonitoring
The monitoring instance.
DQMCanvasView * m_pCanvasView
The canvas view to display monitor elements.
DQMMonitorElementView * m_pMonitorElementView
The monitor element view to display the element hierarchy.
QMainWindow * m_pMainWindow
The main window containing the whole view.
Private Slots
void handleAutoUpdateButtonClicked ()
Detailed Description
DQMMonitoringView class.
Definition at line 49 of file DQMMonitoringView.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitoringView::DQMMonitoringView (DQMMonitoring * pMonitoring)
Constructor.
Definition at line 83 of file DQMMonitoringView.cc.
References m_pMonitoring, and dqm4hep::DQMMonitoring::setView().
                                                               :
  m_pMonitoring(pMonitoring),
  m_pCanvasView(NULL),
  m_pMonitorElementView(NULL),
  m_pMainWindow(NULL),
  m_viewBuilt(false)
{
  m_pMonitoring->setView(this);
}
dqm4hep::DQMMonitoringView::~DQMMonitoringView ()
Destructor.
Definition at line 95 of file DQMMonitoringView.cc.
References m_pCanvasView, m_pMainWindow, and m_pMonitorElementView.
{
  if(m_pCanvasView)
    delete m_pCanvasView;
  if(m_pMonitorElementView)
    delete m_pMonitorElementView;
  if(m_pMainWindow)
    delete m_pMainWindow;
}
Member Function Documentation
void dqm4hep::DQMMonitoringView::buildCentralView () [protected]
Definition at line 224 of file DQMMonitoringView.cc.
References getMonitoring(), handleAutoUpdateButtonClicked(), m_pCanvasView, m_pMainWindow, m_pMonitorElementView, and m_pMonitoring.
Referenced by buildView().
{
  // main area
  QSplitter *pMainWidget = new QSplitter(Qt::Horizontal);
  m_pMainWindow->setCentralWidget(pMainWidget);
  QWidget *pLeftViewWidget = new QWidget();
  pLeftViewWidget->setLayout(new QVBoxLayout());
    // update buttons
  QWidget *pUpdateButtonAreaWidget = new QWidget();
  pUpdateButtonAreaWidget->setLayout(new QHBoxLayout());
  QPushButton *pAutoUpdateButton = new QPushButton("Start update");
  pUpdateButtonAreaWidget->layout()->addWidget(pAutoUpdateButton);
  QPushButton *pUpdateButton = new QPushButton("Update");
  pUpdateButtonAreaWidget->layout()->addWidget(pUpdateButton);
  pUpdateButtonAreaWidget->setMaximumHeight(50);
  pLeftViewWidget->layout()->addWidget(pUpdateButtonAreaWidget);
  // monitor element contents view
  QGroupBox *pContentGroupBox = new QGroupBox("Contents");
  pContentGroupBox->setLayout(new QVBoxLayout());
  pLeftViewWidget->layout()->addWidget(pContentGroupBox);
  m_pMonitorElementView = new DQMMonitorElementView(m_pMonitoring);
  m_pMonitorElementView->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
  pContentGroupBox->layout()->addWidget(m_pMonitorElementView);
  // clear and browse buttons
  QWidget *pClearBrowseButtonAreaWidget = new QWidget();
  pClearBrowseButtonAreaWidget->setLayout(new QHBoxLayout());
  QPushButton *pClearButton = new QPushButton("Clear");
  pClearBrowseButtonAreaWidget->layout()->addWidget(pClearButton);
  QPushButton *pBrowseButton = new QPushButton("Browse");
  pClearBrowseButtonAreaWidget->layout()->addWidget(pBrowseButton);
  pClearBrowseButtonAreaWidget->setMaximumHeight(50);
    pLeftViewWidget->layout()->addWidget(pClearBrowseButtonAreaWidget);
  pMainWidget->addWidget(pLeftViewWidget);
  m_pCanvasView = new DQMCanvasView(m_pMonitoring);
  pMainWidget->addWidget(m_pCanvasView);
  connect(pAutoUpdateButton, SIGNAL(clicked()), this, SLOT(
      handleAutoUpdateButtonClicked()));
  connect(pUpdateButton, SIGNAL(clicked()), this->getMonitoring()->getController(), SLOT(
      querySubscribedMonitorElements()));
  connect(pClearButton, SIGNAL(clicked()), this->getMonitoring()->getController(), SLOT(clearMonitoring()))
      ;
  connect(pBrowseButton, SIGNAL(clicked()), this->getMonitoring()->getController(), SLOT(openBrowser()));
}
void dqm4hep::DQMMonitoringView::buildMenus () [protected]
Definition at line 199 of file DQMMonitoringView.cc.
References getMonitoring(), and m_pMainWindow.
Referenced by buildView().
{
  QMenu *pFileMenu = m_pMainWindow->menuBar()->addMenu("&File");
  pFileMenu->addAction("&Import", this->getMonitoring()->getController(), SLOT(openFile()), QKeySequence(
      QKeySequence::Open));
  pFileMenu->addAction("&Export", this->getMonitoring()->getController(), SLOT(saveAs()), QKeySequence(
      QKeySequence::SaveAs));
  pFileMenu->addSeparator();
  pFileMenu->addAction("&Browse", this->getMonitoring()->getController(), SLOT(openBrowser()), QKeySequence
      (QKeySequence::New));
  pFileMenu->addSeparator();
  pFileMenu->addAction("&Quit", this->getMonitoring()->getController(), SLOT(quit()), QKeySequence(
      QKeySequence::Quit));
  QMenu *pHelpMenu = m_pMainWindow->menuBar()->addMenu("&Help");
  pHelpMenu->addAction("Doxygen", this->getMonitoring()->getController(), SLOT(openDoxygenDoc()));
  pHelpMenu->addAction("User guide", this->getMonitoring()->getController(), SLOT(openUserGuide()));
  pHelpMenu->addSeparator();
  pHelpMenu->addAction("Contribute", this->getMonitoring()->getController(), SLOT(openGithubPage()));
  pHelpMenu->addAction("Report bugs", this->getMonitoring()->getController(), SLOT(openIssuesPage()));
  pHelpMenu->addSeparator();
  pHelpMenu->addAction("About Qt", qApp, SLOT(aboutQt()));
  pHelpMenu->addAction("About DQM4HEP", this->getMonitoring()->getController(), SLOT(aboutDQM4HEP()));
}
void dqm4hep::DQMMonitoringView::buildStatusBar () [protected]
Definition at line 285 of file DQMMonitoringView.cc.
References getMainWindow().
Referenced by buildView().
{
  this->getMainWindow()->statusBar()->showMessage("Welcome", 3000);
}
void dqm4hep::DQMMonitoringView::buildView ()
Build the view.
Should be called once
Definition at line 178 of file DQMMonitoringView.cc.
References buildCentralView(), buildMenus(), buildStatusBar(), DQMViz_DIR, getMonitoring(), m_pMainWindow, and m_viewBuilt.
Referenced by hideView(), and showView().
{
  if(m_viewBuilt)
    return;
  m_pMainWindow = new DQMMonitoringMainWindow(this->getMonitoring());
  m_pMainWindow->setWindowTitle("DQM Monitoring");
  m_pMainWindow->setAnimated(true);
  QString iconDir = QString(DQMViz_DIR) + "/icons";
  m_pMainWindow->setWindowIcon(QIcon(iconDir + "/MON_WIN.png"));
  buildMenus();
  buildCentralView();
  buildStatusBar();
  m_viewBuilt = true;
}
void dqm4hep::DQMMonitoringView::clear ()
Definition at line 308 of file DQMMonitoringView.cc.
References dqm4hep::DQMCanvasView::clear(), dqm4hep::DQMMonitorElementView::clear(), m_pCanvasView, and m_pMonitorElementView.
Referenced by dqm4hep::DQMMonitoringController::clearMonitoring(), dqm4hep::DQMMonitoringController::clearViewAndModel(), fromXml(), and dqm4hep::DQMMonitoringController::openFile().
{
  m_pMonitorElementView->clear();
  m_pCanvasView->clear();
}
void dqm4hep::DQMMonitoringView::fromXml (TiXmlElement *const pXmlElement)
Import settings from xml element.
Definition at line 135 of file DQMMonitoringView.cc.
References clear(), dqm4hep::DQMCanvasView::fromXml(), dqm4hep::DQMMonitorElementView::fromXml(), m_pCanvasView, and m_pMonitorElementView.
Referenced by dqm4hep::DQMMonitoringController::openFile().
{
  if(!pXmlElement)
    return;
  this->clear();
    TiXmlHandle elementHandle(pXmlElement);
    TiXmlElement *pCanvasViewElement = elementHandle.FirstChild("canvasView").Element();
    if(pCanvasViewElement)
      m_pCanvasView->fromXml(pCanvasViewElement);
    TiXmlElement *pMeViewElement = elementHandle.FirstChild("meView").Element();
    if(pMeViewElement)
      m_pMonitorElementView->fromXml(pMeViewElement);
}
DQMCanvasView * dqm4hep::DQMMonitoringView::getCanvasView () const
Definition at line 157 of file DQMMonitoringView.cc.
References m_pCanvasView.
Referenced by dqm4hep::DQMRootWidget::createContextMenu(), dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements(), dqm4hep::DQMMonitorElementNavigator::handleItemDoubleClick(), dqm4hep::DQMMonitorElementNavigator::keyPressEvent(), dqm4hep::DQMRootWidget::moveCanvas(), dqm4hep::DQMRootWidget::removeCanvas(), and dqm4hep::DQMMonitorElementNavigator::showContextMenu().
{
  return m_pCanvasView;
}
QMainWindow * dqm4hep::DQMMonitoringView::getMainWindow () const
Definition at line 171 of file DQMMonitoringView.cc.
References m_pMainWindow.
Referenced by buildStatusBar(), hideView(), dqm4hep::DQMMonitoringController::log(), and showView().
{
  return m_pMainWindow;
}
DQMMonitorElementView * dqm4hep::DQMMonitoringView::getMonitorElementView () const
Definition at line 164 of file DQMMonitoringView.cc.
References m_pMonitorElementView.
Referenced by dqm4hep::DQMMonitoringModel::clear(), dqm4hep::DQMMonitoringModel::getOrCreateGuiMonitorElement(), dqm4hep::DQMMonitoringController::handleServerShutdown(), dqm4hep::DQMMonitoringController::handleServerStartup(), dqm4hep::DQMMonitoringModel::loadMonitorElementInfoList(), dqm4hep::DQMMonitoringModel::removeMonitorElement(), and dqm4hep::DQMMonitoringModel::updateMonitorElement().
{
  return m_pMonitorElementView;
}
DQMMonitoring * dqm4hep::DQMMonitoringView::getMonitoring () const
Get the monitoring instance.
Definition at line 109 of file DQMMonitoringView.cc.
References m_pMonitoring.
Referenced by buildCentralView(), buildMenus(), buildView(), and handleAutoUpdateButtonClicked().
{
  return m_pMonitoring;
}
void dqm4hep::DQMMonitoringView::handleAutoUpdateButtonClicked () [private], [slot]
Definition at line 316 of file DQMMonitoringView.cc.
References dqm4hep::DQMMonitoring::getController(), getMonitoring(), dqm4hep::DQMMonitoringController::getUpdateMode(), and dqm4hep::DQMMonitoringController::setUpdateMode().
Referenced by buildCentralView().
{
  QPushButton *pButton = qobject_cast<QPushButton *>(sender());
  if(!pButton)
    return;
  // update view
  if(this->getMonitoring()->getController()->getUpdateMode())
  {
    pButton->setText("Start update");
    this->getMonitoring()->getController()->setUpdateMode(false);
  }
  else
  {
    pButton->setText("Stop update");
    this->getMonitoring()->getController()->setUpdateMode(true);
  }
}
void dqm4hep::DQMMonitoringView::hideView ()
Definition at line 300 of file DQMMonitoringView.cc.
References buildView(), and getMainWindow().
{
  this->buildView();
  this->getMainWindow()->showMinimized();
}
void dqm4hep::DQMMonitoringView::showView ()
Definition at line 292 of file DQMMonitoringView.cc.
References buildView(), and getMainWindow().
{
  this->buildView();
  this->getMainWindow()->show();
}
TiXmlElement * dqm4hep::DQMMonitoringView::toXml () const
Export settings to xml element.
Definition at line 116 of file DQMMonitoringView.cc.
References m_pCanvasView, m_pMonitorElementView, dqm4hep::DQMCanvasView::toXml(), and dqm4hep::DQMMonitorElementView::toXml().
Referenced by dqm4hep::DQMMonitoringController::saveAs().
{
  TiXmlElement *pXmlElement = new TiXmlElement("view");
  TiXmlElement *pMeViewElement = m_pMonitorElementView->toXml();
  if(pMeViewElement)
    pXmlElement->LinkEndChild(pMeViewElement);
  TiXmlElement *pCanvasViewElement = m_pCanvasView->toXml();
  if(pCanvasViewElement)
    pXmlElement->LinkEndChild(pCanvasViewElement);
  return pXmlElement;
}
Member Data Documentation
DQMCanvasView* dqm4hep::DQMMonitoringView::m_pCanvasView [protected]
The canvas view to display monitor elements.
Definition at line 126 of file DQMMonitoringView.h.
Referenced by buildCentralView(), clear(), fromXml(), getCanvasView(), toXml(), and ~DQMMonitoringView().
QMainWindow* dqm4hep::DQMMonitoringView::m_pMainWindow [protected]
The main window containing the whole view.
Definition at line 128 of file DQMMonitoringView.h.
Referenced by buildCentralView(), buildMenus(), buildView(), getMainWindow(), and ~DQMMonitoringView().
DQMMonitorElementView* dqm4hep::DQMMonitoringView::m_pMonitorElementView [protected]
The monitor element view to display the element hierarchy.
Definition at line 127 of file DQMMonitoringView.h.
Referenced by buildCentralView(), clear(), fromXml(), getMonitorElementView(), toXml(), and ~DQMMonitoringView().
DQMMonitoring* dqm4hep::DQMMonitoringView::m_pMonitoring [protected]
The monitoring instance.
Definition at line 125 of file DQMMonitoringView.h.
Referenced by buildCentralView(), DQMMonitoringView(), and getMonitoring().
bool dqm4hep::DQMMonitoringView::m_viewBuilt [protected]
Whether the view has been built.
Definition at line 123 of file DQMMonitoringView.h.
Referenced by buildView().
The documentation for this class was generated from the following files:
DQMMonitoringView.h
DQMMonitoringView.cc