dqm4hep::TreeWidgetItem Class Reference
Public Member Functions
TreeWidgetItem ()
Constructor.
TreeWidgetItem (QTreeWidgetItem *pParent)
Constructor with parent item.
TreeWidgetItem (QTreeWidget *pTreeWidget)
Constructor with tree widget.
void setData (int column, int role, const QVariant &value)
Set data for a target column with a given role.
void setCheckable (bool checkable)
Set whether the element can be checked (subscribed)
Private Attributes
bool m_checkable
Detailed Description
Definition at line 50 of file DQMMonitorElementView.cc.
Constructor & Destructor Documentation
dqm4hep::TreeWidgetItem::TreeWidgetItem ()
Constructor.
Definition at line 79 of file DQMMonitorElementView.cc.
                               :
    QTreeWidgetItem(),
    m_checkable(true)
{
  /* nop */
}
dqm4hep::TreeWidgetItem::TreeWidgetItem (QTreeWidgetItem * pParent)
Constructor with parent item.
Definition at line 88 of file DQMMonitorElementView.cc.
                                                       :
    QTreeWidgetItem(pParent),
    m_checkable(true)
{
  /* nop */
}
dqm4hep::TreeWidgetItem::TreeWidgetItem (QTreeWidget * pTreeWidget)
Constructor with tree widget.
Definition at line 97 of file DQMMonitorElementView.cc.
                                                       :
    QTreeWidgetItem(pTreeWidget),
    m_checkable(true)
{
  /* nop */
}
Member Function Documentation
void dqm4hep::TreeWidgetItem::setCheckable (bool checkable)
Set whether the element can be checked (subscribed)
Definition at line 168 of file DQMMonitorElementView.cc.
References m_checkable.
Referenced by dqm4hep::DQMMonitorElementNavigator::addMonitorElement(), and dqm4hep::DQMMonitorElementNavigator::enableSubscription().
{
  std::cout << "Item " << this->text(0).toStdString() << " set checkable to " << checkable << std::endl;
  m_checkable = checkable;
}
void dqm4hep::TreeWidgetItem::setData (int column, int role, const QVariant & value)
Set data for a target column with a given role.
Definition at line 106 of file DQMMonitorElementView.cc.
References dqm4hep::DQMMonitorElementNavigator::getCollectorName(), dqm4hep::DQMMonitoring::getController(), dqm4hep::DQMMonitorElementNavigator::getFullPathName(), dqm4hep::DQMMonitorElementNavigator::getModuleName(), dqm4hep::DQMMonitorElementNavigator::getMonitoring(), dqm4hep::DQMMonitorElementNavigator::isMonitorElementItem(), dqm4hep::DQMMonitoringController::log(), m_checkable, dqm4hep::DQMMonitoringController::subscribe(), and dqm4hep::DQMMonitoringController::unsubscribe().
Referenced by dqm4hep::DQMMonitorElementNavigator::addMonitorElement().
{
  if(0 == column && role == Qt::CheckStateRole)
  {
    Qt::CheckState oldState = static_cast<Qt::CheckState>(this->data(column, role).toInt());
    Qt::CheckState newState = static_cast<Qt::CheckState>(value.toInt());
    if(oldState == newState)
    {
      QTreeWidgetItem::setData(column, role, value);
      return;
    }
    DQMMonitorElementNavigator *pNavigator = qobject_cast<DQMMonitorElementNavigator *>(this->treeWidget())
      ;
    if(!pNavigator)
    {
      QTreeWidgetItem::setData(column, role, value);
      return;
    }
    if(!pNavigator->isMonitorElementItem(this))
    {
      QTreeWidgetItem::setData(column, role, value);
      return;
    }
    QString collectorName(pNavigator->getCollectorName());
    QString moduleName(pNavigator->getModuleName(this));
    QString fullPathName(pNavigator->getFullPathName(this));
    QString monitorElementName(this->text(0));
    std::string fullName = (DQMPath(fullPathName.toStdString()) + monitorElementName.toStdString()).getPath
      ();
    DQMMonitorElementRequest request;
    request.push_back(DQMMonitorElementRequest::value_type(moduleName.toStdString(), fullName));
    if(Qt::Checked == newState)
    {
      if(m_checkable)
      {
        std::cout << "Subscribing to " << fullName << std::endl;
        pNavigator->getMonitoring()->getController()->subscribe(collectorName.toStdString(), request);
      }
      else
      {
        pNavigator->getMonitoring()->getController()->log(ERROR, "Can't subscribe to monitor element to " +
       fullName + " (disabled)");
        return;
      }
    }
    else
    {
      std::cout << "Un-subscribing to " << fullName << std::endl;
      pNavigator->getMonitoring()->getController()->unsubscribe(collectorName.toStdString(), request);
    }
  }
  QTreeWidgetItem::setData(column, role, value);
}
Member Data Documentation
bool dqm4hep::TreeWidgetItem::m_checkable [private]
Definition at line 74 of file DQMMonitorElementView.cc.
Referenced by setCheckable(), and setData().
The documentation for this class was generated from the following file:
DQMMonitorElementView.cc