dqm4hep::DQMRootWidget Class Reference
DQMRootWidget class.
#include <DQMRootWidget.h>
Public Member Functions
DQMRootWidget (DQMMonitoring *pMonitoring, QWidget *pParent=0)
Constructor.
~DQMRootWidget ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
void setCanvas (DQMCanvas *pCanvas)
Set canvas on which the the root widget is drawn.
DQMCanvas * getCanvas () const
Get the canvas on which the the root widget is drawn.
virtual void mouseDoubleClickEvent (QMouseEvent *e)
Handle mouse double click event on the widget.
virtual void mouseReleaseEvent (QMouseEvent *e)
Handle mouse release event on the widget.
virtual void postDraw ()
Post draw function with a 'fake' update of the widget.
virtual void drawNoVis ()
Draw an image saying `no vis available`.
virtual void draw (DQMGuiMonitorElement *pMonitorElement)
Draw the monitor element on the canvas.
virtual TImage * getNoVisImage ()
Get the `no vis` image, create it if not (proxy method)
virtual DQMGuiMonitorElement * getCurrentMonitorElement () const
Get the current monitor element draw on the root canvas.
Protected Member Functions
QMenu * createContextMenu () const
void addDrawOptions (QMenu *pMenu) const
void updateMonitorElement (DQMGuiMonitorElement *pNewGuiMonitorElement)
Protected Attributes
DQMMonitoring * m_pMonitoring
DQMCanvas * m_pCanvas
TImage * m_pNoVisImage
DQMGuiMonitorElement * m_pCurrentMonitorElement
Private Slots
void showContextMenu (const QPoint &point)
void moveCanvas ()
void queryUpdate ()
void removeCanvas ()
void setDrawOption ()
void setDrawOptionFromDialog ()
void unzoom ()
void saveAs ()
void openROOTPanel ()
void showMonitorElementInfo ()
void showQTestResults ()
void redraw ()
Detailed Description
DQMRootWidget class.
Definition at line 52 of file DQMRootWidget.h.
Constructor & Destructor Documentation
dqm4hep::DQMRootWidget::DQMRootWidget (DQMMonitoring * pMonitoring, QWidget * pParent = 0)
Constructor.
Definition at line 51 of file DQMRootWidget.cc.
References showContextMenu().
                                                                         :
  TQtWidget(pParent, 0, true),
  m_pMonitoring(pMonitoring),
  m_pCanvas(NULL),
  m_pCurrentMonitorElement(NULL),
  m_pNoVisImage(NULL)
{
  this->setContextMenuPolicy(Qt::CustomContextMenu);
    connect(this, SIGNAL(customContextMenuRequested(const QPoint &)),
        this, SLOT(showContextMenu(const QPoint &)));
}
dqm4hep::DQMRootWidget::~DQMRootWidget ()
Destructor.
Definition at line 66 of file DQMRootWidget.cc.
References m_pNoVisImage.
{
  if(m_pNoVisImage)
    delete m_pNoVisImage;
}
Member Function Documentation
void dqm4hep::DQMRootWidget::addDrawOptions (QMenu * pMenu) const [protected]
Definition at line 260 of file DQMRootWidget.cc.
References setDrawOption(), and setDrawOptionFromDialog().
Referenced by createContextMenu().
{
  pMenu->addAction("", this, SLOT(setDrawOption()));
  pMenu->addAction("E", this, SLOT(setDrawOption()));
  pMenu->addAction("LEGO", this, SLOT(setDrawOption()));
  pMenu->addSeparator();
  pMenu->addAction("COL", this, SLOT(setDrawOption()));
  pMenu->addAction("COLZ", this, SLOT(setDrawOption()));
  pMenu->addAction("SURF", this, SLOT(setDrawOption()));
  pMenu->addAction("SURF1", this, SLOT(setDrawOption()));
  pMenu->addSeparator();
    QMenu *pMoreDrawOptionMenu = pMenu->addMenu("More draw options");
    pMoreDrawOptionMenu->addAction("FUNC", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("LEGO1", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("LEGO2", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("E0", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("E1", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("E2", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("E3", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("E4", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("E5", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("E6", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addSeparator();
    pMoreDrawOptionMenu->addAction("ARR", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("BOX", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("SURF2", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("SURF3", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("SURF4", this, SLOT(setDrawOption()));
    pMoreDrawOptionMenu->addAction("SURF5", this, SLOT(setDrawOption()));
    pMenu->addSeparator();
    pMenu->addAction("Custom draw option", this, SLOT(setDrawOptionFromDialog()));
}
QMenu * dqm4hep::DQMRootWidget::createContextMenu () const [protected]
Definition at line 204 of file DQMRootWidget.cc.
References addDrawOptions(), dqm4hep::DQMCanvasView::canvasAreaList(), dqm4hep::DQMCanvasView::getCanvasAreaName(), dqm4hep::DQMMonitoringView::getCanvasView(), dqm4hep::DQMCanvasView::getCurrentCanvasArea(), getCurrentMonitorElement(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), moveCanvas(), openROOTPanel(), queryUpdate(), removeCanvas(), saveAs(), setDrawOption(), showMonitorElementInfo(), showQTestResults(), and unzoom().
Referenced by showContextMenu().
{
  QMenu *pContextMenu = new QMenu();
  QMenu *pMoveToCanvasAreaMenu = pContextMenu->addMenu("Move to canvas area");
  DQMCanvasView *pCanvasView = this->getMonitoring()->getView()->getCanvasView();
  DQMCanvasArea *pCurrentCanvasArea = pCanvasView->getCurrentCanvasArea();
  QList<DQMCanvasArea*> canvasAreaList = pCanvasView->canvasAreaList();
  if(canvasAreaList.count() == 1)
    pMoveToCanvasAreaMenu->setEnabled(false);
  else
  {
    for(int i=0 ; i<canvasAreaList.count() ; i++)
    {
      DQMCanvasArea *pCanvasArea = canvasAreaList.at(i);
      if(pCanvasArea == pCurrentCanvasArea)
        continue;
      QAction *pAction = pMoveToCanvasAreaMenu->addAction(pCanvasView->getCanvasAreaName(i).c_str(), this,
      SLOT(moveCanvas()));
      pAction->setData(i);
    }
  }
  pContextMenu->addAction("Update", this, SLOT(queryUpdate()));
  pContextMenu->addAction("Remove", this, SLOT(removeCanvas()));
  pContextMenu->addSeparator();
  QMenu *pSetDrawOptionMenu = pContextMenu->addMenu("Set draw option");
  if(!this->getCurrentMonitorElement())
  {
    pSetDrawOptionMenu->setEnabled(false);
  }
  else
  {
    pSetDrawOptionMenu->addAction(this->getCurrentMonitorElement()->getMonitorElement()->getDrawOption().
      c_str(), this, SLOT(setDrawOption()));
    pSetDrawOptionMenu->addSeparator();
    this->addDrawOptions(pSetDrawOptionMenu);
  }
    pContextMenu->addAction("UnZoom", this, SLOT(unzoom()));
    pContextMenu->addAction("Save as", this, SLOT(saveAs()));
    pContextMenu->addAction("ROOT Panel", this, SLOT(openROOTPanel()));
    pContextMenu->addSeparator();
    pContextMenu->addAction("Show info", this, SLOT(showMonitorElementInfo()));
    pContextMenu->addAction("QTest results", this, SLOT(showQTestResults()));
  return pContextMenu;
}
void dqm4hep::DQMRootWidget::draw (DQMGuiMonitorElement * pMonitorElement) [virtual]
Draw the monitor element on the canvas.
Definition at line 141 of file DQMRootWidget.cc.
References drawNoVis(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), postDraw(), and updateMonitorElement().
Referenced by dqm4hep::DQMCanvas::draw(), redraw(), setDrawOption(), and setDrawOptionFromDialog().
{
  bool drawNoVis = (pMonitorElement == NULL ||
      pMonitorElement->getMonitorElement() == NULL ||
      pMonitorElement->getMonitorElement()->getObject() == NULL);
  if(drawNoVis)
  {
    this->drawNoVis();
    this->updateMonitorElement(pMonitorElement);
    return;
  }
  TObject *pObject = pMonitorElement->getMonitorElement()->getObject();
  const std::string &drawOption(pMonitorElement->getMonitorElement()->getDrawOption());
  if(pMonitorElement->getMonitorElement()->isHistogram())
  {
    TH1 *pHistogram = dynamic_cast<TH1*>(pObject);
    pHistogram->SetStats(0);
  }
  this->cd();
  pObject->Draw(drawOption.c_str());
  gPad->Update();
  this->postDraw();
  this->updateMonitorElement(pMonitorElement);
}
void dqm4hep::DQMRootWidget::drawNoVis () [virtual]
Draw an image saying `no vis available`.
Definition at line 130 of file DQMRootWidget.cc.
References getNoVisImage(), m_pCurrentMonitorElement, and postDraw().
Referenced by draw().
{
  TImage *pNoVisImage = this->getNoVisImage();
  this->GetCanvas()->cd();
  pNoVisImage->Draw();
  this->postDraw();
  m_pCurrentMonitorElement = NULL;
}
DQMCanvas * dqm4hep::DQMRootWidget::getCanvas () const
Get the canvas on which the the root widget is drawn.
Definition at line 88 of file DQMRootWidget.cc.
References m_pCanvas.
Referenced by moveCanvas(), removeCanvas(), saveAs(), and updateMonitorElement().
{
  return m_pCanvas;
}
DQMGuiMonitorElement * dqm4hep::DQMRootWidget::getCurrentMonitorElement () const [virtual]
Get the current monitor element draw on the root canvas.
Definition at line 173 of file DQMRootWidget.cc.
References m_pCurrentMonitorElement.
Referenced by createContextMenu(), dqm4hep::DQMCanvas::getCurrentMonitorElement(), openROOTPanel(), queryUpdate(), redraw(), setDrawOption(), setDrawOptionFromDialog(), showMonitorElementInfo(), showQTestResults(), unzoom(), and updateMonitorElement().
{
  return m_pCurrentMonitorElement;
}
DQMMonitoring * dqm4hep::DQMRootWidget::getMonitoring () const
Get the monitoring instance.
Definition at line 74 of file DQMRootWidget.cc.
References m_pMonitoring.
Referenced by createContextMenu(), moveCanvas(), openROOTPanel(), queryUpdate(), removeCanvas(), saveAs(), showMonitorElementInfo(), and showQTestResults().
{
  return m_pMonitoring;
}
TImage * dqm4hep::DQMRootWidget::getNoVisImage () [virtual]
Get the `no vis` image, create it if not (proxy method)
Definition at line 189 of file DQMRootWidget.cc.
References DQMViz_DIR, and m_pNoVisImage.
Referenced by drawNoVis().
{
  if(NULL == m_pNoVisImage)
  {
    std::string noVisFileName = std::string(DQMViz_DIR) + "/icons/NO_VIS.xpm";
    m_pNoVisImage = TImage::Open(noVisFileName.c_str());
    m_pNoVisImage->SetEditable(kFALSE);
    m_pNoVisImage->SetConstRatio(0);
  }
  return m_pNoVisImage;
}
void dqm4hep::DQMRootWidget::mouseDoubleClickEvent (QMouseEvent * e) [virtual]
Handle mouse double click event on the widget.
Definition at line 95 of file DQMRootWidget.cc.
References postDraw().
{
  TQtWidget::mouseDoubleClickEvent(e);
  this->postDraw();
}
void dqm4hep::DQMRootWidget::mouseReleaseEvent (QMouseEvent * e) [virtual]
Handle mouse release event on the widget.
Definition at line 103 of file DQMRootWidget.cc.
References postDraw().
{
  TQtWidget::mouseReleaseEvent(e);
  this->postDraw();
}
void dqm4hep::DQMRootWidget::moveCanvas () [private], [slot]
Definition at line 296 of file DQMRootWidget.cc.
References getCanvas(), dqm4hep::DQMMonitoringView::getCanvasView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), and dqm4hep::DQMCanvasView::moveCanvas().
Referenced by createContextMenu().
{
  QAction *pAction = (QAction*) sender();
  if(!pAction || !this->getCanvas())
    return;
  int index = pAction->data().toInt();
  DQMCanvasView *pCanvasView = this->getMonitoring()->getView()->getCanvasView();
  pCanvasView->moveCanvas(this->getCanvas(), index);
}
void dqm4hep::DQMRootWidget::openROOTPanel () [private], [slot]
Definition at line 391 of file DQMRootWidget.cc.
References dqm4hep::DQMMonitoring::getController(), getCurrentMonitorElement(), getMonitoring(), and dqm4hep::DQMMonitoringController::openInROOTWindow().
Referenced by createContextMenu().
{
  if(!this->getCurrentMonitorElement())
    return;
  this->getMonitoring()->getController()->openInROOTWindow(this->
      getCurrentMonitorElement());
}
void dqm4hep::DQMRootWidget::postDraw () [virtual]
Post draw function with a 'fake' update of the widget.
Definition at line 111 of file DQMRootWidget.cc.
Referenced by draw(), drawNoVis(), mouseDoubleClickEvent(), mouseReleaseEvent(), and unzoom().
{
  // fake update triggered by object resize
  QSize currentSize = size();
  currentSize.setHeight(currentSize.height()+1);
  currentSize.setWidth(currentSize.width()+1);
  resize(currentSize);
  currentSize.setHeight(currentSize.height()-1);
  currentSize.setWidth(currentSize.width()-1);
  resize(currentSize);
  GetCanvas()->Resize();
  Refresh();
}
void dqm4hep::DQMRootWidget::queryUpdate () [private], [slot]
Definition at line 310 of file DQMRootWidget.cc.
References dqm4hep::DQMMonitoring::getController(), getCurrentMonitorElement(), getMonitoring(), and dqm4hep::DQMMonitoringController::queryUpdate().
Referenced by createContextMenu().
{
  if(!this->getCurrentMonitorElement())
    return;
  this->getMonitoring()->getController()->queryUpdate(this->
      getCurrentMonitorElement());
}
void dqm4hep::DQMRootWidget::redraw () [private], [slot]
Definition at line 421 of file DQMRootWidget.cc.
References draw(), and getCurrentMonitorElement().
Referenced by updateMonitorElement().
{
  if(!this->getCurrentMonitorElement())
    return;
  this->draw(this->getCurrentMonitorElement());
}
void dqm4hep::DQMRootWidget::removeCanvas () [private], [slot]
Definition at line 320 of file DQMRootWidget.cc.
References getCanvas(), dqm4hep::DQMMonitoringView::getCanvasView(), dqm4hep::DQMCanvasView::getCurrentCanvasArea(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), and dqm4hep::DQMCanvasArea::removeCanvas().
Referenced by createContextMenu(), and updateMonitorElement().
{
  if(!this->getCanvas())
    return;
  this->getMonitoring()->getView()->getCanvasView()->getCurrentCanvasArea()->
      removeCanvas(this->getCanvas(), true);
}
void dqm4hep::DQMRootWidget::saveAs () [private], [slot]
Definition at line 384 of file DQMRootWidget.cc.
References getCanvas(), dqm4hep::DQMMonitoring::getController(), getMonitoring(), and dqm4hep::DQMMonitoringController::saveAs().
Referenced by createContextMenu().
{
  this->getMonitoring()->getController()->saveAs(this->getCanvas());
}
void dqm4hep::DQMRootWidget::setCanvas (DQMCanvas * pCanvas)
Set canvas on which the the root widget is drawn.
Definition at line 81 of file DQMRootWidget.cc.
References m_pCanvas.
Referenced by dqm4hep::DQMCanvas::DQMCanvas().
{
  m_pCanvas = pCanvas;
}
void dqm4hep::DQMRootWidget::setDrawOption () [private], [slot]
Definition at line 330 of file DQMRootWidget.cc.
References draw(), getCurrentMonitorElement(), and dqm4hep::DQMGuiMonitorElement::setDrawOption().
Referenced by addDrawOptions(), and createContextMenu().
{
  QAction *pDrawOptionAction = qobject_cast<QAction*>(sender());
  if(!pDrawOptionAction || !this->getCurrentMonitorElement())
    return;
  this->getCurrentMonitorElement()->setDrawOption(pDrawOptionAction->text().toStdString());
  this->draw(this->getCurrentMonitorElement());
}
void dqm4hep::DQMRootWidget::setDrawOptionFromDialog () [private], [slot]
Definition at line 343 of file DQMRootWidget.cc.
References draw(), getCurrentMonitorElement(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), and dqm4hep::DQMGuiMonitorElement::setDrawOption().
Referenced by addDrawOptions().
{
  if(!this->getCurrentMonitorElement())
    return;
    bool ok = false;
    QString oldDrawOption = this->getCurrentMonitorElement()->getMonitorElement()->getDrawOption().c_str();
    QString newDrawOption = QInputDialog::getText(this, "Set draw option",
                                               "", QLineEdit::Normal,
                                               oldDrawOption, &ok);
    if(ok)
    {
      this->getCurrentMonitorElement()->setDrawOption(newDrawOption.toStdString());
      this->draw(this->getCurrentMonitorElement());
    }
}
void dqm4hep::DQMRootWidget::showContextMenu (const QPoint & point) [private], [slot]
Definition at line 180 of file DQMRootWidget.cc.
References createContextMenu().
Referenced by DQMRootWidget().
{
    QMenu *pContextMenu = this->createContextMenu();
    pContextMenu->exec(this->mapToGlobal(point));
    pContextMenu->deleteLater();
}
void dqm4hep::DQMRootWidget::showMonitorElementInfo () [private], [slot]
Definition at line 401 of file DQMRootWidget.cc.
References dqm4hep::DQMMonitoring::getController(), getCurrentMonitorElement(), getMonitoring(), and dqm4hep::DQMMonitoringController::openMonitorElementInfo().
Referenced by createContextMenu().
{
  if(!this->getCurrentMonitorElement())
    return;
  this->getMonitoring()->getController()->openMonitorElementInfo(this->
      getCurrentMonitorElement());
}
void dqm4hep::DQMRootWidget::showQTestResults () [private], [slot]
Definition at line 411 of file DQMRootWidget.cc.
References dqm4hep::DQMMonitoring::getController(), getCurrentMonitorElement(), getMonitoring(), and dqm4hep::DQMMonitoringController::openQualityTestResults().
Referenced by createContextMenu().
{
  if(!this->getCurrentMonitorElement())
    return;
  this->getMonitoring()->getController()->openQualityTestResults(this->
      getCurrentMonitorElement());
}
void dqm4hep::DQMRootWidget::unzoom () [private], [slot]
Definition at line 364 of file DQMRootWidget.cc.
References getCurrentMonitorElement(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), and postDraw().
Referenced by createContextMenu().
{
  if(!this->getCurrentMonitorElement())
    return;
  TH1 *pHistogram = this->getCurrentMonitorElement()->getMonitorElement()->get<TH1>();
  if(pHistogram)
  {
    this->GetCanvas()->cd();
    pHistogram->GetXaxis()->UnZoom();
    pHistogram->GetYaxis()->UnZoom();
    this->GetCanvas()->Modified();
    this->GetCanvas()->Update();
    this->postDraw();
  }
}
void dqm4hep::DQMRootWidget::updateMonitorElement (DQMGuiMonitorElement * pNewGuiMonitorElement) [protected]
Definition at line 431 of file DQMRootWidget.cc.
References getCanvas(), dqm4hep::DQMMonitoring::getController(), getCurrentMonitorElement(), dqm4hep::DQMMonitoringController::getIcon(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), dqm4hep::DQMCanvas::getMonitoring(), m_pCurrentMonitorElement, redraw(), and removeCanvas().
Referenced by draw().
{
  DQMGuiMonitorElement *pCurrentGuiMonitorElement = this->
      getCurrentMonitorElement();
  if(pCurrentGuiMonitorElement == pNewGuiMonitorElement)
    return;
  if(NULL != pCurrentGuiMonitorElement)
  {
    QObject::disconnect(pCurrentGuiMonitorElement, SIGNAL(destroyed()), this, SLOT(
      removeCanvas()));
    QObject::disconnect(pCurrentGuiMonitorElement, SIGNAL(updated()), this, SLOT(
      redraw()));
  }
  m_pCurrentMonitorElement = pNewGuiMonitorElement;
  if(pNewGuiMonitorElement)
  {
    QObject::connect(pNewGuiMonitorElement, SIGNAL(destroyed()), this, SLOT(
      removeCanvas()));
    QObject::connect(pNewGuiMonitorElement, SIGNAL(updated()), this, SLOT(redraw()));
    DQMCanvas *pCanvas = this->getCanvas();
    pCanvas->setWindowTitle(pNewGuiMonitorElement->getMonitorElement()->getTitle().c_str());
    pCanvas->setWindowIcon(pCanvas->getMonitoring()->getController()->getIcon(pNewGuiMonitorElement->
      getMonitorElement()->getQuality()));
  }
}
Member Data Documentation
DQMCanvas* dqm4hep::DQMRootWidget::m_pCanvas [protected]
Definition at line 170 of file DQMRootWidget.h.
Referenced by getCanvas(), and setCanvas().
DQMGuiMonitorElement* dqm4hep::DQMRootWidget::m_pCurrentMonitorElement [protected]
Definition at line 172 of file DQMRootWidget.h.
Referenced by drawNoVis(), getCurrentMonitorElement(), and updateMonitorElement().
DQMMonitoring* dqm4hep::DQMRootWidget::m_pMonitoring [protected]
Definition at line 169 of file DQMRootWidget.h.
Referenced by getMonitoring().
TImage* dqm4hep::DQMRootWidget::m_pNoVisImage [protected]
Definition at line 171 of file DQMRootWidget.h.
Referenced by getNoVisImage(), and ~DQMRootWidget().
The documentation for this class was generated from the following files:
DQMRootWidget.h
DQMRootWidget.cc