dqm4hep::DQMMonitorElementView Class Reference
DQMMonitorElementView class.
#include <DQMMonitorElementView.h>
Public Slots
void addMonitorElement (DQMGuiMonitorElement *pMonitorElement)
Add a monitor element to the view.
void removeMonitorElement (DQMGuiMonitorElement *pGuiMonitorElement)
Remove a monitor element from the view.
void updateMonitorElement (DQMGuiMonitorElement *pMonitorElement)
Update the monitor element.
void replaceMonitorElement (DQMGuiMonitorElement *pOldMonitorElement, DQMGuiMonitorElement *pNewMonitorElement)
void clear ()
void clear (const std::string &collectorName)
Public Member Functions
DQMMonitorElementView (DQMMonitoring *pMonitoring)
Constructor.
virtual ~DQMMonitorElementView ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
QStringList getCollectorNames () const
QList< QTreeWidgetItem * > getCheckedMonitorElements () const
QList< QTreeWidgetItem * > getCheckedMonitorElements (const std::string &collectorName) const
void uncheckAllMonitorElements (const std::string &collectorName)
void enableSubscription (const std::string &collectorName, bool enable=true)
Enable subscription of monitor elements.
TiXmlElement * toXml () const
Export settings to xml element.
void fromXml (TiXmlElement *const pXmlElement)
Import settings from xml element.
Private Slots
void handleMonitorElementUpdate ()
void handleMonitorElementDeletion ()
Private Attributes
DQMMonitoring * m_pMonitoring
QToolBox * m_pToolBox
Detailed Description
DQMMonitorElementView class.
Definition at line 263 of file DQMMonitorElementView.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElementView::DQMMonitorElementView (DQMMonitoring * pMonitoring)
Constructor.
Definition at line 1196 of file DQMMonitorElementView.cc.
References m_pToolBox.
                                                                       :
    m_pMonitoring(pMonitoring)
{
  setLayout(new QVBoxLayout());
  m_pToolBox = new QToolBox();
  layout()->addWidget(m_pToolBox);
}
dqm4hep::DQMMonitorElementView::~DQMMonitorElementView () [virtual]
Destructor.
Definition at line 1207 of file DQMMonitorElementView.cc.
{
  /* nop */
}
Member Function Documentation
void dqm4hep::DQMMonitorElementView::addMonitorElement (DQMGuiMonitorElement * pMonitorElement) [slot]
Add a monitor element to the view.
Definition at line 1410 of file DQMMonitorElementView.cc.
References updateMonitorElement().
Referenced by dqm4hep::DQMMonitoringModel::getOrCreateGuiMonitorElement(), dqm4hep::DQMMonitoringModel::loadMonitorElementInfoList(), and dqm4hep::DQMMonitoringModel::updateMonitorElement().
{
  this->updateMonitorElement(pMonitorElement);
}
void dqm4hep::DQMMonitorElementView::clear () [slot]
Definition at line 1473 of file DQMMonitorElementView.cc.
References dqm4hep::DQMMonitorElementNavigator::clear(), and m_pToolBox.
Referenced by dqm4hep::DQMMonitoringView::clear(), and fromXml().
{
  for(int i=0 ; i<m_pToolBox->count() ; i++)
  {
    DQMMonitorElementNavigator *pNavigator = qobject_cast<DQMMonitorElementNavigator*>(
      m_pToolBox->widget(i));
    pNavigator->clear();
    m_pToolBox->removeItem(i);
    pNavigator->deleteLater();
  }
}
void dqm4hep::DQMMonitorElementView::clear (const std::string & collectorName) [slot]
Definition at line 1486 of file DQMMonitorElementView.cc.
References dqm4hep::DQMMonitorElementNavigator::clear(), and m_pToolBox.
{
  for(int i=0 ; i<m_pToolBox->count() ; i++)
  {
    if(m_pToolBox->itemText(i) == QString(collectorName.c_str()))
    {
      DQMMonitorElementNavigator *pNavigator = qobject_cast<DQMMonitorElementNavigator*>(
      m_pToolBox->widget(i));
      pNavigator->clear();
      break;
    }
  }
}
void dqm4hep::DQMMonitorElementView::enableSubscription (const std::string & collectorName, bool enable = true)
Enable subscription of monitor elements.
Definition at line 1285 of file DQMMonitorElementView.cc.
References dqm4hep::DQMMonitorElementNavigator::enableSubscription(), and m_pToolBox.
Referenced by dqm4hep::DQMMonitoringController::handleServerShutdown(), and dqm4hep::DQMMonitoringController::handleServerStartup().
{
  for(int i=0 ; i<m_pToolBox->count() ; i++)
  {
    if(m_pToolBox->itemText(i).toStdString() == collectorName)
    {
      DQMMonitorElementNavigator *pNavigator = qobject_cast<DQMMonitorElementNavigator*>(
      m_pToolBox->widget(i));
      pNavigator->enableSubscription(enable);
      break;
    }
  }
}
void dqm4hep::DQMMonitorElementView::fromXml (TiXmlElement *const pXmlElement)
Import settings from xml element.
Definition at line 1351 of file DQMMonitorElementView.cc.
References dqm4hep::DQMMonitorElementNavigator::addMonitorElement(), clear(), getMonitoring(), m_pToolBox, and dqm4hep::DQMMonitorElementNavigator::mkdir().
Referenced by dqm4hep::DQMMonitoringView::fromXml().
{
  if(!pXmlElement)
    return;
  this->clear();
    TiXmlHandle elementHandle(pXmlElement);
    for (TiXmlElement *pCollectorElement = elementHandle.FirstChild("collector").Element(); NULL !=
      pCollectorElement;
        pCollectorElement = pCollectorElement->NextSiblingElement("collector"))
    {
      std::string collectorName;
        if(pCollectorElement->QueryStringAttribute("name", &collectorName))
            continue;
        DQMMonitorElementNavigator *pNavigator = new DQMMonitorElementNavigator(collectorName.c_str(),
      this->getMonitoring());
    m_pToolBox->addItem(pNavigator, collectorName.c_str());
        TiXmlHandle collectorHandle(pCollectorElement);
        for (TiXmlElement *pModuleElement = collectorHandle.FirstChild("module").Element(); NULL !=
      pModuleElement;
            pModuleElement = pModuleElement->NextSiblingElement("module"))
        {
          std::string moduleName;
            if(pModuleElement->QueryStringAttribute("name", &moduleName))
                continue;
            QTreeWidgetItem *pModuleItem = pNavigator->mkdir(moduleName.c_str());
            TiXmlHandle moduleHandle(pModuleElement);
            for (TiXmlElement *pItemElement = moduleHandle.FirstChild("item").Element(); NULL !=
      pItemElement;
                pItemElement = pItemElement->NextSiblingElement("item"))
            {
              std::string name;
                if(pItemElement->QueryStringAttribute("name", &name))
                    continue;
              std::string path;
                if(pItemElement->QueryStringAttribute("path", &path))
                    continue;
              bool checked = false;
                if(pItemElement->QueryValueAttribute("checked", &checked))
                    continue;
                QTreeWidgetItem *pDirectoryItem = pNavigator->mkdir(moduleName.c_str(), path.c_str());
                QTreeWidgetItem *pMonitorElementItem = pNavigator->addMonitorElement(pDirectoryItem, name.
      c_str());
                if(pMonitorElementItem)
                  pMonitorElementItem->setCheckState(0, checked ? Qt::Checked : Qt::Unchecked);
            }
        }
    }
}
QList< QTreeWidgetItem * > dqm4hep::DQMMonitorElementView::getCheckedMonitorElements () const
Definition at line 1233 of file DQMMonitorElementView.cc.
References dqm4hep::DQMMonitorElementNavigator::getCheckedMonitorElements(), and m_pToolBox.
Referenced by dqm4hep::DQMMonitoringController::handleServerStartup().
{
  QList<QTreeWidgetItem*> checkedMonitorElements;
  for(int i=0 ; i<m_pToolBox->count() ; i++)
  {
    DQMMonitorElementNavigator *pNavigator = qobject_cast<DQMMonitorElementNavigator*>(
      m_pToolBox->widget(i));
    checkedMonitorElements.append(pNavigator->getCheckedMonitorElements());
  }
  return checkedMonitorElements;
}
QList< QTreeWidgetItem * > dqm4hep::DQMMonitorElementView::getCheckedMonitorElements (const std::string & collectorName) const
Definition at line 1248 of file DQMMonitorElementView.cc.
References dqm4hep::DQMMonitorElementNavigator::getCheckedMonitorElements(), and m_pToolBox.
{
  QList<QTreeWidgetItem*> checkedMonitorElements;
  DQMMonitorElementNavigator *pNavigator = NULL;
  for(int i=0 ; i<m_pToolBox->count() ; i++)
  {
    if(m_pToolBox->itemText(i).toStdString() == collectorName)
    {
      pNavigator = qobject_cast<DQMMonitorElementNavigator*>(m_pToolBox->widget(i));
      break;
    }
  }
  if(NULL == pNavigator)
    return checkedMonitorElements;
  return pNavigator->getCheckedMonitorElements();
}
QStringList dqm4hep::DQMMonitorElementView::getCollectorNames () const
Definition at line 1221 of file DQMMonitorElementView.cc.
References m_pToolBox.
{
  QStringList collectorNames;
  for(int i=0 ; i<m_pToolBox->count() ; i++)
    collectorNames << m_pToolBox->itemText(i);
  return collectorNames;
}
DQMMonitoring * dqm4hep::DQMMonitorElementView::getMonitoring () const
Get the monitoring instance.
Definition at line 1214 of file DQMMonitorElementView.cc.
References m_pMonitoring.
Referenced by fromXml(), and updateMonitorElement().
{
  return m_pMonitoring;
}
void dqm4hep::DQMMonitorElementView::handleMonitorElementDeletion () [private], [slot]
Definition at line 1509 of file DQMMonitorElementView.cc.
References removeMonitorElement().
{
  DQMGuiMonitorElement *pGuiMonitorElement = qobject_cast<DQMGuiMonitorElement*>(sender());
  this->removeMonitorElement(pGuiMonitorElement);
}
void dqm4hep::DQMMonitorElementView::handleMonitorElementUpdate () [private], [slot]
Definition at line 1501 of file DQMMonitorElementView.cc.
References updateMonitorElement().
{
  DQMGuiMonitorElement *pGuiMonitorElement = qobject_cast<DQMGuiMonitorElement*>(sender());
  this->updateMonitorElement(pGuiMonitorElement);
}
void dqm4hep::DQMMonitorElementView::removeMonitorElement (DQMGuiMonitorElement * pGuiMonitorElement) [slot]
Remove a monitor element from the view.
Definition at line 1417 of file DQMMonitorElementView.cc.
References dqm4hep::DQMGuiMonitorElement::getMonitorElement(), m_pToolBox, and dqm4hep::DQMMonitorElementNavigator::removeMonitorElement().
Referenced by dqm4hep::DQMMonitoringModel::clear(), handleMonitorElementDeletion(), and dqm4hep::DQMMonitoringModel::removeMonitorElement().
{
  QString collectorName = pMonitorElement->getMonitorElement()->getCollectorName().c_str();
  DQMMonitorElementNavigator *pNavigator = NULL;
  for(int i=0 ; i<m_pToolBox->count() ; i++)
  {
    if(m_pToolBox->itemText(i) == collectorName)
    {
      pNavigator = qobject_cast<DQMMonitorElementNavigator*>(m_pToolBox->widget(i));
      break;
    }
  }
  if(NULL == pNavigator)
    return;
  pNavigator->removeMonitorElement(pMonitorElement);
}
void dqm4hep::DQMMonitorElementView::replaceMonitorElement (DQMGuiMonitorElement * pOldMonitorElement, DQMGuiMonitorElement * pNewMonitorElement) [slot]
Definition at line 1466 of file DQMMonitorElementView.cc.
References updateMonitorElement().
{
  this->updateMonitorElement(pNewMonitorElement);
}
TiXmlElement * dqm4hep::DQMMonitorElementView::toXml () const
Export settings to xml element.
Definition at line 1300 of file DQMMonitorElementView.cc.
References dqm4hep::DQMMonitorElementNavigator::getAllMonitorElementItems(), dqm4hep::DQMMonitorElementNavigator::getFullPathName(), dqm4hep::DQMMonitorElementNavigator::getModuleNames(), and m_pToolBox.
Referenced by dqm4hep::DQMMonitoringView::toXml().
{
  TiXmlElement *pXmlElement = new TiXmlElement("meView");
  // loop over collectors
  for(int c=0 ; c<m_pToolBox->count() ; c++)
  {
    TiXmlElement *pCollectorElement = new TiXmlElement("collector");
    pXmlElement->LinkEndChild(pCollectorElement);
    std::string collectorName = m_pToolBox->itemText(c).toStdString();
    pCollectorElement->SetAttribute("name", collectorName);
    DQMMonitorElementNavigator *pNavigator = qobject_cast<DQMMonitorElementNavigator*>(
      m_pToolBox->widget(c));
    QStringList moduleNames = pNavigator->getModuleNames();
    for(int m=0 ; m<moduleNames.count() ; m++)
    {
      QString moduleName(moduleNames.at(m));
      TiXmlElement *pModuleElement = new TiXmlElement("module");
      pCollectorElement->LinkEndChild(pModuleElement);
      pModuleElement->SetAttribute("name", moduleName.toStdString());
      QList<QTreeWidgetItem*> monitorElementItems = pNavigator->getAllMonitorElementItems(moduleName);
      for(int i=0 ; i<monitorElementItems.count() ; i++)
      {
        QTreeWidgetItem *pMonitorElementItem = monitorElementItems.at(i);
        QString fullPath(pNavigator->getFullPathName(pMonitorElementItem));
        QString name(pMonitorElementItem->text(0));
        bool checked(pMonitorElementItem->checkState(0) == Qt::Checked);
        TiXmlElement *pItemElement = new TiXmlElement("item");
        pModuleElement->LinkEndChild(pItemElement);
        pItemElement->SetAttribute("path", fullPath.toStdString());
        pItemElement->SetAttribute("name", name.toStdString());
        pItemElement->SetAttribute("checked", checked);
      }
    }
  }
  return pXmlElement;
}
void dqm4hep::DQMMonitorElementView::uncheckAllMonitorElements (const std::string & collectorName)
Definition at line 1270 of file DQMMonitorElementView.cc.
References m_pToolBox, and dqm4hep::DQMMonitorElementNavigator::uncheckAllMonitorElements().
Referenced by dqm4hep::DQMMonitoringController::handleServerShutdown().
{
  for(int i=0 ; i<m_pToolBox->count() ; i++)
  {
    if(m_pToolBox->itemText(i).toStdString() == collectorName)
    {
      DQMMonitorElementNavigator *pNavigator = qobject_cast<DQMMonitorElementNavigator*>(
      m_pToolBox->widget(i));
      pNavigator->uncheckAllMonitorElements();
      break;
    }
  }
}
void dqm4hep::DQMMonitorElementView::updateMonitorElement (DQMGuiMonitorElement * pMonitorElement) [slot]
Update the monitor element.
Definition at line 1440 of file DQMMonitorElementView.cc.
References dqm4hep::DQMGuiMonitorElement::getMonitorElement(), getMonitoring(), m_pToolBox, and dqm4hep::DQMMonitorElementNavigator::updateMonitorElement().
Referenced by addMonitorElement(), handleMonitorElementUpdate(), replaceMonitorElement(), and dqm4hep::DQMMonitoringModel::updateMonitorElement().
{
  QString collectorName = pMonitorElement->getMonitorElement()->getCollectorName().c_str();
  DQMMonitorElementNavigator *pNavigator = NULL;
  for(int i=0 ; i<m_pToolBox->count() ; i++)
  {
    if(m_pToolBox->itemText(i) == collectorName)
    {
      pNavigator = qobject_cast<DQMMonitorElementNavigator*>(m_pToolBox->widget(i));
      break;
    }
  }
  if(NULL == pNavigator)
  {
    pNavigator = new DQMMonitorElementNavigator(collectorName, this->
      getMonitoring());
    m_pToolBox->addItem(pNavigator, collectorName);
  }
  pNavigator->updateMonitorElement(pMonitorElement);
}
Member Data Documentation
DQMMonitoring* dqm4hep::DQMMonitorElementView::m_pMonitoring [private]
Definition at line 344 of file DQMMonitorElementView.h.
Referenced by getMonitoring().
QToolBox* dqm4hep::DQMMonitorElementView::m_pToolBox [private]
Definition at line 345 of file DQMMonitorElementView.h.
Referenced by clear(), DQMMonitorElementView(), enableSubscription(), fromXml(), getCheckedMonitorElements(), getCollectorNames(), removeMonitorElement(), toXml(), uncheckAllMonitorElements(), and updateMonitorElement().
The documentation for this class was generated from the following files:
DQMMonitorElementView.h
DQMMonitorElementView.cc