dqm4hep::DQMGuiMonitorElementClient Class Reference
DQMGuiMonitorElementClient class.
#include <DQMGuiMonitorElementClient.h>
Signals
void collectorInfoReceived (const DQMCollectorInfo &)
Qt signal emitted when the dim handler receives a collector info structure.
void monitorElementListNameReceived (const DQMMonitorElementInfoList &)
Qt signal emitted when the dim handler receives an info list on monitor elements.
void monitorElementPublicationReceived (const DQMMonitorElementPublication &)
Qt signal emitted when the dim handler receives a monitor element publication.
void onMonitorElementClientConnect ()
Qt signal emitted when the client is connected.
void onMonitorElementClientDisconnect ()
Qt signal emitted when the client is disconnected.
void onServerStartup ()
Qt signal emitted when the collector server is started.
void onServerShutdown ()
Qt signal emitted when the collector server is shut down.
Public Member Functions
DQMGuiMonitorElementClient (const std::string &collectorName)
Constructor.
virtual ~DQMGuiMonitorElementClient ()
Destructor.
DQMMonitorElementClient * getMonitorElementClient () const
Get the monitor element client instance (dqm core class)
Private Member Functions
void onMonitorElementClientConnect (DQMMonitorElementClient *)
void onMonitorElementClientDisconnect (DQMMonitorElementClient *)
void onServerStartup (DQMMonitorElementClient *)
void onServerShutdown (DQMMonitorElementClient *)
void availableMonitorElementListReceived (DQMMonitorElementClient *, const DQMMonitorElementInfoList &)
void monitorElementCollectorInfoReceived (DQMMonitorElementClient *, const DQMCollectorInfo &)
void monitorElementsReceived (DQMMonitorElementClient *, DQMMonitorElementPublication &)
Private Attributes
DQMMonitorElementClient * m_pMonitorElementClient
DQMMonitorElementPublication m_publication
Detailed Description
DQMGuiMonitorElementClient class.
Definition at line 42 of file DQMGuiMonitorElementClient.h.
Constructor & Destructor Documentation
dqm4hep::DQMGuiMonitorElementClient::DQMGuiMonitorElementClient (const std::string & collectorName)
Constructor.
Definition at line 34 of file DQMGuiMonitorElementClient.cc.
References m_pMonitorElementClient.
                                                                                     :
    m_pMonitorElementClient(NULL)
{
  m_pMonitorElementClient = new DQMMonitorElementClient();
  m_pMonitorElementClient->addListener(this);
  m_pMonitorElementClient->setCollectorName(collectorName);
}
dqm4hep::DQMGuiMonitorElementClient::~DQMGuiMonitorElementClient () [virtual]
Destructor.
Definition at line 44 of file DQMGuiMonitorElementClient.cc.
References m_pMonitorElementClient.
{
  delete m_pMonitorElementClient;
}
Member Function Documentation
void dqm4hep::DQMGuiMonitorElementClient::availableMonitorElementListReceived (DQMMonitorElementClient * , const DQMMonitorElementInfoList & infoList) [private]
Definition at line 65 of file DQMGuiMonitorElementClient.cc.
References monitorElementListNameReceived().
{
  emit monitorElementListNameReceived(infoList);
}
void dqm4hep::DQMGuiMonitorElementClient::collectorInfoReceived (const DQMCollectorInfo &) [signal]
Qt signal emitted when the dim handler receives a collector info structure.
Referenced by monitorElementCollectorInfoReceived().
DQMMonitorElementClient * dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient () const
Get the monitor element client instance (dqm core class)
Definition at line 51 of file DQMGuiMonitorElementClient.cc.
References m_pMonitorElementClient.
Referenced by dqm4hep::DQMBrowserWidget::handleCollectorSelection(), dqm4hep::DQMMonitoringController::handleServerShutdown(), dqm4hep::DQMMonitoringController::handleServerStartup(), dqm4hep::DQMBrowserWidget::querySearch(), dqm4hep::DQMMonitoringController::querySubscribedMonitorElements(), dqm4hep::DQMMonitoringController::subscribe(), and dqm4hep::DQMMonitoringController::unsubscribe().
{
  return m_pMonitorElementClient;
}
void dqm4hep::DQMGuiMonitorElementClient::monitorElementCollectorInfoReceived (DQMMonitorElementClient * , const DQMCollectorInfo & collectorInfo) [private]
Definition at line 58 of file DQMGuiMonitorElementClient.cc.
References collectorInfoReceived().
{
  emit collectorInfoReceived(collectorInfo);
}
void dqm4hep::DQMGuiMonitorElementClient::monitorElementListNameReceived (const DQMMonitorElementInfoList &) [signal]
Qt signal emitted when the dim handler receives an info list on monitor elements.
Referenced by availableMonitorElementListReceived().
void dqm4hep::DQMGuiMonitorElementClient::monitorElementPublicationReceived (const DQMMonitorElementPublication &) [signal]
Qt signal emitted when the dim handler receives a monitor element publication.
Referenced by monitorElementsReceived().
void dqm4hep::DQMGuiMonitorElementClient::monitorElementsReceived (DQMMonitorElementClient * , DQMMonitorElementPublication & publication) [private]
Definition at line 72 of file DQMGuiMonitorElementClient.cc.
References monitorElementPublicationReceived().
{
  // get copy of publication and clear the one in argument
  DQMMonitorElementPublication publicationCopy(publication);
  publication.clear();
  emit monitorElementPublicationReceived(publicationCopy);
}
void dqm4hep::DQMGuiMonitorElementClient::onMonitorElementClientConnect () [signal]
Qt signal emitted when the client is connected.
Referenced by onMonitorElementClientConnect().
void dqm4hep::DQMGuiMonitorElementClient::onMonitorElementClientConnect (DQMMonitorElementClient *) [private]
Definition at line 82 of file DQMGuiMonitorElementClient.cc.
References onMonitorElementClientConnect().
{
  emit onMonitorElementClientConnect();
}
void dqm4hep::DQMGuiMonitorElementClient::onMonitorElementClientDisconnect () [signal]
Qt signal emitted when the client is disconnected.
Referenced by onMonitorElementClientDisconnect().
void dqm4hep::DQMGuiMonitorElementClient::onMonitorElementClientDisconnect (DQMMonitorElementClient *) [private]
Definition at line 89 of file DQMGuiMonitorElementClient.cc.
References onMonitorElementClientDisconnect().
{
  emit onMonitorElementClientDisconnect();
}
void dqm4hep::DQMGuiMonitorElementClient::onServerShutdown () [signal]
Qt signal emitted when the collector server is shut down.
Referenced by onServerShutdown().
void dqm4hep::DQMGuiMonitorElementClient::onServerShutdown (DQMMonitorElementClient *) [private]
Definition at line 103 of file DQMGuiMonitorElementClient.cc.
References onServerShutdown().
{
  emit onServerShutdown();
}
void dqm4hep::DQMGuiMonitorElementClient::onServerStartup () [signal]
Qt signal emitted when the collector server is started.
Referenced by onServerStartup().
void dqm4hep::DQMGuiMonitorElementClient::onServerStartup (DQMMonitorElementClient *) [private]
Definition at line 96 of file DQMGuiMonitorElementClient.cc.
References onServerStartup().
{
  emit onServerStartup();
}
Member Data Documentation
DQMMonitorElementClient* dqm4hep::DQMGuiMonitorElementClient::m_pMonitorElementClient [private]
Definition at line 98 of file DQMGuiMonitorElementClient.h.
Referenced by DQMGuiMonitorElementClient(), getMonitorElementClient(), and ~DQMGuiMonitorElementClient().
DQMMonitorElementPublication dqm4hep::DQMGuiMonitorElementClient::m_publication [private]
Definition at line 99 of file DQMGuiMonitorElementClient.h.
The documentation for this class was generated from the following files:
DQMGuiMonitorElementClient.h
DQMGuiMonitorElementClient.cc