dqm4hep::DQMBrowserWidget Class Reference
DQMBrowserWidget class.
#include <DQMBrowserWidget.h>
Public Slots
void updateCollectorList ()
Update the collector list (combo box)
Signals
void keyPressEvent (QKeyEvent *)
Key pressed event emitted in the tree widget.
Public Member Functions
DQMBrowserWidget (DQMMonitoring *pMonitoring)
Constructor.
~DQMBrowserWidget ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
QString getCollectorName () const
Get the collector name.
Private Slots
void handleCollectorSelection (int index)
void querySearch ()
Send the query for monitor element browsing on the collector.
void clearSearch ()
Clear the search interface.
void fillModuleNameList (const DQMMonitorElementInfoList &nameList)
Fill the module name list.
void checkItem (QTreeWidgetItem *pItem, int)
Check/uncheck the given item.
void checkSelectedElements ()
Check all the selected items.
void handleKeyPressEvent (QKeyEvent *pKeyEvent)
Handle the key press event.
void selectAllElements ()
Select all items.
void handleUpdateButtonClicked ()
void handleReplaceButtonClicked ()
Private Member Functions
void buildMonitorElementInfoList (DQMMonitorElementInfoList &infoList) const
Build the monitor element info list of the current selection.
Private Attributes
DQMMonitoring * m_pMonitoring
QComboBox * m_pCollectorNameComboBox
QLineEdit * m_pModuleNameEdit
QLineEdit * m_pMonitorElementNameEdit
QComboBox * m_pMonitorElementTypeComboBox
QTreeWidget * m_pSearchTreeWidget
QGroupBox * m_pOptionGroupBox
QPushButton * m_pReplaceButton
QPushButton * m_pAppendButton
QPushButton * m_pCloseButton
DQMGuiMonitorElementClient * m_pMonitorElementClient
Detailed Description
DQMBrowserWidget class.
A browser to find monitor elements over the network. Uses a DimBrowser to perform the service finding, a monitor element client as the interface to the server and a qt handler for request call back functions received by the server.
Definition at line 58 of file DQMBrowserWidget.h.
Constructor & Destructor Documentation
dqm4hep::DQMBrowserWidget::DQMBrowserWidget (DQMMonitoring * pMonitoring)
Constructor.
Definition at line 55 of file DQMBrowserWidget.cc.
References checkItem(), clearSearch(), handleCollectorSelection(), handleKeyPressEvent(), handleReplaceButtonClicked(), handleUpdateButtonClicked(), keyPressEvent(), m_pAppendButton, m_pCloseButton, m_pCollectorNameComboBox, m_pModuleNameEdit, m_pMonitorElementNameEdit, m_pMonitorElementTypeComboBox, m_pOptionGroupBox, m_pReplaceButton, m_pSearchTreeWidget, querySearch(), and updateCollectorList().
                                                             :
    QWidget(0),
    m_pMonitoring(pMonitoring),
    m_pMonitorElementClient(NULL)
{
  setLayout(new QVBoxLayout());
  char *pDnsNode = getenv("DIM_DNS_NODE");
  QString dimDnsNode = pDnsNode == NULL ? "UNKNOWN" : pDnsNode;
  // monitor element collector
  QGroupBox *pCollectorGroupBox = new QGroupBox("Monitor element collectors (DIM_DNS_NODE = " + dimDnsNode
      + ")");
  QFormLayout *pCollectorLayout = new QFormLayout();
  pCollectorGroupBox->setLayout(pCollectorLayout);
  layout()->addWidget(pCollectorGroupBox);
  QWidget *pCollectorNameWidget = new QWidget();
  QHBoxLayout *pCollectorNameLayout = new QHBoxLayout();
  pCollectorNameWidget->setLayout(pCollectorNameLayout);
  pCollectorLayout->addRow("Monitor element collector : ", pCollectorNameWidget);
  m_pCollectorNameComboBox = new QComboBox();
  pCollectorNameLayout->addWidget(m_pCollectorNameComboBox);
  QPushButton *pUpdateCollectorListButton = new QPushButton("Update list");
  pUpdateCollectorListButton->setMaximumWidth(150);
  pCollectorNameLayout->addWidget(pUpdateCollectorListButton);
  // search options with form and buttons
  m_pOptionGroupBox = new QGroupBox("Search option", this);
  QFormLayout *pOptionFormLayout = new QFormLayout();
  m_pOptionGroupBox->setLayout(pOptionFormLayout);
  m_pModuleNameEdit = new QLineEdit();
  pOptionFormLayout->addRow("Module name", m_pModuleNameEdit);
  m_pMonitorElementNameEdit = new QLineEdit();
  pOptionFormLayout->addRow("Monitor element name", m_pMonitorElementNameEdit);
  m_pMonitorElementTypeComboBox = new QComboBox();
  m_pMonitorElementTypeComboBox->addItem("All", NO_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(INT_ELEMENT_TYPE).c_str(),
      INT_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(REAL_ELEMENT_TYPE).c_str(),
      REAL_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(SHORT_ELEMENT_TYPE).c_str(),
      SHORT_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(STRING_ELEMENT_TYPE).c_str(),
      STRING_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(INT_HISTOGRAM_1D_ELEMENT_TYPE).c_str(),
       INT_HISTOGRAM_1D_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(REAL_HISTOGRAM_1D_ELEMENT_TYPE).c_str()
      , REAL_HISTOGRAM_1D_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(SHORT_HISTOGRAM_1D_ELEMENT_TYPE).c_str(
      ), SHORT_HISTOGRAM_1D_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(CHAR_HISTOGRAM_1D_ELEMENT_TYPE).c_str()
      , CHAR_HISTOGRAM_1D_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(INT_HISTOGRAM_2D_ELEMENT_TYPE).c_str(),
       INT_HISTOGRAM_2D_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(REAL_HISTOGRAM_2D_ELEMENT_TYPE).c_str()
      , REAL_HISTOGRAM_2D_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(CHAR_HISTOGRAM_2D_ELEMENT_TYPE).c_str()
      , CHAR_HISTOGRAM_2D_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(SHORT_HISTOGRAM_2D_ELEMENT_TYPE).c_str(
      ), SHORT_HISTOGRAM_2D_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(PROFILE_1D_ELEMENT_TYPE).c_str(),
      PROFILE_1D_ELEMENT_TYPE);
  m_pMonitorElementTypeComboBox->addItem(monitorElementTypeToString(PROFILE_2D_ELEMENT_TYPE).c_str(),
      PROFILE_2D_ELEMENT_TYPE);
  pOptionFormLayout->addRow("Monitor element type",
      m_pMonitorElementTypeComboBox);
  QWidget *pSearchButtonAreaWidget = new QWidget();
  pOptionFormLayout->addRow("", pSearchButtonAreaWidget);
  QHBoxLayout *pSearchAreaLayout = new QHBoxLayout();
  pSearchButtonAreaWidget->setLayout(pSearchAreaLayout);
  QPushButton *pStartSearchButton = new QPushButton("Search");
  pStartSearchButton->setMaximumWidth(150);
  pSearchAreaLayout->addWidget(pStartSearchButton);
  QPushButton *pClearSelectionButton = new QPushButton("Clear");
  pClearSelectionButton->setMaximumWidth(150);
  pSearchAreaLayout->addWidget(pClearSelectionButton);
  layout()->addWidget(m_pOptionGroupBox);
  // search result main view
  QGroupBox *pSearchResultGroupBox = new QGroupBox("Search result");
  layout()->addWidget(pSearchResultGroupBox);
  QHBoxLayout *pSearchResultLayout = new QHBoxLayout();
  pSearchResultGroupBox->setLayout(pSearchResultLayout);
  m_pSearchTreeWidget = new QTreeWidget();
  m_pSearchTreeWidget->setHeaderLabels(QStringList() << "Module" << "Directory" << "Name" << "Type");
  pSearchResultLayout->addWidget(m_pSearchTreeWidget);
  // bottom button area
  QWidget *pBottomButtonAreaWidget = new QWidget();
  layout()->addWidget(pBottomButtonAreaWidget);
  QHBoxLayout *pBottomAreaLayout = new QHBoxLayout();
  pBottomButtonAreaWidget->setLayout(pBottomAreaLayout);
  m_pReplaceButton = new QPushButton("Replace");
  m_pReplaceButton->setMaximumWidth(150);
  m_pReplaceButton->setEnabled(false);
  pBottomAreaLayout->addWidget(m_pReplaceButton);
  m_pAppendButton = new QPushButton("Append");
  m_pAppendButton->setMaximumWidth(150);
  m_pAppendButton->setEnabled(false);
  pBottomAreaLayout->addWidget(m_pAppendButton);
  m_pCloseButton = new QPushButton("Close");
  m_pCloseButton->setMaximumWidth(150);
  pBottomAreaLayout->addWidget(m_pCloseButton);
  connect(m_pCloseButton, SIGNAL(clicked()), this, SLOT(close()));
  connect(pUpdateCollectorListButton, SIGNAL(clicked()), this, SLOT(
      updateCollectorList()));
  connect(m_pCollectorNameComboBox, SIGNAL(currentIndexChanged(int)), this, SLOT(
      handleCollectorSelection(int)));
  connect(pClearSelectionButton, SIGNAL(clicked()), this, SLOT(clearSearch()));
  connect(pStartSearchButton, SIGNAL(clicked()), this, SLOT(querySearch()));
  connect(m_pSearchTreeWidget, SIGNAL(itemDoubleClicked(QTreeWidgetItem *, int)), this, SLOT(
      checkItem(QTreeWidgetItem*, int)));
  connect(this, SIGNAL(keyPressEvent(QKeyEvent*)), this, SLOT(
      handleKeyPressEvent(QKeyEvent*)));
  connect(m_pAppendButton, SIGNAL(clicked()), this, SLOT(
      handleUpdateButtonClicked()));
  connect(m_pReplaceButton, SIGNAL(clicked()), this, SLOT(
      handleReplaceButtonClicked()));
  updateCollectorList();
  resize(700, 700);
}
dqm4hep::DQMBrowserWidget::~DQMBrowserWidget ()
Destructor.
Definition at line 165 of file DQMBrowserWidget.cc.
References m_pMonitorElementClient.
{
  if(m_pMonitorElementClient)
    m_pMonitorElementClient->deleteLater();
}
Member Function Documentation
void dqm4hep::DQMBrowserWidget::buildMonitorElementInfoList (DQMMonitorElementInfoList & infoList) const [private]
Build the monitor element info list of the current selection.
Definition at line 384 of file DQMBrowserWidget.cc.
References m_pSearchTreeWidget.
Referenced by handleReplaceButtonClicked(), and handleUpdateButtonClicked().
{
  for(unsigned int i=0 ; i<m_pSearchTreeWidget->topLevelItemCount() ; i++)
  {
    if(Qt::Checked == m_pSearchTreeWidget->topLevelItem(i)->checkState(0))
    {
      DQMMonitorElementInfo info;
      info.m_moduleName = m_pSearchTreeWidget->topLevelItem(i)->text(0).toStdString();
      info.m_monitorElementFullPath = m_pSearchTreeWidget->topLevelItem(i)->text(1).toStdString();
      info.m_monitorElementName = m_pSearchTreeWidget->topLevelItem(i)->text(2).toStdString();
      info.m_monitorElementType = m_pSearchTreeWidget->topLevelItem(i)->text(3).toStdString();
      info.m_monitorElementDescription = m_pSearchTreeWidget->topLevelItem(i)->toolTip(0).toStdString();
      infoList.push_back(info);
    }
  }
}
void dqm4hep::DQMBrowserWidget::checkItem (QTreeWidgetItem * pItem, int) [private], [slot]
Check/uncheck the given item.
Definition at line 332 of file DQMBrowserWidget.cc.
Referenced by DQMBrowserWidget().
{
  Qt::CheckState state = pItem->checkState(0);
  pItem->setCheckState(0, state == Qt::Checked ? Qt::Unchecked : Qt::Checked);
}
void dqm4hep::DQMBrowserWidget::checkSelectedElements () [private], [slot]
Check all the selected items.
Definition at line 350 of file DQMBrowserWidget.cc.
References m_pSearchTreeWidget.
Referenced by handleKeyPressEvent().
{
  QList<QTreeWidgetItem *> selectedItems = m_pSearchTreeWidget->selectedItems();
  if(selectedItems.isEmpty())
    return;
  Qt::CheckState state = Qt::Checked;
  for(unsigned int i=0 ; i<selectedItems.size() ; i++)
  {
    if(i == 0)
    {
      QTreeWidgetItem *pFirstItem = selectedItems.at(i);
      if(pFirstItem->checkState(0) == Qt::Checked)
        state = Qt::Unchecked;
    }
    QTreeWidgetItem *pItem = selectedItems.at(i);
    pItem->setCheckState(0, state);
  }
}
void dqm4hep::DQMBrowserWidget::clearSearch () [private], [slot]
Clear the search interface.
Definition at line 273 of file DQMBrowserWidget.cc.
References m_pModuleNameEdit, m_pMonitorElementNameEdit, m_pMonitorElementTypeComboBox, and m_pSearchTreeWidget.
Referenced by DQMBrowserWidget(), handleCollectorSelection(), and updateCollectorList().
{
  m_pModuleNameEdit->clear();
  m_pMonitorElementNameEdit->clear();
  m_pMonitorElementTypeComboBox->setCurrentIndex(0);
  m_pSearchTreeWidget->clear();
}
void dqm4hep::DQMBrowserWidget::fillModuleNameList (const DQMMonitorElementInfoList & nameList) [private], [slot]
Fill the module name list.
Definition at line 298 of file DQMBrowserWidget.cc.
References m_pSearchTreeWidget.
Referenced by handleCollectorSelection().
{
  m_pSearchTreeWidget->clear();
  if(nameList.empty())
    return;
  for(unsigned int i=0 ; i<nameList.size() ; i++)
  {
    QString moduleName = nameList.at(i).m_moduleName.c_str();
    QString monitorElementFullPath = nameList.at(i).m_monitorElementFullPath.c_str();
    QString monitorElementName = nameList.at(i).m_monitorElementName.c_str();
    QString monitorElementType = nameList.at(i).m_monitorElementType.c_str();
    QString monitorElementDescription = nameList.at(i).m_monitorElementDescription.c_str();
    QStringList itemColumns;
    itemColumns << moduleName << monitorElementFullPath << monitorElementName << monitorElementType;
    QTreeWidgetItem *pItem = new QTreeWidgetItem(itemColumns);
    pItem->setCheckState(0, Qt::Checked);
    pItem->setToolTip(0, monitorElementDescription);
    pItem->setToolTip(1, monitorElementDescription);
    pItem->setToolTip(2, monitorElementDescription);
    pItem->setToolTip(3, monitorElementDescription);
    m_pSearchTreeWidget->addTopLevelItem(pItem);
  }
  m_pSearchTreeWidget->header()->resizeSections(QHeaderView::Stretch);
}
QString dqm4hep::DQMBrowserWidget::getCollectorName () const
Get the collector name.
Definition at line 180 of file DQMBrowserWidget.cc.
References m_pCollectorNameComboBox.
Referenced by handleReplaceButtonClicked(), handleUpdateButtonClicked(), and updateCollectorList().
{
  if(m_pCollectorNameComboBox->currentIndex() != 0)
    return m_pCollectorNameComboBox->currentText();
  return QString();
}
DQMMonitoring * dqm4hep::DQMBrowserWidget::getMonitoring () const
Get the monitoring instance.
Definition at line 173 of file DQMBrowserWidget.cc.
References m_pMonitoring.
Referenced by handleCollectorSelection(), handleReplaceButtonClicked(), and handleUpdateButtonClicked().
{
  return m_pMonitoring;
}
void dqm4hep::DQMBrowserWidget::handleCollectorSelection (int index) [private], [slot]
Definition at line 217 of file DQMBrowserWidget.cc.
References clearSearch(), dqm4hep::DQMMonitoringController::createClient(), fillModuleNameList(), dqm4hep::DQMMonitoring::getController(), dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient(), getMonitoring(), m_pAppendButton, m_pCollectorNameComboBox, m_pMonitorElementClient, m_pReplaceButton, and querySearch().
Referenced by DQMBrowserWidget().
{
  if(index < 0)
    return;
  if(index == 0)
  {
    clearSearch();
    if(m_pMonitorElementClient)
    {
      m_pMonitorElementClient->deleteLater();
      m_pMonitorElementClient = 0;
    }
    m_pReplaceButton->setEnabled(false);
    m_pAppendButton->setEnabled(false);
    return;
  }
  m_pReplaceButton->setEnabled(true);
  m_pAppendButton->setEnabled(true);
  QString newCollectorName = m_pCollectorNameComboBox->itemText(index);
  if(m_pMonitorElementClient)
  {
    bool sameCollectorName =
        newCollectorName.toStdString()
        ==
        m_pMonitorElementClient->getMonitorElementClient()->getCollectorName();
    if(!sameCollectorName)
    {
      m_pMonitorElementClient->deleteLater();
      m_pMonitorElementClient = 0;
    }
  }
  if(!m_pMonitorElementClient)
  {
    m_pMonitorElementClient = this->getMonitoring()->getController()->
      createClient(newCollectorName.toStdString());
    m_pMonitorElementClient->getMonitorElementClient()->connectToService();
    connect(m_pMonitorElementClient, SIGNAL(monitorElementListNameReceived(const DQMMonitorElementInfoList
      &)),
        this, SLOT(fillModuleNameList(const DQMMonitorElementInfoList &)));
    clearSearch();
    querySearch();
  }
}
void dqm4hep::DQMBrowserWidget::handleKeyPressEvent (QKeyEvent * pKeyEvent) [private], [slot]
Handle the key press event.
Key Alt+A : select all elements in the list
Key enter : check all the selected items
Definition at line 340 of file DQMBrowserWidget.cc.
References checkSelectedElements(), and selectAllElements().
Referenced by DQMBrowserWidget().
{
  if(pKeyEvent->key() == Qt::Key_Return)
    checkSelectedElements();
  if(pKeyEvent->key() == Qt::Key_A)
    selectAllElements();
}
void dqm4hep::DQMBrowserWidget::handleReplaceButtonClicked () [private], [slot]
Definition at line 424 of file DQMBrowserWidget.cc.
References buildMonitorElementInfoList(), dqm4hep::DQMMonitoringController::clearViewAndModel(), dqm4hep::DQMMonitoringController::createEmptyMonitorElements(), dqm4hep::DQMMonitoringController::getClient(), getCollectorName(), dqm4hep::DQMMonitoring::getController(), and getMonitoring().
Referenced by DQMBrowserWidget().
{
  DQMMonitorElementInfoList infoList;
  this->buildMonitorElementInfoList(infoList);
  std::string collectorName = this->getCollectorName().toStdString();
  if(infoList.empty() || collectorName.empty())
    return;
  this->getMonitoring()->getController()->clearViewAndModel();
  // create the client instance (owned by the controller)
  this->getMonitoring()->getController()->getClient(collectorName);
  // create the list in view
  this->getMonitoring()->getController()->createEmptyMonitorElements(collectorName, infoList);
}
void dqm4hep::DQMBrowserWidget::handleUpdateButtonClicked () [private], [slot]
Definition at line 405 of file DQMBrowserWidget.cc.
References buildMonitorElementInfoList(), dqm4hep::DQMMonitoringController::createEmptyMonitorElements(), dqm4hep::DQMMonitoringController::getClient(), getCollectorName(), dqm4hep::DQMMonitoring::getController(), and getMonitoring().
Referenced by DQMBrowserWidget().
{
  DQMMonitorElementInfoList infoList;
  this->buildMonitorElementInfoList(infoList);
  std::string collectorName = this->getCollectorName().toStdString();
  if(infoList.empty() || collectorName.empty())
    return;
  // create the client instance (owned by the controller)
  this->getMonitoring()->getController()->getClient(collectorName);
  // create the list in view
  this->getMonitoring()->getController()->createEmptyMonitorElements(collectorName, infoList);
}
void dqm4hep::DQMBrowserWidget::keyPressEvent (QKeyEvent *) [signal]
Key pressed event emitted in the tree widget.
Referenced by DQMBrowserWidget().
void dqm4hep::DQMBrowserWidget::querySearch () [private], [slot]
Send the query for monitor element browsing on the collector.
Definition at line 283 of file DQMBrowserWidget.cc.
References dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient(), m_pModuleNameEdit, m_pMonitorElementClient, m_pMonitorElementNameEdit, and m_pMonitorElementTypeComboBox.
Referenced by DQMBrowserWidget(), and handleCollectorSelection().
{
  if(!m_pMonitorElementClient)
    return;
  DQMMonitorElementListNameRequest request;
  request.m_moduleName = m_pModuleNameEdit->text().toStdString();
  request.m_monitorElementName = m_pMonitorElementNameEdit->text().toStdString();
  request.m_monitorElementType = static_cast<DQMMonitorElementType>(
      m_pMonitorElementTypeComboBox->currentIndex());
  m_pMonitorElementClient->getMonitorElementClient()->queryAvailableMonitorElements(request);
}
void dqm4hep::DQMBrowserWidget::selectAllElements () [private], [slot]
Select all items.
Definition at line 376 of file DQMBrowserWidget.cc.
References m_pSearchTreeWidget.
Referenced by handleKeyPressEvent().
{
  for(unsigned int i=0 ; i<m_pSearchTreeWidget->topLevelItemCount() ; i++)
    m_pSearchTreeWidget->topLevelItem(i)->setSelected(true);
}
void dqm4hep::DQMBrowserWidget::updateCollectorList () [slot]
Update the collector list (combo box)
Definition at line 190 of file DQMBrowserWidget.cc.
References clearSearch(), getCollectorName(), and m_pCollectorNameComboBox.
Referenced by DQMBrowserWidget().
{
  QString collectorName = getCollectorName();
  StringVector collectorList = DQMNetworkTool::getMonitorElementCollectors();
  m_pCollectorNameComboBox->clear();
  m_pCollectorNameComboBox->addItem("-- Collector list --");
  for(StringVector::iterator iter = collectorList.begin() , endIter = collectorList.end() ;
      endIter != iter ; ++iter)
    m_pCollectorNameComboBox->addItem(iter->c_str());
  // retrieve the collector in the new list
  int collectorIndex = m_pCollectorNameComboBox->findText(collectorName);
  if(collectorIndex > 0)
  {
    m_pCollectorNameComboBox->setCurrentIndex(collectorIndex);
  }
  else
  {
    clearSearch();
  }
}
Member Data Documentation
QPushButton* dqm4hep::DQMBrowserWidget::m_pAppendButton [private]
Definition at line 148 of file DQMBrowserWidget.h.
Referenced by DQMBrowserWidget(), and handleCollectorSelection().
QPushButton* dqm4hep::DQMBrowserWidget::m_pCloseButton [private]
Definition at line 149 of file DQMBrowserWidget.h.
Referenced by DQMBrowserWidget().
QComboBox* dqm4hep::DQMBrowserWidget::m_pCollectorNameComboBox [private]
Definition at line 141 of file DQMBrowserWidget.h.
Referenced by DQMBrowserWidget(), getCollectorName(), handleCollectorSelection(), and updateCollectorList().
QLineEdit* dqm4hep::DQMBrowserWidget::m_pModuleNameEdit [private]
Definition at line 142 of file DQMBrowserWidget.h.
Referenced by clearSearch(), DQMBrowserWidget(), and querySearch().
DQMGuiMonitorElementClient* dqm4hep::DQMBrowserWidget::m_pMonitorElementClient [private]
Definition at line 151 of file DQMBrowserWidget.h.
Referenced by handleCollectorSelection(), querySearch(), and ~DQMBrowserWidget().
QLineEdit* dqm4hep::DQMBrowserWidget::m_pMonitorElementNameEdit [private]
Definition at line 143 of file DQMBrowserWidget.h.
Referenced by clearSearch(), DQMBrowserWidget(), and querySearch().
QComboBox* dqm4hep::DQMBrowserWidget::m_pMonitorElementTypeComboBox [private]
Definition at line 144 of file DQMBrowserWidget.h.
Referenced by clearSearch(), DQMBrowserWidget(), and querySearch().
DQMMonitoring* dqm4hep::DQMBrowserWidget::m_pMonitoring [private]
Definition at line 139 of file DQMBrowserWidget.h.
Referenced by getMonitoring().
QGroupBox* dqm4hep::DQMBrowserWidget::m_pOptionGroupBox [private]
Definition at line 146 of file DQMBrowserWidget.h.
Referenced by DQMBrowserWidget().
QPushButton* dqm4hep::DQMBrowserWidget::m_pReplaceButton [private]
Definition at line 147 of file DQMBrowserWidget.h.
Referenced by DQMBrowserWidget(), and handleCollectorSelection().
QTreeWidget* dqm4hep::DQMBrowserWidget::m_pSearchTreeWidget [private]
Definition at line 145 of file DQMBrowserWidget.h.
Referenced by buildMonitorElementInfoList(), checkSelectedElements(), clearSearch(), DQMBrowserWidget(), fillModuleNameList(), and selectAllElements().
The documentation for this class was generated from the following files:
DQMBrowserWidget.h
DQMBrowserWidget.cc