dqm4hep::DQMJobInterfaceWidget Class Reference
DQMJobInterfaceWidget class.
#include <DQMJobInterfaceWidget.h>
Public Types
enum ItemType {
*
HOST_ITEM,
JOB_ITEM,
JOB_STATUS_ITEM,
JOB_PROGRAM_NAME_ITEM,
*
JOB_PID_ITEM,
JOB_ENV_ITEM,
JOB_ARGS_ITEM,
VARIABLE_ITEM
 }
ItemType enum.
Public Slots
void loadJsonFile (const std::string &fileName)
Load json file.
void startHostJobs ()
void startAllJobs ()
void startSelectedJob ()
void clearHostJobs ()
void clearAllJobs ()
void killSelectedJob ()
void restartSelectedJob ()
void restartAllJobs ()
void updateJobStatus ()
Public Member Functions
DQMJobInterfaceWidget (QWidget *pParent=NULL)
Constructor.
~DQMJobInterfaceWidget ()
Destructor.
const std::string & getCurrentJsonFile () const
Get the current json file name.
DQMJobInterface * getJobInterface () const
Get the job interface implementation.
Private Types
enum ColumnType { NAME,
PROG_NAME,
PID,
STATUS
 }
Private Slots
void loadJsonFile ()
void reloadJsonFile ()
void handleAutomaticModeButtonClicked ()
void handleAutomaticModeValueChanged (int value)
void updateStatus (const QString &hostName)
Private Member Functions
void loadJson (const Json::Value &root)
void updateStatus (const Json::Value &value)
void createActions ()
void createMenus ()
void contextMenuEvent (QContextMenuEvent *event)
bool jobControlExists (const std::string &hostName) const
QStringList getNonRunningJobControls () const
void popupMissingJobControl (const QString &hostName)
void popupMissingJobControls (const QStringList &hostName)
Private Attributes
DQMJobInterface * m_pJobIterface
std::string m_currentJsonFile
QPushButton * m_pAutomaticModeButton
QSpinBox * m_pUpdatePeriodSpinBox
QComboBox * m_pKillComboBoxWidget
QTreeWidget * m_pTreeWidget
QPushButton * m_pLoadFileButton
QPushButton * m_pReloadFileButton
QPushButton * m_pStartHostJobsButton
QPushButton * m_pClearHostJobsButton
QPushButton * m_pKillJobButton
QPushButton * m_pRestartJobButton
QPushButton * m_pClearAllJobsButton
QPushButton * m_pRestartAllJobsButton
QPushButton * m_pStartAllJobsButton
QPushButton * m_pUpdateButton
QMenuBar * m_pMenuBar
QMenu * m_pContextMenu
QMenu * m_pFileMenu
QMenu * m_pHelpMenu
QAction * m_pLoadFileAction
QAction * m_pReloadFileAction
QAction * m_pStartHostJobsAction
QAction * m_pClearHostJobsAction
QAction * m_pKillJobAction
QAction * m_pStartJobAction
QAction * m_pRestartJobAction
QAction * m_pClearAllJobsAction
QAction * m_pRestartAllJobsAction
QAction * m_pStartAllJobsAction
QAction * m_pUpdateAction
Detailed Description
DQMJobInterfaceWidget class.
Definition at line 54 of file DQMJobInterfaceWidget.h.
Member Enumeration Documentation
enum dqm4hep::DQMJobInterfaceWidget::ColumnType [private]
Enumerator
NAME
PROG_NAME
PID
STATUS
Definition at line 153 of file DQMJobInterfaceWidget.h.
    {
        NAME,
        PROG_NAME,
        PID,
        STATUS
    };
enum dqm4hep::DQMJobInterfaceWidget::ItemType
ItemType enum.
Enumerator
HOST_ITEM
JOB_ITEM
JOB_STATUS_ITEM
JOB_PROGRAM_NAME_ITEM
JOB_PID_ITEM
JOB_ENV_ITEM
JOB_ARGS_ITEM
VARIABLE_ITEM
Definition at line 61 of file DQMJobInterfaceWidget.h.
    {
        HOST_ITEM,
        JOB_ITEM,
        JOB_STATUS_ITEM,
        JOB_PROGRAM_NAME_ITEM,
        JOB_PID_ITEM,
        JOB_ENV_ITEM,
        JOB_ARGS_ITEM,
        VARIABLE_ITEM
    };
Constructor & Destructor Documentation
dqm4hep::DQMJobInterfaceWidget::DQMJobInterfaceWidget (QWidget * pParent = NULL)
Constructor.
Definition at line 55 of file DQMJobInterfaceWidget.cc.
References createActions(), createMenus(), handleAutomaticModeButtonClicked(), handleAutomaticModeValueChanged(), loadJsonFile(), m_pAutomaticModeButton, m_pJobIterface, m_pKillComboBoxWidget, m_pLoadFileButton, m_pReloadFileButton, m_pTreeWidget, m_pUpdateButton, m_pUpdatePeriodSpinBox, reloadJsonFile(), updateJobStatus(), and updateStatus().
                                                            :
    QWidget(pParent),
    m_pAutomaticModeButton(0)
{
    m_pJobIterface = new DQMJobInterface();
    QLayout *pMainLayout = new QVBoxLayout();
    setLayout(pMainLayout);
    QHBoxLayout *pComboBoxLayout = new QHBoxLayout();
    QGroupBox *pComboBoxGroupBox = new QGroupBox();
    pMainLayout->addWidget(pComboBoxGroupBox);
    m_pAutomaticModeButton = new QPushButton("Start");
  pComboBoxLayout->addWidget(m_pAutomaticModeButton);
  QLabel *pUpdatePeriodLabel = new QLabel("Update period (secs) : ");
  pComboBoxLayout->addWidget(pUpdatePeriodLabel);
  m_pUpdatePeriodSpinBox = new QSpinBox();
  m_pUpdatePeriodSpinBox->setValue(5);
  pComboBoxLayout->addWidget(m_pUpdatePeriodSpinBox);
  connect(m_pAutomaticModeButton, SIGNAL(clicked()), this, SLOT(
      handleAutomaticModeButtonClicked()));
  connect(m_pUpdatePeriodSpinBox, SIGNAL(valueChanged(int)), this, SLOT(
      handleAutomaticModeValueChanged(int)));
  connect(m_pJobIterface, SIGNAL(statusReceived(const QString &)), this, SLOT(
      updateStatus(const QString &)));
    QSpacerItem *p_HSpacer = new QSpacerItem(1, 0, QSizePolicy::Expanding, QSizePolicy::Minimum);
    pComboBoxLayout->addSpacerItem(p_HSpacer);
    QLabel *pKillComboBoxCaption = new QLabel("Set Kill Method");
    pComboBoxLayout->addWidget(pKillComboBoxCaption);
    m_pKillComboBoxWidget = new QComboBox();
    m_pKillComboBoxWidget->addItem("HUP (Hang Up): 1", 1);
    m_pKillComboBoxWidget->addItem("INT (Interrupt): 2", 2);
    m_pKillComboBoxWidget->addItem("QUIT (Quit): 3", 3);
    m_pKillComboBoxWidget->addItem("ABRT (Abort): 6", 6);
    m_pKillComboBoxWidget->addItem("KILL (Non-ignorable kill): 9", 9);
    m_pKillComboBoxWidget->addItem("ALRM (Alarm Clock): 14", 14);
    m_pKillComboBoxWidget->addItem("TERM (Software Term Signal): 15", 15);
    m_pKillComboBoxWidget->setCurrentIndex(1); // Default: Interrupt = kill -2
    pComboBoxLayout->addWidget(m_pKillComboBoxWidget);
    pComboBoxGroupBox->setLayout(pComboBoxLayout);
    m_pTreeWidget = new QTreeWidget();
    pMainLayout->addWidget(m_pTreeWidget);
    m_pTreeWidget->setColumnCount(4);
    m_pTreeWidget->setHeaderLabels(QStringList() << "Job Control" << "Program Name" << "PID" << "Status");
    // Create Buttons
    QWidget *pButtonWidget = new QWidget();
    pMainLayout->addWidget(pButtonWidget);
    QHBoxLayout *pButtonHLayout = new QHBoxLayout();
    pButtonWidget->setLayout(pButtonHLayout);
    m_pLoadFileButton = new QPushButton("Load file");
    pButtonHLayout->addWidget(m_pLoadFileButton);
    connect(m_pLoadFileButton, SIGNAL(clicked()), this, SLOT(loadJsonFile()));
    m_pReloadFileButton = new QPushButton("Reload file");
    pButtonHLayout->addWidget(m_pReloadFileButton);
    connect(m_pReloadFileButton, SIGNAL(clicked()), this, SLOT(reloadJsonFile()));
    QSpacerItem *p_HButtonSpacer = new QSpacerItem(1, 0, QSizePolicy::Expanding, QSizePolicy::Minimum);
    pButtonHLayout->addSpacerItem(p_HButtonSpacer);
    m_pUpdateButton = new QPushButton("Update");
    pButtonHLayout->addWidget(m_pUpdateButton);
    connect(m_pUpdateButton, SIGNAL(clicked()), this, SLOT(updateJobStatus()));
    // Create Menus / Menus Entries
    createActions();
    createMenus();
}
dqm4hep::DQMJobInterfaceWidget::~DQMJobInterfaceWidget ()
Destructor.
Definition at line 137 of file DQMJobInterfaceWidget.cc.
References m_pJobIterface.
{
    delete m_pJobIterface;
}
Member Function Documentation
void dqm4hep::DQMJobInterfaceWidget::clearAllJobs () [slot]
Definition at line 429 of file DQMJobInterfaceWidget.cc.
References getNonRunningJobControls(), m_pJobIterface, and popupMissingJobControls().
Referenced by createActions(), and loadJsonFile().
{
    QStringList nonRunningJobControls = getNonRunningJobControls();
    if(!nonRunningJobControls.isEmpty())
      popupMissingJobControls(nonRunningJobControls);
    m_pJobIterface->clearAllJobs();
}
void dqm4hep::DQMJobInterfaceWidget::clearHostJobs () [slot]
Definition at line 406 of file DQMJobInterfaceWidget.cc.
References HOST_ITEM, jobControlExists(), m_pJobIterface, m_pTreeWidget, NAME, and popupMissingJobControl().
Referenced by createActions().
{
    QTreeWidgetItem* pSelectedItem = m_pTreeWidget->currentItem();
    if(!pSelectedItem)
        return;
    if(pSelectedItem->data(0, Qt::UserRole).value<int>() != HOST_ITEM)
        return;
    QString hostName = pSelectedItem->text(NAME);
    if(!this->jobControlExists(hostName.toStdString()))
    {
      popupMissingJobControl(hostName);
      return;
    }
    m_pJobIterface->clearHostJobs(hostName.toStdString());
}
void dqm4hep::DQMJobInterfaceWidget::contextMenuEvent (QContextMenuEvent * event) [private]
Definition at line 206 of file DQMJobInterfaceWidget.cc.
References HOST_ITEM, JOB_ITEM, m_pClearAllJobsAction, m_pClearHostJobsAction, m_pContextMenu, m_pKillJobAction, m_pRestartAllJobsAction, m_pRestartJobAction, m_pStartAllJobsAction, m_pStartHostJobsAction, m_pStartJobAction, m_pTreeWidget, m_pUpdateAction, PID, and STATUS.
{
    m_pContextMenu = new QMenu();
    m_pContextMenu->addAction(m_pStartHostJobsAction);
    m_pContextMenu->addAction(m_pClearHostJobsAction);
    m_pContextMenu->addSeparator();
    m_pContextMenu->addAction(m_pKillJobAction);
    m_pContextMenu->addAction(m_pRestartJobAction);
    m_pContextMenu->addAction(m_pStartJobAction);
    m_pContextMenu->addSeparator();
    m_pContextMenu->addAction(m_pClearAllJobsAction);
    m_pContextMenu->addAction(m_pRestartAllJobsAction);
    m_pContextMenu->addAction(m_pStartAllJobsAction);
    m_pContextMenu->addSeparator();
    m_pContextMenu->addAction(m_pUpdateAction);
    m_pStartHostJobsAction->setEnabled(false);
    m_pClearHostJobsAction->setEnabled(false);
    m_pKillJobAction->setEnabled(false);
    m_pRestartJobAction->setEnabled(false);
    m_pStartJobAction->setEnabled(false);
    // Activate items as needed
    QTreeWidgetItem* pCurrentItem = m_pTreeWidget->currentItem();
    if (NULL == pCurrentItem)
    {
        m_pContextMenu->exec(event->globalPos());
        return;
    }
    if(pCurrentItem->data(0, Qt::UserRole).value<int>() == HOST_ITEM)
    {
        m_pStartHostJobsAction->setEnabled(true);
        m_pClearHostJobsAction->setEnabled(true);
    }
    else if(pCurrentItem->data(0, Qt::UserRole).value<int>() == JOB_ITEM)
    {
        QString status = pCurrentItem->text(STATUS).at(0);
        if (status.isEmpty())
            return;
        if (status == "D" || status == "X") //Dead
        {
            if (pCurrentItem->text(PID).toInt())
                m_pRestartJobAction->setEnabled(true);
            else
                m_pStartJobAction->setEnabled(true);
        }
        else if (status != "Z" && // Zombie
                  status != "T" // Traced or Stopped
                  )
        {
            m_pKillJobAction->setEnabled(true);
            m_pRestartJobAction->setEnabled(true);
        }
        else
        {
            m_pStartJobAction->setEnabled(true);
        }
    }
    m_pContextMenu->exec(event->globalPos());
}
void dqm4hep::DQMJobInterfaceWidget::createActions () [private]
Definition at line 158 of file DQMJobInterfaceWidget.cc.
References clearAllJobs(), clearHostJobs(), killSelectedJob(), loadJsonFile(), m_pClearAllJobsAction, m_pClearHostJobsAction, m_pKillJobAction, m_pLoadFileAction, m_pReloadFileAction, m_pRestartAllJobsAction, m_pRestartJobAction, m_pStartAllJobsAction, m_pStartHostJobsAction, m_pStartJobAction, m_pUpdateAction, reloadJsonFile(), restartAllJobs(), restartSelectedJob(), startAllJobs(), startHostJobs(), startSelectedJob(), and updateJobStatus().
Referenced by DQMJobInterfaceWidget().
{
    m_pLoadFileAction = new QAction("Load File", this);
    connect(m_pLoadFileAction, SIGNAL(triggered()), this, SLOT(loadJsonFile()));
    m_pReloadFileAction = new QAction("Reload File", this);
    connect(m_pReloadFileAction, SIGNAL(triggered()), this, SLOT(reloadJsonFile()));
    m_pStartHostJobsAction = new QAction("Start host jobs", this);
    connect(m_pStartHostJobsAction, SIGNAL(triggered()), this, SLOT(
      startHostJobs()));
    m_pClearHostJobsAction = new QAction("Kill host jobs", this);
    connect(m_pClearHostJobsAction, SIGNAL(triggered()), this, SLOT(
      clearHostJobs()));
    m_pKillJobAction = new QAction("Kill selected job", this);
    connect(m_pKillJobAction, SIGNAL(triggered()), this, SLOT(killSelectedJob()));
    m_pRestartJobAction = new QAction("Restart selected job", this);
    connect(m_pRestartJobAction, SIGNAL(triggered()), this, SLOT(
      restartSelectedJob()));
    m_pStartJobAction = new QAction("Start selected job", this);
    connect(m_pStartJobAction, SIGNAL(triggered()), this, SLOT(startSelectedJob()));
    m_pClearAllJobsAction = new QAction("Kill all jobs", this);
    connect(m_pClearAllJobsAction, SIGNAL(triggered()), this, SLOT(clearAllJobs()));
    m_pRestartAllJobsAction = new QAction("Restart all jobs", this);
    connect(m_pRestartAllJobsAction, SIGNAL(triggered()), this, SLOT(
      restartAllJobs()));
    m_pStartAllJobsAction = new QAction("Start all jobs", this);
    connect(m_pStartAllJobsAction, SIGNAL(triggered()), this, SLOT(startAllJobs()));
    m_pUpdateAction = new QAction("Update jobs", this);
    connect(m_pUpdateAction, SIGNAL(triggered()), this, SLOT(updateJobStatus()));
}
void dqm4hep::DQMJobInterfaceWidget::createMenus () [private]
Definition at line 196 of file DQMJobInterfaceWidget.cc.
References m_pFileMenu, m_pLoadFileAction, m_pMenuBar, and m_pReloadFileAction.
Referenced by DQMJobInterfaceWidget().
{
    m_pMenuBar = new QMenuBar();
    m_pFileMenu = m_pMenuBar->addMenu("&File");
    m_pFileMenu->addAction(m_pLoadFileAction);
    m_pFileMenu->addAction(m_pReloadFileAction);
}
const std::string & dqm4hep::DQMJobInterfaceWidget::getCurrentJsonFile () const
Get the current json file name.
Definition at line 144 of file DQMJobInterfaceWidget.cc.
References m_currentJsonFile.
{
  return m_currentJsonFile;
}
DQMJobInterface * dqm4hep::DQMJobInterfaceWidget::getJobInterface () const
Get the job interface implementation.
Definition at line 151 of file DQMJobInterfaceWidget.cc.
References m_pJobIterface.
{
  return m_pJobIterface;
}
QStringList dqm4hep::DQMJobInterfaceWidget::getNonRunningJobControls () const [private]
Definition at line 810 of file DQMJobInterfaceWidget.cc.
References jobControlExists(), and m_pTreeWidget.
Referenced by clearAllJobs(), restartAllJobs(), and startAllJobs().
{
  QStringList missingJobControlList;
  for(int i=0 ; i<m_pTreeWidget->topLevelItemCount() ; i++)
  {
    QString hostName = m_pTreeWidget->topLevelItem(i)->text(0);
    if(!this->jobControlExists(hostName.toStdString()))
      missingJobControlList << hostName;
  }
  return missingJobControlList;
}
void dqm4hep::DQMJobInterfaceWidget::handleAutomaticModeButtonClicked () [private], [slot]
Definition at line 700 of file DQMJobInterfaceWidget.cc.
References m_pAutomaticModeButton, m_pJobIterface, m_pUpdatePeriodSpinBox, dqm4hep::DQMJobInterface::started(), dqm4hep::DQMJobInterface::startUpdate(), and dqm4hep::DQMJobInterface::stopUpdate().
Referenced by DQMJobInterfaceWidget().
{
  if(m_pJobIterface->started())
  {
    m_pJobIterface->stopUpdate();
    m_pAutomaticModeButton->setText("Start");
  }
  else
  {
    int nSeconds = m_pUpdatePeriodSpinBox->value();
    m_pJobIterface->startUpdate(nSeconds);
    m_pAutomaticModeButton->setText("Stop");
  }
}
void dqm4hep::DQMJobInterfaceWidget::handleAutomaticModeValueChanged (int value) [private], [slot]
Definition at line 717 of file DQMJobInterfaceWidget.cc.
References m_pJobIterface, dqm4hep::DQMJobInterface::started(), dqm4hep::DQMJobInterface::startUpdate(), and dqm4hep::DQMJobInterface::stopUpdate().
Referenced by DQMJobInterfaceWidget().
{
  if(m_pJobIterface->started())
  {
    m_pJobIterface->stopUpdate();
    m_pJobIterface->startUpdate(value);
  }
}
bool dqm4hep::DQMJobInterfaceWidget::jobControlExists (const std::string & hostName) const [private]
Definition at line 797 of file DQMJobInterfaceWidget.cc.
Referenced by clearHostJobs(), getNonRunningJobControls(), killSelectedJob(), restartSelectedJob(), startHostJobs(), and startSelectedJob().
{
  // Look for DB server
  DimBrowser browser;
  std::string jobControlName = "/DJC/" + hostName + "/JOBSTATUS";
  int nServices = browser.getServices(jobControlName.c_str());
  return (nServices != 0);
}
void dqm4hep::DQMJobInterfaceWidget::killSelectedJob () [slot]
Definition at line 441 of file DQMJobInterfaceWidget.cc.
References JOB_ITEM, jobControlExists(), m_pJobIterface, m_pKillComboBoxWidget, m_pTreeWidget, NAME, PID, and popupMissingJobControl().
Referenced by createActions().
{
    QComboBox* pKillItem = m_pKillComboBoxWidget;
    QTreeWidgetItem* pSelectedItem = m_pTreeWidget->currentItem();
    if(!pSelectedItem)
        return;
    if(pSelectedItem->data(0, Qt::UserRole).value<int>() != JOB_ITEM)
        return;
    QString hostName = pSelectedItem->parent()->text(NAME);
    QString pidStr = pSelectedItem->text(PID);
    QVariant sigVar = pKillItem->itemData(pKillItem->currentIndex());
    if(!this->jobControlExists(hostName.toStdString()))
    {
      popupMissingJobControl(hostName);
      return;
    }
    if(pidStr.isEmpty())
        return;
    uint32_t pid = pidStr.toUInt();
    uint32_t sig = sigVar.toUInt();
    m_pJobIterface->killJob(hostName.toStdString(), pid, sig);
}
void dqm4hep::DQMJobInterfaceWidget::loadJson (const Json::Value & root) [private]
Definition at line 558 of file DQMJobInterfaceWidget.cc.
References HOST_ITEM, JOB_ARGS_ITEM, JOB_ENV_ITEM, JOB_ITEM, JOB_PID_ITEM, JOB_PROGRAM_NAME_ITEM, JOB_STATUS_ITEM, m_pTreeWidget, NAME, PID, PROG_NAME, STATUS, and VARIABLE_ITEM.
Referenced by loadJsonFile().
{
    m_pTreeWidget->clear();
    StringVector hostList = root["HOSTS"].getMemberNames();
    // loop over hosts
    for(StringVector::iterator iter = hostList.begin(), endIter = hostList.end() ;
        endIter != iter ; ++iter)
    {
        const Json::Value &host(root["HOSTS"][*iter]);
        QStringList name((*iter).c_str());
        QTreeWidgetItem *pHostItem = new QTreeWidgetItem(name);
        pHostItem->setData(0, Qt::UserRole, HOST_ITEM);
        m_pTreeWidget->addTopLevelItem(pHostItem);
        // loop over jobs host
        for(unsigned int j=0 ; j<host.size() ; j++)
        {
            QStringList jobHeader;
            jobHeader << host[j]["NAME"].asString().c_str() << host[j]["PROGRAM"].asString().c_str() <<
      host[j]["PID"].asString().c_str() << host[j]["STATUS"].asString().c_str() ;
            QTreeWidgetItem *pJobItem = new QTreeWidgetItem(jobHeader);
            pJobItem->setData(NAME, Qt::UserRole, JOB_ITEM);
            pJobItem->setData(PROG_NAME, Qt::UserRole, JOB_PROGRAM_NAME_ITEM);
            pJobItem->setData(PID, Qt::UserRole, JOB_PID_ITEM);
            pJobItem->setData(STATUS, Qt::UserRole, JOB_STATUS_ITEM);
            pHostItem->addChild(pJobItem);
            QTreeWidgetItem *pEnvironmentItem = new QTreeWidgetItem(QStringList("ENV"));
            pEnvironmentItem->setData(0, Qt::UserRole, JOB_ENV_ITEM);
            pJobItem->addChild(pEnvironmentItem);
            const Json::Value &envJsonValue = host[j]["ENV"];
            for(unsigned int e=0 ; e<envJsonValue.size() ; e++)
            {
                QString env(envJsonValue[e].asString().c_str());
                QStringList envVarHeader;
                envVarHeader << env;
                QTreeWidgetItem *pEnvVarItem = new QTreeWidgetItem(envVarHeader);
                pEnvVarItem->setData(0, Qt::UserRole, VARIABLE_ITEM);
                pEnvironmentItem->addChild(pEnvVarItem);
            }
            QTreeWidgetItem *pArgsItem = new QTreeWidgetItem(QStringList("ARGS"));
            pArgsItem->setData(0, Qt::UserRole, JOB_ARGS_ITEM);
            pJobItem->addChild(pArgsItem);
            const Json::Value &argsJsonValue = host[j]["ARGS"];
            for(unsigned int e=0 ; e<argsJsonValue.size() ; e++)
            {
                QString arg(argsJsonValue[e].asString().c_str());
                QStringList argVarHeader;
                argVarHeader << arg;
                QTreeWidgetItem *pArgVarItem = new QTreeWidgetItem(argVarHeader);
                pArgVarItem->setData(0, Qt::UserRole, VARIABLE_ITEM);
                pArgsItem->addChild(pArgVarItem);
            }
        }
        pHostItem->setExpanded(true);
    }
    m_pTreeWidget->header()->resizeSections(QHeaderView::Stretch);
}
void dqm4hep::DQMJobInterfaceWidget::loadJsonFile (const std::string & fileName) [slot]
Load json file.
Clear the pocess table
Definition at line 290 of file DQMJobInterfaceWidget.cc.
References clearAllJobs(), loadJson(), m_currentJsonFile, m_pJobIterface, m_pTreeWidget, and updateJobStatus().
{
    if(fileName.empty())
        return;
  if(m_pTreeWidget->topLevelItemCount() != 0)
  {
    QMessageBox::StandardButton button =
        QMessageBox::warning(this, "Load json file",
        "WARNING !\n"
        "The process table is not empty. Some of the processes are maybe running.\n\n"
        "Do you want to kill all running jobs ?",
        QMessageBox::Yes | QMessageBox::No | QMessageBox::Cancel,
        QMessageBox::Cancel);
    switch(button)
    {
    case QMessageBox::Yes:
      this->clearAllJobs();
      break;
    case QMessageBox::No:
      break;
    case QMessageBox::Cancel:
    default:
      return;
    }
  }
    m_pJobIterface->loadJSON(fileName);
    const Json::Value &root(m_pJobIterface->getRoot());
    loadJson(root);
    m_currentJsonFile = fileName;
    updateJobStatus();
}
void dqm4hep::DQMJobInterfaceWidget::loadJsonFile () [private], [slot]
Definition at line 278 of file DQMJobInterfaceWidget.cc.
Referenced by createActions(), DQMJobInterfaceWidget(), and reloadJsonFile().
{
    QString fileName = QFileDialog::getOpenFileName(this, "Load file");
    if(fileName.isEmpty())
        return;
    loadJsonFile(fileName.toStdString());
}
void dqm4hep::DQMJobInterfaceWidget::popupMissingJobControl (const QString & hostName) [private]
Definition at line 827 of file DQMJobInterfaceWidget.cc.
Referenced by clearHostJobs(), killSelectedJob(), restartSelectedJob(), startHostJobs(), and startSelectedJob().
{
  QMessageBox::warning(this, "Job control not running !",
    "ERROR !\n\n"
    "The job control on '" + hostName + "' is not running (or crashed).\n"
    "Please, (re)start it !");
}
void dqm4hep::DQMJobInterfaceWidget::popupMissingJobControls (const QStringList & hostName) [private]
Definition at line 837 of file DQMJobInterfaceWidget.cc.
Referenced by clearAllJobs(), restartAllJobs(), and startAllJobs().
{
  QString message = "ERROR !\n\n"
      "The following job controls are not running (or crashed) : \n";
  for(int i=0 ; i<hostNameList.size() ; i++)
    message += " * " + hostNameList.at(i) + "\n";
  message += "Please, check the job controls status on the different servers "
      "and restart them if needed";
  QMessageBox::warning(this, "Job controls not running !", message);
}
void dqm4hep::DQMJobInterfaceWidget::reloadJsonFile () [private], [slot]
Definition at line 329 of file DQMJobInterfaceWidget.cc.
References loadJsonFile(), and m_currentJsonFile.
Referenced by createActions(), and DQMJobInterfaceWidget().
{
    if(m_currentJsonFile.empty())
        return;
    loadJsonFile(m_currentJsonFile);
}
void dqm4hep::DQMJobInterfaceWidget::restartAllJobs () [slot]
Definition at line 506 of file DQMJobInterfaceWidget.cc.
References getNonRunningJobControls(), m_pJobIterface, m_pKillComboBoxWidget, m_pTreeWidget, NAME, PID, and popupMissingJobControls().
Referenced by createActions().
{
    QComboBox* pKillItem = m_pKillComboBoxWidget;
    QStringList nonRunningJobControls = getNonRunningJobControls();
    if(!nonRunningJobControls.isEmpty())
      popupMissingJobControls(nonRunningJobControls);
    // loop over hosts and jobs
    // and restart them if the pid is defined
    for(unsigned int h=0 ; h<m_pTreeWidget->topLevelItemCount() ; h++)
    {
        QTreeWidgetItem *pHostItem = m_pTreeWidget->topLevelItem(h);
        QString hostName = pHostItem->text(NAME);
        for(unsigned int j=0 ; j<pHostItem->childCount() ; j++)
        {
            QTreeWidgetItem *pJobItem = pHostItem->child(j);
            QString jobName = pJobItem->text(NAME);
            QString pidStr = pJobItem->text(PID);
            QVariant sigVar = pKillItem->itemData(pKillItem->currentIndex());
            if(pidStr.isEmpty())
                continue;
            uint32_t pid = pidStr.toUInt();
            uint32_t sig = sigVar.toUInt();
            m_pJobIterface->restartJob(hostName.toStdString(), jobName.toStdString(), pid, sig);
        }
    }
}
void dqm4hep::DQMJobInterfaceWidget::restartSelectedJob () [slot]
Definition at line 473 of file DQMJobInterfaceWidget.cc.
References JOB_ITEM, jobControlExists(), m_pJobIterface, m_pKillComboBoxWidget, m_pTreeWidget, NAME, PID, and popupMissingJobControl().
Referenced by createActions().
{
    QComboBox* pKillItem = m_pKillComboBoxWidget;
    QTreeWidgetItem* pSelectedItem = m_pTreeWidget->currentItem();
    if(!pSelectedItem)
        return;
    if(pSelectedItem->data(0, Qt::UserRole).value<int>() != JOB_ITEM)
        return;
    QString hostName = pSelectedItem->parent()->text(NAME);
    QString jobName = pSelectedItem->text(NAME);
    QString pidStr = pSelectedItem->text(PID);
    QVariant sigVar = pKillItem->itemData(pKillItem->currentIndex());
    if(!this->jobControlExists(hostName.toStdString()))
    {
      popupMissingJobControl(hostName);
      return;
    }
    if(pidStr.isEmpty())
        return;
    uint32_t pid = pidStr.toUInt();
    uint32_t sig = sigVar.toUInt();
    m_pJobIterface->restartJob(hostName.toStdString(), jobName.toStdString(), pid, sig);
}
void dqm4hep::DQMJobInterfaceWidget::startAllJobs () [slot]
Definition at line 386 of file DQMJobInterfaceWidget.cc.
References getNonRunningJobControls(), m_pJobIterface, and popupMissingJobControls().
Referenced by createActions().
{
    const Json::Value &root(m_pJobIterface->getRoot());
    StringVector hostList = root["HOSTS"].getMemberNames();
    QStringList nonRunningJobControls = getNonRunningJobControls();
    if(!nonRunningJobControls.isEmpty())
      popupMissingJobControls(nonRunningJobControls);
    // loop over hosts
    for(StringVector::iterator iter = hostList.begin(), endIter = hostList.end() ;
        endIter != iter ; ++iter)
    {
        m_pJobIterface->startJobs(*iter);
    }
}
void dqm4hep::DQMJobInterfaceWidget::startHostJobs () [slot]
Definition at line 339 of file DQMJobInterfaceWidget.cc.
References HOST_ITEM, jobControlExists(), m_pJobIterface, m_pTreeWidget, NAME, and popupMissingJobControl().
Referenced by createActions().
{
    QTreeWidgetItem* pSelectedItem = m_pTreeWidget->currentItem();
    if(!pSelectedItem)
        return;
    if(pSelectedItem->data(0, Qt::UserRole).value<int>() != HOST_ITEM)
        return;
    QString hostName = pSelectedItem->text(NAME);
    if(!this->jobControlExists(hostName.toStdString()))
    {
      popupMissingJobControl(hostName);
      return;
    }
    m_pJobIterface->startJobs(hostName.toStdString());
}
void dqm4hep::DQMJobInterfaceWidget::startSelectedJob () [slot]
Definition at line 362 of file DQMJobInterfaceWidget.cc.
References JOB_ITEM, jobControlExists(), m_pJobIterface, m_pTreeWidget, NAME, and popupMissingJobControl().
Referenced by createActions().
{
    QTreeWidgetItem* pSelectedItem = m_pTreeWidget->currentItem();
    if(!pSelectedItem)
        return;
    if(pSelectedItem->data(0, Qt::UserRole).value<int>() != JOB_ITEM)
        return;
    QString hostName = pSelectedItem->parent()->text(NAME);
    QString jobName = pSelectedItem->text(NAME);
    if(!this->jobControlExists(hostName.toStdString()))
    {
      popupMissingJobControl(hostName);
      return;
    }
    m_pJobIterface->startJob(hostName.toStdString(), jobName.toStdString());
}
void dqm4hep::DQMJobInterfaceWidget::updateJobStatus () [slot]
Definition at line 544 of file DQMJobInterfaceWidget.cc.
References m_pJobIterface, and updateStatus().
Referenced by createActions(), DQMJobInterfaceWidget(), and loadJsonFile().
{
    m_pJobIterface->status();
    struct timespec timesleep;
    timesleep.tv_sec = 0;
    timesleep.tv_nsec = 500000000L;
    nanosleep(&timesleep, NULL);
    this->updateStatus(m_pJobIterface->getProcessStatusValue());
}
void dqm4hep::DQMJobInterfaceWidget::updateStatus (const QString & hostName) [private], [slot]
Definition at line 728 of file DQMJobInterfaceWidget.cc.
References m_pJobIterface, m_pTreeWidget, NAME, PID, and STATUS.
Referenced by DQMJobInterfaceWidget(), and updateJobStatus().
{
  const Json::Value value = m_pJobIterface->processStatus(hostName.toStdString())["JOBS"];
    QTreeWidgetItem *pHostItem = 0;
    for(unsigned int i=0 ; i<m_pTreeWidget->topLevelItemCount() ; i++)
    {
        QTreeWidgetItem *pItem = m_pTreeWidget->topLevelItem(i);
        if(hostName == pItem->text(NAME))
          pHostItem = pItem;
    }
    if(!pHostItem)
      return;
    QMap<QString, QColor> stateToColorMap;
    stateToColorMap["Z"] = QColor(Qt::red); // zombie
    stateToColorMap["T"] = QColor(Qt::darkRed); // traced or stopped
    stateToColorMap["R"] = QColor(Qt::green); // running
    stateToColorMap["D"] = QColor(Qt::darkGreen); // un-interruptible sleep
    stateToColorMap["S"] = QColor(Qt::darkGreen); // interruptible sleep
    stateToColorMap["X"] = QColor(Qt::red); // interruptible sleep
  for(unsigned int j=0 ; j<pHostItem->childCount() ; j++)
  {
    QTreeWidgetItem *pJobItem = pHostItem->child(j);
    std::string jobName = pJobItem->text(NAME).toStdString();
    bool found = false;
    for(unsigned int v=0 ; v<value.size() ; v++)
    {
      std::string vHost = value[v]["HOST"].asString();
      std::string vJobName = value[v]["NAME"].asString();
      uint32_t vJobPid = value[v]["PID"].asUInt();
      std::string vJobStatus = value[v]["STATUS"].asString();
      if(vJobName == jobName)
      {
        pJobItem->setText(STATUS, QString(vJobStatus.c_str()).trimmed());
        pJobItem->setText(PID, QString::number(vJobPid));
        found = true;
        break;
      }
    }
    if(!found)
    {
      pJobItem->setText(STATUS, "X (dead)");
      pJobItem->setText(PID, "");
    }
    // cases available in /proc/pid/status file
    QMap<QString, QColor>::iterator findIter = stateToColorMap.find(pJobItem->text(
      STATUS).at(0));
    if(findIter != stateToColorMap.end())
      pJobItem->setData(STATUS, Qt::ForegroundRole, QBrush(findIter.value()));
    else
      pJobItem->setData(STATUS, Qt::ForegroundRole, QBrush(Qt::black));
  }
    m_pTreeWidget->header()->resizeSections(QHeaderView::Stretch);
}
void dqm4hep::DQMJobInterfaceWidget::updateStatus (const Json::Value & value) [private]
Definition at line 637 of file DQMJobInterfaceWidget.cc.
References m_pTreeWidget, NAME, PID, and STATUS.
{
    QMap<QString, QColor> stateToColorMap;
    stateToColorMap["Z"] = QColor(Qt::red); // zombie
    stateToColorMap["T"] = QColor(Qt::darkRed); // traced or stopped
    stateToColorMap["R"] = QColor(Qt::green); // running
    stateToColorMap["D"] = QColor(Qt::darkGreen); // un-interruptible sleep
    stateToColorMap["S"] = QColor(Qt::darkGreen); // interruptible sleep
    stateToColorMap["X"] = QColor(Qt::red); // interruptible sleep
    for(unsigned int i=0 ; i<m_pTreeWidget->topLevelItemCount() ; i++)
    {
        QTreeWidgetItem *pHostItem = m_pTreeWidget->topLevelItem(i);
        std::string hostName = pHostItem->text(NAME).toStdString();
        for(unsigned int j=0 ; j<pHostItem->childCount() ; j++)
        {
            QTreeWidgetItem *pJobItem = pHostItem->child(j);
            std::string jobName = pJobItem->text(NAME).toStdString();
            bool found = false;
            for(unsigned int v=0 ; v<value.size() ; v++)
            {
                std::string vHost = value[v]["HOST"].asString();
                std::string vJobName = value[v]["NAME"].asString();
                uint32_t vJobPid = value[v]["PID"].asUInt();
                std::string vJobStatus = value[v]["STATUS"].asString();
                if(vHost == hostName && vJobName == jobName)
                {
                    pJobItem->setText(STATUS, QString(vJobStatus.c_str()).trimmed());
                    pJobItem->setText(PID, QString::number(vJobPid));
                    found = true;
                    break;
                }
            }
            if(!found)
            {
                pJobItem->setText(STATUS, "X (dead)");
                pJobItem->setText(PID, "");
            }
            // cases available in /proc/pid/status file
      QMap<QString, QColor>::iterator findIter = stateToColorMap.find(pJobItem->text(
      STATUS).at(0));
      if(findIter != stateToColorMap.end())
        pJobItem->setData(STATUS, Qt::ForegroundRole, QBrush(findIter.value()));
      else
        pJobItem->setData(STATUS, Qt::ForegroundRole, QBrush(Qt::black));
        }
    }
    m_pTreeWidget->header()->resizeSections(QHeaderView::Stretch);
}
Member Data Documentation
std::string dqm4hep::DQMJobInterfaceWidget::m_currentJsonFile [private]
Definition at line 200 of file DQMJobInterfaceWidget.h.
Referenced by getCurrentJsonFile(), loadJsonFile(), and reloadJsonFile().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pAutomaticModeButton [private]
Definition at line 202 of file DQMJobInterfaceWidget.h.
Referenced by DQMJobInterfaceWidget(), and handleAutomaticModeButtonClicked().
QAction* dqm4hep::DQMJobInterfaceWidget::m_pClearAllJobsAction [private]
Definition at line 238 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent(), and createActions().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pClearAllJobsButton [private]
Definition at line 217 of file DQMJobInterfaceWidget.h.
QAction* dqm4hep::DQMJobInterfaceWidget::m_pClearHostJobsAction [private]
Definition at line 232 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent(), and createActions().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pClearHostJobsButton [private]
Definition at line 213 of file DQMJobInterfaceWidget.h.
QMenu* dqm4hep::DQMJobInterfaceWidget::m_pContextMenu [private]
Definition at line 224 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent().
QMenu* dqm4hep::DQMJobInterfaceWidget::m_pFileMenu [private]
Definition at line 225 of file DQMJobInterfaceWidget.h.
Referenced by createMenus().
QMenu* dqm4hep::DQMJobInterfaceWidget::m_pHelpMenu [private]
Definition at line 226 of file DQMJobInterfaceWidget.h.
DQMJobInterface* dqm4hep::DQMJobInterfaceWidget::m_pJobIterface [private]
Definition at line 199 of file DQMJobInterfaceWidget.h.
Referenced by clearAllJobs(), clearHostJobs(), DQMJobInterfaceWidget(), getJobInterface(), handleAutomaticModeButtonClicked(), handleAutomaticModeValueChanged(), killSelectedJob(), loadJsonFile(), restartAllJobs(), restartSelectedJob(), startAllJobs(), startHostJobs(), startSelectedJob(), updateJobStatus(), updateStatus(), and ~DQMJobInterfaceWidget().
QComboBox* dqm4hep::DQMJobInterfaceWidget::m_pKillComboBoxWidget [private]
Definition at line 205 of file DQMJobInterfaceWidget.h.
Referenced by DQMJobInterfaceWidget(), killSelectedJob(), restartAllJobs(), and restartSelectedJob().
QAction* dqm4hep::DQMJobInterfaceWidget::m_pKillJobAction [private]
Definition at line 234 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent(), and createActions().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pKillJobButton [private]
Definition at line 214 of file DQMJobInterfaceWidget.h.
QAction* dqm4hep::DQMJobInterfaceWidget::m_pLoadFileAction [private]
Definition at line 228 of file DQMJobInterfaceWidget.h.
Referenced by createActions(), and createMenus().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pLoadFileButton [private]
Definition at line 209 of file DQMJobInterfaceWidget.h.
Referenced by DQMJobInterfaceWidget().
QMenuBar* dqm4hep::DQMJobInterfaceWidget::m_pMenuBar [private]
Definition at line 223 of file DQMJobInterfaceWidget.h.
Referenced by createMenus().
QAction* dqm4hep::DQMJobInterfaceWidget::m_pReloadFileAction [private]
Definition at line 229 of file DQMJobInterfaceWidget.h.
Referenced by createActions(), and createMenus().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pReloadFileButton [private]
Definition at line 210 of file DQMJobInterfaceWidget.h.
Referenced by DQMJobInterfaceWidget().
QAction* dqm4hep::DQMJobInterfaceWidget::m_pRestartAllJobsAction [private]
Definition at line 239 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent(), and createActions().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pRestartAllJobsButton [private]
Definition at line 218 of file DQMJobInterfaceWidget.h.
QAction* dqm4hep::DQMJobInterfaceWidget::m_pRestartJobAction [private]
Definition at line 236 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent(), and createActions().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pRestartJobButton [private]
Definition at line 215 of file DQMJobInterfaceWidget.h.
QAction* dqm4hep::DQMJobInterfaceWidget::m_pStartAllJobsAction [private]
Definition at line 240 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent(), and createActions().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pStartAllJobsButton [private]
Definition at line 219 of file DQMJobInterfaceWidget.h.
QAction* dqm4hep::DQMJobInterfaceWidget::m_pStartHostJobsAction [private]
Definition at line 231 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent(), and createActions().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pStartHostJobsButton [private]
Definition at line 212 of file DQMJobInterfaceWidget.h.
QAction* dqm4hep::DQMJobInterfaceWidget::m_pStartJobAction [private]
Definition at line 235 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent(), and createActions().
QTreeWidget* dqm4hep::DQMJobInterfaceWidget::m_pTreeWidget [private]
Definition at line 207 of file DQMJobInterfaceWidget.h.
Referenced by clearHostJobs(), contextMenuEvent(), DQMJobInterfaceWidget(), getNonRunningJobControls(), killSelectedJob(), loadJson(), loadJsonFile(), restartAllJobs(), restartSelectedJob(), startHostJobs(), startSelectedJob(), and updateStatus().
QAction* dqm4hep::DQMJobInterfaceWidget::m_pUpdateAction [private]
Definition at line 242 of file DQMJobInterfaceWidget.h.
Referenced by contextMenuEvent(), and createActions().
QPushButton* dqm4hep::DQMJobInterfaceWidget::m_pUpdateButton [private]
Definition at line 221 of file DQMJobInterfaceWidget.h.
Referenced by DQMJobInterfaceWidget().
QSpinBox* dqm4hep::DQMJobInterfaceWidget::m_pUpdatePeriodSpinBox [private]
Definition at line 203 of file DQMJobInterfaceWidget.h.
Referenced by DQMJobInterfaceWidget(), and handleAutomaticModeButtonClicked().
The documentation for this class was generated from the following files:
DQMJobInterfaceWidget.h
DQMJobInterfaceWidget.cc