dqm4hep::DQMMonitoringController Class Reference
DQMMonitoringController class.
#include <DQMMonitoringController.h>
Public Slots
void querySubscribedMonitorElements ()
Send a query to the all collectors to send back the subscribed monitor elements.
void openFile ()
Open a file from a file dialog.
void openFile (const std::string &fileName)
Workhorse of the openfile() method.
void saveAs ()
Open a file dialog and save the current view and model to the target file.
void saveAs (const std::string &fileName) const
Workhorse of the saveAs() method.
void openBrowser ()
Open a browser widget in a separate window.
void aboutDQM4HEP ()
Open about DQM4HEP pop up dialog.
void openDoxygenDoc ()
Open the doxygen documentation (if exists) in the default web browser.
void openUserGuide ()
Open user guide (pdf) in the default pdf reader.
void openGithubPage ()
Open the DQM4HEP github page in the default web browser.
void openIssuesPage ()
Open the DQM4HEP issues github page in the default web browser.
void openMonitorElementInfo (DQMGuiMonitorElement *pMonitorElement) const
Open a monitor element info widget in a dialog.
void openQualityTestResults (DQMGuiMonitorElement *pMonitorElement) const
Open a monitor element info widget in a dialog.
void openInROOTWindow (DQMGuiMonitorElement *pMonitorElement) const
Fork a process and open the monitor element in root canvas.
void saveAs (DQMCanvasArea *pCanvasArea)
Save all the canvases of the canvas area in a file Different file format available.
void saveAs (DQMCanvas *pCanvas)
Save the canvas in a file Different file format available.
void clear ()
Clear the controller.
void clearViewAndModel ()
Clear the model and view of the monitoring system.
void clearMonitoring ()
Clear the model, view and controller.
void quit ()
Exit the monitoring application.
Public Member Functions
DQMMonitoringController (DQMMonitoring *pMonitoring)
Constructor.
~DQMMonitoringController ()
Destructor.
DQMMonitoring * getMonitoring () const
Get the monitoring instance.
void log (const std::string &message)
Log a message in the application.
void log (LogLevel level, const std::string &message)
Log in the logger with a log level.
DQMGuiMonitorElementClient * createClient (const std::string &collectorName)
Create a monitor element client from the collector name.
DQMGuiMonitorElementClient * getClient (const std::string &collectorName)
Get a registered client.
DQMGuiMonitorElementClient * findClient (const std::string &collectorName)
Find a client.
void removeClient (const std::string &collectorName)
Remove a client from the application.
void createEmptyMonitorElements (const std::string &collectorName, const DQMMonitorElementInfoList &nameList)
Fill the model and the view view empty monitor elements.
void subscribe (const std::string &collectorName, const DQMMonitorElementRequest &request)
Subscribe to monitor elements of the target collector.
void unsubscribe (const std::string &collectorName, const DQMMonitorElementRequest &request)
Un-subscribe to monitor elements of the target collector.
void querySubscribedMonitorElements (const std::string &collectorName)
Send a query to the target collector to send back the subscribed monitor elements.
void querySubscribedMonitorElements (const std::string &collectorName, const DQMMonitorElementRequest &request)
Send a query to the target collector to subscribe to the element list (if not done yet) and send back the monitor elements in the request.
void unsubscribe (const std::string &collectorName)
Un-subscribe to all monitor elements of the target collector.
void setUpdateMode (bool updateMode)
Set the update mode of the target collector.
bool getUpdateMode () const
Get the update mode.
void queryUpdate (DQMGuiMonitorElement *pMonitorElement)
Send a query to the collector to first subscribed to the element if not done yet, then to send back the element if collected on the server.
void queryUpdate (const DQMGuiMonitorElementList &monitorElementList)
Send a query to the collector to first subscribed to the elements if not done yet, then to send back the elements if collected on the server.
QColor getColor (DQMQuality quality) const
Get the color associated to the data quality.
QIcon getIcon (DQMQuality quality) const
Get the icon associated to the data quality.
Private Types
typedef std::map< std::string,
*
DQMGuiMonitorElementClient * > DQMGuiMonitorElementClientMap
Private Slots
void receiveMonitorElementPublication (const DQMMonitorElementPublication &publication)
Call back method called by monitor element clients when a publication is received.
void handleServerStartup ()
Send the list of subscribed elements to the collector.
void handleServerShutdown ()
Send the list of subscribed elements to the collector.
Private Attributes
DQMMonitoring * m_pMonitoring
bool m_updateMode
DQMGuiMonitorElementClientMap m_clientMap
QMap< LogLevel, QString > m_logLevelToTextMap
Detailed Description
DQMMonitoringController class.
Definition at line 54 of file DQMMonitoringController.h.
Member Typedef Documentation
typedef std::map<std::string, DQMGuiMonitorElementClient*> dqm4hep::DQMMonitoringController::DQMGuiMonitorElementClientMap [private]
Definition at line 58 of file DQMMonitoringController.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitoringController::DQMMonitoringController (DQMMonitoring * pMonitoring)
Constructor.
Definition at line 66 of file DQMMonitoringController.cc.
References m_logLevelToTextMap, m_pMonitoring, and dqm4hep::DQMMonitoring::setController().
                                                                           :
  m_pMonitoring(pMonitoring),
  m_updateMode(false)
{
  m_pMonitoring->setController(this);
  m_logLevelToTextMap.insert(DEBUG, "[DEBUG] ");
  m_logLevelToTextMap.insert(MESSAGE, "[MESSAGE] ");
  m_logLevelToTextMap.insert(WARNING, "[WARNING] ");
  m_logLevelToTextMap.insert(ERROR, "[ERROR] ");
}
dqm4hep::DQMMonitoringController::~DQMMonitoringController ()
Destructor.
Definition at line 80 of file DQMMonitoringController.cc.
References clear().
{
  clear();
}
Member Function Documentation
void dqm4hep::DQMMonitoringController::aboutDQM4HEP () [slot]
Open about DQM4HEP pop up dialog.
Definition at line 642 of file DQMMonitoringController.cc.
References DQMViz_DIR, DQMViz_VERSION_STR, and getMonitoring().
{
  QString iconDir = QString(DQMViz_DIR) + "/icons";
  QStringList authorList;
  authorList << "R. Ete , IPNL"
      << "A. Pingault, GHENT"
      << "L. Mirabito, IPNL";
  QString text;
  text += "DQMHEP : Data Quality Monitoring for High Energy Physics\n\n";
  text += "Version : "+ QString(DQMViz_VERSION_STR) + "\n\n";
  text += "DQM4HEP is free software: you can redistribute it and/or modify ";
  text += "it under the terms of the GNU General Public License as published by";
  text += "the Free Software Foundation, either version 3 of the License, or";
  text += "(at your option) any later version.\n\n";
  text += "DQM4HEP is distributed in the hope that it will be useful,";
  text += "but WITHOUT ANY WARRANTY; without even the implied warranty of";
  text += "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the";
  text += "GNU General Public License for more details.\n\n";
  text += "You should have received a copy of the GNU General Public License";
  text += "along with DQM4HEP. If not, see <http://www.gnu.org/licenses/>.\n\n";
  text += "Authors :\n";
  text += " * R. Ete , IPNL\n";
  text += " * A. Pingault, Ghent University\n";
  text += " * L. Mirabito, IPNL\n\n";
  text += "Please, send comments or report bug via the github interface ";
  text += "<https://github.com/DQM4HEP/DQMViz/issues>";
  QMessageBox *pMessageBox = new QMessageBox(this->getMonitoring()->getView()->getMainWindow());
  pMessageBox->setWindowTitle("About DQM4HEP");
  pMessageBox->setIconPixmap(QPixmap(iconDir + "/MON_WIN.png").scaled(QSize(100, 100),
      Qt::KeepAspectRatioByExpanding));
  pMessageBox->setText(text);
  pMessageBox->exec();
  pMessageBox->deleteLater();
}
void dqm4hep::DQMMonitoringController::clear () [slot]
Clear the controller.
This will remove all client connections. The view and model are not clear. Use clearViewAndModel() to clear only the model and view or use clearMonitoring() to clear the model, view and controller.
Definition at line 1000 of file DQMMonitoringController.cc.
References m_clientMap, and m_updateMode.
Referenced by clearMonitoring(), openFile(), and ~DQMMonitoringController().
{
  for(DQMGuiMonitorElementClientMap::iterator iter = m_clientMap.begin(), endIter =
      m_clientMap.end() ;
      endIter != iter ; ++iter)
  {
    iter->second->deleteLater();
  }
  m_clientMap.clear();
  m_updateMode = false;
}
void dqm4hep::DQMMonitoringController::clearMonitoring () [slot]
Clear the model, view and controller.
Definition at line 1022 of file DQMMonitoringController.cc.
References dqm4hep::DQMMonitoringModel::clear(), dqm4hep::DQMMonitoringView::clear(), clear(), dqm4hep::DQMMonitoring::getModel(), getMonitoring(), and dqm4hep::DQMMonitoring::getView().
Referenced by quit().
{
  // first clear the client connections to avoid updates
  this->clear();
  // clear contents
  this->getMonitoring()->getView()->clear();
  this->getMonitoring()->getModel()->clear();
}
void dqm4hep::DQMMonitoringController::clearViewAndModel () [slot]
Clear the model and view of the monitoring system.
The clients update mode is set to false, disabling automatic updates. The client connections are not removed. Use clearMonitoring() to also clear the client connections. Use clear() to clear only the client connections and keep the view and model
Definition at line 1014 of file DQMMonitoringController.cc.
References dqm4hep::DQMMonitoringModel::clear(), dqm4hep::DQMMonitoringView::clear(), dqm4hep::DQMMonitoring::getModel(), getMonitoring(), and dqm4hep::DQMMonitoring::getView().
Referenced by dqm4hep::DQMBrowserWidget::handleReplaceButtonClicked().
{
  this->getMonitoring()->getView()->clear();
  this->getMonitoring()->getModel()->clear();
}
DQMGuiMonitorElementClient * dqm4hep::DQMMonitoringController::createClient (const std::string & collectorName)
Create a monitor element client from the collector name.
Act as a factory method. The client is not registered. To get a registered client, use getClient(n) instead
Definition at line 109 of file DQMMonitoringController.cc.
Referenced by dqm4hep::DQMBrowserWidget::handleCollectorSelection().
{
  std::cout << "Creating collector client for " << collectorName << std::endl;
  return new DQMGuiMonitorElementClient(collectorName);
}
void dqm4hep::DQMMonitoringController::createEmptyMonitorElements (const std::string & collectorName, const DQMMonitorElementInfoList & nameList)
Fill the model and the view view empty monitor elements.
Empty monitor elements are created. If draw action is requested, a 'no viz' canvas will be drawn
Definition at line 170 of file DQMMonitoringController.cc.
References dqm4hep::DQMMonitoring::getModel(), getMonitoring(), and dqm4hep::DQMMonitoringModel::loadMonitorElementInfoList().
Referenced by dqm4hep::DQMBrowserWidget::handleReplaceButtonClicked(), and dqm4hep::DQMBrowserWidget::handleUpdateButtonClicked().
{
  this->getMonitoring()->getModel()->loadMonitorElementInfoList(collectorName, nameList);
}
DQMGuiMonitorElementClient * dqm4hep::DQMMonitoringController::findClient (const std::string & collectorName)
Find a client.
Returns NULL is not registered
Definition at line 144 of file DQMMonitoringController.cc.
References m_clientMap.
{
  DQMGuiMonitorElementClientMap::iterator findIter = m_clientMap.find(collectorName);
  if(m_clientMap.end() != findIter)
    return findIter->second;
  return NULL;
}
DQMGuiMonitorElementClient * dqm4hep::DQMMonitoringController::getClient (const std::string & collectorName)
Get a registered client.
If the client is not registered, it is created and added on the fly to the list of registered clients
Definition at line 117 of file DQMMonitoringController.cc.
References handleServerShutdown(), handleServerStartup(), m_clientMap, m_updateMode, and receiveMonitorElementPublication().
Referenced by dqm4hep::DQMBrowserWidget::handleReplaceButtonClicked(), dqm4hep::DQMBrowserWidget::handleUpdateButtonClicked(), openFile(), querySubscribedMonitorElements(), subscribe(), and unsubscribe().
{
  DQMGuiMonitorElementClientMap::iterator findIter = m_clientMap.find(collectorName);
  if(m_clientMap.end() != findIter)
    return findIter->second;
  DQMGuiMonitorElementClient *pNewClient = this->createClient(collectorName);
  // to receive monitor elements
  connect(pNewClient, SIGNAL(monitorElementPublicationReceived(const DQMMonitorElementPublication &)),
      this, SLOT(receiveMonitorElementPublication(const DQMMonitorElementPublication &)));
  // to handle server startup
  connect(pNewClient, SIGNAL(onServerStartup()), this, SLOT(handleServerStartup()));
  // to handle server shutdown
  connect(pNewClient, SIGNAL(onServerShutdown()), this, SLOT(
      handleServerShutdown()));
  m_clientMap.insert(DQMGuiMonitorElementClientMap::value_type(collectorName, pNewClient));
  pNewClient->getMonitorElementClient()->setUpdateMode(m_updateMode);
  return pNewClient;
}
QColor dqm4hep::DQMMonitoringController::getColor (DQMQuality quality) const
Get the color associated to the data quality.
Definition at line 429 of file DQMMonitoringController.cc.
{
  QMap<DQMQuality, QColor> colorPalette;
  colorPalette.insert(NO_QUALITY, QColor(Qt::gray));
  colorPalette.insert(VERY_BAD_QUALITY, QColor(Qt::darkRed));
  colorPalette.insert(BAD_QUALITY, QColor(Qt::darkYellow));
  colorPalette.insert(NORMAL_QUALITY, QColor(Qt::black));
  colorPalette.insert(GOOD_QUALITY, QColor(Qt::darkBlue));
  colorPalette.insert(VERY_GOOD_QUALITY, QColor(Qt::darkGreen));
  QMap<DQMQuality, QColor>::const_iterator findIter = colorPalette.find(quality);
  if(colorPalette.end() == findIter)
    return colorPalette[NO_QUALITY];
  return findIter.value();
}
QIcon dqm4hep::DQMMonitoringController::getIcon (DQMQuality quality) const
Get the icon associated to the data quality.
Definition at line 450 of file DQMMonitoringController.cc.
References DQMViz_DIR.
Referenced by dqm4hep::DQMMonitorElementNavigator::updateMonitorElement(), and dqm4hep::DQMRootWidget::updateMonitorElement().
{
  QMap<DQMQuality, QIcon> iconMap;
  QString iconDir = QString(DQMViz_DIR) + "/icons/";
  iconMap.insert(NO_QUALITY, QIcon(iconDir + "ME_N.xpm"));
  iconMap.insert(VERY_BAD_QUALITY, QIcon(iconDir + "ME_VB.xpm"));
  iconMap.insert(BAD_QUALITY, QIcon(iconDir + "ME_B.xpm"));
  iconMap.insert(NORMAL_QUALITY, QIcon(iconDir + "ME_N.xpm"));
  iconMap.insert(GOOD_QUALITY, QIcon(iconDir + "ME_G.xpm"));
  iconMap.insert(VERY_GOOD_QUALITY, QIcon(iconDir + "ME_VG.xpm"));
  QMap<DQMQuality, QIcon>::const_iterator findIter = iconMap.find(quality);
  if(iconMap.end() == findIter)
    return iconMap[NO_QUALITY];
  return findIter.value();
}
DQMMonitoring * dqm4hep::DQMMonitoringController::getMonitoring () const
Get the monitoring instance.
Definition at line 87 of file DQMMonitoringController.cc.
References m_pMonitoring.
Referenced by aboutDQM4HEP(), clearMonitoring(), clearViewAndModel(), createEmptyMonitorElements(), handleServerShutdown(), handleServerStartup(), log(), openBrowser(), openDoxygenDoc(), openFile(), receiveMonitorElementPublication(), and saveAs().
{
  return m_pMonitoring;
}
bool dqm4hep::DQMMonitoringController::getUpdateMode () const
Get the update mode.
Definition at line 304 of file DQMMonitoringController.cc.
References m_updateMode.
Referenced by dqm4hep::DQMMonitoringView::handleAutoUpdateButtonClicked().
{
  return m_updateMode;
}
void dqm4hep::DQMMonitoringController::handleServerShutdown () [private], [slot]
Send the list of subscribed elements to the collector.
This is usually called when the server is restarted after a shutdown, a manual restart or a crash. Send also the update mode
Definition at line 403 of file DQMMonitoringController.cc.
References dqm4hep::DQMMonitorElementView::enableSubscription(), dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient(), dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), and dqm4hep::DQMMonitorElementView::uncheckAllMonitorElements().
Referenced by getClient().
{
  DQMGuiMonitorElementClient *pGuiClient = qobject_cast<DQMGuiMonitorElementClient *>(sender());
  if(!pGuiClient)
    return;
  DQMMonitorElementClient *pClient = pGuiClient->getMonitorElementClient();
  std::string collectorName = pClient->getCollectorName();
  QMessageBox::warning(this->getMonitoring()->getView()->getMainWindow(),
      "Collector shutdown",
      QString("The following monitor element collector was shut down :\n\n"
      "* %1\n\n"
      "If you need to restart it, type in a terminal :\n"
      " dqm4hep_start_monitor_element_collector -c %1 \n"
      "or restart it from the job control.").arg(collectorName.c_str()));
  DQMMonitorElementView *pMeView = this->getMonitoring()->getView()->
      getMonitorElementView();
  pMeView->uncheckAllMonitorElements(collectorName);
  std::cout << "pMeView->enableSubscription(collectorName, false); " << std::endl;
  pMeView->enableSubscription(collectorName, false);
}
void dqm4hep::DQMMonitoringController::handleServerStartup () [private], [slot]
Send the list of subscribed elements to the collector.
This is usually called when the server is restarted after a shutdown, a manual restart or a crash. Send also the update mode
Definition at line 364 of file DQMMonitoringController.cc.
References dqm4hep::DQMMonitorElementView::enableSubscription(), dqm4hep::DQMMonitorElementView::getCheckedMonitorElements(), dqm4hep::DQMMonitorElementNavigator::getFullPathName(), dqm4hep::DQMMonitorElementNavigator::getModuleName(), dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient(), dqm4hep::DQMMonitoringView::getMonitorElementView(), getMonitoring(), and dqm4hep::DQMMonitoring::getView().
Referenced by getClient().
{
  DQMGuiMonitorElementClient *pGuiClient = qobject_cast<DQMGuiMonitorElementClient *>(sender());
  if(!pGuiClient)
    return;
  DQMMonitorElementClient *pClient = pGuiClient->getMonitorElementClient();
  std::string collectorName = pClient->getCollectorName();
  std::cout << collectorName << " server startup !" << std::endl;
  // get all subscribed elements
  DQMMonitorElementView *pMeView = this->getMonitoring()->getView()->
      getMonitorElementView();
  pMeView->enableSubscription(collectorName, true);
  QList<QTreeWidgetItem *> items = pMeView->getCheckedMonitorElements(collectorName);
  DQMMonitorElementRequest request;
  for(int j=0 ; j<items.size() ; j++)
  {
    DQMMonitorElementNavigator *pNavigator = qobject_cast<DQMMonitorElementNavigator *>(items.at(j)->
      treeWidget());
    std::string moduleName = pNavigator->getModuleName(items.at(j)).toStdString();
    std::string path = pNavigator->getFullPathName(items.at(j)).toStdString();
    std::string name = items.at(j)->text(0).toStdString();
    std::string fullName = (DQMPath(path) + name).getPath();
    request.push_back(DQMMonitorElementRequest::value_type(moduleName, fullName));
  }
  if(!pClient->isConnectedToService())
    pClient->connectToService();
  pClient->replaceSubscription(request);
}
void dqm4hep::DQMMonitoringController::log (const std::string & message)
Log a message in the application.
Log level is 'MESSAGE'
Definition at line 94 of file DQMMonitoringController.cc.
Referenced by dqm4hep::DQMMonitorElementNavigator::drawSelectedMonitorElements(), dqm4hep::DQMCanvasArea::dropEvent(), dqm4hep::DQMMonitorElementNavigator::handleItemDoubleClick(), querySubscribedMonitorElements(), dqm4hep::TreeWidgetItem::setData(), dqm4hep::DQMMonitorElementNavigator::startDrag(), subscribe(), and unsubscribe().
{
  this->log(MESSAGE, message);
}
void dqm4hep::DQMMonitoringController::log (LogLevel level, const std::string & message)
Log in the logger with a log level.
Definition at line 101 of file DQMMonitoringController.cc.
References dqm4hep::DQMMonitoringView::getMainWindow(), getMonitoring(), dqm4hep::DQMMonitoring::getView(), and m_logLevelToTextMap.
{
  QString completeMessage = m_logLevelToTextMap.find(level).value() + message.c_str();
  this->getMonitoring()->getView()->getMainWindow()->statusBar()->showMessage(completeMessage, 2000);
}
void dqm4hep::DQMMonitoringController::openBrowser () [slot]
Open a browser widget in a separate window.
The browser is deleted on close action
Definition at line 626 of file DQMMonitoringController.cc.
References DQMViz_DIR, and getMonitoring().
{
  DQMBrowserWidget *pBrowser = new DQMBrowserWidget(this->getMonitoring());
  pBrowser->setWindowTitle("DQM Browser");
  QString iconDir = QString(DQMViz_DIR) + "/icons";
  pBrowser->setWindowIcon(QIcon(iconDir + "/MON_BROWSER.png"));
  pBrowser->setAttribute(Qt::WA_DeleteOnClose, true);
  pBrowser->show();
  QObject::connect(this->getMonitoring()->getView()->getMainWindow(), SIGNAL(destroyed()), pBrowser, SLOT(
      close()));
}
void dqm4hep::DQMMonitoringController::openDoxygenDoc () [slot]
Open the doxygen documentation (if exists) in the default web browser.
Definition at line 690 of file DQMMonitoringController.cc.
References getMonitoring().
{
  QString indexHtml;
  indexHtml += DQMCore_DIR;
  indexHtml += "/doc/html/index.html";
  QDir dir;
  if(!dir.exists(indexHtml))
  {
    QMessageBox::information(this->getMonitoring()->getView()->getMainWindow(),
        "Not found",
        "DQM4HEP was not built with Doxygen documentation. Sorry !");
    return;
  }
  QDesktopServices::openUrl(QUrl::fromLocalFile(indexHtml));
}
void dqm4hep::DQMMonitoringController::openFile () [slot]
Open a file from a file dialog.
This will clear the current view and model and reload a new one.
Definition at line 472 of file DQMMonitoringController.cc.
References getMonitoring().
{
    QString fileName = QFileDialog::getOpenFileName(this->getMonitoring()->getView()->getMainWindow(), tr("
      Import file"),
                    QString(""),
                    "XML files (*.xml)");
    if(fileName.isEmpty())
            return;
  this->openFile(fileName.toStdString());
}
void dqm4hep::DQMMonitoringController::openFile (const std::string & fileName) [slot]
Workhorse of the openfile() method.
Definition at line 486 of file DQMMonitoringController.cc.
References dqm4hep::DQMMonitoringModel::clear(), dqm4hep::DQMMonitoringView::clear(), clear(), dqm4hep::DQMMonitoringView::fromXml(), getClient(), dqm4hep::DQMMonitoring::getModel(), getMonitoring(), and dqm4hep::DQMMonitoring::getView().
{
  TiXmlDocument document(fileName);
  if(!document.LoadFile())
  {
    QMessageBox::warning(this->getMonitoring()->getView()->getMainWindow(),
        "XML Import",
        "Couldn't import selection from xml file :\n\n"
        "* Invalid XML file content");
    return;
  }
  TiXmlHandle documentHandle(&document);
  TiXmlElement *pRootElement = documentHandle.FirstChildElement().Element();
  if(!pRootElement)
  {
    QMessageBox::warning(this->getMonitoring()->getView()->getMainWindow(),
        "XML Import",
        "Couldn't import selection from xml file :\n\n"
        "* No root element found");
    return;
  }
  TiXmlHandle rootHandle(pRootElement);
  TiXmlElement *pMonitoringElement = rootHandle.FirstChild("monitoring").Element();
  if(!pMonitoringElement)
  {
    QMessageBox::warning(this->getMonitoring()->getView()->getMainWindow(),
        "XML Import",
        "Couldn't import selection from xml file :\n\n"
        "* No <monitoring> element found");
    return;
  }
  TiXmlHandle monitoringHandle(pMonitoringElement);
  this->clear();
  this->getMonitoring()->getModel()->clear();
  this->getMonitoring()->getView()->clear();
  TiXmlElement *pDimDnsNodeElement = monitoringHandle.FirstChild("dimDnsNode").Element();
  if(pDimDnsNodeElement)
  {
    std::string dimDnsNode;
    if(!pDimDnsNodeElement->QueryStringAttribute("value", &dimDnsNode))
      DimClient::setDnsNode(dimDnsNode.c_str());
  }
  TiXmlElement *pViewElement = monitoringHandle.FirstChild("view").Element();
  if(pViewElement)
    this->getMonitoring()->getView()->fromXml(pViewElement);
  TiXmlElement *pControllerElement = monitoringHandle.FirstChild("controller").Element();
  if(pControllerElement)
  {
    TiXmlHandle controllerHandle(pControllerElement);
        for (TiXmlElement *pCollectorElement = controllerHandle.FirstChild("collector").Element(); NULL !=
      pCollectorElement;
            pCollectorElement = pCollectorElement->NextSiblingElement("collector"))
        {
          std::string collectorName;
            if(pCollectorElement->QueryStringAttribute("name", &collectorName))
                continue;
            this->getClient(collectorName);
        }
  }
}
void dqm4hep::DQMMonitoringController::openGithubPage () [slot]
Open the DQM4HEP github page in the default web browser.
Definition at line 717 of file DQMMonitoringController.cc.
{
  QDesktopServices::openUrl(QUrl("https://github.com/DQM4HEP"));
}
void dqm4hep::DQMMonitoringController::openInROOTWindow (DQMGuiMonitorElement * pMonitorElement) const [slot]
Fork a process and open the monitor element in root canvas.
By doing this, the gui client becomes the ROOT one and the monitor element in the ROOT process won't be updated.
Definition at line 769 of file DQMMonitoringController.cc.
References dqm4hep::DQMGuiMonitorElement::getMonitorElement().
Referenced by dqm4hep::DQMRootWidget::openROOTPanel().
{
  TObject *pObject = pMonitorElement->getMonitorElement()->getObject();
  if(!pObject)
    return;
  pid_t pid = fork();
  // parent process
  if(pid != 0)
    return;
  // child process
  char templateFile[] = "/tmp/canvasTmpXXXXXX.root";
  int ret = mkstemps(templateFile, 5);
  if(ret < 0)
    exit(-1);
  std::string tmpRootFileName = templateFile;
  TFile *pTmpRootFile = TFile::Open(tmpRootFileName.c_str(), "RECREATE");
  if(!pTmpRootFile)
    exit(1);
  // re-add the pave stats
  TH1 *pHistogram = (TH1*)pObject;
  if(pHistogram)
    pHistogram->SetStats(1);
  pTmpRootFile->cd();
  pObject->Write("dqm4hep_open_root_canvas");
  delete pTmpRootFile;
  // full program name
  std::string fullPathProg = std::string(DQMCore_DIR) + "/bin/dqm4hep_open_root_canvas";
  char executivePath[1000];
  memset(executivePath, 0, 1000);
  memcpy(executivePath, fullPathProg.c_str(), fullPathProg.size());
  // fill arguments
  const unsigned int maxNArgs = 100;
  const unsigned int maxMArgs = 1000;
  char argv[maxNArgs][maxMArgs];
  char *pArgv[maxNArgs];
  for(unsigned int i=0 ; i<maxNArgs ; i++)
    for(unsigned int j=0 ; j<maxMArgs ; j++)
      argv[i][j] = char(NULL);
  pArgv[0] = executivePath;
  sprintf(argv[1], "%s", "-f");
  pArgv[1] = & argv[1][0];
  sprintf(argv[2], "%s", tmpRootFileName.c_str());
  pArgv[2] = & argv[2][0];
  pArgv[3] = NULL;
  // fill environment
  const unsigned int maxNEnv = 10;
  const unsigned int maxMEnv = 1000;
  char env[maxNEnv][maxMEnv];
  char *pEnv[maxNEnv];
  for(unsigned int i=0 ; i<maxNEnv ; i++)
    for(unsigned int j=0 ; j<maxMEnv ; j++)
      env[i][j] = char(NULL);
  sprintf(env[0], "%s", "DISPLAY=:0");
  pEnv[0] = & env[0][0];
  pEnv[1] = NULL;
  // start root panel from dqm4hep specific executable
  int execveRet = execve(executivePath, pArgv, pEnv);
  streamlog_out(ERROR) << "ERROR ! execve returned " << execveRet << " with errno set to " << errno <<
      std::endl;
  streamlog_out(ERROR) << "Aborting" << std::endl;
  exit(1);
}
void dqm4hep::DQMMonitoringController::openIssuesPage () [slot]
Open the DQM4HEP issues github page in the default web browser.
Definition at line 724 of file DQMMonitoringController.cc.
{
  QDesktopServices::openUrl(QUrl("https://github.com/DQM4HEP/DQMViz/issues"));
}
void dqm4hep::DQMMonitoringController::openMonitorElementInfo (DQMGuiMonitorElement * pMonitorElement) const [slot]
Open a monitor element info widget in a dialog.
The tab is set `me info`
Definition at line 731 of file DQMMonitoringController.cc.
References dqm4hep::DQMGuiMonitorElement::getMonitorElement(), dqm4hep::DQMMonitorElementInfoWidget::MONITOR_ELEMENT_INFO, and dqm4hep::DQMMonitorElementInfoWidget::showTab().
Referenced by dqm4hep::DQMRootWidget::showMonitorElementInfo().
{
  QDialog *pDialog = new QDialog();
  pDialog->setWindowTitle("Monitor element info (" + QString(pGuiMonitorElement->getMonitorElement()->
      getName().c_str()) + ")");
  QHBoxLayout *pLayout = new QHBoxLayout();
  pDialog->setLayout(pLayout);
  DQMMonitorElementInfoWidget *pMEInfoWidget = new DQMMonitorElementInfoWidget(pGuiMonitorElement);
  pMEInfoWidget->showTab(DQMMonitorElementInfoWidget::MONITOR_ELEMENT_INFO);
  pLayout->addWidget(pMEInfoWidget);
  pDialog->exec();
  pDialog->deleteLater();
}
void dqm4hep::DQMMonitoringController::openQualityTestResults (DQMGuiMonitorElement * pMonitorElement) const [slot]
Open a monitor element info widget in a dialog.
The tab is set `qtest results`
Definition at line 750 of file DQMMonitoringController.cc.
References dqm4hep::DQMGuiMonitorElement::getMonitorElement(), dqm4hep::DQMMonitorElementInfoWidget::QUALITY_TEST_RESULTS, and dqm4hep::DQMMonitorElementInfoWidget::showTab().
Referenced by dqm4hep::DQMRootWidget::showQTestResults().
{
  QDialog *pDialog = new QDialog();
  pDialog->setWindowTitle("Monitor element info (" + QString(pGuiMonitorElement->getMonitorElement()->
      getName().c_str()) + ")");
  QHBoxLayout *pLayout = new QHBoxLayout();
  pDialog->setLayout(pLayout);
  DQMMonitorElementInfoWidget *pMEInfoWidget = new DQMMonitorElementInfoWidget(pGuiMonitorElement);
  pMEInfoWidget->showTab(DQMMonitorElementInfoWidget::QUALITY_TEST_RESULTS);
  pLayout->addWidget(pMEInfoWidget);
  pDialog->exec();
  pDialog->deleteLater();
}
void dqm4hep::DQMMonitoringController::openUserGuide () [slot]
Open user guide (pdf) in the default pdf reader.
Definition at line 710 of file DQMMonitoringController.cc.
{
  /* nop */
}
void dqm4hep::DQMMonitoringController::querySubscribedMonitorElements () [slot]
Send a query to the all collectors to send back the subscribed monitor elements.
Definition at line 215 of file DQMMonitoringController.cc.
References log(), and m_clientMap.
Referenced by queryUpdate().
{
  int nCollectorErrors = 0;
  for(DQMGuiMonitorElementClientMap::iterator iter = m_clientMap.begin(), endIter =
      m_clientMap.end() ;
      endIter != iter ; ++iter)
  {
    StatusCode statusCode = iter->second->getMonitorElementClient()->querySubscribedMonitorElements();
    if(STATUS_CODE_SUCCESS != statusCode)
      nCollectorErrors++;
  }
  if(nCollectorErrors != 0)
    this->log(ERROR, "Couldn't send update request to collectors (" + DQM4HEP::typeToString(
      nCollectorErrors) + " errors)");
}
void dqm4hep::DQMMonitoringController::querySubscribedMonitorElements (const std::string & collectorName)
Send a query to the target collector to send back the subscribed monitor elements.
Definition at line 234 of file DQMMonitoringController.cc.
References getClient(), dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient(), and log().
{
  if(collectorName.empty())
    return;
  DQMGuiMonitorElementClient *pGuiClient = this->getClient(collectorName);
  DQMMonitorElementClient *pClient = pGuiClient->getMonitorElementClient();
  if(!pClient->isConnectedToService())
    pClient->connectToService();
  StatusCode statusCode = pClient->querySubscribedMonitorElements();
  if(STATUS_CODE_SUCCESS != statusCode)
    this->log(ERROR, "Couldn't send un-subscription request to collector " + collectorName + " : " +
      statusCodeToString(statusCode));
}
void dqm4hep::DQMMonitoringController::querySubscribedMonitorElements (const std::string & collectorName, const DQMMonitorElementRequest & request)
Send a query to the target collector to subscribe to the element list (if not done yet) and send back the monitor elements in the request.
Definition at line 253 of file DQMMonitoringController.cc.
References getClient(), dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient(), and log().
{
  if(collectorName.empty())
    return;
  DQMGuiMonitorElementClient *pGuiClient = this->getClient(collectorName);
  DQMMonitorElementClient *pClient = pGuiClient->getMonitorElementClient();
  if(!pClient->isConnectedToService())
    pClient->connectToService();
  StatusCode statusCode = pClient->querySubscribedMonitorElements(request);
  if(STATUS_CODE_SUCCESS != statusCode)
    this->log(ERROR, "Couldn't send un-subscription request to collector " + collectorName + " : " +
      statusCodeToString(statusCode));
}
void dqm4hep::DQMMonitoringController::queryUpdate (DQMGuiMonitorElement * pMonitorElement)
Send a query to the collector to first subscribed to the element if not done yet, then to send back the element if collected on the server.
Definition at line 311 of file DQMMonitoringController.cc.
References dqm4hep::DQMGuiMonitorElement::getMonitorElement(), and querySubscribedMonitorElements().
Referenced by dqm4hep::DQMRootWidget::queryUpdate(), and dqm4hep::DQMMonitorElementNavigator::queryUpdate().
{
  std::string fullName = (pMonitorElement->getMonitorElement()->getPath() + pMonitorElement->
      getMonitorElement()->getName()).getPath();
  std::string moduleName = pMonitorElement->getMonitorElement()->getModuleName();
  std::string collectorName = pMonitorElement->getMonitorElement()->getCollectorName();
  DQMMonitorElementRequest request;
  request.push_back(DQMMonitorElementRequest::value_type(moduleName, fullName));
  this->querySubscribedMonitorElements(collectorName, request);
}
void dqm4hep::DQMMonitoringController::queryUpdate (const DQMGuiMonitorElementList & monitorElementList)
Send a query to the collector to first subscribed to the elements if not done yet, then to send back the elements if collected on the server.
Definition at line 325 of file DQMMonitoringController.cc.
References querySubscribedMonitorElements().
{
  DQMMonitorElementRequest request;
  std::map<std::string, DQMMonitorElementRequest> requestMap;
  for(DQMGuiMonitorElementList::const_iterator iter = monitorElementList.begin(), endIter =
      monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    std::string fullName = ((*iter)->getMonitorElement()->getPath() + (*iter)->getMonitorElement()->getName
      ()).getPath();
    std::string moduleName = (*iter)->getMonitorElement()->getModuleName();
    std::string collectorName = (*iter)->getMonitorElement()->getCollectorName();
    requestMap[collectorName].push_back(DQMMonitorElementRequest::value_type(moduleName, fullName));
  }
  for(std::map<std::string, DQMMonitorElementRequest>::iterator iter = requestMap.begin(), endIter =
      requestMap.end() ;
      endIter != iter ; ++iter)
  {
    this->querySubscribedMonitorElements(iter->first, iter->second);
  }
}
void dqm4hep::DQMMonitoringController::quit () [slot]
Exit the monitoring application.
Clear the monitoring and exit the Qt application
Definition at line 1034 of file DQMMonitoringController.cc.
References clearMonitoring().
Referenced by dqm4hep::DQMMonitoringMainWindow::closeEvent().
{
  this->clearMonitoring();
  qApp->closeAllWindows();
  qApp->quit();
}
void dqm4hep::DQMMonitoringController::receiveMonitorElementPublication (const DQMMonitorElementPublication & publication) [private], [slot]
Call back method called by monitor element clients when a publication is received.
Definition at line 349 of file DQMMonitoringController.cc.
References dqm4hep::DQMMonitoring::getModel(), getMonitoring(), and dqm4hep::DQMMonitoringModel::updateMonitorElement().
Referenced by getClient().
{
  std::cout << "Received publication of " << publication.size() << " modules" << std::endl;
  for(DQMMonitorElementPublication::const_iterator iter = publication.begin(), endIter = publication.end()
      ;
      endIter != iter ; ++iter)
  {
    std::string moduleName = iter->first;
    for(int i=0 ; i<iter->second.size() ; i++)
      this->getMonitoring()->getModel()->updateMonitorElement(iter->second.at(i));
  }
}
void dqm4hep::DQMMonitoringController::removeClient (const std::string & collectorName)
Remove a client from the application.
Does nothing if the client is not found
Definition at line 156 of file DQMMonitoringController.cc.
References m_clientMap.
{
  DQMGuiMonitorElementClientMap::iterator findIter = m_clientMap.find(collectorName);
  if(m_clientMap.end() != findIter)
  {
    DQMGuiMonitorElementClient *pClient = findIter->second;
    delete pClient; // delete also calls disconnectFromService()
    m_clientMap.erase(findIter);
  }
}
void dqm4hep::DQMMonitoringController::saveAs () [slot]
Open a file dialog and save the current view and model to the target file.
Definition at line 568 of file DQMMonitoringController.cc.
References getMonitoring().
Referenced by dqm4hep::DQMCanvasView::handleSaveAsActionTriggered(), and dqm4hep::DQMRootWidget::saveAs().
{
    QString fileName = QFileDialog::getSaveFileName(this->getMonitoring()->getView()->getMainWindow(), tr("
      Export file"),
                    QString(""),
                    "XML files (*.xml)");
    if(fileName.isEmpty())
            return;
  this->saveAs(fileName.toStdString());
}
void dqm4hep::DQMMonitoringController::saveAs (const std::string & fileName) const [slot]
Workhorse of the saveAs() method.
Definition at line 582 of file DQMMonitoringController.cc.
References getMonitoring(), dqm4hep::DQMMonitoring::getView(), m_clientMap, and dqm4hep::DQMMonitoringView::toXml().
{
  if(fileName.empty())
    return;
  TiXmlDocument document;
  TiXmlDeclaration *pDeclaration = new TiXmlDeclaration("1.0", "", "");
  document.LinkEndChild(pDeclaration);
  TiXmlElement *pRootElement = new TiXmlElement("dqm4hep");
  document.LinkEndChild(pRootElement);
  TiXmlElement *pMonitoringElement = new TiXmlElement("monitoring");
  pRootElement->LinkEndChild(pMonitoringElement);
  TiXmlElement *pDimDnsNodeElement = new TiXmlElement("dimDnsNode");
  pMonitoringElement->LinkEndChild(pDimDnsNodeElement);
  pDimDnsNodeElement->SetAttribute("value", DimClient::getDnsNode());
  TiXmlElement *pViewElement = this->getMonitoring()->getView()->toXml();
  if(pViewElement)
    pMonitoringElement->LinkEndChild(pViewElement);
  TiXmlElement *pControllerElement = new TiXmlElement("controller");
  for(DQMGuiMonitorElementClientMap::const_iterator iter = m_clientMap.begin(), endIter =
      m_clientMap.end() ;
      endIter != iter ; ++iter)
  {
    const std::string &collectorName = iter->first;
    TiXmlElement *pCollectorElement = new TiXmlElement("collector");
    pControllerElement->LinkEndChild(pCollectorElement);
    pCollectorElement->SetAttribute("value", collectorName);
  }
  pMonitoringElement->LinkEndChild(pControllerElement);
  document.SaveFile(fileName);
}
void dqm4hep::DQMMonitoringController::saveAs (DQMCanvasArea * pCanvasArea) [slot]
Save all the canvases of the canvas area in a file Different file format available.
See implementation.
Definition at line 856 of file DQMMonitoringController.cc.
References dqm4hep::DQMCanvas::getCurrentMonitorElement(), dqm4hep::DQMGuiMonitorElement::getMonitorElement(), getMonitoring(), and dqm4hep::DQMCanvas::getRootWidget().
{
  QList<QMdiSubWindow*> subWindows = pCanvasArea->subWindowList();
  if(subWindows.isEmpty())
    return;
    QStringList formatList;
    QStringList extensionList;
    QString selectedFormat;
    formatList
// << "Postscript (*.ps)"
// << "Encapsulated Postscript (*.eps)"
// << "PDF (*.pdf)"
// << "GIF (*.gif)"
// << "JPG (*.jpg)"
// << "PNG (*.png)"
// << "ROOT Macro (*.C)"
            << "ROOT Files (*.root)";
    extensionList
// << ".ps"
// << ".eps"
// << ".pdf"
// << ".gif"
// << ".jpg"
// << ".png"
// << ".C"
            << ".root";
    QString fileName = QFileDialog::getSaveFileName(this->getMonitoring()->getView()->getMainWindow(),
        "Save as",
            "",
            formatList.join(";;"),
            &selectedFormat);
    if(fileName.isEmpty())
      return;
    int lastIndexOf = fileName.lastIndexOf(extensionList.at(formatList.indexOf(selectedFormat)));
    QString baseFileName;
    QString extensionFileName;
    if(lastIndexOf < 0)
    {
        lastIndexOf = fileName.size() -1;
        baseFileName = fileName;
        int index = formatList.indexOf(selectedFormat);
        extensionFileName = extensionList.at(index);
    }
    else
    {
        baseFileName = fileName.left(lastIndexOf);
        extensionFileName = fileName.right(fileName.size() - lastIndexOf);
    }
    std::string realFileName = (baseFileName + extensionFileName).toStdString();
    TFile *pFile = TFile::Open(realFileName.c_str(), "RECREATE");
    if(NULL == pFile)
      return;
    for(int i=0 ; i<subWindows.count() ; i++)
    {
      DQMCanvas *pCanvas = qobject_cast<DQMCanvas*>(subWindows.at(i));
      if(!pCanvas)
        continue;
      TCanvas *pSaveCanvas = pCanvas->getRootWidget()->GetCanvas();
      std::string objectName = pCanvas->getCurrentMonitorElement()->getMonitorElement()->getName();
      pFile->WriteTObject(pSaveCanvas, objectName.c_str());
    }
    pFile->Close();
    delete pFile;
}
void dqm4hep::DQMMonitoringController::saveAs (DQMCanvas * pCanvas) [slot]
Save the canvas in a file Different file format available.
See implementation.
Definition at line 938 of file DQMMonitoringController.cc.
References getMonitoring(), and dqm4hep::DQMCanvas::getRootWidget().
{
    QStringList formatList;
    QStringList extensionList;
    QString selectedFormat;
    formatList
            << "Postscript (*.ps)"
            << "Encapsulated Postscript (*.eps)"
            << "PDF (*.pdf)"
            << "GIF (*.gif)"
            << "JPG (*.jpg)"
            << "PNG (*.png)"
            << "ROOT Macro (*.C)"
            << "ROOT Files (*.root)";
    extensionList
            << ".ps"
            << ".eps"
            << ".pdf"
            << ".gif"
            << ".jpg"
            << ".png"
            << ".C"
            << ".root";
    QString fileName = QFileDialog::getSaveFileName(this->getMonitoring()->getView()->getMainWindow(),
        "Save as",
            "",
            formatList.join(";;"),
            &selectedFormat);
    std::cout << "selectedFormat : " << selectedFormat.toStdString() << std::endl;
    if(fileName.isEmpty())
      return;
    int lastIndexOf = fileName.lastIndexOf(extensionList.at(formatList.indexOf(selectedFormat)));
    QString baseFileName;
    QString extensionFileName;
    if(lastIndexOf < 0)
    {
        lastIndexOf = fileName.size() -1;
        baseFileName = fileName;
        int index = formatList.indexOf(selectedFormat);
        extensionFileName = extensionList.at(index);
    }
    else
    {
        baseFileName = fileName.left(lastIndexOf);
        extensionFileName = fileName.right(fileName.size() - lastIndexOf);
    }
    std::string realFileName = (baseFileName + extensionFileName).toStdString();
    // save the canvas
    pCanvas->getRootWidget()->GetCanvas()->SaveAs(realFileName.c_str());
}
void dqm4hep::DQMMonitoringController::setUpdateMode (bool updateMode)
Set the update mode of the target collector.
Definition at line 293 of file DQMMonitoringController.cc.
References m_clientMap, and m_updateMode.
Referenced by dqm4hep::DQMMonitoringView::handleAutoUpdateButtonClicked().
{
  for(DQMGuiMonitorElementClientMap::iterator iter = m_clientMap.begin(), endIter =
      m_clientMap.end() ;
      endIter != iter ; ++iter)
    iter->second->getMonitorElementClient()->setUpdateMode(updateMode);
  m_updateMode = updateMode;
}
void dqm4hep::DQMMonitoringController::subscribe (const std::string & collectorName, const DQMMonitorElementRequest & request)
Subscribe to monitor elements of the target collector.
Definition at line 177 of file DQMMonitoringController.cc.
References getClient(), dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient(), and log().
Referenced by dqm4hep::TreeWidgetItem::setData().
{
  if(collectorName.empty() || request.empty())
    return;
  DQMGuiMonitorElementClient *pGuiClient = this->getClient(collectorName);
  DQMMonitorElementClient *pClient = pGuiClient->getMonitorElementClient();
  if(!pClient->isConnectedToService())
    pClient->connectToService();
  StatusCode statusCode = pClient->subscribe(request);
  if(STATUS_CODE_SUCCESS != statusCode)
    this->log(ERROR, "Couldn't send subscription to collector " + collectorName + " : " +
      statusCodeToString(statusCode));
}
void dqm4hep::DQMMonitoringController::unsubscribe (const std::string & collectorName, const DQMMonitorElementRequest & request)
Un-subscribe to monitor elements of the target collector.
Definition at line 196 of file DQMMonitoringController.cc.
References getClient(), dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient(), and log().
Referenced by dqm4hep::TreeWidgetItem::setData().
{
  if(collectorName.empty() || request.empty())
    return;
  DQMGuiMonitorElementClient *pGuiClient = this->getClient(collectorName);
  DQMMonitorElementClient *pClient = pGuiClient->getMonitorElementClient();
  if(!pClient->isConnectedToService())
    pClient->connectToService();
  StatusCode statusCode = pClient->unsubscribe(request);
  if(STATUS_CODE_SUCCESS != statusCode)
    this->log(ERROR, "Couldn't send un-subscription to collector " + collectorName + " : " +
      statusCodeToString(statusCode));
}
void dqm4hep::DQMMonitoringController::unsubscribe (const std::string & collectorName)
Un-subscribe to all monitor elements of the target collector.
Definition at line 272 of file DQMMonitoringController.cc.
References getClient(), dqm4hep::DQMGuiMonitorElementClient::getMonitorElementClient(), and log().
{
  if(collectorName.empty())
    return;
  DQMGuiMonitorElementClient *pGuiClient = this->getClient(collectorName);
  DQMMonitorElementClient *pClient = pGuiClient->getMonitorElementClient();
  if(!pClient->isConnectedToService())
    pClient->connectToService();
  // empty subscription request to clear subscriptions
  DQMMonitorElementRequest request;
  StatusCode statusCode = pClient->replaceSubscription(request);
  if(STATUS_CODE_SUCCESS != statusCode)
    this->log(ERROR, "Couldn't send un-subscription request to collector " + collectorName + " : " +
      statusCodeToString(statusCode));
}
Member Data Documentation
DQMGuiMonitorElementClientMap dqm4hep::DQMMonitoringController::m_clientMap [private]
Definition at line 299 of file DQMMonitoringController.h.
Referenced by clear(), findClient(), getClient(), querySubscribedMonitorElements(), removeClient(), saveAs(), and setUpdateMode().
QMap<LogLevel, QString> dqm4hep::DQMMonitoringController::m_logLevelToTextMap [private]
Definition at line 300 of file DQMMonitoringController.h.
Referenced by DQMMonitoringController(), and log().
DQMMonitoring* dqm4hep::DQMMonitoringController::m_pMonitoring [private]
Definition at line 297 of file DQMMonitoringController.h.
Referenced by DQMMonitoringController(), and getMonitoring().
bool dqm4hep::DQMMonitoringController::m_updateMode [private]
Definition at line 298 of file DQMMonitoringController.h.
Referenced by clear(), getClient(), getUpdateMode(), and setUpdateMode().
The documentation for this class was generated from the following files:
DQMMonitoringController.h
DQMMonitoringController.cc