dqm4hep::DQMModule Class Reference
DQMModule base class.
#include <DQMModule.h>
Public Member Functions
DQMModule ()
Constructor.
virtual ~DQMModule ()
Destructor.
const std::string & getName () const
Get the module name.
const std::string & getDetectorName () const
Get the detector name associated to this module.
const DQMVersion & getVersion () const
Get the module version.
virtual StatusCode initModule ()=0
Initialize the module.
virtual StatusCode readSettings (const TiXmlHandle handle)=0
Read the input settings from a xml handle.
virtual StatusCode startOfCycle ()=0
Called at start of cycle.
virtual StatusCode endOfCycle ()=0
Called at end of cycle before publishing monitor elements.
virtual StatusCode endModule ()=0
End the module.
Protected Member Functions
void setDetectorName (const std::string &detectorName)
Set the detector name for this module.
void setName (const std::string &name)
Set the module name.
void setVersion (unsigned int major, unsigned int minor, unsigned int patch)
Set the module version.
Private Member Functions
DQMModuleApplication * getModuleApplication () const
Get the module application in which the module is registered.
void setModuleApplication (DQMModuleApplication *pModuleApplication)
Set the module application in which the module is registered.
Private Attributes
std::string m_name
The module name.
std::string m_detectorName
The detector name for this module.
DQMVersion m_version
The module version.
DQMModuleApplication * m_pModuleApplication
The monitor element manager.
Friends
class DQMModuleApi
class DQMArchiver
class DQMModuleApplication
Detailed Description
DQMModule base class.
Base class for monitor element booking modules. See daughter classes for specific implementations.
This class owns a monitor element manager used to book monitor elements through the DQMModuleApi.
Author
R.Ete
Definition at line 53 of file DQMModule.h.
Constructor & Destructor Documentation
dqm4hep::DQMModule::DQMModule ()
Constructor.
Definition at line 35 of file DQMModule.cc.
                     :
    m_name(""),
    m_pModuleApplication(NULL)
{
  /* nop */
}
dqm4hep::DQMModule::~DQMModule () [virtual]
Destructor.
Definition at line 44 of file DQMModule.cc.
{
  /* nop */
}
Member Function Documentation
virtual StatusCode dqm4hep::DQMModule::endModule () [pure virtual]
End the module.
Called at termination of the process.
Referenced by dqm4hep::DQMStandaloneModuleApplication::run().
virtual StatusCode dqm4hep::DQMModule::endOfCycle () [pure virtual]
Called at end of cycle before publishing monitor elements.
User should not reset monitor elements in this method. Generally used to set the quality of monitor elements or set some of them to do not be published.
const std::string & dqm4hep::DQMModule::getDetectorName () const
Get the detector name associated to this module.
Definition at line 65 of file DQMModule.cc.
References m_detectorName.
Referenced by dqm4hep::DQMArchiver::archive().
{
  return m_detectorName;
}
DQMModuleApplication * dqm4hep::DQMModule::getModuleApplication () const [private]
Get the module application in which the module is registered.
Definition at line 93 of file DQMModule.cc.
References m_pModuleApplication.
Referenced by dqm4hep::DQMModuleApi::addQualityTest(), dqm4hep::DQMArchiver::archive(), dqm4hep::DQMModuleApi::bookCharHistogram1D(), dqm4hep::DQMModuleApi::bookCharHistogram2D(), dqm4hep::DQMModuleApi::bookFloat(), dqm4hep::DQMModuleApi::bookInt(), dqm4hep::DQMModuleApi::bookIntHistogram1D(), dqm4hep::DQMModuleApi::bookIntHistogram2D(), dqm4hep::DQMModuleApi::bookMonitorElement(), dqm4hep::DQMModuleApi::bookObject(), dqm4hep::DQMModuleApi::bookProfile1D(), dqm4hep::DQMModuleApi::bookProfile2D(), dqm4hep::DQMModuleApi::bookRealHistogram1D(), dqm4hep::DQMModuleApi::bookRealHistogram2D(), dqm4hep::DQMModuleApi::bookShort(), dqm4hep::DQMModuleApi::bookShortHistogram1D(), dqm4hep::DQMModuleApi::bookShortHistogram2D(), dqm4hep::DQMModuleApi::bookString(), dqm4hep::DQMModuleApi::cd(), dqm4hep::DQMModuleApi::createQualityTest(), dqm4hep::DQMModuleApi::deleteMonitorElement(), dqm4hep::DQMModuleApi::getAllMonitorElements(), dqm4hep::DQMModuleApi::getMonitorElement(), dqm4hep::DQMModuleApi::goUp(), dqm4hep::DQMModuleApi::ls(), dqm4hep::DQMModuleApi::mkdir(), dqm4hep::DQMModuleApi::pwd(), dqm4hep::DQMModuleApi::registerQualityTestFactory(), dqm4hep::DQMModuleApi::resetMonitorElements(), dqm4hep::DQMModuleApi::rmdir(), dqm4hep::DQMModuleApi::runQualityTest(), and dqm4hep::DQMModuleApi::runQualityTests().
{
  return m_pModuleApplication;
}
const std::string & dqm4hep::DQMModule::getName () const
Get the module name.
Definition at line 58 of file DQMModule.cc.
References m_name.
Referenced by dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMArchiver::archive(), dqm4hep::DQMModuleApi::bookCharHistogram1D(), dqm4hep::DQMModuleApi::bookCharHistogram2D(), dqm4hep::DQMModuleApi::bookFloat(), dqm4hep::DQMModuleApi::bookInt(), dqm4hep::DQMModuleApi::bookIntHistogram1D(), dqm4hep::DQMModuleApi::bookIntHistogram2D(), dqm4hep::DQMModuleApi::bookMonitorElement(), dqm4hep::DQMModuleApi::bookObject(), dqm4hep::DQMModuleApi::bookProfile1D(), dqm4hep::DQMModuleApi::bookProfile2D(), dqm4hep::DQMModuleApi::bookRealHistogram1D(), dqm4hep::DQMModuleApi::bookRealHistogram2D(), dqm4hep::DQMModuleApi::bookShort(), dqm4hep::DQMModuleApi::bookShortHistogram1D(), dqm4hep::DQMModuleApi::bookShortHistogram2D(), dqm4hep::DQMModuleApi::bookString(), dqm4hep::DQMAnalysisModuleApplication::configureModule(), dqm4hep::DQMModuleApplication::getModuleName(), dqm4hep::DQMStandaloneModuleApplication::readSettings(), dqm4hep::DQMAnalysisModuleApplication::readSettings(), dqm4hep::DQMAnalysisModuleApplication::run(), dqm4hep::DQMMonitorElementSender::sendAvailableMonitorElementList(), and dqm4hep::DQMMonitorElementSender::sendMonitorElements().
{
  return m_name;
}
const DQMVersion & dqm4hep::DQMModule::getVersion () const
Get the module version.
Definition at line 79 of file DQMModule.cc.
References m_version.
Referenced by dqm4hep::DQMArchiver::archive().
{
  return m_version;
}
virtual StatusCode dqm4hep::DQMModule::initModule () [pure virtual]
Initialize the module.
It is generally in this method that monitor elements are booked.
virtual StatusCode dqm4hep::DQMModule::readSettings (const TiXmlHandle handle) [pure virtual]
Read the input settings from a xml handle.
void dqm4hep::DQMModule::setDetectorName (const std::string & detectorName) [protected]
Set the detector name for this module.
Definition at line 72 of file DQMModule.cc.
References m_detectorName.
{
  m_detectorName = detectorName;
}
void dqm4hep::DQMModule::setModuleApplication (DQMModuleApplication * pModuleApplication) [private]
Set the module application in which the module is registered.
Definition at line 100 of file DQMModule.cc.
References m_pModuleApplication.
Referenced by dqm4hep::DQMModuleApplication::setModule().
{
  m_pModuleApplication = pModuleApplication;
}
void dqm4hep::DQMModule::setName (const std::string & name) [protected]
Set the module name.
Definition at line 51 of file DQMModule.cc.
References m_name.
Referenced by dqm4hep::DQMModuleApplication::setModule(), and dqm4hep::DQMModuleApplication::setModuleName().
{
  m_name = name;
}
void dqm4hep::DQMModule::setVersion (unsigned int major, unsigned int minor, unsigned int patch) [protected]
Set the module version.
Definition at line 86 of file DQMModule.cc.
References m_version, and dqm4hep::DQMVersion::set().
{
  m_version.set(major, minor, patch);
}
virtual StatusCode dqm4hep::DQMModule::startOfCycle () [pure virtual]
Called at start of cycle.
User can reset the monitor elements if needed in this method.
Friends And Related Function Documentation
friend class DQMArchiver [friend]
Definition at line 56 of file DQMModule.h.
friend class DQMModuleApi [friend]
Definition at line 55 of file DQMModule.h.
friend class DQMModuleApplication [friend]
Definition at line 57 of file DQMModule.h.
Member Data Documentation
std::string dqm4hep::DQMModule::m_detectorName [private]
The detector name for this module.
Definition at line 133 of file DQMModule.h.
Referenced by getDetectorName(), and setDetectorName().
std::string dqm4hep::DQMModule::m_name [private]
The module name.
Definition at line 132 of file DQMModule.h.
Referenced by getName(), and setName().
DQMModuleApplication* dqm4hep::DQMModule::m_pModuleApplication [private]
The monitor element manager.
Definition at line 135 of file DQMModule.h.
Referenced by getModuleApplication(), and setModuleApplication().
DQMVersion dqm4hep::DQMModule::m_version [private]
The module version.
Definition at line 134 of file DQMModule.h.
Referenced by getVersion(), and setVersion().
The documentation for this class was generated from the following files:
DQMModule.h
DQMModule.cc