dqm4hep::DQMDBFileHandler Class Reference
DQMDBFileHandler class.
#include <DQMDBFileHandler.h>
Public Member Functions
DQMDBFileHandler ()
Constructor.
~DQMDBFileHandler ()
Destructor.
const std::string & type () const
Get the file handler type as string.
StatusCode download (const std::string &pattern)
Download the file locally using the target pattern.
const std::string & getLocalFileName () const
Get the full file name after the download step.
Private Attributes
DQMDBInterface * m_pDBInterface
std::string m_type
std::string m_localFileName
Detailed Description
DQMDBFileHandler class.
Definition at line 41 of file DQMDBFileHandler.h.
Constructor & Destructor Documentation
dqm4hep::DQMDBFileHandler::DQMDBFileHandler ()
Constructor.
Definition at line 38 of file DQMDBFileHandler.cc.
References m_pDBInterface.
                                   :
    m_type("db")
{
  m_pDBInterface = new DQMDBInterface();
}
dqm4hep::DQMDBFileHandler::~DQMDBFileHandler ()
Destructor.
Definition at line 46 of file DQMDBFileHandler.cc.
References m_pDBInterface.
{
  delete m_pDBInterface;
}
Member Function Documentation
StatusCode dqm4hep::DQMDBFileHandler::download (const std::string & pattern) [virtual]
Download the file locally using the target pattern.
Implements dqm4hep::DQMFileHandler .
Definition at line 60 of file DQMDBFileHandler.cc.
References dqm4hep::DQMDBInterface::connect(), dqm4hep::DEBUG, dqm4hep::DQMDBInterface::disconnect(), dqm4hep::ERROR, dqm4hep::DQMDBInterface::isConnected(), m_localFileName, m_pDBInterface, dqm4hep::DQMDBInterface::queryConfigFileContent(), and RETURN_RESULT_IF.
{
  streamlog_out(ERROR) << "DQMDBFileHandler: Performing download step ... " << std::endl;
  m_localFileName = "";
  if(pattern.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  // pattern is :
  // "HOST:hostname:USER:username:PWD=password:FILE=filename"
  size_t hostStart = pattern.find("HOST");
  size_t userStart = pattern.find("USER");
  size_t pwdStart = pattern.find("PWD");
  size_t fileStart = pattern.find("FILE");
  bool invalidPattern = hostStart != 0
  || hostStart == std::string::npos
  || userStart == std::string::npos
  || pwdStart == std::string::npos
  || fileStart == std::string::npos;
  if(!invalidPattern)
  {
    if(hostStart > userStart
    || userStart > pwdStart
    || pwdStart > fileStart)
      invalidPattern = true;
  }
  if(invalidPattern)
  {
    streamlog_out(ERROR) << "DQMDBFileHandler: Invalid pattern => " << pattern << std::endl;
    streamlog_out(ERROR) << "Expected pattern : 'HOST=hostname:USER=username:PWD=password:FILE=filename'" <
      < std::endl;
    return STATUS_CODE_INVALID_PARAMETER;
  }
  const std::string host = pattern.substr(5, userStart-1-5);
  const std::string user = pattern.substr(userStart+5, pwdStart-1-userStart-5);
  const std::string password = pattern.substr(pwdStart+4, fileStart-1-pwdStart-4);
  const std::string fileName = pattern.substr(fileStart+5);
  streamlog_out(DEBUG) << "host : " << host << std::endl;
  streamlog_out(DEBUG) << "user : " << user << std::endl;
  streamlog_out(DEBUG) << "password : " << password << std::endl;
  streamlog_out(DEBUG) << "fileName : " << fileName << std::endl;
  if(m_pDBInterface->isConnected())
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pDBInterface->disconnect());
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pDBInterface->connect(host, user, password, "DQM4HEP"));
  std::string fileContents;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pDBInterface->
      queryConfigFileContent(fileName, fileContents));
  char templateFile[] = "/tmp/dqmdbfilehandler_XXXXXX.xml";
  int ret = mkstemps(templateFile, 4);
  if(ret < 0)
  {
    streamlog_out(ERROR) << "Counldn't create tmp file for db download !" << std::endl;
    return STATUS_CODE_FAILURE;
  }
  m_localFileName = templateFile;
  std::ofstream file;
  file.open(m_localFileName.c_str(), std::ios::out);
  if(!file.is_open())
  {
    streamlog_out(ERROR) << "Counldn't open tmp file for db download !" << std::endl;
    m_localFileName = "";
    return STATUS_CODE_FAILURE;
  }
  file << fileContents;
  file.close();
  return STATUS_CODE_SUCCESS;
}
const std::string & dqm4hep::DQMDBFileHandler::getLocalFileName () const [virtual]
Get the full file name after the download step.
Implements dqm4hep::DQMFileHandler .
Definition at line 146 of file DQMDBFileHandler.cc.
References m_localFileName.
{
  return m_localFileName;
}
const std::string & dqm4hep::DQMDBFileHandler::type () const [virtual]
Get the file handler type as string.
Implements dqm4hep::DQMFileHandler .
Definition at line 53 of file DQMDBFileHandler.cc.
References m_type.
{
  return m_type;
}
Member Data Documentation
std::string dqm4hep::DQMDBFileHandler::m_localFileName [private]
Definition at line 67 of file DQMDBFileHandler.h.
Referenced by download(), and getLocalFileName().
DQMDBInterface* dqm4hep::DQMDBFileHandler::m_pDBInterface [private]
Definition at line 65 of file DQMDBFileHandler.h.
Referenced by download(), DQMDBFileHandler(), and ~DQMDBFileHandler().
std::string dqm4hep::DQMDBFileHandler::m_type [private]
Definition at line 66 of file DQMDBFileHandler.h.
Referenced by type().
The documentation for this class was generated from the following files:
DQMDBFileHandler.h
DQMDBFileHandler.cc