dqm4hep::StatusCodeException Class Reference
StatusCodeException class.
#include <DQM4HEP.h>
Public Member Functions
StatusCodeException (const StatusCode statusCode)
Constructor.
~StatusCodeException () throw ()
Constructor.
StatusCode getStatusCode () const
Get status code.
std::string toString () const
Get status code as a string.
const std::string & getBackTrace () const
Get back trace at point of exception construction (gcc only)
Private Attributes
const StatusCode m_statusCode
The status code.
std::string m_backTrace
The back trace.
Detailed Description
StatusCodeException class.
Definition at line 293 of file DQM4HEP.h.
Constructor & Destructor Documentation
dqm4hep::StatusCodeException::StatusCodeException (const StatusCode statusCode)
Constructor.
Definition at line 34 of file DQM4HEP.cc.
References m_backTrace.
                                                                    :
    m_statusCode(statusCode)
{
#if defined(__GNUC__) && defined(BACKTRACE)
        const size_t maxDepth = 100;
        void *stackAddresses[maxDepth];
        size_t stackDepth = backtrace(stackAddresses, maxDepth);
        char **stackStrings = backtrace_symbols(stackAddresses, stackDepth);
        m_backTrace = "\nBackTrace\n ";
        for (size_t i = 1; i < stackDepth; ++i)
        {
                m_backTrace += stackStrings[i];
                m_backTrace += "\n ";
        }
        free(stackStrings); // malloc()ed by backtrace_symbols
#endif
}
dqm4hep::StatusCodeException::~StatusCodeException () throw)
Constructor.
Definition at line 58 of file DQM4HEP.cc.
{
  /* nop */
}
Member Function Documentation
const std::string & dqm4hep::StatusCodeException::getBackTrace () const
Get back trace at point of exception construction (gcc only)
Definition at line 79 of file DQM4HEP.cc.
References m_backTrace.
{
  return m_backTrace;
}
StatusCode dqm4hep::StatusCodeException::getStatusCode () const
Get status code.
Definition at line 65 of file DQM4HEP.cc.
References m_statusCode.
Referenced by dqm4hep::DQMMonitorElementManager::bookCharHistogram1D(), dqm4hep::DQMMonitorElementManager::bookCharHistogram2D(), dqm4hep::DQMMonitorElementManager::bookFloat(), dqm4hep::DQMMonitorElementManager::bookInt(), dqm4hep::DQMMonitorElementManager::bookIntHistogram1D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram2D(), dqm4hep::DQMMonitorElementManager::bookObject(), dqm4hep::DQMMonitorElementManager::bookProfile1D(), dqm4hep::DQMMonitorElementManager::bookProfile2D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram1D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram2D(), dqm4hep::DQMMonitorElementManager::bookShort(), dqm4hep::DQMMonitorElementManager::bookShortHistogram1D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram2D(), dqm4hep::DQMMonitorElementManager::bookString(), dqm4hep::DQMAnalysisModuleApplication::configureArchiver(), dqm4hep::DQMAnalysisModuleApplication::configureCycle(), dqm4hep::DQMAnalysisModuleApplication::configureModule(), dqm4hep::DQMAnalysisModuleApplication::configureNetwork(), dqm4hep::DQMDBInterface::connect(), dqm4hep::DQMMonitorElementManager::createQualityTest(), dqm4hep::DQMTPCHitStreamer::deserialize(), dqm4hep::DQMClusterStreamer::deserialize(), dqm4hep::DQMParticleIDStreamer::deserialize(), dqm4hep::DQMLCFloatVecStreamer::deserialize(), dqm4hep::DQMLCIntVecStreamer::deserialize(), dqm4hep::DQMLCStrVecStreamer::deserialize(), dqm4hep::DQMDimEventCollector::handleEventReception(), dqm4hep::DQMStandaloneModuleApplication::readSettings(), and dqm4hep::DQMMonitorElementSender::sendAvailableMonitorElementList().
{
  return m_statusCode;
}
std::string dqm4hep::StatusCodeException::toString () const
Get status code as a string.
Definition at line 72 of file DQM4HEP.cc.
References m_statusCode, and dqm4hep::statusCodeToString().
Referenced by dqm4hep::DQMMonitorElementManager::bookCharHistogram1D(), dqm4hep::DQMMonitorElementManager::bookCharHistogram2D(), dqm4hep::DQMMonitorElementManager::bookFloat(), dqm4hep::DQMMonitorElementManager::bookInt(), dqm4hep::DQMMonitorElementManager::bookIntHistogram1D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram2D(), dqm4hep::DQMMonitorElementManager::bookObject(), dqm4hep::DQMMonitorElementManager::bookProfile1D(), dqm4hep::DQMMonitorElementManager::bookProfile2D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram1D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram2D(), dqm4hep::DQMMonitorElementManager::bookShort(), dqm4hep::DQMMonitorElementManager::bookShortHistogram1D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram2D(), dqm4hep::DQMMonitorElementManager::bookString(), dqm4hep::DQMMonitorElementCollector::handleAvailableListUpdate(), dqm4hep::DQMMonitorElementCollector::handleClientRequestList(), dqm4hep::DQMMonitorElementCollector::handleClientSubscription(), dqm4hep::DQMMonitorElementCollector::handleClientUnsubscription(), dqm4hep::DQMRunControlService::handleCurrentRunRpc(), dqm4hep::DQMMonitorElementCollector::handleMeCollectUpdate(), dqm4hep::DQMMonitorElementCollector::handleMeQuery(), dqm4hep::DQMDimRunControlClient::infoHandler(), and dqm4hep::DQMAnalysisModuleApplication::run().
{
  return statusCodeToString(m_statusCode);
}
Member Data Documentation
std::string dqm4hep::StatusCodeException::m_backTrace [private]
The back trace.
Definition at line 320 of file DQM4HEP.h.
Referenced by getBackTrace(), and StatusCodeException().
const StatusCode dqm4hep::StatusCodeException::m_statusCode [private]
The status code.
Definition at line 319 of file DQM4HEP.h.
Referenced by getStatusCode(), and toString().
The documentation for this class was generated from the following files:
DQM4HEP.h
DQM4HEP.cc