dqm4hep::DQMCoreTool Class Reference
DQMCoreTool class.
#include <DQMCoreTool.h>
Static Public Member Functions
static void timeToHMS (time_t t, int &hours, int &minutes, int &seconds)
Convert time_t to hour, minutes and seconds.
static void timeToHMS (time_t t, std::string &timeStr)
Convert time_t to string format as `HOURSh MINUTESm SECONDSs`.
static StringVector getSpecialCharacterList ()
Get the special character list that are to be avoided in some strings.
static bool containsSpecialCharacters (const std::string &str)
Whether the string contains a special character.
Detailed Description
DQMCoreTool class.
Definition at line 40 of file DQMCoreTool.h.
Member Function Documentation
bool dqm4hep::DQMCoreTool::containsSpecialCharacters (const std::string & str) [static]
Whether the string contains a special character.
Definition at line 92 of file DQMCoreTool.cc.
References getSpecialCharacterList().
Referenced by dqm4hep::DQMMonitorElementManager::bookCharHistogram1D(), dqm4hep::DQMMonitorElementManager::bookCharHistogram2D(), dqm4hep::DQMMonitorElementManager::bookFloat(), dqm4hep::DQMMonitorElementManager::bookInt(), dqm4hep::DQMMonitorElementManager::bookIntHistogram1D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram2D(), dqm4hep::DQMMonitorElementManager::bookObject(), dqm4hep::DQMMonitorElementManager::bookProfile1D(), dqm4hep::DQMMonitorElementManager::bookProfile2D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram1D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram2D(), dqm4hep::DQMMonitorElementManager::bookShort(), dqm4hep::DQMMonitorElementManager::bookShortHistogram1D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram2D(), dqm4hep::DQMMonitorElementManager::bookString(), dqm4hep::DQMDirectory::containsDir(), dqm4hep::DQMPath::isValid(), and dqm4hep::DQMDirectory::mkdir().
{
  StringVector specialCharacterList = DQMCoreTool::getSpecialCharacterList();
  for(StringVector::iterator iter = specialCharacterList.begin(), endIter = specialCharacterList.end() ;
      endIter != iter ; ++iter)
  {
    if(str.find(*iter) != std::string::npos)
      return true;
  }
  return false;
}
StringVector dqm4hep::DQMCoreTool::getSpecialCharacterList () [static]
Get the special character list that are to be avoided in some strings.
Definition at line 60 of file DQMCoreTool.cc.
Referenced by containsSpecialCharacters().
{
  StringVector specialCharacterList;
  specialCharacterList.push_back("|");
  specialCharacterList.push_back("&");
  specialCharacterList.push_back(";");
  specialCharacterList.push_back("<");
  specialCharacterList.push_back(">");
  specialCharacterList.push_back("(");
  specialCharacterList.push_back(")");
  specialCharacterList.push_back("$");
  specialCharacterList.push_back("\\");
  specialCharacterList.push_back("\'");
  specialCharacterList.push_back("\"");
  specialCharacterList.push_back("\t");
  specialCharacterList.push_back("\n");
  specialCharacterList.push_back("*");
  specialCharacterList.push_back("?");
  specialCharacterList.push_back(",");
  specialCharacterList.push_back("[");
  specialCharacterList.push_back("]");
  specialCharacterList.push_back("#");
  specialCharacterList.push_back("~");
  specialCharacterList.push_back("=");
  specialCharacterList.push_back("%");
  return specialCharacterList;
}
void dqm4hep::DQMCoreTool::timeToHMS (time_t t, int & hours, int & minutes, int & seconds) [static]
Convert time_t to hour, minutes and seconds.
Definition at line 34 of file DQMCoreTool.cc.
Referenced by timeToHMS().
{
  struct tm *pTmTime = new tm();
  localtime_r(&t, pTmTime);
  hours = pTmTime->tm_hour;
  minutes = pTmTime->tm_min;
  seconds = pTmTime->tm_sec;
  delete pTmTime;
}
void dqm4hep::DQMCoreTool::timeToHMS (time_t t, std::string & timeStr) [static]
Convert time_t to string format as `HOURSh MINUTESm SECONDSs`.
Definition at line 46 of file DQMCoreTool.cc.
References timeToHMS().
{
  // get h m and s
  int hours, minutes, seconds;
  DQMCoreTool::timeToHMS(t, hours, minutes, seconds);
  // convert to str
  std::stringstream ss;
  ss << hours << "h " << minutes << "m " << seconds << "s";
  timeStr = ss.str();
}
The documentation for this class was generated from the following files:
DQMCoreTool.h
DQMCoreTool.cc