TCLAP::UnlabeledMultiArg< T > Class Template Reference
Just like a MultiArg, except that the arguments are unlabeled.
#include <UnlabeledMultiArg.h>
Public Member Functions
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, bool ignoreable=false, Visitor *v=NULL)
Constructor.
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, CmdLineInterface &parser, bool ignoreable=false, Visitor *v=NULL)
Constructor.
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, Constraint< T > *constraint, bool ignoreable=false, Visitor *v=NULL)
Constructor.
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, Constraint< T > *constraint, CmdLineInterface &parser, bool ignoreable=false, Visitor *v=NULL)
Constructor.
virtual bool processArg (int *i, std::vector< std::string > &args)
Handles the processing of the argument.
virtual std::string shortID (const std::string &val=`val`) const
Returns the a short id string.
virtual std::string longID (const std::string &val=`val`) const
Returns the a long id string.
virtual bool operator== (const Arg &a) const
Opertor ==.
virtual void addToList (std::list< Arg * > &argList) const
Pushes this to back of list rather than front.
Additional Inherited Members
Detailed Description
template<class T>class TCLAP::UnlabeledMultiArg< T >
Just like a MultiArg, except that the arguments are unlabeled.
Basically, this Arg will slurp up everything that hasn't been matched to another Arg.
Definition at line 40 of file UnlabeledMultiArg.h.
Constructor & Destructor Documentation
template<class T > TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, const std::string & typeDesc, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
ignoreable - Whether or not this argument can be ignored using the `--` flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 187 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
: MultiArg<T>("", name, desc, req, typeDesc, v)
{
  _ignoreable = ignoreable;
  OptionalUnlabeledTracker::check(true, toString());
}
template<class T > TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, const std::string & typeDesc, CmdLineInterface & parser, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
parser - A CmdLine parser object to add this Arg to
ignoreable - Whether or not this argument can be ignored using the `--` flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 200 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::CmdLineInterface::add(), TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
: MultiArg<T>("", name, desc, req, typeDesc, v)
{
  _ignoreable = ignoreable;
  OptionalUnlabeledTracker::check(true, toString());
  parser.add(this);
}
template<class T > TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, Constraint< T > * constraint, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
ignoreable - Whether or not this argument can be ignored using the `--` flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 216 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
: MultiArg<T>("", name, desc, req, constraint, v)
{
  _ignoreable = ignoreable;
  OptionalUnlabeledTracker::check(true, toString());
}
template<class T > TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, Constraint< T > * constraint, CmdLineInterface & parser, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
parser - A CmdLine parser object to add this Arg to
ignoreable - Whether or not this argument can be ignored using the `--` flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 229 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::CmdLineInterface::add(), TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
: MultiArg<T>("", name, desc, req, constraint, v)
{
  _ignoreable = ignoreable;
  OptionalUnlabeledTracker::check(true, toString());
  parser.add(this);
}
Member Function Documentation
template<class T > void TCLAP::UnlabeledMultiArg< T >::addToList (std::list< Arg * > & argList) const [virtual]
Pushes this to back of list rather than front.
Parameters
argList - The list this should be added to.
Reimplemented from TCLAP::Arg .
Definition at line 294 of file UnlabeledMultiArg.h.
{
  argList.push_back(const_cast<Arg*>(static_cast<const Arg* const>(this)));
}
template<class T > std::string TCLAP::UnlabeledMultiArg< T >::longID (const std::string & val = `val`) const [virtual]
Returns the a long id string.
Used in the usage.
Parameters
val - value to be used.
Reimplemented from TCLAP::MultiArg< T > .
Definition at line 278 of file UnlabeledMultiArg.h.
{
  static_cast<void>(val); // Ignore input, don't warn
  return std::string("<") + _typeDesc + "> (accepted multiple times)";
}
template<class T > bool TCLAP::UnlabeledMultiArg< T >::operator== (const Arg & a) const [virtual]
Opertor ==.
Parameters
a - The Arg to be compared to this.
Reimplemented from TCLAP::Arg .
Definition at line 285 of file UnlabeledMultiArg.h.
References TCLAP::Arg::getDescription(), and TCLAP::Arg::getName().
{
  if (_name == a.getName() || _description == a.getDescription())
    return true;
  else
    return false;
}
template<class T > bool TCLAP::UnlabeledMultiArg< T >::processArg (int * i, std::vector< std::string > & args) [virtual]
Handles the processing of the argument.
This re-implements the Arg version of this method to set the _value of the argument appropriately. It knows the difference between labeled and unlabeled.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings. Passed from main().
Reimplemented from TCLAP::MultiArg< T > .
Definition at line 245 of file UnlabeledMultiArg.h.
{
  if (_hasBlanks(args[*i]))
    return false;
  // never ignore an unlabeled multi arg
  // always take the first value, regardless of the start string
  _extractValue(args[(*i)]);
  /*
  // continue taking args until we hit the end or a start string
  while ((unsigned int)(*i)+1 < args.size() &&
      args[(*i)+1].find_first_of(Arg::flagStartString()) != 0 &&
            args[(*i)+1].find_first_of(Arg::nameStartString()) != 0)
    _extractValue(args[++(*i)]);
  */
  _alreadySet = true;
  return true;
}
template<class T > std::string TCLAP::UnlabeledMultiArg< T >::shortID (const std::string & val = `val`) const [virtual]
Returns the a short id string.
Used in the usage.
Parameters
val - value to be used.
Reimplemented from TCLAP::MultiArg< T > .
Definition at line 271 of file UnlabeledMultiArg.h.
{
  static_cast<void>(val); // Ignore input, don't warn
  return std::string("<") + _typeDesc + "> ...";
}
The documentation for this class was generated from the following file:
UnlabeledMultiArg.h