dqm4hep::DQMDimEventClient Class Reference
DQMDimEventClient class.
#include <DQMDimEventClient.h>
Public Member Functions
DQMDimEventClient ()
Constructor.
~DQMDimEventClient ()
Destructor.
StatusCode performServiceConnection ()
Workhorse of the service connection.
StatusCode performServiceDisconnection ()
Workhorse of the service connection.
bool isConnectedToService () const
Whether the client is connected to the collector (server)
StatusCode sendEvent (const DQMEvent *pEvent)
Send an event to the collector (server).
StatusCode queryEvent (DQMEvent *&pEvent, int timeout)
Query an event to the collector (server) with a timeout and handle it without pushing it into the internal queue.
StatusCode queryEvent ()
Query an event to the collector.
void setUpdateMode (bool updateMode)
Set the update mode.
bool getUpdateMode () const
Whether the update mode is set.
Private Member Functions
void infoHandler ()
Dim info handler.
StatusCode eventReception (dqm_char *pBuffer, dqm_uint bufferSize)
Handle the event reception as a buffer an its buffer size.
void setSubEventIdentifier (const std::string &identifier)
Set the sub event identifier.
StatusCode readSettings (const TiXmlHandle &xmlHandle)
Read settings from the xml handle.
Private Attributes
bool m_isConnected
DimEventRpcInfo * m_pDimEventRpcInfo
DimUpdatedInfo * m_pClientIdInfo
to receive the client id stored on server
DimUpdatedInfo * m_pServerStateInfo
Server state. 0 for stopped : 1 for running.
DimUpdatedInfo * m_pEventUpdateInfo
For event reception.
int m_serverClientId
bool m_updateMode
DQMDataStream m_dataStream
pthread_mutex_t m_mutex
Friends
class DimEventRpcInfo
Additional Inherited Members
Detailed Description
DQMDimEventClient class.
Definition at line 69 of file DQMDimEventClient.h.
Constructor & Destructor Documentation
dqm4hep::DQMDimEventClient::DQMDimEventClient ()
Constructor.
Definition at line 59 of file DQMDimEventClient.cc.
                                     :
  m_isConnected(false),
  m_pDimEventRpcInfo(NULL),
  m_updateMode(false),
  m_serverClientId(0),
  m_dataStream(5*1024*1024) // 5 Mo should be enough to start ...
{
  pthread_mutex_init(&m_mutex, NULL);
}
dqm4hep::DQMDimEventClient::~DQMDimEventClient ()
Destructor.
Definition at line 71 of file DQMDimEventClient.cc.
References dqm4hep::DQMEventClient::disconnectFromService(), isConnectedToService(), and m_mutex.
{
  if(this->isConnectedToService())
    this->disconnectFromService();
  pthread_mutex_destroy(&m_mutex);
}
Member Function Documentation
StatusCode dqm4hep::DQMDimEventClient::eventReception (dqm_char * pBuffer, dqm_uint bufferSize) [private]
Handle the event reception as a buffer an its buffer size.
Definition at line 338 of file DQMDimEventClient.cc.
References dqm4hep::DQMEventClient::getEventStreamer(), m_dataStream, m_mutex, dqm4hep::DQMEventClient::pushEvent(), RETURN_RESULT_IF, and dqm4hep::DQMDataStream::setBuffer().
Referenced by infoHandler(), and dqm4hep::DimEventRpcInfo::rpcInfoHandler().
{
  if(NULL == pBuffer || 0 == bufferSize)
    return STATUS_CODE_INVALID_PARAMETER;
  // set buffer
  scoped_lock(& this->m_mutex);
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
  // read event
  DQMEvent *pEvent = NULL;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getEventStreamer()->deserialize(pEvent, &
      m_dataStream));
  // add it to event queue
  this->pushEvent(pEvent);
  return STATUS_CODE_SUCCESS;
}
bool dqm4hep::DQMDimEventClient::getUpdateMode () const [virtual]
Whether the update mode is set.
Implements dqm4hep::DQMEventClient .
Definition at line 255 of file DQMDimEventClient.cc.
References m_updateMode.
Referenced by readSettings().
{
  return m_updateMode;
}
void dqm4hep::DQMDimEventClient::infoHandler () [private]
Dim info handler.
Definition at line 262 of file DQMDimEventClient.cc.
References eventReception(), dqm4hep::DQMEventClient::getCollectorName(), dqm4hep::DQMEventClient::getSubEventIdentifier(), m_pClientIdInfo, m_pEventUpdateInfo, m_pServerStateInfo, m_serverClientId, m_updateMode, and dqm4hep::MESSAGE.
{
  DimInfo *pInfo = getInfo();
  if(!pInfo)
    return;
  // client has just been registered
  if(pInfo == m_pClientIdInfo)
  {
    int clientId = pInfo->getInt();
    streamlog_out(MESSAGE) << "Client id on server : " << clientId << std::endl;
    if(clientId <= 0)
      return;
    m_serverClientId = clientId;
    std::string subEventIdentifierCommandName = "DQM4HEP/EventCollector/" + this->
      getCollectorName() + "/SUB_EVENT_IDENTIFIER";
    std::string updateModeCommandName = "DQM4HEP/EventCollector/" + this->
      getCollectorName() + "/UPDATE_MODE";
    // send to server the client parameters
    DimClient::sendCommandNB((char*) updateModeCommandName.c_str(), static_cast<int>(
      m_updateMode));
    DimClient::sendCommandNB((char*) subEventIdentifierCommandName.c_str(), (char *) this->
      getSubEventIdentifier().c_str());
    return;
  }
  if(pInfo == m_pServerStateInfo)
  {
    int serverRunning = pInfo->getInt();
    // server is running
    if(serverRunning > 0)
    {
      // client is already registered, so nothing to do ...
      if(m_serverClientId > 0)
        return;
      // client is not registered yet, we need to do it !
      else
      {
        streamlog_out(MESSAGE) << "Registering client into event collector server application !" <<
      std::endl;
        DimClient::sendCommandNB(("DQM4HEP/EventCollector/" + this->
      getCollectorName() + "/CLIENT_REGISTRATION").c_str(), 1);
        return;
      }
    }
    // server is shutting down.
    // client is no longer connected and client id is no longer valid.
    else if(m_serverClientId > 0)
    {
      m_serverClientId = 0;
      streamlog_out(MESSAGE) << "Unregistered from event collector server application !" << std::endl;
      return;
    }
  }
  if(pInfo == m_pEventUpdateInfo)
  {
    if(m_serverClientId == 0)
      return;
    char *pBuffer = (char*) pInfo->getData();
    unsigned int bufferSize = pInfo->getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      return;
    this->eventReception(pBuffer, bufferSize);
    return;
  }
}
bool dqm4hep::DQMDimEventClient::isConnectedToService () const [virtual]
Whether the client is connected to the collector (server)
Implements dqm4hep::DQMEventClient .
Definition at line 138 of file DQMDimEventClient.cc.
References m_isConnected.
Referenced by performServiceConnection(), performServiceDisconnection(), queryEvent(), readSettings(), setSubEventIdentifier(), setUpdateMode(), and ~DQMDimEventClient().
{
  return m_isConnected;
}
StatusCode dqm4hep::DQMDimEventClient::performServiceConnection () [virtual]
Workhorse of the service connection.
Implements dqm4hep::DQMEventClient .
Definition at line 81 of file DQMDimEventClient.cc.
References DimEventRpcInfo, dqm4hep::DQMEventClient::getCollectorName(), isConnectedToService(), m_isConnected, m_pClientIdInfo, m_pDimEventRpcInfo, m_pEventUpdateInfo, m_pServerStateInfo, dqm4hep::MESSAGE, and dqm4hep::WARNING.
{
  if(isConnectedToService())
    return STATUS_CODE_SUCCESS;
  DimClient::setExitHandler(("DQM4HEP/EventCollector/" + this->getCollectorName()).c_str());
  m_pDimEventRpcInfo = new DimEventRpcInfo(this);
  m_pClientIdInfo = new DimUpdatedInfo(("DQM4HEP/EventCollector/" + this->
      getCollectorName() + "/CLIENT_REGISTERED").c_str(), static_cast<int>(0), this);
  m_pServerStateInfo = new DimUpdatedInfo(("DQM4HEP/EventCollector/" + this->
      getCollectorName() + "/SERVER_STATE").c_str(), static_cast<int>(0), this);
  m_pEventUpdateInfo = new DimUpdatedInfo(("DQM4HEP/EventCollector/" + this->
      getCollectorName() + "/EVENT_RAW_UPDATE").c_str(), (void*) NULL, 0, this);
  m_isConnected = true;
  DimCurrentInfo serverStateInfo(("DQM4HEP/EventCollector/" + this->
      getCollectorName() + "/SERVER_STATE").c_str(), static_cast<int>(0));
  int serverRunning = serverStateInfo.getInt();
  if(!serverRunning)
  {
    streamlog_out(WARNING) << "Server collector application not running yet" << std::endl;
    return STATUS_CODE_SUCCESS;
  }
  // send command to register the client on the server
  // the server is expected to update m_pClientIdInfo info with the client id
  streamlog_out(MESSAGE) << "Registering client into server collector application !" << std::endl;
  DimClient::sendCommandNB(("DQM4HEP/EventCollector/" + this->getCollectorName() + "/CLIENT_REGISTRATION").
      c_str(), 1);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDimEventClient::performServiceDisconnection () [virtual]
Workhorse of the service connection.
Implements dqm4hep::DQMEventClient .
Definition at line 115 of file DQMDimEventClient.cc.
References dqm4hep::DQMEventClient::getCollectorName(), isConnectedToService(), m_isConnected, m_pClientIdInfo, m_pDimEventRpcInfo, m_pEventUpdateInfo, m_pServerStateInfo, and m_serverClientId.
{
  if(!isConnectedToService())
    return STATUS_CODE_SUCCESS;
  delete m_pDimEventRpcInfo;
  delete m_pClientIdInfo;
  delete m_pServerStateInfo;
  delete m_pEventUpdateInfo;
  m_isConnected = false;
  // un-register client on the server
  if(m_serverClientId > 0)
  {
    DimClient::sendCommandNB(("DQM4HEP/EventCollector/" + this->getCollectorName() + "/CLIENT_REGISTRATION"
      ).c_str(), 0);
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDimEventClient::queryEvent (DQMEvent *& pEvent, int timeout) [virtual]
Query an event to the collector (server) with a timeout and handle it without pushing it into the internal queue.
Implements dqm4hep::DQMEventClient .
Definition at line 185 of file DQMDimEventClient.cc.
References dqm4hep::DQMEventStreamer::deserialize(), dqm4hep::DQMEventClient::getCollectorName(), dqm4hep::DQMEventClient::getEventStreamer(), dqm4hep::DQMEventClient::getSubEventIdentifier(), isConnectedToService(), m_dataStream, m_mutex, and dqm4hep::DQMDataStream::setBuffer().
{
  scoped_lock(& this->m_mutex);
  if(! this->isConnectedToService())
    return STATUS_CODE_NOT_INITIALIZED;
  if(NULL == this->getEventStreamer())
    return STATUS_CODE_NOT_INITIALIZED;
  // check for valid parameters
  if(timeout <= 0)
    return STATUS_CODE_INVALID_PARAMETER;
  // rpc service name
  std::string serviceName = "DQM4HEP/EventCollector/" + this->getCollectorName() + "/EVENT_RAW_REQUEST";
  pEvent = NULL;
  // declare the rpc service info
  DimRpcInfo eventDimRpcInfo((char*) serviceName.c_str(), timeout, (void*) NULL, 0);
  // send the query
  eventDimRpcInfo.setData((char*) this->getSubEventIdentifier().c_str());
  // receive the query result
  char *pEventRawBuffer = static_cast<char*>(eventDimRpcInfo.getData());
  int bufferSize = eventDimRpcInfo.getSize();
  // check for message validity
  if(NULL == pEventRawBuffer || 0 == bufferSize)
    return STATUS_CODE_FAILURE;
  // deserialize the event raw buffer
  m_dataStream.setBuffer(pEventRawBuffer, bufferSize);
  return this->getEventStreamer()->deserialize(pEvent, &m_dataStream);
}
StatusCode dqm4hep::DQMDimEventClient::queryEvent () [virtual]
Query an event to the collector.
A command is send to the collector in order to send back an event. This method does not wait for the event reception.
To query a single event that is directly handled by the caller, use queryEvent(evt, timeout).
The received event is pushed in an internal event queue.
Implements dqm4hep::DQMEventClient .
Definition at line 224 of file DQMDimEventClient.cc.
References dqm4hep::DQMEventClient::getEventStreamer(), dqm4hep::DQMEventClient::getSubEventIdentifier(), isConnectedToService(), m_mutex, and m_pDimEventRpcInfo.
{
  scoped_lock(& this->m_mutex);
  if(! this->isConnectedToService())
    return STATUS_CODE_NOT_INITIALIZED;
  if(NULL == this->getEventStreamer())
    return STATUS_CODE_NOT_INITIALIZED;
  // send the query
  m_pDimEventRpcInfo->setData((char*) this->getSubEventIdentifier().c_str());
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDimEventClient::readSettings (const TiXmlHandle & xmlHandle) [private], [virtual]
Read settings from the xml handle.
Implements dqm4hep::DQMEventClient .
Definition at line 359 of file DQMDimEventClient.cc.
References dqm4hep::DQMEventClient::connectToService(), dqm4hep::DQMPluginManager::createPluginClass(), dqm4hep::DQMEventClient::disconnectFromService(), dqm4hep::DQMEventClient::getCollectorName(), dqm4hep::DQMEventClient::getMaximumQueueSize(), dqm4hep::DQMEventClient::getSubEventIdentifier(), getUpdateMode(), dqm4hep::DQMSingleton< DQMPluginManager >::instance(), isConnectedToService(), dqm4hep::DQMXmlHelper::readParameterValue(), RETURN_RESULT_IF, RETURN_RESULT_IF_AND_IF, dqm4hep::DQMEventClient::setCollectorName(), dqm4hep::DQMEventClient::setEventStreamer(), dqm4hep::DQMEventClient::setMaximumQueueSize(), setSubEventIdentifier(), and setUpdateMode().
{
  bool reconnect = this->isConnectedToService();
  // first disconnect
  if(reconnect)
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->disconnectFromService());
  // read all xml values first
  std::string collectorName = this->getCollectorName();
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::readParameterValue(xmlHandle,
      "collectorName", collectorName));
  std::string subEventIdentifier = this->getSubEventIdentifier();
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::readParameterValue(xmlHandle,
      "subEventIdentifier", subEventIdentifier));
  unsigned int maxEventQueueSize = this->getMaximumQueueSize();
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::readParameterValue(xmlHandle,
      "maxQueueSize", maxEventQueueSize));
  bool updateMode = this->getUpdateMode();
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::readParameterValue(xmlHandle,
      "updateMode", updateMode));
  std::string eventStreamerName;
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::readParameterValue(xmlHandle,
      "streamerName", eventStreamerName));
  // configure the client
  // connection to service will come afterward
  this->setCollectorName(collectorName);
  this->setSubEventIdentifier(subEventIdentifier);
  this->setMaximumQueueSize(maxEventQueueSize);
  this->setUpdateMode(updateMode);
  if(! eventStreamerName.empty())
  {
    DQMEventStreamer *pEventStreamer = DQMPluginManager::instance()->
      createPluginClass<DQMEventStreamer>(eventStreamerName);
    if(! pEventStreamer)
      return STATUS_CODE_FAILURE;
    this->setEventStreamer(pEventStreamer, true);
  }
  // reconnect only if connected before configuration
  if(reconnect)
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->connectToService());
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDimEventClient::sendEvent (const DQMEvent * pEvent) [virtual]
Send an event to the collector (server).
Possible only if a connection has been created (connectToService()) and an event streamer set.
Implements dqm4hep::DQMEventClient .
Definition at line 145 of file DQMDimEventClient.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), dqm4hep::DQMEventClient::getCollectorName(), dqm4hep::DQMEventClient::getEventStreamer(), m_dataStream, m_mutex, dqm4hep::DQMDataStream::reset(), and RETURN_RESULT_IF.
{
  scoped_lock(& this->m_mutex);
  if(NULL == this->getEventStreamer())
    return STATUS_CODE_NOT_INITIALIZED;
  if(NULL == pEvent)
    return STATUS_CODE_INVALID_PARAMETER;
  m_dataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getEventStreamer()->serialize(pEvent, &
      m_dataStream));
  char *pBuffer = m_dataStream.getBuffer();
  unsigned int bufferSize = m_dataStream.getBufferSize();
  if(NULL == pBuffer || 0 == bufferSize)
    return STATUS_CODE_FAILURE;
  std::string commandName = "DQM4HEP/EventCollector/" + this->getCollectorName() + "/COLLECT_RAW_EVENT";
  DimClient::sendCommandNB((char*) commandName.c_str(), (void *) pBuffer, bufferSize);
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMDimEventClient::setSubEventIdentifier (const std::string & identifier) [private], [virtual]
Set the sub event identifier.
This string is sent while querying events. The received event will be a sub event matching this identifier
The event sub identifier is sent the the collector is the client is connected to the service
Reimplemented from dqm4hep::DQMEventClient .
Definition at line 172 of file DQMDimEventClient.cc.
References dqm4hep::DQMEventClient::getCollectorName(), isConnectedToService(), and dqm4hep::DQMEventClient::setSubEventIdentifier().
Referenced by readSettings().
{
  DQMEventClient::setSubEventIdentifier(identifier);
  if(! this->isConnectedToService())
    return;
  std::string subEventIdentifierCommandName = "DQM4HEP/EventCollector/" + this->
      getCollectorName() + "/SUB_EVENT_IDENTIFIER";
  DimClient::sendCommandNB((char*) subEventIdentifierCommandName.c_str(), (char *) identifier.c_str());
}
void dqm4hep::DQMDimEventClient::setUpdateMode (bool updateMode) [virtual]
Set the update mode.
If the update mode is set to true, a command is sent to the server in order to update the client as soon as an event is received in the collector server.
Implements dqm4hep::DQMEventClient .
Definition at line 242 of file DQMDimEventClient.cc.
References dqm4hep::DQMEventClient::getCollectorName(), isConnectedToService(), and m_updateMode.
Referenced by readSettings().
{
  m_updateMode = updateMode;
  if(! this->isConnectedToService())
    return;
  // send command to server
  DimClient::sendCommandNB((char*) (std::string("DQM4HEP/EventCollector/") + this->
      getCollectorName() + "/UPDATE_MODE").c_str(), static_cast<int>(m_updateMode));
}
Friends And Related Function Documentation
friend class DimEventRpcInfo [friend]
Definition at line 71 of file DQMDimEventClient.h.
Referenced by performServiceConnection().
Member Data Documentation
DQMDataStream dqm4hep::DQMDimEventClient::m_dataStream [private]
Definition at line 160 of file DQMDimEventClient.h.
Referenced by eventReception(), queryEvent(), and sendEvent().
bool dqm4hep::DQMDimEventClient::m_isConnected [private]
Definition at line 151 of file DQMDimEventClient.h.
Referenced by isConnectedToService(), performServiceConnection(), and performServiceDisconnection().
pthread_mutex_t dqm4hep::DQMDimEventClient::m_mutex [mutable], [private]
Definition at line 161 of file DQMDimEventClient.h.
Referenced by eventReception(), queryEvent(), sendEvent(), and ~DQMDimEventClient().
DimUpdatedInfo* dqm4hep::DQMDimEventClient::m_pClientIdInfo [private]
to receive the client id stored on server
Definition at line 153 of file DQMDimEventClient.h.
Referenced by infoHandler(), performServiceConnection(), and performServiceDisconnection().
DimEventRpcInfo* dqm4hep::DQMDimEventClient::m_pDimEventRpcInfo [private]
Definition at line 152 of file DQMDimEventClient.h.
Referenced by performServiceConnection(), performServiceDisconnection(), and queryEvent().
DimUpdatedInfo* dqm4hep::DQMDimEventClient::m_pEventUpdateInfo [private]
For event reception.
Definition at line 155 of file DQMDimEventClient.h.
Referenced by infoHandler(), performServiceConnection(), and performServiceDisconnection().
DimUpdatedInfo* dqm4hep::DQMDimEventClient::m_pServerStateInfo [private]
Server state. 0 for stopped : 1 for running.
Definition at line 154 of file DQMDimEventClient.h.
Referenced by infoHandler(), performServiceConnection(), and performServiceDisconnection().
int dqm4hep::DQMDimEventClient::m_serverClientId [private]
Definition at line 157 of file DQMDimEventClient.h.
Referenced by infoHandler(), and performServiceDisconnection().
bool dqm4hep::DQMDimEventClient::m_updateMode [private]
Definition at line 158 of file DQMDimEventClient.h.
Referenced by getUpdateMode(), infoHandler(), and setUpdateMode().
The documentation for this class was generated from the following files:
DQMDimEventClient.h
DQMDimEventClient.cc