dqm4hep::DQMLCCollectionStreamer Class Reference
DQMLCCollectionStreamer class.
#include <DQMLCEventStreamer.h>
Public Member Functions
DQMLCCollectionStreamer (const std::string &collectionType, DQMLCObjectStreamer *pLCObjectStreamer)
Constructor with a lc object streamer.
~DQMLCCollectionStreamer ()
Destructor.
StatusCode serialize (const EVENT::LCCollection *const pLCCollection, DQMDataStream *const pDataStream)
Serialize an LCCollection.
StatusCode deserialize (EVENT::LCCollection *&pLCCollection, DQMDataStream *const pDataStream)
Deserialize an LCCollection.
Protected Attributes
const std::string m_collectionType
DQMLCObjectStreamer * m_pLCObjectStreamer
DQMLCParametersStreamer m_lcParametersStreamer
Detailed Description
DQMLCCollectionStreamer class.
Definition at line 110 of file DQMLCEventStreamer.h.
Constructor & Destructor Documentation
dqm4hep::DQMLCCollectionStreamer::DQMLCCollectionStreamer (const std::string & collectionType, DQMLCObjectStreamer * pLCObjectStreamer)
Constructor with a lc object streamer.
Definition at line 490 of file DQMLCEventStreamer.cc.
                                                                                                           
                   :
    m_collectionType(collectionType),
    m_pLCObjectStreamer(pLCObjectStreamer)
{
  /* nop */
}
dqm4hep::DQMLCCollectionStreamer::~DQMLCCollectionStreamer ()
Destructor.
Definition at line 499 of file DQMLCEventStreamer.cc.
References m_pLCObjectStreamer.
{
  delete m_pLCObjectStreamer;
}
Member Function Documentation
StatusCode dqm4hep::DQMLCCollectionStreamer::deserialize (EVENT::LCCollection *& pLCCollection, DQMDataStream *const pDataStream) [virtual]
Deserialize an LCCollection.
The collection must be allocated in this function
Implements dqm4hep::DQMStreamer< EVENT::LCCollection > .
Definition at line 539 of file DQMLCEventStreamer.cc.
References dqm4hep::DQMStreamer< T >::deserialize(), dqm4hep::DQMLCParametersStreamer::deserialize(), m_collectionType, m_lcParametersStreamer, m_pLCObjectStreamer, PROCESS_CODE_IF_AND_RETURN, dqm4hep::DQMDataStream::read(), and RETURN_RESULT_IF.
{
  pLCCollection = NULL;
  IMPL::LCCollectionVec *pTmpLCCollection = new IMPL::LCCollectionVec(
      m_collectionType);
  dqm_int flag = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(flag));
  pTmpLCCollection->setFlag(flag);
  dqm_bool isTransient = false;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(isTransient));
  pTmpLCCollection->setTransient(isTransient);
  dqm_bool isDefault = false;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(isDefault));
  pTmpLCCollection->setDefault(isDefault);
  dqm_bool isSubset = false;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(isSubset));
  pTmpLCCollection->setSubset(isSubset);
  EVENT::LCParameters *pLCParameters = &pTmpLCCollection->parameters();
  PROCESS_CODE_IF_AND_RETURN(STATUS_CODE_SUCCESS, !=, m_lcParametersStreamer.
      deserialize(pLCParameters, pDataStream),
    delete pTmpLCCollection;
  );
  dqm_int nElements = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nElements));
  for(int i=0 ; i<nElements ; i++)
  {
    EVENT::LCObject *pLCObject = NULL;
    PROCESS_CODE_IF_AND_RETURN(STATUS_CODE_SUCCESS, !=, m_pLCObjectStreamer->
      deserialize(pLCObject, pDataStream),
      delete pTmpLCCollection;
    );
    pTmpLCCollection->addElement(pLCObject);
  }
  pLCCollection = pTmpLCCollection;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMLCCollectionStreamer::serialize (const EVENT::LCCollection *const pLCCollection, DQMDataStream *const pDataStream) [virtual]
Serialize an LCCollection.
Implements dqm4hep::DQMStreamer< EVENT::LCCollection > .
Definition at line 506 of file DQMLCEventStreamer.cc.
References m_collectionType, m_lcParametersStreamer, m_pLCObjectStreamer, RETURN_RESULT_IF, dqm4hep::DQMStreamer< T >::serialize(), dqm4hep::DQMLCParametersStreamer::serialize(), and dqm4hep::DQMDataStream::write().
{
  if(pLCCollection->getTypeName() != m_collectionType)
    return STATUS_CODE_INVALID_PARAMETER;
  dqm_int flag = pLCCollection->getFlag();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(flag));
  dqm_bool isTransient = pLCCollection->isTransient();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(isTransient));
  dqm_bool isDefault = pLCCollection->isDefault();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(isDefault));
  dqm_bool isSubset = pLCCollection->isSubset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(isSubset));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_lcParametersStreamer.serialize(&pLCCollection->getParameters(
      ), pDataStream));
  dqm_int nElements = pLCCollection->getNumberOfElements();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nElements));
  for(int i=0 ; i<pLCCollection->getNumberOfElements() ; i++)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pLCObjectStreamer->serialize(pLCCollection->getElementAt(i)
      , pDataStream));
  }
  return STATUS_CODE_SUCCESS;
}
Member Data Documentation
const std::string dqm4hep::DQMLCCollectionStreamer::m_collectionType [protected]
Definition at line 131 of file DQMLCEventStreamer.h.
Referenced by deserialize(), and serialize().
DQMLCParametersStreamer dqm4hep::DQMLCCollectionStreamer::m_lcParametersStreamer [protected]
Definition at line 133 of file DQMLCEventStreamer.h.
Referenced by deserialize(), and serialize().
DQMLCObjectStreamer* dqm4hep::DQMLCCollectionStreamer::m_pLCObjectStreamer [protected]
Definition at line 132 of file DQMLCEventStreamer.h.
Referenced by deserialize(), serialize(), and ~DQMLCCollectionStreamer().
The documentation for this class was generated from the following files:
DQMLCEventStreamer.h
DQMLCEventStreamer.cc