dqm4hep::DQMMonitorElementCollectorApplication Class Reference
DQMMonitorElementCollectorApplication class.
#include <DQMMonitorElementCollectorApplication.h>
Public Member Functions
DQMMonitorElementCollectorApplication ()
Constructor with collector name.
~DQMMonitorElementCollectorApplication ()
Destructor.
StatusCode run ()
Run the application.
StatusCode exit (int returnCode)
Stop the application.
const std::string & getName () const
Get the application name.
const std::string & getType () const
Get the application type.
StatusCode setCollectorName (const std::string &collectorName)
Set the monitor element collector name.
Protected Member Functions
StatusCode readSettings (const std::string &settingsFile=``)
No settings to read.
Protected Attributes
bool m_shouldExit
std::string m_type
DQMState m_applicationState
DQMMonitorElementCollector * m_pMonitorElementCollector
Detailed Description
DQMMonitorElementCollectorApplication class.
Definition at line 41 of file DQMMonitorElementCollectorApplication.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElementCollectorApplication::DQMMonitorElementCollectorApplication ()
Constructor with collector name.
Definition at line 38 of file DQMMonitorElementCollectorApplication.cc.
References m_pMonitorElementCollector.
                                                                             :
    m_applicationState(STOPPED_STATE),
    m_shouldExit(false),
    m_type("MonitorElementCollector")
{
  m_pMonitorElementCollector = new DQMMonitorElementCollector();
}
dqm4hep::DQMMonitorElementCollectorApplication::~DQMMonitorElementCollectorApplication ()
Destructor.
Definition at line 48 of file DQMMonitorElementCollectorApplication.cc.
References dqm4hep::DQMMonitorElementCollector::isRunning(), m_pMonitorElementCollector, and dqm4hep::DQMMonitorElementCollector::stop().
{
  if(m_pMonitorElementCollector->isRunning())
    m_pMonitorElementCollector->stop();
  delete m_pMonitorElementCollector;
}
Member Function Documentation
StatusCode dqm4hep::DQMMonitorElementCollectorApplication::exit (int returnCode) [virtual]
Stop the application.
Implements dqm4hep::DQMApplication .
Definition at line 83 of file DQMMonitorElementCollectorApplication.cc.
References m_applicationState, m_pMonitorElementCollector, m_shouldExit, dqm4hep::NUMBER_OF_STATUS_CODES, RETURN_RESULT_IF, and dqm4hep::DQMMonitorElementCollector::stop().
{
  if(m_applicationState == STOPPED_STATE)
    return STATUS_CODE_FAILURE;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementCollector->stop());
  m_shouldExit = true;
  m_applicationState = STOPPED_STATE;
  StatusCode returnStatusCode;
  if(returnCode >= 0 && returnCode < NUMBER_OF_STATUS_CODES)
    returnStatusCode = static_cast<StatusCode>(returnCode);
  else
    returnStatusCode = STATUS_CODE_FAILURE;
  return returnStatusCode;
}
const std::string & dqm4hep::DQMMonitorElementCollectorApplication::getName () const [virtual]
Get the application name.
Implements dqm4hep::DQMApplication .
Definition at line 105 of file DQMMonitorElementCollectorApplication.cc.
References dqm4hep::DQMMonitorElementCollector::getCollectorName(), and m_pMonitorElementCollector.
Referenced by run().
{
  return m_pMonitorElementCollector->getCollectorName();
}
const std::string & dqm4hep::DQMMonitorElementCollectorApplication::getType () const [virtual]
Get the application type.
Implements dqm4hep::DQMApplication .
Definition at line 112 of file DQMMonitorElementCollectorApplication.cc.
References m_type.
Referenced by run().
{
  return m_type;
}
StatusCode dqm4hep::DQMMonitorElementCollectorApplication::readSettings (const std::string & settingsFile = ``) [inline], [protected], [virtual]
No settings to read.
Implements dqm4hep::DQMApplication .
Definition at line 75 of file DQMMonitorElementCollectorApplication.h.
{ return STATUS_CODE_SUCCESS; }
StatusCode dqm4hep::DQMMonitorElementCollectorApplication::run () [virtual]
Run the application.
Implements dqm4hep::DQMApplication .
Definition at line 58 of file DQMMonitorElementCollectorApplication.cc.
References getName(), getType(), m_applicationState, m_pMonitorElementCollector, m_shouldExit, RETURN_RESULT_IF, and dqm4hep::DQMMonitorElementCollector::start().
{
  if(m_applicationState == RUNNING_STATE)
    return STATUS_CODE_FAILURE;
  m_applicationState = RUNNING_STATE;
  DimServer::addClientExitHandler(m_pMonitorElementCollector);
  DimServer::start(("DQM4HEP/" + getType() + "/" + getName()).c_str());
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementCollector->start());
  while(!m_shouldExit)
  {
    timespec timesleep;
      timesleep.tv_sec = 0;
      timesleep.tv_nsec = 100000L;
    nanosleep(&timesleep, NULL);
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementCollectorApplication::setCollectorName (const std::string & collectorName)
Set the monitor element collector name.
Definition at line 119 of file DQMMonitorElementCollectorApplication.cc.
References m_pMonitorElementCollector, and dqm4hep::DQMMonitorElementCollector::setCollectorName().
{
  return m_pMonitorElementCollector->setCollectorName(collectorName);
}
Member Data Documentation
DQMState dqm4hep::DQMMonitorElementCollectorApplication::m_applicationState [protected]
Definition at line 79 of file DQMMonitorElementCollectorApplication.h.
Referenced by exit(), and run().
DQMMonitorElementCollector* dqm4hep::DQMMonitorElementCollectorApplication::m_pMonitorElementCollector [protected]
Definition at line 80 of file DQMMonitorElementCollectorApplication.h.
Referenced by DQMMonitorElementCollectorApplication(), exit(), getName(), run(), setCollectorName(), and ~DQMMonitorElementCollectorApplication().
bool dqm4hep::DQMMonitorElementCollectorApplication::m_shouldExit [protected]
Definition at line 77 of file DQMMonitorElementCollectorApplication.h.
Referenced by exit(), and run().
std::string dqm4hep::DQMMonitorElementCollectorApplication::m_type [protected]
Definition at line 78 of file DQMMonitorElementCollectorApplication.h.
Referenced by getType().
The documentation for this class was generated from the following files:
DQMMonitorElementCollectorApplication.h
DQMMonitorElementCollectorApplication.cc