dqm4hep::DQMEventClient Class Reference
DQMEventClient class.
#include <DQMEventClient.h>
Public Member Functions
DQMEventClient ()
Constructor.
virtual ~DQMEventClient ()
Destructor.
virtual void setCollectorName (const std::string &collectorName)
Set the collector to connect to.
const std::string & getCollectorName () const
Get the collector name.
virtual void setEventStreamer (DQMEventStreamer *pEventStreamer, bool owner=true)
Set the streamer that will stream in/out the sent/received event(s).
DQMEventStreamer * getEventStreamer () const
Get the event streamer.
virtual void setMaximumQueueSize (unsigned int queueSize)
Set the queue size that stores the received events.
virtual unsigned int getMaximumQueueSize () const
Get the maximum number of events that the client can store in its event queue.
virtual void clearQueue ()
Clear the event queue.
virtual void setSubEventIdentifier (const std::string &identifier)
Set the sub event identifier.
const std::string & getSubEventIdentifier () const
Get the sub event identifier.
void takeEvent (DQMEvent *&pEvent)
Take an event from the event queue (pop front) and return the pointer to the caller.
void addListener (DQMEventClientListener *pListener)
Add a listener to this event client.
void removeListener (DQMEventClientListener *pListener)
Remove a listener from this event client.
StatusCode connectToService ()
Connect to the collector service (server)
StatusCode disconnectFromService ()
Disconnect the client from the collector (server)
virtual bool isConnectedToService () const =0
Whether the client is connected to the collector (server)
virtual StatusCode sendEvent (const DQMEvent *const pEvent)=0
Send an event to the collector (server).
virtual StatusCode queryEvent (DQMEvent *&pEvent, int timeout)=0
Query an event to the collector (server) with a timeout and handle it without pushing it into the internal queue.
virtual StatusCode queryEvent ()=0
Query an event to the collector.
virtual void setUpdateMode (bool updateMode)=0
Set the update mode.
virtual bool getUpdateMode () const =0
Whether the update mode is set.
virtual StatusCode readSettings (const TiXmlHandle &xmlHandle)=0
Read settings from the xml handle.
Protected Member Functions
virtual StatusCode performServiceConnection ()=0
Workhorse of the service connection.
virtual StatusCode performServiceDisconnection ()=0
Workhorse of the service connection.
void pushEvent (DQMEvent *pEvent)
Push a new event in the event queue.
Private Attributes
bool m_eventStreamerOwner
DQMEventStreamer * m_pEventStreamer
std::string m_collectorName
std::string m_subEventIdentifier
DQMEventQueue m_eventQueue
unsigned int m_maximumQueueSize
std::set
*
< DQMEventClientListener * > m_listeners
pthread_mutex_t m_mutex
Detailed Description
DQMEventClient class.
Main interface for sending events to a collector (server part) and for event queries.
Note that pushing/taking events in the event queue is thread-safe.
Definition at line 80 of file DQMEventClient.h.
Constructor & Destructor Documentation
dqm4hep::DQMEventClient::DQMEventClient ()
Constructor.
Definition at line 36 of file DQMEventClient.cc.
References m_mutex.
                               :
    m_pEventStreamer(NULL),
    m_maximumQueueSize(100),
    m_eventStreamerOwner(true)
{
  pthread_mutex_init(&m_mutex, NULL);
}
dqm4hep::DQMEventClient::~DQMEventClient () [virtual]
Destructor.
Definition at line 46 of file DQMEventClient.cc.
References clearQueue(), m_eventStreamerOwner, m_mutex, and m_pEventStreamer.
{
  this->clearQueue();
  if(m_eventStreamerOwner && NULL != m_pEventStreamer)
    delete m_pEventStreamer;
  pthread_mutex_destroy(&m_mutex);
}
Member Function Documentation
void dqm4hep::DQMEventClient::addListener (DQMEventClientListener * pListener)
Add a listener to this event client.
Definition at line 160 of file DQMEventClient.cc.
References m_listeners, and m_mutex.
{
  scoped_lock(& this->m_mutex);
  if(NULL == pListener)
    return;
  m_listeners.insert(pListener);
}
void dqm4hep::DQMEventClient::clearQueue () [virtual]
Clear the event queue.
Definition at line 120 of file DQMEventClient.cc.
References m_eventQueue, and m_mutex.
Referenced by dqm4hep::DQMAnalysisModuleApplication::run(), and ~DQMEventClient().
{
  scoped_lock(& this->m_mutex);
  while(! m_eventQueue.empty())
  {
    delete m_eventQueue.front();
    m_eventQueue.pop();
  }
}
StatusCode dqm4hep::DQMEventClient::connectToService ()
Connect to the collector service (server)
Definition at line 209 of file DQMEventClient.cc.
References m_listeners, performServiceConnection(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMDimEventClient::readSettings(), dqm4hep::DQMAnalysisModuleApplication::startServices(), and dqm4hep::DQMAnalysisModuleApplication::stopServices().
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->performServiceConnection());
  for(std::set<DQMEventClientListener*>::iterator iter = m_listeners.begin(), endIter =
      m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->onEventClientConnnect(this);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMEventClient::disconnectFromService ()
Disconnect the client from the collector (server)
Definition at line 222 of file DQMEventClient.cc.
References m_listeners, performServiceDisconnection(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMDimEventClient::readSettings(), and dqm4hep::DQMDimEventClient::~DQMDimEventClient().
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->performServiceDisconnection());
  for(std::set<DQMEventClientListener*>::iterator iter = m_listeners.begin(), endIter =
      m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->onEventClientDisconnnect(this);
  return STATUS_CODE_SUCCESS;
}
const std::string & dqm4hep::DQMEventClient::getCollectorName () const
Get the collector name.
Definition at line 69 of file DQMEventClient.cc.
References m_collectorName.
Referenced by dqm4hep::DQMDimEventClient::infoHandler(), dqm4hep::DQMDimEventClient::performServiceConnection(), dqm4hep::DQMDimEventClient::performServiceDisconnection(), dqm4hep::DQMDimEventClient::queryEvent(), dqm4hep::DQMDimEventClient::readSettings(), dqm4hep::DQMDimEventClient::sendEvent(), dqm4hep::DQMDimEventClient::setSubEventIdentifier(), and dqm4hep::DQMDimEventClient::setUpdateMode().
{
  return m_collectorName;
}
DQMEventStreamer * dqm4hep::DQMEventClient::getEventStreamer () const
Get the event streamer.
Definition at line 87 of file DQMEventClient.cc.
References m_pEventStreamer.
Referenced by dqm4hep::DQMDimEventClient::eventReception(), dqm4hep::DQMDimEventClient::queryEvent(), and dqm4hep::DQMDimEventClient::sendEvent().
{
  return m_pEventStreamer;
}
unsigned int dqm4hep::DQMEventClient::getMaximumQueueSize () const [virtual]
Get the maximum number of events that the client can store in its event queue.
Definition at line 113 of file DQMEventClient.cc.
References m_maximumQueueSize.
Referenced by dqm4hep::DQMDimEventClient::readSettings().
{
  return m_maximumQueueSize;
}
const std::string & dqm4hep::DQMEventClient::getSubEventIdentifier () const
Get the sub event identifier.
Definition at line 140 of file DQMEventClient.cc.
References m_subEventIdentifier.
Referenced by dqm4hep::DQMDimEventClient::infoHandler(), dqm4hep::DQMDimEventClient::queryEvent(), and dqm4hep::DQMDimEventClient::readSettings().
{
  return m_subEventIdentifier;
}
virtual bool dqm4hep::DQMEventClient::getUpdateMode () const [pure virtual]
Whether the update mode is set.
Implemented in dqm4hep::DQMDimEventClient .
virtual bool dqm4hep::DQMEventClient::isConnectedToService () const [pure virtual]
Whether the client is connected to the collector (server)
Implemented in dqm4hep::DQMDimEventClient .
Referenced by setCollectorName(), and dqm4hep::DQMAnalysisModuleApplication::stopServices().
virtual StatusCode dqm4hep::DQMEventClient::performServiceConnection () [protected], [pure virtual]
Workhorse of the service connection.
Implemented in dqm4hep::DQMDimEventClient .
Referenced by connectToService().
virtual StatusCode dqm4hep::DQMEventClient::performServiceDisconnection () [protected], [pure virtual]
Workhorse of the service connection.
Implemented in dqm4hep::DQMDimEventClient .
Referenced by disconnectFromService().
void dqm4hep::DQMEventClient::pushEvent (DQMEvent * pEvent) [protected]
Push a new event in the event queue.
If the event queue has reaches its maximum size the front element of the queue is first deleted and popped.
Listeners are notified of a 'push event'
Definition at line 184 of file DQMEventClient.cc.
References m_eventQueue, m_listeners, m_maximumQueueSize, and m_mutex.
Referenced by dqm4hep::DQMDimEventClient::eventReception().
{
  if(NULL == pEvent)
    return;
  pthread_mutex_lock(& this->m_mutex);
  if(m_eventQueue.size() == m_maximumQueueSize)
  {
    delete m_eventQueue.front();
    m_eventQueue.pop();
  }
  m_eventQueue.push(pEvent);
  // need unlock before notifying
  pthread_mutex_unlock(& this->m_mutex);
  for(std::set<DQMEventClientListener*>::iterator iter = m_listeners.begin(), endIter =
      m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->eventPushed(this);
}
virtual StatusCode dqm4hep::DQMEventClient::queryEvent (DQMEvent *& pEvent, int timeout) [pure virtual]
Query an event to the collector (server) with a timeout and handle it without pushing it into the internal queue.
Implemented in dqm4hep::DQMDimEventClient .
virtual StatusCode dqm4hep::DQMEventClient::queryEvent () [pure virtual]
Query an event to the collector.
A command is send to the collector in order to send back an event. This method does not wait for the event reception.
To query a single event that is directly handled by the caller, use querySingleEvent().
The received event is push in an internal event queue.
Implemented in dqm4hep::DQMDimEventClient .
virtual StatusCode dqm4hep::DQMEventClient::readSettings (const TiXmlHandle & xmlHandle) [pure virtual]
Read settings from the xml handle.
Implemented in dqm4hep::DQMDimEventClient .
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureNetwork().
void dqm4hep::DQMEventClient::removeListener (DQMEventClientListener * pListener)
Remove a listener from this event client.
Definition at line 172 of file DQMEventClient.cc.
References m_listeners, and m_mutex.
{
  scoped_lock(& this->m_mutex);
  if(NULL == pListener)
    return;
  m_listeners.erase(pListener);
}
virtual StatusCode dqm4hep::DQMEventClient::sendEvent (const DQMEvent *const pEvent) [pure virtual]
Send an event to the collector (server).
Possible only if a connection has been created (connectToService()) and an event streamer set.
Implemented in dqm4hep::DQMDimEventClient .
Referenced by dqm4hep::DQMLcioReaderListener::processEvent().
void dqm4hep::DQMEventClient::setCollectorName (const std::string & collectorName) [virtual]
Set the collector to connect to.
Can set the name only if client not yet connected
Definition at line 58 of file DQMEventClient.cc.
References isConnectedToService(), and m_collectorName.
Referenced by dqm4hep::DQMDimEventClient::readSettings().
{
  // if connected to service, can't change collector name
  if(this->isConnectedToService())
    return;
  m_collectorName = collectorName;
}
void dqm4hep::DQMEventClient::setEventStreamer (DQMEventStreamer * pEventStreamer, bool owner = true) [virtual]
Set the streamer that will stream in/out the sent/received event(s).
No default streamer is provided. User must provide one before querying/sending events from/to collector (server). Note that the client does not own the streamer !
Definition at line 76 of file DQMEventClient.cc.
References m_eventStreamerOwner, and m_pEventStreamer.
Referenced by dqm4hep::DQMDimEventClient::readSettings().
{
  if(m_eventStreamerOwner && NULL != m_pEventStreamer)
    delete m_pEventStreamer;
  m_pEventStreamer = pEventStreamer;
  m_eventStreamerOwner = owner;
}
void dqm4hep::DQMEventClient::setMaximumQueueSize (unsigned int queueSize) [virtual]
Set the queue size that stores the received events.
Definition at line 94 of file DQMEventClient.cc.
References m_eventQueue, m_maximumQueueSize, and m_mutex.
Referenced by dqm4hep::DQMDimEventClient::readSettings().
{
  if(0 == maxQueueSize)
    return;
  m_maximumQueueSize = maxQueueSize;
  scoped_lock(& this->m_mutex);
  // shrink the queue to fit the new max queue size
  while(m_eventQueue.size() > m_maximumQueueSize)
  {
    delete m_eventQueue.front();
    m_eventQueue.pop();
  }
}
void dqm4hep::DQMEventClient::setSubEventIdentifier (const std::string & identifier) [virtual]
Set the sub event identifier.
This string is sent while querying events. The received event will be a sub event matching this identifier
Reimplemented in dqm4hep::DQMDimEventClient .
Definition at line 133 of file DQMEventClient.cc.
References m_subEventIdentifier.
Referenced by dqm4hep::DQMDimEventClient::setSubEventIdentifier().
{
  m_subEventIdentifier = identifier;
}
virtual void dqm4hep::DQMEventClient::setUpdateMode (bool updateMode) [pure virtual]
Set the update mode.
If the update mode is set to true, a command is sent to the server in order to update the client as soon as an event is received in the collector server.
Implemented in dqm4hep::DQMDimEventClient .
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureNetwork(), and dqm4hep::DQMAnalysisModuleApplication::run().
void dqm4hep::DQMEventClient::takeEvent (DQMEvent *& pEvent)
Take an event from the event queue (pop front) and return the pointer to the caller.
The event is removed from the queue, meaning that the caller is responsible for the event deletion. If no event is available, the queue remains unchanged and the pointer is not set
Definition at line 147 of file DQMEventClient.cc.
References m_eventQueue, and m_mutex.
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
{
  scoped_lock(& this->m_mutex);
  if(! m_eventQueue.empty())
  {
    pEvent = m_eventQueue.front();
    m_eventQueue.pop();
  }
}
Member Data Documentation
std::string dqm4hep::DQMEventClient::m_collectorName [private]
Definition at line 222 of file DQMEventClient.h.
Referenced by getCollectorName(), and setCollectorName().
DQMEventQueue dqm4hep::DQMEventClient::m_eventQueue [private]
Definition at line 224 of file DQMEventClient.h.
Referenced by clearQueue(), pushEvent(), setMaximumQueueSize(), and takeEvent().
bool dqm4hep::DQMEventClient::m_eventStreamerOwner [private]
Definition at line 220 of file DQMEventClient.h.
Referenced by setEventStreamer(), and ~DQMEventClient().
std::set<DQMEventClientListener*> dqm4hep::DQMEventClient::m_listeners [private]
Definition at line 226 of file DQMEventClient.h.
Referenced by addListener(), connectToService(), disconnectFromService(), pushEvent(), and removeListener().
unsigned int dqm4hep::DQMEventClient::m_maximumQueueSize [private]
Definition at line 225 of file DQMEventClient.h.
Referenced by getMaximumQueueSize(), pushEvent(), and setMaximumQueueSize().
pthread_mutex_t dqm4hep::DQMEventClient::m_mutex [mutable], [private]
Definition at line 227 of file DQMEventClient.h.
Referenced by addListener(), clearQueue(), DQMEventClient(), pushEvent(), removeListener(), setMaximumQueueSize(), takeEvent(), and ~DQMEventClient().
DQMEventStreamer* dqm4hep::DQMEventClient::m_pEventStreamer [private]
Definition at line 221 of file DQMEventClient.h.
Referenced by getEventStreamer(), setEventStreamer(), and ~DQMEventClient().
std::string dqm4hep::DQMEventClient::m_subEventIdentifier [private]
Definition at line 223 of file DQMEventClient.h.
Referenced by getSubEventIdentifier(), and setSubEventIdentifier().
The documentation for this class was generated from the following files:
DQMEventClient.h
DQMEventClient.cc