dqm4hep::DQMTimerCycle Class Reference
DQMTimerCycle class.
#include <DQMTimerCycle.h>
Public Member Functions
DQMTimerCycle ()
Constructor.
~DQMTimerCycle ()
Destructor.
void onCycleStarted ()
Specific call back function when a cycle is stopped.
void onCycleStopped ()
Specific call back function when a cycle is stopped.
void onEventProcessed (const DQMEvent *const)
Specific call back function when an event is processed, depends on cycle type.
bool isEndOfCycleReached () const
Specific function to tell the application to know whether the cycle has reached the end.
Detailed Description
DQMTimerCycle class.
DQMCycle based on a time cycle in seconds. processCycle() called during n seconds
Definition at line 42 of file DQMTimerCycle.h.
Constructor & Destructor Documentation
dqm4hep::DQMTimerCycle::DQMTimerCycle ()
Constructor.
Definition at line 43 of file DQMTimerCycle.cc.
                             :
    DQMCycle()
{
  setCycleValue(30.f); // default set to 30 seconds
}
dqm4hep::DQMTimerCycle::~DQMTimerCycle ()
Destructor.
Definition at line 51 of file DQMTimerCycle.cc.
{
  /* nop */
}
Member Function Documentation
bool dqm4hep::DQMTimerCycle::isEndOfCycleReached () const [virtual]
Specific function to tell the application to know whether the cycle has reached the end.
Implements dqm4hep::DQMCycle .
Definition at line 58 of file DQMTimerCycle.cc.
References dqm4hep::DQMCycle::getCycleValue(), and dqm4hep::DQMCycle::getStartTime().
Referenced by dqm4hep::DQMStandaloneModuleApplication::run().
{
  if(gSystem->Now() > this->getStartTime() + TTime(this->getCycleValue()*1000))
    return true;
  return false;
}
void dqm4hep::DQMTimerCycle::onCycleStarted () [inline], [virtual]
Specific call back function when a cycle is stopped.
Implements dqm4hep::DQMCycle .
Definition at line 53 of file DQMTimerCycle.h.
{ /* nop */ }
void dqm4hep::DQMTimerCycle::onCycleStopped () [inline], [virtual]
Specific call back function when a cycle is stopped.
Implements dqm4hep::DQMCycle .
Definition at line 54 of file DQMTimerCycle.h.
{ /* nop */ }
void dqm4hep::DQMTimerCycle::onEventProcessed (const DQMEvent * pEvent) [inline], [virtual]
Specific call back function when an event is processed, depends on cycle type.
Implements dqm4hep::DQMCycle .
Definition at line 55 of file DQMTimerCycle.h.
{ /* nop */ }
The documentation for this class was generated from the following files:
DQMTimerCycle.h
DQMTimerCycle.cc