dqm4hep::DQMAnalysisModuleApplication Class Reference
DQMAnalysisModuleApplication class.
#include <DQMAnalysisModuleApplication.h>
Classes
class Settings
Settings class.
Public Member Functions
DQMAnalysisModuleApplication ()
Constructor.
~DQMAnalysisModuleApplication ()
Destructor.
const std::string & getType () const
Get the application type (`AnalysisModule`)
const std::string & getName () const
Get the application name (`ModuleType/ModuleName`)
StatusCode readSettings (const std::string &settingsFile)
Read settings from a xml file.
StatusCode run ()
Run the application.
Private Member Functions
StatusCode configureModule (const TiXmlHandle xmlHandle)
Configure the module.
StatusCode configureNetwork (const TiXmlHandle xmlHandle)
Configure network interface.
StatusCode configureCycle (const TiXmlHandle xmlHandle)
Configure the workflow cycle.
StatusCode configureArchiver (const TiXmlHandle xmlHandle)
Configure the archiver.
StatusCode startServices ()
Start all services.
StatusCode stopServices ()
Stop all services.
int getCurrentRunNumber () const
Get the current run number that was started (not from run control)
void onEventProcessed (const DQMCycle *const pCycle, const DQMEvent *const pEvent)
Call back function when an event is processed by the framework.
void onCycleStarted (const DQMCycle *const pCycle)
Call back function when the cycle is started by the framework.
void onCycleStopped (const DQMCycle *const pCycle)
Call back function when the cycle is stopped by the framework.
Private Attributes
Settings m_settings
DQMEventClient * m_pEventClient
DQMRunControlClient * m_pRunControlClient
DQMCycle * m_pCycle
DQMArchiver * m_pArchiver
std::string m_applicationType
std::string m_applicationName
int m_runNumber
Additional Inherited Members
Detailed Description
DQMAnalysisModuleApplication class.
Definition at line 49 of file DQMAnalysisModuleApplication.h.
Constructor & Destructor Documentation
dqm4hep::DQMAnalysisModuleApplication::DQMAnalysisModuleApplication ()
Constructor.
Definition at line 59 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::DQMModuleApplication::DQMArchiver, and m_pArchiver.
                                                           :
    DQMModuleApplication(),
    m_pEventClient(NULL),
    m_pRunControlClient(NULL),
    m_pCycle(NULL),
    m_applicationType("AnalysisModule"),
    m_applicationName("UNKNOWN"),
    m_runNumber(-1)
{
  m_pArchiver = new DQMArchiver();
}
dqm4hep::DQMAnalysisModuleApplication::~DQMAnalysisModuleApplication ()
Destructor.
Definition at line 73 of file DQMAnalysisModuleApplication.cc.
References m_pArchiver, m_pCycle, m_pEventClient, and m_pRunControlClient.
{
  delete m_pArchiver;
  if(m_pEventClient)
    delete m_pEventClient;
  if(m_pRunControlClient)
    delete m_pRunControlClient;
  if(m_pCycle)
    delete m_pCycle;
}
Member Function Documentation
StatusCode dqm4hep::DQMAnalysisModuleApplication::configureArchiver (const TiXmlHandle xmlHandle) [private]
Configure the archiver.
Definition at line 547 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChildElement(), dqm4hep::DQMXmlHelper::getAttribute(), dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMAnalysisModuleApplication::Settings::m_archiveDirectory, m_settings, dqm4hep::DQMAnalysisModuleApplication::Settings::m_shouldOpenArchive, dqm4hep::MESSAGE, and THROW_RESULT_IF.
Referenced by readSettings().
{
  try
  {
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureArchiver: configuring ..." <<
      std::endl;
    const TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("archiver").Element();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "open",
      m_settings.m_shouldOpenArchive));
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "directory",
      m_settings.m_archiveDirectory));
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureArchiver: configuring ... OK" <<
      std::endl;
  }
  catch(const StatusCodeException &exception)
  {
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMAnalysisModuleApplication::configureCycle (const TiXmlHandle xmlHandle) [private]
Configure the workflow cycle.
Definition at line 447 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::DQMCycle::addListener(), dqm4hep::DQMPluginManager::createPluginClass(), dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChildElement(), dqm4hep::DQMXmlHelper::getAttribute(), dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMSingleton< DQMPluginManager >::instance(), dqm4hep::DQMAnalysisModuleApplication::Settings::m_cycleTimeout, dqm4hep::DQMAnalysisModuleApplication::Settings::m_cycleType, dqm4hep::DQMAnalysisModuleApplication::Settings::m_cycleValue, m_pCycle, m_settings, dqm4hep::MESSAGE, dqm4hep::DQMCycle::setCycleValue(), dqm4hep::DQMCycle::setTimeout(), and THROW_RESULT_IF_AND_IF.
Referenced by readSettings().
{
  try
  {
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureCycle: configuring ..." << std::endl;
    const TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("cycle").Element();
    // default values
    m_settings.m_cycleType = "TimerCycle";
    m_settings.m_cycleValue = 10; // 10 seconds
    m_settings.m_cycleTimeout = 3; // 3 seconds
    if(pXmlElement)
    {
      THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pXmlElement, "type", m_settings.m_cycleType));
      THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pXmlElement, "value", m_settings.m_cycleValue));
      THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pXmlElement, "timeout", m_settings.m_cycleTimeout));
    }
    // find the cycle plug-in
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureCycle: querying cycle to
       PluginManager ... OK" << std::endl;
    m_pCycle = DQMPluginManager::instance()->createPluginClass<DQMCycle>(
      m_settings.m_cycleType);
    if(!m_pCycle)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureCycle: querying cycle to
       PluginManager ... OK" << std::endl;
    m_pCycle->setCycleValue(m_settings.m_cycleValue);
    m_pCycle->setTimeout(m_settings.m_cycleTimeout);
    m_pCycle->addListener(this);
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureCycle: configuring ... OK" <<
      std::endl;
  }
  catch(const StatusCodeException &exception)
  {
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMAnalysisModuleApplication::configureModule (const TiXmlHandle xmlHandle) [private]
Configure the module.
Definition at line 492 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::DQMPluginManager::createPluginClass(), dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChildElement(), dqm4hep::DQMXmlHelper::getAttribute(), dqm4hep::DQMModuleApplication::getModule(), dqm4hep::DQMModuleApplication::getModuleName(), dqm4hep::DQMModuleApplication::getModuleType(), dqm4hep::DQMModule::getName(), dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMSingleton< DQMPluginManager >::instance(), m_applicationName, dqm4hep::MESSAGE, readSettings(), dqm4hep::DQMModuleApplication::setModule(), dqm4hep::DQMModuleApplication::setModuleName(), dqm4hep::DQMModuleApplication::setModuleType(), and THROW_RESULT_IF.
Referenced by readSettings().
{
  try
  {
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureModule: configuring ..." << std::endl
      ;
    TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("module").Element();
    std::string type;
    std::string name;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "type", type));
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "name", name));
    if(this->getModuleType().empty())
      this->setModuleType(type);
    if(this->getModuleName().empty())
      this->setModuleName(name);
    streamlog_out(MESSAGE) << "Query analysis module to PluginManager ... " << std::endl;
    DQMAnalysisModule *pAnalysisModule = DQMPluginManager::instance()->
      createPluginClass<DQMAnalysisModule>(this->getModuleType());
    if(!pAnalysisModule)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    this->setModule(pAnalysisModule);
    streamlog_out(MESSAGE) << "Query analysis module to PluginManager ... OK" << std::endl;
    TiXmlHandle moduleHandle(pXmlElement);
    streamlog_out(MESSAGE) << "Reading settings of active module '" << this->
      getModule()->getName() << "' ..." << std::endl;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->readSettings(moduleHandle));
    streamlog_out(MESSAGE) << "Reading settings of active module '" << this->
      getModule()->getName() << "' ... OK" << std::endl;
    streamlog_out(MESSAGE) << "Initializing active module '" << this->
      getModule()->getName() << "' ..." << std::endl;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->initModule());
    streamlog_out(MESSAGE) << "Initializing active module '" << this->
      getModule()->getName() << "' ... OK" << std::endl;
    m_applicationName = this->getModule()->getName();
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureModule: configuring ... OK" <<
      std::endl;
  }
  catch(const StatusCodeException &exception)
  {
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMAnalysisModuleApplication::configureNetwork (const TiXmlHandle xmlHandle) [private]
Configure network interface.
Definition at line 371 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::DQMPluginManager::createPluginClass(), dqm4hep::TiXmlHandle::Element(), dqm4hep::ERROR, dqm4hep::TiXmlHandle::FirstChildElement(), dqm4hep::DQMXmlHelper::getAttribute(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMSingleton< DQMPluginManager >::instance(), dqm4hep::DQMAnalysisModuleApplication::Settings::m_eventClientType, dqm4hep::DQMAnalysisModuleApplication::Settings::m_monitorElementCollector, m_pEventClient, m_pRunControlClient, dqm4hep::DQMAnalysisModuleApplication::Settings::m_runControlName, dqm4hep::DQMAnalysisModuleApplication::Settings::m_runControlType, m_settings, dqm4hep::MESSAGE, dqm4hep::DQMEventClient::readSettings(), dqm4hep::DQMMonitorElementSender::setCollectorName(), dqm4hep::DQMRunControl::setRunControlName(), dqm4hep::DQMEventClient::setUpdateMode(), THROW_RESULT_IF, and THROW_RESULT_IF_AND_IF.
Referenced by readSettings().
{
  try
  {
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureNetwork: configuring ..." <<
      std::endl;
    //
    // Get all xml attributes needed to configure network options !
    //
    TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("network").Element();
    if(NULL == pXmlElement)
    {
      streamlog_out(ERROR) << "<network> element not found !" << std::endl;
      return STATUS_CODE_NOT_FOUND;
    }
    const TiXmlHandle networkHandle(pXmlElement);
    TiXmlElement *const pRunControlXmlElement = networkHandle.FirstChildElement("runcontrol").Element();
    TiXmlElement *const pEventCollectorXmlElement = networkHandle.FirstChildElement("eventcollector").
      Element();
    TiXmlElement *const pMonitorElementCollectorXmlElement = networkHandle.FirstChildElement("
      monitorelementcollector").Element();
    if(NULL == pRunControlXmlElement
    || NULL == pEventCollectorXmlElement
    || NULL == pMonitorElementCollectorXmlElement)
    {
      streamlog_out(ERROR) << "Incomplete network xml element" << std::endl;
      return STATUS_CODE_NOT_FOUND;
    }
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pRunControlXmlElement, "name",
      m_settings.m_runControlName));
    THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pRunControlXmlElement, "type", m_settings.
      m_runControlType));
    THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pEventCollectorXmlElement, "type", m_settings.
      m_eventClientType));
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pMonitorElementCollectorXmlElement,
       "name", m_settings.m_monitorElementCollector));
    //
    // Configure network form the extracted xml values
    //
    // monitor element collector name
    this->getMonitorElementSender()->setCollectorName(m_settings.
      m_monitorElementCollector);
    // event client
    DQMEventClient *pEventClient = DQMPluginManager::instance()->
      createPluginClass<DQMEventClient>(m_settings.m_eventClientType);
    if(! pEventClient)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pEventClient->readSettings(TiXmlHandle(
      pEventCollectorXmlElement)));
    // force update mode to false for the moment
    pEventClient->setUpdateMode(false);
    m_pEventClient = pEventClient;
    // configure run control
    DQMRunControlClient *pRunControlClient = DQMPluginManager::instance()->
      createPluginClass<DQMRunControlClient>(m_settings.m_runControlType);
    if(NULL == pRunControlClient)
      throw StatusCodeException(STATUS_CODE_NOT_FOUND);
    pRunControlClient->setRunControlName(m_settings.m_runControlName);
    m_pRunControlClient = pRunControlClient;
    streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication::configureNetwork: configuring ... OK" <<
      std::endl;
  }
  catch(const StatusCodeException &exception)
  {
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
int dqm4hep::DQMAnalysisModuleApplication::getCurrentRunNumber () const [private]
Get the current run number that was started (not from run control)
Definition at line 599 of file DQMAnalysisModuleApplication.cc.
References m_runNumber.
Referenced by run().
{
  return m_runNumber;
}
const std::string & dqm4hep::DQMAnalysisModuleApplication::getName () const [virtual]
Get the application name (`ModuleType/ModuleName`)
Implements dqm4hep::DQMModuleApplication .
Definition at line 364 of file DQMAnalysisModuleApplication.cc.
References m_applicationName.
{
  return m_applicationName;
}
const std::string & dqm4hep::DQMAnalysisModuleApplication::getType () const [virtual]
Get the application type (`AnalysisModule`)
Implements dqm4hep::DQMModuleApplication .
Definition at line 357 of file DQMAnalysisModuleApplication.cc.
References m_applicationType.
{
  return m_applicationType;
}
void dqm4hep::DQMAnalysisModuleApplication::onCycleStarted (const DQMCycle *const pCycle) [private], [virtual]
Call back function when the cycle is started by the framework.
Implements dqm4hep::DQMCycleListener .
Definition at line 606 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::DQMModuleApplication::getModule(), and THROW_RESULT_IF.
{
  THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->startOfCycle());
}
void dqm4hep::DQMAnalysisModuleApplication::onCycleStopped (const DQMCycle *const pCycle) [private], [virtual]
Call back function when the cycle is stopped by the framework.
Implements dqm4hep::DQMCycleListener .
Definition at line 613 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::DQMModuleApplication::getModule(), and THROW_RESULT_IF.
{
  THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->endOfCycle());
}
void dqm4hep::DQMAnalysisModuleApplication::onEventProcessed (const DQMCycle *const pCycle, const DQMEvent *const pEvent) [inline], [private], [virtual]
Call back function when an event is processed by the framework.
Implements dqm4hep::DQMCycleListener .
Definition at line 135 of file DQMAnalysisModuleApplication.h.
{ /* nop */ }
StatusCode dqm4hep::DQMAnalysisModuleApplication::readSettings (const std::string & settingsFile) [virtual]
Read settings from a xml file.
Initialize the application. Declare all the services, load the shared libraries, configure the active module
Implements dqm4hep::DQMModuleApplication .
Definition at line 89 of file DQMAnalysisModuleApplication.cc.
References configureArchiver(), configureCycle(), configureModule(), configureNetwork(), dqm4hep::DQMFileHandlerFactory::createFileHandler(), dqm4hep::DEBUG, dqm4hep::DQMFileHandler::download(), dqm4hep::TiXmlHandle::Element(), dqm4hep::ERROR, dqm4hep::TiXmlHandle::FirstChildElement(), dqm4hep::DQMFileHandler::getLocalFileName(), dqm4hep::DQMModuleApplication::getModule(), dqm4hep::DQMModule::getName(), dqm4hep::DQMModuleApplication::isInitialized(), dqm4hep::TiXmlDocument::LoadFile(), m_settings, dqm4hep::DQMAnalysisModuleApplication::Settings::m_settingsFileName, dqm4hep::DQMAnalysisModuleApplication::Settings::print(), RETURN_RESULT_IF, and dqm4hep::DQMModuleApplication::setInitialized().
Referenced by configureModule().
{
  if(this->isInitialized())
    return STATUS_CODE_ALREADY_INITIALIZED;
  size_t splitterPosition = settingsFileName.find(":");
  std::string fileHandlerType;
  std::string filePattern;
  if(splitterPosition != std::string::npos)
  {
    fileHandlerType = settingsFileName.substr(0, splitterPosition);
    filePattern = settingsFileName.substr(splitterPosition+1);
  }
  else
  {
    fileHandlerType = "";
    filePattern = settingsFileName;
  }
  streamlog_out(DEBUG) << "File handler type : " << fileHandlerType << std::endl;
  DQMFileHandlerFactory fileHandlerFactory;
  DQMFileHandler *pFileHandler = fileHandlerFactory.createFileHandler(fileHandlerType);
  if(!pFileHandler)
    return STATUS_CODE_FAILURE;
  StatusCode statusCode = pFileHandler->download(filePattern);
  if(statusCode != STATUS_CODE_SUCCESS)
  {
    delete pFileHandler;
    return statusCode;
  }
  std::string localSettingsFile = pFileHandler->getLocalFileName();
  delete pFileHandler;
  TiXmlDocument xmlDocument(localSettingsFile);
    if (!xmlDocument.LoadFile())
    {
        std::cout << "DQMAnalysisModuleApplication::readSettings - Invalid xml file." << std::endl;
        return STATUS_CODE_FAILURE;
    }
    const TiXmlHandle xmlDocumentHandle(&xmlDocument);
    const TiXmlHandle xmlHandle = TiXmlHandle(xmlDocumentHandle.FirstChildElement().Element());
  // configure module
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, configureModule(xmlHandle));
  DimBrowser browser;
  int nServers = browser.getServers();
  std::string moduleServerName = "DQM4HEP/Module/" + this->getModule()->getName();
  if(nServers)
  {
    char *serverName;
    char *node;
    while(browser.getNextServer(serverName, node))
    {
      if(moduleServerName == serverName)
      {
        streamlog_out(ERROR) << "Module '" << this->getModule()->getName() << "' already registered over
       the network.\n"
            << "Please, change the module name or stop the other module application with the same name !" <
      < std::endl;
        return STATUS_CODE_ALREADY_PRESENT;
      }
    }
  }
  DimServer::start(moduleServerName.c_str());
  // configure remaining part of the application
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->configureCycle(xmlHandle));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->configureArchiver(xmlHandle));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->configureNetwork(xmlHandle));
  m_settings.m_settingsFileName = settingsFileName;
  m_settings.print();
  setInitialized(true);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMAnalysisModuleApplication::run () [virtual]
Run the application.
Implements dqm4hep::DQMModuleApplication .
Definition at line 181 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::DQMArchiver::archive(), dqm4hep::DQMEventClient::clearQueue(), dqm4hep::DQMArchiver::close(), dqm4hep::DQMAnalysisModule::endOfRun(), dqm4hep::ERROR, dqm4hep::DQMCycle::eventProcessed(), dqm4hep::DQMRunControl::getCurrentRun(), dqm4hep::DQMRunControl::getCurrentRunNumber(), getCurrentRunNumber(), dqm4hep::DQMArchiver::getFileName(), dqm4hep::DQMModuleApplication::getModule(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), dqm4hep::DQMCycle::getNProcessedEvents(), dqm4hep::DQMCycle::getProcessingRate(), dqm4hep::DQMModuleApplication::getReturnCode(), dqm4hep::DQMRun::getRunNumber(), dqm4hep::DQMCycle::getTotalCycleTime(), dqm4hep::DQMCycle::isEndOfCycleReached(), dqm4hep::DQMModuleApplication::isInitialized(), dqm4hep::DQMRunControl::isRunning(), dqm4hep::DQMCycle::isTimeoutReached(), dqm4hep::DQMAnalysisModuleApplication::Settings::m_archiveDirectory, m_pArchiver, m_pCycle, m_pEventClient, m_pRunControlClient, m_runNumber, m_settings, dqm4hep::DQMAnalysisModuleApplication::Settings::m_shouldOpenArchive, dqm4hep::MESSAGE, dqm4hep::DQMArchiver::open(), dqm4hep::DQMAnalysisModule::processEvent(), RETURN_RESULT_IF, dqm4hep::DQMRun::setEndTime(), dqm4hep::DQMEventClient::setUpdateMode(), dqm4hep::DQMModuleApplication::shouldStopApplication(), dqm4hep::DQMCycle::startCycle(), dqm4hep::DQMAnalysisModule::startOfRun(), startServices(), dqm4hep::DQMCycle::stopCycle(), stopServices(), dqm4hep::DQMEventClient::takeEvent(), and dqm4hep::StatusCodeException::toString().
{
  if(!this->isInitialized())
    return STATUS_CODE_NOT_INITIALIZED;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->startServices());
  // get casted module for easier manipulation
  DQMAnalysisModule *pAnalysisModule = dynamic_cast<DQMAnalysisModule *>(this->
      getModule());
  std::string moduleName = pAnalysisModule->getName();
  // infinite loop
  while(!this->shouldStopApplication())
  {
    // wait for a start of run
    bool firstMessage = true;
    while(!m_pRunControlClient->isRunning() && !this->shouldStopApplication())
    {
      if(firstMessage)
      {
        streamlog_out(MESSAGE) << "... Waiting for next run ..." << std::endl;
        firstMessage = false;
      }
      timespec timesleep;
      timesleep.tv_sec = 0;
      timesleep.tv_nsec = 1000000L;
      nanosleep(&timesleep, NULL);
    }
    if(this->shouldStopApplication())
      break;
    DQMRun *pRun = m_pRunControlClient->getCurrentRun();
    if(NULL == pRun)
      continue;
    m_runNumber = pRun->getRunNumber();
    streamlog_out(MESSAGE) << "Starting new run no " << pRun->getRunNumber() << std::endl;
    // open an archive
    if(m_settings.m_shouldOpenArchive)
    {
      std::stringstream archiveFileName;
      std::string directory =
          m_settings.m_archiveDirectory.at(m_settings.m_archiveDirectory.size() - 1) == '/' ?
              m_settings.m_archiveDirectory : m_settings.m_archiveDirectory + "/";
      archiveFileName << directory
          << "DQMArchive"
          << "_M" << moduleName
          << "_I" << pRun->getRunNumber();
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->open(archiveFileName.str(), "RECREATE"));
      streamlog_out(MESSAGE) << "Archive '" << m_pArchiver->getFileName() << "' opened" << std::endl;
    }
    // start of run !
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pAnalysisModule->startOfRun(pRun));
    // start receiving data
    m_pEventClient->setUpdateMode(true);
    // while run has not ended, process cycles
    while(m_pRunControlClient->isRunning() && !this->shouldStopApplication())
    {
      // process a cycle
      streamlog_out(MESSAGE) << "**************************************************" << std::endl;
      streamlog_out(MESSAGE) << "*** Start of cycle ***" << std::endl;
      streamlog_out(MESSAGE) << "**************************************************" << std::endl;
      m_pCycle->startCycle();
      while(1)
      {
        if(m_pCycle->isEndOfCycleReached())
          break;
        if(m_pCycle->isTimeoutReached())
          break;
        if(this->shouldStopApplication())
          break;
        DQMEvent *pEvent = NULL;
        m_pEventClient->takeEvent(pEvent);
        if(NULL == pEvent)
          continue;
        try
        {
          StatusCode statusCode = pAnalysisModule->processEvent(pEvent);
          m_pCycle->eventProcessed(pEvent);
        }
        catch(StatusCodeException &exception)
        {
          streamlog_out(ERROR) << "Module::processEvent(evt) returned " << exception.toString() << " !" <<
      std::endl;
        }
        catch(...)
        {
          streamlog_out(ERROR) << "Module::processEvent(evt) : caught unknown exception !" << std::endl;
        }
        if(pEvent)
          delete pEvent;
      }
      m_pCycle->stopCycle();
      streamlog_out(MESSAGE) << "**************************************************" << std::endl;
      streamlog_out(MESSAGE) << "*** End of cycle reached ***" << std::endl;
      streamlog_out(MESSAGE) << "**************************************************" << std::endl;
      streamlog_out(MESSAGE) << "*** STATISTICS ***" << std::endl;
      streamlog_out(MESSAGE) << "*** N processed events : " << m_pCycle->
      getNProcessedEvents() << std::endl;
      streamlog_out(MESSAGE) << "*** Event rate : " << m_pCycle->
      getProcessingRate()*1000.f << " evts/s" << std::endl;
      streamlog_out(MESSAGE) << "*** Processing time : " << m_pCycle->
      getTotalCycleTime().operator long long()/1000.f << " s" << std::endl;
      streamlog_out(MESSAGE) << "**************************************************" << std::endl;
      // archive publication if user asked for
      if(m_settings.m_shouldOpenArchive)
        RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->archive(pAnalysisModule));
// DQMMonitorElementList monitorElementListToPublish;
// RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementManager()
// ->getMonitorElementListToPublish(monitorElementListToPublish));
      // TODO find a way to update the run number in monitor elements
// // set monitor elements infos
// for(DQMMonitorElementList::iterator iter = monitorElementListToPublish.begin(), endIter =
       monitorElementListToPublish.end() ;
// endIter != iter ; ++iter)
// (*iter)->setRunNumber(this->getCurrentRunNumber());
      // send monitor elements to collector
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->sendMonitorElements());
      // reset the monitor elements with end of run reset policy
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementManager()
          ->resetMonitorElements(END_OF_CYCLE_RESET_POLICY));
      // stop current run if run number has changed or run stopped
      if(m_pRunControlClient->getCurrentRunNumber() != this->getCurrentRunNumber())
        break;
    }
    // stop receive data and clear contents
    m_pEventClient->setUpdateMode(false);
    m_pEventClient->clearQueue();
    // fill the run end time
    pRun->setEndTime(time(NULL));
    // process the end of run module stuff
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pAnalysisModule->endOfRun(pRun));
    // reset the monitor elements that have been reset at end of run
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementManager()
        ->resetMonitorElements(END_OF_RUN_RESET_POLICY));
    // archive the monitor element if archive is opened
    if(m_settings.m_shouldOpenArchive)
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->close());
  }
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, stopServices());
  streamlog_out(MESSAGE) << "DQMAnalysisModuleApplication: Exiting application ..." << std::endl;
  return this->getReturnCode();
}
StatusCode dqm4hep::DQMAnalysisModuleApplication::startServices () [private]
Start all services.
Called just at beginning of run()
Definition at line 570 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::DQMRunControlClient::connectToService(), dqm4hep::DQMEventClient::connectToService(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), m_pEventClient, m_pRunControlClient, and RETURN_RESULT_IF.
Referenced by run().
{
  // start clients
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventClient->connectToService());
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControlClient->
      connectToService());
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->connectToService());
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMAnalysisModuleApplication::stopServices () [private]
Stop all services.
Called at the end of run() before exit
Definition at line 582 of file DQMAnalysisModuleApplication.cc.
References dqm4hep::DQMRunControlClient::connectToService(), dqm4hep::DQMMonitorElementSender::connectToService(), dqm4hep::DQMEventClient::connectToService(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMRunControlClient::isConnectedToService(), dqm4hep::DQMMonitorElementSender::isConnectedToService(), dqm4hep::DQMEventClient::isConnectedToService(), m_pEventClient, m_pRunControlClient, and RETURN_RESULT_IF.
Referenced by run().
{
  // start clients
  if(m_pEventClient && m_pEventClient->isConnectedToService())
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventClient->connectToService());
  if(m_pRunControlClient && m_pRunControlClient->isConnectedToService())
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControlClient->
      connectToService());
  if(this->getMonitorElementSender() && this->getMonitorElementSender()->
      isConnectedToService())
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->
      connectToService());
  return STATUS_CODE_SUCCESS;
}
Member Data Documentation
std::string dqm4hep::DQMAnalysisModuleApplication::m_applicationName [private]
Definition at line 149 of file DQMAnalysisModuleApplication.h.
Referenced by configureModule(), and getName().
std::string dqm4hep::DQMAnalysisModuleApplication::m_applicationType [private]
Definition at line 148 of file DQMAnalysisModuleApplication.h.
Referenced by getType().
DQMArchiver* dqm4hep::DQMAnalysisModuleApplication::m_pArchiver [private]
Definition at line 146 of file DQMAnalysisModuleApplication.h.
Referenced by DQMAnalysisModuleApplication(), run(), and ~DQMAnalysisModuleApplication().
DQMCycle* dqm4hep::DQMAnalysisModuleApplication::m_pCycle [private]
Definition at line 145 of file DQMAnalysisModuleApplication.h.
Referenced by configureCycle(), run(), and ~DQMAnalysisModuleApplication().
DQMEventClient* dqm4hep::DQMAnalysisModuleApplication::m_pEventClient [private]
Definition at line 143 of file DQMAnalysisModuleApplication.h.
Referenced by configureNetwork(), run(), startServices(), stopServices(), and ~DQMAnalysisModuleApplication().
DQMRunControlClient* dqm4hep::DQMAnalysisModuleApplication::m_pRunControlClient [private]
Definition at line 144 of file DQMAnalysisModuleApplication.h.
Referenced by configureNetwork(), run(), startServices(), stopServices(), and ~DQMAnalysisModuleApplication().
int dqm4hep::DQMAnalysisModuleApplication::m_runNumber [private]
Definition at line 151 of file DQMAnalysisModuleApplication.h.
Referenced by getCurrentRunNumber(), and run().
Settings dqm4hep::DQMAnalysisModuleApplication::m_settings [private]
Definition at line 141 of file DQMAnalysisModuleApplication.h.
Referenced by configureArchiver(), configureCycle(), configureNetwork(), readSettings(), and run().
The documentation for this class was generated from the following files:
DQMAnalysisModuleApplication.h
DQMAnalysisModuleApplication.cc