dqm4hep::TiXmlDocument Class Reference
Always the top level node.
#include <tinyxml.h>
Public Member Functions
TiXmlDocument ()
Create an empty document, that has no name.
TiXmlDocument (const char *documentName)
Create a document with a name. The name of the document is also the filename of the xml.
TiXmlDocument (const std::string &documentName)
Constructor.
TiXmlDocument (const TiXmlDocument &copy)
void operator= (const TiXmlDocument &copy)
virtual ~TiXmlDocument ()
bool LoadFile (TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the current document value.
bool SaveFile () const
Save a file using the current document value. Returns true if successful.
bool LoadFile (const char *filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
bool SaveFile (const char *filename) const
Save a file using the given filename. Returns true if successful.
bool LoadFile (FILE *, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*.
bool SaveFile (FILE *) const
Save a file using the given FILE*. Returns true if successful.
bool LoadFile (const std::string &filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool SaveFile (const std::string &filename) const
< STL std::string version.
virtual const char * Parse (const char *p, TiXmlParsingData *data=0, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Parse the given null terminated block of xml data.
const TiXmlElement * RootElement () const
Get the root element -- the only top level element -- of the document.
TiXmlElement * RootElement ()
bool Error () const
If an error occurs, Error will be set to true.
const char * ErrorDesc () const
Contains a textual (english) description of the error if one occurs.
int ErrorId () const
Generally, you probably want the error string (ErrorDesc()).
int ErrorRow () const
Returns the location (if known) of the error.
int ErrorCol () const
The column where the error occured. See ErrorRow()
void SetTabSize (int _tabsize)
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column.
int TabSize () const
void ClearError ()
If you have handled the error, it can be reset with this call.
void Print () const
Write the document to standard out using formatted printing (`pretty print`).
virtual void Print (FILE *cfile, int depth=0) const
Print this Document to a FILE stream.
void SetError (int err, const char *errorLocation, TiXmlParsingData *prevData, TiXmlEncoding encoding)
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *content) const
Walk the XML tree visiting this node and all of its children.
Protected Member Functions
virtual TiXmlNode * Clone () const
Create an exact duplicate of this node and return it.
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Private Member Functions
void CopyTo (TiXmlDocument *target) const
Private Attributes
bool error
int errorId
TIXML_STRING errorDesc
int tabsize
TiXmlCursor errorLocation
bool useMicrosoftBOM
Additional Inherited Members
Detailed Description
Always the top level node.
A document binds together all the XML pieces. It can be saved, loaded, and printed to the screen. The 'value' of a document node is the xml file name.
Definition at line 1392 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::TiXmlDocument::TiXmlDocument ()
Create an empty document, that has no name.
Definition at line 872 of file tinyxml.cc.
References ClearError(), tabsize, and useMicrosoftBOM.
Referenced by Clone().
                             : TiXmlNode(TiXmlNode::TINYXML_DOCUMENT)
{
  tabsize = 4;
  useMicrosoftBOM = false;
  ClearError();
}
dqm4hep::TiXmlDocument::TiXmlDocument (const char * documentName)
Create a document with a name. The name of the document is also the filename of the xml.
Definition at line 879 of file tinyxml.cc.
References ClearError(), tabsize, useMicrosoftBOM, and dqm4hep::TiXmlNode::value.
                                                        : TiXmlNode(
      TiXmlNode::TINYXML_DOCUMENT)
{
  tabsize = 4;
  useMicrosoftBOM = false;
  value = documentName;
  ClearError();
}
dqm4hep::TiXmlDocument::TiXmlDocument (const std::string & documentName)
Constructor.
dqm4hep::TiXmlDocument::TiXmlDocument (const TiXmlDocument & copy)
Definition at line 899 of file tinyxml.cc.
References CopyTo().
                                                        : TiXmlNode(
      TiXmlNode::TINYXML_DOCUMENT)
{
  copy.CopyTo(this);
}
virtual dqm4hep::TiXmlDocument::~TiXmlDocument () [inline], [virtual]
Definition at line 1408 of file tinyxml.h.
{}
Member Function Documentation
bool dqm4hep::TiXmlDocument::Accept (TiXmlVisitor * content) const [virtual]
Walk the XML tree visiting this node and all of its children.
Implements dqm4hep::TiXmlNode .
Definition at line 1114 of file tinyxml.cc.
References dqm4hep::TiXmlNode::FirstChild(), dqm4hep::TiXmlNode::NextSibling(), dqm4hep::TiXmlVisitor::VisitEnter(), and dqm4hep::TiXmlVisitor::VisitExit().
{
  if (visitor->VisitEnter(*this))
  {
    for (const TiXmlNode* node=FirstChild(); node; node=node->NextSibling())
    {
      if (!node->Accept(visitor))
        break;
    }
  }
  return visitor->VisitExit(*this);
}
void dqm4hep::TiXmlDocument::ClearError () [inline]
If you have handled the error, it can be reset with this call.
The error state is automatically cleared if you Parse a new XML block.
Definition at line 1510 of file tinyxml.h.
References dqm4hep::TiXmlCursor::col, error, errorDesc, errorId, errorLocation, and dqm4hep::TiXmlCursor::row.
Referenced by Parse(), and TiXmlDocument().
                              { error = false;
                        errorId = 0;
                        errorDesc = "";
                        errorLocation.row = errorLocation.col = 0;
                        //errorLocation.last = 0;
                      }
TiXmlNode * dqm4hep::TiXmlDocument::Clone () const [protected], [virtual]
Create an exact duplicate of this node and return it.
The memory must be deleted by the caller.
Implements dqm4hep::TiXmlNode .
Definition at line 1092 of file tinyxml.cc.
References CopyTo(), and TiXmlDocument().
{
  TiXmlDocument* clone = new TiXmlDocument();
  if (!clone)
    return 0;
  CopyTo(clone);
  return clone;
}
void dqm4hep::TiXmlDocument::CopyTo (TiXmlDocument * target) const [private]
Definition at line 1073 of file tinyxml.cc.
References dqm4hep::TiXmlNode::Clone(), dqm4hep::TiXmlNode::CopyTo(), error, errorDesc, errorId, errorLocation, dqm4hep::TiXmlNode::firstChild, dqm4hep::TiXmlNode::LinkEndChild(), dqm4hep::TiXmlNode::NextSibling(), tabsize, and useMicrosoftBOM.
Referenced by Clone(), operator=(), and TiXmlDocument().
{
  TiXmlNode::CopyTo(target);
  target->error = error;
  target->errorId = errorId;
  target->errorDesc = errorDesc;
  target->tabsize = tabsize;
  target->errorLocation = errorLocation;
  target->useMicrosoftBOM = useMicrosoftBOM;
  TiXmlNode* node = 0;
  for (node = firstChild; node; node = node->NextSibling())
  {
    target->LinkEndChild(node->Clone());
  }
}
bool dqm4hep::TiXmlDocument::Error () const [inline]
If an error occurs, Error will be set to true.
Also,
The ErrorId() will contain the integer identifier of the error (not generally useful)
The ErrorDesc() method will return the name of the error. (very useful)
The ErrorRow() and ErrorCol() will return the location of the error (if known)
Definition at line 1459 of file tinyxml.h.
References error.
Referenced by LoadFile().
{ return error; }
int dqm4hep::TiXmlDocument::ErrorCol () const [inline]
The column where the error occured. See ErrorRow()
Definition at line 1477 of file tinyxml.h.
References dqm4hep::TiXmlCursor::col, and errorLocation.
const char* dqm4hep::TiXmlDocument::ErrorDesc () const [inline]
Contains a textual (english) description of the error if one occurs.
Definition at line 1462 of file tinyxml.h.
References errorDesc.
{ return errorDesc.c_str (); }
int dqm4hep::TiXmlDocument::ErrorId () const [inline]
Generally, you probably want the error string (ErrorDesc()).
But if you prefer the ErrorId, this function will fetch it.
Definition at line 1467 of file tinyxml.h.
References errorId.
{ return errorId; }
int dqm4hep::TiXmlDocument::ErrorRow () const [inline]
Returns the location (if known) of the error.
The first column is column 1, and the first row is row 1. A value of 0 means the row and column wasn't applicable (memory errors, for example, have no row/column) or the parser lost the error. (An error in the error reporting, in that case.)
See also
SetTabSize, Row, Column
Definition at line 1476 of file tinyxml.h.
References errorLocation, and dqm4hep::TiXmlCursor::row.
{ return errorLocation.row+1; }
bool dqm4hep::TiXmlDocument::LoadFile (TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the current document value.
Returns true if successful. Will delete any existing document data before loading.
Definition at line 912 of file tinyxml.cc.
References dqm4hep::TiXmlNode::Value().
Referenced by LoadFile(), dqm4hep::DQMStandaloneModuleApplication::readSettings(), and dqm4hep::DQMAnalysisModuleApplication::readSettings().
{
  return LoadFile(Value(), encoding);
}
bool dqm4hep::TiXmlDocument::LoadFile (const char * filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
Definition at line 923 of file tinyxml.cc.
References LoadFile(), SetError(), dqm4hep::TIXML_ENCODING_UNKNOWN, dqm4hep::TiXmlBase::TIXML_ERROR_OPENING_FILE, TIXML_STRING, dqm4hep::TiXmlFOpen(), and dqm4hep::TiXmlNode::value.
{
  TIXML_STRING filename(_filename);
  value = filename;
  // reading in binary mode so that tinyxml can normalize the EOL
  FILE* file = TiXmlFOpen(value.c_str (), "rb");
  if (file)
  {
    bool result = LoadFile(file, encoding);
    fclose(file);
    return result;
  }
  else
  {
    SetError(TIXML_ERROR_OPENING_FILE, 0, 0, TIXML_ENCODING_UNKNOWN);
    return false;
  }
}
bool dqm4hep::TiXmlDocument::LoadFile (FILE * file, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*.
Returns true if successful. Note that this method doesn't stream - the entire object pointed at by the FILE* will be interpreted as an XML file. TinyXML doesn't stream in XML from the current file location. Streaming may be added in the future.
Definition at line 944 of file tinyxml.cc.
References dqm4hep::TiXmlCursor::Clear(), dqm4hep::TiXmlNode::Clear(), Error(), dqm4hep::TiXmlBase::location, Parse(), SetError(), dqm4hep::TIXML_ENCODING_UNKNOWN, dqm4hep::TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, and dqm4hep::TiXmlBase::TIXML_ERROR_OPENING_FILE.
{
  if (!file)
  {
    SetError(TIXML_ERROR_OPENING_FILE, 0, 0, TIXML_ENCODING_UNKNOWN);
    return false;
  }
  // Delete the existing data:
  Clear();
  location.Clear();
  // Get the file size, so we can pre-allocate the string. HUGE speed impact.
  long length = 0;
  fseek(file, 0, SEEK_END);
  length = ftell(file);
  fseek(file, 0, SEEK_SET);
  // Strange case, but good to handle up front.
  if (length <= 0)
  {
    SetError(TIXML_ERROR_DOCUMENT_EMPTY, 0, 0, TIXML_ENCODING_UNKNOWN);
    return false;
  }
  // Subtle bug here. TinyXml did use fgets. But from the XML spec:
  // 2.11 End-of-Line Handling
  // <snip>
  // <quote>
  // ...the XML processor MUST behave as if it normalized all line breaks in external
  // parsed entities (including the document entity) on input, before parsing, by translating
  // both the two-character sequence #xD #xA and any #xD that is not followed by #xA to
  // a single #xA character.
  // </quote>
  //
  // It is not clear fgets does that, and certainly isn't clear it works cross platform.
  // Generally, you expect fgets to translate from the convention of the OS to the c/unix
  // convention, and not work generally.
  /*
  while(fgets(buf, sizeof(buf), file))
  {
    data += buf;
  }
  */
  char* buf = new char[ length+1 ];
  buf[0] = 0;
  if (fread(buf, length, 1, file) != 1) {
    delete [] buf;
    SetError(TIXML_ERROR_OPENING_FILE, 0, 0, TIXML_ENCODING_UNKNOWN);
    return false;
  }
  // Process the buffer in place to normalize new lines. (See comment above.)
  // Copies from the 'p' to 'q' pointer, where p can advance faster if
  // a newline-carriage return is hit.
  //
  // Wikipedia:
  // Systems based on ASCII or a compatible character set use either LF (Line feed, '\n', 0x0A, 10 in
       decimal) or
  // CR (Carriage return, '\r', 0x0D, 13 in decimal) individually, or CR followed by LF (CR+LF, 0x0D
       0x0A)...
  // * LF: Multics, Unix and Unix-like systems (GNU/Linux, AIX, Xenix, Mac OS X, FreeBSD, etc.),
       BeOS, Amiga, RISC OS, and others
    // * CR+LF: DEC RT-11 and most other early non-Unix, non-IBM OSes, CP/M, MP/M, DOS, OS/2, Microsoft
       Windows, Symbian OS
    // * CR: Commodore 8-bit machines, Apple II family, Mac OS up to version 9 and OS-9
  const char* p = buf; // the read head
  char* q = buf; // the write head
  const char CR = 0x0d;
  const char LF = 0x0a;
  buf[length] = 0;
  while(*p) {
    assert(p < (buf+length));
    assert(q <= (buf+length));
    assert(q <= p);
    if (*p == CR) {
      *q++ = LF;
      p++;
      if (*p == LF) { // check for CR+LF (and skip LF)
        p++;
      }
    }
    else {
      *q++ = *p++;
    }
  }
  assert(q <= (buf+length));
  *q = 0;
  Parse(buf, 0, encoding);
  delete [] buf;
  return !Error();
}
bool dqm4hep::TiXmlDocument::LoadFile (const std::string & filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING) [inline]
Parameters
encoding STL std::string version.
Definition at line 1431 of file tinyxml.h.
References LoadFile().
  {
    return LoadFile(filename.c_str(), encoding);
  }
void dqm4hep::TiXmlDocument::operator= (const TiXmlDocument & copy)
Definition at line 905 of file tinyxml.cc.
References dqm4hep::TiXmlNode::Clear(), and CopyTo().
{
  Clear();
  copy.CopyTo(this);
}
const char * dqm4hep::TiXmlDocument::Parse (const char * p, TiXmlParsingData * data = 0, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING) [virtual]
Parse the given null terminated block of xml data.
Passing in an encoding to this method (either TIXML_ENCODING_LEGACY or TIXML_ENCODING_UTF8 will force TinyXml to use that encoding, regardless of what TinyXml might otherwise try to detect.
Implements dqm4hep::TiXmlBase .
Definition at line 707 of file tinyxmlparser.cc.
References dqm4hep::TiXmlCursor::Clear(), ClearError(), dqm4hep::TiXmlCursor::col, dqm4hep::TiXmlParsingData::Cursor(), dqm4hep::TiXmlParsingData::cursor, dqm4hep::TiXmlDeclaration::Encoding(), dqm4hep::TiXmlNode::firstChild, dqm4hep::TiXmlNode::Identify(), dqm4hep::TiXmlNode::LinkEndChild(), dqm4hep::TiXmlBase::location, dqm4hep::TiXmlBase::Parse(), dqm4hep::TiXmlCursor::row, SetError(), dqm4hep::TiXmlBase::SkipWhiteSpace(), dqm4hep::TiXmlBase::StringEqual(), TabSize(), dqm4hep::TIXML_ENCODING_LEGACY, dqm4hep::TIXML_ENCODING_UNKNOWN, dqm4hep::TIXML_ENCODING_UTF8, dqm4hep::TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, dqm4hep::TiXmlNode::ToDeclaration(), and useMicrosoftBOM.
Referenced by LoadFile().
{
  ClearError();
  // Parse away, at the document level. Since a document
  // contains nothing but other tags, most of what happens
  // here is skipping white space.
  if (!p || !*p)
  {
    SetError(TIXML_ERROR_DOCUMENT_EMPTY, 0, 0, TIXML_ENCODING_UNKNOWN);
    return 0;
  }
  // Note that, for a document, this needs to come
  // before the while space skip, so that parsing
  // starts from the pointer we are given.
  location.Clear();
  if (prevData)
  {
    location.row = prevData->cursor.row;
    location.col = prevData->cursor.col;
  }
  else
  {
    location.row = 0;
    location.col = 0;
  }
  TiXmlParsingData data(p, TabSize(), location.row, location.col);
  location = data.Cursor();
  if (encoding == TIXML_ENCODING_UNKNOWN)
  {
    // Check for the Microsoft UTF-8 lead bytes.
    const unsigned char* pU = (const unsigned char*)p;
    if (*(pU+0) && *(pU+0) == TIXML_UTF_LEAD_0
       && *(pU+1) && *(pU+1) == TIXML_UTF_LEAD_1
       && *(pU+2) && *(pU+2) == TIXML_UTF_LEAD_2)
    {
      encoding = TIXML_ENCODING_UTF8;
      useMicrosoftBOM = true;
    }
  }
    p = SkipWhiteSpace(p, encoding);
  if (!p)
  {
    SetError(TIXML_ERROR_DOCUMENT_EMPTY, 0, 0, TIXML_ENCODING_UNKNOWN);
    return 0;
  }
  while (p && *p)
  {
    TiXmlNode* node = Identify(p, encoding);
    if (node)
    {
      p = node->Parse(p, &data, encoding);
      LinkEndChild(node);
    }
    else
    {
      break;
    }
    // Did we get encoding info?
    if (encoding == TIXML_ENCODING_UNKNOWN
       && node->ToDeclaration())
    {
      TiXmlDeclaration* dec = node->ToDeclaration();
      const char* enc = dec->Encoding();
      assert(enc);
      if (*enc == 0)
        encoding = TIXML_ENCODING_UTF8;
      else if (StringEqual(enc, "UTF-8", true, TIXML_ENCODING_UNKNOWN))
        encoding = TIXML_ENCODING_UTF8;
      else if (StringEqual(enc, "UTF8", true, TIXML_ENCODING_UNKNOWN))
        encoding = TIXML_ENCODING_UTF8; // incorrect, but be nice
      else
        encoding = TIXML_ENCODING_LEGACY;
    }
    p = SkipWhiteSpace(p, encoding);
  }
  // Was this empty?
  if (!firstChild) {
    SetError(TIXML_ERROR_DOCUMENT_EMPTY, 0, 0, encoding);
    return 0;
  }
  // All is well.
  return p;
}
void dqm4hep::TiXmlDocument::Print () const [inline]
Write the document to standard out using formatted printing (`pretty print`).
Definition at line 1518 of file tinyxml.h.
References Print().
Referenced by Print(), and SaveFile().
{ Print(stdout, 0); }
void dqm4hep::TiXmlDocument::Print (FILE * cfile, int depth = 0) const [virtual]
Print this Document to a FILE stream.
Implements dqm4hep::TiXmlBase .
Definition at line 1103 of file tinyxml.cc.
References dqm4hep::TiXmlNode::FirstChild(), and dqm4hep::TiXmlNode::NextSibling().
{
  assert(cfile);
  for (const TiXmlNode* node=FirstChild(); node; node=node->NextSibling())
  {
    node->Print(cfile, depth);
    fprintf(cfile, "\n");
  }
}
const TiXmlElement* dqm4hep::TiXmlDocument::RootElement () const [inline]
Get the root element -- the only top level element -- of the document.
In well formed XML, there should only be one. TinyXml is tolerant of multiple elements at the document level.
Definition at line 1451 of file tinyxml.h.
References dqm4hep::TiXmlNode::FirstChildElement().
{ return FirstChildElement(); }
TiXmlElement* dqm4hep::TiXmlDocument::RootElement () [inline]
Definition at line 1452 of file tinyxml.h.
References dqm4hep::TiXmlNode::FirstChildElement().
{ return FirstChildElement(); }
bool dqm4hep::TiXmlDocument::SaveFile () const
Save a file using the current document value. Returns true if successful.
Definition at line 918 of file tinyxml.cc.
References dqm4hep::TiXmlNode::Value().
Referenced by SaveFile().
{
  return SaveFile(Value());
}
bool dqm4hep::TiXmlDocument::SaveFile (const char * filename) const
Save a file using the given filename. Returns true if successful.
Definition at line 1042 of file tinyxml.cc.
References SaveFile(), and dqm4hep::TiXmlFOpen().
{
  // The old c stuff lives on...
  FILE* fp = TiXmlFOpen(filename, "w");
  if (fp)
  {
    bool result = SaveFile(fp);
    fclose(fp);
    return result;
  }
  return false;
}
bool dqm4hep::TiXmlDocument::SaveFile (FILE * fp) const
Save a file using the given FILE*. Returns true if successful.
Definition at line 1056 of file tinyxml.cc.
References Print(), dqm4hep::TIXML_UTF_LEAD_0, dqm4hep::TIXML_UTF_LEAD_1, dqm4hep::TIXML_UTF_LEAD_2, and useMicrosoftBOM.
{
  if (useMicrosoftBOM)
  {
    const unsigned char TIXML_UTF_LEAD_0 = 0xefU;
    const unsigned char TIXML_UTF_LEAD_1 = 0xbbU;
    const unsigned char TIXML_UTF_LEAD_2 = 0xbfU;
    fputc(TIXML_UTF_LEAD_0, fp);
    fputc(TIXML_UTF_LEAD_1, fp);
    fputc(TIXML_UTF_LEAD_2, fp);
  }
  Print(fp, 0);
  return (ferror(fp) == 0);
}
bool dqm4hep::TiXmlDocument::SaveFile (const std::string & filename) const [inline]
< STL std::string version.
Definition at line 1435 of file tinyxml.h.
References SaveFile().
  {
    return SaveFile(filename.c_str());
  }
void dqm4hep::TiXmlDocument::SetError (int err, const char * errorLocation, TiXmlParsingData * prevData, TiXmlEncoding encoding)
Definition at line 801 of file tinyxmlparser.cc.
References dqm4hep::TiXmlCursor::Clear(), dqm4hep::TiXmlParsingData::Cursor(), error, errorDesc, errorId, errorLocation, dqm4hep::TiXmlBase::errorString, dqm4hep::TiXmlParsingData::Stamp(), and dqm4hep::TiXmlBase::TIXML_ERROR_STRING_COUNT.
Referenced by dqm4hep::TiXmlNode::InsertAfterChild(), dqm4hep::TiXmlNode::InsertBeforeChild(), dqm4hep::TiXmlNode::InsertEndChild(), dqm4hep::TiXmlNode::LinkEndChild(), LoadFile(), dqm4hep::TiXmlAttribute::Parse(), dqm4hep::TiXmlElement::Parse(), dqm4hep::TiXmlComment::Parse(), dqm4hep::TiXmlText::Parse(), dqm4hep::TiXmlDeclaration::Parse(), dqm4hep::TiXmlUnknown::Parse(), Parse(), dqm4hep::TiXmlElement::ReadValue(), and dqm4hep::TiXmlNode::ReplaceChild().
{
  // The first error in a chain is more accurate - don't set again!
  if (error)
    return;
  assert(err > 0 && err < TIXML_ERROR_STRING_COUNT);
  error = true;
  errorId = err;
  errorDesc = errorString[ errorId ];
  errorLocation.Clear();
  if (pError && data)
  {
    data->Stamp(pError, encoding);
    errorLocation = data->Cursor();
  }
}
void dqm4hep::TiXmlDocument::SetTabSize (int _tabsize) [inline]
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column.
It does not change the output or input in any way.
By calling this method, with a tab size greater than 0, the row and column of each node and attribute is stored when the file is loaded. Very useful for tracking the DOM back in to the source file.
The tab size is required for calculating the location of nodes. If not set, the default of 4 is used. The tabsize is set per document. Setting the tabsize to 0 disables row/column tracking.
Note that row and column tracking is not supported when using operator>>.
The tab size needs to be enabled before the parse or load. Correct usage:
TiXmlDocument doc;
doc.SetTabSize( 8 );
doc.Load( "myfile.xml" );
See also
Row, Column
Definition at line 1503 of file tinyxml.h.
References tabsize.
{ tabsize = _tabsize; }
virtual void dqm4hep::TiXmlDocument::StreamIn (std::istream * in, TIXML_STRING * tag) [protected], [virtual]
Implements dqm4hep::TiXmlNode .
int dqm4hep::TiXmlDocument::TabSize () const [inline]
Definition at line 1505 of file tinyxml.h.
References tabsize.
Referenced by Parse().
{ return tabsize; }
virtual const TiXmlDocument* dqm4hep::TiXmlDocument::ToDocument () const [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1531 of file tinyxml.h.
virtual TiXmlDocument* dqm4hep::TiXmlDocument::ToDocument () [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1532 of file tinyxml.h.
Member Data Documentation
bool dqm4hep::TiXmlDocument::error [private]
Definition at line 1548 of file tinyxml.h.
Referenced by ClearError(), CopyTo(), Error(), and SetError().
TIXML_STRING dqm4hep::TiXmlDocument::errorDesc [private]
Definition at line 1550 of file tinyxml.h.
Referenced by ClearError(), CopyTo(), ErrorDesc(), and SetError().
int dqm4hep::TiXmlDocument::errorId [private]
Definition at line 1549 of file tinyxml.h.
Referenced by ClearError(), CopyTo(), ErrorId(), and SetError().
TiXmlCursor dqm4hep::TiXmlDocument::errorLocation [private]
Definition at line 1552 of file tinyxml.h.
Referenced by ClearError(), CopyTo(), ErrorCol(), ErrorRow(), and SetError().
int dqm4hep::TiXmlDocument::tabsize [private]
Definition at line 1551 of file tinyxml.h.
Referenced by CopyTo(), SetTabSize(), TabSize(), and TiXmlDocument().
bool dqm4hep::TiXmlDocument::useMicrosoftBOM [private]
Definition at line 1553 of file tinyxml.h.
Referenced by CopyTo(), Parse(), SaveFile(), and TiXmlDocument().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc