TCLAP::DocBookOutput Class Reference
A class that generates DocBook output for usage() method for the given CmdLine and its Args.
#include <DocBookOutput.h>
Public Member Functions
virtual void usage (CmdLineInterface &c)
Prints the usage to stdout.
virtual void version (CmdLineInterface &c)
Prints the version to stdout.
virtual void failure (CmdLineInterface &c, ArgException &e)
Prints (to stderr) an error message, short usage Can be overridden to produce alternative behavior.
Protected Member Functions
void substituteSpecialChars (std::string &s, char r, std::string &x)
Substitutes the char r for string x in string s.
void removeChar (std::string &s, char r)
void basename (std::string &s)
void printShortArg (Arg *it)
void printLongArg (Arg *it)
Protected Attributes
char theDelimiter
Detailed Description
A class that generates DocBook output for usage() method for the given CmdLine and its Args.
Definition at line 43 of file DocBookOutput.h.
Member Function Documentation
void TCLAP::DocBookOutput::basename (std::string & s) [inline], [protected]
Definition at line 203 of file DocBookOutput.h.
Referenced by usage().
{
  size_t p = s.find_last_of('/');
  if (p != std::string::npos)
  {
    s.erase(0, p + 1);
  }
}
void TCLAP::DocBookOutput::failure (CmdLineInterface & c, ArgException & e) [inline], [virtual]
Prints (to stderr) an error message, short usage Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
e - The ArgException that caused the failure.
Implements TCLAP::CmdLineOutput .
Definition at line 174 of file DocBookOutput.h.
References TCLAP::ArgException::what().
{
  static_cast<void>(_cmd); // unused
  std::cout << e.what() << std::endl;
  throw ExitException(1);
}
void TCLAP::DocBookOutput::printLongArg (Arg * it) [inline], [protected]
Definition at line 252 of file DocBookOutput.h.
Referenced by usage().
{
  std::string lt = "&lt;";
  std::string gt = "&gt;";
  std::string desc = a->getDescription();
  substituteSpecialChars(desc,'<',lt);
  substituteSpecialChars(desc,'>',gt);
  std::cout << "<varlistentry>" << std::endl;
  if (!a->getFlag().empty())
  {
    std::cout << "<term>" << std::endl;
    std::cout << "<option>";
    std::cout << a->flagStartChar() << a->getFlag();
    std::cout << "</option>" << std::endl;
    std::cout << "</term>" << std::endl;
  }
  std::cout << "<term>" << std::endl;
  std::cout << "<option>";
  std::cout << a->nameStartString() << a->getName();
  if (a->isValueRequired())
  {
    std::string arg = a->shortID();
    removeChar(arg,'[');
    removeChar(arg,']');
    removeChar(arg,'<');
    removeChar(arg,'>');
    arg.erase(0, arg.find_last_of(theDelimiter) + 1);
    std::cout << theDelimiter;
    std::cout << "<replaceable>" << arg << "</replaceable>";
  }
  std::cout << "</option>" << std::endl;
  std::cout << "</term>" << std::endl;
  std::cout << "<listitem>" << std::endl;
  std::cout << "<para>" << std::endl;
  std::cout << desc << std::endl;
  std::cout << "</para>" << std::endl;
  std::cout << "</listitem>" << std::endl;
  std::cout << "</varlistentry>" << std::endl;
}
void TCLAP::DocBookOutput::printShortArg (Arg * it) [inline], [protected]
Definition at line 212 of file DocBookOutput.h.
References TCLAP::Arg::acceptsMultipleValues(), TCLAP::Arg::isRequired(), removeChar(), TCLAP::Arg::shortID(), and substituteSpecialChars().
Referenced by usage().
{
  std::string lt = "&lt;";
  std::string gt = "&gt;";
  std::string id = a->shortID();
  substituteSpecialChars(id,'<',lt);
  substituteSpecialChars(id,'>',gt);
  removeChar(id,'[');
  removeChar(id,']');
  
  std::string choice = "opt";
  if (a->isRequired())
    choice = "plain";
  std::cout << "<arg choice='" << choice << '\'';
  if (a->acceptsMultipleValues())
    std::cout << " rep='repeat'";
  std::cout << '>';
  if (!a->getFlag().empty())
    std::cout << a->flagStartChar() << a->getFlag();
  else
    std::cout << a->nameStartString() << a->getName();
  if (a->isValueRequired())
  {
    std::string arg = a->shortID();
    removeChar(arg,'[');
    removeChar(arg,']');
    removeChar(arg,'<');
    removeChar(arg,'>');
    arg.erase(0, arg.find_last_of(theDelimiter) + 1);
    std::cout << theDelimiter;
    std::cout << "<replaceable>" << arg << "</replaceable>";
  }
  std::cout << "</arg>" << std::endl;
}
void TCLAP::DocBookOutput::removeChar (std::string & s, char r) [inline], [protected]
Definition at line 194 of file DocBookOutput.h.
Referenced by printShortArg().
{
  size_t p;
  while ((p = s.find_first_of(r)) != std::string::npos)
  {
    s.erase(p,1);
  }
}
void TCLAP::DocBookOutput::substituteSpecialChars (std::string & s, char r, std::string & x) [inline], [protected]
Substitutes the char r for string x in string s.
Parameters
s - The string to operate on.
r - The char to replace.
x - What to replace r with.
Definition at line 182 of file DocBookOutput.h.
Referenced by printShortArg().
{
  size_t p;
  while ((p = s.find_first_of(r)) != std::string::npos)
  {
    s.erase(p,1);
    s.insert(p,x);
  }
}
void TCLAP::DocBookOutput::usage (CmdLineInterface & c) [inline], [virtual]
Prints the usage to stdout.
Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
Implements TCLAP::CmdLineOutput .
Definition at line 95 of file DocBookOutput.h.
References basename(), TCLAP::XorHandler::contains(), TCLAP::CmdLineInterface::getArgList(), TCLAP::CmdLineInterface::getDelimiter(), TCLAP::CmdLineInterface::getMessage(), TCLAP::CmdLineInterface::getProgramName(), TCLAP::CmdLineInterface::getVersion(), TCLAP::CmdLineInterface::getXorHandler(), TCLAP::XorHandler::getXorList(), printLongArg(), printShortArg(), and theDelimiter.
{
  std::list<Arg*> argList = _cmd.getArgList();
  std::string progName = _cmd.getProgramName();
  std::string xversion = _cmd.getVersion();
  theDelimiter = _cmd.getDelimiter();
  XorHandler xorHandler = _cmd.getXorHandler();
  std::vector< std::vector<Arg*> > xorList = xorHandler.getXorList();
  basename(progName);
  std::cout << "<?xml version='1.0'?>" << std::endl;
  std::cout << "<!DOCTYPE refentry PUBLIC \"-//OASIS//DTD DocBook XML V4.2//EN\"" << std::endl;
  std::cout << "\t\"http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd\">" << std::endl << std::endl;
  std::cout << "<refentry>" << std::endl;
  std::cout << "<refmeta>" << std::endl;
  std::cout << "<refentrytitle>" << progName << "</refentrytitle>" << std::endl;
  std::cout << "<manvolnum>1</manvolnum>" << std::endl;
  std::cout << "</refmeta>" << std::endl;
  std::cout << "<refnamediv>" << std::endl;
  std::cout << "<refname>" << progName << "</refname>" << std::endl;
  std::cout << "<refpurpose>" << _cmd.getMessage() << "</refpurpose>" << std::endl;
  std::cout << "</refnamediv>" << std::endl;
  std::cout << "<refsynopsisdiv>" << std::endl;
  std::cout << "<cmdsynopsis>" << std::endl;
  std::cout << "<command>" << progName << "</command>" << std::endl;
  // xor
  for (int i = 0; (unsigned int)i < xorList.size(); i++)
  {
    std::cout << "<group choice='req'>" << std::endl;
    for (ArgVectorIterator it = xorList[i].begin();
            it != xorList[i].end(); it++)
      printShortArg((*it));
    std::cout << "</group>" << std::endl;
  }
  
  // rest of args
  for (ArgListIterator it = argList.begin(); it != argList.end(); it++)
    if (!xorHandler.contains((*it)))
      printShortArg((*it));
  std::cout << "</cmdsynopsis>" << std::endl;
  std::cout << "</refsynopsisdiv>" << std::endl;
  std::cout << "<refsect1>" << std::endl;
  std::cout << "<title>Description</title>" << std::endl;
  std::cout << "<para>" << std::endl;
  std::cout << _cmd.getMessage() << std::endl;
  std::cout << "</para>" << std::endl;
  std::cout << "</refsect1>" << std::endl;
  std::cout << "<refsect1>" << std::endl;
  std::cout << "<title>Options</title>" << std::endl;
  std::cout << "<variablelist>" << std::endl;
  
  for (ArgListIterator it = argList.begin(); it != argList.end(); it++)
    printLongArg((*it));
  std::cout << "</variablelist>" << std::endl;
  std::cout << "</refsect1>" << std::endl;
  std::cout << "<refsect1>" << std::endl;
  std::cout << "<title>Version</title>" << std::endl;
  std::cout << "<para>" << std::endl;
  std::cout << xversion << std::endl;
  std::cout << "</para>" << std::endl;
  std::cout << "</refsect1>" << std::endl;
  
  std::cout << "</refentry>" << std::endl;
}
void TCLAP::DocBookOutput::version (CmdLineInterface & c) [inline], [virtual]
Prints the version to stdout.
Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
Implements TCLAP::CmdLineOutput .
Definition at line 90 of file DocBookOutput.h.
References TCLAP::CmdLineInterface::getVersion().
{
  std::cout << _cmd.getVersion() << std::endl;
}
Member Data Documentation
char TCLAP::DocBookOutput::theDelimiter [protected]
Definition at line 86 of file DocBookOutput.h.
Referenced by usage().
The documentation for this class was generated from the following file:
DocBookOutput.h