dqm4hep::DQMRunControlService Class Reference
DQMRunControlService class.
#include <DQMRunControlService.h>
Public Member Functions
DQMRunControlService ()
Constructor.
~DQMRunControlService ()
Destructor.
StatusCode start ()
Start the service.
StatusCode stop ()
Stop the service.
StatusCode pause ()
Pause the service until restart is called.
StatusCode restart ()
Restart the service.
DQMState getState () const
Get the service state.
bool isRunning () const
Whether the service is running.
StatusCode setRunControlName (const std::string &runControlName)
Set the run control name.
const std::string & getRunControlName () const
Get the run control name.
StatusCode startNewRun (unsigned int runNumber, const std::string &description=``, const std::string &detectorName=``)
Create a new run.
StatusCode startNewRun (DQMRun *pRun)
Create a new run.
StatusCode endCurrentRun ()
End the current run.
int getCurrentRunNumber () const
Get the current run number.
DQMState getRunState () const
Get the run state (running or not)
DQMRun * getCurrentRun () const
Get the current run.
Private Member Functions
void handleCurrentRunRpc (DimRpc *pRpc)
Private Attributes
int m_currentRunNumber
DQMState m_serviceState
DQMRunControl * m_pRunControl
std::string m_runControlName
DimService * m_pStartOfRunService
DimService * m_pEndOfRunService
DimRpc * m_pCurrentRunRpc
DQMDataStream m_dataStream
dqm_char * m_pRunBuffer
dqm_uint m_runBufferSize
Friends
class DQMCurrentRunRpc
Detailed Description
DQMRunControlService class.
Definition at line 72 of file DQMRunControlService.h.
Constructor & Destructor Documentation
dqm4hep::DQMRunControlService::DQMRunControlService ()
Constructor.
Definition at line 53 of file DQMRunControlService.cc.
References m_pRunControl.
                                           :
    m_currentRunNumber(-1),
    m_serviceState(STOPPED_STATE),
    m_pStartOfRunService(NULL),
    m_pEndOfRunService(NULL),
    m_pRunControl(NULL),
    m_pCurrentRunRpc(NULL),
    m_runControlName("DEFAULT"),
    m_dataStream(1024)
{
  m_pRunControl = new DQMRunControl();
}
dqm4hep::DQMRunControlService::~DQMRunControlService ()
Destructor.
Definition at line 68 of file DQMRunControlService.cc.
References endCurrentRun(), dqm4hep::DQMRunControl::getRunState(), isRunning(), m_pRunBuffer, m_pRunControl, and stop().
{
  if(isRunning())
  {
    if(RUNNING_STATE == m_pRunControl->getRunState())
      endCurrentRun();
    stop();
  }
  delete m_pRunControl;
  if(m_pRunBuffer)
    delete [] m_pRunBuffer;
}
Member Function Documentation
StatusCode dqm4hep::DQMRunControlService::endCurrentRun ()
End the current run.
Definition at line 194 of file DQMRunControlService.cc.
References dqm4hep::DQMRunControl::endCurrentRun(), dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), dqm4hep::DQMRunControl::getCurrentRun(), getRunState(), isRunning(), m_currentRunNumber, m_dataStream, m_pEndOfRunService, m_pRunControl, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, dqm4hep::DQMRun::serialize(), and dqm4hep::DQMRun::setEndTime().
Referenced by startNewRun(), and ~DQMRunControlService().
{
  if(!isRunning())
    return STATUS_CODE_NOT_INITIALIZED;
  if(RUNNING_STATE != getRunState())
    return STATUS_CODE_SUCCESS;
  m_currentRunNumber = -1;
  m_pRunControl->getCurrentRun()->setEndTime(time(0));
  m_dataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->getCurrentRun()->
      serialize(&m_dataStream));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->endCurrentRun());
  m_pEndOfRunService->updateService(m_dataStream.getBuffer(), m_dataStream.
      getBufferSize());
  return STATUS_CODE_SUCCESS;
}
DQMRun * dqm4hep::DQMRunControlService::getCurrentRun () const
Get the current run.
Return NULL if not running
Definition at line 265 of file DQMRunControlService.cc.
References dqm4hep::DQMRunControl::getCurrentRun(), and m_pRunControl.
{
  return m_pRunControl->getCurrentRun();
}
int dqm4hep::DQMRunControlService::getCurrentRunNumber () const
Get the current run number.
Definition at line 218 of file DQMRunControlService.cc.
References m_currentRunNumber.
{
  return m_currentRunNumber;
}
const std::string & dqm4hep::DQMRunControlService::getRunControlName () const
Get the run control name.
Definition at line 258 of file DQMRunControlService.cc.
References m_runControlName.
{
  return m_runControlName;
}
DQMState dqm4hep::DQMRunControlService::getRunState () const
Get the run state (running or not)
Definition at line 225 of file DQMRunControlService.cc.
References dqm4hep::DQMRunControl::getRunState(), and m_pRunControl.
Referenced by endCurrentRun(), and startNewRun().
{
  return m_pRunControl->getRunState();
}
DQMState dqm4hep::DQMRunControlService::getState () const
Get the service state.
See DQMState enum (DQM4HEP.h)
Definition at line 239 of file DQMRunControlService.cc.
References m_serviceState.
{
  return m_serviceState;
}
void dqm4hep::DQMRunControlService::handleCurrentRunRpc (DimRpc * pRpc) [private]
Definition at line 272 of file DQMRunControlService.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), dqm4hep::DQMRunControl::getCurrentRun(), isRunning(), dqm4hep::DQMRunControl::isRunning(), m_dataStream, m_pRunControl, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMRun::serialize(), THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by dqm4hep::DQMCurrentRunRpc::rpcHandler().
{
  if(!this->isRunning())
    return;
  std::cout << "Handling current run rpc !" << std::endl;
  try
  {
    // if running send the current run
    // else send back an empty run
    if(m_pRunControl->isRunning())
    {
      // stream
      m_dataStream.reset();
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->getCurrentRun()->
      serialize(&m_dataStream));
      // send back current run
      pRpc->setData((void *) m_dataStream.getBuffer() , m_dataStream.
      getBufferSize());
      // reset
      m_dataStream.reset();
    }
    else
    {
      DQMRun emptyRun;
      // stream
      m_dataStream.reset();
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, emptyRun.serialize(&m_dataStream));
      // send back empty run
      pRpc->setData((void *) m_dataStream.getBuffer() , m_dataStream.
      getBufferSize());
      // reset
      m_dataStream.reset();
    }
  }
  catch(StatusCodeException &exception)
  {
    std::cout << "Couldn't send back current run : " << exception.toString() << std::endl;
  }
}
bool dqm4hep::DQMRunControlService::isRunning () const
Whether the service is running.
Definition at line 232 of file DQMRunControlService.cc.
References m_serviceState.
Referenced by endCurrentRun(), handleCurrentRunRpc(), restart(), setRunControlName(), start(), startNewRun(), stop(), and ~DQMRunControlService().
{
  return (m_serviceState == RUNNING_STATE);
}
StatusCode dqm4hep::DQMRunControlService::pause ()
Pause the service until restart is called.
Definition at line 124 of file DQMRunControlService.cc.
References stop().
{
  return stop();
}
StatusCode dqm4hep::DQMRunControlService::restart ()
Restart the service.
Definition at line 131 of file DQMRunControlService.cc.
References isRunning(), RETURN_RESULT_IF, start(), and stop().
{
  if(isRunning())
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, stop());
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, start());
    return STATUS_CODE_SUCCESS;
  }
  else
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, start());
    return STATUS_CODE_SUCCESS;
  }
}
StatusCode dqm4hep::DQMRunControlService::setRunControlName (const std::string & runControlName)
Set the run control name.
Definition at line 246 of file DQMRunControlService.cc.
References isRunning(), and m_runControlName.
{
  if(isRunning())
    return STATUS_CODE_NOT_ALLOWED;
  m_runControlName = runControlName;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMRunControlService::start ()
Start the service.
Definition at line 86 of file DQMRunControlService.cc.
References DQMCurrentRunRpc, dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isRunning(), m_dataStream, m_pCurrentRunRpc, m_pEndOfRunService, m_pStartOfRunService, m_runControlName, and m_serviceState.
Referenced by restart().
{
  if(isRunning())
    return STATUS_CODE_ALREADY_INITIALIZED;
  std::string sorServiceName = "DQM4HEP/RunControl/" + m_runControlName + "/START_OF_RUN";
  std::string eorServiceName = "DQM4HEP/RunControl/" + m_runControlName + "/END_OF_RUN";
  std::string currentRunRpcName = "DQM4HEP/RunControl/" + m_runControlName + "/CURRENT_RUN";
  m_pStartOfRunService = new DimService(sorServiceName.c_str(), "C", (void*)
      m_dataStream.getBuffer(), m_dataStream.getBufferSize());
  m_pEndOfRunService = new DimService(eorServiceName.c_str(), "C", (void*)
      m_dataStream.getBuffer(), m_dataStream.getBufferSize());
  m_pCurrentRunRpc = new DQMCurrentRunRpc((char *) currentRunRpcName.c_str(), this);
  m_serviceState = RUNNING_STATE;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMRunControlService::startNewRun (unsigned int runNumber, const std::string & description = ``, const std::string & detectorName = ``)
Create a new run.
End the current run if there is one.
Definition at line 150 of file DQMRunControlService.cc.
References endCurrentRun(), dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), dqm4hep::DQMRunControl::getCurrentRun(), getRunState(), isRunning(), m_currentRunNumber, m_dataStream, m_pRunControl, m_pStartOfRunService, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, dqm4hep::DQMRun::serialize(), and dqm4hep::DQMRunControl::startNewRun().
{
  if(!isRunning())
    return STATUS_CODE_NOT_INITIALIZED;
  if(RUNNING_STATE == getRunState())
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, endCurrentRun());
  m_currentRunNumber = runNumber;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->startNewRun(
      m_currentRunNumber, description, detectorName));
  m_dataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->getCurrentRun()->
      serialize(&m_dataStream));
  m_pStartOfRunService->updateService(m_dataStream.getBuffer(), m_dataStream.
      getBufferSize());
  m_dataStream.reset();
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMRunControlService::startNewRun (DQMRun * pRun)
Create a new run.
End the current run if there is one.
Definition at line 172 of file DQMRunControlService.cc.
References endCurrentRun(), dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), dqm4hep::DQMRunControl::getCurrentRun(), dqm4hep::DQMRun::getRunNumber(), getRunState(), isRunning(), m_currentRunNumber, m_dataStream, m_pRunControl, m_pStartOfRunService, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, dqm4hep::DQMRun::serialize(), and dqm4hep::DQMRunControl::startNewRun().
{
  if(!isRunning())
    return STATUS_CODE_NOT_INITIALIZED;
  if(RUNNING_STATE == getRunState())
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, endCurrentRun());
  m_currentRunNumber = pRun->getRunNumber();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->startNewRun(pRun));
  m_dataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->getCurrentRun()->
      serialize(&m_dataStream));
  m_pStartOfRunService->updateService(m_dataStream.getBuffer(), m_dataStream.
      getBufferSize());
  m_dataStream.reset();
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMRunControlService::stop ()
Stop the service.
Remove all connections and clean up the service. Use pause to stop the service temporarily.
Definition at line 106 of file DQMRunControlService.cc.
References isRunning(), m_pEndOfRunService, m_pStartOfRunService, and m_serviceState.
Referenced by pause(), restart(), and ~DQMRunControlService().
{
  if(!isRunning())
    return STATUS_CODE_NOT_INITIALIZED;
  delete m_pStartOfRunService;
  delete m_pEndOfRunService;
  m_pStartOfRunService = NULL;
  m_pEndOfRunService = NULL;
  m_serviceState = STOPPED_STATE;
  return STATUS_CODE_SUCCESS;
}
Friends And Related Function Documentation
friend class DQMCurrentRunRpc [friend]
Definition at line 165 of file DQMRunControlService.h.
Referenced by start().
Member Data Documentation
int dqm4hep::DQMRunControlService::m_currentRunNumber [private]
Definition at line 150 of file DQMRunControlService.h.
Referenced by endCurrentRun(), getCurrentRunNumber(), and startNewRun().
DQMDataStream dqm4hep::DQMRunControlService::m_dataStream [private]
Definition at line 160 of file DQMRunControlService.h.
Referenced by endCurrentRun(), handleCurrentRunRpc(), start(), and startNewRun().
DimRpc* dqm4hep::DQMRunControlService::m_pCurrentRunRpc [private]
Definition at line 158 of file DQMRunControlService.h.
Referenced by start().
DimService* dqm4hep::DQMRunControlService::m_pEndOfRunService [private]
Definition at line 157 of file DQMRunControlService.h.
Referenced by endCurrentRun(), start(), and stop().
dqm_char* dqm4hep::DQMRunControlService::m_pRunBuffer [private]
Definition at line 162 of file DQMRunControlService.h.
Referenced by ~DQMRunControlService().
DQMRunControl* dqm4hep::DQMRunControlService::m_pRunControl [private]
Definition at line 152 of file DQMRunControlService.h.
Referenced by DQMRunControlService(), endCurrentRun(), getCurrentRun(), getRunState(), handleCurrentRunRpc(), startNewRun(), and ~DQMRunControlService().
DimService* dqm4hep::DQMRunControlService::m_pStartOfRunService [private]
Definition at line 156 of file DQMRunControlService.h.
Referenced by start(), startNewRun(), and stop().
dqm_uint dqm4hep::DQMRunControlService::m_runBufferSize [private]
Definition at line 163 of file DQMRunControlService.h.
std::string dqm4hep::DQMRunControlService::m_runControlName [private]
Definition at line 154 of file DQMRunControlService.h.
Referenced by getRunControlName(), setRunControlName(), and start().
DQMState dqm4hep::DQMRunControlService::m_serviceState [private]
Definition at line 151 of file DQMRunControlService.h.
Referenced by getState(), isRunning(), start(), and stop().
The documentation for this class was generated from the following files:
DQMRunControlService.h
DQMRunControlService.cc