dqm4hep::ELog Class Reference
#include <ELogInterface.h>
Public Member Functions
ELog ()
Default constructor.
ELog (const std::string &host, int port)
Constructor with host and port.
ELog (const std::string &host, int port, const std::string &userName, const std::string &password)
Constructor with host, port, user name and password.
void setHost (const std::string &host)
Set the host of the logbook.
void setPort (int port)
Set the port on which the entries will be logged.
void setUser (const std::string &user)
Set the user name for the logbook.
void setPassword (const std::string &password)
Set the password for the logbook.
void setLogbook (const std::string &logbook)
Set the logbook in which the entries will be published.
void useSSL (bool useSSL)
Whether to use ssl to log.
void setEncoding (Encoding encoding)
Set the logbook encoding.
void suppressEmailNotification (bool suppress)
Whether to suppres notification.
StatusCode addEntry (const std::string &name, const std::string &value)
Add an entry to the next logbook publication.
StatusCode addEntry (const LogbookEntry &entry)
Add an entry to the next logbook publication.
StatusCode addEntries (const LogbookEntryMap &entryMap)
Add entries to the next logbook publication.
void setMessage (const std::string &message)
Set the message that will goes in the next logged entry.
StatusCode log ()
Log in the logbook.
StatusCode log (const LogbookEntryMap &entryMap, const std::string &message=``)
Log in the logbook.
StatusCode log (const std::string &logbook)
Log in the logbook.
StatusCode log (const std::string &logbook, const LogbookEntryMap &entryMap, const std::string &message=``)
Log in the logbook.
void clear ()
Clear the ELog interface.
Private Types
enum Encoding { ELOG_CODE,
PLAIN,
HTML
 }
Encoding enumerator.
Private Member Functions
bool checkConsistency () const
int processELogCommand () const
Process the elog command.
Private Attributes
std::string m_eLogCommand
std::string m_host
int m_port
std::string m_userName
std::string m_password
std::string m_logbook
std::string m_message
LogbookEntryMap m_logbookEntryMap
Encoding m_encoding
bool m_useSSL
bool m_suppresssEmailNotification
Detailed Description
Definition at line 41 of file ELogInterface.h.
Member Enumeration Documentation
enum dqm4hep::ELog::Encoding [private]
Encoding enumerator.
Enumerator
ELOG_CODE
PLAIN
HTML
Definition at line 45 of file ELogInterface.h.
  {
    ELOG_CODE,
    PLAIN,
    HTML
  };
Constructor & Destructor Documentation
dqm4hep::ELog::ELog ()
Default constructor.
Default command is defined as DQM4HEP_ELOG_COMMAND in DQMCoreConfig.h
Definition at line 38 of file ELogInterface.cc.
           :
    m_eLogCommand(DQM4HEP_ELOG_EXECUTABLE),
    m_host(""),
    m_port(80),
    m_userName(""),
    m_password(""),
    m_logbook(""),
    m_encoding(ELog::PLAIN),
    m_useSSL(false),
    m_suppresssEmailNotification(false)
{
#ifndef DQM4HEP_USE_ELOG
  throw StatusCodeException(STATUS_COE_FAILURE);
#endif
}
dqm4hep::ELog::ELog (const std::string & host, int port)
Constructor with host and port.
Definition at line 56 of file ELogInterface.cc.
                                          :
    m_eLogCommand(DQM4HEP_ELOG_EXECUTABLE),
    m_host(host),
    m_port(port),
    m_userName(""),
    m_password(""),
    m_logbook(""),
    m_encoding(ELog::PLAIN),
    m_useSSL(false),
    m_suppresssEmailNotification(false)
{
#ifndef DQM4HEP_USE_ELOG
  throw StatusCodeException(STATUS_COE_FAILURE);
#endif
}
dqm4hep::ELog::ELog (const std::string & host, int port, const std::string & userName, const std::string & password)
Constructor with host, port, user name and password.
Definition at line 74 of file ELogInterface.cc.
                                                                                                :
    m_eLogCommand(DQM4HEP_ELOG_EXECUTABLE),
    m_host(host),
    m_port(port),
    m_userName(userName),
    m_password(password),
    m_logbook(""),
    m_encoding(ELog::PLAIN),
    m_useSSL(false),
    m_suppresssEmailNotification(false)
{
#ifndef DQM4HEP_USE_ELOG
  throw StatusCodeException(STATUS_COE_FAILURE);
#endif
}
Member Function Documentation
StatusCode dqm4hep::ELog::addEntries (const LogbookEntryMap & entryMap)
Add entries to the next logbook publication.
Definition at line 172 of file ELogInterface.cc.
References addEntry(), and RETURN_RESULT_IF.
Referenced by log().
{
  for(LogbookEntryMap::const_iterator iter = entryMap.begin(), endIter = entryMap.end() ;
      endIter != iter ; ++iter)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, addEntry(iter->first, iter->second));
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::ELog::addEntry (const std::string & name, const std::string & value)
Add an entry to the next logbook publication.
Definition at line 148 of file ELogInterface.cc.
References m_logbookEntryMap.
Referenced by addEntries().
{
  if(name.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  m_logbookEntryMap[name] = value;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::ELog::addEntry (const LogbookEntry & entry)
Add an entry to the next logbook publication.
Definition at line 160 of file ELogInterface.cc.
References m_logbookEntryMap.
{
  if(entry.first.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  m_logbookEntryMap[entry.first] = entry.second;
  return STATUS_CODE_SUCCESS;
}
bool dqm4hep::ELog::checkConsistency () const [private]
Definition at line 235 of file ELogInterface.cc.
References m_eLogCommand, m_host, m_logbook, m_logbookEntryMap, m_password, and m_userName.
Referenced by log().
{
  if(m_eLogCommand.empty()
  || m_host.empty()
  || m_userName.empty()
  || m_password.empty()
  || m_logbook.empty()
  || m_logbookEntryMap.empty())
    return false;
  if(m_logbookEntryMap.size() > 50)
    return false;
  return true;
}
void dqm4hep::ELog::clear ()
Clear the ELog interface.
Remove all previously added entries
Definition at line 284 of file ELogInterface.cc.
References m_logbookEntryMap.
Referenced by log().
{
  m_logbookEntryMap.clear();
}
StatusCode dqm4hep::ELog::log ()
Log in the logbook.
User must have set the logbook name, user name and password. Command not run if nothing was added with addEntry() functions
Definition at line 192 of file ELogInterface.cc.
References checkConsistency(), clear(), and processELogCommand().
Referenced by log().
{
  if(!checkConsistency())
    return STATUS_CODE_FAILURE;
  if(processELogCommand())
    return STATUS_CODE_FAILURE;
  clear();
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::ELog::log (const LogbookEntryMap & entryMap, const std::string & message = ``)
Log in the logbook.
User must have set the logbook name, user name and password. Command not run if the map is empty.
Definition at line 207 of file ELogInterface.cc.
References addEntries(), clear(), log(), RETURN_RESULT_IF, and setMessage().
{
  clear();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, addEntries(entryMap));
  setMessage(message);
  return this->log();
}
StatusCode dqm4hep::ELog::log (const std::string & logbook)
Log in the logbook.
User must have set the user name, password. Command not run if nothing was added with addEntry() functions
Definition at line 217 of file ELogInterface.cc.
References log(), and setLogbook().
{
  setLogbook(logbook);
  return this->log();
}
StatusCode dqm4hep::ELog::log (const std::string & logbook, const LogbookEntryMap & entryMap, const std::string & message = ``)
Log in the logbook.
User must have set the user name, password. Command not run if the map is empty.
Definition at line 225 of file ELogInterface.cc.
References addEntries(), log(), RETURN_RESULT_IF, setLogbook(), and setMessage().
{
  setLogbook(logbook);
  setMessage(message);
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, addEntries(entryMap));
  return this->log();
}
int dqm4hep::ELog::processELogCommand () const [private]
Process the elog command.
The user input has to be valid (see checkConsistency())
Definition at line 253 of file ELogInterface.cc.
References m_eLogCommand, m_encoding, m_host, m_logbook, m_logbookEntryMap, m_message, m_password, m_port, m_suppresssEmailNotification, m_userName, m_useSSL, and dqm4hep::MESSAGE.
Referenced by log().
{
  std::stringstream command;
  command << m_eLogCommand
      << " -h \"" << m_host << "\""
      << " -p " << m_port
      << " -u \"" << m_userName << "\" \"" << m_password << "\""
      << " -l \"" << m_logbook << "\"";
  for(LogbookEntryMap::const_iterator iter = m_logbookEntryMap.begin(), endIter =
      m_logbookEntryMap.end() ;
      endIter != iter ; ++iter)
  {
    command << " -a \"" << iter->first << "\"=\"" << iter->second << "\"";
  }
  command << " -n " << m_encoding;
  if(m_useSSL)
    command << " -s ";
  if(m_suppresssEmailNotification)
    command << " -x ";
  command << " \"" << m_message << "\"";
  streamlog_out(MESSAGE) << "Processing logbook command : '" << command.str() << "'" << std::endl;
  return system(command.str().c_str());
}
void dqm4hep::ELog::setEncoding (Encoding encoding)
Set the logbook encoding.
Default is ELog::PLAIN
Definition at line 134 of file ELogInterface.cc.
References m_encoding.
{
  m_encoding = encoding;
}
void dqm4hep::ELog::setHost (const std::string & host)
Set the host of the logbook.
Definition at line 92 of file ELogInterface.cc.
References m_host.
{
  m_host = host;
}
void dqm4hep::ELog::setLogbook (const std::string & logbook)
Set the logbook in which the entries will be published.
Definition at line 120 of file ELogInterface.cc.
References m_logbook.
Referenced by log().
{
  m_logbook = logbook;
}
void dqm4hep::ELog::setMessage (const std::string & message)
Set the message that will goes in the next logged entry.
Definition at line 185 of file ELogInterface.cc.
References m_message.
Referenced by log().
{
  m_message = message;
}
void dqm4hep::ELog::setPassword (const std::string & password)
Set the password for the logbook.
Definition at line 113 of file ELogInterface.cc.
References m_password.
{
  m_password = password;
}
void dqm4hep::ELog::setPort (int port)
Set the port on which the entries will be logged.
Definition at line 99 of file ELogInterface.cc.
References m_port.
{
  m_port = port;
}
void dqm4hep::ELog::setUser (const std::string & user)
Set the user name for the logbook.
Definition at line 106 of file ELogInterface.cc.
References m_userName.
{
  m_userName = user;
}
void dqm4hep::ELog::suppressEmailNotification (bool suppress)
Whether to suppres notification.
Default is false
Definition at line 141 of file ELogInterface.cc.
References m_suppresssEmailNotification.
{
  m_suppresssEmailNotification = suppress;
}
void dqm4hep::ELog::useSSL (bool useSSL)
Whether to use ssl to log.
Default is false
Definition at line 127 of file ELogInterface.cc.
References m_useSSL.
{
  m_useSSL = useSSL;
}
Member Data Documentation
std::string dqm4hep::ELog::m_eLogCommand [private]
Definition at line 170 of file ELogInterface.h.
Referenced by checkConsistency(), and processELogCommand().
Encoding dqm4hep::ELog::m_encoding [private]
Definition at line 178 of file ELogInterface.h.
Referenced by processELogCommand(), and setEncoding().
std::string dqm4hep::ELog::m_host [private]
Definition at line 171 of file ELogInterface.h.
Referenced by checkConsistency(), processELogCommand(), and setHost().
std::string dqm4hep::ELog::m_logbook [private]
Definition at line 175 of file ELogInterface.h.
Referenced by checkConsistency(), processELogCommand(), and setLogbook().
LogbookEntryMap dqm4hep::ELog::m_logbookEntryMap [private]
Definition at line 177 of file ELogInterface.h.
Referenced by addEntry(), checkConsistency(), clear(), and processELogCommand().
std::string dqm4hep::ELog::m_message [private]
Definition at line 176 of file ELogInterface.h.
Referenced by processELogCommand(), and setMessage().
std::string dqm4hep::ELog::m_password [private]
Definition at line 174 of file ELogInterface.h.
Referenced by checkConsistency(), processELogCommand(), and setPassword().
int dqm4hep::ELog::m_port [private]
Definition at line 172 of file ELogInterface.h.
Referenced by processELogCommand(), and setPort().
bool dqm4hep::ELog::m_suppresssEmailNotification [private]
Definition at line 180 of file ELogInterface.h.
Referenced by processELogCommand(), and suppressEmailNotification().
std::string dqm4hep::ELog::m_userName [private]
Definition at line 173 of file ELogInterface.h.
Referenced by checkConsistency(), processELogCommand(), and setUser().
bool dqm4hep::ELog::m_useSSL [private]
Definition at line 179 of file ELogInterface.h.
Referenced by processELogCommand(), and useSSL().
The documentation for this class was generated from the following files:
ELogInterface.h
ELogInterface.cc