dqm4hep::DQMDimRunControlClient Class Reference
DQMRunControlClient class.
#include <DQMDimRunControlClient.h>
Public Member Functions
DQMDimRunControlClient ()
Constructor.
~DQMDimRunControlClient ()
Destructor.
StatusCode connectToService ()
Connect to the service.
StatusCode disconnectFromService ()
Disconnect from the service.
bool isConnectedToService () const
Whether the client is connected to the service.
Private Member Functions
void infoHandler ()
Dim info handler.
void handleCurrentRunRpcInfo (DimRpcInfo *pRpcInfo)
Handle the dim current run rpc info.
Private Attributes
bool m_isConnected
Whether the client is connected to the server instance.
DQMDataStream m_dataStream
The data stream to deserialize the run at start of run.
DimInfo * m_pStartOfRunInfo
The dim start of run info.
DimInfo * m_pEndOfRunInfo
The dim end of run info.
DimRpcInfo * m_pCurrentRunRpcInfo
The dim current run rpc info.
Friends
class DQMCurrentRunRpcInfo
Additional Inherited Members
Detailed Description
DQMRunControlClient class.
Definition at line 69 of file DQMDimRunControlClient.h.
Constructor & Destructor Documentation
dqm4hep::DQMDimRunControlClient::DQMDimRunControlClient ()
Constructor.
Definition at line 59 of file DQMDimRunControlClient.cc.
                                               :
    DQMRunControlClient(),
    m_isConnected(false),
    m_pStartOfRunInfo(NULL),
    m_pEndOfRunInfo(NULL),
    m_dataStream(1024) // 1 ko to start
{
  /* nop */
}
dqm4hep::DQMDimRunControlClient::~DQMDimRunControlClient ()
Destructor.
Definition at line 71 of file DQMDimRunControlClient.cc.
References disconnectFromService(), and isConnectedToService().
{
  if(isConnectedToService())
    disconnectFromService();
}
Member Function Documentation
StatusCode dqm4hep::DQMDimRunControlClient::connectToService () [virtual]
Connect to the service.
Implements dqm4hep::DQMRunControlClient .
Definition at line 79 of file DQMDimRunControlClient.cc.
References DQMCurrentRunRpcInfo, dqm4hep::DQMRunControl::getRunControlName(), isConnectedToService(), m_isConnected, m_pCurrentRunRpcInfo, m_pEndOfRunInfo, and m_pStartOfRunInfo.
{
  if(isConnectedToService())
    return STATUS_CODE_SUCCESS;
  std::string sorServiceName = "DQM4HEP/RunControl/" + this->getRunControlName() + "/START_OF_RUN";
  std::string eorServiceName = "DQM4HEP/RunControl/" + this->getRunControlName() + "/END_OF_RUN";
  std::string currentRunRpcName = "DQM4HEP/RunControl/" + this->
      getRunControlName() + "/CURRENT_RUN";
  m_pStartOfRunInfo = new DimUpdatedInfo(sorServiceName.c_str(), (void*) NULL, 0, this);
  m_pEndOfRunInfo = new DimUpdatedInfo(eorServiceName.c_str(), (void*) NULL, 0, this);
  m_pCurrentRunRpcInfo = new DQMCurrentRunRpcInfo((char *) currentRunRpcName.c_str() , this);
  m_isConnected = true;
  sleep(1);
  int dummy = 0;
  m_pCurrentRunRpcInfo->setData(dummy);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDimRunControlClient::disconnectFromService () [virtual]
Disconnect from the service.
Implements dqm4hep::DQMRunControlClient .
Definition at line 103 of file DQMDimRunControlClient.cc.
References isConnectedToService(), m_isConnected, m_pCurrentRunRpcInfo, m_pEndOfRunInfo, and m_pStartOfRunInfo.
Referenced by ~DQMDimRunControlClient().
{
  if(!isConnectedToService())
    return STATUS_CODE_SUCCESS;
  delete m_pStartOfRunInfo; m_pStartOfRunInfo = NULL;
  delete m_pEndOfRunInfo; m_pEndOfRunInfo = NULL;
  delete m_pCurrentRunRpcInfo; m_pCurrentRunRpcInfo = NULL;
  m_isConnected = false;
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMDimRunControlClient::handleCurrentRunRpcInfo (DimRpcInfo * pRpcInfo) [private]
Handle the dim current run rpc info.
Definition at line 185 of file DQMDimRunControlClient.cc.
References dqm4hep::DQMRun::deserialize(), dqm4hep::DQMRun::getRunNumber(), isConnectedToService(), m_dataStream, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), dqm4hep::DQMRunControl::startNewRun(), and THROW_RESULT_IF.
Referenced by dqm4hep::DQMCurrentRunRpcInfo::rpcInfoHandler().
{
  if(! this->isConnectedToService())
    return;
  DQMRun *pRun = new DQMRun();
  try
  {
    dqm_char *pBuffer = static_cast<dqm_char*>(pRpcInfo->getData());
    dqm_uint bufferSize = pRpcInfo->getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pRun->deserialize(&m_dataStream));
    // run number is invalid, meaning not running
    if(pRun->getRunNumber() <= 0)
      throw StatusCodeException(STATUS_CODE_SUCCESS);
    // run is adopted here by the run control. No need to delete
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->startNewRun(pRun));
    // return avoids run deletion
    return;
  }
  catch(StatusCodeException &exception)
  {
  }
  if(pRun)
    delete pRun;
}
void dqm4hep::DQMDimRunControlClient::infoHandler () [private]
Dim info handler.
Definition at line 126 of file DQMDimRunControlClient.cc.
References dqm4hep::DQMRunControl::endCurrentRun(), isConnectedToService(), dqm4hep::DQMRunControl::isRunning(), m_dataStream, m_pEndOfRunInfo, m_pStartOfRunInfo, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), dqm4hep::DQMRunControl::startNewRun(), THROW_RESULT_IF, dqm4hep::StatusCodeException::toString(), and dqm4hep::WARNING.
{
  DimInfo *pCurrentDimInfo = getInfo();
  if(m_pStartOfRunInfo == pCurrentDimInfo)
  {
    if(this->isRunning() || !this->isConnectedToService())
      return;
    dqm_char *pBuffer = static_cast<dqm_char*>(pCurrentDimInfo->getData());
    dqm_uint bufferSize = pCurrentDimInfo->getSize();
    if(pBuffer == NULL || bufferSize == 0)
      return;
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    DQMRun *pRun = new DQMRun();
    try
    {
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pRun->deserialize(&m_dataStream));
      if(pRun->getRunNumber() < 0)
        throw StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
      // run is adopted here by the run control. No need to delete
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->startNewRun(pRun));
    }
    catch(StatusCodeException &exception)
    {
      if(pRun)
        delete pRun;
    }
  }
  else if(m_pEndOfRunInfo == pCurrentDimInfo)
  {
    if(!this->isRunning() || !this->isConnectedToService())
      return;
    try
    {
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->endCurrentRun());
    }
    catch(StatusCodeException &exception)
    {
      streamlog_out(WARNING) << "Couldn't stop the run (at stop) : " << exception.toString() << std::endl;
      return;
    }
  }
  else
  {
    streamlog_out(WARNING) << "Unknown info handled by the run control client : " << pCurrentDimInfo->
      getName() << std::endl;
  }
}
bool dqm4hep::DQMDimRunControlClient::isConnectedToService () const [virtual]
Whether the client is connected to the service.
Implements dqm4hep::DQMRunControlClient .
Definition at line 119 of file DQMDimRunControlClient.cc.
References m_isConnected.
Referenced by connectToService(), disconnectFromService(), handleCurrentRunRpcInfo(), infoHandler(), and ~DQMDimRunControlClient().
{
  return m_isConnected;
}
Friends And Related Function Documentation
friend class DQMCurrentRunRpcInfo [friend]
Definition at line 109 of file DQMDimRunControlClient.h.
Referenced by connectToService().
Member Data Documentation
DQMDataStream dqm4hep::DQMDimRunControlClient::m_dataStream [private]
The data stream to deserialize the run at start of run.
Definition at line 103 of file DQMDimRunControlClient.h.
Referenced by handleCurrentRunRpcInfo(), and infoHandler().
bool dqm4hep::DQMDimRunControlClient::m_isConnected [private]
Whether the client is connected to the server instance.
Definition at line 102 of file DQMDimRunControlClient.h.
Referenced by connectToService(), disconnectFromService(), and isConnectedToService().
DimRpcInfo* dqm4hep::DQMDimRunControlClient::m_pCurrentRunRpcInfo [private]
The dim current run rpc info.
Definition at line 107 of file DQMDimRunControlClient.h.
Referenced by connectToService(), and disconnectFromService().
DimInfo* dqm4hep::DQMDimRunControlClient::m_pEndOfRunInfo [private]
The dim end of run info.
Definition at line 106 of file DQMDimRunControlClient.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
DimInfo* dqm4hep::DQMDimRunControlClient::m_pStartOfRunInfo [private]
The dim start of run info.
Definition at line 105 of file DQMDimRunControlClient.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
The documentation for this class was generated from the following files:
DQMDimRunControlClient.h
DQMDimRunControlClient.cc