dqm4hep::DQMMonitorElementInfoList Class Reference
#include <DQMMessaging.h>
Public Member Functions
StatusCode serialize (DQMDataStream *const pDataStream) const
Serialize a monitor element publication and store it in the data stream.
StatusCode deserialize (DQMDataStream *const pDataStream)
De-serialize a monitor element publication from the data stream.
Detailed Description
Definition at line 81 of file DQMMessaging.h.
Member Function Documentation
StatusCode dqm4hep::DQMMonitorElementInfoList::deserialize (DQMDataStream *const pDataStream)
De-serialize a monitor element publication from the data stream.
Definition at line 139 of file DQMMessaging.cc.
References dqm4hep::DQMMonitorElementInfo::deserialize(), dqm4hep::DQMDataStream::read(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMMonitorElementCollector::handleAvailableListUpdate().
{
  clear();
  dqm_uint nMonitorElement = 0;
  RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->read(nMonitorElement));
  for(unsigned int i=0 ; i<nMonitorElement ; i++)
  {
    DQMMonitorElementInfo info;
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, info.deserialize(pDataStream));
    this->push_back(info);
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementInfoList::serialize (DQMDataStream *const pDataStream) const
Serialize a monitor element publication and store it in the data stream.
Definition at line 124 of file DQMMessaging.cc.
References RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
Referenced by dqm4hep::DQMMonitorElementSender::sendAvailableMonitorElementList().
{
  dqm_uint nMonitorElementInfo = size();
  RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->write(nMonitorElementInfo));
  for(unsigned int i=0 ; i<nMonitorElementInfo ; i++)
  {
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, this->at(i).serialize(pDataStream));
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMMessaging.h
DQMMessaging.cc