dqm4hep::DQMClusterStreamer Class Reference
DQMClusterStreamer class.
#include <DQMLCEventStreamer.h>
Public Member Functions
StatusCode serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize an Cluster.
StatusCode deserialize (EVENT::LCObject *&pLCObject, DQMDataStream *const pDataStream)
Deserialize a Cluster.
Detailed Description
DQMClusterStreamer class.
Definition at line 209 of file DQMLCEventStreamer.h.
Member Function Documentation
StatusCode dqm4hep::DQMClusterStreamer::deserialize (EVENT::LCObject *& pLCObject, DQMDataStream *const pDataStream)
Deserialize a Cluster.
The object is allocated in this function
Definition at line 1000 of file DQMLCEventStreamer.cc.
References dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMDataStream::read(), THROW_RESULT_IF, and dqm4hep::DQMDataStream::write().
{
  IMPL::ClusterImpl *pCluster = new IMPL::ClusterImpl();
  try
  {
    dqm_int type = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(type));
    std::bitset<32> clusterBitSet(type);
    for(dqm_uint i=0 ; i<clusterBitSet.size() ; i++)
      pCluster->setTypeBit(i, clusterBitSet[i]);
    dqm_float energy = 0.f;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(energy));
    pCluster->setEnergy(energy);
    dqm_float energyError = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(energyError));
    pCluster->setEnergyError(energyError);
    dqm_float *pPosition = 0;
    dqm_uint nPos = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(pPosition, nPos));
    if(nPos != 3)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    pCluster->setPosition(pPosition);
    delete [] pPosition;
    dqm_uint nPositionErrors = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nPositionErrors));
    EVENT::FloatVec positionErrors;
    for(dqm_uint i=0 ; i<nPositionErrors ; i++)
    {
      dqm_float positionError = 0;
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(positionError));
      positionErrors.push_back(positionError);
    }
    pCluster->setPositionError(positionErrors);
    dqm_float iTheta = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(iTheta));
    pCluster->setITheta(iTheta);
    dqm_float iPhi = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(iPhi));
    pCluster->setIPhi(iPhi);
    dqm_uint nDirectionErrors = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nDirectionErrors));
    EVENT::FloatVec directionErrors;
    for(dqm_uint i=0 ; i<nDirectionErrors ; i++)
    {
      dqm_float directionError = 0;
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(directionError));
      directionErrors.push_back(directionError);
    }
    pCluster->setDirectionError(directionErrors);
    dqm_uint nShapes = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nShapes));
    EVENT::FloatVec shapes;
    for(dqm_uint i=0 ; i<nShapes ; i++)
    {
      dqm_float shape = 0;
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(shape));
      shapes.push_back(shape);
    }
    pCluster->setShape(shapes);
    dqm_uint nParticleIDs = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nParticleIDs));
    DQMParticleIDStreamer particleIDStreamer;
    for(dqm_uint i=0 ; i<nParticleIDs ; i++)
    {
      EVENT::LCObject *pParticleID = 0;
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, particleIDStreamer.deserialize(pParticleID, pDataStream));
      pCluster->addParticleID(dynamic_cast<EVENT::ParticleID*>(pParticleID));
    }
    dqm_uint nSubdetectorEnergies = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nSubdetectorEnergies));
    for(dqm_uint i=0 ; i<nSubdetectorEnergies ; i++)
    {
      dqm_float subdetectorEnergy = 0;
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(subdetectorEnergy));
      pCluster->subdetectorEnergies().push_back(subdetectorEnergy);
    }
  }
  catch(StatusCodeException &exception)
  {
    delete pCluster;
    pCluster = 0;
    return exception.getStatusCode();
  }
  pLCObject = pCluster;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMClusterStreamer::serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize an Cluster.
Definition at line 923 of file DQMLCEventStreamer.cc.
References RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
{
  const EVENT::Cluster *const pCluster = dynamic_cast<const EVENT::Cluster *const>(pLCObject);
  if(NULL == pCluster)
    return STATUS_CODE_INVALID_PARAMETER;
  dqm_int type = pCluster->getType();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(type));
  dqm_float energy = pCluster->getEnergy();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(energy));
  dqm_float energyError = pCluster->getEnergyError();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(energyError));
  const dqm_float *pPosition = pCluster->getPosition();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(pPosition, 3));
  dqm_uint nPositionErrors = pCluster->getPositionError().size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nPositionErrors));
  for(dqm_uint i=0 ; i<nPositionErrors ; i++)
  {
    dqm_float positionError = pCluster->getPositionError().at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(positionError));
  }
  dqm_float iTheta = pCluster->getITheta();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(iTheta));
  dqm_float iPhi = pCluster->getIPhi();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(iPhi));
  dqm_uint nDirectionErrors = pCluster->getDirectionError().size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nDirectionErrors));
  for(dqm_uint i=0 ; i<nDirectionErrors ; i++)
  {
    dqm_float directionError = pCluster->getDirectionError().at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(directionError));
  }
  dqm_uint nShapes = pCluster->getShape().size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nShapes));
  for(dqm_uint i=0 ; i<nShapes ; i++)
  {
    dqm_float shape = pCluster->getShape().at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(shape));
  }
  dqm_uint nParticleIDs = pCluster->getParticleIDs().size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nParticleIDs));
  DQMParticleIDStreamer particleIDStreamer;
  for(dqm_uint i=0 ; i<nParticleIDs ; i++)
  {
    EVENT::ParticleID *pParticleID = pCluster->getParticleIDs().at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, particleIDStreamer.serialize(pParticleID, pDataStream));
  }
  dqm_uint nSubdetectorEnergies = pCluster->getSubdetectorEnergies().size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nSubdetectorEnergies));
  for(dqm_uint i=0 ; i<nSubdetectorEnergies ; i++)
  {
    dqm_float subdetectorEnergy = pCluster->getSubdetectorEnergies().at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(subdetectorEnergy));
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMLCEventStreamer.h
DQMLCEventStreamer.cc