dqm4hep::DQMVersion Class Reference
DQMVersion class.
#include <DQMVersion.h>
Public Member Functions
DQMVersion ()
Constructor.
DQMVersion (unsigned int major, unsigned int minor, unsigned int patch)
Constructor with version numbers.
~DQMVersion ()
Destructor.
unsigned int getMajor () const
Get the major version number.
unsigned int getMinor () const
Get the minor version number.
unsigned int getPatch () const
Get the patch version number.
void set (unsigned int major, unsigned int minor, unsigned int patch)
Set the complete version numbers.
const std::string & toString () const
Get the version to string.
DQMVersion & operator= (const DQMVersion &version)
Assignment operator.
StatusCode serialize (DQMDataStream *const pDataStream) const
Serialize the object and store the result in the data stream.
StatusCode deserialize (DQMDataStream *const pDataStream)
Deserialize the object from the data stream.
Private Attributes
unsigned int m_major
unsigned int m_minor
unsigned int m_patch
std::string m_versionString
Detailed Description
DQMVersion class.
Definition at line 41 of file DQMVersion.h.
Constructor & Destructor Documentation
dqm4hep::DQMVersion::DQMVersion ()
Constructor.
Definition at line 35 of file DQMVersion.cc.
                       :
    m_major(0),
    m_minor(0),
    m_patch(0)
{
  /* nop */
}
dqm4hep::DQMVersion::DQMVersion (unsigned int major, unsigned int minor, unsigned int patch)
Constructor with version numbers.
Definition at line 45 of file DQMVersion.cc.
References m_major, m_minor, m_patch, and set().
{
  set(m_major, m_minor, m_patch);
}
dqm4hep::DQMVersion::~DQMVersion ()
Destructor.
Definition at line 52 of file DQMVersion.cc.
{
  /* nop */
}
Member Function Documentation
StatusCode dqm4hep::DQMVersion::deserialize (DQMDataStream *const pDataStream) [virtual]
Deserialize the object from the data stream.
Implements dqm4hep::DQMStreamable .
Definition at line 188 of file DQMVersion.cc.
References dqm4hep::DQMDataStream::read(), RETURN_RESULT_IF, and set().
{
  dqm_uint major = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(major));
  dqm_uint minor = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(major));
  dqm_uint patch = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(major));
  set(major, minor, patch);
  return STATUS_CODE_SUCCESS;
}
unsigned int dqm4hep::DQMVersion::getMajor () const
Get the major version number.
Definition at line 59 of file DQMVersion.cc.
References m_major.
Referenced by dqm4hep::operator<(), dqm4hep::operator<=(), dqm4hep::operator==(), and serialize().
{
  return m_major;
}
unsigned int dqm4hep::DQMVersion::getMinor () const
Get the minor version number.
Definition at line 66 of file DQMVersion.cc.
References m_minor.
Referenced by dqm4hep::operator<(), dqm4hep::operator<=(), dqm4hep::operator==(), and serialize().
{
  return m_minor;
}
unsigned int dqm4hep::DQMVersion::getPatch () const
Get the patch version number.
Definition at line 73 of file DQMVersion.cc.
References m_patch.
Referenced by dqm4hep::operator<(), dqm4hep::operator<=(), dqm4hep::operator==(), and serialize().
{
  return m_patch;
}
DQMVersion & dqm4hep::DQMVersion::operator= (const DQMVersion & version)
Assignment operator.
Definition at line 99 of file DQMVersion.cc.
References m_major, m_minor, m_patch, m_versionString, and toString().
{
  m_major = version.m_major;
  m_minor = version.m_minor;
  m_patch = version.m_patch;
  m_versionString = version.toString();
  return *this;
}
StatusCode dqm4hep::DQMVersion::serialize (DQMDataStream *const pDataStream) const [virtual]
Serialize the object and store the result in the data stream.
Implements dqm4hep::DQMStreamable .
Definition at line 172 of file DQMVersion.cc.
References getMajor(), getMinor(), getPatch(), RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
{
  dqm_uint major = getMajor();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(major));
  dqm_uint minor = getMinor();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(minor));
  dqm_uint patch = getPatch();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(patch));
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMVersion::set (unsigned int major, unsigned int minor, unsigned int patch)
Set the complete version numbers.
Definition at line 80 of file DQMVersion.cc.
References m_major, m_minor, m_patch, and m_versionString.
Referenced by deserialize(), DQMVersion(), and dqm4hep::DQMModule::setVersion().
{
  m_major = major;
  m_minor = minor;
  m_patch = patch;
  std::stringstream ss;
  ss << m_major << "." << m_minor << "." << m_patch;
  m_versionString = ss.str();
}
const std::string & dqm4hep::DQMVersion::toString () const
Get the version to string.
Definition at line 92 of file DQMVersion.cc.
References m_versionString.
Referenced by dqm4hep::DQMArchiver::archive(), and operator=().
{
  return m_versionString;
}
Member Data Documentation
unsigned int dqm4hep::DQMVersion::m_major [private]
Definition at line 85 of file DQMVersion.h.
Referenced by DQMVersion(), getMajor(), operator=(), and set().
unsigned int dqm4hep::DQMVersion::m_minor [private]
Definition at line 86 of file DQMVersion.h.
Referenced by DQMVersion(), getMinor(), operator=(), and set().
unsigned int dqm4hep::DQMVersion::m_patch [private]
Definition at line 87 of file DQMVersion.h.
Referenced by DQMVersion(), getPatch(), operator=(), and set().
std::string dqm4hep::DQMVersion::m_versionString [private]
Definition at line 88 of file DQMVersion.h.
Referenced by operator=(), set(), and toString().
The documentation for this class was generated from the following files:
DQMVersion.h
DQMVersion.cc