dqm4hep::DQMModuleApplication Class Reference
DQMModuleApplication class.
#include <DQMModuleApplication.h>
Public Member Functions
DQMModuleApplication ()
Constructor.
virtual ~DQMModuleApplication ()
Destructor.
virtual StatusCode run ()=0
Run the application.
virtual StatusCode exit (int returnCode)
Stop the application.
virtual StatusCode readSettings (const std::string &settingsFile)=0
Read the settings from file.
virtual const std::string & getType () const =0
Get the application type.
virtual const std::string & getName () const =0
Get the application name.
DQMModule * getModule () const
Get the module for this application.
bool shouldStopApplication () const
Whether the module application should stop.
void setStopApplication (bool stopApplication)
Set the application stop flag.
StatusCode setModuleName (const std::string &name)
Set the module name in used.
StatusCode setModuleType (const std::string &type)
Set the module type to look for (before calling readSettings())
const std::string & getModuleName () const
Get the module name in used.
const std::string & getModuleType () const
Get the module type in used.
bool isInitialized () const
Whether the application is initialized.
StatusCode getReturnCode () const
Get the return code when application ends.
Protected Member Functions
void setInitialized (bool initialized)
Set the application has initialized.
DQMMonitorElementManager * getMonitorElementManager () const
Get the monitor element manager.
DQMMonitorElementSender * getMonitorElementSender () const
Get the monitor element sender.
StatusCode setModule (DQMModule *pModule)
Set the module in use in this application.
Protected Attributes
StatusCode m_returnCode
DQMModule * m_pModule
Private Attributes
bool m_isInitialized
bool m_shouldStop
std::string m_moduleType
std::string m_moduleName
DQMMonitorElementManager * m_pMonitorElementManager
DQMMonitorElementSender * m_pMonitorElementSender
Friends
class DQMArchiver
class DQMModuleApi
Detailed Description
DQMModuleApplication class.
Definition at line 47 of file DQMModuleApplication.h.
Constructor & Destructor Documentation
dqm4hep::DQMModuleApplication::DQMModuleApplication ()
Constructor.
Definition at line 36 of file DQMModuleApplication.cc.
References m_pMonitorElementManager, and m_pMonitorElementSender.
                                           :
    m_isInitialized(false),
    m_shouldStop(false),
    m_pModule(NULL),
    m_pMonitorElementManager(NULL),
    m_pMonitorElementSender(NULL)
{
  m_pMonitorElementManager = new DQMMonitorElementManager();
  m_pMonitorElementSender = new DQMMonitorElementSender(this);
}
dqm4hep::DQMModuleApplication::~DQMModuleApplication () [virtual]
Destructor.
Definition at line 49 of file DQMModuleApplication.cc.
References m_pModule, m_pMonitorElementManager, and m_pMonitorElementSender.
{
  delete m_pMonitorElementManager;
  delete m_pMonitorElementSender;
  if(m_pModule)
    delete m_pModule;
}
Member Function Documentation
StatusCode dqm4hep::DQMModuleApplication::exit (int returnCode) [virtual]
Stop the application.
Implements dqm4hep::DQMApplication .
Definition at line 60 of file DQMModuleApplication.cc.
References isInitialized(), m_returnCode, dqm4hep::MESSAGE, dqm4hep::NUMBER_OF_STATUS_CODES, and setStopApplication().
{
  streamlog_out(MESSAGE) << "Exiting application ..." << std::endl;
  if(!this->isInitialized())
    return STATUS_CODE_NOT_INITIALIZED;
  if(returnCode >= 0 && returnCode < NUMBER_OF_STATUS_CODES)
    m_returnCode = static_cast< StatusCode >(returnCode);
  else
    m_returnCode = STATUS_CODE_FAILURE;
  this->setStopApplication(true);
  streamlog_out(MESSAGE) << "Exiting application ... OK" << std::endl;
  return m_returnCode;
}
DQMModule * dqm4hep::DQMModuleApplication::getModule () const
Get the module for this application.
Definition at line 81 of file DQMModuleApplication.cc.
References m_pModule.
Referenced by dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMAnalysisModuleApplication::configureModule(), dqm4hep::DQMStandaloneModuleApplication::onCycleStarted(), dqm4hep::DQMAnalysisModuleApplication::onCycleStarted(), dqm4hep::DQMStandaloneModuleApplication::onCycleStopped(), dqm4hep::DQMAnalysisModuleApplication::onCycleStopped(), dqm4hep::DQMStandaloneModuleApplication::readSettings(), dqm4hep::DQMAnalysisModuleApplication::readSettings(), dqm4hep::DQMStandaloneModuleApplication::run(), dqm4hep::DQMAnalysisModuleApplication::run(), dqm4hep::DQMMonitorElementSender::sendAvailableMonitorElementList(), and dqm4hep::DQMMonitorElementSender::sendMonitorElements().
{
  return m_pModule;
}
const std::string & dqm4hep::DQMModuleApplication::getModuleName () const
Get the module name in used.
Definition at line 129 of file DQMModuleApplication.cc.
References dqm4hep::DQMModule::getName(), m_moduleName, and m_pModule.
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureModule(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  if(m_pModule)
    return m_pModule->getName();
  return m_moduleName;
}
const std::string & dqm4hep::DQMModuleApplication::getModuleType () const
Get the module type in used.
Definition at line 139 of file DQMModuleApplication.cc.
References m_moduleType.
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureModule(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  return m_moduleType;
}
DQMMonitorElementManager * dqm4hep::DQMModuleApplication::getMonitorElementManager () const [protected]
Get the monitor element manager.
Definition at line 167 of file DQMModuleApplication.cc.
References m_pMonitorElementManager.
Referenced by dqm4hep::DQMModuleApi::addQualityTest(), dqm4hep::DQMArchiver::archive(), dqm4hep::DQMModuleApi::bookCharHistogram1D(), dqm4hep::DQMModuleApi::bookCharHistogram2D(), dqm4hep::DQMModuleApi::bookFloat(), dqm4hep::DQMModuleApi::bookInt(), dqm4hep::DQMModuleApi::bookIntHistogram1D(), dqm4hep::DQMModuleApi::bookIntHistogram2D(), dqm4hep::DQMModuleApi::bookMonitorElement(), dqm4hep::DQMModuleApi::bookObject(), dqm4hep::DQMModuleApi::bookProfile1D(), dqm4hep::DQMModuleApi::bookProfile2D(), dqm4hep::DQMModuleApi::bookRealHistogram1D(), dqm4hep::DQMModuleApi::bookRealHistogram2D(), dqm4hep::DQMModuleApi::bookShort(), dqm4hep::DQMModuleApi::bookShortHistogram1D(), dqm4hep::DQMModuleApi::bookShortHistogram2D(), dqm4hep::DQMModuleApi::bookString(), dqm4hep::DQMModuleApi::cd(), dqm4hep::DQMModuleApi::createQualityTest(), dqm4hep::DQMModuleApi::deleteMonitorElement(), dqm4hep::DQMModuleApi::getAllMonitorElements(), dqm4hep::DQMModuleApi::getMonitorElement(), dqm4hep::DQMModuleApi::goUp(), dqm4hep::DQMModuleApi::ls(), dqm4hep::DQMModuleApi::mkdir(), dqm4hep::DQMModuleApi::pwd(), dqm4hep::DQMModuleApi::registerQualityTestFactory(), dqm4hep::DQMModuleApi::resetMonitorElements(), dqm4hep::DQMModuleApi::rmdir(), dqm4hep::DQMAnalysisModuleApplication::run(), dqm4hep::DQMModuleApi::runQualityTest(), and dqm4hep::DQMModuleApi::runQualityTests().
{
  return m_pMonitorElementManager;
}
DQMMonitorElementSender * dqm4hep::DQMModuleApplication::getMonitorElementSender () const [protected]
Get the monitor element sender.
Definition at line 174 of file DQMModuleApplication.cc.
References m_pMonitorElementSender.
Referenced by dqm4hep::DQMModuleApi::bookCharHistogram1D(), dqm4hep::DQMModuleApi::bookCharHistogram2D(), dqm4hep::DQMModuleApi::bookFloat(), dqm4hep::DQMModuleApi::bookInt(), dqm4hep::DQMModuleApi::bookIntHistogram1D(), dqm4hep::DQMModuleApi::bookIntHistogram2D(), dqm4hep::DQMModuleApi::bookMonitorElement(), dqm4hep::DQMModuleApi::bookObject(), dqm4hep::DQMModuleApi::bookProfile1D(), dqm4hep::DQMModuleApi::bookProfile2D(), dqm4hep::DQMModuleApi::bookRealHistogram1D(), dqm4hep::DQMModuleApi::bookRealHistogram2D(), dqm4hep::DQMModuleApi::bookShort(), dqm4hep::DQMModuleApi::bookShortHistogram1D(), dqm4hep::DQMModuleApi::bookShortHistogram2D(), dqm4hep::DQMModuleApi::bookString(), dqm4hep::DQMAnalysisModuleApplication::configureNetwork(), dqm4hep::DQMModuleApi::deleteMonitorElement(), dqm4hep::DQMStandaloneModuleApplication::readSettings(), dqm4hep::DQMStandaloneModuleApplication::run(), dqm4hep::DQMAnalysisModuleApplication::run(), dqm4hep::DQMAnalysisModuleApplication::startServices(), and dqm4hep::DQMAnalysisModuleApplication::stopServices().
{
  return m_pMonitorElementSender;
}
virtual const std::string& dqm4hep::DQMModuleApplication::getName () const [pure virtual]
Get the application name.
Implements dqm4hep::DQMApplication .
Implemented in dqm4hep::DQMAnalysisModuleApplication , and dqm4hep::DQMStandaloneModuleApplication .
StatusCode dqm4hep::DQMModuleApplication::getReturnCode () const
Get the return code when application ends.
Definition at line 153 of file DQMModuleApplication.cc.
References m_returnCode.
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
{
  return m_returnCode;
}
virtual const std::string& dqm4hep::DQMModuleApplication::getType () const [pure virtual]
Get the application type.
Implements dqm4hep::DQMApplication .
Implemented in dqm4hep::DQMAnalysisModuleApplication , and dqm4hep::DQMStandaloneModuleApplication .
bool dqm4hep::DQMModuleApplication::isInitialized () const
Whether the application is initialized.
Definition at line 146 of file DQMModuleApplication.cc.
References m_isInitialized.
Referenced by exit(), dqm4hep::DQMStandaloneModuleApplication::readSettings(), dqm4hep::DQMAnalysisModuleApplication::readSettings(), dqm4hep::DQMStandaloneModuleApplication::run(), dqm4hep::DQMAnalysisModuleApplication::run(), setModuleName(), and setModuleType().
{
  return m_isInitialized;
}
virtual StatusCode dqm4hep::DQMModuleApplication::readSettings (const std::string & settingsFile) [pure virtual]
Read the settings from file.
Implements dqm4hep::DQMApplication .
Implemented in dqm4hep::DQMAnalysisModuleApplication , and dqm4hep::DQMStandaloneModuleApplication .
virtual StatusCode dqm4hep::DQMModuleApplication::run () [pure virtual]
Run the application.
Implements dqm4hep::DQMApplication .
Implemented in dqm4hep::DQMAnalysisModuleApplication , and dqm4hep::DQMStandaloneModuleApplication .
void dqm4hep::DQMModuleApplication::setInitialized (bool initialized) [protected]
Set the application has initialized.
Definition at line 160 of file DQMModuleApplication.cc.
References m_isInitialized.
Referenced by dqm4hep::DQMStandaloneModuleApplication::readSettings(), and dqm4hep::DQMAnalysisModuleApplication::readSettings().
{
  m_isInitialized = initialized;
}
StatusCode dqm4hep::DQMModuleApplication::setModule (DQMModule * pModule) [protected]
Set the module in use in this application.
Definition at line 181 of file DQMModuleApplication.cc.
References m_moduleName, m_pModule, dqm4hep::DQMModule::setModuleApplication(), and dqm4hep::DQMModule::setName().
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureModule(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  if(!pModule)
    return STATUS_CODE_INVALID_PTR;
  m_pModule = pModule;
  m_pModule->setName(m_moduleName);
  m_pModule->setModuleApplication(this);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApplication::setModuleName (const std::string & name)
Set the module name in used.
Definition at line 102 of file DQMModuleApplication.cc.
References isInitialized(), m_moduleName, m_pModule, and dqm4hep::DQMModule::setName().
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureModule(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  if(this->isInitialized())
    return STATUS_CODE_ALREADY_INITIALIZED;
  m_moduleName = name;
  if(m_pModule)
    m_pModule->setName(name);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApplication::setModuleType (const std::string & type)
Set the module type to look for (before calling readSettings())
Definition at line 117 of file DQMModuleApplication.cc.
References isInitialized(), and m_moduleType.
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureModule(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  if(this->isInitialized())
    return STATUS_CODE_ALREADY_INITIALIZED;
  m_moduleType = type;
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMModuleApplication::setStopApplication (bool stopApplication)
Set the application stop flag.
Definition at line 95 of file DQMModuleApplication.cc.
References m_shouldStop.
Referenced by exit().
{
  m_shouldStop = stopApplication;
}
bool dqm4hep::DQMModuleApplication::shouldStopApplication () const
Whether the module application should stop.
Definition at line 88 of file DQMModuleApplication.cc.
References m_shouldStop.
Referenced by dqm4hep::DQMStandaloneModuleApplication::run(), and dqm4hep::DQMAnalysisModuleApplication::run().
{
  return m_shouldStop;
}
Friends And Related Function Documentation
friend class DQMArchiver [friend]
Definition at line 49 of file DQMModuleApplication.h.
Referenced by dqm4hep::DQMAnalysisModuleApplication::DQMAnalysisModuleApplication(), and dqm4hep::DQMStandaloneModuleApplication::DQMStandaloneModuleApplication().
friend class DQMModuleApi [friend]
Definition at line 50 of file DQMModuleApplication.h.
Member Data Documentation
bool dqm4hep::DQMModuleApplication::m_isInitialized [private]
Definition at line 138 of file DQMModuleApplication.h.
Referenced by isInitialized(), and setInitialized().
std::string dqm4hep::DQMModuleApplication::m_moduleName [private]
Definition at line 141 of file DQMModuleApplication.h.
Referenced by getModuleName(), dqm4hep::DQMStandaloneModuleApplication::Settings::print(), setModule(), and setModuleName().
std::string dqm4hep::DQMModuleApplication::m_moduleType [private]
Definition at line 140 of file DQMModuleApplication.h.
Referenced by getModuleType(), dqm4hep::DQMStandaloneModuleApplication::Settings::print(), and setModuleType().
DQMModule* dqm4hep::DQMModuleApplication::m_pModule [protected]
Definition at line 135 of file DQMModuleApplication.h.
Referenced by getModule(), getModuleName(), setModule(), setModuleName(), and ~DQMModuleApplication().
DQMMonitorElementManager* dqm4hep::DQMModuleApplication::m_pMonitorElementManager [private]
Definition at line 143 of file DQMModuleApplication.h.
Referenced by DQMModuleApplication(), getMonitorElementManager(), and ~DQMModuleApplication().
DQMMonitorElementSender* dqm4hep::DQMModuleApplication::m_pMonitorElementSender [private]
Definition at line 144 of file DQMModuleApplication.h.
Referenced by DQMModuleApplication(), getMonitorElementSender(), and ~DQMModuleApplication().
StatusCode dqm4hep::DQMModuleApplication::m_returnCode [protected]
Definition at line 134 of file DQMModuleApplication.h.
Referenced by exit(), and getReturnCode().
bool dqm4hep::DQMModuleApplication::m_shouldStop [private]
Definition at line 139 of file DQMModuleApplication.h.
Referenced by setStopApplication(), and shouldStopApplication().
The documentation for this class was generated from the following files:
DQMModuleApplication.h
DQMModuleApplication.cc