dqm4hep::DQMChi2FitFunctionTest Class Reference
DQMChi2FitFunctionTest class.
#include <DQMQualityTest.h>
Classes
class Factory
Factory class.
Public Member Functions
DQMChi2FitFunctionTest (const std::string &name)
Constructor with name.
virtual ~DQMChi2FitFunctionTest ()
Destructor.
virtual StatusCode readSettings (const TiXmlHandle xmlHandle)
Read the settings from the xml handle.
virtual StatusCode init ()
Initialize the quality test.
virtual StatusCode run (DQMMonitorElement *pMonitorElement)
Runs a quality test on the given monitor element.
virtual bool canRun (DQMMonitorElement *pMonitorElement) const
Whether the quality test can be run on the monitor element.
Protected Attributes
std::string m_formula
std::vector< double > m_inputParameterList
unsigned int m_functionNParameters
double m_functionXMin
double m_functionXMax
Additional Inherited Members
Detailed Description
DQMChi2FitFunctionTest class.
Definition at line 244 of file DQMQualityTest.h.
Constructor & Destructor Documentation
dqm4hep::DQMChi2FitFunctionTest::DQMChi2FitFunctionTest (const std::string & name)
Constructor with name.
Definition at line 320 of file DQMQualityTest.cc.
                                                                    :
  DQMQualityTest(name),
  m_functionXMin(0.f),
  m_functionXMax(1.f),
  m_functionNParameters(0)
{
  /* nop */
}
dqm4hep::DQMChi2FitFunctionTest::~DQMChi2FitFunctionTest () [virtual]
Destructor.
Definition at line 331 of file DQMQualityTest.cc.
{
  /* nop */
}
Member Function Documentation
bool dqm4hep::DQMChi2FitFunctionTest::canRun (DQMMonitorElement * pMonitorElement) const [virtual]
Whether the quality test can be run on the monitor element.
Implements dqm4hep::DQMQualityTest .
Definition at line 432 of file DQMQualityTest.cc.
References dqm4hep::DQMMonitorElement::get(), and dqm4hep::DQMMonitorElement::getType().
{
  if(NULL == pMonitorElement)
    return false;
  DQMMonitorElementType type = pMonitorElement->getType();
  TH1 *pHistogram = pMonitorElement->get<TH1>();
  // asking for a histo 1D
  if(type < INT_HISTOGRAM_1D_ELEMENT_TYPE || type > CHAR_HISTOGRAM_1D_ELEMENT_TYPE)
    return false;
  if(NULL == pHistogram)
    return false;
  return true;
}
StatusCode dqm4hep::DQMChi2FitFunctionTest::init () [virtual]
Initialize the quality test.
Implements dqm4hep::DQMQualityTest .
Definition at line 363 of file DQMQualityTest.cc.
{
  /* nop */
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMChi2FitFunctionTest::readSettings (const TiXmlHandle xmlHandle) [virtual]
Read the settings from the xml handle.
Implements dqm4hep::DQMQualityTest .
Definition at line 338 of file DQMQualityTest.cc.
References m_formula, m_functionNParameters, m_functionXMax, m_functionXMin, m_inputParameterList, dqm4hep::DQMXmlHelper::readValue(), dqm4hep::DQMXmlHelper::readVectorOfValues(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
      "Formula", m_formula));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readVectorOfValues(xmlHandle,
      "InputParameterList", m_inputParameterList));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
      "FunctionNParameters", m_functionNParameters));
  if(!m_inputParameterList.empty() && m_inputParameterList.size() !=
      m_functionNParameters)
    return STATUS_CODE_INVALID_PARAMETER;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
      "FunctionXMin", m_functionXMin));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
      "FunctionXMax", m_functionXMax));
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMChi2FitFunctionTest::run (DQMMonitorElement * pMonitorElement) [virtual]
Runs a quality test on the given monitor element.
Implements dqm4hep::DQMQualityTest .
Definition at line 371 of file DQMQualityTest.cc.
References dqm4hep::DQMMonitorElement::get(), dqm4hep::DQMMonitorElement::getName(), dqm4hep::DQMQualityTest::getName(), m_formula, m_functionNParameters, m_functionXMax, m_functionXMin, m_inputParameterList, dqm4hep::DQMQualityTest::m_isSuccessful, dqm4hep::DQMQualityTest::m_message, dqm4hep::DQMQualityTest::m_quality, dqm4hep::DQM4HEP::scaleToQuality(), and dqm4hep::DQM4HEP::typeToString().
{
  m_isSuccessful = false;
  m_quality = NO_QUALITY;
  m_message = "";
  TH1 *pHistogram = pMonitorElement->get<TH1>();
  std::string functionName = "DQMChi2FitFunctionTest_"+ getName() +"_fitFunction";
  // we need to remove the function from the TH1
  // since when TH1::Fit is called, the function
  // is stored in the TH1. The function is removed and deleted
  // since we don't know if the formula is the same as the user provides
  TF1 *pFitFunction = pHistogram->GetFunction(functionName.c_str());
  if(pFitFunction)
  {
    pHistogram->RecursiveRemove(pFitFunction);
    delete pFitFunction;
    pFitFunction = NULL;
  }
  // declare the fit function and fill the parameter list
  pFitFunction = new TF1(functionName.c_str(), m_formula.c_str(), m_functionXMin,
      m_functionXMax);//, m_functionNParameters);
  // set the parameters depending on if an
  // input has been provided or not by the user
  for(unsigned int p=0 ; p<m_functionNParameters ; p++)
    pFitFunction->SetParameter(p, m_inputParameterList.empty() ? 0 :
      m_inputParameterList.at(p));
  // Q for quiet
  // N for no draw
  int status = pHistogram->Fit(pFitFunction, "QN", "", m_functionXMin,
      m_functionXMax);
  if(status != 0)
  {
    m_message = "Try to fit function '"+ m_formula + "' with histogram '" + pMonitorElement->getName() + "
      '. " +
        "Fit failed and returned status " + DQM4HEP::typeToString(status);
    return STATUS_CODE_SUCCESS;
  }
  double chi2 = pFitFunction->GetChisquare();
  double proba = TMath::Prob(chi2, m_inputParameterList.size());
  m_isSuccessful = true;
  m_quality = DQM4HEP::scaleToQuality(proba);
  m_message = "Function '"+ m_formula +"' fitted on histogram '" + pMonitorElement->getName() + "' ends
       with the following output :\n" +
      "Chi2 = " + DQM4HEP::typeToString(chi2) + "\n" +
      "Excess probability = " + DQM4HEP::typeToString(proba) + "\n" +
      "Output parameters : \n";
  for(unsigned int p=0 ; p<m_functionNParameters ; p++)
    m_message += (" p" + DQM4HEP::typeToString(p) + " = " +
      DQM4HEP::typeToString(pFitFunction->GetParameter(p)) + "\n");
  return STATUS_CODE_SUCCESS;
}
Member Data Documentation
std::string dqm4hep::DQMChi2FitFunctionTest::m_formula [protected]
Definition at line 283 of file DQMQualityTest.h.
Referenced by readSettings(), and run().
unsigned int dqm4hep::DQMChi2FitFunctionTest::m_functionNParameters [protected]
Definition at line 285 of file DQMQualityTest.h.
Referenced by readSettings(), and run().
double dqm4hep::DQMChi2FitFunctionTest::m_functionXMax [protected]
Definition at line 287 of file DQMQualityTest.h.
Referenced by readSettings(), and run().
double dqm4hep::DQMChi2FitFunctionTest::m_functionXMin [protected]
Definition at line 286 of file DQMQualityTest.h.
Referenced by readSettings(), and run().
std::vector<double> dqm4hep::DQMChi2FitFunctionTest::m_inputParameterList [protected]
Definition at line 284 of file DQMQualityTest.h.
Referenced by readSettings(), and run().
The documentation for this class was generated from the following files:
DQMQualityTest.h
DQMQualityTest.cc