dqm4hep::DQMEventStreamer Class Reference
DQMEventStreamer class.
#include <DQMEventStreamer.h>
Public Member Functions
virtual ~DQMEventStreamer ()
Destructor.
virtual StatusCode serialize (const DQMEvent *const pObject, DQMDataStream *const pDataStream)=0
Serialize a DQMEvent object and store it in the data stream.
virtual StatusCode deserialize (DQMEvent *&pObject, DQMDataStream *const pDataStream)=0
De-serialize a DQMEvent given from the data stream.
virtual StatusCode serialize (const DQMEvent *const pObject, const std::string &subEventIdentifier, DQMDataStream *const pDataStream)=0
Serialize a part of a DQMEvent object identified by the reg exp 'subEventIdentifier' and store it in the data stream.
Detailed Description
DQMEventStreamer class.
Definition at line 41 of file DQMEventStreamer.h.
Constructor & Destructor Documentation
virtual dqm4hep::DQMEventStreamer::~DQMEventStreamer () [inline], [virtual]
Destructor.
Definition at line 46 of file DQMEventStreamer.h.
{}
Member Function Documentation
virtual StatusCode dqm4hep::DQMEventStreamer::deserialize (DQMEvent *& pObject, DQMDataStream *const pDataStream) [pure virtual]
De-serialize a DQMEvent given from the data stream.
Implements dqm4hep::DQMStreamer< DQMEvent > .
Implemented in dqm4hep::DQMLCEventStreamer .
Referenced by dqm4hep::DQMDimEventCollector::handleEventReception(), and dqm4hep::DQMDimEventClient::queryEvent().
virtual StatusCode dqm4hep::DQMEventStreamer::serialize (const DQMEvent *const pObject, DQMDataStream *const pDataStream) [pure virtual]
Serialize a DQMEvent object and store it in the data stream.
Implements dqm4hep::DQMStreamer< DQMEvent > .
Implemented in dqm4hep::DQMLCEventStreamer .
Referenced by dqm4hep::DQMDimEventCollector::handleEventRequest(), and dqm4hep::DQMDimEventCollector::updateEventService().
virtual StatusCode dqm4hep::DQMEventStreamer::serialize (const DQMEvent *const pObject, const std::string & subEventIdentifier, DQMDataStream *const pDataStream) [pure virtual]
Serialize a part of a DQMEvent object identified by the reg exp 'subEventIdentifier' and store it in the data stream.
Example : subEventIdentifier = `MyCollection1:MyCollection2` subEventIdentifier = `*TpcCollection`
The identifier decoding has to be performed by the user, based on the event contents itself
Implemented in dqm4hep::DQMLCEventStreamer .
The documentation for this class was generated from the following file:
DQMEventStreamer.h