dqm4hep::DQMRunControl Class Reference
DQMRunControl class.
#include <DQMRunControl.h>
Public Member Functions
DQMRunControl ()
Constructor.
DQMRunControl (const std::string &runControlName)
Constructor with name.
virtual ~DQMRunControl ()
Destructor.
void setRunControlName (const std::string &runControlName)
Set the run control name.
const std::string & getRunControlName () const
Get the run control name.
StatusCode startNewRun (DQMRun *pRun)
Create a new run from a DQMRun The run control is the owner the run.
StatusCode startNewRun (int runNumber, const std::string &description=``, const std::string &detectorName=``)
Create a new run.
StatusCode endCurrentRun ()
End the current run.
int getCurrentRunNumber () const
Get the current run number.
DQMRun * getCurrentRun () const
Get the current run header.
DQMState getRunState () const
Get the run state (running or not)
bool isRunning () const
Whether a run has been started.
void addListener (DQMRunListener *pListener)
Add a listener to the run control.
void removeListener (DQMRunListener *pListener)
Remove a listener from the run control.
Protected Attributes
DQMState m_runState
DQMRun * m_pCurrentRun
std::string m_runControlName
std::vector< DQMRunListener * > m_listeners
Detailed Description
DQMRunControl class.
Definition at line 63 of file DQMRunControl.h.
Constructor & Destructor Documentation
dqm4hep::DQMRunControl::DQMRunControl ()
Constructor.
Definition at line 38 of file DQMRunControl.cc.
                             :
    m_runState(STOPPED_STATE),
    m_pCurrentRun(NULL),
    m_runControlName("DEFAULT")
{
  /* nop */
}
dqm4hep::DQMRunControl::DQMRunControl (const std::string & runControlName)
Constructor with name.
Definition at line 48 of file DQMRunControl.cc.
                                                            :
    m_runState(STOPPED_STATE),
    m_pCurrentRun(NULL),
    m_runControlName(runControlName)
{
  /* nop */
}
dqm4hep::DQMRunControl::~DQMRunControl () [virtual]
Destructor.
Definition at line 58 of file DQMRunControl.cc.
References endCurrentRun(), and isRunning().
{
  if(isRunning())
    endCurrentRun();
}
Member Function Documentation
void dqm4hep::DQMRunControl::addListener (DQMRunListener * pListener)
Add a listener to the run control.
Definition at line 175 of file DQMRunControl.cc.
References m_listeners.
{
  if(NULL == pListener)
    return;
  if(std::find(m_listeners.begin(), m_listeners.end(), pListener) == m_listeners.end())
    m_listeners.push_back(pListener);
}
StatusCode dqm4hep::DQMRunControl::endCurrentRun ()
End the current run.
Definition at line 120 of file DQMRunControl.cc.
References isRunning(), m_listeners, m_pCurrentRun, and m_runState.
Referenced by dqm4hep::DQMRunControlService::endCurrentRun(), dqm4hep::DQMDimRunControlClient::infoHandler(), setRunControlName(), startNewRun(), and ~DQMRunControl().
{
  if(!isRunning())
    return STATUS_CODE_SUCCESS;
  m_runState = STOPPED_STATE;
  if(NULL != m_pCurrentRun)
  {
    // notify before deletion
    for(std::vector<DQMRunListener*>::iterator iter = m_listeners.begin(), endIter =
      m_listeners.end() ;
        endIter != iter ; ++iter)
      (*iter)->onEndOfRun(m_pCurrentRun);
    delete m_pCurrentRun;
  }
  m_pCurrentRun = NULL;
  return STATUS_CODE_SUCCESS;
}
DQMRun * dqm4hep::DQMRunControl::getCurrentRun () const
Get the current run header.
Definition at line 154 of file DQMRunControl.cc.
References m_pCurrentRun.
Referenced by dqm4hep::DQMRunControlService::endCurrentRun(), dqm4hep::DQMRunControlService::getCurrentRun(), dqm4hep::DQMRunControlService::handleCurrentRunRpc(), dqm4hep::DQMAnalysisModuleApplication::run(), and dqm4hep::DQMRunControlService::startNewRun().
{
  return m_pCurrentRun;
}
int dqm4hep::DQMRunControl::getCurrentRunNumber () const
Get the current run number.
Definition at line 144 of file DQMRunControl.cc.
References dqm4hep::DQMRun::getRunNumber(), and m_pCurrentRun.
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
{
  if(NULL != m_pCurrentRun)
    return m_pCurrentRun->getRunNumber();
  else
    return 0;
}
const std::string & dqm4hep::DQMRunControl::getRunControlName () const
Get the run control name.
Definition at line 76 of file DQMRunControl.cc.
References m_runControlName.
Referenced by dqm4hep::DQMDimRunControlClient::connectToService().
{
  return m_runControlName;
}
DQMState dqm4hep::DQMRunControl::getRunState () const
Get the run state (running or not)
Definition at line 161 of file DQMRunControl.cc.
References m_runState.
Referenced by dqm4hep::DQMRunControlService::getRunState(), and dqm4hep::DQMRunControlService::~DQMRunControlService().
{
  return m_runState;
}
bool dqm4hep::DQMRunControl::isRunning () const
Whether a run has been started.
Definition at line 168 of file DQMRunControl.cc.
References m_runState.
Referenced by endCurrentRun(), dqm4hep::DQMRunControlService::handleCurrentRunRpc(), dqm4hep::DQMDimRunControlClient::infoHandler(), dqm4hep::DQMAnalysisModuleApplication::run(), setRunControlName(), startNewRun(), and ~DQMRunControl().
{
  return m_runState == RUNNING_STATE;
}
void dqm4hep::DQMRunControl::removeListener (DQMRunListener * pListener)
Remove a listener from the run control.
Definition at line 186 of file DQMRunControl.cc.
References m_listeners.
{
  std::vector<DQMRunListener*>::iterator findIter = std::find(m_listeners.begin(),
      m_listeners.end(), pListener);
  if(findIter != m_listeners.end())
    m_listeners.erase(findIter);
}
void dqm4hep::DQMRunControl::setRunControlName (const std::string & runControlName)
Set the run control name.
This stops the current before
Definition at line 66 of file DQMRunControl.cc.
References endCurrentRun(), isRunning(), and m_runControlName.
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureNetwork().
{
  if(this->isRunning())
    endCurrentRun();
  m_runControlName = runControlName;
}
StatusCode dqm4hep::DQMRunControl::startNewRun (DQMRun * pRun)
Create a new run from a DQMRun The run control is the owner the run.
Definition at line 83 of file DQMRunControl.cc.
References endCurrentRun(), isRunning(), m_listeners, m_pCurrentRun, m_runState, and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMDimRunControlClient::handleCurrentRunRpcInfo(), dqm4hep::DQMDimRunControlClient::infoHandler(), and dqm4hep::DQMRunControlService::startNewRun().
{
  if(NULL == pRun)
    return STATUS_CODE_INVALID_PTR;
  if(isRunning())
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, endCurrentRun());
  m_pCurrentRun = pRun;
  m_runState = RUNNING_STATE;
  for(std::vector<DQMRunListener*>::iterator iter = m_listeners.begin(), endIter =
      m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->onStartOfRun(m_pCurrentRun);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMRunControl::startNewRun (int runNumber, const std::string & description = ``, const std::string & detectorName = ``)
Create a new run.
End the current run if running
Definition at line 103 of file DQMRunControl.cc.
References endCurrentRun(), isRunning(), m_listeners, m_pCurrentRun, m_runState, and RETURN_RESULT_IF.
{
  if(isRunning())
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, endCurrentRun());
  m_pCurrentRun = new DQMRun(runNumber, description, detectorName);
  m_runState = RUNNING_STATE;
  for(std::vector<DQMRunListener*>::iterator iter = m_listeners.begin(), endIter =
      m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->onStartOfRun(m_pCurrentRun);
  return STATUS_CODE_SUCCESS;
}
Member Data Documentation
std::vector<DQMRunListener *> dqm4hep::DQMRunControl::m_listeners [protected]
Definition at line 128 of file DQMRunControl.h.
Referenced by addListener(), endCurrentRun(), removeListener(), and startNewRun().
DQMRun* dqm4hep::DQMRunControl::m_pCurrentRun [protected]
Definition at line 126 of file DQMRunControl.h.
Referenced by endCurrentRun(), getCurrentRun(), getCurrentRunNumber(), and startNewRun().
std::string dqm4hep::DQMRunControl::m_runControlName [protected]
Definition at line 127 of file DQMRunControl.h.
Referenced by getRunControlName(), and setRunControlName().
DQMState dqm4hep::DQMRunControl::m_runState [protected]
Definition at line 125 of file DQMRunControl.h.
Referenced by endCurrentRun(), getRunState(), isRunning(), and startNewRun().
The documentation for this class was generated from the following files:
DQMRunControl.h
DQMRunControl.cc