dqm4hep::DQMTPCHitStreamer Class Reference
DQMTPCHitStreamer class.
#include <DQMLCEventStreamer.h>
Public Member Functions
StatusCode serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize a TPCHit.
StatusCode deserialize (EVENT::LCObject *&pLCObject, DQMDataStream *const pDataStream)
Deserialize a TPCHit.
Detailed Description
DQMTPCHitStreamer class.
Definition at line 192 of file DQMLCEventStreamer.h.
Member Function Documentation
StatusCode dqm4hep::DQMTPCHitStreamer::deserialize (EVENT::LCObject *& pLCObject, DQMDataStream *const pDataStream)
Deserialize a TPCHit.
The object is allocated in this function
Definition at line 861 of file DQMLCEventStreamer.cc.
References dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMDataStream::read(), and THROW_RESULT_IF.
{
  pLCObject = 0;
  IMPL::TPCHitImpl *pTPCHit = new IMPL::TPCHitImpl();
  try
  {
    dqm_int cellID = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(cellID));
    pTPCHit->setCellID(cellID);
    dqm_int time = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(time));
    pTPCHit->setTime(time);
    dqm_float charge = 0.f;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(charge));
    pTPCHit->setCharge(charge);
    dqm_int quality = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(quality));
    pTPCHit->setQuality(quality);
    dqm_uint nRawDataWords = 0.f;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nRawDataWords));
    int *pRawData = new int[nRawDataWords];
    try
    {
      for(dqm_uint i=0 ; i<nRawDataWords ; i++)
      {
        dqm_int rawDataWord = 0;
        THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(rawDataWord));
        pRawData[i] = rawDataWord;
      }
      pTPCHit->setRawData(pRawData, nRawDataWords);
    }
    catch(const StatusCodeException &exception)
    {
      delete [] pRawData;
      throw StatusCodeException(exception.getStatusCode());
    }
  }
  catch(StatusCodeException &exception)
  {
    delete pTPCHit;
    pTPCHit = 0;
    pLCObject = 0;
  }
  pLCObject = pTPCHit;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMTPCHitStreamer::serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize a TPCHit.
Definition at line 827 of file DQMLCEventStreamer.cc.
References RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
{
  const EVENT::TPCHit *const pTPCHit = dynamic_cast<const EVENT::TPCHit *const>(pLCObject);
  if(NULL == pTPCHit)
    return STATUS_CODE_INVALID_PARAMETER;
  dqm_int cellID = pTPCHit->getCellID();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(cellID));
  dqm_float time = pTPCHit->getTime();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(time));
  dqm_float charge = pTPCHit->getCharge();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(charge));
  dqm_int quality = pTPCHit->getQuality();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(quality));
  dqm_uint nRawDataWords = pTPCHit->getNRawDataWords();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nRawDataWords));
  for(dqm_uint i=0 ; i<nRawDataWords ; i++)
  {
    dqm_uint rawDataWord = pTPCHit->getRawDataWord(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(rawDataWord));
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMLCEventStreamer.h
DQMLCEventStreamer.cc