dqm4hep::DQMMeanWithinExpectedTest Class Reference
DQMMeanWithinExpectedTest class.
#include <DQMQualityTest.h>
Classes
class Factory
Factory class.
Public Member Functions
DQMMeanWithinExpectedTest (const std::string &name)
Constructor with name.
virtual ~DQMMeanWithinExpectedTest ()
Destructor.
virtual StatusCode readSettings (const TiXmlHandle xmlHandle)
Read the settings from the xml handle.
virtual StatusCode init ()
Initialize the quality test.
virtual StatusCode run (DQMMonitorElement *pMonitorElement)
Runs a quality test on the given monitor element.
virtual bool canRun (DQMMonitorElement *pMonitorElement) const
Whether the quality test can be run on the monitor element.
Protected Attributes
unsigned int m_strategy
float m_xMin
float m_xMax
float m_expectedMean
float m_sigma
Additional Inherited Members
Detailed Description
DQMMeanWithinExpectedTest class.
Definition at line 185 of file DQMQualityTest.h.
Constructor & Destructor Documentation
dqm4hep::DQMMeanWithinExpectedTest::DQMMeanWithinExpectedTest (const std::string & name)
Constructor with name.
Definition at line 183 of file DQMQualityTest.cc.
Referenced by dqm4hep::DQMMeanWithinExpectedTest::Factory::createQualityTest().
                                                                          :
  DQMQualityTest(name),
  m_strategy(0),
  m_xMin(0.f),
  m_xMax(0.f),
  m_expectedMean(0.f),
  m_sigma(0.f)
{
  /* nop */
}
dqm4hep::DQMMeanWithinExpectedTest::~DQMMeanWithinExpectedTest () [virtual]
Destructor.
Definition at line 196 of file DQMQualityTest.cc.
{
  /* nop */
}
Member Function Documentation
bool dqm4hep::DQMMeanWithinExpectedTest::canRun (DQMMonitorElement * pMonitorElement) const [virtual]
Whether the quality test can be run on the monitor element.
Implements dqm4hep::DQMQualityTest .
Definition at line 299 of file DQMQualityTest.cc.
References dqm4hep::DQMMonitorElement::get(), and dqm4hep::DQMMonitorElement::getType().
{
  if(NULL == pMonitorElement)
    return false;
  DQMMonitorElementType type = pMonitorElement->getType();
  TH1 *pHistogram = pMonitorElement->get<TH1>();
  // asking for a histo 1D
  if(type < INT_HISTOGRAM_1D_ELEMENT_TYPE || type > CHAR_HISTOGRAM_1D_ELEMENT_TYPE)
    return false;
  if(NULL == pHistogram)
    return false;
  return true;
}
StatusCode dqm4hep::DQMMeanWithinExpectedTest::init () [virtual]
Initialize the quality test.
Implements dqm4hep::DQMQualityTest .
Definition at line 237 of file DQMQualityTest.cc.
{
  /* nop */
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMeanWithinExpectedTest::readSettings (const TiXmlHandle xmlHandle) [virtual]
Read the settings from the xml handle.
Implements dqm4hep::DQMQualityTest .
Definition at line 203 of file DQMQualityTest.cc.
References m_expectedMean, m_sigma, m_strategy, m_xMax, m_xMin, dqm4hep::DQMXmlHelper::readValue(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
      "Strategy", m_strategy));
  if(0 == m_strategy)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
        "XMin", m_xMin));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
        "XMax", m_xMax));
  }
  else if(1 == m_strategy)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
        "ExpectedMean", m_expectedMean));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
        "Sigma", m_sigma));
  }
  else if(2 == m_strategy)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::readValue(xmlHandle,
        "ExpectedMean", m_expectedMean));
  }
  else
    return STATUS_CODE_INVALID_PARAMETER;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMeanWithinExpectedTest::run (DQMMonitorElement * pMonitorElement) [virtual]
Runs a quality test on the given monitor element.
Implements dqm4hep::DQMQualityTest .
Definition at line 245 of file DQMQualityTest.cc.
References dqm4hep::DQMMonitorElement::get(), m_expectedMean, dqm4hep::DQMQualityTest::m_isSuccessful, dqm4hep::DQMQualityTest::m_message, dqm4hep::DQMQualityTest::m_quality, m_sigma, m_strategy, m_xMax, and dqm4hep::DQM4HEP::scaleToQuality().
{
  m_isSuccessful = false;
  m_quality = NO_QUALITY;
  m_message = "";
  TH1 *pHistogram = pMonitorElement->get<TH1>();
  if(0 == m_strategy)
  {
    float mean = pHistogram->GetMean();
    // test failed ?
    if(mean < m_xMin || mean > m_xMax)
    {
      m_quality = VERY_BAD_QUALITY;
      m_message = "Out of range !";
    }
    else
    {
      m_quality = VERY_GOOD_QUALITY;
      m_message = "";
    }
    m_isSuccessful = true;
  }
  else if(1 == m_strategy)
  {
    float chi = (pHistogram->GetMean() - m_expectedMean)/m_sigma;
    float probability = TMath::Prob(chi*chi, 1);
    m_quality = DQM4HEP::scaleToQuality(probability);
    m_isSuccessful = true;
  }
  else if(2 == m_strategy)
  {
    float chi = (pHistogram->GetMean() - m_expectedMean)/pHistogram->GetRMS();
    float probability = TMath::Prob(chi*chi, 1);
    m_quality = DQM4HEP::scaleToQuality(probability);
    m_isSuccessful = true;
  }
  else
  {
    m_isSuccessful = false;
    m_quality = NO_QUALITY;
    m_message = "Undefined strategy for this test";
  }
  return STATUS_CODE_SUCCESS;
}
Member Data Documentation
float dqm4hep::DQMMeanWithinExpectedTest::m_expectedMean [protected]
Definition at line 227 of file DQMQualityTest.h.
Referenced by readSettings(), and run().
float dqm4hep::DQMMeanWithinExpectedTest::m_sigma [protected]
Definition at line 228 of file DQMQualityTest.h.
Referenced by readSettings(), and run().
unsigned int dqm4hep::DQMMeanWithinExpectedTest::m_strategy [protected]
Definition at line 224 of file DQMQualityTest.h.
Referenced by readSettings(), and run().
float dqm4hep::DQMMeanWithinExpectedTest::m_xMax [protected]
Definition at line 226 of file DQMQualityTest.h.
Referenced by readSettings(), and run().
float dqm4hep::DQMMeanWithinExpectedTest::m_xMin [protected]
Definition at line 225 of file DQMQualityTest.h.
Referenced by readSettings().
The documentation for this class was generated from the following files:
DQMQualityTest.h
DQMQualityTest.cc