dqm4hep::DQMMonitorElementCollector Class Reference
DQMMonitorElementCollector class.
#include <DQMMonitorElementCollector.h>
Public Types
typedef std::map< std::string,
*
DQMMonitorElementList > DQMMonitorElementListMap
Module name to element list map.
typedef std::map< std::string,
*
ModuleMeInfo * > ModuleMeInfoMap
Module element storage.
typedef std::set
*
< DQMMonitorElement * > DQMMonitorElementSet
typedef std::map< int,
*
DQMMonitorElementSet > ClientUpdateMap
Map of monitor element list to update.
Public Member Functions
DQMMonitorElementCollector ()
Constructor.
~DQMMonitorElementCollector ()
Destructor.
StatusCode setCollectorName (const std::string &collectorName)
Set the collector name.
const std::string & getCollectorName () const
Get the collector name.
StatusCode start ()
Start the collector.
StatusCode stop ()
Stop the collector.
DQMState getState () const
Get the collector state.
bool isRunning () const
Whether the collector is running.
Static Public Attributes
static const std::string m_emptyBufferStr = `EMPTY`
Private Member Functions
void commandHandler ()
Dim command handler.
void clientExitHandler ()
Dim client exit handler.
void updateClients (const ClientUpdateMap &clientUpdateMap, bool forceUpdate=false)
Update client side with the monitor elements.
void handleMeCollectUpdate (DimCommand *pCommand)
Handle the monitor element packet reception from a module application.
void handleAvailableListUpdate (DimCommand *pCommand)
Handle the available list of monitor element on module side.
void handleClientSubscription (int clientID, DimCommand *pCommand)
Handle a client subscription.
void handleClientUnsubscription (int clientID, DimCommand *pCommand)
Handle a client unsubscription.
void handleClientUpdateMode (int clientId, bool updateMode)
Handle client automatic update mode.
void handleClientRequestList (int clientId, DimCommand *pCommand)
Handle client me name request list update.
void handleMeQuery (int clientId, DimCommand *pCommand)
Handle the me query of target client id.
void sendMeUpdate (int clientID)
Update the monitor element publication service for a specific client.
void notifyWatchedMe (const std::string &moduleName)
Notify the module that users are watching a different set of monitor elements provided by the module.
bool registerClient (int clientId)
Register a monitor element client.
bool registerClient (int clientId, const std::string moduleName)
Register a module client.
bool deregisterClient (int clientId)
De-register a client.
int getModuleClientID (const std::string &moduleName) const
Get the module client ID.
Private Attributes
std::string m_collectorName
DQMMonitorElementNameListRpc * m_pMonitorElementNameListRpc
DQMMonitorElementCollectorInfoRpc * m_pMonitorElementCollectorInfoRpc
DimCommand * m_pCollectMeCommand
DimCommand * m_pAvailableMeListCommand
DimCommand * m_pMeQueryCommand
DimCommand * m_pSetUpdateModeCommand
DimCommand * m_pSubscribeCommand
DimCommand * m_pUnsubscribeCommand
DimCommand * m_pSetSubscriptionCommand
DimCommand * m_pQuerySubscribedCommand
DimService * m_pMeUpdateService
DimService * m_pNotifyWatchedMeService
DimService * m_pCollectorStateService
DQMStatisticsService * m_pStatisticsService
int m_collectorState
DQMDataStream m_dataStream
To deserialize incoming monitor elements from modules.
ModuleMeInfoMap m_moduleMeInfoMap
ClientMap m_clientMap
Friends
class DQMCollectorCommandHandler
class DQMMonitorElementNameListRpc
class DQMMonitorElementCollectorInfoRpc
Detailed Description
DQMMonitorElementCollector class.
Definition at line 219 of file DQMMonitorElementCollector.h.
Member Typedef Documentation
typedef std::map<int, DQMMonitorElementSet> dqm4hep::DQMMonitorElementCollector::ClientUpdateMap
Map of monitor element list to update.
Definition at line 259 of file DQMMonitorElementCollector.h.
typedef std::map<std::string, DQMMonitorElementList> dqm4hep::DQMMonitorElementCollector::DQMMonitorElementListMap
Module name to element list map.
Definition at line 256 of file DQMMonitorElementCollector.h.
typedef std::set<DQMMonitorElement *> dqm4hep::DQMMonitorElementCollector::DQMMonitorElementSet
Definition at line 258 of file DQMMonitorElementCollector.h.
typedef std::map<std::string, ModuleMeInfo *> dqm4hep::DQMMonitorElementCollector::ModuleMeInfoMap
Module element storage.
Definition at line 257 of file DQMMonitorElementCollector.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElementCollector::DQMMonitorElementCollector ()
Constructor.
Definition at line 390 of file DQMMonitorElementCollector.cc.
References m_dataStream, m_emptyBufferStr, and dqm4hep::DQMDataStream::write().
                                                       :
    m_collectorName("DEFAULT"),
    m_collectorState(STOPPED_STATE),
    m_pMonitorElementNameListRpc(NULL),
    m_pMonitorElementCollectorInfoRpc(NULL),
    m_dataStream(5*1024*1024)
{
  m_dataStream.write(m_emptyBufferStr);
}
dqm4hep::DQMMonitorElementCollector::~DQMMonitorElementCollector ()
Destructor.
Definition at line 402 of file DQMMonitorElementCollector.cc.
References isRunning(), and stop().
{
  if(isRunning())
    stop();
}
Member Function Documentation
void dqm4hep::DQMMonitorElementCollector::clientExitHandler () [private]
Dim client exit handler.
Definition at line 617 of file DQMMonitorElementCollector.cc.
References deregisterClient().
{
  int clientId = getClientId();
  this->deregisterClient(clientId);
}
void dqm4hep::DQMMonitorElementCollector::commandHandler () [private]
Dim command handler.
Definition at line 577 of file DQMMonitorElementCollector.cc.
References handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleClientUpdateMode(), handleMeCollectUpdate(), handleMeQuery(), m_pAvailableMeListCommand, m_pCollectMeCommand, m_pMeQueryCommand, m_pSetSubscriptionCommand, m_pSetUpdateModeCommand, m_pSubscribeCommand, and m_pUnsubscribeCommand.
{
  DimCommand *pReceivedCommand = getCommand();
  std::cout << "Received command : " << pReceivedCommand->getName() << std::endl;
  // from modules
  if(pReceivedCommand == m_pCollectMeCommand)
  {
    this->handleMeCollectUpdate(pReceivedCommand);
  }
  else if(pReceivedCommand == m_pAvailableMeListCommand)
  {
    this->handleAvailableListUpdate(pReceivedCommand);
  }
  // from client side
  else if(pReceivedCommand == m_pMeQueryCommand)
  {
    this->handleMeQuery(getClientId(), m_pMeQueryCommand);
  }
  else if(pReceivedCommand == m_pSetUpdateModeCommand)
  {
    this->handleClientUpdateMode(getClientId(), static_cast<bool>(pReceivedCommand->getInt()));
  }
  else if(pReceivedCommand == m_pSubscribeCommand)
  {
    this->handleClientSubscription(getClientId(), pReceivedCommand);
  }
  else if(pReceivedCommand == m_pUnsubscribeCommand)
  {
    this->handleClientUnsubscription(getClientId(), pReceivedCommand);
  }
  else if(pReceivedCommand == m_pSetSubscriptionCommand)
  {
    this->handleClientRequestList(getClientId(), pReceivedCommand);
  }
}
bool dqm4hep::DQMMonitorElementCollector::deregisterClient (int clientId) [private]
De-register a client.
Definition at line 1183 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, m_clientMap, m_moduleMeInfoMap, and notifyWatchedMe().
Referenced by clientExitHandler().
{
  ClientMap::iterator findIter = m_clientMap.find(clientId);
  if(findIter == m_clientMap.end())
    return false;
  DimServer::clearClientExitHandler(clientId);
  // module client case
  if(findIter->second.isModule())
  {
    std::string moduleName = findIter->second.getModuleName();
    ModuleMeInfoMap::iterator moduleFindIter = m_moduleMeInfoMap.find(moduleName);
    if(moduleFindIter != m_moduleMeInfoMap.end())
    {
      delete moduleFindIter->second;
      m_moduleMeInfoMap.erase(moduleFindIter);
    }
    streamlog_out(DEBUG) << "Deregistering module " << moduleName << " with client id " << clientId <<
      std::endl;
  }
  // monitor element client case
  else
  {
    // unsubscribe to all element that the client subscribed
    // this will update the list of watched monitor elements
    // We then have to notify modules that watched elements are not the same
    for(ModuleMeInfoMap::iterator iter = m_moduleMeInfoMap.begin(), endIter =
      m_moduleMeInfoMap.end() ;
        endIter != iter ; ++iter)
    {
      // this returns if at least one element has been removed
      // from the watched list. Use it to trigger update if necessary
      bool updateService = iter->second->unsubscribe(clientId);
      if(updateService)
        this->notifyWatchedMe(iter->first);
    }
    streamlog_out(DEBUG) << "Registering me client " << clientId << std::endl;
  }
  // finally remove the client from the map
  m_clientMap.erase(findIter);
  return true;
}
const std::string & dqm4hep::DQMMonitorElementCollector::getCollectorName () const
Get the collector name.
Definition at line 422 of file DQMMonitorElementCollector.cc.
References m_collectorName.
Referenced by dqm4hep::DQMMonitorElementCollectorApplication::getName(), and handleMeCollectUpdate().
{
  return m_collectorName;
}
int dqm4hep::DQMMonitorElementCollector::getModuleClientID (const std::string & moduleName) const [private]
Get the module client ID.
Return 0 is not found (invalid for dim)
Definition at line 1235 of file DQMMonitorElementCollector.cc.
References m_clientMap.
Referenced by notifyWatchedMe().
{
  for(ClientMap::const_iterator iter = m_clientMap.begin(), endIter =
      m_clientMap.end() ;
      endIter != iter ; ++iter)
  {
    if(! iter->second.isModule())
      continue;
    if(iter->second.getModuleName() == moduleName)
      return iter->first;
  }
  return 0;
}
DQMState dqm4hep::DQMMonitorElementCollector::getState () const
Get the collector state.
See DQMState enum (DQM4HEP.h)
Definition at line 537 of file DQMMonitorElementCollector.cc.
References m_collectorState.
{
  return static_cast<DQMState>(m_collectorState);
}
void dqm4hep::DQMMonitorElementCollector::handleAvailableListUpdate (DimCommand * pCommand) [private]
Handle the available list of monitor element on module side.
Definition at line 714 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, dqm4hep::DQMMonitorElementInfoList::deserialize(), isRunning(), m_dataStream, m_moduleMeInfoMap, notifyWatchedMe(), dqm4hep::DQMDataStream::read(), registerClient(), dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), THROW_RESULT_IF, dqm4hep::StatusCodeException::toString(), and dqm4hep::WARNING.
Referenced by commandHandler().
{
  if(!this->isRunning())
    return;
  try
  {
    dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
    dqm_uint bufferSize = pCommand->getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      return;
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    // read the buffer
    std::string moduleName;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.read(moduleName));
    if(moduleName.empty())
      return;
    DQMMonitorElementInfoList availableMeList;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, availableMeList.deserialize(&
      m_dataStream));
    // register client, even if maybe already registered
    bool newClient = this->registerClient(getClientId(), moduleName);
    // look for module entry to update
    ModuleMeInfoMap::iterator findIter = m_moduleMeInfoMap.find(moduleName);
    // if not found, add the entry
    if(findIter == m_moduleMeInfoMap.end())
      findIter = m_moduleMeInfoMap.insert(ModuleMeInfoMap::value_type(moduleName, new ModuleMeInfo())).
      first;
    // update the entry
    findIter->second->setAvailableMeList(availableMeList);
    streamlog_out(DEBUG) << "Received " << availableMeList.size() << " available element from module " <<
      moduleName << std::endl;
    if(newClient)
      this->notifyWatchedMe(moduleName);
  }
  catch(const StatusCodeException &exception)
  {
    streamlog_out(WARNING) << "Exception caught : " << exception.toString() << std::endl;
  }
}
void dqm4hep::DQMMonitorElementCollector::handleClientRequestList (int clientId, DimCommand * pCommand) [private]
Handle client me name request list update.
Definition at line 788 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, isRunning(), m_dataStream, m_moduleMeInfoMap, notifyWatchedMe(), registerClient(), dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), THROW_RESULT_IF, dqm4hep::StatusCodeException::toString(), and dqm4hep::WARNING.
Referenced by commandHandler().
{
  if(!this->isRunning())
    return;
  try
  {
    dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
    dqm_uint bufferSize = pCommand->getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      return;
    this->registerClient(clientId);
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    DQMMonitorElementRequest request;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.deserialize(&m_dataStream));
    for(DQMMonitorElementRequest::iterator iter = request.begin(), endIter = request.end() ;
        endIter != iter ; ++iter)
    {
      ModuleMeInfoMap::iterator moduleIter = m_moduleMeInfoMap.find(iter->first);
      if(moduleIter == m_moduleMeInfoMap.end())
        continue;
      streamlog_out(DEBUG) << "Found module : " << iter->first << std::endl;
      // first unsubscribe to all elements
      moduleIter->second->unsubscribe(clientId);
      moduleIter->second->subscribe(clientId, iter->second);
      // in case the subscribed element is different
      this->notifyWatchedMe(iter->first);
    }
  }
  catch(const StatusCodeException &exception)
  {
    streamlog_out(WARNING) << "Exception caught : " << exception.toString() << std::endl;
  }
}
void dqm4hep::DQMMonitorElementCollector::handleClientSubscription (int clientID, DimCommand * pCommand) [private]
Handle a client subscription.
Definition at line 934 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, isRunning(), m_dataStream, m_moduleMeInfoMap, notifyWatchedMe(), registerClient(), dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), THROW_RESULT_IF, dqm4hep::StatusCodeException::toString(), and dqm4hep::WARNING.
Referenced by commandHandler().
{
  if(!this->isRunning())
    return;
  try
  {
    dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
    dqm_uint bufferSize = pCommand->getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      return;
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    DQMMonitorElementRequest request;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.deserialize(&m_dataStream));
    // if nothing specified in the request, return
    if(request.empty())
    {
      streamlog_out(DEBUG) << "No element to subscribe !" << std::endl;
      return;
    }
    this->registerClient(clientId);
    StringSet updateModuleList;
    for(DQMMonitorElementRequest::iterator iter = request.begin(), endIter = request.end() ;
        endIter != iter ; ++iter)
    {
      ModuleMeInfoMap::iterator moduleIter = m_moduleMeInfoMap.find(iter->first);
      if(moduleIter == m_moduleMeInfoMap.end())
        continue;
      if(moduleIter->second->subscribe(clientId, iter->second).second)
      {
        streamlog_out(DEBUG) << "New subscription for element : " << iter->second << std::endl;
        updateModuleList.insert(iter->first);
      }
    }
    for(StringSet::iterator iter = updateModuleList.begin(), endIter = updateModuleList.end() ;
        endIter != iter ; ++iter)
    {
      streamlog_out(DEBUG) << "Module " << *iter << " notified to send new me list !" << std::endl;
      this->notifyWatchedMe(*iter);
    }
  }
  catch(const StatusCodeException &exception)
  {
    streamlog_out(WARNING) << "Exception caught : " << exception.toString() << std::endl;
  }
}
void dqm4hep::DQMMonitorElementCollector::handleClientUnsubscription (int clientID, DimCommand * pCommand) [private]
Handle a client unsubscription.
Definition at line 994 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, isRunning(), m_dataStream, m_moduleMeInfoMap, notifyWatchedMe(), registerClient(), dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), THROW_RESULT_IF, dqm4hep::StatusCodeException::toString(), and dqm4hep::WARNING.
Referenced by commandHandler().
{
  if(!this->isRunning())
    return;
  try
  {
    dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
    dqm_uint bufferSize = pCommand->getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      return;
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    DQMMonitorElementRequest request;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.deserialize(&m_dataStream));
    // if nothing specified in the request, return
    if(request.empty())
    {
      streamlog_out(DEBUG) << "No element to unsubscribe !" << std::endl;
      return;
    }
    this->registerClient(clientId);
    StringSet updateModuleList;
    for(DQMMonitorElementRequest::iterator iter = request.begin(), endIter = request.end() ;
        endIter != iter ; ++iter)
    {
      ModuleMeInfoMap::iterator moduleIter = m_moduleMeInfoMap.find(iter->first);
      if(moduleIter == m_moduleMeInfoMap.end())
        continue;
      if(moduleIter->second->unsubscribe(clientId, iter->second).second)
      {
        streamlog_out(DEBUG) << "Element un-subscribed : " << iter->second << std::endl;
        updateModuleList.insert(iter->first);
      }
    }
    for(StringSet::iterator iter = updateModuleList.begin(), endIter = updateModuleList.end() ;
        endIter != iter ; ++iter)
    {
      streamlog_out(DEBUG) << "Module " << *iter << " notified to send new me list !" << std::endl;
      this->notifyWatchedMe(*iter);
    }
  }
  catch(const StatusCodeException &exception)
  {
    streamlog_out(WARNING) << "Exception caught : " << exception.toString() << std::endl;
  }
}
void dqm4hep::DQMMonitorElementCollector::handleClientUpdateMode (int clientId, bool updateMode) [private]
Handle client automatic update mode.
Definition at line 765 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, m_clientMap, and sendMeUpdate().
Referenced by commandHandler().
{
  ClientMap::iterator findIter = m_clientMap.find(clientId);
  if(findIter != m_clientMap.end())
  {
    if(! findIter->second.hasUpdateMode() && updateMode)
    {
      streamlog_out(DEBUG) << "Client no " << clientId << " update mode switched ON. Sending updates !" <<
      std::endl;
      this->sendMeUpdate(clientId);
    }
    streamlog_out(DEBUG) << "Client no " << clientId << " setting update mode to " << updateMode <<
      std::endl;
    findIter->second.setUpdateMode(updateMode);
    return;
  }
  streamlog_out(DEBUG) << "Client no " << clientId << " not registered !" << std::endl;
}
void dqm4hep::DQMMonitorElementCollector::handleMeCollectUpdate (DimCommand * pCommand) [private]
Handle the monitor element packet reception from a module application.
Definition at line 625 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, getCollectorName(), m_dataStream, m_moduleMeInfoMap, m_pStatisticsService, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), THROW_RESULT_IF, dqm4hep::StatusCodeException::toString(), dqm4hep::DQMStatisticsService::update(), updateClients(), and dqm4hep::WARNING.
Referenced by commandHandler().
{
  try
  {
    char *pBuffer = static_cast<char *>(pCommand->getData());
    int bufferSize = pCommand->getSize();
    if(bufferSize == 0 || NULL == pBuffer)
    {
      streamlog_out(WARNING) << "Empty buffer, skipping packet ..." << std::endl;
      throw StatusCodeException(STATUS_CODE_SUCCESS);
    }
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    DQMMonitorElementPublication publication;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, publication.deserialize(&
      m_dataStream));
    if(publication.empty())
    {
      streamlog_out(WARNING) << "Empty publication, skipping packet ..." << std::endl;
      throw StatusCodeException(STATUS_CODE_SUCCESS);
    }
    int nElements = 0;
    ClientUpdateMap clientUpdateMap;
    // update the monitor element with ones received !
    // build the monitor element list to update for each client
    for(DQMMonitorElementPublication::iterator iter = publication.begin(),
        endIter = publication.end() ; endIter != iter ; ++iter)
    {
      ModuleMeInfoMap::iterator findIter = m_moduleMeInfoMap.find(iter->first);
      // if module not found, clean the monitor elements related to this module
      if(findIter == m_moduleMeInfoMap.end())
      {
        for(DQMMonitorElementList::iterator meIter = iter->second.begin(), meEndIter = iter->second.end() ;
            meEndIter != meIter ; ++meIter)
          delete *meIter;
        continue;
      }
      // update monitor elements !
      for(DQMMonitorElementList::iterator meIter = iter->second.begin(), meEndIter = iter->second.end() ;
                  meEndIter != meIter ; ++meIter)
      {
        bool updated = findIter->second->updateMonitorElement(*meIter);
        if(!updated)
          delete *meIter;
        nElements++;
        (*meIter)->setCollectorName(this->getCollectorName());
        // get the client ids that have subscribed to these elements
        std::string meFullName = ((*meIter)->getPath() + (*meIter)->getName()).getPath();
        if(meFullName.at(0) != '/')
          meFullName = "/" + meFullName;
        streamlog_out(DEBUG) << "meFullName on collect : " << meFullName << std::endl;
        std::set<int> clientIdSet = findIter->second->getSubscribers(meFullName);
        // add the monitor element entry into the update map
        for(std::set<int>::iterator cliIter = clientIdSet.begin(), cliEndIter = clientIdSet.end() ;
            cliEndIter != cliIter ; ++cliIter)
        {
          clientUpdateMap[*cliIter].insert(*meIter);
        }
      }
    }
    m_pStatisticsService->update(nElements);
    streamlog_out(DEBUG) << "Received n elements : " << nElements << " from " << publication.size() << "
       modules" << std::endl;
    this->updateClients(clientUpdateMap);
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(WARNING) << "Exception caught : " << exception.toString() << std::endl;
  }
}
void dqm4hep::DQMMonitorElementCollector::handleMeQuery (int clientId, DimCommand * pCommand) [private]
Handle the me query of target client id.
Definition at line 835 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isRunning(), m_dataStream, m_moduleMeInfoMap, m_pMeUpdateService, notifyWatchedMe(), registerClient(), dqm4hep::DQMDataStream::reset(), sendMeUpdate(), dqm4hep::DQMMonitorElementPublication::serialize(), dqm4hep::DQMDataStream::setBuffer(), THROW_RESULT_IF, dqm4hep::StatusCodeException::toString(), and dqm4hep::WARNING.
Referenced by commandHandler().
{
  if(!this->isRunning())
    return;
  try
  {
    dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
    dqm_uint bufferSize = pCommand->getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      return;
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    DQMMonitorElementRequest request;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.deserialize(&m_dataStream));
    // if nothing specified in the request, just send updates
    if(request.empty())
    {
      streamlog_out(DEBUG) << "Sending me updates from client query" << std::endl;
      this->sendMeUpdate(clientId);
      return;
    }
    this->registerClient(clientId);
    StringSet updateModuleList;
    DQMMonitorElementPublication monitorElementPublication;
    streamlog_out(DEBUG) << "Request size : " << request.size() << std::endl;
    for(DQMMonitorElementRequest::iterator iter = request.begin(), endIter = request.end() ;
        endIter != iter ; ++iter)
    {
      ModuleMeInfoMap::iterator moduleIter = m_moduleMeInfoMap.find(iter->first);
      if(moduleIter == m_moduleMeInfoMap.end())
        continue;
      streamlog_out(DEBUG) << "Found module : " << iter->first << std::endl;
      // subscribe to me if not done yet
      if(moduleIter->second->subscribe(clientId, iter->second).second)
      {
        streamlog_out(DEBUG) << "New subscription for element : " << iter->second << std::endl;
        updateModuleList.insert(iter->first);
      }
      else
      {
        streamlog_out(DEBUG) << "Element : " << iter->second << " already subscribed !" << std::endl;
      }
      // find the monitor element
      DQMMonitorElement *pMonitorElement = moduleIter->second->getMonitorElement(iter->second);
      if(NULL == pMonitorElement)
        continue;
      streamlog_out(DEBUG) << "Element : " << iter->second << " found !" << std::endl;
      monitorElementPublication[iter->first].push_back(pMonitorElement);
    }
    for(StringSet::iterator iter = updateModuleList.begin(), endIter = updateModuleList.end() ;
        endIter != iter ; ++iter)
    {
      streamlog_out(DEBUG) << "Module " << *iter << " notified to send new me list !" << std::endl;
      this->notifyWatchedMe(*iter);
    }
    if(monitorElementPublication.empty())
      return;
    m_dataStream.reset();
    StatusCode statusCode = monitorElementPublication.serialize(&m_dataStream);
    if(statusCode != STATUS_CODE_SUCCESS)
    {
      m_dataStream.reset();
      return;
    }
    int clientIds[2];
    clientIds[0] = clientId;
    clientIds[1] = 0;
    streamlog_out(DEBUG) << "Me update service called (on query) !" << std::endl;
    m_pMeUpdateService->selectiveUpdateService((void *) m_dataStream.getBuffer(),
      m_dataStream.getBufferSize() , &clientIds[0]);
  }
  catch(const StatusCodeException &exception)
  {
    streamlog_out(WARNING) << "Exception caught : " << exception.toString() << std::endl;
  }
}
bool dqm4hep::DQMMonitorElementCollector::isRunning () const
Whether the collector is running.
Definition at line 544 of file DQMMonitorElementCollector.cc.
References m_collectorState.
Referenced by handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleMeQuery(), dqm4hep::DQMMonitorElementNameListRpc::rpcHandler(), sendMeUpdate(), setCollectorName(), start(), stop(), ~DQMMonitorElementCollector(), and dqm4hep::DQMMonitorElementCollectorApplication::~DQMMonitorElementCollectorApplication().
{
  return (m_collectorState == RUNNING_STATE);
}
void dqm4hep::DQMMonitorElementCollector::notifyWatchedMe (const std::string & moduleName) [private]
Notify the module that users are watching a different set of monitor elements provided by the module.
Definition at line 1104 of file DQMMonitorElementCollector.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), getModuleClientID(), m_dataStream, m_moduleMeInfoMap, m_pNotifyWatchedMeService, dqm4hep::DQMDataStream::reset(), and dqm4hep::DQMDataStream::write().
Referenced by deregisterClient(), handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), and handleMeQuery().
{
  int clientId = this->getModuleClientID(moduleName);
  if(0 == clientId)
    return;
  ModuleMeInfoMap::iterator moduleFindIter = m_moduleMeInfoMap.find(moduleName);
  if(moduleFindIter == m_moduleMeInfoMap.end())
    return;
  StringSet watchedMeList = moduleFindIter->second->getSubscribedList();
  m_dataStream.reset();
  if(STATUS_CODE_SUCCESS != m_dataStream.write(static_cast<dqm_uint>(watchedMeList.size())))
  {
    m_dataStream.reset();
    return;
  }
  for(StringSet::iterator iter = watchedMeList.begin(), endIter = watchedMeList.end() ;
      endIter != iter ; ++iter)
  {
    if(STATUS_CODE_SUCCESS != m_dataStream.write(*iter))
    {
      m_dataStream.reset();
      return;
    }
  }
  int clientIds[2];
  clientIds[0] = clientId;
  clientIds[1] = 0;
  m_pNotifyWatchedMeService->selectiveUpdateService((void *) m_dataStream.
      getBuffer(), m_dataStream.getBufferSize(), &clientIds[0]);
}
bool dqm4hep::DQMMonitorElementCollector::registerClient (int clientId) [private]
Register a monitor element client.
Definition at line 1145 of file DQMMonitorElementCollector.cc.
References m_clientMap.
Referenced by handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleMeQuery(), and sendMeUpdate().
{
  ClientMap::iterator findIter = m_clientMap.find(clientId);
  if(findIter != m_clientMap.end())
    return false;
  // just insert a new client
  m_clientMap.insert(ClientMap::value_type(clientId, ClientInfo(clientId)));
  DimServer::setClientExitHandler(clientId);
  return true;
}
bool dqm4hep::DQMMonitorElementCollector::registerClient (int clientId, const std::string moduleName) [private]
Register a module client.
Definition at line 1161 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, m_clientMap, and m_moduleMeInfoMap.
{
  ClientMap::iterator findIter = m_clientMap.find(clientId);
  if(findIter != m_clientMap.end())
    return false;
  streamlog_out(DEBUG) << "Registering module " << moduleName << " with client id " << clientId <<
      std::endl;
  // insert a new client
  m_clientMap.insert(ClientMap::value_type(clientId, ClientInfo(clientId, moduleName)));
  // create monitor element storage
  m_moduleMeInfoMap.insert(ModuleMeInfoMap::value_type(moduleName, new ModuleMeInfo()));
  DimServer::setClientExitHandler(clientId);
  return true;
}
void dqm4hep::DQMMonitorElementCollector::sendMeUpdate (int clientID) [private]
Update the monitor element publication service for a specific client.
Definition at line 1054 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isRunning(), m_dataStream, m_moduleMeInfoMap, m_pMeUpdateService, registerClient(), dqm4hep::DQMDataStream::reset(), and dqm4hep::DQMMonitorElementPublication::serialize().
Referenced by handleClientUpdateMode(), handleMeQuery(), and updateClients().
{
  if(!this->isRunning())
    return;
  this->registerClient(clientId);
  DQMMonitorElementPublication monitorElementPublication;
  streamlog_out(DEBUG) << "Building publication to send to client" << std::endl;
  for(ModuleMeInfoMap::const_iterator iter = m_moduleMeInfoMap.begin(), endIter =
      m_moduleMeInfoMap.end() ;
      endIter != iter ; ++iter)
  {
    std::string moduleName = iter->first;
    DQMMonitorElementList subscribedMeList = iter->second->getSubscribedMeList(clientId);
    if(subscribedMeList.empty())
      continue;
    streamlog_out(DEBUG) << "Module " << moduleName << ", total me list = " << subscribedMeList.size() <<
      std::endl;
    monitorElementPublication.insert(DQMMonitorElementPublication::value_type(moduleName, subscribedMeList)
      );
  }
  if(monitorElementPublication.empty())
  {
    streamlog_out(DEBUG) << "Empty publication ! Nothing will be sent !" << std::endl;
    return;
  }
  m_dataStream.reset();
  StatusCode statusCode = monitorElementPublication.serialize(&m_dataStream);
  if(statusCode != STATUS_CODE_SUCCESS)
  {
    m_dataStream.reset();
    return;
  }
  int clientIds[2];
  clientIds[0] = clientId;
  clientIds[1] = 0;
  streamlog_out(DEBUG) << "Me update service called (on update)!" << std::endl;
  m_pMeUpdateService->selectiveUpdateService((void *) m_dataStream.getBuffer(),
      m_dataStream.getBufferSize() , &clientIds[0]);
}
StatusCode dqm4hep::DQMMonitorElementCollector::setCollectorName (const std::string & collectorName)
Set the collector name.
Can be set only if the collector is not running. The collector name is used to build the service and command names over the network
Definition at line 410 of file DQMMonitorElementCollector.cc.
References isRunning(), and m_collectorName.
Referenced by dqm4hep::DQMMonitorElementCollectorApplication::setCollectorName().
{
  if(isRunning())
    return STATUS_CODE_NOT_ALLOWED;
  m_collectorName = collectorName;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementCollector::start ()
Start the collector.
Allocate services and commands
Definition at line 429 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, DQMMonitorElementCollectorInfoRpc, DQMMonitorElementNameListRpc, dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isRunning(), m_collectorName, m_collectorState, m_dataStream, m_pAvailableMeListCommand, m_pCollectMeCommand, m_pCollectorStateService, m_pMeQueryCommand, m_pMeUpdateService, m_pMonitorElementCollectorInfoRpc, m_pMonitorElementNameListRpc, m_pNotifyWatchedMeService, m_pSetSubscriptionCommand, m_pSetUpdateModeCommand, m_pStatisticsService, m_pSubscribeCommand, and m_pUnsubscribeCommand.
Referenced by dqm4hep::DQMMonitorElementCollectorApplication::run().
{
  if(isRunning())
    return STATUS_CODE_SUCCESS;
  std::string baseName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/";
  std::stringstream ss;
  ss << baseName << "MONITOR_ELEMENT_NAME_LIST_RPC";
  m_pMonitorElementNameListRpc = new DQMMonitorElementNameListRpc((char *)ss.str().c_str(), this);
  ss.str("");
  ss << baseName << "COLLECTOR_INFO_RPC";
  m_pMonitorElementCollectorInfoRpc = new DQMMonitorElementCollectorInfoRpc((char *)ss.str().c_str(), this)
      ;
  // from modules
  ss.str("");
  ss << baseName << "COLLECT_ME_CMD";
  m_pCollectMeCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
  ss.str("");
  ss << baseName << "NOTIFY_WATCHED_ME_SVC";
  m_pNotifyWatchedMeService = new DimService((char *)ss.str().c_str(), "C",
      (void*) m_dataStream.getBuffer(), m_dataStream.getBufferSize());
  // from clients
  ss.str("");
  ss << baseName << "AVAILABLE_ME_CMD";
  m_pAvailableMeListCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
  ss.str("");
  ss << baseName << "QUERY_ME_CMD";
  m_pMeQueryCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
  ss.str("");
  ss << baseName << "SET_UPDATE_MODE_CMD";
  m_pSetUpdateModeCommand = new DimCommand((char *)ss.str().c_str(), "I", this);
  ss.str("");
  ss << baseName << "SUBSCRIBE_CMD";
  m_pSubscribeCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
  ss.str("");
  ss << baseName << "UNSUBSCRIBE_CMD";
  m_pUnsubscribeCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
  ss.str("");
  ss << baseName << "SET_SUBSCRIPTION_CMD";
  m_pSetSubscriptionCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
  ss.str("");
  ss << baseName << "STATS";
  m_pStatisticsService = new DQMStatisticsService(ss.str());
  ss.str("");
  ss << baseName << "ME_UPDATE_SVC";
  m_pMeUpdateService = new DimService((char *)ss.str().c_str(), "C",
      (void*) m_dataStream.getBuffer(), m_dataStream.getBufferSize());
  m_collectorState = RUNNING_STATE;
  ss.str("");
  ss << baseName << "COLLECTOR_STATE_SVC";
  m_pCollectorStateService = new DimService((char *)ss.str().c_str(),
      m_collectorState);
  // for registration on dns ...
  sleep(1);
  // notify server running !
  streamlog_out(DEBUG) << "Server started !" << std::endl;
  m_pCollectorStateService->updateService(m_collectorState);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementCollector::stop ()
Stop the collector.
Destroy the commands and services
Definition at line 509 of file DQMMonitorElementCollector.cc.
References isRunning(), m_collectorState, m_pAvailableMeListCommand, m_pCollectMeCommand, m_pCollectorStateService, m_pMeQueryCommand, m_pMeUpdateService, m_pMonitorElementCollectorInfoRpc, m_pMonitorElementNameListRpc, m_pNotifyWatchedMeService, m_pSetSubscriptionCommand, m_pSetUpdateModeCommand, m_pStatisticsService, m_pSubscribeCommand, and m_pUnsubscribeCommand.
Referenced by dqm4hep::DQMMonitorElementCollectorApplication::exit(), ~DQMMonitorElementCollector(), and dqm4hep::DQMMonitorElementCollectorApplication::~DQMMonitorElementCollectorApplication().
{
  if(!isRunning())
    return STATUS_CODE_SUCCESS;
  delete m_pCollectMeCommand;
  delete m_pAvailableMeListCommand;
  delete m_pMeQueryCommand;
  delete m_pSetUpdateModeCommand;
  delete m_pSubscribeCommand;
  delete m_pUnsubscribeCommand;
  delete m_pSetSubscriptionCommand;
  delete m_pMonitorElementNameListRpc;
  delete m_pMonitorElementCollectorInfoRpc;
  delete m_pStatisticsService;
  delete m_pMeUpdateService;
  delete m_pNotifyWatchedMeService;
  m_collectorState = STOPPED_STATE;
  m_pCollectorStateService->updateService(m_collectorState);
  delete m_pCollectorStateService;
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMMonitorElementCollector::updateClients (const ClientUpdateMap & clientUpdateMap, bool forceUpdate = false) [private]
Update client side with the monitor elements.
Definition at line 551 of file DQMMonitorElementCollector.cc.
References dqm4hep::DEBUG, m_clientMap, and sendMeUpdate().
Referenced by handleMeCollectUpdate().
{
  for(ClientUpdateMap::const_iterator iter = clientUpdateMap.begin(), endIter = clientUpdateMap.end() ;
      endIter != iter ; ++iter)
  {
    ClientMap::iterator clientIter = m_clientMap.find(iter->first);
    if(clientIter == m_clientMap.end())
    {
      streamlog_out(DEBUG) << "Client no " << iter->first << " not registered. Skipping ..." << std::endl;
      continue;
    }
    if(!clientIter->second.hasUpdateMode() && !forceUpdate)
    {
      streamlog_out(DEBUG) << "Client no " << iter->first << " is not in update mode. Skipping ..." <<
      std::endl;
      continue;
    }
    streamlog_out(DEBUG) << "Sending updates to client no " << iter->first << std::endl;
    this->sendMeUpdate(clientIter->first);
  }
}
Friends And Related Function Documentation
friend class DQMCollectorCommandHandler [friend]
Definition at line 363 of file DQMMonitorElementCollector.h.
friend class DQMMonitorElementCollectorInfoRpc [friend]
Definition at line 365 of file DQMMonitorElementCollector.h.
Referenced by start().
friend class DQMMonitorElementNameListRpc [friend]
Definition at line 364 of file DQMMonitorElementCollector.h.
Referenced by start().
Member Data Documentation
ClientMap dqm4hep::DQMMonitorElementCollector::m_clientMap [private]
Definition at line 361 of file DQMMonitorElementCollector.h.
Referenced by deregisterClient(), getModuleClientID(), handleClientUpdateMode(), registerClient(), and updateClients().
std::string dqm4hep::DQMMonitorElementCollector::m_collectorName [private]
Definition at line 335 of file DQMMonitorElementCollector.h.
Referenced by getCollectorName(), setCollectorName(), and start().
int dqm4hep::DQMMonitorElementCollector::m_collectorState [private]
Definition at line 356 of file DQMMonitorElementCollector.h.
Referenced by getState(), isRunning(), start(), and stop().
DQMDataStream dqm4hep::DQMMonitorElementCollector::m_dataStream [private]
To deserialize incoming monitor elements from modules.
Definition at line 357 of file DQMMonitorElementCollector.h.
Referenced by DQMMonitorElementCollector(), handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleMeCollectUpdate(), handleMeQuery(), notifyWatchedMe(), sendMeUpdate(), and start().
const std::string dqm4hep::DQMMonitorElementCollector::m_emptyBufferStr = `EMPTY` [static]
Definition at line 261 of file DQMMonitorElementCollector.h.
Referenced by DQMMonitorElementCollector().
ModuleMeInfoMap dqm4hep::DQMMonitorElementCollector::m_moduleMeInfoMap [private]
Definition at line 360 of file DQMMonitorElementCollector.h.
Referenced by deregisterClient(), handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleMeCollectUpdate(), handleMeQuery(), notifyWatchedMe(), registerClient(), dqm4hep::DQMMonitorElementNameListRpc::rpcHandler(), dqm4hep::DQMMonitorElementCollectorInfoRpc::rpcHandler(), and sendMeUpdate().
DimCommand* dqm4hep::DQMMonitorElementCollector::m_pAvailableMeListCommand [private]
Definition at line 342 of file DQMMonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimCommand* dqm4hep::DQMMonitorElementCollector::m_pCollectMeCommand [private]
Definition at line 341 of file DQMMonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimService* dqm4hep::DQMMonitorElementCollector::m_pCollectorStateService [private]
Definition at line 352 of file DQMMonitorElementCollector.h.
Referenced by start(), and stop().
DimCommand* dqm4hep::DQMMonitorElementCollector::m_pMeQueryCommand [private]
Definition at line 343 of file DQMMonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimService* dqm4hep::DQMMonitorElementCollector::m_pMeUpdateService [private]
Definition at line 350 of file DQMMonitorElementCollector.h.
Referenced by handleMeQuery(), sendMeUpdate(), start(), and stop().
DQMMonitorElementCollectorInfoRpc* dqm4hep::DQMMonitorElementCollector::m_pMonitorElementCollectorInfoRpc [private]
Definition at line 339 of file DQMMonitorElementCollector.h.
Referenced by start(), and stop().
DQMMonitorElementNameListRpc* dqm4hep::DQMMonitorElementCollector::m_pMonitorElementNameListRpc [private]
Definition at line 338 of file DQMMonitorElementCollector.h.
Referenced by start(), and stop().
DimService* dqm4hep::DQMMonitorElementCollector::m_pNotifyWatchedMeService [private]
Definition at line 351 of file DQMMonitorElementCollector.h.
Referenced by notifyWatchedMe(), start(), and stop().
DimCommand* dqm4hep::DQMMonitorElementCollector::m_pQuerySubscribedCommand [private]
Definition at line 348 of file DQMMonitorElementCollector.h.
DimCommand* dqm4hep::DQMMonitorElementCollector::m_pSetSubscriptionCommand [private]
Definition at line 347 of file DQMMonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimCommand* dqm4hep::DQMMonitorElementCollector::m_pSetUpdateModeCommand [private]
Definition at line 344 of file DQMMonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DQMStatisticsService* dqm4hep::DQMMonitorElementCollector::m_pStatisticsService [private]
Definition at line 353 of file DQMMonitorElementCollector.h.
Referenced by handleMeCollectUpdate(), start(), and stop().
DimCommand* dqm4hep::DQMMonitorElementCollector::m_pSubscribeCommand [private]
Definition at line 345 of file DQMMonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimCommand* dqm4hep::DQMMonitorElementCollector::m_pUnsubscribeCommand [private]
Definition at line 346 of file DQMMonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
The documentation for this class was generated from the following files:
DQMMonitorElementCollector.h
DQMMonitorElementCollector.cc