dqm4hep::DQMLCEvent Class Reference
DQMLCEvent class.
#include <DQMLCEvent.h>
Public Member Functions
DQMLCEvent ()
Constructor.
~DQMLCEvent ()
Destructor.
EVENT::LCEvent * getEvent () const
Returns the stored lc event.
void setEvent (EVENT::LCEvent *pLCEvent)
Set the handled lc event.
void clear ()
Clear the handler by deleting the handled lc event.
Private Attributes
EVENT::LCEvent * m_pLCEvent
Additional Inherited Members
Detailed Description
DQMLCEvent class.
Wrapper for LCEvent class to be used in DQM system. Used in DQMAnalysisModule::processEvent(DQMEvent) to monitor event. See DQMAnalysisModule on how to process it in the DQM system framework
Definition at line 48 of file DQMLCEvent.h.
Constructor & Destructor Documentation
dqm4hep::DQMLCEvent::DQMLCEvent () [inline]
Constructor.
Definition at line 78 of file DQMLCEvent.h.
                              :
    m_pLCEvent(0)
{
}
dqm4hep::DQMLCEvent::~DQMLCEvent () [inline]
Destructor.
Definition at line 85 of file DQMLCEvent.h.
References clear().
{
  clear();
}
Member Function Documentation
void dqm4hep::DQMLCEvent::clear () [inline], [virtual]
Clear the handler by deleting the handled lc event.
Implements dqm4hep::DQMEventBase< EVENT::LCEvent > .
Definition at line 107 of file DQMLCEvent.h.
References dqm4hep::DQMEvent::isOwner(), and m_pLCEvent.
Referenced by setEvent(), and ~DQMLCEvent().
{
  if(0 != m_pLCEvent && this->isOwner())
    delete m_pLCEvent;
}
EVENT::LCEvent * dqm4hep::DQMLCEvent::getEvent () const [inline], [virtual]
Returns the stored lc event.
Implements dqm4hep::DQMEventBase< EVENT::LCEvent > .
Definition at line 92 of file DQMLCEvent.h.
References m_pLCEvent.
{
  return m_pLCEvent;
}
void dqm4hep::DQMLCEvent::setEvent (EVENT::LCEvent * pLCEvent) [inline], [virtual]
Set the handled lc event.
Implements dqm4hep::DQMEventBase< EVENT::LCEvent > .
Definition at line 99 of file DQMLCEvent.h.
References clear(), and m_pLCEvent.
{
  clear();
  m_pLCEvent = pLCEvent;
}
Member Data Documentation
EVENT::LCEvent* dqm4hep::DQMLCEvent::m_pLCEvent [private]
Definition at line 72 of file DQMLCEvent.h.
Referenced by clear(), getEvent(), and setEvent().
The documentation for this class was generated from the following file:
DQMLCEvent.h