dqm4hep::DQMLCIntVecStreamer Class Reference
DQMLCIntVecStreamer class.
#include <DQMLCEventStreamer.h>
Public Member Functions
StatusCode serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize a LCIntVec.
StatusCode deserialize (EVENT::LCObject *&pLCObject, DQMDataStream *const pDataStream)
Deserialize a LCIntVec.
Detailed Description
DQMLCIntVecStreamer class.
Definition at line 260 of file DQMLCEventStreamer.h.
Member Function Documentation
StatusCode dqm4hep::DQMLCIntVecStreamer::deserialize (EVENT::LCObject *& pLCObject, DQMDataStream *const pDataStream)
Deserialize a LCIntVec.
The object is allocated in this function
Definition at line 1278 of file DQMLCEventStreamer.cc.
References dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMDataStream::read(), and THROW_RESULT_IF.
{
  pLCObject = 0;
  EVENT::LCIntVec *pIntVec = new EVENT::LCIntVec();
  try
  {
    dqm_uint nVals = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nVals));
    for(dqm_uint i=0 ; i<nVals ; i++)
    {
      dqm_int value = 0;
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(value));
      pIntVec->push_back(value);
    }
  }
  catch(StatusCodeException &exception)
  {
    delete pIntVec;
    pIntVec = 0;
    pLCObject = 0;
    return exception.getStatusCode();
  }
  pLCObject = pIntVec;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMLCIntVecStreamer::serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize a LCIntVec.
Definition at line 1257 of file DQMLCEventStreamer.cc.
References RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
{
  const EVENT::LCIntVec *const pIntVec = dynamic_cast<const EVENT::LCIntVec *const>(pLCObject);
  if(NULL == pIntVec)
    return STATUS_CODE_INVALID_PARAMETER;
  dqm_uint nVals = pIntVec->size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nVals));
  for(dqm_uint i=0 ; i<nVals ; i++)
  {
    dqm_int value = pIntVec->at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(value));
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMLCEventStreamer.h
DQMLCEventStreamer.cc