dqm4hep::DQMLCParametersStreamer Class Reference
DQMLCParametersStreamer class.
#include <DQMLCEventStreamer.h>
Public Member Functions
StatusCode serialize (const EVENT::LCParameters *const pLCarameters, DQMDataStream *const pDataStream)
Serialize the LCParameters in dataStream.
StatusCode deserialize (EVENT::LCParameters *&pLCParameters, DQMDataStream *const pDataStream)
Deserialize the LCParameters from dataStream.
Detailed Description
DQMLCParametersStreamer class.
Definition at line 56 of file DQMLCEventStreamer.h.
Member Function Documentation
StatusCode dqm4hep::DQMLCParametersStreamer::deserialize (EVENT::LCParameters *& pLCParameters, DQMDataStream *const pDataStream) [virtual]
Deserialize the LCParameters from dataStream.
Implements dqm4hep::DQMStreamer< EVENT::LCParameters > .
Definition at line 403 of file DQMLCEventStreamer.cc.
References dqm4hep::DQMDataStream::read(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMLCEventStreamer::deserialize(), and dqm4hep::DQMLCCollectionStreamer::deserialize().
{
  dqm_int nInt = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nInt));
  if(nInt != 0)
  {
    for(int i=0 ; i<nInt ; i++)
    {
      std::string key;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(key));
      dqm_int vecSize = 0;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(vecSize));
      EVENT::IntVec intValues;
      for(int j=0 ; j<vecSize ; j++)
      {
        dqm_int value = 0;
        RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(value));
        intValues.push_back(value);
      }
      pLCParameters->setValues(key, intValues);
    }
  }
  dqm_int nFloat = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nFloat));
  if(nFloat != 0)
  {
    for(int i=0 ; i<nFloat ; i++)
    {
      std::string key;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(key));
      dqm_int vecSize = 0;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(vecSize));
      EVENT::FloatVec floatValues;
      for(int j=0 ; j<vecSize ; j++)
      {
        dqm_float value = 0.f;
        RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(value));
        floatValues.push_back(value);
      }
      pLCParameters->setValues(key, floatValues);
    }
  }
  dqm_int nString = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nString));
  if(nString != 0)
  {
    for(int i=0 ; i<nString ; i++)
    {
      std::string key;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(key));
      dqm_int vecSize = 0;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(vecSize));
      EVENT::StringVec stringValues;
      for(int j=0 ; j<vecSize ; j++)
      {
        std::string value;
        RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(value));
        stringValues.push_back(value);
      }
      pLCParameters->setValues(key, stringValues);
    }
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMLCParametersStreamer::serialize (const EVENT::LCParameters *const pLCarameters, DQMDataStream *const pDataStream) [virtual]
Serialize the LCParameters in dataStream.
Implements dqm4hep::DQMStreamer< EVENT::LCParameters > .
Definition at line 320 of file DQMLCEventStreamer.cc.
References RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
Referenced by dqm4hep::DQMLCEventStreamer::serialize(), and dqm4hep::DQMLCCollectionStreamer::serialize().
{
  // write int keys/values
  EVENT::StringVec keys;
  pLCParameters->getIntKeys(keys);
  dqm_int nKeys = keys.size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nKeys));
  for(int i=0 ; i<keys.size() ; i++)
  {
    EVENT::IntVec intVec;
    pLCParameters->getIntVals(keys.at(i), intVec);
    std::string key = keys.at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(key));
    dqm_int nKeyParams = intVec.size();
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nKeyParams));
    for(int j=0 ; j<intVec.size() ; j++)
    {
      dqm_int val = intVec.at(j);
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(val));
    }
  }
  // write float keys/values
  keys.clear();
  pLCParameters->getFloatKeys(keys);
  nKeys = keys.size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nKeys));
  for(int i=0 ; i<keys.size() ; i++)
  {
    EVENT::FloatVec floatVec;
    pLCParameters->getFloatVals(keys.at(i), floatVec);
    std::string key = keys.at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(key));
    dqm_int nKeyParams = floatVec.size();
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nKeyParams));
    for(int j=0 ; j<floatVec.size() ; j++)
    {
      dqm_float val = floatVec.at(j);
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(val));
    }
  }
  // write string keys/values
  keys.clear();
  pLCParameters->getStringKeys(keys);
  nKeys = keys.size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nKeys));
  for(int i=0 ; i<keys.size() ; i++)
  {
    EVENT::StringVec stringVec;
    pLCParameters->getStringVals(keys.at(i), stringVec);
    std::string key = keys.at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(key));
    dqm_int nKeyParams = stringVec.size();
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nKeyParams));
    for(int j=0 ; j<stringVec.size() ; j++)
    {
      std::string val = stringVec.at(j);
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(val));
    }
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMLCEventStreamer.h
DQMLCEventStreamer.cc