dqm4hep::TiXmlUnknown Class Reference
Any tag that tinyXml doesn't recognize is saved as an unknown.
#include <tinyxml.h>
Public Member Functions
TiXmlUnknown ()
virtual ~TiXmlUnknown ()
TiXmlUnknown (const TiXmlUnknown &copy)
void operator= (const TiXmlUnknown &copy)
virtual TiXmlNode * Clone () const
Creates a copy of this Unknown and returns it.
virtual void Print (FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *content) const
Walk the XML tree visiting this node and all of its children.
Protected Member Functions
void CopyTo (TiXmlUnknown *target) const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Additional Inherited Members
Detailed Description
Any tag that tinyXml doesn't recognize is saved as an unknown.
It is a tag of text, but should not be modified. It will be written back to the XML, unchanged, when the file is saved.
DTD tags get thrown into TiXmlUnknowns.
Definition at line 1353 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::TiXmlUnknown::TiXmlUnknown () [inline]
Definition at line 1356 of file tinyxml.h.
Referenced by Clone().
: TiXmlNode(TiXmlNode::TINYXML_UNKNOWN) {}
virtual dqm4hep::TiXmlUnknown::~TiXmlUnknown () [inline], [virtual]
Definition at line 1357 of file tinyxml.h.
{}
dqm4hep::TiXmlUnknown::TiXmlUnknown (const TiXmlUnknown & copy) [inline]
Definition at line 1359 of file tinyxml.h.
References CopyTo().
: TiXmlNode(TiXmlNode::TINYXML_UNKNOWN) { copy.CopyTo(this); }
Member Function Documentation
bool dqm4hep::TiXmlUnknown::Accept (TiXmlVisitor * content) const [virtual]
Walk the XML tree visiting this node and all of its children.
Implements dqm4hep::TiXmlNode .
Definition at line 1438 of file tinyxml.cc.
References dqm4hep::TiXmlVisitor::Visit().
{
  return visitor->Visit(*this);
}
TiXmlNode * dqm4hep::TiXmlUnknown::Clone () const [virtual]
Creates a copy of this Unknown and returns it.
Implements dqm4hep::TiXmlNode .
Definition at line 1444 of file tinyxml.cc.
References CopyTo(), and TiXmlUnknown().
{
  TiXmlUnknown* clone = new TiXmlUnknown();
  if (!clone)
    return 0;
  CopyTo(clone);
  return clone;
}
void dqm4hep::TiXmlUnknown::CopyTo (TiXmlUnknown * target) const [protected]
Definition at line 1432 of file tinyxml.cc.
References dqm4hep::TiXmlNode::CopyTo().
Referenced by Clone(), operator=(), and TiXmlUnknown().
{
  TiXmlNode::CopyTo(target);
}
void dqm4hep::TiXmlUnknown::operator= (const TiXmlUnknown & copy) [inline]
Definition at line 1360 of file tinyxml.h.
References CopyTo().
{ copy.CopyTo(this); }
const char * dqm4hep::TiXmlUnknown::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) [virtual]
Implements dqm4hep::TiXmlBase .
Definition at line 1278 of file tinyxmlparser.cc.
References dqm4hep::TiXmlParsingData::Cursor(), dqm4hep::TiXmlNode::GetDocument(), dqm4hep::TiXmlBase::location, dqm4hep::TiXmlDocument::SetError(), dqm4hep::TiXmlBase::SkipWhiteSpace(), dqm4hep::TiXmlParsingData::Stamp(), dqm4hep::TiXmlBase::TIXML_ERROR_PARSING_UNKNOWN, and dqm4hep::TiXmlNode::value.
{
  TiXmlDocument* document = GetDocument();
  p = SkipWhiteSpace(p, encoding);
  if (data)
  {
    data->Stamp(p, encoding);
    location = data->Cursor();
  }
  if (!p || !*p || *p != '<')
  {
    if (document) document->SetError(TIXML_ERROR_PARSING_UNKNOWN, p, data, encoding);
    return 0;
  }
  ++p;
    value = "";
  while (p && *p && *p != '>')
  {
    value += *p;
    ++p;
  }
  if (!p)
  {
    if (document) document->SetError(TIXML_ERROR_PARSING_UNKNOWN, 0, 0, encoding);
  }
  if (*p == '>')
    return p+1;
  return p;
}
void dqm4hep::TiXmlUnknown::Print (FILE * cfile, int depth) const [virtual]
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements dqm4hep::TiXmlBase .
Definition at line 1424 of file tinyxml.cc.
References dqm4hep::TiXmlNode::value.
{
  for (int i=0; i<depth; i++)
    fprintf(cfile, " ");
  fprintf(cfile, "<%s>", value.c_str());
}
virtual void dqm4hep::TiXmlUnknown::StreamIn (std::istream * in, TIXML_STRING * tag) [protected], [virtual]
Implements dqm4hep::TiXmlNode .
virtual const TiXmlUnknown* dqm4hep::TiXmlUnknown::ToUnknown () const [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1369 of file tinyxml.h.
virtual TiXmlUnknown* dqm4hep::TiXmlUnknown::ToUnknown () [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1370 of file tinyxml.h.
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc