dqm4hep::DQMMonitorElementPublication Class Reference
DQMMonitorElementPublication class.
#include <DQMMessaging.h>
Public Member Functions
StatusCode serialize (DQMDataStream *const pDataStream) const
Serialize a monitor element publication and store it in the data stream.
StatusCode deserialize (DQMDataStream *const pDataStream)
De-serialize a monitor element publication from the data stream.
Detailed Description
DQMMonitorElementPublication class.
Definition at line 41 of file DQMMessaging.h.
Member Function Documentation
StatusCode dqm4hep::DQMMonitorElementPublication::deserialize (DQMDataStream *const pDataStream) [virtual]
De-serialize a monitor element publication from the data stream.
Implements dqm4hep::DQMStreamable .
Definition at line 62 of file DQMMessaging.cc.
References dqm4hep::DQMMonitorElement::deserialize(), PROCESS_CODE_IF_AND_RETURN, dqm4hep::DQMDataStream::read(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMMonitorElementClient::infoHandler().
{
  dqm_uint mapSize = 0;
  RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->read(mapSize));
  for(unsigned int i=0 ; i<mapSize ; i++)
  {
    std::string moduleName;
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->read(moduleName));
    dqm_uint meListSize = 0;
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->read(meListSize));
    DQMMonitorElementList meList;
    for(unsigned int i=0 ; i<meListSize ; i++)
    {
      DQMMonitorElement *pMonitorElement = new DQMMonitorElement();
      PROCESS_CODE_IF_AND_RETURN(STATUS_CODE_SUCCESS, !=, pMonitorElement->deserialize(pDataStream),
          delete pMonitorElement;
      );
      meList.push_back(pMonitorElement);
    }
    (*this)[moduleName] = meList;
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementPublication::serialize (DQMDataStream *const pDataStream) const [virtual]
Serialize a monitor element publication and store it in the data stream.
Implements dqm4hep::DQMStreamable .
Definition at line 36 of file DQMMessaging.cc.
References RETURN_RESULT_IF, dqm4hep::DQMMonitorElement::serialize(), and dqm4hep::DQMDataStream::write().
Referenced by dqm4hep::DQMMonitorElementCollector::handleMeQuery(), dqm4hep::DQMMonitorElementCollector::sendMeUpdate(), and dqm4hep::DQMMonitorElementSender::sendMonitorElements().
{
  dqm_uint mapSize = this->size();
  RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->write(mapSize));
  for(std::map<std::string, std::vector<DQMMonitorElement *> >::const_iterator iter = this->begin(),
      endIter = this->end() ;
    endIter != iter ; ++iter)
  {
    std::string moduleName(iter->first);
    DQMMonitorElementList meList(iter->second);
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->write(moduleName));
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->write((
      dqm_uint)meList.size()));
    for(unsigned int i=0 ; i<meList.size() ; i++)
    {
      DQMMonitorElement *pMonitorElement = meList.at(i);
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pMonitorElement->serialize(pDataStream));
    }
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMMessaging.h
DQMMessaging.cc