dqm4hep::DQMParticleIDStreamer Class Reference
DQMParticleIDStreamer class.
#include <DQMLCEventStreamer.h>
Public Member Functions
StatusCode serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize an ParticleID.
StatusCode deserialize (EVENT::LCObject *&pLCObject, DQMDataStream *const pDataStream)
Deserialize a ParticleID.
Detailed Description
DQMParticleIDStreamer class.
Definition at line 226 of file DQMLCEventStreamer.h.
Member Function Documentation
StatusCode dqm4hep::DQMParticleIDStreamer::deserialize (EVENT::LCObject *& pLCObject, DQMDataStream *const pDataStream)
Deserialize a ParticleID.
The object is allocated in this function
Definition at line 1153 of file DQMLCEventStreamer.cc.
References dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMDataStream::read(), and THROW_RESULT_IF.
{
  pLCObject = 0;
  IMPL::ParticleIDImpl *pParticleID = new IMPL::ParticleIDImpl();
  try
  {
    dqm_int type = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(type));
    pParticleID->setType(type);
    dqm_int pdg = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(pdg));
    pParticleID->setPDG(pdg);
    dqm_float likelihood = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(likelihood));
    pParticleID->setLikelihood(likelihood);
    dqm_int algorithmType = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(algorithmType));
    pParticleID->setAlgorithmType(algorithmType);
    dqm_uint nParameters = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nParameters));
    for(dqm_uint i=0 ; i<nParameters ; i++)
    {
      dqm_float parameter = 0;
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(parameter));
      pParticleID->parameters().push_back(parameter);
    }
  }
  catch(StatusCodeException &exception)
  {
    delete pParticleID;
    pParticleID = 0;
    pLCObject = 0;
    return exception.getStatusCode();
  }
  pLCObject = pParticleID;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMParticleIDStreamer::serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize an ParticleID.
Definition at line 1120 of file DQMLCEventStreamer.cc.
References RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
{
  const EVENT::ParticleID *const pParticleID = dynamic_cast<const EVENT::ParticleID *const>(pLCObject);
  if(NULL == pParticleID)
    return STATUS_CODE_INVALID_PARAMETER;
  dqm_int type = pParticleID->getType();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(type));
  dqm_int pdg = pParticleID->getPDG();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(pdg));
  dqm_float likelihood = pParticleID->getLikelihood();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(likelihood));
  dqm_int algorithmType = pParticleID->getAlgorithmType();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(algorithmType));
  dqm_uint nParameters = pParticleID->getParameters().size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nParameters));
  for(dqm_uint i=0 ; i<nParameters ; i++)
  {
    dqm_float parameter = pParticleID->getParameters().at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(parameter));
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMLCEventStreamer.h
DQMLCEventStreamer.cc