dqm4hep::DQMMonitorElementRequest Class Reference
DQMMonitorElementRequest class.
#include <DQMMessaging.h>
Public Member Functions
StatusCode serialize (DQMDataStream *const pDataStream) const
Serialize a monitor element request and store it in the data stream.
StatusCode deserialize (DQMDataStream *const pDataStream)
De-serialize a monitor element request from the data stream.
Detailed Description
DQMMonitorElementRequest class.
Definition at line 160 of file DQMMessaging.h.
Member Function Documentation
StatusCode dqm4hep::DQMMonitorElementRequest::deserialize (DQMDataStream *const pDataStream) [virtual]
De-serialize a monitor element request from the data stream.
Implements dqm4hep::DQMStreamable .
Definition at line 244 of file DQMMessaging.cc.
References dqm4hep::DQMDataStream::read(), and RETURN_RESULT_IF.
{
  dqm_uint requestListSize = 0;
  RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->read(requestListSize));
  for(unsigned int i=0 ; i<requestListSize ; i++)
  {
    value_type requestedPair;
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->read(requestedPair.first));
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->read(requestedPair.second));
    this->push_back(requestedPair);
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementRequest::serialize (DQMDataStream *const pDataStream) const [virtual]
Serialize a monitor element request and store it in the data stream.
Implements dqm4hep::DQMStreamable .
Definition at line 229 of file DQMMessaging.cc.
References RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
Referenced by dqm4hep::DQMMonitorElementClient::querySubscribedMonitorElements(), dqm4hep::DQMMonitorElementClient::replaceSubscription(), dqm4hep::DQMMonitorElementClient::subscribe(), and dqm4hep::DQMMonitorElementClient::unsubscribe().
{
  RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->write((
      dqm_uint)this->size()));
  for(unsigned int i=0 ; i<this->size() ; i++)
  {
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->write(this->at(i).first));
    RETURN_RESULT_IF(dqm4hep::STATUS_CODE_SUCCESS, !=, pDataStream->write(this->at(i).second));
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMMessaging.h
DQMMessaging.cc