dqm4hep::TiXmlText Class Reference
XML text.
#include <tinyxml.h>
Public Member Functions
TiXmlText (const char *initValue)
Constructor for text element.
virtual ~TiXmlText ()
TiXmlText (const std::string &initValue)
Constructor.
TiXmlText (const TiXmlText &copy)
void operator= (const TiXmlText &base)
virtual void Print (FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
bool CDATA () const
Queries whether this represents text using a CDATA section.
void SetCDATA (bool _cdata)
Turns on or off a CDATA representation of text.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *content) const
Walk the XML tree visiting this node and all of its children.
Protected Member Functions
virtual TiXmlNode * Clone () const
[internal use] Creates a new Element and returns it.
void CopyTo (TiXmlText *target) const
bool Blank () const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Private Attributes
bool cdata
Friends
class TiXmlElement
Additional Inherited Members
Detailed Description
XML text.
A text node can have 2 ways to output the next. `normal` output and CDATA. It will default to the mode it was parsed from the XML file and you generally want to leave it alone, but you can change the output mode with SetCDATA() and query it with CDATA().
Definition at line 1211 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::TiXmlText::TiXmlText (const char * initValue) [inline]
Constructor for text element.
By default, it is treated as normal, encoded text. If you want it be output as a CDATA text element, set the parameter _cdata to 'true'
Definition at line 1219 of file tinyxml.h.
References cdata, and dqm4hep::TiXmlNode::SetValue().
Referenced by Clone().
                                      : TiXmlNode (TiXmlNode::TINYXML_TEXT)
  {
    SetValue(initValue);
    cdata = false;
  }
virtual dqm4hep::TiXmlText::~TiXmlText () [inline], [virtual]
Definition at line 1224 of file tinyxml.h.
{}
dqm4hep::TiXmlText::TiXmlText (const std::string & initValue) [inline]
Constructor.
Definition at line 1228 of file tinyxml.h.
                                          : TiXmlNode (TiXmlNode::TINYXML_TEXT)
  {
    SetValue(initValue);
    cdata = false;
  }
dqm4hep::TiXmlText::TiXmlText (const TiXmlText & copy) [inline]
Definition at line 1235 of file tinyxml.h.
References CopyTo().
: TiXmlNode(TiXmlNode::TINYXML_TEXT) { copy.CopyTo(this); }
Member Function Documentation
bool dqm4hep::TiXmlText::Accept (TiXmlVisitor * content) const [virtual]
Walk the XML tree visiting this node and all of its children.
Implements dqm4hep::TiXmlNode .
Definition at line 1317 of file tinyxml.cc.
References dqm4hep::TiXmlVisitor::Visit().
{
  return visitor->Visit(*this);
}
bool dqm4hep::TiXmlText::Blank () const [protected]
Definition at line 1631 of file tinyxmlparser.cc.
References dqm4hep::TiXmlBase::IsWhiteSpace(), and dqm4hep::TiXmlNode::value.
Referenced by dqm4hep::TiXmlElement::ReadValue().
{
  for (unsigned i=0; i<value.length(); i++)
    if (!IsWhiteSpace(value[i]))
      return false;
  return true;
}
bool dqm4hep::TiXmlText::CDATA () const [inline]
Queries whether this represents text using a CDATA section.
Definition at line 1242 of file tinyxml.h.
References cdata.
Referenced by dqm4hep::TiXmlPrinter::Visit(), and dqm4hep::TiXmlPrinter::VisitEnter().
{ return cdata; }
TiXmlNode * dqm4hep::TiXmlText::Clone () const [protected], [virtual]
[internal use] Creates a new Element and returns it.
Implements dqm4hep::TiXmlNode .
Definition at line 1323 of file tinyxml.cc.
References CopyTo(), and TiXmlText().
{
  TiXmlText* clone = 0;
  clone = new TiXmlText("");
  if (!clone)
    return 0;
  CopyTo(clone);
  return clone;
}
void dqm4hep::TiXmlText::CopyTo (TiXmlText * target) const [protected]
Definition at line 1310 of file tinyxml.cc.
References cdata, and dqm4hep::TiXmlNode::CopyTo().
Referenced by Clone(), operator=(), and TiXmlText().
{
  TiXmlNode::CopyTo(target);
  target->cdata = cdata;
}
void dqm4hep::TiXmlText::operator= (const TiXmlText & base) [inline]
Definition at line 1236 of file tinyxml.h.
References CopyTo().
{ base.CopyTo(this); }
const char * dqm4hep::TiXmlText::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) [virtual]
Implements dqm4hep::TiXmlBase .
Definition at line 1498 of file tinyxmlparser.cc.
References cdata, dqm4hep::TiXmlParsingData::Cursor(), dqm4hep::TiXmlNode::GetDocument(), dqm4hep::TiXmlBase::location, dqm4hep::TiXmlBase::ReadText(), dqm4hep::TiXmlDocument::SetError(), dqm4hep::TiXmlParsingData::Stamp(), dqm4hep::TiXmlBase::StringEqual(), dqm4hep::TiXmlBase::TIXML_ERROR_PARSING_CDATA, TIXML_STRING, and dqm4hep::TiXmlNode::value.
Referenced by dqm4hep::TiXmlElement::ReadValue().
{
  value = "";
  TiXmlDocument* document = GetDocument();
  if (data)
  {
    data->Stamp(p, encoding);
    location = data->Cursor();
  }
  const char* const startTag = "<![CDATA[";
  const char* const endTag = "]]>";
  if (cdata || StringEqual(p, startTag, false, encoding))
  {
    cdata = true;
    if (!StringEqual(p, startTag, false, encoding))
    {
      document->SetError(TIXML_ERROR_PARSING_CDATA, p, data, encoding);
      return 0;
    }
    p += strlen(startTag);
    // Keep all the white space, ignore the encoding, etc.
    while (p && *p
        && !StringEqual(p, endTag, false, encoding)
        )
    {
      value += *p;
      ++p;
    }
    TIXML_STRING dummy;
    p = ReadText(p, &dummy, false, endTag, false, encoding);
    return p;
  }
  else
  {
    bool ignoreWhite = true;
    const char* end = "<";
    p = ReadText(p, &value, ignoreWhite, end, false, encoding);
    if (p)
      return p-1; // don't truncate the '<'
    return 0;
  }
}
void dqm4hep::TiXmlText::Print (FILE * cfile, int depth) const [virtual]
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements dqm4hep::TiXmlBase .
Definition at line 1289 of file tinyxml.cc.
References cdata, dqm4hep::TiXmlBase::EncodeString(), TIXML_STRING, and dqm4hep::TiXmlNode::value.
{
  assert(cfile);
  if (cdata)
  {
    int i;
    fprintf(cfile, "\n");
    for (i=0; i<depth; i++) {
      fprintf(cfile, " ");
    }
    fprintf(cfile, "<![CDATA[%s]]>\n", value.c_str()); // unformatted output
  }
  else
  {
    TIXML_STRING buffer;
    EncodeString(value, &buffer);
    fprintf(cfile, "%s", buffer.c_str());
  }
}
void dqm4hep::TiXmlText::SetCDATA (bool _cdata) [inline]
Turns on or off a CDATA representation of text.
Definition at line 1244 of file tinyxml.h.
References cdata.
Referenced by dqm4hep::TiXmlNode::Identify().
{ cdata = _cdata; }
virtual void dqm4hep::TiXmlText::StreamIn (std::istream * in, TIXML_STRING * tag) [protected], [virtual]
Implements dqm4hep::TiXmlNode .
virtual const TiXmlText* dqm4hep::TiXmlText::ToText () const [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1248 of file tinyxml.h.
virtual TiXmlText* dqm4hep::TiXmlText::ToText () [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1249 of file tinyxml.h.
Friends And Related Function Documentation
friend class TiXmlElement [friend]
Definition at line 1213 of file tinyxml.h.
Member Data Documentation
bool dqm4hep::TiXmlText::cdata [private]
Definition at line 1267 of file tinyxml.h.
Referenced by CDATA(), CopyTo(), Parse(), Print(), SetCDATA(), and TiXmlText().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc