dqm4hep::DQMDataStream Class Reference
DQMDataStream class.
#include <DQMDataStream.h>
Public Member Functions
DQMDataStream (dqm_uint maxBufferSize)
Constructor with an initial buffer size.
virtual ~DQMDataStream ()
Destructor.
void reset ()
Reset the buffer ptr to beginning of the buffer.
char * getBuffer () const
Get the buffer.
StatusCode setBuffer (char *pBuffer, dqm_uint size)
Set the buffer with its size.
dqm_uint getMaxBufferSize () const
Get the maximum size of the allocated buffer.
dqm_uint getBufferSize () const
Get the current buffer size.
dqm_uint getAvailableSize () const
Get remaining size in the buffer.
bool isValid () const
Whether the buffer is valid.
StatusCode seek (dqm_uint pos=0)
Seek the current buffer ptr to given position (in bytes)
template<typename T >
StatusCode write (const T &value)
template<typename T >
StatusCode write (const T *pValue, dqm_uint nVals)
template<typename T >
StatusCode read (T &value)
template<typename T >
StatusCode read (T *&pValue, dqm_uint &nVals)
StatusCode writeAddress (const void *&pAddress)
StatusCode readAddress (void *&pAddress)
template<>
StatusCode write (const std::string &value)
template<>
StatusCode read (dqm_char *&pValue, dqm_uint &nVals)
template<>
StatusCode read (std::string &value)
Protected Member Functions
StatusCode reallocBuffer (dqm_uint newSize, bool copyCurrentBuffer=true)
Reallocate the buffer with a new size.
Protected Attributes
dqm_uint m_maxBufferSize
char * m_pBuffer
char * m_pBufferPtr
dqm_uint m_bufferSize
bool m_isValid
Detailed Description
DQMDataStream class.
Definition at line 42 of file DQMDataStream.h.
Constructor & Destructor Documentation
dqm4hep::DQMDataStream::DQMDataStream (dqm_uint maxBufferSize)
Constructor with an initial buffer size.
The buffer can be reallocated if there is not enough place to write bytes. Then maxBufferSize will change according to needed size
Definition at line 37 of file DQMDataStream.cc.
References m_pBuffer, and m_pBufferPtr.
                                                   :
    m_maxBufferSize(maxBufferSize),
    m_isValid(false),
    m_bufferSize(0)
{
  m_pBuffer = new char[maxBufferSize];
  m_pBufferPtr = m_pBuffer;
  memset(m_pBuffer, 0, maxBufferSize);
}
dqm4hep::DQMDataStream::~DQMDataStream () [virtual]
Destructor.
Definition at line 49 of file DQMDataStream.cc.
References m_pBuffer, and m_pBufferPtr.
{
  delete [] m_pBuffer;
  m_pBuffer = NULL;
  m_pBufferPtr = NULL;
}
Member Function Documentation
dqm_uint dqm4hep::DQMDataStream::getAvailableSize () const
Get remaining size in the buffer.
Definition at line 127 of file DQMDataStream.cc.
References getBufferSize(), and getMaxBufferSize().
{
  return getMaxBufferSize() - getBufferSize();
}
char * dqm4hep::DQMDataStream::getBuffer () const
Get the buffer.
Definition at line 75 of file DQMDataStream.cc.
References m_pBuffer.
Referenced by dqm4hep::DQMMonitorElementSender::connectToService(), dqm4hep::DQMRunControlService::endCurrentRun(), dqm4hep::DQMRunControlService::handleCurrentRunRpc(), dqm4hep::DQMDimEventCollector::handleEventRequest(), dqm4hep::DQMMonitorElementCollector::handleMeQuery(), dqm4hep::DQMMonitorElementCollector::notifyWatchedMe(), dqm4hep::DQMMonitorElementClient::queryAvailableMonitorElements(), dqm4hep::DQMMonitorElementClient::querySubscribedMonitorElements(), dqm4hep::DQMMonitorElementClient::replaceSubscription(), dqm4hep::DQMMonitorElementNameListRpc::rpcHandler(), dqm4hep::DQMMonitorElementCollectorInfoRpc::rpcHandler(), dqm4hep::DQMMonitorElementSender::sendAvailableMonitorElementList(), dqm4hep::DQMDimEventClient::sendEvent(), dqm4hep::DQMMonitorElementCollector::sendMeUpdate(), dqm4hep::DQMMonitorElementSender::sendMonitorElements(), dqm4hep::DQMRunControlService::start(), dqm4hep::DQMMonitorElementCollector::start(), dqm4hep::DQMDimEventCollector::startCollector(), dqm4hep::DQMRunControlService::startNewRun(), dqm4hep::DQMMonitorElementClient::subscribe(), dqm4hep::DQMMonitorElementClient::unsubscribe(), and dqm4hep::DQMDimEventCollector::updateEventService().
{
  return m_pBuffer;
}
dqm_uint dqm4hep::DQMDataStream::getBufferSize () const
Get the current buffer size.
Definition at line 120 of file DQMDataStream.cc.
References m_bufferSize.
Referenced by dqm4hep::DQMMonitorElementSender::connectToService(), dqm4hep::DQMRunControlService::endCurrentRun(), getAvailableSize(), dqm4hep::DQMRunControlService::handleCurrentRunRpc(), dqm4hep::DQMDimEventCollector::handleEventRequest(), dqm4hep::DQMMonitorElementCollector::handleMeQuery(), dqm4hep::DQMMonitorElementCollector::notifyWatchedMe(), dqm4hep::DQMMonitorElementClient::queryAvailableMonitorElements(), dqm4hep::DQMMonitorElementClient::querySubscribedMonitorElements(), reallocBuffer(), dqm4hep::DQMMonitorElementClient::replaceSubscription(), dqm4hep::DQMMonitorElementNameListRpc::rpcHandler(), dqm4hep::DQMMonitorElementCollectorInfoRpc::rpcHandler(), seek(), dqm4hep::DQMMonitorElementSender::sendAvailableMonitorElementList(), dqm4hep::DQMDimEventClient::sendEvent(), dqm4hep::DQMMonitorElementCollector::sendMeUpdate(), dqm4hep::DQMMonitorElementSender::sendMonitorElements(), dqm4hep::DQMRunControlService::start(), dqm4hep::DQMMonitorElementCollector::start(), dqm4hep::DQMDimEventCollector::startCollector(), dqm4hep::DQMRunControlService::startNewRun(), dqm4hep::DQMMonitorElementClient::subscribe(), dqm4hep::DQMMonitorElementClient::unsubscribe(), dqm4hep::DQMDimEventCollector::updateEventService(), and write().
{
  return m_bufferSize;
}
dqm_uint dqm4hep::DQMDataStream::getMaxBufferSize () const
Get the maximum size of the allocated buffer.
Definition at line 113 of file DQMDataStream.cc.
References m_maxBufferSize.
Referenced by getAvailableSize(), setBuffer(), and write().
{
  return m_maxBufferSize;
}
bool dqm4hep::DQMDataStream::isValid () const
Whether the buffer is valid.
Returns true if the set buffer has been called after a reset call
Definition at line 68 of file DQMDataStream.cc.
References m_bufferSize.
Referenced by dqm4hep::DQMLCEventStreamer::deserialize().
{
  return (m_bufferSize != 0);
}
template<typename T > StatusCode dqm4hep::DQMDataStream::read (T & value) [inline]
Definition at line 212 of file DQMDataStream.h.
References m_pBufferPtr.
Referenced by dqm4hep::DQMMonitorElementPublication::deserialize(), dqm4hep::DQMQualityTestResult::deserialize(), dqm4hep::DQMLCParametersStreamer::deserialize(), dqm4hep::DQMMonitorElementInfo::deserialize(), dqm4hep::DQMVersion::deserialize(), dqm4hep::DQMMonitorElementInfoList::deserialize(), dqm4hep::DQMLCEventStreamer::deserialize(), dqm4hep::DQMCollectorInfo::deserialize(), dqm4hep::DQMRun::deserialize(), dqm4hep::DQMLCCollectionStreamer::deserialize(), dqm4hep::DQMMonitorElementListNameRequest::deserialize(), dqm4hep::DQMLCGenericObjectStreamer::deserialize(), dqm4hep::DQMCalorimeterHitStreamer::deserialize(), dqm4hep::DQMMonitorElementRequest::deserialize(), dqm4hep::DQMRawCalorimeterHitStreamer::deserialize(), dqm4hep::DQMTPCHitStreamer::deserialize(), dqm4hep::DQMClusterStreamer::deserialize(), dqm4hep::DQMParticleIDStreamer::deserialize(), dqm4hep::DQMLCFloatVecStreamer::deserialize(), dqm4hep::DQMLCIntVecStreamer::deserialize(), dqm4hep::DQMLCStrVecStreamer::deserialize(), dqm4hep::DQMMonitorElementCollector::handleAvailableListUpdate(), dqm4hep::DQMMonitorElementSender::infoHandler(), and readAddress().
{
  dqm_uint *pCurrBuff = (dqm_uint *) m_pBufferPtr;
  // get the size of the next values to read
  dqm_uint size = pCurrBuff[0] & 0xFFFFFF;
  if(sizeof(T) != size)
    return STATUS_CODE_INVALID_PARAMETER;
  // increment the buffer ptr
  m_pBufferPtr += sizeof(dqm_uint);
  // read and copy the asked buffer region
  memcpy(&value, m_pBufferPtr, size);
  // increment the buffer ptr
  m_pBufferPtr += size;
  return STATUS_CODE_SUCCESS;
}
template<typename T > StatusCode dqm4hep::DQMDataStream::read (T *& pValue, dqm_uint & nVals) [inline]
Definition at line 269 of file DQMDataStream.h.
References m_pBufferPtr.
{
  pValue = NULL;
  dqm_uint *pCurrBuff = (dqm_uint *) m_pBufferPtr;
  // get the size of the next values to read
  dqm_uint size = pCurrBuff[0] & 0xFFFFFF;
  if(size%sizeof(T) != 0)
    return STATUS_CODE_INVALID_PARAMETER;
  // valid operation because of the previous check
  nVals = size/sizeof(T);
  // increment the buffer ptr
  m_pBufferPtr += sizeof(dqm_uint);
  // valid even if size is 0, then nothing happens while copying memory
  pValue = new T[nVals];
  // read and copy the asked buffer region
  memcpy(pValue, m_pBufferPtr, size);
  // increment the buffer ptr
  m_pBufferPtr += size;
  return STATUS_CODE_SUCCESS;
}
template<> StatusCode dqm4hep::DQMDataStream::read (dqm_char *& pValue, dqm_uint & nVals) [inline]
Definition at line 184 of file DQMDataStream.h.
References m_pBufferPtr.
{
  dqm_uint *pCurrBuff = (dqm_uint *) m_pBufferPtr;
  // get the size of the next values to read
  dqm_uint size = pCurrBuff[0] & 0xFFFFFF;
  nVals = size;
  // increment the buffer ptr
  m_pBufferPtr += sizeof(dqm_uint);
  // allocate the new buffer
  pValue = new dqm_char[size+1];
  pValue[size] = '\0';
  memset(pValue, 0, size);
  // read and copy the asked buffer region
  memcpy(pValue, m_pBufferPtr, size);
  // increment the buffer ptr
  m_pBufferPtr += size;
  return STATUS_CODE_SUCCESS;
}
template<> StatusCode dqm4hep::DQMDataStream::read (std::string & value) [inline]
Definition at line 237 of file DQMDataStream.h.
References m_pBufferPtr.
{
  dqm_uint *pCurrBuff = (dqm_uint *) m_pBufferPtr;
  // get the size of the next values to read
  dqm_uint size = pCurrBuff[0] & 0xFFFFFF;
  char *pString = NULL;
  StatusCode statusCode = read<char>(pString, size);
  if(STATUS_CODE_SUCCESS != statusCode)
  {
    delete [] pString;
    return statusCode;
  }
  if(NULL == pString)
    return STATUS_CODE_FAILURE;
  if(0 == size)
    value.clear();
  else
    value = pString;
  delete [] pString;
  
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDataStream::readAddress (void *& pAddress)
Definition at line 179 of file DQMDataStream.cc.
References read(), and RETURN_RESULT_IF.
{
  dqm_int address;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->read(address));
  pAddress = reinterpret_cast<void *>(address);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDataStream::reallocBuffer (dqm_uint newSize, bool copyCurrentBuffer = true) [protected]
Reallocate the buffer with a new size.
The buffer is copied if the flag is true (default)
Definition at line 134 of file DQMDataStream.cc.
References getBufferSize(), m_maxBufferSize, m_pBuffer, m_pBufferPtr, and seek().
Referenced by setBuffer(), and write().
{
  dqm_uint bufferSize = getBufferSize();
  dqm_uint currentPos = m_pBufferPtr - m_pBuffer;
  // can not shrink the current buffer or allocate 0 size buffer
  if(newSize < bufferSize || 0 == newSize)
    return STATUS_CODE_NOT_ALLOWED;
  char *pNewBuffer = new char[newSize];
  if(NULL != m_pBuffer)
  {
    if(copyCurrentBuffer && 0 != bufferSize)
    {
      memcpy(pNewBuffer, m_pBuffer, bufferSize);
    }
    else
    {
      memset(pNewBuffer, 0, newSize);
    }
    delete [] m_pBuffer;
  }
  else
  {
    memset(pNewBuffer, 0, newSize);
  }
  m_pBuffer = pNewBuffer;
  m_maxBufferSize = newSize;
  seek(currentPos);
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMDataStream::reset ()
Reset the buffer ptr to beginning of the buffer.
Definition at line 58 of file DQMDataStream.cc.
References m_bufferSize, m_isValid, m_maxBufferSize, m_pBuffer, and m_pBufferPtr.
Referenced by dqm4hep::DQMRunControlService::endCurrentRun(), dqm4hep::DQMMonitorElementCollector::handleAvailableListUpdate(), dqm4hep::DQMMonitorElementCollector::handleClientRequestList(), dqm4hep::DQMMonitorElementCollector::handleClientSubscription(), dqm4hep::DQMMonitorElementCollector::handleClientUnsubscription(), dqm4hep::DQMRunControlService::handleCurrentRunRpc(), dqm4hep::DQMDimRunControlClient::handleCurrentRunRpcInfo(), dqm4hep::DQMDimEventCollector::handleEventRequest(), dqm4hep::DQMMonitorElementClient::handleMeCollectorInfoRpcInfo(), dqm4hep::DQMMonitorElementCollector::handleMeCollectUpdate(), dqm4hep::DQMMonitorElementClient::handleMeListNameRpcInfo(), dqm4hep::DQMMonitorElementCollector::handleMeQuery(), dqm4hep::DQMMonitorElementSender::infoHandler(), dqm4hep::DQMDimRunControlClient::infoHandler(), dqm4hep::DQMMonitorElementClient::infoHandler(), dqm4hep::DQMMonitorElementCollector::notifyWatchedMe(), dqm4hep::DQMMonitorElementClient::queryAvailableMonitorElements(), dqm4hep::DQMMonitorElementClient::querySubscribedMonitorElements(), dqm4hep::DQMMonitorElementClient::replaceSubscription(), dqm4hep::DQMMonitorElementNameListRpc::rpcHandler(), dqm4hep::DQMMonitorElementCollectorInfoRpc::rpcHandler(), dqm4hep::DQMMonitorElementSender::sendAvailableMonitorElementList(), dqm4hep::DQMDimEventClient::sendEvent(), dqm4hep::DQMMonitorElementCollector::sendMeUpdate(), dqm4hep::DQMMonitorElementSender::sendMonitorElements(), setBuffer(), dqm4hep::DQMRunControlService::startNewRun(), dqm4hep::DQMDimEventCollector::stopCollector(), dqm4hep::DQMMonitorElementClient::subscribe(), dqm4hep::DQMMonitorElementClient::unsubscribe(), and dqm4hep::DQMDimEventCollector::updateEventService().
{
  m_pBufferPtr = m_pBuffer;
  memset(m_pBuffer, 0, m_maxBufferSize);
  m_bufferSize = 0;
  m_isValid = false;
}
StatusCode dqm4hep::DQMDataStream::seek (dqm_uint pos = 0)
Seek the current buffer ptr to given position (in bytes)
Definition at line 101 of file DQMDataStream.cc.
References getBufferSize(), m_pBuffer, and m_pBufferPtr.
Referenced by reallocBuffer().
{
  if(pos > getBufferSize())
    return STATUS_CODE_INVALID_PARAMETER;
  m_pBufferPtr = m_pBuffer + pos;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDataStream::setBuffer (char * pBuffer, dqm_uint size)
Set the buffer with its size.
Definition at line 82 of file DQMDataStream.cc.
References getMaxBufferSize(), m_bufferSize, m_isValid, m_pBuffer, m_pBufferPtr, reallocBuffer(), reset(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMDimEventClient::eventReception(), dqm4hep::DQMMonitorElementCollector::handleAvailableListUpdate(), dqm4hep::DQMMonitorElementCollector::handleClientRequestList(), dqm4hep::DQMMonitorElementCollector::handleClientSubscription(), dqm4hep::DQMMonitorElementCollector::handleClientUnsubscription(), dqm4hep::DQMDimRunControlClient::handleCurrentRunRpcInfo(), dqm4hep::DQMDimEventCollector::handleEventReception(), dqm4hep::DQMMonitorElementClient::handleMeCollectorInfoRpcInfo(), dqm4hep::DQMMonitorElementCollector::handleMeCollectUpdate(), dqm4hep::DQMMonitorElementClient::handleMeListNameRpcInfo(), dqm4hep::DQMMonitorElementCollector::handleMeQuery(), dqm4hep::DQMMonitorElementSender::infoHandler(), dqm4hep::DQMDimRunControlClient::infoHandler(), dqm4hep::DQMMonitorElementClient::infoHandler(), dqm4hep::DQMDimEventClient::queryEvent(), and dqm4hep::DQMMonitorElementNameListRpc::rpcHandler().
{
  if(size > this->getMaxBufferSize())
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, reallocBuffer(size, false));
  }
  else
    reset();
  memcpy(m_pBuffer, pBuffer, size);
  m_bufferSize = size;
  m_isValid = true;
  m_pBufferPtr = m_pBuffer;
  return STATUS_CODE_SUCCESS;
}
template<typename T > StatusCode dqm4hep::DQMDataStream::write (const T & value) [inline]
Definition at line 127 of file DQMDataStream.h.
Referenced by dqm4hep::DQMClusterStreamer::deserialize(), dqm4hep::DQMDimEventCollector::DQMDimEventCollector(), dqm4hep::DQMMonitorElementCollector::DQMMonitorElementCollector(), dqm4hep::DQMMonitorElementCollector::notifyWatchedMe(), dqm4hep::DQMMonitorElementSender::sendAvailableMonitorElementList(), dqm4hep::DQMMonitorElementSender::sendMonitorElements(), dqm4hep::DQMMonitorElementPublication::serialize(), dqm4hep::DQMLCParametersStreamer::serialize(), dqm4hep::DQMQualityTestResult::serialize(), dqm4hep::DQMMonitorElementInfo::serialize(), dqm4hep::DQMVersion::serialize(), dqm4hep::DQMMonitorElementInfoList::serialize(), dqm4hep::DQMLCEventStreamer::serialize(), dqm4hep::DQMCollectorInfo::serialize(), dqm4hep::DQMRun::serialize(), dqm4hep::DQMLCCollectionStreamer::serialize(), dqm4hep::DQMMonitorElementListNameRequest::serialize(), dqm4hep::DQMLCGenericObjectStreamer::serialize(), dqm4hep::DQMCalorimeterHitStreamer::serialize(), dqm4hep::DQMMonitorElementRequest::serialize(), dqm4hep::DQMRawCalorimeterHitStreamer::serialize(), dqm4hep::DQMTPCHitStreamer::serialize(), dqm4hep::DQMClusterStreamer::serialize(), dqm4hep::DQMParticleIDStreamer::serialize(), dqm4hep::DQMLCFloatVecStreamer::serialize(), dqm4hep::DQMLCIntVecStreamer::serialize(), dqm4hep::DQMLCStrVecStreamer::serialize(), dqm4hep::DQMDimEventCollector::stopCollector(), and writeAddress().
{
  return write<T>(&value, 1);
}
template<typename T > StatusCode dqm4hep::DQMDataStream::write (const T * pValue, dqm_uint nVals) [inline]
Definition at line 143 of file DQMDataStream.h.
References getBufferSize(), getMaxBufferSize(), m_bufferSize, m_maxBufferSize, m_pBufferPtr, reallocBuffer(), and RETURN_RESULT_IF.
{
  if(NULL == pValue)
    return STATUS_CODE_INVALID_PARAMETER;
  dqm_uint size = sizeof(T)*nVals;
  dqm_uint availableSize = getMaxBufferSize() - getBufferSize();
  if(availableSize <= size+sizeof(dqm_uint))
  {
    dqm_uint newSize = m_maxBufferSize + 1*1024*1024;
    if(size + sizeof(dqm_uint) > 1*1024*1024)
      newSize = size + sizeof(dqm_uint);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, reallocBuffer(newSize));
  }
  // get the current buffer ptr
  dqm_uint *pCurrBuff = (dqm_uint *) m_pBufferPtr;
  // write the packet size
  pCurrBuff[0] = size;
  // increment the buffer
  m_pBufferPtr += sizeof(dqm_uint);
  m_bufferSize += sizeof(dqm_uint);
  // write the packet in the buffer
  memcpy(m_pBufferPtr, (const void*)pValue, size);
  // increment again the buffer
  m_pBufferPtr += size;
  m_bufferSize += size;
  return STATUS_CODE_SUCCESS;
}
template<> StatusCode dqm4hep::DQMDataStream::write (const std::string & value) [inline]
Definition at line 135 of file DQMDataStream.h.
{
  return write<char>(value.c_str(), value.size());
}
StatusCode dqm4hep::DQMDataStream::writeAddress (const void *& pAddress)
Definition at line 172 of file DQMDataStream.cc.
References write().
{
  return this->write(reinterpret_cast<dqm_int>(pAddress));
}
Member Data Documentation
dqm_uint dqm4hep::DQMDataStream::m_bufferSize [protected]
Definition at line 119 of file DQMDataStream.h.
Referenced by getBufferSize(), isValid(), reset(), setBuffer(), and write().
bool dqm4hep::DQMDataStream::m_isValid [protected]
Definition at line 120 of file DQMDataStream.h.
Referenced by reset(), and setBuffer().
dqm_uint dqm4hep::DQMDataStream::m_maxBufferSize [protected]
Definition at line 116 of file DQMDataStream.h.
Referenced by getMaxBufferSize(), reallocBuffer(), reset(), and write().
char* dqm4hep::DQMDataStream::m_pBuffer [protected]
Definition at line 117 of file DQMDataStream.h.
Referenced by DQMDataStream(), getBuffer(), reallocBuffer(), reset(), seek(), setBuffer(), and ~DQMDataStream().
char* dqm4hep::DQMDataStream::m_pBufferPtr [protected]
Definition at line 118 of file DQMDataStream.h.
Referenced by DQMDataStream(), read(), reallocBuffer(), reset(), seek(), setBuffer(), write(), and ~DQMDataStream().
The documentation for this class was generated from the following files:
DQMDataStream.h
DQMDataStream.cc