dqm4hep::DQMArchiver Class Reference
DQMArchiver class.
#include <DQMArchiver.h>
Public Member Functions
DQMArchiver ()
Constructor.
DQMArchiver (const std::string &archiveFileName, const std::string &openingMode=`RECREATE`)
Constructor with file name and opening mode.
virtual ~DQMArchiver ()
Destructor.
StatusCode open (const std::string &archiveFileName, const std::string &openingMode=`RECREATE`)
Open a new archive.
StatusCode close ()
Close the current archive.
StatusCode archive (DQMModule *pModule, bool archiveAll=true)
Archive the monitor element list of the given module Monitor elements that are set to `non-publish` can be written passing the flag to true (default)
StatusCode archive (DQMStorage *pStorage, TDirectory *pDirectory)
Archive the current state of the storage in the root TDirectory.
const std::string & getFileName () const
Get the file name.
bool isOpened () const
Whether the archive is opened.
const std::string & getOpeningMode () const
Get the opening mode of this archive.
Protected Member Functions
StatusCode recursiveFill (DQMDirectory *pDirectory, TDirectory *pROOTDir)
Fill recursively the TDirectory with the DQMDirectory.
StatusCode createTDirectories (DQMDirectory *pDirectory, TDirectory *pROOTDir)
Create TDirectories as labeled in the DQMDirectory.
StatusCode writeMonitorElements (DQMDirectory *pDirectory, TDirectory *pROOTDir)
Write the monitor elements contained in the DQMDirectory in the TDirectory.
Private Attributes
std::string m_fileName
std::string m_openingMode
bool m_isOpened
bool m_firstArchive
TFile * m_pArchiveFile
Friends
class DQMMonitorElementManager
Detailed Description
DQMArchiver class.
Definition at line 50 of file DQMArchiver.h.
Constructor & Destructor Documentation
dqm4hep::DQMArchiver::DQMArchiver ()
Constructor.
Definition at line 49 of file DQMArchiver.cc.
                         :
    m_fileName(""),
    m_openingMode(""),
    m_pArchiveFile(NULL),
    m_isOpened(false),
    m_firstArchive(true)
{
  /* nop */
}
dqm4hep::DQMArchiver::DQMArchiver (const std::string & archiveFileName, const std::string & openingMode = `RECREATE`)
Constructor with file name and opening mode.
Definition at line 61 of file DQMArchiver.cc.
References open(), and THROW_RESULT_IF.
{
  THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, open(archiveFileName, openingMode));
}
dqm4hep::DQMArchiver::~DQMArchiver () [virtual]
Destructor.
Definition at line 68 of file DQMArchiver.cc.
References close(), and m_isOpened.
{
  if(m_isOpened)
    close();
}
Member Function Documentation
StatusCode dqm4hep::DQMArchiver::archive (DQMModule * pModule, bool archiveAll = true)
Archive the monitor element list of the given module Monitor elements that are set to `non-publish` can be written passing the flag to true (default)
Definition at line 146 of file DQMArchiver.cc.
References dqm4hep::DQMModule::getDetectorName(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModule::getName(), dqm4hep::DQMMonitorElementManager::getStorage(), dqm4hep::DQMModule::getVersion(), isOpened(), m_firstArchive, m_pArchiveFile, dqm4hep::MESSAGE, RETURN_RESULT_IF, and dqm4hep::DQMVersion::toString().
Referenced by dqm4hep::DQMStandaloneModuleApplication::run(), and dqm4hep::DQMAnalysisModuleApplication::run().
{
  if(!isOpened())
    return STATUS_CODE_NOT_INITIALIZED;
  streamlog_out(MESSAGE) << "Archiving monitor elements of module : " << pModule->getName() << std::endl;
  // archive directory
  m_pArchiveFile->cd();
  TDirectory *pArchiveDirectory = m_pArchiveFile->GetDirectory("root");
  if(pArchiveDirectory)
    m_pArchiveFile->rmdir("root");
  pArchiveDirectory = m_pArchiveFile->mkdir("root");
  if(!pArchiveDirectory)
    return STATUS_CODE_FAILURE;
  if(m_firstArchive)
  {
    // write module info in the file
    TObjString *pModuleNameString = new TObjString();
    pModuleNameString->SetString(pModule->getName().c_str());
    m_pArchiveFile->WriteTObject(pModuleNameString);
    delete pModuleNameString;
    TObjString *pModuleVersionString = new TObjString();
    pModuleVersionString->SetString(pModule->getVersion().toString().c_str());
    m_pArchiveFile->WriteTObject(pModuleVersionString);
    delete pModuleVersionString;
    TObjString *pModuleDetectorString = new TObjString();
    pModuleDetectorString->SetString(pModule->getDetectorName().c_str());
    m_pArchiveFile->WriteTObject(pModuleDetectorString);
    delete pModuleDetectorString;
    m_firstArchive = false;
  }
  // get the storage of the module
  DQMStorage *pStorage = pModule->getModuleApplication()->getMonitorElementManager()->getStorage();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, archive(pStorage, pArchiveDirectory));
  delete pArchiveDirectory;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMArchiver::archive (DQMStorage * pStorage, TDirectory * pDirectory)
Archive the current state of the storage in the root TDirectory.
Definition at line 199 of file DQMArchiver.cc.
References dqm4hep::DQMStorage::getRootDirectory(), m_pArchiveFile, recursiveFill(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, recursiveFill(pStorage->getRootDirectory(), pDirectory));
  m_pArchiveFile->cd();
  m_pArchiveFile->Write();
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMArchiver::close ()
Close the current archive.
Definition at line 127 of file DQMArchiver.cc.
References m_firstArchive, m_isOpened, m_openingMode, and m_pArchiveFile.
Referenced by open(), dqm4hep::DQMStandaloneModuleApplication::run(), dqm4hep::DQMAnalysisModuleApplication::run(), and ~DQMArchiver().
{
  if(!m_isOpened)
    return STATUS_CODE_FAILURE;
  m_pArchiveFile->Close();
  delete m_pArchiveFile;
  m_pArchiveFile = NULL;
  m_isOpened = false;
  m_firstArchive = false;
  m_openingMode = "";
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMArchiver::createTDirectories (DQMDirectory * pDirectory, TDirectory * pROOTDir) [protected]
Create TDirectories as labeled in the DQMDirectory.
const std::string & dqm4hep::DQMArchiver::getFileName () const
Get the file name.
Definition at line 211 of file DQMArchiver.cc.
References m_fileName.
Referenced by dqm4hep::DQMStandaloneModuleApplication::run(), and dqm4hep::DQMAnalysisModuleApplication::run().
{
  return m_fileName;
}
const std::string & dqm4hep::DQMArchiver::getOpeningMode () const
Get the opening mode of this archive.
Definition at line 225 of file DQMArchiver.cc.
References m_openingMode.
{
  return m_openingMode;
}
bool dqm4hep::DQMArchiver::isOpened () const
Whether the archive is opened.
Definition at line 218 of file DQMArchiver.cc.
References m_isOpened.
Referenced by archive().
{
  return m_isOpened;
}
StatusCode dqm4hep::DQMArchiver::open (const std::string & archiveFileName, const std::string & openingMode = `RECREATE`)
Open a new archive.
Close the current file if opened. Supported opening mode are the TFile opening mode option (see TFile)
Definition at line 76 of file DQMArchiver.cc.
References close(), m_fileName, m_firstArchive, m_isOpened, m_openingMode, m_pArchiveFile, RETURN_RESULT_IF, and dqm4hep::WARNING.
Referenced by DQMArchiver(), dqm4hep::DQMStandaloneModuleApplication::run(), and dqm4hep::DQMAnalysisModuleApplication::run().
{
  // if already open write the archive if not done
  // and close it before to re-open
  if(m_isOpened)
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, close());
  if(archiveFileName.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  std::string fullArchiveName;
  std::string baseArchiveName;
  if(archiveFileName.size() > 5 && archiveFileName.substr(archiveFileName.size()-5) == ".root")
  {
    fullArchiveName = archiveFileName;
    baseArchiveName = archiveFileName.substr(0, archiveFileName.size()-5);
  }
  else
  {
    fullArchiveName = archiveFileName + ".root";
    baseArchiveName = archiveFileName;
  }
  int fileId = 0;
  while(!gSystem->AccessPathName(fullArchiveName.c_str()))
  {
    streamlog_out(WARNING) << fullArchiveName << " file already exists ..." << std::endl;
    fileId ++;
    std::stringstream ss;
    ss << baseArchiveName << "_" << fileId << ".root";
    fullArchiveName = ss.str();
  }
  m_fileName = fullArchiveName;
  m_openingMode = openingMode;
  m_pArchiveFile = new TFile(m_fileName.c_str(), openingMode.c_str());
  if(NULL == m_pArchiveFile)
    return STATUS_CODE_FAILURE;
  m_isOpened = true;
  m_firstArchive = true;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMArchiver::recursiveFill (DQMDirectory * pDirectory, TDirectory * pROOTDir) [protected]
Fill recursively the TDirectory with the DQMDirectory.
Definition at line 232 of file DQMArchiver.cc.
References dqm4hep::DQMDirectory::getMonitorElementList(), dqm4hep::DQMDirectory::getName(), dqm4hep::DQMDirectory::getSubDirList(), dqm4hep::DQMDirectory::mkdir(), RETURN_RESULT_IF, and writeMonitorElements().
Referenced by archive().
{
  if(NULL == pDirectory || NULL == pROOTDir)
    return STATUS_CODE_INVALID_PTR;
  pROOTDir->cd();
  const std::vector<DQMDirectory*> &subDirList(pDirectory->getSubDirList());
  if(!subDirList.empty())
  {
    for(std::vector<DQMDirectory*>::const_iterator iter = subDirList.begin(), endIter = subDirList.end() ;
        endIter != iter ; ++iter)
    {
      DQMDirectory *pSubDir = *iter;
      TDirectory *pROOTSubDir = pROOTDir->mkdir(pSubDir->getName().c_str());
      if(NULL != pROOTSubDir)
      {
        RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, recursiveFill(pSubDir, pROOTSubDir));
      }
    }
  }
  const std::vector<DQMMonitorElement*> &monitorElementList(pDirectory->getMonitorElementList());
  // write the monitor elements
  if(!monitorElementList.empty())
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, writeMonitorElements(pDirectory, pROOTDir));
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMArchiver::writeMonitorElements (DQMDirectory * pDirectory, TDirectory * pROOTDir) [protected]
Write the monitor elements contained in the DQMDirectory in the TDirectory.
Definition at line 269 of file DQMArchiver.cc.
References dqm4hep::DQMDirectory::getMonitorElementList(), dqm4hep::DQMMonitorElement::getName(), and dqm4hep::DQMMonitorElement::getObject().
Referenced by recursiveFill().
{
  if(NULL == pDirectory || NULL == pROOTDir)
    return STATUS_CODE_INVALID_PTR;
  pROOTDir->cd();
  const DQMMonitorElementList &monitorElementList(pDirectory->getMonitorElementList());
  for(DQMMonitorElementList::const_iterator iter = monitorElementList.begin(), endIter = monitorElementList
      .end() ;
      endIter != iter ; ++iter)
  {
    DQMMonitorElement *pMonitorElement = *iter;
    TObject *pObject = pMonitorElement->getObject();
    pROOTDir->WriteObjectAny(pObject, pObject->IsA(), pMonitorElement->getName().c_str());
  }
  return STATUS_CODE_SUCCESS;
}
Friends And Related Function Documentation
friend class DQMMonitorElementManager [friend]
Definition at line 52 of file DQMArchiver.h.
Member Data Documentation
std::string dqm4hep::DQMArchiver::m_fileName [private]
Definition at line 112 of file DQMArchiver.h.
Referenced by getFileName(), and open().
bool dqm4hep::DQMArchiver::m_firstArchive [private]
Definition at line 115 of file DQMArchiver.h.
Referenced by archive(), close(), and open().
bool dqm4hep::DQMArchiver::m_isOpened [private]
Definition at line 114 of file DQMArchiver.h.
Referenced by close(), isOpened(), open(), and ~DQMArchiver().
std::string dqm4hep::DQMArchiver::m_openingMode [private]
Definition at line 113 of file DQMArchiver.h.
Referenced by close(), getOpeningMode(), and open().
TFile* dqm4hep::DQMArchiver::m_pArchiveFile [private]
Definition at line 117 of file DQMArchiver.h.
Referenced by archive(), close(), and open().
The documentation for this class was generated from the following files:
DQMArchiver.h
DQMArchiver.cc