dqm4hep::DQMEvent Class Reference
DQMEvent class.
#include <DQMEvent.h>
Public Member Functions
virtual ~DQMEvent ()
Destructor.
template<typename T >
T * getEvent () const
Returns the event converted to asked type.
template<typename T >
void setEvent (T *pEvent, bool isOwner=true)
Set the event.
template<typename T >
void clear ()
Clear the event (normally delete the event structure)
bool isOwner () const
Whether the dqm event is the owner of the wrapped event.
Protected Member Functions
DQMEvent ()
Private constructor.
Protected Attributes
bool m_isOwner
Detailed Description
DQMEvent class.
Main interface to a monitored event through the framework. This class is passed to modules in order to monitor its contents. The real data structure can be accessed via the getEvent methods which convert the interface into a DQMEventBase (see below).
To define an event, the user should always inherits the DQMEventBase class in order to have valid operations.
Definition at line 51 of file DQMEvent.h.
Constructor & Destructor Documentation
dqm4hep::DQMEvent::~DQMEvent () [inline], [virtual]
Destructor.
Definition at line 122 of file DQMEvent.h.
{
}
dqm4hep::DQMEvent::DQMEvent () [inline], [protected]
Private constructor.
Definition at line 115 of file DQMEvent.h.
                          :
    m_isOwner(true)
{
}
Member Function Documentation
template<typename T > void dqm4hep::DQMEvent::clear () [inline]
Clear the event (normally delete the event structure)
Definition at line 156 of file DQMEvent.h.
References dqm4hep::DQMEventBase< T >::clear(), and m_isOwner.
{
  if(m_isOwner)
  {
    DQMEventBase<T> *pBaseEvent = dynamic_cast<DQMEventBase<T>*>(this);
    if(NULL == pBaseEvent)
      return;
    pBaseEvent->clear();
  }
}
template<typename T > T * dqm4hep::DQMEvent::getEvent () const [inline]
Returns the event converted to asked type.
Definition at line 129 of file DQMEvent.h.
References dqm4hep::DQMEventBase< T >::getEvent().
Referenced by dqm4hep::DQMLCEventStreamer::serialize().
{
  const DQMEventBase<T> *pBaseEvent = dynamic_cast<const DQMEventBase<T>*>(this);
  if(NULL == pBaseEvent)
    return 0;
  return pBaseEvent->getEvent();
}
bool dqm4hep::DQMEvent::isOwner () const [inline]
Whether the dqm event is the owner of the wrapped event.
Definition at line 171 of file DQMEvent.h.
References m_isOwner.
Referenced by dqm4hep::DQMLCEvent::clear(), and setEvent().
{
  return m_isOwner;
}
template<typename T > void dqm4hep::DQMEvent::setEvent (T * pEvent, bool isOwner = true) [inline]
Set the event.
The dqm event can own the wrapped event is the second arguement is set to true
Definition at line 142 of file DQMEvent.h.
References isOwner(), m_isOwner, and dqm4hep::DQMEventBase< T >::setEvent().
Referenced by dqm4hep::DQMLCEventStreamer::deserialize(), and dqm4hep::DQMLcioReaderListener::processEvent().
{
  DQMEventBase<T> *pBaseEvent = dynamic_cast<DQMEventBase<T>*>(this);
  if(NULL == pBaseEvent)
    return;
  pBaseEvent->setEvent(pEvent);
  m_isOwner = isOwner;
}
Member Data Documentation
bool dqm4hep::DQMEvent::m_isOwner [protected]
Definition at line 85 of file DQMEvent.h.
Referenced by clear(), isOwner(), and setEvent().
The documentation for this class was generated from the following file:
DQMEvent.h