dqm4hep::TiXmlAttributeSet Class Reference
#include <tinyxml.h>
Public Member Functions
TiXmlAttributeSet ()
~TiXmlAttributeSet ()
void Add (TiXmlAttribute *attribute)
void Remove (TiXmlAttribute *attribute)
const TiXmlAttribute * First () const
TiXmlAttribute * First ()
const TiXmlAttribute * Last () const
TiXmlAttribute * Last ()
TiXmlAttribute * Find (const char *_name) const
TiXmlAttribute * FindOrCreate (const char *_name)
TiXmlAttribute * Find (const std::string &_name) const
TiXmlAttribute * FindOrCreate (const std::string &_name)
Private Member Functions
TiXmlAttributeSet (const TiXmlAttributeSet &)
void operator= (const TiXmlAttributeSet &)
Private Attributes
TiXmlAttribute sentinel
Detailed Description
Definition at line 909 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::TiXmlAttributeSet::TiXmlAttributeSet ()
Definition at line 1456 of file tinyxml.cc.
References dqm4hep::TiXmlAttribute::next, dqm4hep::TiXmlAttribute::prev, and sentinel.
{
  sentinel.next = &sentinel;
  sentinel.prev = &sentinel;
}
dqm4hep::TiXmlAttributeSet::~TiXmlAttributeSet ()
Definition at line 1463 of file tinyxml.cc.
References dqm4hep::TiXmlAttribute::next, dqm4hep::TiXmlAttribute::prev, and sentinel.
{
  assert(sentinel.next == &sentinel);
  assert(sentinel.prev == &sentinel);
}
dqm4hep::TiXmlAttributeSet::TiXmlAttributeSet (const TiXmlAttributeSet &) [private]
Member Function Documentation
void dqm4hep::TiXmlAttributeSet::Add (TiXmlAttribute * attribute)
Definition at line 1470 of file tinyxml.cc.
References Find(), dqm4hep::TiXmlAttribute::Name(), dqm4hep::TiXmlAttribute::next, dqm4hep::TiXmlAttribute::prev, sentinel, and TIXML_STRING.
Referenced by FindOrCreate(), and dqm4hep::TiXmlElement::Parse().
{
    #ifdef TIXML_USE_STL
  assert(!Find(TIXML_STRING(addMe->Name()))); // Shouldn't be multiply adding to the set.
  #else
  assert(!Find(addMe->Name())); // Shouldn't be multiply adding to the set.
  #endif
  addMe->next = &sentinel;
  addMe->prev = sentinel.prev;
  sentinel.prev->next = addMe;
  sentinel.prev = addMe;
}
TiXmlAttribute * dqm4hep::TiXmlAttributeSet::Find (const char * _name) const
Definition at line 1528 of file tinyxml.cc.
References dqm4hep::TiXmlAttribute::next, and sentinel.
Referenced by Add(), dqm4hep::TiXmlElement::Attribute(), FindOrCreate(), dqm4hep::TiXmlElement::Parse(), dqm4hep::TiXmlElement::QueryDoubleAttribute(), dqm4hep::TiXmlElement::QueryIntAttribute(), dqm4hep::TiXmlElement::QueryValueAttribute(), and dqm4hep::TiXmlElement::RemoveAttribute().
{
  for(TiXmlAttribute* node = sentinel.next; node != &sentinel; node = node->
      next)
  {
    if (strcmp(node->name.c_str(), name) == 0)
      return node;
  }
  return 0;
}
TiXmlAttribute* dqm4hep::TiXmlAttributeSet::Find (const std::string & _name) const
TiXmlAttribute * dqm4hep::TiXmlAttributeSet::FindOrCreate (const char * _name)
Definition at line 1539 of file tinyxml.cc.
References Add(), Find(), and dqm4hep::TiXmlAttribute::SetName().
Referenced by dqm4hep::TiXmlElement::SetAttribute(), and dqm4hep::TiXmlElement::SetDoubleAttribute().
{
  TiXmlAttribute* attrib = Find(_name);
  if (!attrib) {
    attrib = new TiXmlAttribute();
    Add(attrib);
    attrib->SetName(_name);
  }
  return attrib;
}
TiXmlAttribute* dqm4hep::TiXmlAttributeSet::FindOrCreate (const std::string & _name)
const TiXmlAttribute* dqm4hep::TiXmlAttributeSet::First () const [inline]
Definition at line 918 of file tinyxml.h.
References dqm4hep::TiXmlAttribute::next, and sentinel.
Referenced by dqm4hep::TiXmlElement::Accept(), dqm4hep::TiXmlElement::ClearThis(), dqm4hep::TiXmlElement::CopyTo(), dqm4hep::TiXmlElement::FirstAttribute(), and dqm4hep::TiXmlElement::Print().
{ return (sentinel.next == &sentinel) ? 0 : sentinel.next; }
TiXmlAttribute* dqm4hep::TiXmlAttributeSet::First () [inline]
Definition at line 919 of file tinyxml.h.
References dqm4hep::TiXmlAttribute::next, and sentinel.
{ return (sentinel.next == &sentinel) ? 0 : sentinel.next; }
const TiXmlAttribute* dqm4hep::TiXmlAttributeSet::Last () const [inline]
Definition at line 920 of file tinyxml.h.
References dqm4hep::TiXmlAttribute::prev, and sentinel.
Referenced by dqm4hep::TiXmlElement::LastAttribute().
{ return (sentinel.prev == &sentinel) ? 0 : sentinel.prev; }
TiXmlAttribute* dqm4hep::TiXmlAttributeSet::Last () [inline]
Definition at line 921 of file tinyxml.h.
References dqm4hep::TiXmlAttribute::prev, and sentinel.
{ return (sentinel.prev == &sentinel) ? 0 : sentinel.prev; }
void dqm4hep::TiXmlAttributeSet::operator= (const TiXmlAttributeSet &) [private]
void dqm4hep::TiXmlAttributeSet::Remove (TiXmlAttribute * attribute)
Definition at line 1485 of file tinyxml.cc.
References dqm4hep::TiXmlAttribute::next, dqm4hep::TiXmlAttribute::prev, and sentinel.
Referenced by dqm4hep::TiXmlElement::ClearThis(), and dqm4hep::TiXmlElement::RemoveAttribute().
{
  TiXmlAttribute* node;
  for(node = sentinel.next; node != &sentinel; node = node->next)
  {
    if (node == removeMe)
    {
      node->prev->next = node->next;
      node->next->prev = node->prev;
      node->next = 0;
      node->prev = 0;
      return;
    }
  }
  assert(0); // we tried to remove a non-linked attribute.
}
Member Data Documentation
TiXmlAttribute dqm4hep::TiXmlAttributeSet::sentinel [private]
Definition at line 938 of file tinyxml.h.
Referenced by Add(), Find(), First(), Last(), Remove(), TiXmlAttributeSet(), and ~TiXmlAttributeSet().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc