dqm4hep::DQMDBInterface Class Reference
DQMDBInterface class.
#include <DQMDBInterface.h>
Public Member Functions
DQMDBInterface ()
Constructor.
DQMDBInterface (const std::string &host, const std::string &user, const std::string &password, const std::string &database)
Constructor.
virtual ~DQMDBInterface ()
Destructor.
StatusCode connect ()
Connect to the mysql server.
StatusCode disconnect ()
Disconnect from the database.
StatusCode connect (const std::string &host, const std::string &user, const std::string &password, const std::string &database)
Connect to the database.
StatusCode set (const std::string &host, const std::string &user, const std::string &password, const std::string &database)
Set host, user, password and database.
const std::string & getHost () const
Get the host.
const std::string & getUser () const
Get the user name.
const std::string & getPassword () const
Get the password.
const std::string & getDataBase () const
Get the data base name.
StatusCode queryRaw (const std::string &query, void *&pResult)
Send query to database The result is not converted.
template<typename T >
StatusCode query (const std::string &query, T &result)
Send query to database.
template<typename T >
StatusCode queryVector (const std::string &query, std::vector< T > &result)
Send query to database.
StatusCode execute (const std::string &query)
Execute the query (no result expected)
bool isConnected ()
Whether a connection is being handled.
StatusCode queryConfigFileContent (const std::string &configFileName, std::string &fileContents)
Query a config file content stored in the DQM4HEP data base (table CONFIG_FILES)
StatusCode queryConfigFileDescription (const std::string &configFileName, std::string &fileDescription)
Query a config file description.
StatusCode insertConfigFile (const std::string &localFileName, const std::string &fileNameEntry, const std::string &fileDescription=``, bool forceReplace=false)
Insert a new new config file entry in the database.
Private Attributes
MYSQL * m_pMySQL
std::string m_host
std::string m_user
std::string m_password
std::string m_database
bool m_isConnected
Detailed Description
DQMDBInterface class.
Definition at line 43 of file DQMDBInterface.h.
Constructor & Destructor Documentation
dqm4hep::DQMDBInterface::DQMDBInterface ()
Constructor.
Definition at line 36 of file DQMDBInterface.cc.
                               :
    m_pMySQL(NULL),
    m_isConnected(false)
{
}
dqm4hep::DQMDBInterface::DQMDBInterface (const std::string & host, const std::string & user, const std::string & password, const std::string & database)
Constructor.
Connect to data base
Definition at line 45 of file DQMDBInterface.cc.
References connect(), and set().
                                                                                                           
                            :
    m_pMySQL(NULL),
    m_isConnected(false)
{
  this->set(host, user, password, database);
  this->connect();
}
dqm4hep::DQMDBInterface::~DQMDBInterface () [virtual]
Destructor.
Definition at line 55 of file DQMDBInterface.cc.
References disconnect(), and isConnected().
{
  if(this->isConnected())
    this->disconnect();
}
Member Function Documentation
StatusCode dqm4hep::DQMDBInterface::connect ()
Connect to the mysql server.
Definition at line 63 of file DQMDBInterface.cc.
References dqm4hep::ERROR, execute(), dqm4hep::StatusCodeException::getStatusCode(), isConnected(), m_database, m_host, m_isConnected, m_password, m_pMySQL, m_user, query(), and THROW_RESULT_IF.
Referenced by connect(), dqm4hep::DQMDBFileHandler::download(), and DQMDBInterface().
{
  if(this->isConnected())
    return STATUS_CODE_ALREADY_INITIALIZED;
  try
  {
    // create mysql instance
    m_pMySQL = mysql_init(NULL);
    if(!m_pMySQL)
    {
      streamlog_out(ERROR) << "Couldn't create mysql instance : " << mysql_error(
      m_pMySQL) << std::endl;
      throw StatusCodeException(STATUS_CODE_FAILURE);
    }
    // create connection to database
    if(NULL == mysql_real_connect(m_pMySQL, m_host.c_str(), m_user.c_str(),
      m_password.c_str(),
                             NULL, 0, NULL, 0))
    {
      streamlog_out(ERROR) << "Couldn't initialize mysql connection : " << mysql_error(
      m_pMySQL) << std::endl;
      throw StatusCodeException(STATUS_CODE_FAILURE);
    }
    m_isConnected = true;
    // select data base
    std::stringstream query;
    query << "USE " << m_database << " ;";
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(query.str()));
  }
  catch(const StatusCodeException &exception)
  {
    if(m_pMySQL)
      mysql_close(m_pMySQL);
    m_isConnected = false;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDBInterface::connect (const std::string & host, const std::string & user, const std::string & password, const std::string & database)
Connect to the database.
Not possible if a connection is being handled. Use disconnect() first and then connect()
Definition at line 125 of file DQMDBInterface.cc.
References connect(), RETURN_RESULT_IF, and set().
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->set(host, user, password, database));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->connect());
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDBInterface::disconnect ()
Disconnect from the database.
Definition at line 110 of file DQMDBInterface.cc.
References isConnected(), m_isConnected, and m_pMySQL.
Referenced by dqm4hep::DQMDBFileHandler::download(), and ~DQMDBInterface().
{
  if(this->isConnected())
    return STATUS_CODE_UNCHANGED;
  if(m_pMySQL)
    mysql_close(m_pMySQL);
  m_isConnected = false;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDBInterface::execute (const std::string & query)
Execute the query (no result expected)
Definition at line 213 of file DQMDBInterface.cc.
References dqm4hep::ERROR, isConnected(), and m_pMySQL.
Referenced by connect(), insertConfigFile(), queryConfigFileContent(), and queryConfigFileDescription().
{
  if(!this->isConnected())
    return STATUS_CODE_NOT_INITIALIZED;
  if(mysql_query(m_pMySQL, query.c_str()))
  {
    streamlog_out(ERROR) << "MySQL query failed : " << mysql_error(m_pMySQL) << std::endl;
    return STATUS_CODE_FAILURE;
  }
  return STATUS_CODE_SUCCESS;
}
const std::string & dqm4hep::DQMDBInterface::getDataBase () const
Get the data base name.
Definition at line 171 of file DQMDBInterface.cc.
References m_database.
{
  return m_database;
}
const std::string & dqm4hep::DQMDBInterface::getHost () const
Get the host.
Definition at line 150 of file DQMDBInterface.cc.
References m_host.
{
  return m_host;
}
const std::string & dqm4hep::DQMDBInterface::getPassword () const
Get the password.
Definition at line 164 of file DQMDBInterface.cc.
References m_password.
{
  return m_password;
}
const std::string & dqm4hep::DQMDBInterface::getUser () const
Get the user name.
Definition at line 157 of file DQMDBInterface.cc.
References m_user.
{
  return m_user;
}
StatusCode dqm4hep::DQMDBInterface::insertConfigFile (const std::string & localFileName, const std::string & fileNameEntry, const std::string & fileDescription = ``, bool forceReplace = false)
Insert a new new config file entry in the database.
Definition at line 312 of file DQMDBInterface.cc.
References dqm4hep::ERROR, execute(), isConnected(), m_database, query(), and RETURN_RESULT_IF.
{
  if(localFileName.empty() || fileNameEntry.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  if(!this->isConnected())
    return STATUS_CODE_NOT_INITIALIZED;
  std::ifstream ifile;
  ifile.open(localFileName.c_str(), std::ios::in);
  if(!ifile.is_open())
  {
    streamlog_out(ERROR) << "Couln't open file '" << localFileName << "' !" << std::endl;
    return STATUS_CODE_FAILURE;
  }
  std::string fileContents;
  while(!ifile.eof())
  {
    std::string str;
    getline(ifile, str);
    fileContents += str + "\n";
  }
  if(fileContents.empty())
    return STATUS_CODE_FAILURE;
  std::string queryUse = "USE " + m_database + " ;";
  // construct the mysql query
  std::stringstream query;
  if(forceReplace)
    query << "REPLACE ";
  else
    query << "INSERT ";
  query << "INTO CONFIG_FILES VALUES "
      << "('" << fileNameEntry << "' ,"
      << "'" << fileDescription << "' ,"
      << "'" << fileContents << "') ;";
  // select DQM4HEP database
  if(m_database != "DQM4HEP")
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute("USE DQM4HEP ;"));
  StatusCode statusCode = this->execute(query.str());
  if(STATUS_CODE_SUCCESS != statusCode)
  {
    // select again the current database
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
    return statusCode;
  }
  // select again the current database
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
  return STATUS_CODE_SUCCESS;
}
bool dqm4hep::DQMDBInterface::isConnected ()
Whether a connection is being handled.
Definition at line 229 of file DQMDBInterface.cc.
References m_isConnected.
Referenced by connect(), disconnect(), dqm4hep::DQMDBFileHandler::download(), execute(), insertConfigFile(), query(), queryConfigFileContent(), queryConfigFileDescription(), queryRaw(), queryVector(), set(), and ~DQMDBInterface().
{
  return m_isConnected;
}
template<typename T > StatusCode dqm4hep::DQMDBInterface::query (const std::string & query, T & result) [inline]
Send query to database.
The result is streamed in type T using DQM4HEP::stringToType()
Definition at line 154 of file DQMDBInterface.h.
References dqm4hep::ERROR, isConnected(), m_pMySQL, and dqm4hep::DQM4HEP::stringToType().
Referenced by connect(), insertConfigFile(), queryConfigFileContent(), and queryConfigFileDescription().
{
  if(!this->isConnected())
    return STATUS_CODE_NOT_INITIALIZED;
  if(mysql_query(m_pMySQL, query.c_str()))
  {
    streamlog_out(ERROR) << "MySQL query failed : " << mysql_error(m_pMySQL) << std::endl;
    return STATUS_CODE_FAILURE;
  }
  MYSQL_RES *pMySQLResult = mysql_store_result(m_pMySQL);
  if(!pMySQLResult)
  {
    streamlog_out(ERROR) << "MySQL store result failed : " << mysql_error(
      m_pMySQL) << std::endl;
    return STATUS_CODE_FAILURE;
  }
  MYSQL_ROW row = mysql_fetch_row(pMySQLResult);
  std::cout << "DQMDBInterface::query : MySQL row[0] = " << row[0] << std::endl;
  if(!DQM4HEP::stringToType(row[0], result))
  {
    mysql_free_result(pMySQLResult);
    return STATUS_CODE_FAILURE;
  }
  std::cout << "DQMDBInterface::query : MySQL result = " << result << std::endl;
  mysql_free_result(pMySQLResult);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDBInterface::queryConfigFileContent (const std::string & configFileName, std::string & fileContents)
Query a config file content stored in the DQM4HEP data base (table CONFIG_FILES)
Definition at line 236 of file DQMDBInterface.cc.
References execute(), isConnected(), m_database, query(), queryRaw(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMDBFileHandler::download().
{
  if(configFileName.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  if(!this->isConnected())
    return STATUS_CODE_NOT_INITIALIZED;
  // select DQM4HEP database
  if(m_database != "DQM4HEP")
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute("USE DQM4HEP ;"));
  std::string queryUse = "USE " + m_database + " ;";
  std::stringstream query;
  query << "SELECT CONTENTS FROM CONFIG_FILES WHERE FILE_NAME=\"" << configFileName << "\" ;";
  void *pFileContent = NULL;
  StatusCode statusCode = this->queryRaw(query.str(), pFileContent);
  if(statusCode != STATUS_CODE_SUCCESS)
  {
    // select again the current database
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
    return statusCode;
  }
  fileContents = (char *) pFileContent;
  // select again the current database
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDBInterface::queryConfigFileDescription (const std::string & configFileName, std::string & fileDescription)
Query a config file description.
Definition at line 274 of file DQMDBInterface.cc.
References execute(), isConnected(), m_database, query(), queryRaw(), and RETURN_RESULT_IF.
{
  if(configFileName.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  if(!this->isConnected())
    return STATUS_CODE_NOT_INITIALIZED;
  // select DQM4HEP database
  if(m_database != "DQM4HEP")
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute("USE DQM4HEP ;"));
  std::string queryUse = "USE " + m_database + " ;";
  std::stringstream query;
  query << "SELECT DESCRIPTION FROM CONFIG_FILES WHERE FILE_NAME=\"" << configFileName << "\" ;";
  void *pFileDescription = NULL;
  StatusCode statusCode = this->queryRaw(query.str(), pFileDescription);
  if(statusCode != STATUS_CODE_SUCCESS)
  {
    // select again the current database
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
    return statusCode;
  }
  fileDescription = (char *) pFileDescription;
  // select again the current database
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDBInterface::queryRaw (const std::string & query, void *& pResult)
Send query to database The result is not converted.
Definition at line 178 of file DQMDBInterface.cc.
References dqm4hep::ERROR, isConnected(), and m_pMySQL.
Referenced by queryConfigFileContent(), and queryConfigFileDescription().
{
  pResult = NULL;
  if(!this->isConnected())
    return STATUS_CODE_NOT_INITIALIZED;
  if(mysql_query(m_pMySQL, query.c_str()))
  {
    streamlog_out(ERROR) << "MySQL query failed : " << mysql_error(m_pMySQL) << std::endl;
    return STATUS_CODE_FAILURE;
  }
  MYSQL_RES *pMySQLResult = mysql_store_result(m_pMySQL);
  if(!pMySQLResult)
  {
    streamlog_out(ERROR) << "MySQL store result failed : " << mysql_error(
      m_pMySQL) << std::endl;
    return STATUS_CODE_FAILURE;
  }
  MYSQL_ROW row = mysql_fetch_row(pMySQLResult);
  pResult = (void *) row[0];
  mysql_free_result(pMySQLResult);
  if(NULL == pResult)
    return STATUS_CODE_FAILURE;
  return STATUS_CODE_SUCCESS;
}
template<typename T > StatusCode dqm4hep::DQMDBInterface::queryVector (const std::string & query, std::vector< T > & result) [inline]
Send query to database.
The result is streamed in a vector. Each value of the vector is streamed using DQM4HEP::stringToType()
Definition at line 193 of file DQMDBInterface.h.
References dqm4hep::ERROR, isConnected(), m_pMySQL, and dqm4hep::DQM4HEP::stringToType().
{
  if(!this->isConnected())
    return STATUS_CODE_NOT_INITIALIZED;
  if(mysql_query(m_pMySQL, query.c_str()))
  {
    streamlog_out(ERROR) << "MySQL query failed : " << mysql_error(m_pMySQL) << std::endl;
    return STATUS_CODE_FAILURE;
  }
  MYSQL_RES *pMySQLResult = mysql_store_result(m_pMySQL);
  if(!pMySQLResult)
  {
    streamlog_out(ERROR) << "MySQL store result failed : " << mysql_error(
      m_pMySQL) << std::endl;
    return STATUS_CODE_FAILURE;
  }
  MYSQL_ROW row;
  while((row = mysql_fetch_row(pMySQLResult)))
  {
    T value = T();
    if(!DQM4HEP::stringToType(row[0], value))
      continue;
    result.push_back(value);
  }
  mysql_free_result(pMySQLResult);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDBInterface::set (const std::string & host, const std::string & user, const std::string & password, const std::string & database)
Set host, user, password and database.
Not possible if a connection is being handled. Use disconnect() first and then connect()
Definition at line 135 of file DQMDBInterface.cc.
References isConnected(), m_database, m_host, m_password, and m_user.
Referenced by connect(), and DQMDBInterface().
{
  if(this->isConnected())
    return STATUS_CODE_NOT_ALLOWED;
  m_host = host;
  m_user = user;
  m_password = password;
  m_database = database;
  return STATUS_CODE_SUCCESS;
}
Member Data Documentation
std::string dqm4hep::DQMDBInterface::m_database [private]
Definition at line 145 of file DQMDBInterface.h.
Referenced by connect(), getDataBase(), insertConfigFile(), queryConfigFileContent(), queryConfigFileDescription(), and set().
std::string dqm4hep::DQMDBInterface::m_host [private]
Definition at line 142 of file DQMDBInterface.h.
Referenced by connect(), getHost(), and set().
bool dqm4hep::DQMDBInterface::m_isConnected [private]
Definition at line 147 of file DQMDBInterface.h.
Referenced by connect(), disconnect(), and isConnected().
std::string dqm4hep::DQMDBInterface::m_password [private]
Definition at line 144 of file DQMDBInterface.h.
Referenced by connect(), getPassword(), and set().
MYSQL* dqm4hep::DQMDBInterface::m_pMySQL [private]
Definition at line 140 of file DQMDBInterface.h.
Referenced by connect(), disconnect(), execute(), query(), queryRaw(), and queryVector().
std::string dqm4hep::DQMDBInterface::m_user [private]
Definition at line 143 of file DQMDBInterface.h.
Referenced by connect(), getUser(), and set().
The documentation for this class was generated from the following files:
DQMDBInterface.h
DQMDBInterface.cc