dqm4hep::DQMMonitorElementCollectorInfoRpc Class Reference
#include <DQMMonitorElementCollector.h>
Public Member Functions
DQMMonitorElementCollectorInfoRpc (char *rpcName, DQMMonitorElementCollector *pCollector)
void rpcHandler ()
Private Attributes
DQMMonitorElementCollector * m_pCollector
DQMDataStream m_dataStream
Detailed Description
Definition at line 203 of file DQMMonitorElementCollector.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElementCollectorInfoRpc::DQMMonitorElementCollectorInfoRpc (char * rpcName, DQMMonitorElementCollector * pCollector)
Definition at line 1344 of file DQMMonitorElementCollector.cc.
                                                                                                           
                     :
    DimRpc(rpcName, "C", "C"),
    m_pCollector(pCollector),
    m_dataStream(128*1024)
{
  /* nop */
}
Member Function Documentation
void dqm4hep::DQMMonitorElementCollectorInfoRpc::rpcHandler ()
Definition at line 1354 of file DQMMonitorElementCollector.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), m_dataStream, dqm4hep::DQMCollectorInfo::m_hostName, dqm4hep::DQMCollectorInfo::m_machine, dqm4hep::DQMCollectorInfo::m_moduleListName, dqm4hep::DQMMonitorElementCollector::m_moduleMeInfoMap, dqm4hep::DQMCollectorInfo::m_nodeName, m_pCollector, dqm4hep::DQMCollectorInfo::m_release, dqm4hep::DQMCollectorInfo::m_systemName, dqm4hep::DQMCollectorInfo::m_version, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMCollectorInfo::serialize(), and THROW_RESULT_IF.
{
  try
  {
    DQMCollectorInfo collectorInfo;
    // uname
    struct utsname unameStruct;
    uname(&unameStruct);
    collectorInfo.m_systemName = unameStruct.sysname;
    collectorInfo.m_nodeName = unameStruct.nodename;
    collectorInfo.m_release = unameStruct.release;
    collectorInfo.m_version = unameStruct.version;
    collectorInfo.m_machine = unameStruct.machine;
    // hostname
    char host[256];
    gethostname(host, 256);
    collectorInfo.m_hostName = host;
    // module name list
    for(DQMMonitorElementCollector::ModuleMeInfoMap::iterator iter =
      m_pCollector->m_moduleMeInfoMap.begin(),
        endIter = m_pCollector->m_moduleMeInfoMap.end() ; endIter != iter ; ++iter)
      collectorInfo.m_moduleListName.push_back(iter->first);
    // serialize the packet
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, collectorInfo.serialize(&
      m_dataStream));
    // get the buffer
    dqm_char *pBuffer = m_dataStream.getBuffer();
    dqm_uint bufferSize = m_dataStream.getBufferSize();
    // and set it as data to send back
    setData((void*) pBuffer, bufferSize);
  }
  catch(StatusCodeException &exception)
  {
  }
  catch(...)
  {
  }
}
Member Data Documentation
DQMDataStream dqm4hep::DQMMonitorElementCollectorInfoRpc::m_dataStream [private]
Definition at line 211 of file DQMMonitorElementCollector.h.
Referenced by rpcHandler().
DQMMonitorElementCollector* dqm4hep::DQMMonitorElementCollectorInfoRpc::m_pCollector [private]
Definition at line 210 of file DQMMonitorElementCollector.h.
Referenced by rpcHandler().
The documentation for this class was generated from the following files:
DQMMonitorElementCollector.h
DQMMonitorElementCollector.cc