dqm4hep::DQMLCFloatVecStreamer Class Reference
DQMLCFloatVecStreamer class.
#include <DQMLCEventStreamer.h>
Public Member Functions
StatusCode serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize a LCFloatVec.
StatusCode deserialize (EVENT::LCObject *&pLCObject, DQMDataStream *const pDataStream)
Deserialize a LCFloatVec.
Detailed Description
DQMLCFloatVecStreamer class.
Definition at line 243 of file DQMLCEventStreamer.h.
Member Function Documentation
StatusCode dqm4hep::DQMLCFloatVecStreamer::deserialize (EVENT::LCObject *& pLCObject, DQMDataStream *const pDataStream)
Deserialize a LCFloatVec.
The object is allocated in this function
Definition at line 1223 of file DQMLCEventStreamer.cc.
References dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMDataStream::read(), and THROW_RESULT_IF.
{
  pLCObject = 0;
  EVENT::LCFloatVec *pFloatVec = new EVENT::LCFloatVec();
  try
  {
    dqm_uint nVals = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nVals));
    for(dqm_uint i=0 ; i<nVals ; i++)
    {
      dqm_float value = 0;
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(value));
      pFloatVec->push_back(value);
    }
  }
  catch(StatusCodeException &exception)
  {
    delete pFloatVec;
    pFloatVec = 0;
    pLCObject = 0;
    return exception.getStatusCode();
  }
  pLCObject = pFloatVec;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMLCFloatVecStreamer::serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize a LCFloatVec.
Definition at line 1202 of file DQMLCEventStreamer.cc.
References RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
{
  const EVENT::LCFloatVec *const pFloatVec = dynamic_cast<const EVENT::LCFloatVec *const>(pLCObject);
  if(NULL == pFloatVec)
    return STATUS_CODE_INVALID_PARAMETER;
  dqm_uint nVals = pFloatVec->size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nVals));
  for(dqm_uint i=0 ; i<nVals ; i++)
  {
    dqm_float value = pFloatVec->at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(value));
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMLCEventStreamer.h
DQMLCEventStreamer.cc