dqm4hep::TiXmlAttribute Class Reference
An attribute is a name-value pair.
#include <tinyxml.h>
Public Member Functions
TiXmlAttribute ()
Construct an empty attribute.
TiXmlAttribute (const std::string &_name, const std::string &_value)
std::string constructor.
TiXmlAttribute (const char *_name, const char *_value)
Construct an attribute with a name and value.
const char * Name () const
Return the name of this attribute.
const char * Value () const
Return the value of this attribute.
const std::string & ValueStr () const
Return the value of this attribute.
int IntValue () const
Return the value of this attribute, converted to an integer.
double DoubleValue () const
Return the value of this attribute, converted to a double.
const TIXML_STRING & NameTStr () const
int QueryIntValue (int *_value) const
QueryIntValue examines the value string.
int QueryDoubleValue (double *_value) const
QueryDoubleValue examines the value string. See QueryIntValue().
void SetName (const char *_name)
Set the name of this attribute.
void SetValue (const char *_value)
Set the value.
void SetIntValue (int _value)
Set the value from an integer.
void SetDoubleValue (double _value)
Set the value from a double.
void SetName (const std::string &_name)
STL std::string form.
void SetValue (const std::string &_value)
STL std::string form.
const TiXmlAttribute * Next () const
Get the next sibling attribute in the DOM. Returns null at end.
TiXmlAttribute * Next ()
const TiXmlAttribute * Previous () const
Get the previous sibling attribute in the DOM. Returns null at beginning.
TiXmlAttribute * Previous ()
bool operator== (const TiXmlAttribute &rhs) const
bool operator< (const TiXmlAttribute &rhs) const
bool operator> (const TiXmlAttribute &rhs) const
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual void Print (FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
void Print (FILE *cfile, int depth, TIXML_STRING *str) const
void SetDocument (TiXmlDocument *doc)
Private Member Functions
TiXmlAttribute (const TiXmlAttribute &)
void operator= (const TiXmlAttribute &base)
Private Attributes
TiXmlDocument * document
TIXML_STRING name
TIXML_STRING value
TiXmlAttribute * prev
TiXmlAttribute * next
Friends
class TiXmlAttributeSet
Additional Inherited Members
Detailed Description
An attribute is a name-value pair.
Elements have an arbitrary number of attributes, each with a unique name.
Note
The attributes are not TiXmlNodes, since they are not part of the tinyXML document object model. There are other suggested ways to look at this problem.
Definition at line 785 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::TiXmlAttribute::TiXmlAttribute () [inline]
Construct an empty attribute.
Definition at line 791 of file tinyxml.h.
References document, next, and prev.
                   : TiXmlBase()
  {
    document = 0;
    prev = next = 0;
  }
dqm4hep::TiXmlAttribute::TiXmlAttribute (const std::string & _name, const std::string & _value) [inline]
std::string constructor.
Definition at line 799 of file tinyxml.h.
  {
    name = _name;
    value = _value;
    document = 0;
    prev = next = 0;
  }
dqm4hep::TiXmlAttribute::TiXmlAttribute (const char * _name, const char * _value) [inline]
Construct an attribute with a name and value.
Definition at line 809 of file tinyxml.h.
References document, name, next, prev, and value.
  {
    name = _name;
    value = _value;
    document = 0;
    prev = next = 0;
  }
dqm4hep::TiXmlAttribute::TiXmlAttribute (const TiXmlAttribute &) [private]
Member Function Documentation
double dqm4hep::TiXmlAttribute::DoubleValue () const
Return the value of this attribute, converted to a double.
Definition at line 1235 of file tinyxml.cc.
References value.
{
  return atof (value.c_str ());
}
int dqm4hep::TiXmlAttribute::IntValue () const
Return the value of this attribute, converted to an integer.
Definition at line 1230 of file tinyxml.cc.
References value.
{
  return atoi (value.c_str ());
}
const char* dqm4hep::TiXmlAttribute::Name () const [inline]
Return the name of this attribute.
Definition at line 817 of file tinyxml.h.
References name.
Referenced by dqm4hep::TiXmlAttributeSet::Add(), dqm4hep::TiXmlElement::CopyTo(), and dqm4hep::TiXmlElement::Parse().
const TIXML_STRING& dqm4hep::TiXmlAttribute::NameTStr () const [inline]
Definition at line 826 of file tinyxml.h.
References name.
Referenced by dqm4hep::TiXmlElement::Parse().
{ return name; }
const TiXmlAttribute * dqm4hep::TiXmlAttribute::Next () const
Get the next sibling attribute in the DOM. Returns null at end.
Definition at line 1128 of file tinyxml.cc.
References name, next, and value.
Referenced by dqm4hep::TiXmlElement::CopyTo(), dqm4hep::TiXmlElement::Print(), and dqm4hep::TiXmlPrinter::VisitEnter().
{
  // We are using knowledge of the sentinel. The sentinel
  // have a value or name.
  if (next->value.empty() && next->name.empty())
    return 0;
  return next;
}
TiXmlAttribute* dqm4hep::TiXmlAttribute::Next () [inline]
Definition at line 856 of file tinyxml.h.
                         {
    return const_cast< TiXmlAttribute* >((const_cast< const TiXmlAttribute* >(this))->Next());
  }
bool dqm4hep::TiXmlAttribute::operator< (const TiXmlAttribute & rhs) const [inline]
Definition at line 867 of file tinyxml.h.
References name.
{ return name < rhs.name; }
void dqm4hep::TiXmlAttribute::operator= (const TiXmlAttribute & base) [private]
bool dqm4hep::TiXmlAttribute::operator== (const TiXmlAttribute & rhs) const [inline]
Definition at line 866 of file tinyxml.h.
References name.
{ return rhs.name == name; }
bool dqm4hep::TiXmlAttribute::operator> (const TiXmlAttribute & rhs) const [inline]
Definition at line 868 of file tinyxml.h.
References name.
{ return name > rhs.name; }
const char * dqm4hep::TiXmlAttribute::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) [virtual]
Implements dqm4hep::TiXmlBase .
Definition at line 1393 of file tinyxmlparser.cc.
References dqm4hep::TiXmlParsingData::Cursor(), dqm4hep::TiXmlBase::IsWhiteSpace(), dqm4hep::TiXmlBase::location, name, dqm4hep::TiXmlBase::ReadName(), dqm4hep::TiXmlBase::ReadText(), dqm4hep::TiXmlDocument::SetError(), dqm4hep::TiXmlBase::SkipWhiteSpace(), dqm4hep::TiXmlParsingData::Stamp(), dqm4hep::TiXmlBase::TIXML_ERROR_READING_ATTRIBUTES, and value.
Referenced by dqm4hep::TiXmlElement::Parse(), and dqm4hep::TiXmlDeclaration::Parse().
{
  p = SkipWhiteSpace(p, encoding);
  if (!p || !*p) return 0;
  if (data)
  {
    data->Stamp(p, encoding);
    location = data->Cursor();
  }
  // Read the name, the '=' and the value.
  const char* pErr = p;
  p = ReadName(p, &name, encoding);
  if (!p || !*p)
  {
    if (document) document->SetError(TIXML_ERROR_READING_ATTRIBUTES, pErr, data, encoding);
    return 0;
  }
  p = SkipWhiteSpace(p, encoding);
  if (!p || !*p || *p != '=')
  {
    if (document) document->SetError(TIXML_ERROR_READING_ATTRIBUTES, p, data, encoding);
    return 0;
  }
  ++p; // skip '='
  p = SkipWhiteSpace(p, encoding);
  if (!p || !*p)
  {
    if (document) document->SetError(TIXML_ERROR_READING_ATTRIBUTES, p, data, encoding);
    return 0;
  }
  
  const char* end;
  const char SINGLE_QUOTE = '\'';
  const char DOUBLE_QUOTE = '\"';
  if (*p == SINGLE_QUOTE)
  {
    ++p;
    end = "\'"; // single quote in string
    p = ReadText(p, &value, false, end, false, encoding);
  }
  else if (*p == DOUBLE_QUOTE)
  {
    ++p;
    end = "\""; // double quote in string
    p = ReadText(p, &value, false, end, false, encoding);
  }
  else
  {
    // All attribute values should be in single or double quotes.
    // But this is such a common error that the parser will try
    // its best, even without them.
    value = "";
    while (p && *p // existence
        && !IsWhiteSpace(*p) // whitespace
        && *p != '/' && *p != '>') // tag end
    {
      if (*p == SINGLE_QUOTE || *p == DOUBLE_QUOTE) {
        // [ 1451649 ] Attribute values with trailing quotes not handled correctly
        // We did not have an opening quote but seem to have a
        // closing one. Give up and throw an error.
        if (document) document->SetError(TIXML_ERROR_READING_ATTRIBUTES, p, data, encoding);
        return 0;
      }
      value += *p;
      ++p;
    }
  }
  return p;
}
const TiXmlAttribute * dqm4hep::TiXmlAttribute::Previous () const
Get the previous sibling attribute in the DOM. Returns null at beginning.
Definition at line 1148 of file tinyxml.cc.
References name, prev, and value.
{
  // We are using knowledge of the sentinel. The sentinel
  // have a value or name.
  if (prev->value.empty() && prev->name.empty())
    return 0;
  return prev;
}
TiXmlAttribute* dqm4hep::TiXmlAttribute::Previous () [inline]
Definition at line 862 of file tinyxml.h.
                             {
    return const_cast< TiXmlAttribute* >((const_cast< const TiXmlAttribute* >(this))->Previous());
  }
virtual void dqm4hep::TiXmlAttribute::Print (FILE * cfile, int depth) const [inline], [virtual]
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements dqm4hep::TiXmlBase .
Definition at line 876 of file tinyxml.h.
                                                     {
    Print(cfile, depth, 0);
  }
void dqm4hep::TiXmlAttribute::Print (FILE * cfile, int depth, TIXML_STRING * str) const
Definition at line 1168 of file tinyxml.cc.
References dqm4hep::TiXmlBase::EncodeString(), TIXML_STRING, and value.
{
  TIXML_STRING n, v;
  EncodeString(name, &n);
  EncodeString(value, &v);
  if (value.find ('\"') == TIXML_STRING::npos) {
    if (cfile) {
    fprintf (cfile, "%s=\"%s\"", n.c_str(), v.c_str());
    }
    if (str) {
      (*str) += n; (*str) += "=\""; (*str) += v; (*str) += "\"";
    }
  }
  else {
    if (cfile) {
    fprintf (cfile, "%s='%s'", n.c_str(), v.c_str());
    }
    if (str) {
      (*str) += n; (*str) += "='"; (*str) += v; (*str) += "'";
    }
  }
}
int dqm4hep::TiXmlAttribute::QueryDoubleValue (double * _value) const
QueryDoubleValue examines the value string. See QueryIntValue().
Definition at line 1201 of file tinyxml.cc.
References TIXML_SSCANF, dqm4hep::TIXML_SUCCESS, dqm4hep::TIXML_WRONG_TYPE, and value.
Referenced by dqm4hep::TiXmlElement::Attribute(), and dqm4hep::TiXmlElement::QueryDoubleAttribute().
{
  if (TIXML_SSCANF(value.c_str(), "%lf", dval) == 1)
    return TIXML_SUCCESS;
  return TIXML_WRONG_TYPE;
}
int dqm4hep::TiXmlAttribute::QueryIntValue (int * _value) const
QueryIntValue examines the value string.
It is an alternative to the IntValue() method with richer error checking. If the value is an integer, it is stored in 'value' and the call returns TIXML_SUCCESS. If it is not an integer, it returns TIXML_WRONG_TYPE.
A specialized but useful call. Note that for success it returns 0, which is the opposite of almost all other TinyXml calls.
Definition at line 1194 of file tinyxml.cc.
References TIXML_SSCANF, dqm4hep::TIXML_SUCCESS, dqm4hep::TIXML_WRONG_TYPE, and value.
Referenced by dqm4hep::TiXmlElement::Attribute(), and dqm4hep::TiXmlElement::QueryIntAttribute().
{
  if (TIXML_SSCANF(value.c_str(), "%d", ival) == 1)
    return TIXML_SUCCESS;
  return TIXML_WRONG_TYPE;
}
void dqm4hep::TiXmlAttribute::SetDocument (TiXmlDocument * doc) [inline]
Definition at line 883 of file tinyxml.h.
References document.
Referenced by dqm4hep::TiXmlElement::Parse().
{ document = doc; }
void dqm4hep::TiXmlAttribute::SetDoubleValue (double _value)
Set the value from a double.
Definition at line 1219 of file tinyxml.cc.
References SetValue(), and TIXML_SNPRINTF.
Referenced by dqm4hep::TiXmlElement::SetDoubleAttribute().
{
  char buf [256];
  #if defined(TIXML_SNPRINTF)
    TIXML_SNPRINTF(buf, sizeof(buf), "%g", _value);
  #else
    sprintf (buf, "%g", _value);
  #endif
  SetValue (buf);
}
void dqm4hep::TiXmlAttribute::SetIntValue (int _value)
Set the value from an integer.
Definition at line 1208 of file tinyxml.cc.
References SetValue(), and TIXML_SNPRINTF.
Referenced by dqm4hep::TiXmlElement::SetAttribute().
{
  char buf [64];
  #if defined(TIXML_SNPRINTF)
    TIXML_SNPRINTF(buf, sizeof(buf), "%d", _value);
  #else
    sprintf (buf, "%d", _value);
  #endif
  SetValue (buf);
}
void dqm4hep::TiXmlAttribute::SetName (const char * _name) [inline]
Set the name of this attribute.
Definition at line 841 of file tinyxml.h.
References name.
Referenced by dqm4hep::TiXmlAttributeSet::FindOrCreate().
void dqm4hep::TiXmlAttribute::SetName (const std::string & _name) [inline]
STL std::string form.
Definition at line 849 of file tinyxml.h.
{ name = _name; }
void dqm4hep::TiXmlAttribute::SetValue (const char * _value) [inline]
Set the value.
Definition at line 842 of file tinyxml.h.
References value.
Referenced by dqm4hep::TiXmlElement::SetAttribute(), SetDoubleValue(), and SetIntValue().
void dqm4hep::TiXmlAttribute::SetValue (const std::string & _value) [inline]
STL std::string form.
Definition at line 851 of file tinyxml.h.
References value.
{ value = _value; }
const char* dqm4hep::TiXmlAttribute::Value () const [inline]
Return the value of this attribute.
Definition at line 818 of file tinyxml.h.
References value.
Referenced by dqm4hep::TiXmlElement::Attribute(), dqm4hep::TiXmlElement::CopyTo(), and dqm4hep::TiXmlDeclaration::Parse().
const std::string& dqm4hep::TiXmlAttribute::ValueStr () const [inline]
Return the value of this attribute.
Definition at line 820 of file tinyxml.h.
References value.
Referenced by dqm4hep::TiXmlElement::QueryValueAttribute().
Friends And Related Function Documentation
friend class TiXmlAttributeSet [friend]
Definition at line 787 of file tinyxml.h.
Member Data Documentation
TiXmlDocument* dqm4hep::TiXmlAttribute::document [private]
Definition at line 889 of file tinyxml.h.
Referenced by SetDocument(), and TiXmlAttribute().
TIXML_STRING dqm4hep::TiXmlAttribute::name [private]
Definition at line 890 of file tinyxml.h.
Referenced by Name(), NameTStr(), Next(), operator<(), operator==(), operator>(), Parse(), Previous(), SetName(), and TiXmlAttribute().
TiXmlAttribute* dqm4hep::TiXmlAttribute::next [private]
Definition at line 893 of file tinyxml.h.
Referenced by dqm4hep::TiXmlAttributeSet::Add(), dqm4hep::TiXmlAttributeSet::Find(), dqm4hep::TiXmlAttributeSet::First(), Next(), dqm4hep::TiXmlAttributeSet::Remove(), TiXmlAttribute(), dqm4hep::TiXmlAttributeSet::TiXmlAttributeSet(), and dqm4hep::TiXmlAttributeSet::~TiXmlAttributeSet().
TiXmlAttribute* dqm4hep::TiXmlAttribute::prev [private]
Definition at line 892 of file tinyxml.h.
Referenced by dqm4hep::TiXmlAttributeSet::Add(), dqm4hep::TiXmlAttributeSet::Last(), Previous(), dqm4hep::TiXmlAttributeSet::Remove(), TiXmlAttribute(), dqm4hep::TiXmlAttributeSet::TiXmlAttributeSet(), and dqm4hep::TiXmlAttributeSet::~TiXmlAttributeSet().
TIXML_STRING dqm4hep::TiXmlAttribute::value [private]
Definition at line 891 of file tinyxml.h.
Referenced by DoubleValue(), IntValue(), Next(), Parse(), Previous(), Print(), QueryDoubleValue(), QueryIntValue(), SetValue(), TiXmlAttribute(), Value(), and ValueStr().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc