dqm4hep::DQMCycle Class Reference
DQMCycle class.
#include <DQMCycle.h>
Public Member Functions
DQMCycle ()
Constructor.
virtual ~DQMCycle ()
Destructor.
float getCycleValue () const
Get the cycle value (time, nb of events, event size)
void setCycleValue (float value)
Set the cycle value.
unsigned int getTimeout () const
Get the cycle timeout (in seconds) Maximum time between two processEvent(evt) call.
void setTimeout (unsigned int timeout)
Set the timeout.
float getProcessingRate () const
Get the processing rate.
unsigned int getNProcessedEvents () const
Get the number of processed events at the end of cycle.
TTime getTotalCycleTime () const
Get the total time spent to process the last cycle.
void eventProcessed (const DQMEvent *const pEvent)
Called back when the application has processed an event.
const TTime & getStartTime () const
Get the start time of the current cycle.
const TTime & getEndTime () const
Get the end time of the last cycle.
void startCycle ()
Start the cycle.
void stopCycle ()
Stop the cycle.
DQMState getState () const
Get the cycle state (running, stopped)
bool isTimeoutReached () const
Whether the timeout is reached.
void addListener (DQMCycleListener *pListener)
Add a cycle listener.
void removeListener (DQMCycleListener *pListener)
Remove a cycle listener.
virtual void onCycleStarted ()=0
Specific call back function when a cycle is stopped.
virtual void onCycleStopped ()=0
Specific call back function when a cycle is stopped.
virtual void onEventProcessed (const DQMEvent *const pEvent)=0
Specific call back function when an event is processed, depends on cycle type.
virtual bool isEndOfCycleReached () const =0
Specific function to tell the application to know whether the cycle has reached the end.
Private Attributes
float m_processingRate
float m_cycleValue
unsigned int m_cycleTimeout
unsigned int m_nProcessedEvents
TTime m_startTime
TTime m_endTime
TTime m_lastEventProcessedTime
std::set< DQMCycleListener * > m_listeners
DQMState m_state
Detailed Description
DQMCycle class.
Process a cycle of processEvent(evt) call for a DQMAnalysisModule. See implementation for cycle types.
The cycle value is the value for which the cycle should normally ends.
The timeout value is the maximum time between two processEvent(evt) call When the timeout is reached, the cycle ends. The default timeout value is 10 seconds and can be changed via the method setTimeout(secs)
Definition at line 78 of file DQMCycle.h.
Constructor & Destructor Documentation
dqm4hep::DQMCycle::DQMCycle ()
Constructor.
Definition at line 36 of file DQMCycle.cc.
                   :
    m_processingRate(0.f),
    m_cycleValue(0.f),
    m_cycleTimeout(10), // 10 seconds is the default value
    m_nProcessedEvents(0)
{
  /* nop */
}
dqm4hep::DQMCycle::~DQMCycle () [virtual]
Destructor.
Definition at line 47 of file DQMCycle.cc.
{
  /* nop */
}
Member Function Documentation
void dqm4hep::DQMCycle::addListener (DQMCycleListener * pListener)
Add a cycle listener.
Definition at line 201 of file DQMCycle.cc.
References m_listeners.
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureCycle(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  if(NULL != pListener)
    m_listeners.insert(pListener);
}
void dqm4hep::DQMCycle::eventProcessed (const DQMEvent *const pEvent)
Called back when the application has processed an event.
Definition at line 103 of file DQMCycle.cc.
References getState(), m_lastEventProcessedTime, m_listeners, m_nProcessedEvents, and onEventProcessed().
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
{
  if(this->getState() != RUNNING_STATE)
    return;
  if(NULL == pEvent)
    return;
  m_nProcessedEvents++;
  m_lastEventProcessedTime = gSystem->Now();
  // call back for daughter class
  this->onEventProcessed(pEvent);
  // call back from listeners
  for(std::set<DQMCycleListener*>::iterator iter = m_listeners.begin(), endIter =
      m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->onEventProcessed(this, pEvent);
}
float dqm4hep::DQMCycle::getCycleValue () const
Get the cycle value (time, nb of events, event size)
Definition at line 54 of file DQMCycle.cc.
References m_cycleValue.
Referenced by dqm4hep::DQMEventCounterCycle::isEndOfCycleReached(), and dqm4hep::DQMTimerCycle::isEndOfCycleReached().
{
  return m_cycleValue;
}
const TTime & dqm4hep::DQMCycle::getEndTime () const
Get the end time of the last cycle.
Valid only between two cycle after stopCycle() call
Definition at line 132 of file DQMCycle.cc.
References m_endTime.
{
  return m_endTime;
}
unsigned int dqm4hep::DQMCycle::getNProcessedEvents () const
Get the number of processed events at the end of cycle.
Definition at line 89 of file DQMCycle.cc.
References m_nProcessedEvents.
Referenced by dqm4hep::DQMEventCounterCycle::isEndOfCycleReached(), and dqm4hep::DQMAnalysisModuleApplication::run().
{
  return m_nProcessedEvents;
}
float dqm4hep::DQMCycle::getProcessingRate () const
Get the processing rate.
May be called after stopCycle() to get the correct value
Definition at line 82 of file DQMCycle.cc.
References m_processingRate.
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
{
  return m_processingRate;
}
const TTime & dqm4hep::DQMCycle::getStartTime () const
Get the start time of the current cycle.
Definition at line 125 of file DQMCycle.cc.
References m_startTime.
Referenced by dqm4hep::DQMTimerCycle::isEndOfCycleReached().
{
  return m_startTime;
}
DQMState dqm4hep::DQMCycle::getState () const
Get the cycle state (running, stopped)
Definition at line 181 of file DQMCycle.cc.
References m_state.
Referenced by eventProcessed().
{
  return m_state;
}
unsigned int dqm4hep::DQMCycle::getTimeout () const
Get the cycle timeout (in seconds) Maximum time between two processEvent(evt) call.
When the timeout is reached, the cycle ends
Definition at line 68 of file DQMCycle.cc.
References m_cycleTimeout.
Referenced by isTimeoutReached().
{
  return m_cycleTimeout;
}
TTime dqm4hep::DQMCycle::getTotalCycleTime () const
Get the total time spent to process the last cycle.
Definition at line 96 of file DQMCycle.cc.
References m_endTime, and m_startTime.
Referenced by dqm4hep::DQMAnalysisModuleApplication::run(), and stopCycle().
{
  return (m_endTime - m_startTime);
}
virtual bool dqm4hep::DQMCycle::isEndOfCycleReached () const [pure virtual]
Specific function to tell the application to know whether the cycle has reached the end.
Implemented in dqm4hep::DQMTimerCycle , and dqm4hep::DQMEventCounterCycle .
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
bool dqm4hep::DQMCycle::isTimeoutReached () const
Whether the timeout is reached.
Definition at line 188 of file DQMCycle.cc.
References getTimeout(), and m_lastEventProcessedTime.
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
{
  if(m_lastEventProcessedTime == TTime(0))
    return false;
  if(gSystem->Now() > m_lastEventProcessedTime + TTime(this->getTimeout()*1000))
    return true;
  return false;
}
virtual void dqm4hep::DQMCycle::onCycleStarted () [pure virtual]
Specific call back function when a cycle is stopped.
Implemented in dqm4hep::DQMTimerCycle , and dqm4hep::DQMEventCounterCycle .
Referenced by startCycle().
virtual void dqm4hep::DQMCycle::onCycleStopped () [pure virtual]
Specific call back function when a cycle is stopped.
Implemented in dqm4hep::DQMTimerCycle , and dqm4hep::DQMEventCounterCycle .
Referenced by stopCycle().
virtual void dqm4hep::DQMCycle::onEventProcessed (const DQMEvent *const pEvent) [pure virtual]
Specific call back function when an event is processed, depends on cycle type.
Implemented in dqm4hep::DQMTimerCycle , and dqm4hep::DQMEventCounterCycle .
Referenced by eventProcessed().
void dqm4hep::DQMCycle::removeListener (DQMCycleListener * pListener)
Remove a cycle listener.
Definition at line 209 of file DQMCycle.cc.
References m_listeners.
{
  m_listeners.erase(pListener);
}
void dqm4hep::DQMCycle::setCycleValue (float value)
Set the cycle value.
Definition at line 61 of file DQMCycle.cc.
References m_cycleValue.
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureCycle(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  m_cycleValue = value;
}
void dqm4hep::DQMCycle::setTimeout (unsigned int timeout)
Set the timeout.
Definition at line 75 of file DQMCycle.cc.
References m_cycleTimeout.
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureCycle(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  m_cycleTimeout = timeout;
}
void dqm4hep::DQMCycle::startCycle ()
Start the cycle.
Definition at line 139 of file DQMCycle.cc.
References m_endTime, m_lastEventProcessedTime, m_listeners, m_nProcessedEvents, m_processingRate, m_startTime, m_state, and onCycleStarted().
Referenced by dqm4hep::DQMStandaloneModuleApplication::run(), and dqm4hep::DQMAnalysisModuleApplication::run().
{
  m_startTime = gSystem->Now();
  m_lastEventProcessedTime = m_startTime;
  m_endTime = TTime(0);
  m_nProcessedEvents = 0;
  m_processingRate = 0.f;
  m_state = RUNNING_STATE;
  // call back for daughter class
  this->onCycleStarted();
  // call back from listeners
  for(std::set<DQMCycleListener*>::iterator iter = m_listeners.begin(), endIter =
      m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->onCycleStarted(this);
}
void dqm4hep::DQMCycle::stopCycle ()
Stop the cycle.
Definition at line 160 of file DQMCycle.cc.
References getTotalCycleTime(), m_endTime, m_listeners, m_nProcessedEvents, m_processingRate, m_state, and onCycleStopped().
Referenced by dqm4hep::DQMStandaloneModuleApplication::run(), and dqm4hep::DQMAnalysisModuleApplication::run().
{
  m_endTime = gSystem->Now();
  m_state = STOPPED_STATE;
  TTime timeDifference = this->getTotalCycleTime();
  if(timeDifference != TTime(0))
    m_processingRate = (static_cast<float>(m_nProcessedEvents) / timeDifference.operator long long());
  // call back for daughter class
  this->onCycleStopped();
  // call back from listeners
  for(std::set<DQMCycleListener*>::iterator iter = m_listeners.begin(), endIter =
      m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->onCycleStopped(this);
}
Member Data Documentation
unsigned int dqm4hep::DQMCycle::m_cycleTimeout [private]
Definition at line 177 of file DQMCycle.h.
Referenced by getTimeout(), and setTimeout().
float dqm4hep::DQMCycle::m_cycleValue [private]
Definition at line 176 of file DQMCycle.h.
Referenced by getCycleValue(), and setCycleValue().
TTime dqm4hep::DQMCycle::m_endTime [private]
Definition at line 180 of file DQMCycle.h.
Referenced by getEndTime(), getTotalCycleTime(), startCycle(), and stopCycle().
TTime dqm4hep::DQMCycle::m_lastEventProcessedTime [private]
Definition at line 181 of file DQMCycle.h.
Referenced by eventProcessed(), isTimeoutReached(), and startCycle().
std::set<DQMCycleListener*> dqm4hep::DQMCycle::m_listeners [private]
Definition at line 182 of file DQMCycle.h.
Referenced by addListener(), eventProcessed(), removeListener(), startCycle(), and stopCycle().
unsigned int dqm4hep::DQMCycle::m_nProcessedEvents [private]
Definition at line 178 of file DQMCycle.h.
Referenced by eventProcessed(), getNProcessedEvents(), startCycle(), and stopCycle().
float dqm4hep::DQMCycle::m_processingRate [private]
Definition at line 175 of file DQMCycle.h.
Referenced by getProcessingRate(), startCycle(), and stopCycle().
TTime dqm4hep::DQMCycle::m_startTime [private]
Definition at line 179 of file DQMCycle.h.
Referenced by getStartTime(), getTotalCycleTime(), and startCycle().
DQMState dqm4hep::DQMCycle::m_state [private]
Definition at line 183 of file DQMCycle.h.
Referenced by getState(), startCycle(), and stopCycle().
The documentation for this class was generated from the following files:
DQMCycle.h
DQMCycle.cc