dqm4hep::DQMMonitorElementClient Class Reference
DQMMonitorElementClient class.
#include <DQMMonitorElementClient.h>
Public Member Functions
DQMMonitorElementClient ()
Constructor.
~DQMMonitorElementClient ()
Destructor.
StatusCode setCollectorName (const std::string &collectorName)
Set the collector name.
const std::string & getCollectorName () const
Get the collector name.
StatusCode connectToService ()
Connect the client to the service.
StatusCode disconnectFromService ()
Disconnect the client from the service.
bool isConnectedToService () const
Whether the client is connected to the service.
StatusCode queryCollectorInfo ()
Sent a request to the collector to get back the collector informations.
StatusCode queryAvailableMonitorElements (const DQMMonitorElementListNameRequest &request)
Send a request to get back monitor element list name (small packet info)
StatusCode subscribe (const DQMMonitorElementRequest &request)
Unsubscribe to monitor elements.
StatusCode unsubscribe (const DQMMonitorElementRequest &request)
Subscribe to monitor elements.
StatusCode replaceSubscription (const DQMMonitorElementRequest &request)
Unsubscribe to all monitor elements the client has already subscribed and subscribe to monitor elements.
StatusCode querySubscribedMonitorElements (const DQMMonitorElementRequest &request)
Send a command to query the monitor element list.
StatusCode querySubscribedMonitorElements ()
Send a command to query the monitor element list that the client subscribed.
void setUpdateMode (bool updateMode)
Set the update mode.
bool getUpdateMode () const
Get the update mode.
bool isCollectorRunning () const
Whether the collector is running.
bool addListener (DQMMonitorElementClientListener *pListener)
Add a listener to this client (observer pattern).
void removeListener (DQMMonitorElementClientListener *pListener)
Remove a listener from this client.
Static Public Attributes
static const std::string m_emptyBufferStr = `EMPTY`
Private Member Functions
void handleMeCollectorInfoRpcInfo (DimRpcInfo *pRpcInfo)
Handle the collector info rpc callback.
void handleMeListNameRpcInfo (DimRpcInfo *pRpcInfo)
Handle the me name list rpc callback.
void infoHandler ()
Dim info handler.
void clearPublication (DQMMonitorElementPublication &publication)
Deep clear of publication.
Private Attributes
DimRpcInfo * m_pMeCollectorInfoRpcInfo
DimRpcInfo * m_pMeListNameRpcInfo
DimUpdatedInfo * m_pMeUpdateInfo
DimInfo * m_pCollectorStateInfo
DQMDataStream m_inDataStream
DQMDataStream m_outDataStream
std::string m_collectorName
bool m_isConnected
bool m_updateMode
bool m_isCollectorRunning
std::vector
*
< DQMMonitorElementClientListener * > m_listeners
Friends
class DQMMeCollectorInfoRpcInfo
class DQMMeListNameRpcInfo
Detailed Description
DQMMonitorElementClient class.
Definition at line 122 of file DQMMonitorElementClient.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElementClient::DQMMonitorElementClient ()
Constructor.
Definition at line 78 of file DQMMonitorElementClient.cc.
                                                 :
    m_isConnected(false),
    m_pMeCollectorInfoRpcInfo(NULL),
    m_pMeListNameRpcInfo(NULL),
    m_inDataStream(4*1024*1024),
    m_outDataStream(1024*1024),
    m_updateMode(false),
    m_isCollectorRunning(false)
{
  /* nop */
}
dqm4hep::DQMMonitorElementClient::~DQMMonitorElementClient ()
Destructor.
Definition at line 92 of file DQMMonitorElementClient.cc.
References disconnectFromService(), and isConnectedToService().
{
  if(isConnectedToService())
    disconnectFromService();
}
Member Function Documentation
bool dqm4hep::DQMMonitorElementClient::addListener (DQMMonitorElementClientListener * pListener)
Add a listener to this client (observer pattern).
Definition at line 323 of file DQMMonitorElementClient.cc.
References m_listeners.
{
  if(NULL == pListener)
    return false;
  std::vector<DQMMonitorElementClientListener *>::iterator findIter = std::find(
      m_listeners.begin(), m_listeners.end(), pListener);
  // if already added, return ok
  if(m_listeners.end() != findIter)
    return true;
  m_listeners.push_back(pListener);
  return true;
}
void dqm4hep::DQMMonitorElementClient::clearPublication (DQMMonitorElementPublication & publication) [private]
Deep clear of publication.
Definition at line 497 of file DQMMonitorElementClient.cc.
Referenced by infoHandler().
{
  for(DQMMonitorElementPublication::iterator iter = publication.begin(), endIter = publication.end() ;
      endIter != iter ; ++iter)
  {
    for(DQMMonitorElementList::iterator meIter = iter->second.begin(), meEndIter = iter->second.end() ;
        meEndIter != meIter ; ++meIter)
    {
      delete *meIter;
    }
  }
  publication.clear();
}
StatusCode dqm4hep::DQMMonitorElementClient::connectToService ()
Connect the client to the service.
Definition at line 122 of file DQMMonitorElementClient.cc.
References DQMMeCollectorInfoRpcInfo, DQMMeListNameRpcInfo, getUpdateMode(), isConnectedToService(), m_collectorName, m_isConnected, m_listeners, m_pCollectorStateInfo, m_pMeCollectorInfoRpcInfo, m_pMeListNameRpcInfo, m_pMeUpdateInfo, and setUpdateMode().
{
  if(isConnectedToService())
    return STATUS_CODE_SUCCESS;
  std::string collectorName = "DQM4HEP/MonitorElementCollector/" +
      m_collectorName + "/";
  std::stringstream ss;
  ss << collectorName << "COLLECTOR_INFO_RPC";
  m_pMeCollectorInfoRpcInfo = new DQMMeCollectorInfoRpcInfo((char*) ss.str().c_str(), this);
  ss.str("");
  ss << collectorName << "MONITOR_ELEMENT_NAME_LIST_RPC";
  m_pMeListNameRpcInfo = new DQMMeListNameRpcInfo((char*) ss.str().c_str(), this);
  ss.str("");
  ss << collectorName << "ME_UPDATE_SVC";
  m_pMeUpdateInfo = new DimUpdatedInfo((char*) ss.str().c_str() , (void *) NULL , 0, this);
  ss.str("");
  ss << collectorName << "COLLECTOR_STATE_SVC";
  m_pCollectorStateInfo = new DimInfo((char*) ss.str().c_str() , static_cast<int>(STOPPED_STATE) , this);
  m_isConnected = true;
  this->setUpdateMode(this->getUpdateMode());
  for(std::vector<DQMMonitorElementClientListener *>::iterator iter =
      m_listeners.begin(), endIter = m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->onMonitorElementClientConnect(this);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementClient::disconnectFromService ()
Disconnect the client from the service.
Definition at line 158 of file DQMMonitorElementClient.cc.
References isConnectedToService(), m_isConnected, m_listeners, m_pCollectorStateInfo, m_pMeCollectorInfoRpcInfo, m_pMeListNameRpcInfo, and m_pMeUpdateInfo.
Referenced by ~DQMMonitorElementClient().
{
  if(!isConnectedToService())
    return STATUS_CODE_SUCCESS;
  delete m_pMeCollectorInfoRpcInfo; m_pMeCollectorInfoRpcInfo = NULL;
  delete m_pMeListNameRpcInfo; m_pMeListNameRpcInfo = NULL;
  delete m_pMeUpdateInfo; m_pMeUpdateInfo = NULL;
  delete m_pCollectorStateInfo; m_pCollectorStateInfo = NULL;
  m_isConnected = false;
  for(std::vector<DQMMonitorElementClientListener *>::iterator iter =
      m_listeners.begin(), endIter = m_listeners.end() ;
      endIter != iter ; ++iter)
    (*iter)->onMonitorElementClientDisconnect(this);
  return STATUS_CODE_SUCCESS;
}
const std::string & dqm4hep::DQMMonitorElementClient::getCollectorName () const
Get the collector name.
Definition at line 115 of file DQMMonitorElementClient.cc.
References m_collectorName.
{
  return m_collectorName;
}
bool dqm4hep::DQMMonitorElementClient::getUpdateMode () const
Get the update mode.
Definition at line 316 of file DQMMonitorElementClient.cc.
References m_updateMode.
Referenced by connectToService(), and infoHandler().
{
  return m_updateMode;
}
void dqm4hep::DQMMonitorElementClient::handleMeCollectorInfoRpcInfo (DimRpcInfo * pRpcInfo) [private]
Handle the collector info rpc callback.
Definition at line 356 of file DQMMonitorElementClient.cc.
References m_inDataStream, m_listeners, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), and THROW_RESULT_IF.
Referenced by dqm4hep::DQMMeCollectorInfoRpcInfo::rpcInfoHandler().
{
  try
  {
    if(m_listeners.empty())
      return;
    dqm_char *pBuffer = static_cast<dqm_char *>(pRpcInfo->getData());
    dqm_uint bufferSize = pRpcInfo->getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      return;
    m_inDataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_inDataStream.setBuffer(pBuffer, bufferSize));
    // deserialize and notify
    DQMCollectorInfo collectorInfo;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, collectorInfo.deserialize(&
      m_inDataStream));
    for(std::vector<DQMMonitorElementClientListener *>::iterator iter =
      m_listeners.begin(), endIter = m_listeners.end() ;
        endIter != iter ; ++iter)
      (*iter)->monitorElementCollectorInfoReceived(this, collectorInfo);
  }
  catch(StatusCodeException &exception)
  {
  }
  catch(...)
  {
  }
}
void dqm4hep::DQMMonitorElementClient::handleMeListNameRpcInfo (DimRpcInfo * pRpcInfo) [private]
Handle the me name list rpc callback.
Definition at line 390 of file DQMMonitorElementClient.cc.
References m_inDataStream, m_listeners, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), and THROW_RESULT_IF.
Referenced by dqm4hep::DQMMeListNameRpcInfo::rpcInfoHandler().
{
  try
  {
    if(m_listeners.empty())
      return;
    dqm_char *pBuffer = static_cast<dqm_char*>(pRpcInfo->getData());
    dqm_uint bufferSize = pRpcInfo->getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    m_inDataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_inDataStream.setBuffer(pBuffer, bufferSize));
    // deserialize and notify
    DQMMonitorElementInfoList monitorElementInfoList;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, monitorElementInfoList.deserialize(&
      m_inDataStream));
    for(std::vector<DQMMonitorElementClientListener *>::iterator iter =
      m_listeners.begin(), endIter = m_listeners.end() ;
        endIter != iter ; ++iter)
      (*iter)->availableMonitorElementListReceived(this, monitorElementInfoList);
  }
  catch(StatusCodeException &exception)
  {
  }
  catch(...)
  {
  }
}
void dqm4hep::DQMMonitorElementClient::infoHandler () [private]
Dim info handler.
Definition at line 424 of file DQMMonitorElementClient.cc.
References clearPublication(), dqm4hep::DQMMonitorElementPublication::deserialize(), getUpdateMode(), isCollectorRunning(), m_inDataStream, m_isCollectorRunning, m_listeners, m_pCollectorStateInfo, m_pMeUpdateInfo, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), setUpdateMode(), and THROW_RESULT_IF.
{
  DimInfo *pInfo = getInfo();
  std::cout << "Received info : " << pInfo->getName() << std::endl;
  if(pInfo == m_pMeUpdateInfo)
  {
    DQMMonitorElementPublication monitorElementPublication;
    try
    {
      if(m_listeners.empty())
        return;
      dqm_char *pBuffer = static_cast<dqm_char *>(m_pMeUpdateInfo->getData());
      dqm_uint bufferSize = m_pMeUpdateInfo->getSize();
      if(NULL == pBuffer || 0 == bufferSize)
        throw StatusCodeException(STATUS_CODE_FAILURE);
      m_inDataStream.reset();
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_inDataStream.setBuffer(pBuffer, bufferSize));
      // deserialize and call the user call back function
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, monitorElementPublication.deserialize(&
      m_inDataStream));
      for(std::vector<DQMMonitorElementClientListener *>::iterator iter =
      m_listeners.begin(), endIter = m_listeners.end() ;
          endIter != iter ; ++iter)
        (*iter)->monitorElementsReceived(this, monitorElementPublication);
    }
    catch(StatusCodeException &exception)
    {
    }
    catch(...)
    {
    }
    std::cout << "Clearing publication !" << std::endl;
    this->clearPublication(monitorElementPublication);
  }
  else if(pInfo == m_pCollectorStateInfo)
  {
    bool isCollectorRunning = static_cast<bool>(m_pCollectorStateInfo->getInt());
    std::cout << "Received collector state : " << isCollectorRunning << std::endl;
    if(isCollectorRunning == m_isCollectorRunning)
      return;
    m_isCollectorRunning = isCollectorRunning;
    if(m_isCollectorRunning)
    {
      // send back update mode info to collector
      this->setUpdateMode(this->getUpdateMode());
      // notify server state !
      for(std::vector<DQMMonitorElementClientListener *>::iterator iter =
      m_listeners.begin(), endIter = m_listeners.end() ;
          endIter != iter ; ++iter)
        (*iter)->onServerStartup(this);
    }
    else
    {
      // notify server state !
      for(std::vector<DQMMonitorElementClientListener *>::iterator iter =
      m_listeners.begin(), endIter = m_listeners.end() ;
          endIter != iter ; ++iter)
        (*iter)->onServerShutdown(this);
    }
  }
}
bool dqm4hep::DQMMonitorElementClient::isCollectorRunning () const
Whether the collector is running.
Definition at line 514 of file DQMMonitorElementClient.cc.
References m_isCollectorRunning.
Referenced by infoHandler().
{
  return m_isCollectorRunning;
}
bool dqm4hep::DQMMonitorElementClient::isConnectedToService () const
Whether the client is connected to the service.
Definition at line 179 of file DQMMonitorElementClient.cc.
References m_isConnected.
Referenced by connectToService(), disconnectFromService(), queryAvailableMonitorElements(), queryCollectorInfo(), querySubscribedMonitorElements(), replaceSubscription(), setCollectorName(), setUpdateMode(), subscribe(), unsubscribe(), and ~DQMMonitorElementClient().
{
  return m_isConnected;
}
StatusCode dqm4hep::DQMMonitorElementClient::queryAvailableMonitorElements (const DQMMonitorElementListNameRequest & request)
Send a request to get back monitor element list name (small packet info)
Definition at line 199 of file DQMMonitorElementClient.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isConnectedToService(), m_outDataStream, m_pMeListNameRpcInfo, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, and dqm4hep::DQMMonitorElementListNameRequest::serialize().
{
  if(!isConnectedToService())
    return STATUS_CODE_NOT_ALLOWED;
  // serialize the list
  m_outDataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.serialize(&m_outDataStream));
  // send query
  m_pMeListNameRpcInfo->setData((void *) m_outDataStream.getBuffer(),
      m_outDataStream.getBufferSize());
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementClient::queryCollectorInfo ()
Sent a request to the collector to get back the collector informations.
Definition at line 186 of file DQMMonitorElementClient.cc.
References isConnectedToService(), and m_pMeCollectorInfoRpcInfo.
{
  if(!isConnectedToService())
    return STATUS_CODE_NOT_ALLOWED;
  char buf[] = "\0";
  m_pMeCollectorInfoRpcInfo->setData((void *) &buf[0], 1);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementClient::querySubscribedMonitorElements (const DQMMonitorElementRequest & request)
Send a command to query the monitor element list.
The element in the list are first subscribed. Then a query is sent to update only the element in the request
Definition at line 216 of file DQMMonitorElementClient.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isConnectedToService(), m_collectorName, m_outDataStream, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, and dqm4hep::DQMMonitorElementRequest::serialize().
{
  if(!isConnectedToService())
    return STATUS_CODE_NOT_ALLOWED;
  // serialize the request
  m_outDataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.serialize(&m_outDataStream));
  // send the request
  std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/QUERY_ME_CMD";
  DimClient::sendCommandNB(commandName.c_str() , (void *) m_outDataStream.
      getBuffer() , m_outDataStream.getBufferSize());
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementClient::querySubscribedMonitorElements ()
Send a command to query the monitor element list that the client subscribed.
Definition at line 234 of file DQMMonitorElementClient.cc.
{
  // send empty request.
  DQMMonitorElementRequest request;
  return this->querySubscribedMonitorElements(request);
}
void dqm4hep::DQMMonitorElementClient::removeListener (DQMMonitorElementClientListener * pListener)
Remove a listener from this client.
Definition at line 341 of file DQMMonitorElementClient.cc.
References m_listeners.
{
  if(NULL == pListener)
    return;
  std::vector<DQMMonitorElementClientListener *>::iterator findIter = std::find(
      m_listeners.begin(), m_listeners.end(), pListener);
  if(m_listeners.end() == findIter)
    return;
  m_listeners.erase(findIter);
}
StatusCode dqm4hep::DQMMonitorElementClient::replaceSubscription (const DQMMonitorElementRequest & request)
Unsubscribe to all monitor elements the client has already subscribed and subscribe to monitor elements.
Definition at line 285 of file DQMMonitorElementClient.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isConnectedToService(), m_collectorName, m_outDataStream, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, and dqm4hep::DQMMonitorElementRequest::serialize().
{
  if(!isConnectedToService())
    return STATUS_CODE_NOT_ALLOWED;
  // serialize the request
  m_outDataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.serialize(&m_outDataStream));
  // send the request
  std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/SET_SUBSCRIPTION_CMD";
  DimClient::sendCommandNB(commandName.c_str() , (void *) m_outDataStream.
      getBuffer(), m_outDataStream.getBufferSize());
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementClient::setCollectorName (const std::string & collectorName)
Set the collector name.
Can be done only if the client is not yet connected to collector service
Definition at line 100 of file DQMMonitorElementClient.cc.
References isConnectedToService(), and m_collectorName.
{
  if(collectorName.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  if(isConnectedToService())
    return STATUS_CODE_NOT_ALLOWED;
  m_collectorName = collectorName;
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMMonitorElementClient::setUpdateMode (bool updateMode)
Set the update mode.
If set to true, subscribed monitor elements will be received when an update is performed on the collector server side
Definition at line 303 of file DQMMonitorElementClient.cc.
References isConnectedToService(), m_collectorName, and m_updateMode.
Referenced by connectToService(), and infoHandler().
{
  if(this->isConnectedToService())
  {
    std::string commandName = "DQM4HEP/MonitorElementCollector/" +
      m_collectorName + "/SET_UPDATE_MODE_CMD";
    DimClient::sendCommandNB(commandName.c_str() , static_cast<int>(updateMode));
  }
  m_updateMode = updateMode;
}
StatusCode dqm4hep::DQMMonitorElementClient::subscribe (const DQMMonitorElementRequest & request)
Unsubscribe to monitor elements.
Definition at line 243 of file DQMMonitorElementClient.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isConnectedToService(), m_collectorName, m_outDataStream, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, and dqm4hep::DQMMonitorElementRequest::serialize().
{
  if(!isConnectedToService())
    return STATUS_CODE_NOT_ALLOWED;
  for(DQMMonitorElementRequest::const_iterator iter = request.begin(), endIter = request.end() ;
      endIter != iter ; ++iter)
  {
    std::cout << "Sending subscription : " << iter->first << " , " << iter->second << std::endl;
  }
  // serialize the request
  m_outDataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.serialize(&m_outDataStream));
  // send the request
  std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/SUBSCRIBE_CMD";
  DimClient::sendCommandNB(commandName.c_str() , (void *) m_outDataStream.
      getBuffer(), m_outDataStream.getBufferSize());
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementClient::unsubscribe (const DQMMonitorElementRequest & request)
Subscribe to monitor elements.
Definition at line 267 of file DQMMonitorElementClient.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isConnectedToService(), m_collectorName, m_outDataStream, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, and dqm4hep::DQMMonitorElementRequest::serialize().
{
  if(!isConnectedToService())
    return STATUS_CODE_NOT_ALLOWED;
  // serialize the request
  m_outDataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.serialize(&m_outDataStream));
  // send the request
  std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/UNSUBSCRIBE_CMD";
  DimClient::sendCommandNB(commandName.c_str() , (void *) m_outDataStream.
      getBuffer(), m_outDataStream.getBufferSize());
  return STATUS_CODE_SUCCESS;
}
Friends And Related Function Documentation
friend class DQMMeCollectorInfoRpcInfo [friend]
Definition at line 243 of file DQMMonitorElementClient.h.
Referenced by connectToService().
friend class DQMMeListNameRpcInfo [friend]
Definition at line 244 of file DQMMonitorElementClient.h.
Referenced by connectToService().
Member Data Documentation
std::string dqm4hep::DQMMonitorElementClient::m_collectorName [private]
Definition at line 235 of file DQMMonitorElementClient.h.
Referenced by connectToService(), getCollectorName(), querySubscribedMonitorElements(), replaceSubscription(), setCollectorName(), setUpdateMode(), subscribe(), and unsubscribe().
const std::string dqm4hep::DQMMonitorElementClient::m_emptyBufferStr = `EMPTY` [static]
Definition at line 207 of file DQMMonitorElementClient.h.
DQMDataStream dqm4hep::DQMMonitorElementClient::m_inDataStream [private]
Definition at line 232 of file DQMMonitorElementClient.h.
Referenced by handleMeCollectorInfoRpcInfo(), handleMeListNameRpcInfo(), and infoHandler().
bool dqm4hep::DQMMonitorElementClient::m_isCollectorRunning [private]
Definition at line 238 of file DQMMonitorElementClient.h.
Referenced by infoHandler(), and isCollectorRunning().
bool dqm4hep::DQMMonitorElementClient::m_isConnected [private]
Definition at line 236 of file DQMMonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and isConnectedToService().
std::vector<DQMMonitorElementClientListener *> dqm4hep::DQMMonitorElementClient::m_listeners [private]
Definition at line 241 of file DQMMonitorElementClient.h.
Referenced by addListener(), connectToService(), disconnectFromService(), handleMeCollectorInfoRpcInfo(), handleMeListNameRpcInfo(), infoHandler(), and removeListener().
DQMDataStream dqm4hep::DQMMonitorElementClient::m_outDataStream [private]
Definition at line 233 of file DQMMonitorElementClient.h.
Referenced by queryAvailableMonitorElements(), querySubscribedMonitorElements(), replaceSubscription(), subscribe(), and unsubscribe().
DimInfo* dqm4hep::DQMMonitorElementClient::m_pCollectorStateInfo [private]
Definition at line 230 of file DQMMonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
DimRpcInfo* dqm4hep::DQMMonitorElementClient::m_pMeCollectorInfoRpcInfo [private]
Definition at line 227 of file DQMMonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and queryCollectorInfo().
DimRpcInfo* dqm4hep::DQMMonitorElementClient::m_pMeListNameRpcInfo [private]
Definition at line 228 of file DQMMonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and queryAvailableMonitorElements().
DimUpdatedInfo* dqm4hep::DQMMonitorElementClient::m_pMeUpdateInfo [private]
Definition at line 229 of file DQMMonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
bool dqm4hep::DQMMonitorElementClient::m_updateMode [private]
Definition at line 237 of file DQMMonitorElementClient.h.
Referenced by getUpdateMode(), and setUpdateMode().
The documentation for this class was generated from the following files:
DQMMonitorElementClient.h
DQMMonitorElementClient.cc