dqm4hep::DQMEventCollector Class Reference
DQMEventCollector class.
#include <DQMEventCollector.h>
Public Member Functions
DQMEventCollector ()
Constructor.
DQMEventCollector (DQMEventCollectorImp *pCollectorImp)
Constructor with collector implementation.
~DQMEventCollector ()
Destructor.
StatusCode setCollectorName (const std::string &collectorName)
Set the collctor name.
const std::string & getCollectorName () const
Get the collector name.
bool isRunning () const
Whether the collector server is running.
StatusCode startCollector ()
Start the collector server.
StatusCode stopCollector ()
Stop the collector server.
void setEventCollectorImp (DQMEventCollectorImp *pCollectorImp)
Set the event collector implementation.
void setEventStreamer (DQMEventStreamer *pEventStreamer)
Set the event streamer to serialize/deserialize the in/out-coming events.
DQMEventStreamer * getEventStreamer () const
Get the event streamer.
Private Attributes
DQMEventCollectorImp * m_pCollectorImp
Detailed Description
DQMEventCollector class.
Definition at line 41 of file DQMEventCollector.h.
Constructor & Destructor Documentation
dqm4hep::DQMEventCollector::DQMEventCollector ()
Constructor.
Definition at line 34 of file DQMEventCollector.cc.
References m_pCollectorImp.
{
  // default implementation is the DIM one
  m_pCollectorImp = new DQMDimEventCollector();
}
dqm4hep::DQMEventCollector::DQMEventCollector (DQMEventCollectorImp * pCollectorImp)
Constructor with collector implementation.
Definition at line 42 of file DQMEventCollector.cc.
                                                                        :
    m_pCollectorImp(pCollectorImp)
{
  /* nop */
}
dqm4hep::DQMEventCollector::~DQMEventCollector ()
Destructor.
Definition at line 50 of file DQMEventCollector.cc.
References m_pCollectorImp.
{
  delete m_pCollectorImp;
}
Member Function Documentation
const std::string & dqm4hep::DQMEventCollector::getCollectorName () const
Get the collector name.
Definition at line 64 of file DQMEventCollector.cc.
References dqm4hep::DQMEventCollectorImp::getCollectorName(), and m_pCollectorImp.
Referenced by dqm4hep::DQMEventCollectorApplication::getName().
{
  return m_pCollectorImp->getCollectorName();
}
DQMEventStreamer * dqm4hep::DQMEventCollector::getEventStreamer () const
Get the event streamer.
Definition at line 110 of file DQMEventCollector.cc.
References dqm4hep::DQMEventCollectorImp::getEventStreamer(), and m_pCollectorImp.
Referenced by dqm4hep::DQMEventCollectorApplication::getEventStreamer().
{
  return m_pCollectorImp->getEventStreamer();
}
bool dqm4hep::DQMEventCollector::isRunning () const
Whether the collector server is running.
Definition at line 71 of file DQMEventCollector.cc.
References dqm4hep::DQMEventCollectorImp::isRunning(), and m_pCollectorImp.
Referenced by dqm4hep::DQMEventCollectorApplication::~DQMEventCollectorApplication().
{
  return m_pCollectorImp->isRunning();
}
StatusCode dqm4hep::DQMEventCollector::setCollectorName (const std::string & collectorName)
Set the collctor name.
Definition at line 57 of file DQMEventCollector.cc.
References m_pCollectorImp, and dqm4hep::DQMEventCollectorImp::setCollectorName().
Referenced by dqm4hep::DQMEventCollectorApplication::setCollectorName().
{
  return m_pCollectorImp->setCollectorName(collectorName);
}
void dqm4hep::DQMEventCollector::setEventCollectorImp (DQMEventCollectorImp * pCollectorImp)
Set the event collector implementation.
Definition at line 92 of file DQMEventCollector.cc.
References m_pCollectorImp.
Referenced by dqm4hep::DQMEventCollectorApplication::setEventCollectorImp().
{
  if(NULL == pCollectorImp)
    return;
  delete m_pCollectorImp;
  m_pCollectorImp = pCollectorImp;
}
void dqm4hep::DQMEventCollector::setEventStreamer (DQMEventStreamer * pEventStreamer)
Set the event streamer to serialize/deserialize the in/out-coming events.
Definition at line 103 of file DQMEventCollector.cc.
References m_pCollectorImp, and dqm4hep::DQMEventCollectorImp::setEventStreamer().
Referenced by dqm4hep::DQMEventCollectorApplication::setEventStreamer().
{
  m_pCollectorImp->setEventStreamer(pEventStreamer);
}
StatusCode dqm4hep::DQMEventCollector::startCollector ()
Start the collector server.
Definition at line 78 of file DQMEventCollector.cc.
References m_pCollectorImp, and dqm4hep::DQMEventCollectorImp::startCollector().
Referenced by dqm4hep::DQMEventCollectorApplication::run().
{
  return m_pCollectorImp->startCollector();
}
StatusCode dqm4hep::DQMEventCollector::stopCollector ()
Stop the collector server.
Definition at line 85 of file DQMEventCollector.cc.
References m_pCollectorImp, and dqm4hep::DQMEventCollectorImp::stopCollector().
Referenced by dqm4hep::DQMEventCollectorApplication::exit(), and dqm4hep::DQMEventCollectorApplication::~DQMEventCollectorApplication().
{
  return m_pCollectorImp->stopCollector();
}
Member Data Documentation
DQMEventCollectorImp* dqm4hep::DQMEventCollector::m_pCollectorImp [private]
Definition at line 90 of file DQMEventCollector.h.
Referenced by DQMEventCollector(), getCollectorName(), getEventStreamer(), isRunning(), setCollectorName(), setEventCollectorImp(), setEventStreamer(), startCollector(), stopCollector(), and ~DQMEventCollector().
The documentation for this class was generated from the following files:
DQMEventCollector.h
DQMEventCollector.cc