dqm4hep::DQMLCEventStreamer Class Reference
DQMLCEventStreamer class.
#include <DQMLCEventStreamer.h>
Public Member Functions
DQMLCEventStreamer ()
Constructor.
~DQMLCEventStreamer ()
Destructor.
StatusCode serialize (const DQMEvent *const pEvent, DQMDataStream *const pDataStream)
Serialize the event and store it into a data stream.
StatusCode deserialize (DQMEvent *&pEvent, DQMDataStream *const pDataStream)
De-serialize the lcio event.
StatusCode serialize (const DQMEvent *const pObject, const std::string &subEventIdentifier, DQMDataStream *const pDataStream)
Serialize the a part of the event and store it into a data stream.
Private Attributes
DQMLCCollectionStreamerMap m_lcCollectionStreamerMap
DQMLCParametersStreamer m_lcParametersStreamer
Detailed Description
DQMLCEventStreamer class.
Definition at line 73 of file DQMLCEventStreamer.h.
Constructor & Destructor Documentation
dqm4hep::DQMLCEventStreamer::DQMLCEventStreamer ()
Constructor.
Definition at line 61 of file DQMLCEventStreamer.cc.
{
  m_lcCollectionStreamerMap[EVENT::LCIO::LCGENERICOBJECT] = new DQMLCCollectionStreamer(
      EVENT::LCIO::LCGENERICOBJECT, new DQMLCGenericObjectStreamer());
  m_lcCollectionStreamerMap[EVENT::LCIO::CALORIMETERHIT] = new DQMLCCollectionStreamer(
      EVENT::LCIO::CALORIMETERHIT, new DQMCalorimeterHitStreamer());
  m_lcCollectionStreamerMap[EVENT::LCIO::RAWCALORIMETERHIT] = new DQMLCCollectionStreamer(
      EVENT::LCIO::RAWCALORIMETERHIT, new DQMRawCalorimeterHitStreamer());
  m_lcCollectionStreamerMap[EVENT::LCIO::TPCHIT] = new DQMLCCollectionStreamer(EVENT::LCIO::TPCHIT, new
      DQMTPCHitStreamer());
  m_lcCollectionStreamerMap[EVENT::LCIO::CLUSTER] = new DQMLCCollectionStreamer(EVENT::LCIO::CLUSTER, new
       DQMClusterStreamer());
  m_lcCollectionStreamerMap[EVENT::LCIO::PARTICLEID] = new DQMLCCollectionStreamer(EVENT::LCIO::PARTICLEID
      , new DQMParticleIDStreamer());
  m_lcCollectionStreamerMap[EVENT::LCIO::LCFLOATVEC] = new DQMLCCollectionStreamer(EVENT::LCIO::LCFLOATVEC
      , new DQMLCFloatVecStreamer());
  m_lcCollectionStreamerMap[EVENT::LCIO::LCINTVEC] = new DQMLCCollectionStreamer(EVENT::LCIO::LCINTVEC,
      new DQMLCIntVecStreamer());
  m_lcCollectionStreamerMap[EVENT::LCIO::LCSTRVEC] = new DQMLCCollectionStreamer(EVENT::LCIO::LCSTRVEC,
      new DQMLCStrVecStreamer());
}
dqm4hep::DQMLCEventStreamer::~DQMLCEventStreamer ()
Destructor.
Definition at line 76 of file DQMLCEventStreamer.cc.
References m_lcCollectionStreamerMap.
{
  for(DQMLCCollectionStreamerMap::iterator iter = m_lcCollectionStreamerMap.begin() , endIter =
      m_lcCollectionStreamerMap.end() ;
      endIter != iter ; ++iter)
    delete iter->second;
  m_lcCollectionStreamerMap.clear();
}
Member Function Documentation
StatusCode dqm4hep::DQMLCEventStreamer::deserialize (DQMEvent *& pEvent, DQMDataStream *const pDataStream) [virtual]
De-serialize the lcio event.
Implements dqm4hep::DQMEventStreamer .
Definition at line 149 of file DQMLCEventStreamer.cc.
References dqm4hep::DQMLCParametersStreamer::deserialize(), dqm4hep::DQMDataStream::isValid(), m_lcCollectionStreamerMap, m_lcParametersStreamer, PROCESS_CODE_IF_AND_RETURN, dqm4hep::DQMDataStream::read(), RETURN_RESULT_IF, dqm4hep::DQMEvent::setEvent(), and dqm4hep::WARNING.
{
  pEvent = NULL;
  if(!pDataStream->isValid())
  {
    streamlog_out(WARNING) << "Invalid buffer while deserializing a LCEvent !" << std::endl;
    return STATUS_CODE_NOT_INITIALIZED;
  }
  pEvent = new DQMLCEvent();
  IMPL::LCEventImpl *pTmpLCEvent = new IMPL::LCEventImpl();
  pEvent->setEvent<EVENT::LCEvent>(pTmpLCEvent);
  dqm_int runNumber = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(runNumber));
  pTmpLCEvent->setRunNumber(runNumber);
  dqm_int eventNumber = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(eventNumber));
  pTmpLCEvent->setEventNumber(eventNumber);
  std::string detectorName;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(detectorName));
  pTmpLCEvent->setDetectorName(detectorName);
  dqm_lint timeStamp = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(timeStamp));
  pTmpLCEvent->setTimeStamp(timeStamp);
  dqm_double weight = 0.;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(weight));
  pTmpLCEvent->setWeight(weight);
  EVENT::LCParameters *pLCParameters = &pTmpLCEvent->parameters();
  PROCESS_CODE_IF_AND_RETURN(STATUS_CODE_SUCCESS, !=, m_lcParametersStreamer.
      deserialize(pLCParameters, pDataStream),
    delete pEvent;
  );
  dqm_int nCollections = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nCollections));
  for(int i=0 ; i<nCollections ; i++)
  {
    EVENT::LCCollection *pCollection = NULL;
    std::string collectionName;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(collectionName));
    std::string collectionType;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(collectionType));
    DQMLCCollectionStreamerMap::const_iterator findIter =
      m_lcCollectionStreamerMap.find(collectionType);
    if(m_lcCollectionStreamerMap.end() == findIter)
    {
      streamlog_out(WARNING) << "Couldn't deserialize collection of type '" << collectionType << "'. " <<
      std::endl
            << "The serializer for this collection type is not yet implemented!" << std::endl;
      delete pEvent;
      return STATUS_CODE_FAILURE;
    }
    PROCESS_CODE_IF_AND_RETURN(STATUS_CODE_SUCCESS, !=, findIter->second->deserialize(pCollection,
      pDataStream),
      delete pEvent;
    );
    pTmpLCEvent->addCollection(pCollection, collectionName);
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMLCEventStreamer::serialize (const DQMEvent *const pEvent, DQMDataStream *const pDataStream) [virtual]
Serialize the event and store it into a data stream.
Implements dqm4hep::DQMEventStreamer .
Definition at line 87 of file DQMLCEventStreamer.cc.
References dqm4hep::DQMEvent::getEvent(), m_lcCollectionStreamerMap, m_lcParametersStreamer, RETURN_RESULT_IF, dqm4hep::DQMLCParametersStreamer::serialize(), dqm4hep::WARNING, and dqm4hep::DQMDataStream::write().
Referenced by serialize().
{
  if(NULL == pEvent)
    return STATUS_CODE_INVALID_PTR;
  EVENT::LCEvent *pLCEvent = pEvent->getEvent<EVENT::LCEvent>();
  if(NULL == pLCEvent)
    return STATUS_CODE_FAILURE;
  // start filling with event parameters
  dqm_int runNumber = pLCEvent->getRunNumber();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(runNumber));
  dqm_int eventNumber = pLCEvent->getEventNumber();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(eventNumber));
  std::string detectorName = pLCEvent->getDetectorName();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(detectorName));
  dqm_lint timeStamp = pLCEvent->getTimeStamp();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(timeStamp));
  dqm_double weight = pLCEvent->getWeight();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(weight));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_lcParametersStreamer.serialize(&pLCEvent->parameters(),
      pDataStream));
  const std::vector<std::string> *collectionNames = pLCEvent->getCollectionNames();
  dqm_int nCollections = collectionNames->size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nCollections));
  // write all collections if possible
  for(std::vector<std::string>::const_iterator iter = collectionNames->begin() , endIter = collectionNames
      ->end() ;
      endIter != iter ; ++iter)
  {
    EVENT::LCCollection *pCollection = pLCEvent->getCollection(*iter);
    DQMLCCollectionStreamerMap::const_iterator findIter =
      m_lcCollectionStreamerMap.find(pCollection->getTypeName());
    if(m_lcCollectionStreamerMap.end() == findIter)
    {
      streamlog_out(WARNING) << "Couldn't serialize collection of type '" << pCollection->getTypeName() <<
      "'. " << std::endl
            << "The serializer for this collection type is not yet implemented!" << std::endl
            << "Will skip this collection" << std::endl;;
      continue;
    }
    std::string collectionName = (*iter);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(collectionName));
    std::string collectionType = pCollection->getTypeName();
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(collectionType));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, findIter->second->serialize(pCollection, pDataStream));
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMLCEventStreamer::serialize (const DQMEvent *const pObject, const std::string & subEventIdentifier, DQMDataStream *const pDataStream) [virtual]
Serialize the a part of the event and store it into a data stream.
The sub event identifier is a string of the collection names concatenated with semi columns : `collectionName1:collectionName2:collectionName3` If the sub event identifier is empty the whole event is serialized
Implements dqm4hep::DQMEventStreamer .
Definition at line 227 of file DQMLCEventStreamer.cc.
References dqm4hep::ERROR, dqm4hep::DQMEvent::getEvent(), m_lcCollectionStreamerMap, m_lcParametersStreamer, RETURN_RESULT_IF, dqm4hep::DQMLCParametersStreamer::serialize(), serialize(), dqm4hep::DQM4HEP::tokenize(), dqm4hep::WARNING, and dqm4hep::DQMDataStream::write().
{
  // no sub event queried -> serialize the whole event
  if(subEventIdentifier.empty())
    return this->serialize(pEvent, pDataStream);
  // split the collection names separated by semi columns
  StringVector collectionNames;
  DQM4HEP::tokenize(subEventIdentifier, collectionNames, ":");
  if(collectionNames.empty())
    return STATUS_CODE_FAILURE;
  if(NULL == pEvent)
    return STATUS_CODE_INVALID_PTR;
  EVENT::LCEvent *pLCEvent = pEvent->getEvent<EVENT::LCEvent>();
  if(NULL == pLCEvent)
    return STATUS_CODE_FAILURE;
  const std::vector<std::string> *pAvailableCollections = pLCEvent->getCollectionNames();
  StringVector serializeCollectionNames;
  for(StringVector::iterator iter = collectionNames.begin(), endIter = collectionNames.end() ;
      endIter != iter ; ++iter)
  {
    const std::string &collectionName(*iter);
    if(std::find(pAvailableCollections->begin(), pAvailableCollections->end(), collectionName) !=
      pAvailableCollections->end())
    {
      serializeCollectionNames.push_back(collectionName);
    }
  }
  collectionNames = serializeCollectionNames;
  if(collectionNames.empty())
  {
    streamlog_out(ERROR) << "None of the specified collections is available. Couldn't serialize the event !
      " << std::endl;
    return STATUS_CODE_FAILURE;
  }
  // start filling with event parameters
  dqm_int runNumber = pLCEvent->getRunNumber();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(runNumber));
  dqm_int eventNumber = pLCEvent->getEventNumber();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(eventNumber));
  std::string detectorName = pLCEvent->getDetectorName();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(detectorName));
  dqm_lint timeStamp = pLCEvent->getTimeStamp();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(timeStamp));
  dqm_double weight = pLCEvent->getWeight();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(weight));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_lcParametersStreamer.serialize(&pLCEvent->parameters(),
      pDataStream));
  dqm_int nCollections = collectionNames.size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nCollections));
  for(std::vector<std::string>::const_iterator iter = collectionNames.begin() , endIter = collectionNames.
      end() ;
      endIter != iter ; ++iter)
  {
    EVENT::LCCollection *pCollection = pLCEvent->getCollection(*iter);
    DQMLCCollectionStreamerMap::const_iterator findIter =
      m_lcCollectionStreamerMap.find(pCollection->getTypeName());
    if(m_lcCollectionStreamerMap.end() == findIter)
    {
      streamlog_out(WARNING) << "Couldn't serialize collection of type '" << pCollection->getTypeName() <<
      "'. " << std::endl
            << "The serializer for this collection type is not yet implemented!" << std::endl;
      return STATUS_CODE_FAILURE;
    }
    std::string collectionName = (*iter);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(collectionName));
    std::string collectionType = pCollection->getTypeName();
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(collectionType));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, findIter->second->serialize(pCollection, pDataStream));
  }
  return STATUS_CODE_SUCCESS;
}
Member Data Documentation
DQMLCCollectionStreamerMap dqm4hep::DQMLCEventStreamer::m_lcCollectionStreamerMap [private]
Definition at line 101 of file DQMLCEventStreamer.h.
Referenced by deserialize(), serialize(), and ~DQMLCEventStreamer().
DQMLCParametersStreamer dqm4hep::DQMLCEventStreamer::m_lcParametersStreamer [private]
Definition at line 102 of file DQMLCEventStreamer.h.
Referenced by deserialize(), and serialize().
The documentation for this class was generated from the following files:
DQMLCEventStreamer.h
DQMLCEventStreamer.cc