dqm4hep::TiXmlDeclaration Class Reference
In correct XML the declaration is the first entry in the file.
#include <tinyxml.h>
Public Member Functions
TiXmlDeclaration ()
Construct an empty declaration.
TiXmlDeclaration (const std::string &_version, const std::string &_encoding, const std::string &_standalone)
Constructor.
TiXmlDeclaration (const char *_version, const char *_encoding, const char *_standalone)
Construct.
TiXmlDeclaration (const TiXmlDeclaration &copy)
void operator= (const TiXmlDeclaration &copy)
virtual ~TiXmlDeclaration ()
const char * Version () const
Version. Will return an empty string if none was found.
const char * Encoding () const
Encoding. Will return an empty string if none was found.
const char * Standalone () const
Is this a standalone document?
virtual TiXmlNode * Clone () const
Creates a copy of this Declaration and returns it.
virtual void Print (FILE *cfile, int depth, TIXML_STRING *str) const
virtual void Print (FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *visitor) const
Walk the XML tree visiting this node and all of its children.
Protected Member Functions
void CopyTo (TiXmlDeclaration *target) const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Private Attributes
TIXML_STRING version
TIXML_STRING encoding
TIXML_STRING standalone
Additional Inherited Members
Detailed Description
In correct XML the declaration is the first entry in the file.
  <?xml version="1.0" standalone="yes"?>
TinyXml will happily read or write files without a declaration, however. There are 3 possible attributes to the declaration: version, encoding, and standalone.
Note: In this version of the code, the attributes are handled as special cases, not generic attributes, simply because there can only be at most 3 and they are always the same.
Definition at line 1284 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::TiXmlDeclaration::TiXmlDeclaration () [inline]
Construct an empty declaration.
Definition at line 1288 of file tinyxml.h.
Referenced by Clone().
: TiXmlNode(TiXmlNode::TINYXML_DECLARATION) {}
dqm4hep::TiXmlDeclaration::TiXmlDeclaration (const std::string & _version, const std::string & _encoding, const std::string & _standalone)
Constructor.
dqm4hep::TiXmlDeclaration::TiXmlDeclaration (const char * _version, const char * _encoding, const char * _standalone)
Construct.
Definition at line 1336 of file tinyxml.cc.
References encoding, standalone, and version.
  : TiXmlNode(TiXmlNode::TINYXML_DECLARATION)
{
  version = _version;
  encoding = _encoding;
  standalone = _standalone;
}
dqm4hep::TiXmlDeclaration::TiXmlDeclaration (const TiXmlDeclaration & copy)
Definition at line 1360 of file tinyxml.cc.
References CopyTo().
  : TiXmlNode(TiXmlNode::TINYXML_DECLARATION)
{
  copy.CopyTo(this);
}
virtual dqm4hep::TiXmlDeclaration::~TiXmlDeclaration () [inline], [virtual]
Definition at line 1305 of file tinyxml.h.
{}
Member Function Documentation
bool dqm4hep::TiXmlDeclaration::Accept (TiXmlVisitor * visitor) const [virtual]
Walk the XML tree visiting this node and all of its children.
Implements dqm4hep::TiXmlNode .
Definition at line 1406 of file tinyxml.cc.
References dqm4hep::TiXmlVisitor::Visit().
{
  return visitor->Visit(*this);
}
TiXmlNode * dqm4hep::TiXmlDeclaration::Clone () const [virtual]
Creates a copy of this Declaration and returns it.
Implements dqm4hep::TiXmlNode .
Definition at line 1412 of file tinyxml.cc.
References CopyTo(), and TiXmlDeclaration().
{
  TiXmlDeclaration* clone = new TiXmlDeclaration();
  if (!clone)
    return 0;
  CopyTo(clone);
  return clone;
}
void dqm4hep::TiXmlDeclaration::CopyTo (TiXmlDeclaration * target) const [protected]
Definition at line 1396 of file tinyxml.cc.
References dqm4hep::TiXmlNode::CopyTo(), encoding, standalone, and version.
Referenced by Clone(), operator=(), and TiXmlDeclaration().
{
  TiXmlNode::CopyTo(target);
  target->version = version;
  target->encoding = encoding;
  target->standalone = standalone;
}
const char* dqm4hep::TiXmlDeclaration::Encoding () const [inline]
Encoding. Will return an empty string if none was found.
Definition at line 1310 of file tinyxml.h.
References encoding.
Referenced by dqm4hep::TiXmlDocument::Parse().
{ return encoding.c_str (); }
void dqm4hep::TiXmlDeclaration::operator= (const TiXmlDeclaration & copy)
Definition at line 1367 of file tinyxml.cc.
References dqm4hep::TiXmlNode::Clear(), and CopyTo().
{
  Clear();
  copy.CopyTo(this);
}
const char * dqm4hep::TiXmlDeclaration::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) [virtual]
Implements dqm4hep::TiXmlBase .
Definition at line 1572 of file tinyxmlparser.cc.
References dqm4hep::TiXmlParsingData::Cursor(), encoding, dqm4hep::TiXmlNode::GetDocument(), dqm4hep::TiXmlBase::IsWhiteSpace(), dqm4hep::TiXmlBase::location, dqm4hep::TiXmlAttribute::Parse(), dqm4hep::TiXmlDocument::SetError(), dqm4hep::TiXmlBase::SkipWhiteSpace(), dqm4hep::TiXmlParsingData::Stamp(), standalone, dqm4hep::TiXmlBase::StringEqual(), dqm4hep::TiXmlBase::TIXML_ERROR_PARSING_DECLARATION, dqm4hep::TiXmlAttribute::Value(), and version.
{
  p = SkipWhiteSpace(p, _encoding);
  // Find the beginning, find the end, and look for
  // the stuff in-between.
  TiXmlDocument* document = GetDocument();
  if (!p || !*p || !StringEqual(p, "<?xml", true, _encoding))
  {
    if (document) document->SetError(TIXML_ERROR_PARSING_DECLARATION, 0, 0, _encoding);
    return 0;
  }
  if (data)
  {
    data->Stamp(p, _encoding);
    location = data->Cursor();
  }
  p += 5;
  version = "";
  encoding = "";
  standalone = "";
  while (p && *p)
  {
    if (*p == '>')
    {
      ++p;
      return p;
    }
    p = SkipWhiteSpace(p, _encoding);
    if (StringEqual(p, "version", true, _encoding))
    {
      TiXmlAttribute attrib;
      p = attrib.Parse(p, data, _encoding);
      version = attrib.Value();
    }
    else if (StringEqual(p, "encoding", true, _encoding))
    {
      TiXmlAttribute attrib;
      p = attrib.Parse(p, data, _encoding);
      encoding = attrib.Value();
    }
    else if (StringEqual(p, "standalone", true, _encoding))
    {
      TiXmlAttribute attrib;
      p = attrib.Parse(p, data, _encoding);
      standalone = attrib.Value();
    }
    else
    {
      // Read over whatever it is.
      while(p && *p && *p != '>' && !IsWhiteSpace(*p))
        ++p;
    }
  }
  return 0;
}
void dqm4hep::TiXmlDeclaration::Print (FILE * cfile, int depth, TIXML_STRING * str) const [virtual]
Definition at line 1374 of file tinyxml.cc.
References encoding, standalone, and version.
Referenced by Print(), and dqm4hep::TiXmlPrinter::Visit().
{
  if (cfile) fprintf(cfile, "<?xml ");
  if (str) (*str) += "<?xml ";
  if (!version.empty()) {
    if (cfile) fprintf (cfile, "version=\"%s\" ", version.c_str ());
    if (str) { (*str) += "version=\""; (*str) += version; (*str) += "\" "; }
  }
  if (!encoding.empty()) {
    if (cfile) fprintf (cfile, "encoding=\"%s\" ", encoding.c_str ());
    if (str) { (*str) += "encoding=\""; (*str) += encoding; (*str) += "\" "; }
  }
  if (!standalone.empty()) {
    if (cfile) fprintf (cfile, "standalone=\"%s\" ", standalone.c_str ());
    if (str) { (*str) += "standalone=\""; (*str) += standalone; (*str) += "\" "; }
  }
  if (cfile) fprintf(cfile, "?>");
  if (str) (*str) += "?>";
}
virtual void dqm4hep::TiXmlDeclaration::Print (FILE * cfile, int depth) const [inline], [virtual]
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements dqm4hep::TiXmlBase .
Definition at line 1318 of file tinyxml.h.
References Print().
                                                     {
    Print(cfile, depth, 0);
  }
const char* dqm4hep::TiXmlDeclaration::Standalone () const [inline]
Is this a standalone document?
Definition at line 1312 of file tinyxml.h.
References standalone.
{ return standalone.c_str (); }
virtual void dqm4hep::TiXmlDeclaration::StreamIn (std::istream * in, TIXML_STRING * tag) [protected], [virtual]
Implements dqm4hep::TiXmlNode .
virtual const TiXmlDeclaration* dqm4hep::TiXmlDeclaration::ToDeclaration () const [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1324 of file tinyxml.h.
virtual TiXmlDeclaration* dqm4hep::TiXmlDeclaration::ToDeclaration () [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1325 of file tinyxml.h.
const char* dqm4hep::TiXmlDeclaration::Version () const [inline]
Version. Will return an empty string if none was found.
Definition at line 1308 of file tinyxml.h.
References version.
{ return version.c_str (); }
Member Data Documentation
TIXML_STRING dqm4hep::TiXmlDeclaration::encoding [private]
Definition at line 1341 of file tinyxml.h.
Referenced by CopyTo(), Encoding(), Parse(), Print(), and TiXmlDeclaration().
TIXML_STRING dqm4hep::TiXmlDeclaration::standalone [private]
Definition at line 1342 of file tinyxml.h.
Referenced by CopyTo(), Parse(), Print(), Standalone(), and TiXmlDeclaration().
TIXML_STRING dqm4hep::TiXmlDeclaration::version [private]
Definition at line 1340 of file tinyxml.h.
Referenced by CopyTo(), Parse(), Print(), TiXmlDeclaration(), and Version().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc