dqm4hep::DQMPath Class Reference
DQMPath class.
#include <DQMPath.h>
Public Member Functions
DQMPath ()
Constructor.
DQMPath (const std::string &path)
Constructor with path.
std::vector< std::string > getSplitPath () const
Get the path, split by '/' in a vector.
const std::string & getPath () const
Get the path as string.
bool isValid () const
Whether the path is valid.
bool isRelative () const
Whether the path is relative (does not start with '/')
DQMPath & operator+= (const DQMPath &path)
+= operator
DQMPath & operator= (const DQMPath &path)
Assignment operator with path.
DQMPath & operator= (const std::string &path)
Assignment operator with string.
Static Public Member Functions
static std::string & normalize (std::string &path)
Normalize the path.
Private Attributes
std::string m_path
Friends
DQMPath operator+ (const DQMPath &lhs, const DQMPath &rhs)
std::ostream & operator<< (std::ostream &out, const DQMPath &path)
<< operator
bool operator== (const DQMPath &lhs, const DQMPath &rhs)
== operator
Detailed Description
DQMPath class.
Definition at line 40 of file DQMPath.h.
Constructor & Destructor Documentation
dqm4hep::DQMPath::DQMPath ()
Constructor.
Definition at line 37 of file DQMPath.cc.
{
}
dqm4hep::DQMPath::DQMPath (const std::string & path)
Constructor with path.
Definition at line 44 of file DQMPath.cc.
References m_path, and normalize().
                                      :
    m_path(path)
{
  DQMPath::normalize(m_path);
}
Member Function Documentation
const std::string & dqm4hep::DQMPath::getPath () const
Get the path as string.
Definition at line 65 of file DQMPath.cc.
References m_path.
Referenced by dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::deleteMonitorElement(), and dqm4hep::DQMStorage::rmdir().
{
  return m_path;
}
std::vector< std::string > dqm4hep::DQMPath::getSplitPath () const
Get the path, split by '/' in a vector.
Definition at line 52 of file DQMPath.cc.
References isValid(), m_path, and dqm4hep::DQM4HEP::tokenize().
Referenced by dqm4hep::DQMStorage::cd(), dqm4hep::DQMStorage::findDir(), dqm4hep::DQMStorage::mkdir(), and dqm4hep::operator==().
{
  if(!this->isValid())
    return std::vector<std::string>();
  std::vector<std::string> splitPath;
  DQM4HEP::tokenize(m_path, splitPath, "/");
  return splitPath;
}
bool dqm4hep::DQMPath::isRelative () const
Whether the path is relative (does not start with '/')
Definition at line 85 of file DQMPath.cc.
References isValid(), and m_path.
Referenced by dqm4hep::DQMStorage::cd(), dqm4hep::DQMStorage::findDir(), and dqm4hep::DQMStorage::mkdir().
{
  if(!this->isValid())
    return false;
  if(m_path.empty())
    return true;
  if(m_path.at(0) == '/')
    return false;
  return true;
}
bool dqm4hep::DQMPath::isValid () const
Whether the path is valid.
Definition at line 72 of file DQMPath.cc.
References dqm4hep::DQMCoreTool::containsSpecialCharacters(), and m_path.
Referenced by dqm4hep::DQMStorage::cd(), dqm4hep::DQMStorage::findDir(), getSplitPath(), isRelative(), and dqm4hep::DQMStorage::mkdir().
{
  if(DQMCoreTool::containsSpecialCharacters(m_path))
    return false;
  if(std::string::npos != m_path.find("//"))
    return false;
  return true;
}
std::string & dqm4hep::DQMPath::normalize (std::string & path) [static]
Normalize the path.
Replace all `//` and `/./` by `/` only characters
Definition at line 101 of file DQMPath.cc.
Referenced by DQMPath(), operator+=(), and operator=().
{
  size_t pos = path.find("//");
  while(std::string::npos != pos)
  {
    path.replace(pos, 2, "/");
    pos = path.find("//");
  }
  pos = path.find("/./");
  while(std::string::npos != pos)
  {
    path.replace(pos, 3, "/");
    pos = path.find("/./");
  }
  return path;
}
DQMPath & dqm4hep::DQMPath::operator+= (const DQMPath & path)
+= operator
Definition at line 124 of file DQMPath.cc.
References m_path, and normalize().
{
  if(path.m_path.empty())
    return *this;
  if(m_path.empty())
  {
    m_path = path.m_path;
    return *this;
  }
  size_t pos = std::string::npos;
  pos = m_path.find_last_not_of("/");
  std::string path1 = (pos == std::string::npos) ? m_path : m_path.substr(0, pos+1);
  pos = path.m_path.find_first_not_of("/");
  std::string path2 = (pos == std::string::npos) ? path.m_path : path.m_path.substr(pos);
  m_path = path1 + "/" + path2;
  DQMPath::normalize(m_path);
  return *this;
}
DQMPath & dqm4hep::DQMPath::operator= (const DQMPath & path)
Assignment operator with path.
Definition at line 151 of file DQMPath.cc.
References m_path.
{
  m_path = path.m_path;
  return *this;
}
DQMPath & dqm4hep::DQMPath::operator= (const std::string & path)
Assignment operator with string.
Definition at line 159 of file DQMPath.cc.
References m_path, and normalize().
{
  m_path = path;
  DQMPath::normalize(m_path);
  return *this;
}
Friends And Related Function Documentation
DQMPath operator+ (const DQMPath & lhs, const DQMPath & rhs) [friend]
operator
Definition at line 102 of file DQMPath.h.
{
  DQMPath path(lhs.m_path);
  path += rhs;
  return path;
}
std::ostream& operator<< (std::ostream & out, const DQMPath & path) [friend]
<< operator
Definition at line 112 of file DQMPath.h.
{
  out << path.m_path;
  return out;
}
bool operator== (const DQMPath & lhs, const DQMPath & rhs) [friend]
== operator
Definition at line 121 of file DQMPath.h.
{
  return (lhs.getSplitPath() == rhs.getSplitPath());
}
Member Data Documentation
std::string dqm4hep::DQMPath::m_path [private]
Definition at line 96 of file DQMPath.h.
Referenced by DQMPath(), getPath(), getSplitPath(), isRelative(), isValid(), dqm4hep::operator+(), operator+=(), dqm4hep::operator<<(), and operator=().
The documentation for this class was generated from the following files:
DQMPath.h
DQMPath.cc