dqm4hep::DQM4HEP Class Reference
DQM4HEP class.
#include <DQM4HEP.h>
Public Member Functions
template<>
bool stringToType (const std::string &s, bool &t)
Specialization for booleans.
Static Public Member Functions
template<class T >
static bool stringToType (const std::string &s, T &t)
Convert std::string to a type.
template<class T >
static std::string typeToString (const T &t)
Convert type to std::string.
static void screenSplash ()
Screen splash of DQM4HEP.
static void tokenize (const std::string &inputString, StringVector &tokens, const std::string &delimiter=` `)
Tokenize string with delimiter.
static DQMQuality scaleToQuality (float scale)
Return the quality that corresponds to a value between 0 and 1.
Detailed Description
DQM4HEP class.
Definitions and utilities
Definition at line 357 of file DQM4HEP.h.
Member Function Documentation
DQMQuality dqm4hep::DQM4HEP::scaleToQuality (float scale) [static]
Return the quality that corresponds to a value between 0 and 1.
Definition at line 126 of file DQM4HEP.cc.
Referenced by dqm4hep::DQMMeanWithinExpectedTest::run(), and dqm4hep::DQMChi2FitFunctionTest::run().
{
  if(scale > 0.f && scale < 0.2f)
    return VERY_BAD_QUALITY;
  else if(scale < 0.4f)
    return BAD_QUALITY;
  else if(scale < 0.6f)
    return NORMAL_QUALITY;
  else if(scale < 0.8f)
    return GOOD_QUALITY;
  else if(scale < 1.f)
    return VERY_GOOD_QUALITY;
  else
    return NO_QUALITY;
}
void dqm4hep::DQM4HEP::screenSplash () [static]
Screen splash of DQM4HEP.
Definition at line 87 of file DQM4HEP.cc.
References DQM4HEP_VERSION_STR.
{
  time_t t;
  time(&t);
  char *pTimeStr = new char[256];
  ctime_r(&t, pTimeStr);
  std::cout << "#######################################################" << std::endl;
  std::cout << "#" << std::endl;
  std::cout << "# DQM4HEP" << std::endl;
  std::cout << "# (Data Quality Monitoring For High Energy Physics)" << std::endl;
  std::cout << "#" << std::endl;
  std::cout << "# Version : " << DQM4HEP_VERSION_STR << std::endl;
  std::cout << "# Started at : " << pTimeStr << std::endl;
  std::cout << "# Author : R. Ete" << std::endl;
  std::cout << "# Mail : <rete@ipnl.in2p3.fr> " << std::endl;
  std::cout << "#" << std::endl;
  std::cout << "#######################################################" << std::endl;
  delete [] pTimeStr;
}
template<class T > bool dqm4hep::DQM4HEP::stringToType (const std::string & s, T & t) [inline], [static]
Convert std::string to a type.
Definition at line 388 of file DQM4HEP.h.
Referenced by dqm4hep::DQMMonitorElementManager::bookMonitorElement(), dqm4hep::DQMXmlHelper::getAttribute(), dqm4hep::DQMRun::getParameter(), dqm4hep::DQMDBInterface::query(), dqm4hep::DQMDBInterface::queryVector(), dqm4hep::DQMXmlHelper::read2DVectorOfValues(), dqm4hep::DQMXmlHelper::readParameterValue(), dqm4hep::DQMXmlHelper::readParameterValues(), dqm4hep::DQMXmlHelper::readValue(), and dqm4hep::DQMXmlHelper::readVectorOfValues().
{
  std::istringstream iss(s);
  return !(iss >> t).fail();
}
template<> bool dqm4hep::DQM4HEP::stringToType (const std::string & s, bool & t) [inline]
Specialization for booleans.
Definition at line 412 of file DQM4HEP.h.
{
  if(s == "on" || s == "1" || s == "true")
    t = true;
  else if(s == "off" || s == "0" || s == "false")
    t = false;
  else
    return false;
  return true;
}
void dqm4hep::DQM4HEP::tokenize (const std::string & inputString, StringVector & tokens, const std::string & delimiter = ` `) [static]
Tokenize string with delimiter.
Definition at line 111 of file DQM4HEP.cc.
Referenced by dqm4hep::DQMPath::getSplitPath(), dqm4hep::DQMPluginManager::loadLibraries(), and dqm4hep::DQMLCEventStreamer::serialize().
{
  std::string::size_type lastPos = inputString.find_first_not_of(delimiter, 0);
  std::string::size_type pos = inputString.find_first_of(delimiter, lastPos);
  while ((std::string::npos != pos) || (std::string::npos != lastPos))
  {
    tokens.push_back(inputString.substr(lastPos, pos - lastPos));
    lastPos = inputString.find_first_not_of(delimiter, pos);
    pos = inputString.find_first_of(delimiter, lastPos);
  }
}
template<class T > std::string dqm4hep::DQM4HEP::typeToString (const T & t) [inline], [static]
Convert type to std::string.
Definition at line 397 of file DQM4HEP.h.
Referenced by dqm4hep::DQMChi2FitFunctionTest::run().
{
  std::ostringstream oss;
  if ((oss << t).fail())
    throw;
  return oss.str();
}
The documentation for this class was generated from the following files:
DQM4HEP.h
DQM4HEP.cc