dqm4hep::DQMLCStrVecStreamer Class Reference
DQMLCStrVecStreamer class.
#include <DQMLCEventStreamer.h>
Public Member Functions
StatusCode serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize a LCStrVec.
StatusCode deserialize (EVENT::LCObject *&pLCObject, DQMDataStream *const pDataStream)
Deserialize a LCStrVec.
Detailed Description
DQMLCStrVecStreamer class.
Definition at line 277 of file DQMLCEventStreamer.h.
Member Function Documentation
StatusCode dqm4hep::DQMLCStrVecStreamer::deserialize (EVENT::LCObject *& pLCObject, DQMDataStream *const pDataStream)
Deserialize a LCStrVec.
The object is allocated in this function
Definition at line 1333 of file DQMLCEventStreamer.cc.
References dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMDataStream::read(), and THROW_RESULT_IF.
{
  pLCObject = 0;
  EVENT::LCStrVec *pStrVec = new EVENT::LCStrVec();
  try
  {
    dqm_uint nVals = 0;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nVals));
    for(dqm_uint i=0 ; i<nVals ; i++)
    {
      std::string value;
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(value));
      pStrVec->push_back(value);
    }
  }
  catch(StatusCodeException &exception)
  {
    delete pStrVec;
    pStrVec = 0;
    pLCObject = 0;
    return exception.getStatusCode();
  }
  pLCObject = pStrVec;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMLCStrVecStreamer::serialize (const EVENT::LCObject *const pLCObject, DQMDataStream *const pDataStream)
Serialize a LCStrVec.
Definition at line 1312 of file DQMLCEventStreamer.cc.
References RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
{
  const EVENT::LCStrVec *const pStrVec = dynamic_cast<const EVENT::LCStrVec *const>(pLCObject);
  if(NULL == pStrVec)
    return STATUS_CODE_INVALID_PARAMETER;
  dqm_uint nVals = pStrVec->size();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(nVals));
  for(dqm_uint i=0 ; i<nVals ; i++)
  {
    std::string value = pStrVec->at(i);
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(value));
  }
  return STATUS_CODE_SUCCESS;
}
The documentation for this class was generated from the following files:
DQMLCEventStreamer.h
DQMLCEventStreamer.cc