dqm4hep::DQMPluginManager Class Reference
DQMPluginManager class.
#include <DQMPluginManager.h>
Public Member Functions
StatusCode loadLibraries ()
Load shared libraries from the environment variable DQM4HEP_PLUGIN_DLL.
StatusCode loadLibraries (const StringVector &libraryNameList)
Load the shared libraries.
StatusCode loadLibrary (const std::string &libraryName)
Load the shared library.
DQMPlugin * getPlugin (const std::string &pluginName) const
Get the plug-in by name.
template<typename T >
T * createPluginClass (const std::string &pluginName) const
Get the plug-in clone.
bool isPluginRegistered (const std::string &pluginName) const
Whether the plug-in is registered within the plug-in manager.
StringVector getPluginNameList () const
Get the plug-in name list.
Private Types
typedef std::map< const
*
std::string, DQMPlugin * > DQMPluginMap
Private Member Functions
DQMPluginManager ()
Constructor.
~DQMPluginManager ()
Destructor.
StatusCode registerPlugin (DQMPlugin *pPlugin)
Register the plug-in.
Private Attributes
DQMPluginMap m_pluginMap
Friends
class DQMSingleton< DQMPluginManager >
class DQMPlugin
Additional Inherited Members
Detailed Description
DQMPluginManager class.
Responsible for loading shared libraries that contains DQMPlugin instances
Definition at line 45 of file DQMPluginManager.h.
Member Typedef Documentation
typedef std::map<const std::string, DQMPlugin*> dqm4hep::DQMPluginManager::DQMPluginMap [private]
Definition at line 50 of file DQMPluginManager.h.
Constructor & Destructor Documentation
dqm4hep::DQMPluginManager::DQMPluginManager () [private]
Constructor.
Definition at line 38 of file DQMPluginManager.cc.
{
  /* nop */
}
dqm4hep::DQMPluginManager::~DQMPluginManager () [private]
Destructor.
Definition at line 45 of file DQMPluginManager.cc.
References m_pluginMap.
{
  for(DQMPluginMap::const_iterator iter = m_pluginMap.begin(), endIter =
      m_pluginMap.end() ;
      endIter != iter ; ++iter)
  {
    delete iter->second;
  }
  m_pluginMap.clear();
}
Member Function Documentation
template<typename T > T * dqm4hep::DQMPluginManager::createPluginClass (const std::string & pluginName) const [inline]
Get the plug-in clone.
A new plug-in instance is allocated and returned to the user. Ownership of the plug-in transfered to the caller.
Definition at line 104 of file DQMPluginManager.h.
References dqm4hep::DQMPlugin::create(), and getPlugin().
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureCycle(), dqm4hep::DQMAnalysisModuleApplication::configureModule(), dqm4hep::DQMAnalysisModuleApplication::configureNetwork(), dqm4hep::DQMStandaloneModuleApplication::readSettings(), and dqm4hep::DQMDimEventClient::readSettings().
{
  DQMPlugin *pPlugin = this->getPlugin(pluginName);
  if(!pPlugin)
    return 0;
  DQMPlugin *pClass = pPlugin->create();
  if(NULL == pClass)
    return 0;
  return dynamic_cast<T *>(pClass);
}
DQMPlugin * dqm4hep::DQMPluginManager::getPlugin (const std::string & pluginName) const
Get the plug-in by name.
Definition at line 133 of file DQMPluginManager.cc.
References isPluginRegistered(), and m_pluginMap.
Referenced by createPluginClass().
{
  if(! isPluginRegistered(pluginName))
    return 0;
  return m_pluginMap.find(pluginName)->second;
}
StringVector dqm4hep::DQMPluginManager::getPluginNameList () const
Get the plug-in name list.
Definition at line 150 of file DQMPluginManager.cc.
References m_pluginMap.
{
  StringVector pluginNameList;
  for(DQMPluginMap::const_iterator iter = m_pluginMap.begin(), endIter =
      m_pluginMap.end() ;
      endIter != iter ; ++iter)
  {
    pluginNameList.push_back(iter->first);
  }
  return pluginNameList;
}
bool dqm4hep::DQMPluginManager::isPluginRegistered (const std::string & pluginName) const
Whether the plug-in is registered within the plug-in manager.
Definition at line 143 of file DQMPluginManager.cc.
References m_pluginMap.
Referenced by getPlugin(), and registerPlugin().
{
  return (m_pluginMap.find(pluginName) != m_pluginMap.end());
}
StatusCode dqm4hep::DQMPluginManager::loadLibraries ()
Load shared libraries from the environment variable DQM4HEP_PLUGIN_DLL.
Definition at line 58 of file DQMPluginManager.cc.
References dqm4hep::ERROR, and dqm4hep::DQM4HEP::tokenize().
{
  // get the environment plug-in dll variable
  char *pPluginDllEnv = getenv("DQM4HEP_PLUGIN_DLL");
  if(pPluginDllEnv == 0)
  {
    streamlog_out(ERROR) << "Environment variable DQM4HEP_PLUGIN_DLL not found ! \n"
        "Set it before loading shared libraries. \n"
        "Example : export DQM4HEP_PLUGIN_DLL=libPlugin1.so:libPlugin2.so" << std::endl;
    return STATUS_CODE_NOT_INITIALIZED;
  }
  // split the string into a list
  std::string libraryConcatenateList(pPluginDllEnv);
  StringVector libraryList;
  DQM4HEP::tokenize(libraryConcatenateList, libraryList, ":");
  // load the shared libraries
  return this->loadLibraries(libraryList);
}
StatusCode dqm4hep::DQMPluginManager::loadLibraries (const StringVector & libraryNameList)
Load the shared libraries.
Definition at line 84 of file DQMPluginManager.cc.
References loadLibrary(), and RETURN_RESULT_IF.
{
  for(StringVector::const_iterator iter = libraryNameList.begin(), endIter = libraryNameList.end() ;
      endIter != iter ; ++iter)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->loadLibrary(*iter));
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMPluginManager::loadLibrary (const std::string & libraryName)
Load the shared library.
Definition at line 97 of file DQMPluginManager.cc.
Referenced by loadLibraries().
{
  size_t idx = libraryName.find_last_of("/");
  // the library basename, i.e. /path/to/libBlah.so --> libBlah.so
  std::string libBaseName(libraryName.substr(idx + 1));
  char *real_path = realpath(libraryName.c_str(), NULL);
  if(NULL != real_path)
  {
    std::cout << "<!-- Loading shared library : " << real_path << " ("<< libBaseName << ")-->" << std::endl
       ;
    // use real_path
    free(real_path);
  }
  else
  {
    std::cout << "<!-- Loading shared library : " << libraryName << " ("<< libBaseName << ")-->" <<
      std::endl ;
  }
  void *pLibPointer = dlopen(libraryName.c_str(), RTLD_LAZY | RTLD_GLOBAL);
  if(pLibPointer == 0)
  {
    std::cout << std::endl << "<!-- ERROR loading shared library : " << libraryName << std::endl
                        << " -> " << dlerror() << " -->" << std::endl << std::endl;
    return STATUS_CODE_FAILURE;
  }
  else
    return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMPluginManager::registerPlugin (DQMPlugin * pPlugin) [private]
Register the plug-in.
Only available by plug-ins themselves
Definition at line 165 of file DQMPluginManager.cc.
References dqm4hep::DQMPlugin::getPluginName(), isPluginRegistered(), and m_pluginMap.
{
  // null ptr case
  if(NULL == pPlugin)
    return STATUS_CODE_INVALID_PTR;
  // check if the plug is already registered
  if(isPluginRegistered(pPlugin->getPluginName()))
  {
    delete pPlugin;
    pPlugin = NULL;
    return STATUS_CODE_ALREADY_PRESENT;
  }
  // try to register it
  if(! m_pluginMap.insert(DQMPluginMap::value_type(pPlugin->getPluginName(), pPlugin)).second)
  {
    delete pPlugin;
    pPlugin = NULL;
    return STATUS_CODE_FAILURE;
  }
  return STATUS_CODE_SUCCESS;
}
Friends And Related Function Documentation
friend class DQMPlugin [friend]
Definition at line 48 of file DQMPluginManager.h.
friend class DQMSingleton< DQMPluginManager > [friend]
Definition at line 47 of file DQMPluginManager.h.
Member Data Documentation
DQMPluginMap dqm4hep::DQMPluginManager::m_pluginMap [private]
Definition at line 97 of file DQMPluginManager.h.
Referenced by getPlugin(), getPluginNameList(), isPluginRegistered(), registerPlugin(), and ~DQMPluginManager().
The documentation for this class was generated from the following files:
DQMPluginManager.h
DQMPluginManager.cc