dqm4hep::DQMModuleApi Class Reference
DQMModuleApi class.
#include <DQMModuleApi.h>
Static Public Member Functions
static void cd (const DQMModule *const pModule)
Go back to root directory.
static StatusCode cd (const DQMModule *const pModule, const std::string &dirName)
Go to directory 'dirName'.
static StatusCode mkdir (const DQMModule *const pModule, const std::string &dirName)
Create the directory 'dirName'.
static void ls (const DQMModule *const pModule, bool recursive=false)
List the current directory content.
static const std::string & pwd (const DQMModule *const pModule)
Get the current directory name.
static StatusCode goUp (const DQMModule *const pModule)
Navigate backward in the directory structure.
static StatusCode rmdir (const DQMModule *const pModule, const std::string &dirName)
Remove the directory 'dirName'.
static StatusCode bookRealHistogram1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D float histogram.
static StatusCode bookIntHistogram1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D integer histogram.
static StatusCode bookCharHistogram1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D char histogram.
static StatusCode bookShortHistogram1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D short histogram.
static StatusCode bookRealHistogram2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D float histogram.
static StatusCode bookIntHistogram2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D integer histogram.
static StatusCode bookCharHistogram2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D char histogram.
static StatusCode bookShortHistogram2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D short histogram.
static StatusCode bookProfile1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, float yMin, float yMax)
Book a 1D profile.
static StatusCode bookProfile2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax)
Book a 2D profile.
static StatusCode bookInt (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const int &value)
Book an integer scalar element.
static StatusCode bookFloat (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const float &value)
Book a float scalar element.
static StatusCode bookShort (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const short &value)
Book a short scalar element.
static StatusCode bookString (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &value)
Book a std::string scalar element.
static StatusCode bookObject (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, TObject *pROOTObject)
Book a generic TObject.
static StatusCode bookRealHistogram1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D float histogram.
static StatusCode bookIntHistogram1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D integer histogram.
static StatusCode bookCharHistogram1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D char histogram.
static StatusCode bookShortHistogram1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D short histogram.
static StatusCode bookRealHistogram2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D float histogram.
static StatusCode bookIntHistogram2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D integer histogram.
static StatusCode bookCharHistogram2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D char histogram.
static StatusCode bookShortHistogram2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D short histogram.
static StatusCode bookProfile1D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, float yMin, float yMax)
Book a 1D profile.
static StatusCode bookProfile2D (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax)
Book a 2D profile.
static StatusCode bookInt (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const int &value)
Book an integer scalar element.
static StatusCode bookFloat (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const float &value)
Book a float scalar element.
static StatusCode bookShort (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const short &value)
Book a short scalar element.
static StatusCode bookString (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &value)
Book a std::string scalar element.
static StatusCode bookObject (const DQMModule *const pModule, DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, TObject *pROOTObject)
Book a generic TObject.
static StatusCode getAllMonitorElements (const DQMModule *const pModule, std::vector< DQMMonitorElement * > &monitorElementList)
Get all the monitor elements already booked by this module in all the directories.
static StatusCode getMonitorElement (const DQMModule *const pModule, const std::string &monitorElementName, DQMMonitorElement *&pMonitorElement)
Get the monitor element in the current directory (result by ptr reference)
static StatusCode getMonitorElement (const DQMModule *const pModule, const std::string &dirName, const std::string &monitorElementName, DQMMonitorElement *&pMonitorElement)
Get the monitor element in the given directory (result by ptr reference)
static DQMMonitorElement * getMonitorElement (const DQMModule *const pModule, const std::string &monitorElementName)
Get the monitor element in the current directory.
static DQMMonitorElement * getMonitorElement (const DQMModule *const pModule, const std::string &dirName, const std::string &monitorElementName)
Get the monitor element in the given directory.
static StatusCode deleteMonitorElement (const DQMModule *const pModule, DQMMonitorElement *pMonitorElement)
Delete the monitor element (by element ptr)
static StatusCode registerQualityTestFactory (const DQMModule *const pModule, const std::string &qualityTestFactoryName, const DQMQualityTestFactory *const pQualityTestFactory)
Delete the monitor element (by element name)
static StatusCode createQualityTest (const DQMModule *const pModule, TiXmlElement *const pXmlElement)
Create a quality test from the xml element.
static StatusCode addQualityTest (const DQMModule *const pModule, DQMMonitorElement *pMonitorElement, const std::string &qualityTestName)
Add a quality test to a given monitor element.
static StatusCode runQualityTests (const DQMModule *const pModule, DQMMonitorElement *pMonitorElement)
Run all the quality test attached to this monitor element.
static StatusCode runQualityTest (const DQMModule *const pModule, DQMMonitorElement *pMonitorElement, const std::string &qualityTestName)
Run a specific quality test attached to this monitor element.
static StatusCode runQualityTests (const DQMModule *const pModule)
Run all the quality test of all the monitor elements of this module.
static StatusCode resetMonitorElements (const DQMModule *const pModule, DQMResetPolicy policy)
Reset all the monitor elements that have the given reset policy.
static StatusCode resetMonitorElements (const DQMModule *const pModule)
Reset all the monitor elements of this module.
Static Private Member Functions
static StatusCode bookMonitorElement (const DQMModule *const pModule, const TiXmlElement *const pXmlElement, DQMMonitorElement *&pMonitorElement)
Archive the current state of this module.
Friends
class DQMXmlHelper
Detailed Description
DQMModuleApi class.
Responsible for direct operation on module application and modules such as monitor element booking and directory navigation. Monitor element booking should be done via a DQMModule.
Example :
DQMMonitorElement *pMyRealHistogram1DElement = NULL;
DQMModuleApi::bookRealHistogram1D(this, pMyRealHistogram1DElement, "MyHisto", "My histo title", 10, 1, 10);
Definition at line 73 of file DQMModuleApi.h.
Member Function Documentation
StatusCode dqm4hep::DQMModuleApi::addQualityTest (const DQMModule *const pModule, DQMMonitorElement * pMonitorElement, const std::string & qualityTestName) [static]
Add a quality test to a given monitor element.
The quality test must have been registered in the framework before calling this method.
Definition at line 509 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementManager::addQualityTest(), dqm4hep::DQMModule::getModuleApplication(), and dqm4hep::DQMModuleApplication::getMonitorElementManager().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->addQualityTest(pMonitorElement,
      qualityTestName);
}
StatusCode dqm4hep::DQMModuleApi::bookCharHistogram1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) [static]
Book a 1D char histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 113 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookCharHistogram1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookCharHistogram1D(pMonitorElement, name, title, pModule->getName(), nBins, minimum, maximum));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookCharHistogram1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) [static]
Book a 1D char histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 278 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookCharHistogram1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookCharHistogram1D(pMonitorElement, dirName, name, title, pModule->getName(), nBins, minimum, maximum));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookCharHistogram2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) [static]
Book a 2D char histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 157 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookCharHistogram2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookCharHistogram2D(pMonitorElement, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins, yMin, yMax))
      ;
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookCharHistogram2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) [static]
Book a 2D char histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 322 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookCharHistogram2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookCharHistogram2D(pMonitorElement, dirName, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins,
      yMin, yMax));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookFloat (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const float & value) [static]
Book a float scalar element.
The scalar is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 215 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookFloat(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookFloat(pMonitorElement, name, title, pModule->getName(), value));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookFloat (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const float & value) [static]
Book a float scalar element.
The scalar is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 380 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookFloat(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookFloat(pMonitorElement, dirName, name, title, pModule->getName(), value));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookInt (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const int & value) [static]
Book an integer scalar element.
The scalar is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 205 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookInt(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookInt(pMonitorElement, name, title, pModule->getName(), value));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookInt (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const int & value) [static]
Book an integer scalar element.
The scalar is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 370 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookInt(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookInt(pMonitorElement, dirName, name, title, pModule->getName(), value));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookIntHistogram1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) [static]
Book a 1D integer histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 103 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookIntHistogram1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookIntHistogram1D(pMonitorElement, name, title, pModule->getName(), nBins, minimum, maximum));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookIntHistogram1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) [static]
Book a 1D integer histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 268 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookIntHistogram1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookIntHistogram1D(pMonitorElement, dirName, name, title, pModule->getName(), nBins, minimum, maximum));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookIntHistogram2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) [static]
Book a 2D integer histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 145 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookIntHistogram2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookIntHistogram2D(pMonitorElement, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins, yMin, yMax));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookIntHistogram2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) [static]
Book a 2D integer histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 310 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookIntHistogram2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookIntHistogram2D(pMonitorElement, dirName, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins, yMin
      , yMax));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookMonitorElement (const DQMModule *const pModule, const TiXmlElement *const pXmlElement, DQMMonitorElement *& pMonitorElement) [static], [private]
Archive the current state of this module.
Simply write the directory structure with the monitor elements in a root fileBook a monitor element from the xml element
Definition at line 537 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookMonitorElement(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMXmlHelper::bookMonitorElement().
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookMonitorElement(pXmlElement, pModule->getName(), pMonitorElement));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookObject (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, TObject * pROOTObject) [static]
Book a generic TObject.
The TObject must be valid and must be a built-in ROOT object or a user defined class inheriting from TObject and providing a dictionary. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 246 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookObject(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookObject(pMonitorElement, name, title, pModule->getName(), pROOTObject));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookObject (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, TObject * pROOTObject) [static]
Book a generic TObject.
The TObject must be valid and must be a built-in ROOT object or a user defined class inheriting from TObject and providing a dictionary. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 410 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookObject(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookObject(pMonitorElement, dirName, name, title, pModule->getName(), pROOTObject));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookProfile1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, float yMin, float yMax) [static]
Book a 1D profile.
The profile is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 181 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookProfile1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookProfile1D(pMonitorElement, name, title, pModule->getName(), nXBins, xMin, xMax, yMin, yMax));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookProfile1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, float yMin, float yMax) [static]
Book a 1D profile.
The profile is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 346 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookProfile1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookProfile1D(pMonitorElement, dirName, name, title, pModule->getName(), nXBins, xMin, xMax, yMin, yMax));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookProfile2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax) [static]
Book a 2D profile.
The profile is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 192 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookProfile2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookProfile2D(pMonitorElement, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins, yMin, yMax, zMin,
      zMax));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookProfile2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax) [static]
Book a 2D profile.
The profile is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 357 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookProfile2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookProfile2D(pMonitorElement, dirName, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins, yMin,
      yMax, zMin, zMax));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookRealHistogram1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) [static]
Book a 1D float histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 93 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookRealHistogram1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookRealHistogram1D(pMonitorElement, name, title, pModule->getName(), nBins, minimum, maximum));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookRealHistogram1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) [static]
Book a 1D float histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 258 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookRealHistogram1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookRealHistogram1D(pMonitorElement, dirName, name, title, pModule->getName(), nBins, minimum, maximum));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookRealHistogram2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) [static]
Book a 2D float histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 133 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookRealHistogram2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookRealHistogram2D(pMonitorElement, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins, yMin, yMax))
      ;
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookRealHistogram2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) [static]
Book a 2D float histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 298 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookRealHistogram2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookRealHistogram2D(pMonitorElement, dirName, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins,
      yMin, yMax));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookShort (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const short & value) [static]
Book a short scalar element.
The scalar is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 225 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookShort(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookShort(pMonitorElement, name, title, pModule->getName(), value));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookShort (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const short & value) [static]
Book a short scalar element.
The scalar is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 390 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookShort(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookShort(pMonitorElement, dirName, name, title, pModule->getName(), value));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookShortHistogram1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) [static]
Book a 1D short histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 123 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookShortHistogram1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookShortHistogram1D(pMonitorElement, name, title, pModule->getName(), nBins, minimum, maximum));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookShortHistogram1D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) [static]
Book a 1D short histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 288 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookShortHistogram1D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookShortHistogram1D(pMonitorElement, dirName, name, title, pModule->getName(), nBins, minimum, maximum));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookShortHistogram2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) [static]
Book a 2D short histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 169 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookShortHistogram2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookShortHistogram2D(pMonitorElement, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins, yMin, yMax)
      );
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookShortHistogram2D (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) [static]
Book a 2D short histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 334 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookShortHistogram2D(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookShortHistogram2D(pMonitorElement, dirName, name, title, pModule->getName(), nXBins, xMin, xMax, nYBins,
      yMin, yMax));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookString (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & value) [static]
Book a std::string scalar element.
The scalar is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 235 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookString(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookString(pMonitorElement, name, title, pModule->getName(), value));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::bookString (const DQMModule *const pModule, DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & value) [static]
Book a std::string scalar element.
The scalar is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 400 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMonitorElementManager::bookString(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      bookString(pMonitorElement, dirName, name, title, pModule->getName(), value));
  pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMModuleApi::cd (const DQMModule *const pModule) [static]
Go back to root directory.
Definition at line 43 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementManager::cd(), dqm4hep::DQMModule::getModuleApplication(), and dqm4hep::DQMModuleApplication::getMonitorElementManager().
{
  pModule->getModuleApplication()->getMonitorElementManager()->cd();
}
StatusCode dqm4hep::DQMModuleApi::cd (const DQMModule *const pModule, const std::string & dirName) [static]
Go to directory 'dirName'.
Definition at line 50 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementManager::cd(), dqm4hep::DQMModule::getModuleApplication(), and dqm4hep::DQMModuleApplication::getMonitorElementManager().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->cd(dirName);
}
StatusCode dqm4hep::DQMModuleApi::createQualityTest (const DQMModule *const pModule, TiXmlElement *const pXmlElement) [static]
Create a quality test from the xml element.
The xml element must contain the attribute 'type' and 'name'
Definition at line 502 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementManager::createQualityTest(), dqm4hep::DQMModule::getModuleApplication(), and dqm4hep::DQMModuleApplication::getMonitorElementManager().
Referenced by dqm4hep::DQMXmlHelper::createQualityTest().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->createQualityTest(pXmlElement);
}
StatusCode dqm4hep::DQMModuleApi::deleteMonitorElement (const DQMModule *const pModule, DQMMonitorElement * pMonitorElement) [static]
Delete the monitor element (by element ptr)
Definition at line 457 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementManager::deleteMonitorElement(), dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMMonitorElement::getName(), dqm4hep::DQMMonitorElement::getPath(), dqm4hep::DQMMonitorElementSender::removeAvailableMonitorElement(), and RETURN_RESULT_IF.
{
  std::string fullName = (pMonitorElement->getPath() + pMonitorElement->getName()).getPath();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->
      deleteMonitorElement(pMonitorElement));
  pModule->getModuleApplication()->getMonitorElementSender()->removeAvailableMonitorElement(fullName);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMModuleApi::getAllMonitorElements (const DQMModule *const pModule, std::vector< DQMMonitorElement * > & monitorElementList) [static]
Get all the monitor elements already booked by this module in all the directories.
Definition at line 421 of file DQMModuleApi.cc.
References dqm4hep::DQMMonitorElementManager::getAllMonitorElements(), dqm4hep::DQMModule::getModuleApplication(), and dqm4hep::DQMModuleApplication::getMonitorElementManager().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->getAllMonitorElements(
      monitorElementList);
}
StatusCode dqm4hep::DQMModuleApi::getMonitorElement (const DQMModule *const pModule, const std::string & monitorElementName, DQMMonitorElement *& pMonitorElement) [static]
Get the monitor element in the current directory (result by ptr reference)
Definition at line 428 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMMonitorElementManager::getMonitorElement(), and dqm4hep::DQMModuleApplication::getMonitorElementManager().
Referenced by dqm4hep::DQMMonitorElementSender::sendMonitorElements().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->getMonitorElement(monitorElementName,
       pMonitorElement);
}
StatusCode dqm4hep::DQMModuleApi::getMonitorElement (const DQMModule *const pModule, const std::string & dirName, const std::string & monitorElementName, DQMMonitorElement *& pMonitorElement) [static]
Get the monitor element in the given directory (result by ptr reference)
Definition at line 435 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMMonitorElementManager::getMonitorElement(), and dqm4hep::DQMModuleApplication::getMonitorElementManager().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->getMonitorElement(dirName,
      monitorElementName, pMonitorElement);
}
DQMMonitorElement * dqm4hep::DQMModuleApi::getMonitorElement (const DQMModule *const pModule, const std::string & monitorElementName) [static]
Get the monitor element in the current directory.
The element is directly returned without any ptr check
Definition at line 442 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMMonitorElementManager::getMonitorElement(), and dqm4hep::DQMModuleApplication::getMonitorElementManager().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->getMonitorElement(monitorElementName)
      ;
}
DQMMonitorElement * dqm4hep::DQMModuleApi::getMonitorElement (const DQMModule *const pModule, const std::string & dirName, const std::string & monitorElementName) [static]
Get the monitor element in the given directory.
The element is directly returned without any ptr check
Definition at line 449 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMMonitorElementManager::getMonitorElement(), and dqm4hep::DQMModuleApplication::getMonitorElementManager().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->getMonitorElement(dirName,
      monitorElementName);
}
StatusCode dqm4hep::DQMModuleApi::goUp (const DQMModule *const pModule) [static]
Navigate backward in the directory structure.
Definition at line 78 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::goUp().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->goUp();
}
void dqm4hep::DQMModuleApi::ls (const DQMModule *const pModule, bool recursive = false) [static]
List the current directory content.
Definition at line 64 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::ls().
{
  pModule->getModuleApplication()->getMonitorElementManager()->ls(recursive);
}
StatusCode dqm4hep::DQMModuleApi::mkdir (const DQMModule *const pModule, const std::string & dirName) [static]
Create the directory 'dirName'.
Definition at line 57 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::mkdir().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->mkdir(dirName);
}
const std::string & dqm4hep::DQMModuleApi::pwd (const DQMModule *const pModule) [static]
Get the current directory name.
Definition at line 71 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::pwd().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->pwd();
}
StatusCode dqm4hep::DQMModuleApi::registerQualityTestFactory (const DQMModule *const pModule, const std::string & qualityTestFactoryName, const DQMQualityTestFactory *const pQualityTestFactory) [static]
Delete the monitor element (by element name)
Register a new quality test factory.
Must be called while reading module settings and before calling DQMModuleApi::createQualityTest()
Definition at line 495 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::registerQualityTestFactory().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->registerQualityTestFactory(
      qualityTestFactoryName, pQualityTestFactory);
}
StatusCode dqm4hep::DQMModuleApi::resetMonitorElements (const DQMModule *const pModule, DQMResetPolicy policy) [static]
Reset all the monitor elements that have the given reset policy.
Definition at line 480 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::resetMonitorElements().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->resetMonitorElements(policy);
}
StatusCode dqm4hep::DQMModuleApi::resetMonitorElements (const DQMModule *const pModule) [static]
Reset all the monitor elements of this module.
Definition at line 487 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::resetMonitorElements().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->resetMonitorElements();
}
StatusCode dqm4hep::DQMModuleApi::rmdir (const DQMModule *const pModule, const std::string & dirName) [static]
Remove the directory 'dirName'.
Definition at line 85 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::rmdir().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->rmdir(dirName);
}
StatusCode dqm4hep::DQMModuleApi::runQualityTest (const DQMModule *const pModule, DQMMonitorElement * pMonitorElement, const std::string & qualityTestName) [static]
Run a specific quality test attached to this monitor element.
Definition at line 523 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::runQualityTest().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->runQualityTest(pMonitorElement,
      qualityTestName);
}
StatusCode dqm4hep::DQMModuleApi::runQualityTests (const DQMModule *const pModule, DQMMonitorElement * pMonitorElement) [static]
Run all the quality test attached to this monitor element.
Definition at line 516 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::runQualityTests().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->runQualityTests(pMonitorElement);
}
StatusCode dqm4hep::DQMModuleApi::runQualityTests (const DQMModule *const pModule) [static]
Run all the quality test of all the monitor elements of this module.
Definition at line 530 of file DQMModuleApi.cc.
References dqm4hep::DQMModule::getModuleApplication(), dqm4hep::DQMModuleApplication::getMonitorElementManager(), and dqm4hep::DQMMonitorElementManager::runQualityTests().
{
  return pModule->getModuleApplication()->getMonitorElementManager()->runQualityTests();
}
Friends And Related Function Documentation
friend class DQMXmlHelper [friend]
Definition at line 412 of file DQMModuleApi.h.
The documentation for this class was generated from the following files:
DQMModuleApi.h
DQMModuleApi.cc