dqm4hep::DQMMonitorElementManager Class Reference
DQMMonitorElementManager class.
#include <DQMMonitorElementManager.h>
Public Member Functions
DQMMonitorElementManager ()
Constructor.
~DQMMonitorElementManager ()
Dtor.
void cd ()
Read the settings for quality tests and initialized them.
StatusCode cd (const std::string &dirName)
Go to directory 'dirName'.
StatusCode mkdir (const std::string &dirName)
Create the directory 'dirName'.
void ls (bool recursive=false)
List the current directory content.
const std::string & pwd ()
Get the current directory name.
StatusCode goUp ()
Navigate backward in the directory structure.
StatusCode rmdir (const std::string &dirName)
Remove the directory 'dirName'.
const std::string & getCurrentDirectoryName () const
Get the current directory name (always defined)
DQMPath getCurrentDirectoryFullPathName () const
Get the current directory full path name (always defined)
StatusCode getFullPathName (const std::string &subDirName, DQMPath &fullPathName) const
Get the full path name of the sub directory.
StatusCode bookRealHistogram1D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nBins, float minimum, float maximum)
Book a 1D float histogram.
StatusCode bookIntHistogram1D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nBins, float minimum, float maximum)
Book a 1D integer histogram.
StatusCode bookCharHistogram1D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nBins, float minimum, float maximum)
Book a 1D char histogram.
StatusCode bookShortHistogram1D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nBins, float minimum, float maximum)
Book a 1D short histogram.
StatusCode bookRealHistogram2D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D float histogram.
StatusCode bookIntHistogram2D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D integer histogram.
StatusCode bookCharHistogram2D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D char histogram.
StatusCode bookShortHistogram2D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D short histogram.
StatusCode bookProfile1D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, float yMin, float yMax)
Book a 1D profile.
StatusCode bookProfile2D (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax)
Book a 2D profile.
StatusCode bookInt (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, const int &value)
Book an integer scalar element.
StatusCode bookFloat (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, const float &value)
Book a float scalar element.
StatusCode bookShort (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, const short &value)
Book a short scalar element.
StatusCode bookString (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, const std::string &value)
Book a std::string scalar element.
StatusCode bookObject (DQMMonitorElement *&pMonitorElement, const std::string &name, const std::string &title, const std::string &moduleName, TObject *pROOTObject)
Book a generic TObject.
StatusCode bookRealHistogram1D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nBins, float minimum, float maximum)
Book a 1D float histogram.
StatusCode bookIntHistogram1D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nBins, float minimum, float maximum)
Book a 1D integer histogram.
StatusCode bookCharHistogram1D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nBins, float minimum, float maximum)
Book a 1D char histogram.
StatusCode bookShortHistogram1D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nBins, float minimum, float maximum)
Book a 1D short histogram.
StatusCode bookRealHistogram2D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D float histogram.
StatusCode bookIntHistogram2D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D integer histogram.
StatusCode bookCharHistogram2D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D char histogram.
StatusCode bookShortHistogram2D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D short histogram.
StatusCode bookProfile1D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, float yMin, float yMax)
Book a 1D profile.
StatusCode bookProfile2D (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax)
Book a 2D profile.
StatusCode bookInt (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, const int &value)
Book an integer scalar element.
StatusCode bookFloat (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, const float &value)
Book a float scalar element.
StatusCode bookShort (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, const short &value)
Book a short scalar element.
StatusCode bookString (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, const std::string &value)
Book a std::string scalar element.
StatusCode bookObject (DQMMonitorElement *&pMonitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &moduleName, TObject *pROOTObject)
Book a generic TObject.
StatusCode bookMonitorElement (const TiXmlElement *const pXmlElement, const std::string &moduleName, DQMMonitorElement *&pMonitorElement)
Book a monitor element from the xml element.
StatusCode getAllMonitorElements (std::vector< DQMMonitorElement * > &monitorElementList) const
Get all the monitor elements already booked by this module in all the directories.
StatusCode getMonitorElement (const std::string &monitorElementName, DQMMonitorElement *&pMonitorElement) const
Get the monitor element in the current directory (result by ptr reference)
StatusCode getMonitorElement (const std::string &dirName, const std::string &monitorElementName, DQMMonitorElement *&pMonitorElement) const
Get the monitor element in the given directory (result by ptr reference)
DQMMonitorElement * getMonitorElement (const std::string &monitorElementName) const
Get the monitor element in the current directory.
DQMMonitorElement * getMonitorElement (const std::string &dirName, const std::string &monitorElementName) const
Get the monitor element in the given directory.
StatusCode deleteMonitorElement (DQMMonitorElement *pMonitorElement)
Delete the monitor element (by element ptr)
StatusCode deleteMonitorElement (const std::string &dirName, const std::string &monitorElement)
Delete the monitor element (by element name)
StatusCode registerQualityTestFactory (const std::string &qualityTestType, const DQMQualityTestFactory *const pQualityTestFactory)
Register a new quality test.
StatusCode createQualityTest (TiXmlElement *const pXmlElement)
Create a quality test from the xml element.
StatusCode addQualityTest (DQMMonitorElement *pMonitorElement, const std::string &qualityTestName) const
Add a quality test to a given monitor element.
StatusCode removeQualityTest (DQMMonitorElement *pMonitorElement, const std::string &qualityTestName)
Remove a specific quality test attached to this monitor element.
StatusCode removeQualityTests (DQMMonitorElement *pMonitorElement)
Remove all quality tests attached to this monitor element.
StatusCode runQualityTests (DQMMonitorElement *pMonitorElement)
Run all the quality test attached to this monitor element.
StatusCode runQualityTest (DQMMonitorElement *pMonitorElement, const std::string &qualityTestName)
Run a specific quality test attached to this monitor element.
StatusCode runQualityTests ()
Run all the quality test of all the monitor elements.
StatusCode getQualityTestResults (DQMQualityTestResultMap &results) const
Get all the quality test results.
StatusCode resetMonitorElements (DQMResetPolicy policy) const
Reset all the monitor elements that have the given reset policy.
StatusCode resetMonitorElements () const
Reset all the monitor elements of this module.
StatusCode getMonitorElementListToPublish (DQMMonitorElementList &monitorElementList) const
Get the monitor element list for which the flag `setToPublish` is true.
Private Types
typedef std::map< const
*
std::string, DQMQualityTest * > DQMQualityTestMap
typedef std::map< const
*
std::string, const
*
DQMQualityTestFactory * > DQMQualityTestFactoryMap
Private Member Functions
StatusCode getQualityTest (const std::string &qualityTestName, DQMQualityTest *&pQualityTest) const
StatusCode runQualityTests (const DQMMonitorElementList &monitorElementList)
DQMStorage * getStorage () const
Get the monitor element storage.
Private Attributes
DQMStorage * m_pMonitorElementStorage
DQMQualityTestFactoryMap m_qualityTestFactoryMap
DQMQualityTestMap m_qualityTestMap
Friends
class DQMArchiver
Detailed Description
DQMMonitorElementManager class.
Definition at line 50 of file DQMMonitorElementManager.h.
Member Typedef Documentation
typedef std::map<const std::string, const DQMQualityTestFactory *> dqm4hep::DQMMonitorElementManager::DQMQualityTestFactoryMap [private]
Definition at line 55 of file DQMMonitorElementManager.h.
typedef std::map<const std::string, DQMQualityTest *> dqm4hep::DQMMonitorElementManager::DQMQualityTestMap [private]
Definition at line 54 of file DQMMonitorElementManager.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElementManager::DQMMonitorElementManager ()
Constructor.
Definition at line 59 of file DQMMonitorElementManager.cc.
References m_pMonitorElementStorage.
{
  m_pMonitorElementStorage = new DQMStorage();
}
dqm4hep::DQMMonitorElementManager::~DQMMonitorElementManager ()
Dtor.
Definition at line 66 of file DQMMonitorElementManager.cc.
References m_pMonitorElementStorage, m_qualityTestFactoryMap, and m_qualityTestMap.
{
  delete m_pMonitorElementStorage;
  for(DQMQualityTestFactoryMap::iterator iter = m_qualityTestFactoryMap.begin(), endIter =
      m_qualityTestFactoryMap.end() ;
      endIter != iter ; ++iter)
    delete iter->second;
  for(DQMQualityTestMap::iterator iter = m_qualityTestMap.begin(), endIter =
      m_qualityTestMap.end() ;
      endIter != iter ; ++iter)
    delete iter->second;
  m_qualityTestFactoryMap.clear();
  m_qualityTestMap.clear();
}
Member Function Documentation
StatusCode dqm4hep::DQMMonitorElementManager::addQualityTest (DQMMonitorElement * pMonitorElement, const std::string & qualityTestName) const
Add a quality test to a given monitor element.
The quality test must have been registered in the framework before calling this method.
Definition at line 2030 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMMonitorElement::addQualityTest(), getQualityTest(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMModuleApi::addQualityTest().
{
  if(NULL == pMonitorElement)
    return STATUS_CODE_INVALID_PTR;
  DQMQualityTest *pQualityTest = NULL;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getQualityTest(qualityTestName, pQualityTest));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pMonitorElement->addQualityTest(pQualityTest));
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookCharHistogram1D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nBins, float minimum, float maximum)
Book a 1D char histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 254 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by dqm4hep::DQMModuleApi::bookCharHistogram1D(), and bookMonitorElement().
{
  pMonitorElement = NULL;
  TH1 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pHistogram = new TH1C(objectName.c_str(), title.c_str(), nBins, minimum, maximum);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, CHAR_HISTOGRAM_1D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookCharHistogram1D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nBins, float minimum, float maximum)
Book a 1D char histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 938 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TH1 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pHistogram = new TH1C(objectName.c_str(), title.c_str(), nBins, minimum, maximum);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, CHAR_HISTOGRAM_1D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookCharHistogram2D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D char histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 442 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by dqm4hep::DQMModuleApi::bookCharHistogram2D(), and bookMonitorElement().
{
  pMonitorElement = NULL;
  TH2 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pHistogram = new TH2C(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, CHAR_HISTOGRAM_2D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookCharHistogram2D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D char histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1130 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TH2 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pHistogram = new TH2C(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, CHAR_HISTOGRAM_2D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookFloat (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, const float & value)
Book a float scalar element.
The scalar is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 674 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by dqm4hep::DQMModuleApi::bookFloat(), and bookMonitorElement().
{
  pMonitorElement = NULL;
  TScalarFloat *pScalarObject = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the histogram first
    pScalarObject = new TScalarFloat(value);
    if(NULL == pScalarObject)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pScalarObject, REAL_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pScalarObject)
      delete pScalarObject;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookFloat (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, const float & value)
Book a float scalar element.
The scalar is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1366 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TScalarFloat *pScalarObject = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the histogram first
    pScalarObject = new TScalarFloat(value);
    if(NULL == pScalarObject)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pScalarObject, REAL_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pScalarObject)
      delete pScalarObject;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookInt (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, const int & value)
Book an integer scalar element.
The scalar is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 630 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by dqm4hep::DQMModuleApi::bookInt(), and bookMonitorElement().
{
  pMonitorElement = NULL;
  TScalarInt *pScalarObject = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the histogram first
    pScalarObject = new TScalarInt(value);
    if(NULL == pScalarObject)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pScalarObject, INT_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pScalarObject)
      delete pScalarObject;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookInt (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, const int & value)
Book an integer scalar element.
The scalar is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1322 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TScalarInt *pScalarObject = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the histogram first
    pScalarObject = new TScalarInt(value);
    if(NULL == pScalarObject)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pScalarObject, INT_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pScalarObject)
      delete pScalarObject;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookIntHistogram1D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nBins, float minimum, float maximum)
Book a 1D integer histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 207 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by dqm4hep::DQMModuleApi::bookIntHistogram1D(), and bookMonitorElement().
{
  pMonitorElement = NULL;
  TH1 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pHistogram = new TH1I(objectName.c_str(), title.c_str(), nBins, minimum, maximum);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, INT_HISTOGRAM_1D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookIntHistogram1D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nBins, float minimum, float maximum)
Book a 1D integer histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 890 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TH1 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pHistogram = new TH1I(objectName.c_str(), title.c_str(), nBins, minimum, maximum);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, INT_HISTOGRAM_1D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookIntHistogram2D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D integer histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 395 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by dqm4hep::DQMModuleApi::bookIntHistogram2D(), and bookMonitorElement().
{
  pMonitorElement = NULL;
  TH2 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pHistogram = new TH2I(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, INT_HISTOGRAM_2D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookIntHistogram2D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D integer histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1082 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TH2 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pHistogram = new TH2I(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, INT_HISTOGRAM_2D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookMonitorElement (const TiXmlElement *const pXmlElement, const std::string & moduleName, DQMMonitorElement *& pMonitorElement)
Book a monitor element from the xml element.
Definition at line 1532 of file DQMMonitorElementManager.cc.
References bookCharHistogram1D(), bookCharHistogram2D(), bookFloat(), bookInt(), bookIntHistogram1D(), bookIntHistogram2D(), bookObject(), bookProfile1D(), bookProfile2D(), bookRealHistogram1D(), bookRealHistogram2D(), bookShort(), bookShortHistogram1D(), bookShortHistogram2D(), bookString(), dqm4hep::DQMXmlHelper::getAttribute(), mkdir(), dqm4hep::NUMBER_OF_DQM_MONITOR_ELEMENT_TYPES, RETURN_RESULT_IF, RETURN_RESULT_IF_AND_IF, dqm4hep::DQMMonitorElement::setDescription(), dqm4hep::DQMMonitorElement::setDrawOption(), dqm4hep::DQMMonitorElement::setResetPolicy(), dqm4hep::stringToMonitorElementRootType(), dqm4hep::stringToResetPolicy(), and dqm4hep::DQM4HEP::stringToType().
Referenced by dqm4hep::DQMModuleApi::bookMonitorElement().
{
  if(NULL == pXmlElement)
    return STATUS_CODE_INVALID_PTR;
  std::string type;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "type", type));
  DQMMonitorElementType monitorElementType = stringToMonitorElementRootType(type);
  if(NO_ELEMENT_TYPE == monitorElementType || monitorElementType >=
      NUMBER_OF_DQM_MONITOR_ELEMENT_TYPES)
    return STATUS_CODE_INVALID_PARAMETER;
  std::string name;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "name", name));
  // empty path means current directory
  std::string path;
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pXmlElement, "path", path));
  // create dir
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_ALREADY_PRESENT, !=, this->
      mkdir(path));
  // not mandatory
  std::string title;
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pXmlElement, "title", title));
  // not mandatory
  std::string description;
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pXmlElement, "description", description));
  // not mandatory
  std::string drawOption;
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pXmlElement, "drawOption", drawOption));
  // not mandatory
  std::string resetPolicyStr;
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pXmlElement, "resetPolicy", resetPolicyStr));
  // for scalar values
  std::string value;
  RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=,
      DQMXmlHelper::getAttribute(pXmlElement, "value", value));
  switch(monitorElementType)
  {
  case INT_ELEMENT_TYPE :
  {
    int intValue;
    if(!DQM4HEP::stringToType(value, intValue))
      return STATUS_CODE_FAILURE;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookInt(pMonitorElement, path, name, title, moduleName,
       intValue));
    break;
  }
  case REAL_ELEMENT_TYPE :
  {
    float floatValue;
    if(!DQM4HEP::stringToType(value, floatValue))
      return STATUS_CODE_FAILURE;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookFloat(pMonitorElement, path, name, title,
      moduleName, floatValue));
    break;
  }
  case SHORT_ELEMENT_TYPE :
  {
    short shortValue;
    if(!DQM4HEP::stringToType(value, shortValue))
      return STATUS_CODE_FAILURE;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookShort(pMonitorElement, path, name, title,
      moduleName, shortValue));
    break;
  }
  case STRING_ELEMENT_TYPE :
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookString(pMonitorElement, path, name, title,
      moduleName, value));
    break;
  }
  case INT_HISTOGRAM_1D_ELEMENT_TYPE :
  {
    int nBins;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBins", nBins, &
      PositiveValidator<int>::validate));
      float min, max;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "min", min));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "max", max,
      BiggerThanValidator<float>(min)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookIntHistogram1D(pMonitorElement, path, name, title
      , moduleName, nBins, min, max));
      break;
  }
  case REAL_HISTOGRAM_1D_ELEMENT_TYPE :
  {
    int nBins;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBins", nBins, &
      PositiveValidator<int>::validate));
      float min, max;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "min", min));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "max", max,
      BiggerThanValidator<float>(min)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookRealHistogram1D(pMonitorElement, path, name,
      title, moduleName, nBins, min, max));
      break;
  }
  case SHORT_HISTOGRAM_1D_ELEMENT_TYPE :
  {
    int nBins;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBins", nBins, &
      PositiveValidator<int>::validate));
      float min, max;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "min", min));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "max", max,
      BiggerThanValidator<float>(min)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookShortHistogram1D(pMonitorElement, path, name,
      title, moduleName, nBins, min, max));
      break;
  }
  case CHAR_HISTOGRAM_1D_ELEMENT_TYPE :
  {
    int nBins;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBins", nBins, &
      PositiveValidator<int>::validate));
      float min, max;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "min", min));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "max", max,
      BiggerThanValidator<float>(min)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookCharHistogram1D(pMonitorElement, path, name,
      title, moduleName, nBins, min, max));
      break;
  }
  case INT_HISTOGRAM_2D_ELEMENT_TYPE :
  {
    int nBinsX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsX", nBinsX, &
      PositiveValidator<int>::validate));
      float minX, maxX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minX", minX));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxX", maxX,
      BiggerThanValidator<float>(minX)));
    int nBinsY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsY", nBinsY, &
      PositiveValidator<int>::validate));
      float minY, maxY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minY", minY));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxY", maxY,
      BiggerThanValidator<float>(minY)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookIntHistogram2D(pMonitorElement, path, name, title
      , moduleName, nBinsX, minX, maxX, nBinsY, minY, maxY));
      break;
  }
  case REAL_HISTOGRAM_2D_ELEMENT_TYPE :
  {
    int nBinsX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsX", nBinsX, &
      PositiveValidator<int>::validate));
      float minX, maxX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minX", minX));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxX", maxX,
      BiggerThanValidator<float>(minX)));
    int nBinsY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsY", nBinsY, &
      PositiveValidator<int>::validate));
      float minY, maxY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minY", minY));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxY", maxY,
      BiggerThanValidator<float>(minY)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookRealHistogram2D(pMonitorElement, path, name,
      title, moduleName, nBinsX, minX, maxX, nBinsY, minY, maxY));
      break;
  }
  case CHAR_HISTOGRAM_2D_ELEMENT_TYPE :
  {
    int nBinsX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsX", nBinsX, &
      PositiveValidator<int>::validate));
      float minX, maxX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minX", minX));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxX", maxX,
      BiggerThanValidator<float>(minX)));
    int nBinsY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsY", nBinsY, &
      PositiveValidator<int>::validate));
      float minY, maxY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minY", minY));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxY", maxY,
      BiggerThanValidator<float>(minY)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookCharHistogram2D(pMonitorElement, path, name,
      title, moduleName, nBinsX, minX, maxX, nBinsY, minY, maxY));
      break;
  }
  case SHORT_HISTOGRAM_2D_ELEMENT_TYPE :
  {
    int nBinsX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsX", nBinsX, &
      PositiveValidator<int>::validate));
      float minX, maxX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minX", minX));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxX", maxX,
      BiggerThanValidator<float>(minX)));
    int nBinsY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsY", nBinsY, &
      PositiveValidator<int>::validate));
      float minY, maxY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minY", minY));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxY", maxY,
      BiggerThanValidator<float>(minY)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookShortHistogram2D(pMonitorElement, path, name,
      title, moduleName, nBinsX, minX, maxX, nBinsY, minY, maxY));
      break;
  }
  case PROFILE_1D_ELEMENT_TYPE :
  {
    int nBinsX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsX", nBinsX, &
      PositiveValidator<int>::validate));
      float minX, maxX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minX", minX));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxX", maxX,
      BiggerThanValidator<float>(minX)));
      float minY, maxY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minY", minY));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxY", maxX,
      BiggerThanValidator<float>(minY)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookProfile1D(pMonitorElement, path, name, title,
      moduleName, nBinsX, minX, maxX, minY, maxY));
      break;
  }
  case PROFILE_2D_ELEMENT_TYPE :
  {
    int nBinsX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsX", nBinsX, &
      PositiveValidator<int>::validate));
      float minX, maxX;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minX", minX));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxX", maxX,
      BiggerThanValidator<float>(minX)));
    int nBinsY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "nBinsY", nBinsY, &
      PositiveValidator<int>::validate));
      float minY, maxY;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minY", minY));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxY", maxY,
      BiggerThanValidator<float>(minY)));
      float minZ, maxZ;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "minZ", minZ));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "maxZ", maxZ,
      BiggerThanValidator<float>(minZ)));
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookProfile2D(pMonitorElement, path, name, title,
      moduleName, nBinsX, minX, maxX, nBinsY, minY, maxY, minZ, maxZ));
      break;
  }
  case USER_DEFINED_ELEMENT_TYPE :
  {
    std::string rootClass;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "ROOTClass",
      rootClass));
      TClass *pClass = gROOT->GetClass(rootClass.c_str());
      if(!pClass)
        return STATUS_CODE_FAILURE;
      TObject *pObject = reinterpret_cast<TObject *>(pClass->New());
      delete pClass; // no longer needed
      if(!pObject)
        return STATUS_CODE_FAILURE;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->bookObject(pMonitorElement, path, name, title,
      moduleName, pObject));
      break;
  }
  default:
    return STATUS_CODE_FAILURE;
  }
  pMonitorElement->setDrawOption(drawOption);
  pMonitorElement->setDescription(description);
  pMonitorElement->setResetPolicy(stringToResetPolicy(resetPolicyStr));
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookObject (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, TObject * pROOTObject)
Book a generic TObject.
The TObject must be valid and must be a built-in ROOT object or a user defined class inheriting from TObject and providing a dictionary. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 807 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::bookObject().
{
  pMonitorElement = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the monitor element
    pMonitorElement = new DQMMonitorElement(pROOTObject, USER_DEFINED_ELEMENT_TYPE, name, title, moduleName
      );
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookObject (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, TObject * pROOTObject)
Book a generic TObject.
The TObject must be valid and must be a built-in ROOT object or a user defined class inheriting from TObject and providing a dictionary. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 1498 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the monitor element
    pMonitorElement = new DQMMonitorElement(pROOTObject, USER_DEFINED_ELEMENT_TYPE, name, title, moduleName
      );
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(directory, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookProfile1D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, float yMin, float yMax)
Book a 1D profile.
The profile is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 536 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::bookProfile1D().
{
  pMonitorElement = NULL;
  TProfile *pProfile = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pProfile = new TProfile(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, yMin, yMax);
    if(NULL == pProfile)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pProfile, PROFILE_1D_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pProfile)
      delete pProfile;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookProfile1D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, float yMin, float yMax)
Book a 1D profile.
The profile is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1226 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TProfile *pProfile = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pProfile = new TProfile(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, yMin, yMax);
    if(NULL == pProfile)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pProfile, PROFILE_1D_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pProfile)
      delete pProfile;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookProfile2D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax)
Book a 2D profile.
The profile is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 583 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::bookProfile2D().
{
  pMonitorElement = NULL;
  TProfile2D *pProfile = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pProfile = new TProfile2D(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax,
      zMin, zMax);
    if(NULL == pProfile)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pProfile, PROFILE_2D_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pProfile)
      delete pProfile;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookProfile2D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax)
Book a 2D profile.
The profile is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1274 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TProfile2D *pProfile = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pProfile = new TProfile2D(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax,
      zMin, zMax);
    if(NULL == pProfile)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pProfile, PROFILE_2D_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pProfile)
      delete pProfile;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookRealHistogram1D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nBins, float minimum, float maximum)
Book a 1D float histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 160 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::bookRealHistogram1D().
{
  pMonitorElement = NULL;
  TH1 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pHistogram = new TH1F(objectName.c_str(), title.c_str(), nBins, minimum, maximum);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, REAL_HISTOGRAM_1D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookRealHistogram1D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nBins, float minimum, float maximum)
Book a 1D float histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 842 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TH1 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pHistogram = new TH1F(objectName.c_str(), title.c_str(), nBins, minimum, maximum);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, REAL_HISTOGRAM_1D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookRealHistogram2D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D float histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 348 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::bookRealHistogram2D().
{
  pMonitorElement = NULL;
  TH2 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pHistogram = new TH2F(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, REAL_HISTOGRAM_2D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookRealHistogram2D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D float histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1034 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TH2 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pHistogram = new TH2F(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, REAL_HISTOGRAM_2D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookShort (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, const short & value)
Book a short scalar element.
The scalar is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 718 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::bookShort().
{
  pMonitorElement = NULL;
  TScalarShort *pScalarObject = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the histogram first
    pScalarObject = new TScalarShort(value);
    if(NULL == pScalarObject)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pScalarObject, SHORT_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pScalarObject)
      delete pScalarObject;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookShort (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, const short & value)
Book a short scalar element.
The scalar is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1410 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TScalarShort *pScalarObject = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the histogram first
    pScalarObject = new TScalarShort(value);
    if(NULL == pScalarObject)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pScalarObject, SHORT_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pScalarObject)
      delete pScalarObject;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookShortHistogram1D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nBins, float minimum, float maximum)
Book a 1D short histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 301 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::bookShortHistogram1D().
{
  pMonitorElement = NULL;
  TH1 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pHistogram = new TH1S(objectName.c_str(), title.c_str(), nBins, minimum, maximum);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, SHORT_HISTOGRAM_1D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookShortHistogram1D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nBins, float minimum, float maximum)
Book a 1D short histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 986 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TH1 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pHistogram = new TH1S(objectName.c_str(), title.c_str(), nBins, minimum, maximum);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, SHORT_HISTOGRAM_1D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookShortHistogram2D (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D short histogram.
The histogram is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 489 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::bookShortHistogram2D().
{
  pMonitorElement = NULL;
  TH2 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMPath currentDirPath = m_pMonitorElementStorage->getCurrentDirectory()->
      getFullPathName();
    std::string objectName = (currentDirPath + name).getPath();
    // create the histogram first
    pHistogram = new TH2S(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, SHORT_HISTOGRAM_2D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookShortHistogram2D (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D short histogram.
The histogram is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1178 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TH2 *pHistogram = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    DQMDirectory *pDirectory = NULL;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(dirName, pDirectory));
    std::string objectName = (pDirectory->getFullPathName() + name).getPath();
    // create the histogram first
    pHistogram = new TH2S(objectName.c_str(), title.c_str(), nXBins, xMin, xMax, nYBins, yMin, yMax);
    if(NULL == pHistogram)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pHistogram, SHORT_HISTOGRAM_2D_ELEMENT_TYPE, name, title,
      moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pHistogram)
      delete pHistogram;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookString (DQMMonitorElement *& pMonitorElement, const std::string & name, const std::string & title, const std::string & moduleName, const std::string & value)
Book a std::string scalar element.
The scalar is encapsulated in the DQMMonitorElement and added to monitor element list of the module. Such a function should be used in DQMModule implementation by passing 'this' as first argument
Definition at line 762 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::bookString().
{
  pMonitorElement = NULL;
  TScalarString *pScalarObject = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the histogram first
    pScalarObject = new TScalarString(value);
    if(NULL == pScalarObject)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pScalarObject, STRING_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pScalarObject)
      delete pScalarObject;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::bookString (DQMMonitorElement *& pMonitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & moduleName, const std::string & value)
Book a std::string scalar element.
The scalar is encapsulated in the DQMMonitorElement Such a function should be used in DQMModule implementation
Definition at line 1454 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_pMonitorElementStorage, THROW_RESULT_IF, and dqm4hep::StatusCodeException::toString().
{
  pMonitorElement = NULL;
  TScalarString *pScalarObject = NULL;
  if(name.empty() || DQMCoreTool::containsSpecialCharacters(name) || name.find("/") != std::string::npos)
    return STATUS_CODE_INVALID_PARAMETER;
  try
  {
    // create the histogram first
    pScalarObject = new TScalarString(value);
    if(NULL == pScalarObject)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // and the monitor element
    pMonitorElement = new DQMMonitorElement(pScalarObject, STRING_ELEMENT_TYPE, name, title, moduleName);
    if(NULL == pMonitorElement)
      throw StatusCodeException(STATUS_CODE_FAILURE);
    // add it to the monitor element list of the module
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      addMonitorElement(dirName, pMonitorElement));
  }
  catch(StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't create monitor element '" << name << "'. Status code exception caught
       : " << exception.toString() << std::endl;
    if(NULL != pScalarObject)
      delete pScalarObject;
    if(NULL != pMonitorElement)
      delete pMonitorElement;
    return exception.getStatusCode();
  }
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMMonitorElementManager::cd ()
Read the settings for quality tests and initialized them.
Create the quality tests which must be registered before calling this methodGo back to root directory
Definition at line 84 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::cd(), and m_pMonitorElementStorage.
Referenced by dqm4hep::DQMModuleApi::cd().
{
  m_pMonitorElementStorage->cd();
}
StatusCode dqm4hep::DQMMonitorElementManager::cd (const std::string & dirName)
Go to directory 'dirName'.
Definition at line 91 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::cd(), and m_pMonitorElementStorage.
{
  return m_pMonitorElementStorage->cd(dirName);
}
StatusCode dqm4hep::DQMMonitorElementManager::createQualityTest (TiXmlElement *const pXmlElement)
Create a quality test from the xml element.
The xml element must contain the attribute 'type' and 'name'
Definition at line 1988 of file DQMMonitorElementManager.cc.
References dqm4hep::DEBUG, dqm4hep::DQMXmlHelper::getAttribute(), dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMQualityTest::init(), m_qualityTestFactoryMap, m_qualityTestMap, dqm4hep::DQMQualityTest::m_type, dqm4hep::DQMQualityTest::readSettings(), RETURN_RESULT_IF, and THROW_RESULT_IF.
Referenced by dqm4hep::DQMModuleApi::createQualityTest().
{
  std::string name;
  std::string type;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "name", name));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "type", type));
  DQMQualityTestMap::iterator findIter = m_qualityTestMap.find(name);
  if(m_qualityTestMap.end() != findIter)
    return STATUS_CODE_ALREADY_PRESENT;
  DQMQualityTestFactoryMap::iterator findFactoryIter = m_qualityTestFactoryMap.find(type);
  if(m_qualityTestFactoryMap.end() == findFactoryIter)
      return STATUS_CODE_NOT_FOUND;
  DQMQualityTest *const pQualityTest = findFactoryIter->second->createQualityTest(name);
  pQualityTest->m_type = type;
  try
  {
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pQualityTest->readSettings(TiXmlHandle(pXmlElement)));
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pQualityTest->init());
    if(!m_qualityTestMap.insert(DQMQualityTestMap::value_type(name, pQualityTest)).second)
      throw StatusCodeException(STATUS_CODE_FAILURE);
  }
  catch(const StatusCodeException &exception)
  {
    delete pQualityTest;
    return exception.getStatusCode();
  }
  streamlog_out(DEBUG) << "Quality test: type '" << type << "' , name '" << name << "' created" <<
      std::endl;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::deleteMonitorElement (DQMMonitorElement * pMonitorElement)
Delete the monitor element (by element ptr)
Definition at line 1850 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMMonitorElement::getName(), dqm4hep::DQMPath::getPath(), dqm4hep::DQMMonitorElement::getPath(), dqm4hep::DQMStorage::isOwner(), m_pMonitorElementStorage, dqm4hep::DQMStorage::removeMonitorElement(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMModuleApi::deleteMonitorElement().
{
  if(NULL == pMonitorElement)
    return STATUS_CODE_INVALID_PTR;
  const std::string fullPath = pMonitorElement->getPath().getPath();
  const std::string name = pMonitorElement->getName();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      removeMonitorElement(fullPath, name));
  if(!m_pMonitorElementStorage->isOwner() && NULL != pMonitorElement)
    delete pMonitorElement;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::deleteMonitorElement (const std::string & dirName, const std::string & monitorElement)
Delete the monitor element (by element name)
Definition at line 1868 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::getMonitorElement(), dqm4hep::DQMStorage::isOwner(), m_pMonitorElementStorage, dqm4hep::DQMStorage::removeMonitorElement(), and RETURN_RESULT_IF.
{
  if(m_pMonitorElementStorage->isOwner())
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      removeMonitorElement(dirName, monitorElementName));
  }
  else
  {
    DQMMonitorElement *pMonitorElement = NULL;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      getMonitorElement(dirName, monitorElementName, pMonitorElement));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->
      removeMonitorElement(dirName, monitorElementName));
    if(NULL != pMonitorElement)
      delete pMonitorElement;
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::getAllMonitorElements (std::vector< DQMMonitorElement * > & monitorElementList) const
Get all the monitor elements already booked by this module in all the directories.
Definition at line 1810 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::getAllMonitorElements(), and m_pMonitorElementStorage.
Referenced by dqm4hep::DQMModuleApi::getAllMonitorElements(), getMonitorElementListToPublish(), getQualityTestResults(), resetMonitorElements(), and runQualityTests().
{
  return m_pMonitorElementStorage->getAllMonitorElements(monitorElementList);
}
DQMPath dqm4hep::DQMMonitorElementManager::getCurrentDirectoryFullPathName () const
Get the current directory full path name (always defined)
Definition at line 140 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getFullPathName(), and m_pMonitorElementStorage.
{
  return m_pMonitorElementStorage->getCurrentDirectory()->getFullPathName();
}
const std::string & dqm4hep::DQMMonitorElementManager::getCurrentDirectoryName () const
Get the current directory name (always defined)
Definition at line 133 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::getCurrentDirectory(), dqm4hep::DQMDirectory::getName(), and m_pMonitorElementStorage.
{
  return m_pMonitorElementStorage->getCurrentDirectory()->getName();
}
StatusCode dqm4hep::DQMMonitorElementManager::getFullPathName (const std::string & subDirName, DQMPath & fullPathName) const
Get the full path name of the sub directory.
Definition at line 147 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::findDir(), dqm4hep::DQMDirectory::getFullPathName(), m_pMonitorElementStorage, and THROW_RESULT_IF.
{
  DQMDirectory *pDirectory = NULL;
  THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementStorage->findDir(subDirName, pDirectory));
  fullPathName = pDirectory->getFullPathName();
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::getMonitorElement (const std::string & monitorElementName, DQMMonitorElement *& pMonitorElement) const
Get the monitor element in the current directory (result by ptr reference)
Definition at line 1817 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::getMonitorElement(), and m_pMonitorElementStorage.
Referenced by dqm4hep::DQMModuleApi::getMonitorElement(), and getMonitorElement().
{
  return m_pMonitorElementStorage->getMonitorElement(monitorElementName, pMonitorElement);
}
StatusCode dqm4hep::DQMMonitorElementManager::getMonitorElement (const std::string & dirName, const std::string & monitorElementName, DQMMonitorElement *& pMonitorElement) const
Get the monitor element in the given directory (result by ptr reference)
Definition at line 1824 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::getMonitorElement(), and m_pMonitorElementStorage.
{
  return m_pMonitorElementStorage->getMonitorElement(dirName, monitorElementName, pMonitorElement);
}
DQMMonitorElement * dqm4hep::DQMMonitorElementManager::getMonitorElement (const std::string & monitorElementName) const
Get the monitor element in the current directory.
The element is directly returned without any ptr check
Definition at line 1831 of file DQMMonitorElementManager.cc.
References getMonitorElement().
{
  DQMMonitorElement *pMonitorElement = NULL;
  this->getMonitorElement(monitorElementName, pMonitorElement);
  return pMonitorElement;
}
DQMMonitorElement * dqm4hep::DQMMonitorElementManager::getMonitorElement (const std::string & dirName, const std::string & monitorElementName) const
Get the monitor element in the given directory.
The element is directly returned without any ptr check
Definition at line 1840 of file DQMMonitorElementManager.cc.
References getMonitorElement().
{
  DQMMonitorElement *pMonitorElement = NULL;
  this->getMonitorElement(dirName, monitorElementName, pMonitorElement);
  return pMonitorElement;
}
StatusCode dqm4hep::DQMMonitorElementManager::getMonitorElementListToPublish (DQMMonitorElementList & monitorElementList) const
Get the monitor element list for which the flag `setToPublish` is true.
Definition at line 1934 of file DQMMonitorElementManager.cc.
References getAllMonitorElements(), dqm4hep::DQMMonitorElement::isToPublish(), and RETURN_RESULT_IF.
{
  DQMMonitorElementList moduleElementList;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getAllMonitorElements(moduleElementList));
  for(DQMMonitorElementList::const_iterator iter = moduleElementList.begin(), endIter = moduleElementList.
      end() ;
      endIter != iter ; ++iter)
  {
    DQMMonitorElement *pMonitorElement = *iter;
    if(pMonitorElement->isToPublish())
      monitorElementListToPublish.push_back(pMonitorElement);
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::getQualityTest (const std::string & qualityTestName, DQMQualityTest *& pQualityTest) const [private]
Definition at line 2087 of file DQMMonitorElementManager.cc.
References m_qualityTestMap.
Referenced by addQualityTest().
{
  pQualityTest = NULL;
  // look for an existing quality test in the map
  DQMQualityTestMap::const_iterator qTestFindIter = m_qualityTestMap.find(qualityTestName);
  if(m_qualityTestMap.end() == qTestFindIter)
    return STATUS_CODE_NOT_FOUND;
  pQualityTest = qTestFindIter->second;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::getQualityTestResults (DQMQualityTestResultMap & results) const
Get all the quality test results.
Definition at line 2104 of file DQMMonitorElementManager.cc.
References getAllMonitorElements(), dqm4hep::DQMMonitorElement::getQualityTestResults(), and RETURN_RESULT_IF.
{
  DQMMonitorElementList monitorElementList;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getAllMonitorElements(monitorElementList));
  for(DQMMonitorElementList::const_iterator iter = monitorElementList.begin(), endIter =
      monitorElementList.end() ;
      endIter != iter ; ++iter)
  {
    DQMMonitorElement *pMonitorElement = *iter;
    const DQMQualityTestResultMap &meResults(pMonitorElement->getQualityTestResults());
    results.insert(meResults.begin(), meResults.end());
  }
  return STATUS_CODE_SUCCESS;
}
DQMStorage * dqm4hep::DQMMonitorElementManager::getStorage () const [private]
Get the monitor element storage.
Definition at line 2123 of file DQMMonitorElementManager.cc.
References m_pMonitorElementStorage.
Referenced by dqm4hep::DQMArchiver::archive().
{
  return m_pMonitorElementStorage;
}
StatusCode dqm4hep::DQMMonitorElementManager::goUp ()
Navigate backward in the directory structure.
Definition at line 119 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::goUp(), and m_pMonitorElementStorage.
Referenced by dqm4hep::DQMModuleApi::goUp().
{
  return m_pMonitorElementStorage->goUp();
}
void dqm4hep::DQMMonitorElementManager::ls (bool recursive = false)
List the current directory content.
Definition at line 105 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMStorage::ls(), and m_pMonitorElementStorage.
Referenced by dqm4hep::DQMModuleApi::ls().
{
  m_pMonitorElementStorage->ls(recursive);
}
StatusCode dqm4hep::DQMMonitorElementManager::mkdir (const std::string & dirName)
Create the directory 'dirName'.
Definition at line 98 of file DQMMonitorElementManager.cc.
References m_pMonitorElementStorage, and dqm4hep::DQMStorage::mkdir().
Referenced by bookMonitorElement(), and dqm4hep::DQMModuleApi::mkdir().
{
  return m_pMonitorElementStorage->mkdir(dirName);
}
const std::string & dqm4hep::DQMMonitorElementManager::pwd ()
Get the current directory name.
Definition at line 112 of file DQMMonitorElementManager.cc.
References m_pMonitorElementStorage, and dqm4hep::DQMStorage::pwd().
Referenced by dqm4hep::DQMModuleApi::pwd().
{
  return m_pMonitorElementStorage->pwd();
}
StatusCode dqm4hep::DQMMonitorElementManager::registerQualityTestFactory (const std::string & qualityTestType, const DQMQualityTestFactory *const pQualityTestFactory)
Register a new quality test.
Ownership transfered to the manager.
Definition at line 1967 of file DQMMonitorElementManager.cc.
References dqm4hep::DEBUG, and m_qualityTestFactoryMap.
Referenced by dqm4hep::DQMModuleApi::registerQualityTestFactory().
{
  if(NULL == pQualityTestFactory)
    return STATUS_CODE_INVALID_PTR;
  DQMQualityTestFactoryMap::iterator findIter = m_qualityTestFactoryMap.find(qualityTestFactoryName);
  if(m_qualityTestFactoryMap.end() != findIter)
  {
    delete pQualityTestFactory;
    return STATUS_CODE_ALREADY_PRESENT;
  }
  m_qualityTestFactoryMap[qualityTestFactoryName] = pQualityTestFactory;
  streamlog_out(DEBUG) << "Quality test " << qualityTestFactoryName << " registered !" << std::endl;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::removeQualityTest (DQMMonitorElement * pMonitorElement, const std::string & qualityTestName)
Remove a specific quality test attached to this monitor element.
StatusCode dqm4hep::DQMMonitorElementManager::removeQualityTests (DQMMonitorElement * pMonitorElement)
Remove all quality tests attached to this monitor element.
StatusCode dqm4hep::DQMMonitorElementManager::resetMonitorElements (DQMResetPolicy policy) const
Reset all the monitor elements that have the given reset policy.
Definition at line 1891 of file DQMMonitorElementManager.cc.
References getAllMonitorElements(), dqm4hep::DQMMonitorElement::getResetPolicy(), dqm4hep::DQMMonitorElement::reset(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMModuleApi::resetMonitorElements().
{
  DQMMonitorElementList monitorElementList;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getAllMonitorElements(monitorElementList));
  for(DQMMonitorElementList::iterator iter = monitorElementList.begin(), endIter = monitorElementList.end()
       ;
      endIter != iter ; ++iter)
  {
    DQMMonitorElement *pMonitorElement = *iter;
    if(NULL == pMonitorElement)
      continue;
    if(policy == pMonitorElement->getResetPolicy())
      pMonitorElement->reset();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::resetMonitorElements () const
Reset all the monitor elements of this module.
Definition at line 1913 of file DQMMonitorElementManager.cc.
References getAllMonitorElements(), dqm4hep::DQMMonitorElement::reset(), and RETURN_RESULT_IF.
{
  DQMMonitorElementList monitorElementList;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getAllMonitorElements(monitorElementList));
  for(DQMMonitorElementList::iterator iter = monitorElementList.begin(), endIter = monitorElementList.end()
       ;
      endIter != iter ; ++iter)
  {
    DQMMonitorElement *pMonitorElement = *iter;
    if(NULL == pMonitorElement)
      continue;
    pMonitorElement->reset();
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementManager::rmdir (const std::string & dirName)
Remove the directory 'dirName'.
Definition at line 126 of file DQMMonitorElementManager.cc.
References m_pMonitorElementStorage, and dqm4hep::DQMStorage::rmdir().
Referenced by dqm4hep::DQMModuleApi::rmdir().
{
  return m_pMonitorElementStorage->rmdir(dirName);
}
StatusCode dqm4hep::DQMMonitorElementManager::runQualityTest (DQMMonitorElement * pMonitorElement, const std::string & qualityTestName)
Run a specific quality test attached to this monitor element.
Definition at line 2054 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMMonitorElement::runQualityTest().
Referenced by dqm4hep::DQMModuleApi::runQualityTest().
{
  if(NULL == pMonitorElement)
    return STATUS_CODE_INVALID_PTR;
  return pMonitorElement->runQualityTest(qualityTestName);
}
StatusCode dqm4hep::DQMMonitorElementManager::runQualityTests (DQMMonitorElement * pMonitorElement)
Run all the quality test attached to this monitor element.
Definition at line 2044 of file DQMMonitorElementManager.cc.
References dqm4hep::DQMMonitorElement::runQualityTests().
Referenced by dqm4hep::DQMModuleApi::runQualityTests().
{
  if(NULL == pMonitorElement)
    return STATUS_CODE_INVALID_PTR;
  return pMonitorElement->runQualityTests();
}
StatusCode dqm4hep::DQMMonitorElementManager::runQualityTests ()
Run all the quality test of all the monitor elements.
Definition at line 2064 of file DQMMonitorElementManager.cc.
References getAllMonitorElements(), and RETURN_RESULT_IF.
Referenced by runQualityTests().
{
  DQMMonitorElementList monitorElementList;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getAllMonitorElements(monitorElementList));
  return this->runQualityTests(monitorElementList);
}
StatusCode dqm4hep::DQMMonitorElementManager::runQualityTests (const DQMMonitorElementList & monitorElementList) [private]
Definition at line 2074 of file DQMMonitorElementManager.cc.
References RETURN_RESULT_IF, and runQualityTests().
{
  for(DQMMonitorElementList::const_iterator iter = monitorElementList.begin(), endIter = monitorElementList
      .end() ;
      endIter != iter ; ++iter)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->runQualityTests(*iter));
  }
  return STATUS_CODE_SUCCESS;
}
Friends And Related Function Documentation
friend class DQMArchiver [friend]
Definition at line 52 of file DQMMonitorElementManager.h.
Member Data Documentation
DQMStorage* dqm4hep::DQMMonitorElementManager::m_pMonitorElementStorage [private]
Definition at line 450 of file DQMMonitorElementManager.h.
Referenced by bookCharHistogram1D(), bookCharHistogram2D(), bookFloat(), bookInt(), bookIntHistogram1D(), bookIntHistogram2D(), bookObject(), bookProfile1D(), bookProfile2D(), bookRealHistogram1D(), bookRealHistogram2D(), bookShort(), bookShortHistogram1D(), bookShortHistogram2D(), bookString(), cd(), deleteMonitorElement(), DQMMonitorElementManager(), getAllMonitorElements(), getCurrentDirectoryFullPathName(), getCurrentDirectoryName(), getFullPathName(), getMonitorElement(), getStorage(), goUp(), ls(), mkdir(), pwd(), rmdir(), and ~DQMMonitorElementManager().
DQMQualityTestFactoryMap dqm4hep::DQMMonitorElementManager::m_qualityTestFactoryMap [private]
Definition at line 451 of file DQMMonitorElementManager.h.
Referenced by createQualityTest(), registerQualityTestFactory(), and ~DQMMonitorElementManager().
DQMQualityTestMap dqm4hep::DQMMonitorElementManager::m_qualityTestMap [private]
Definition at line 452 of file DQMMonitorElementManager.h.
Referenced by createQualityTest(), getQualityTest(), and ~DQMMonitorElementManager().
The documentation for this class was generated from the following files:
DQMMonitorElementManager.h
DQMMonitorElementManager.cc