dqm4hep::DQMMonitorElement Class Reference
DQMMonitorElement class.
#include <DQMMonitorElement.h>
Public Member Functions
DQMMonitorElement (DQMMonitorElementType type=NO_ELEMENT_TYPE, const std::string &name=``, const std::string &title=``, const std::string &moduleName=``)
Default constructor.
DQMMonitorElement (TObject *pObject, DQMMonitorElementType type, const std::string &name, const std::string &title, const std::string &moduleName)
DQMMonitorElement with type, name and title.
virtual ~DQMMonitorElement ()
Destructor.
DQMMonitorElementType getType () const
Returns the element type.
virtual const std::string & getName () const
Returns the name of the element.
const DQMPath & getPath () const
Get the path (directory) of this element.
void setPath (const DQMPath &path)
Set the path (directory) for this element.
const std::string & getCollectorName () const
Get the collector name where this element is collected (or will be) Set by the framework after collect.
void setCollectorName (const std::string &collectorName)
Set the collector name where this element is collected (or will be) Used by the framework after collect.
const std::string & getModuleName () const
Get the module name that has booked this element.
bool isHistogram () const
Whether the monitor element is a histogram.
bool isScalar () const
Whether the monitor element is a scalar value.
DQMQuality getQuality () const
Returns the element quality.
void setQuality (DQMQuality quality)
Set the element quality.
DQMResetPolicy getResetPolicy () const
Returns the reset policy of the element.
void setResetPolicy (DQMResetPolicy policy)
Sets the reset policy of the element.
virtual const std::string & getTitle () const
Returns the title of the object.
virtual void setTitle (const std::string &title)
Sets the element title.
const std::string & getDescription () const
Returns the element description.
void setDescription (const std::string &description)
Sets the element description.
const std::string & getDrawOption () const
Return the draw option.
void setDrawOption (const std::string &drawOption)
Set the draw option.
unsigned int getRunNumber () const
Returns the current run for this monitor element.
void setRunNumber (unsigned int runNumber)
Sets the current run number.
void setToPublish (bool publish)
Sets whether the element has to be published at the next end of cycle.
bool isToPublish () const
Whether the element has to be published at the next end of cycle.
TObject * getObject () const
Return the associated TObject that is monitored.
template<typename T >
T * get () const
Return the monitor object after a dynamic cast of the asked type.
const DQMQualityTestResultMap & getQualityTestResults () const
Return the quality test results map.
void reset ()
Reset the element.
StatusCode serialize (DQMDataStream *const pDataStream) const
StatusCode deserialize (DQMDataStream *const pDataStream)
Private Member Functions
StatusCode runQualityTest (const std::string &qualityTestName)
Run the given quality test.
StatusCode runQualityTests ()
Run all the quality tests.
StatusCode addQualityTest (DQMQualityTest *pQualityTest)
Add a quality test.
StatusCode removeQualityTest (DQMQualityTest *pQualityTest)
Remove a quality test.
StatusCode removeQualityTest (const std::string &qualityTestName)
Remove a quality test.
Private Attributes
TObject * m_pObject
The monitored TObject.
std::string m_name
The element name.
std::string m_title
The element title.
std::string m_description
The element description.
std::string m_drawOption
The draw option to apply while drawing.
std::string m_moduleName
The module name that have booked this element.
std::string m_collectorName
The collector name that have collected this element.
DQMPath m_path
DQMMonitorElementType m_type
The element type.
DQMQuality m_quality
The element quality has defined by the user.
DQMResetPolicy m_resetPolicy
The reset policy. See enumerator definition.
unsigned int m_runNumber
The run number when the element is published.
bool m_toPublish
Whether the element has to be published at end of cycle.
std::map< std::string,
*
DQMQualityTest * > m_qualityTestMap
std::map< std::string,
*
DQMQualityTestResult > m_qualityTestResultMap
The quality test map to perform.
Friends
class DQMModuleApi
class DQMStorage
class DQMDirectory
class DQMMonitorElementManager
Detailed Description
DQMMonitorElement class.
Base class for plots and scalars that can be monitored via a user module. Monitor elements can be booked via the DQMModuleApi in order to be published.
Author
R.Ete
Definition at line 58 of file DQMMonitorElement.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElement::DQMMonitorElement (DQMMonitorElementType type = NO_ELEMENT_TYPE, const std::string & name = ``, const std::string & title = ``, const std::string & moduleName = ``)
Default constructor.
dqm4hep::DQMMonitorElement::DQMMonitorElement (TObject * pObject, DQMMonitorElementType type, const std::string & name, const std::string & title, const std::string & moduleName)
DQMMonitorElement with type, name and title.
virtual dqm4hep::DQMMonitorElement::~DQMMonitorElement () [virtual]
Destructor.
Member Function Documentation
StatusCode dqm4hep::DQMMonitorElement::addQualityTest (DQMQualityTest * pQualityTest) [private]
Add a quality test.
Referenced by dqm4hep::DQMMonitorElementManager::addQualityTest().
StatusCode dqm4hep::DQMMonitorElement::deserialize (DQMDataStream *const pDataStream)
Referenced by dqm4hep::DQMMonitorElementPublication::deserialize().
template<typename T > T * dqm4hep::DQMMonitorElement::get () const
Return the monitor object after a dynamic cast of the asked type.
Definition at line 245 of file DQMMonitorElement.h.
References m_pObject.
Referenced by dqm4hep::DQMMeanWithinExpectedTest::canRun(), dqm4hep::DQMChi2FitFunctionTest::canRun(), dqm4hep::DQMMeanWithinExpectedTest::run(), and dqm4hep::DQMChi2FitFunctionTest::run().
{
  return dynamic_cast<T*>(m_pObject);
}
const std::string& dqm4hep::DQMMonitorElement::getCollectorName () const
Get the collector name where this element is collected (or will be) Set by the framework after collect.
const std::string& dqm4hep::DQMMonitorElement::getDescription () const
Returns the element description.
Referenced by dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement().
const std::string& dqm4hep::DQMMonitorElement::getDrawOption () const
Return the draw option.
const std::string& dqm4hep::DQMMonitorElement::getModuleName () const
Get the module name that has booked this element.
virtual const std::string& dqm4hep::DQMMonitorElement::getName () const [virtual]
Returns the name of the element.
Referenced by dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMDirectory::containsMonitorElement(), dqm4hep::DQMModuleApi::deleteMonitorElement(), dqm4hep::DQMMonitorElementManager::deleteMonitorElement(), dqm4hep::DQMDirectory::findMonitorElement(), dqm4hep::DQMDirectory::ls(), dqm4hep::DQMDirectory::removeMonitorElement(), dqm4hep::DQMChi2FitFunctionTest::run(), dqm4hep::ModuleMeInfo::updateMonitorElement(), and dqm4hep::DQMArchiver::writeMonitorElements().
TObject* dqm4hep::DQMMonitorElement::getObject () const
Return the associated TObject that is monitored.
Referenced by dqm4hep::DQMArchiver::writeMonitorElements().
const DQMPath& dqm4hep::DQMMonitorElement::getPath () const
Get the path (directory) of this element.
Referenced by dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMModuleApi::deleteMonitorElement(), dqm4hep::DQMMonitorElementManager::deleteMonitorElement(), and dqm4hep::ModuleMeInfo::updateMonitorElement().
DQMQuality dqm4hep::DQMMonitorElement::getQuality () const
Returns the element quality.
const DQMQualityTestResultMap& dqm4hep::DQMMonitorElement::getQualityTestResults () const
Return the quality test results map.
Key : quality test name, value : quality test result
Referenced by dqm4hep::DQMMonitorElementManager::getQualityTestResults().
DQMResetPolicy dqm4hep::DQMMonitorElement::getResetPolicy () const
Returns the reset policy of the element.
See enumerator definition
Referenced by dqm4hep::DQMMonitorElementManager::resetMonitorElements().
unsigned int dqm4hep::DQMMonitorElement::getRunNumber () const
Returns the current run for this monitor element.
virtual const std::string& dqm4hep::DQMMonitorElement::getTitle () const [virtual]
Returns the title of the object.
DQMMonitorElementType dqm4hep::DQMMonitorElement::getType () const
Returns the element type.
Referenced by dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), dqm4hep::DQMMeanWithinExpectedTest::canRun(), and dqm4hep::DQMChi2FitFunctionTest::canRun().
bool dqm4hep::DQMMonitorElement::isHistogram () const
Whether the monitor element is a histogram.
bool dqm4hep::DQMMonitorElement::isScalar () const
Whether the monitor element is a scalar value.
bool dqm4hep::DQMMonitorElement::isToPublish () const
Whether the element has to be published at the next end of cycle.
Referenced by dqm4hep::DQMMonitorElementManager::getMonitorElementListToPublish().
StatusCode dqm4hep::DQMMonitorElement::removeQualityTest (DQMQualityTest * pQualityTest) [private]
Remove a quality test.
StatusCode dqm4hep::DQMMonitorElement::removeQualityTest (const std::string & qualityTestName) [private]
Remove a quality test.
void dqm4hep::DQMMonitorElement::reset ()
Reset the element.
Referenced by dqm4hep::DQMMonitorElementManager::resetMonitorElements().
StatusCode dqm4hep::DQMMonitorElement::runQualityTest (const std::string & qualityTestName) [private]
Run the given quality test.
Referenced by dqm4hep::DQMMonitorElementManager::runQualityTest().
StatusCode dqm4hep::DQMMonitorElement::runQualityTests () [private]
Run all the quality tests.
Referenced by dqm4hep::DQMMonitorElementManager::runQualityTests().
StatusCode dqm4hep::DQMMonitorElement::serialize (DQMDataStream *const pDataStream) const
Referenced by dqm4hep::DQMMonitorElementPublication::serialize().
void dqm4hep::DQMMonitorElement::setCollectorName (const std::string & collectorName)
Set the collector name where this element is collected (or will be) Used by the framework after collect.
void dqm4hep::DQMMonitorElement::setDescription (const std::string & description)
Sets the element description.
Referenced by dqm4hep::DQMMonitorElementManager::bookMonitorElement().
void dqm4hep::DQMMonitorElement::setDrawOption (const std::string & drawOption)
Set the draw option.
Referenced by dqm4hep::DQMMonitorElementManager::bookMonitorElement().
void dqm4hep::DQMMonitorElement::setPath (const DQMPath & path)
Set the path (directory) for this element.
Referenced by dqm4hep::DQMStorage::addMonitorElement(), and dqm4hep::DQMStorage::removeMonitorElement().
void dqm4hep::DQMMonitorElement::setQuality (DQMQuality quality)
Set the element quality.
void dqm4hep::DQMMonitorElement::setResetPolicy (DQMResetPolicy policy)
Sets the reset policy of the element.
See enumerator definition
Referenced by dqm4hep::DQMMonitorElementManager::bookMonitorElement().
void dqm4hep::DQMMonitorElement::setRunNumber (unsigned int runNumber)
Sets the current run number.
virtual void dqm4hep::DQMMonitorElement::setTitle (const std::string & title) [virtual]
Sets the element title.
void dqm4hep::DQMMonitorElement::setToPublish (bool publish)
Sets whether the element has to be published at the next end of cycle.
This flag is not reset by the framework. The user is responsible for publishing or not the element.
Friends And Related Function Documentation
friend class DQMDirectory [friend]
Definition at line 62 of file DQMMonitorElement.h.
friend class DQMModuleApi [friend]
Definition at line 60 of file DQMMonitorElement.h.
friend class DQMMonitorElementManager [friend]
Definition at line 63 of file DQMMonitorElement.h.
friend class DQMStorage [friend]
Definition at line 61 of file DQMMonitorElement.h.
Member Data Documentation
std::string dqm4hep::DQMMonitorElement::m_collectorName [private]
The collector name that have collected this element.
Definition at line 227 of file DQMMonitorElement.h.
std::string dqm4hep::DQMMonitorElement::m_description [private]
The element description.
Definition at line 224 of file DQMMonitorElement.h.
std::string dqm4hep::DQMMonitorElement::m_drawOption [private]
The draw option to apply while drawing.
Definition at line 225 of file DQMMonitorElement.h.
std::string dqm4hep::DQMMonitorElement::m_moduleName [private]
The module name that have booked this element.
Definition at line 226 of file DQMMonitorElement.h.
std::string dqm4hep::DQMMonitorElement::m_name [private]
The element name.
Definition at line 222 of file DQMMonitorElement.h.
DQMPath dqm4hep::DQMMonitorElement::m_path [private]
Definition at line 229 of file DQMMonitorElement.h.
TObject* dqm4hep::DQMMonitorElement::m_pObject [private]
The monitored TObject.
Definition at line 220 of file DQMMonitorElement.h.
Referenced by get().
DQMQuality dqm4hep::DQMMonitorElement::m_quality [private]
The element quality has defined by the user.
Definition at line 231 of file DQMMonitorElement.h.
std::map<std::string, DQMQualityTest*> dqm4hep::DQMMonitorElement::m_qualityTestMap [private]
Definition at line 237 of file DQMMonitorElement.h.
std::map<std::string, DQMQualityTestResult> dqm4hep::DQMMonitorElement::m_qualityTestResultMap [private]
The quality test map to perform.
Definition at line 238 of file DQMMonitorElement.h.
DQMResetPolicy dqm4hep::DQMMonitorElement::m_resetPolicy [private]
The reset policy. See enumerator definition.
Definition at line 232 of file DQMMonitorElement.h.
unsigned int dqm4hep::DQMMonitorElement::m_runNumber [private]
The run number when the element is published.
Definition at line 234 of file DQMMonitorElement.h.
std::string dqm4hep::DQMMonitorElement::m_title [private]
The element title.
Definition at line 223 of file DQMMonitorElement.h.
bool dqm4hep::DQMMonitorElement::m_toPublish [private]
Whether the element has to be published at end of cycle.
Definition at line 235 of file DQMMonitorElement.h.
DQMMonitorElementType dqm4hep::DQMMonitorElement::m_type [private]
The element type.
Definition at line 230 of file DQMMonitorElement.h.
The documentation for this class was generated from the following file:
DQMMonitorElement.h