dqm4hep::DQMMonitorElementSender Class Reference
DQMMonitorElementSender class.
#include <DQMMonitorElementSender.h>
Public Member Functions
DQMMonitorElementSender (DQMModuleApplication *pApplication)
Constructor.
~DQMMonitorElementSender ()
Destructor.
StatusCode setCollectorName (const std::string &collectorName)
Set the collector name to which the elements will be sent.
StatusCode sendMonitorElements ()
Send the subscribed monitor element to the collector.
StatusCode connectToService ()
Connect the sender to the collector.
StatusCode disconnectFromService ()
Disconnect the sender to the collector.
bool isConnectedToService () const
Whether the sender is connected to the collector.
Private Types
typedef std::map< std::string,
*
DQMMonitorElementInfo > DQMMonitorElementInfoMap
Private Member Functions
void infoHandler ()
void addAvailableMonitorElement (DQMMonitorElement *pMonitorElement)
void removeAvailableMonitorElement (const std::string &monitorElementName)
void sendAvailableMonitorElementList ()
Private Attributes
DQMModuleApplication * m_pApplication
The module application that sends elements to the collector.
std::string m_collectorName
The collector name to which the monitor elements will be sent.
DQMDataStream m_dataStream
The data stream used to serialize the monitor elements.
DQMDataStream m_inDataStream
The data stream used to serialize dim info.
StringSet m_subscribedMeList
The subscribed monitor element list.
DQMMonitorElementInfoMap m_availableMeMap
The available monitor element list.
pthread_mutex_t m_mutex
Mutex to lock unlock on service update.
bool m_sendAvailableMeList
Whether the list of available me has to be re-sent to the collector.
bool m_isConnected
Whether the sender is connected to the collector.
DimUpdatedInfo * m_pSubscribedListInfo
The dim info to receive subscribed me list from collector.
DimUpdatedInfo * m_pCollectorStateInfo
The dim info to receive when the collector state changes.
Friends
class DQMModuleApi
Detailed Description
DQMMonitorElementSender class.
Definition at line 46 of file DQMMonitorElementSender.h.
Member Typedef Documentation
typedef std::map<std::string, DQMMonitorElementInfo> dqm4hep::DQMMonitorElementSender::DQMMonitorElementInfoMap [private]
Definition at line 96 of file DQMMonitorElementSender.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElementSender::DQMMonitorElementSender (DQMModuleApplication * pApplication)
Constructor.
Definition at line 41 of file DQMMonitorElementSender.cc.
References m_mutex.
                                                                                   :
    m_pApplication(pApplication),
    m_collectorName("DEFAULT"),
    m_dataStream(4*1024*1024), // 4 Mo to start
    m_inDataStream(1024*1024),
    m_sendAvailableMeList(true)
{
  pthread_mutex_init(&m_mutex, NULL);
}
dqm4hep::DQMMonitorElementSender::~DQMMonitorElementSender ()
Destructor.
Definition at line 53 of file DQMMonitorElementSender.cc.
References m_mutex.
{
  pthread_mutex_destroy(&m_mutex);
}
Member Function Documentation
void dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement (DQMMonitorElement * pMonitorElement) [private]
Definition at line 273 of file DQMMonitorElementSender.cc.
References dqm4hep::DQMMonitorElement::getDescription(), dqm4hep::DQMModuleApplication::getModule(), dqm4hep::DQMModule::getName(), dqm4hep::DQMMonitorElement::getName(), dqm4hep::DQMPath::getPath(), dqm4hep::DQMMonitorElement::getPath(), dqm4hep::DQMMonitorElement::getType(), m_availableMeMap, m_pApplication, m_sendAvailableMeList, and dqm4hep::monitorElementTypeToString().
Referenced by dqm4hep::DQMModuleApi::bookCharHistogram1D(), dqm4hep::DQMModuleApi::bookCharHistogram2D(), dqm4hep::DQMModuleApi::bookFloat(), dqm4hep::DQMModuleApi::bookInt(), dqm4hep::DQMModuleApi::bookIntHistogram1D(), dqm4hep::DQMModuleApi::bookIntHistogram2D(), dqm4hep::DQMModuleApi::bookMonitorElement(), dqm4hep::DQMModuleApi::bookObject(), dqm4hep::DQMModuleApi::bookProfile1D(), dqm4hep::DQMModuleApi::bookProfile2D(), dqm4hep::DQMModuleApi::bookRealHistogram1D(), dqm4hep::DQMModuleApi::bookRealHistogram2D(), dqm4hep::DQMModuleApi::bookShort(), dqm4hep::DQMModuleApi::bookShortHistogram1D(), dqm4hep::DQMModuleApi::bookShortHistogram2D(), and dqm4hep::DQMModuleApi::bookString().
{
  std::string fullName = (pMonitorElement->getPath() + pMonitorElement->getName()).getPath();
  if(fullName.at(0) != '/')
    fullName = "/" + fullName;
  // prepare for insert
  DQMMonitorElementInfoMap::value_type insertValue(fullName , DQMMonitorElementInfo());
  // insert it
  std::pair<DQMMonitorElementInfoMap::iterator, bool> ret = m_availableMeMap.insert(insertValue);
  // return is already present
  if(!ret.second)
    return;
  // fill info
  ret.first->second.m_moduleName = m_pApplication->getModule()->getName();
  ret.first->second.m_monitorElementFullPath = pMonitorElement->getPath().getPath();
  ret.first->second.m_monitorElementType = monitorElementTypeToString(pMonitorElement->getType());
  ret.first->second.m_monitorElementName = pMonitorElement->getName();
  ret.first->second.m_monitorElementDescription = pMonitorElement->getDescription();
  std::cout << "me : " << pMonitorElement->getName() << " added in sender" << std::endl;
  // for future update on the collector side
  m_sendAvailableMeList = true;
}
StatusCode dqm4hep::DQMMonitorElementSender::connectToService ()
Connect the sender to the collector.
Definition at line 166 of file DQMMonitorElementSender.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isConnectedToService(), m_collectorName, m_inDataStream, m_isConnected, m_pCollectorStateInfo, and m_pSubscribedListInfo.
Referenced by dqm4hep::DQMAnalysisModuleApplication::stopServices().
{
  if(this->isConnectedToService())
    return STATUS_CODE_SUCCESS;
  std::string serviceName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/NOTIFY_WATCHED_ME_SVC"
      ;
  m_pSubscribedListInfo = new DimUpdatedInfo((char *) serviceName.c_str() , (void *)
      m_inDataStream.getBuffer() , m_inDataStream.getBufferSize() , this);
  serviceName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/COLLECTOR_STATE_SVC";
  m_pCollectorStateInfo = new DimUpdatedInfo((char *) serviceName.c_str(), STOPPED_STATE , this);
  m_isConnected = true;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementSender::disconnectFromService ()
Disconnect the sender to the collector.
Definition at line 184 of file DQMMonitorElementSender.cc.
References isConnectedToService(), m_isConnected, m_pCollectorStateInfo, and m_pSubscribedListInfo.
{
  if(! this->isConnectedToService())
    return STATUS_CODE_SUCCESS;
  delete m_pSubscribedListInfo;
  delete m_pCollectorStateInfo;
  m_isConnected = false;
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMMonitorElementSender::infoHandler () [private]
Definition at line 206 of file DQMMonitorElementSender.cc.
References dqm4hep::DEBUG, m_inDataStream, m_mutex, m_pCollectorStateInfo, m_pSubscribedListInfo, m_sendAvailableMeList, m_subscribedMeList, dqm4hep::DQMDataStream::read(), dqm4hep::DQMDataStream::reset(), and dqm4hep::DQMDataStream::setBuffer().
{
  DimInfo *pInfo = getInfo();
  streamlog_out(DEBUG) << "Received info : " << pInfo->getName() << std::endl;
  if(pInfo == m_pSubscribedListInfo)
  {
    dqm_char *pBuffer = (dqm_char *) m_pSubscribedListInfo->getData();
    dqm_uint bufferSize = m_pSubscribedListInfo->getSize();
    if(!pBuffer || bufferSize == 0)
      return;
    m_inDataStream.reset();
    m_inDataStream.setBuffer(pBuffer, bufferSize);
    StringVector subscribedMeList;
    dqm_uint size;
    if(STATUS_CODE_SUCCESS != m_inDataStream.read(size))
    {
      m_inDataStream.reset();
      return;
    }
    subscribedMeList.resize(size);
    for(dqm_uint i=0 ; i<size ; i++)
    {
      if(STATUS_CODE_SUCCESS != m_inDataStream.read(subscribedMeList[i]))
      {
        m_inDataStream.reset();
        return;
      }
    }
    // update the list
    pthread_mutex_lock(&m_mutex);
    std::cout << "Received subscribed list size : " << subscribedMeList.size() << std::endl;
    m_subscribedMeList.clear();
    m_subscribedMeList.insert(subscribedMeList.begin(), subscribedMeList.end());
    pthread_mutex_unlock(&m_mutex);
  }
  else if(pInfo == m_pCollectorStateInfo)
  {
    if(m_pCollectorStateInfo->getInt() == RUNNING_STATE)
    {
      streamlog_out(DEBUG) << "Force update available list on next EOC !" << std::endl;
      pthread_mutex_lock(&m_mutex);
      m_sendAvailableMeList = true;
      pthread_mutex_unlock(&m_mutex);
    }
    else if(m_pCollectorStateInfo->getInt() == STOPPED_STATE)
    {
      streamlog_out(DEBUG) << "Server is down -> Clearing subscribed me list !" << std::endl;
      pthread_mutex_lock(&m_mutex);
      m_subscribedMeList.clear();
      pthread_mutex_unlock(&m_mutex);
    }
  }
}
bool dqm4hep::DQMMonitorElementSender::isConnectedToService () const
Whether the sender is connected to the collector.
Definition at line 199 of file DQMMonitorElementSender.cc.
References m_isConnected.
Referenced by connectToService(), disconnectFromService(), setCollectorName(), and dqm4hep::DQMAnalysisModuleApplication::stopServices().
{
  return m_isConnected;
}
void dqm4hep::DQMMonitorElementSender::removeAvailableMonitorElement (const std::string & monitorElementName) [private]
Definition at line 305 of file DQMMonitorElementSender.cc.
References m_availableMeMap, and m_sendAvailableMeList.
Referenced by dqm4hep::DQMModuleApi::deleteMonitorElement().
{
  DQMMonitorElementInfoMap::iterator findIter = m_availableMeMap.find(monitorElementName);
  if(findIter == m_availableMeMap.end())
    return;
  // do it baby !
  m_availableMeMap.erase(findIter);
  // for future update on the collector side
  m_sendAvailableMeList = true;
}
void dqm4hep::DQMMonitorElementSender::sendAvailableMonitorElementList () [private]
Definition at line 321 of file DQMMonitorElementSender.cc.
References dqm4hep::ERROR, dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), dqm4hep::DQMModuleApplication::getModule(), dqm4hep::DQMModule::getName(), dqm4hep::StatusCodeException::getStatusCode(), m_availableMeMap, m_collectorName, m_dataStream, m_pApplication, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMMonitorElementInfoList::serialize(), THROW_RESULT_IF, and dqm4hep::DQMDataStream::write().
Referenced by sendMonitorElements().
{
  if(m_availableMeMap.empty())
    return;
  DQMMonitorElementInfoList monitorElementInfoList;
  for(DQMMonitorElementInfoMap::iterator iter = m_availableMeMap.begin(), endIter =
      m_availableMeMap.end() ;
      endIter != iter ; ++iter)
    monitorElementInfoList.push_back(iter->second);
  try
  {
    m_dataStream.reset();
    // first write the module name
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.write(m_pApplication->
      getModule()->getName()));
    // write the monitor element info list
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, monitorElementInfoList.serialize(&
      m_dataStream));
    // send the packet !
    std::string commandName = "DQM4HEP/MonitorElementCollector/" +
      m_collectorName + "/AVAILABLE_ME_CMD";
    DimClient::sendCommandNB(commandName.c_str() , (void *) m_dataStream.
      getBuffer() , m_dataStream.getBufferSize());
  }
  catch(const StatusCodeException &exception)
  {
    streamlog_out(ERROR) << "Couldn't send available monitor element info list : " << exception.
      getStatusCode() << std::endl;
  }
}
StatusCode dqm4hep::DQMMonitorElementSender::sendMonitorElements ()
Send the subscribed monitor element to the collector.
Definition at line 75 of file DQMMonitorElementSender.cc.
References dqm4hep::DEBUG, dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), dqm4hep::DQMModuleApplication::getModule(), dqm4hep::DQMModuleApi::getMonitorElement(), dqm4hep::DQMModule::getName(), m_collectorName, m_dataStream, m_mutex, m_pApplication, m_sendAvailableMeList, m_subscribedMeList, dqm4hep::MESSAGE, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, sendAvailableMonitorElementList(), dqm4hep::DQMMonitorElementPublication::serialize(), and dqm4hep::DQMDataStream::write().
{
  if(NULL == m_pApplication)
    return STATUS_CODE_NOT_INITIALIZED;
  if(m_sendAvailableMeList)
  {
    this->sendAvailableMonitorElementList();
    m_sendAvailableMeList = false;
  }
  std::string moduleName = m_pApplication->getModule()->getName();
  // get subscribed me list copy
  pthread_mutex_lock(&m_mutex);
  StringSet subscribedMeList = m_subscribedMeList;
  pthread_mutex_unlock(&m_mutex);
  // if nothing to send, log and return
  if(subscribedMeList.empty())
  {
    streamlog_out(MESSAGE) << "No monitor element sent !" << std::endl;
    return STATUS_CODE_SUCCESS;
  }
  DQMMonitorElementPublication publication;
  DQMMonitorElementPublication::iterator publicationIter =
      publication.insert(
          DQMMonitorElementPublication::value_type(moduleName,
      DQMMonitorElementList())).first;
  // build the publication to send
  streamlog_out(DEBUG) << "N subscribed me : " << subscribedMeList.size() << std::endl;
  for(StringSet::iterator iter = subscribedMeList.begin(), endIter = subscribedMeList.end() ;
      endIter != iter ; ++iter)
  {
    size_t pos = iter->find_last_of('/');
    streamlog_out(DEBUG) << "Full me name : " << *iter << std::endl;
    streamlog_out(DEBUG) << "Last of / pos : " << pos << std::endl;
    std::string path;
    std::string meName;
    if(pos == std::string::npos)
    {
      path = "/";
      meName = *iter;
    }
    else
    {
      path = iter->substr(0, pos+1);
      meName = iter->substr(pos+1);
    }
    streamlog_out(DEBUG) << "Me path : " << path << " , name : " << meName << std::endl;
    if(path.empty() || meName.empty())
      continue;
    DQMMonitorElement *pMonitorElement = NULL;
    if(STATUS_CODE_SUCCESS != DQMModuleApi::getMonitorElement(m_pApplication->
      getModule(), path, meName, pMonitorElement))
      continue;
    streamlog_out(DEBUG) << "Found !!" << std::endl;
    publicationIter->second.push_back(pMonitorElement);
  }
  if(publication.empty())
    return STATUS_CODE_SUCCESS;
  streamlog_out(MESSAGE) << "Number of monitor element sent : " << publicationIter->second.size() <<
      std::endl;
  // write module name
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.write(moduleName));
  // stream the whole publication
  m_dataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, publication.serialize(&m_dataStream));
  std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/COLLECT_ME_CMD";
  DimClient::sendCommandNB(commandName.c_str(), (void *)m_dataStream.getBuffer(),
      m_dataStream.getBufferSize());
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMMonitorElementSender::setCollectorName (const std::string & collectorName)
Set the collector name to which the elements will be sent.
Definition at line 60 of file DQMMonitorElementSender.cc.
References isConnectedToService(), and m_collectorName.
Referenced by dqm4hep::DQMAnalysisModuleApplication::configureNetwork(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  if(collectorName.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  if(this->isConnectedToService())
    return STATUS_CODE_NOT_ALLOWED;
  m_collectorName = collectorName;
  return STATUS_CODE_SUCCESS;
}
Friends And Related Function Documentation
friend class DQMModuleApi [friend]
Definition at line 48 of file DQMMonitorElementSender.h.
Member Data Documentation
DQMMonitorElementInfoMap dqm4hep::DQMMonitorElementSender::m_availableMeMap [private]
The available monitor element list.
Definition at line 107 of file DQMMonitorElementSender.h.
Referenced by addAvailableMonitorElement(), removeAvailableMonitorElement(), and sendAvailableMonitorElementList().
std::string dqm4hep::DQMMonitorElementSender::m_collectorName [private]
The collector name to which the monitor elements will be sent.
Definition at line 100 of file DQMMonitorElementSender.h.
Referenced by connectToService(), sendAvailableMonitorElementList(), sendMonitorElements(), and setCollectorName().
DQMDataStream dqm4hep::DQMMonitorElementSender::m_dataStream [private]
The data stream used to serialize the monitor elements.
Definition at line 102 of file DQMMonitorElementSender.h.
Referenced by sendAvailableMonitorElementList(), and sendMonitorElements().
DQMDataStream dqm4hep::DQMMonitorElementSender::m_inDataStream [private]
The data stream used to serialize dim info.
Definition at line 103 of file DQMMonitorElementSender.h.
Referenced by connectToService(), and infoHandler().
bool dqm4hep::DQMMonitorElementSender::m_isConnected [private]
Whether the sender is connected to the collector.
Definition at line 110 of file DQMMonitorElementSender.h.
Referenced by connectToService(), disconnectFromService(), and isConnectedToService().
pthread_mutex_t dqm4hep::DQMMonitorElementSender::m_mutex [private]
Mutex to lock unlock on service update.
Definition at line 108 of file DQMMonitorElementSender.h.
Referenced by DQMMonitorElementSender(), infoHandler(), sendMonitorElements(), and ~DQMMonitorElementSender().
DQMModuleApplication* dqm4hep::DQMMonitorElementSender::m_pApplication [private]
The module application that sends elements to the collector.
Definition at line 99 of file DQMMonitorElementSender.h.
Referenced by addAvailableMonitorElement(), sendAvailableMonitorElementList(), and sendMonitorElements().
DimUpdatedInfo* dqm4hep::DQMMonitorElementSender::m_pCollectorStateInfo [private]
The dim info to receive when the collector state changes.
Definition at line 113 of file DQMMonitorElementSender.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
DimUpdatedInfo* dqm4hep::DQMMonitorElementSender::m_pSubscribedListInfo [private]
The dim info to receive subscribed me list from collector.
Definition at line 112 of file DQMMonitorElementSender.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
bool dqm4hep::DQMMonitorElementSender::m_sendAvailableMeList [private]
Whether the list of available me has to be re-sent to the collector.
Definition at line 109 of file DQMMonitorElementSender.h.
Referenced by addAvailableMonitorElement(), infoHandler(), removeAvailableMonitorElement(), and sendMonitorElements().
StringSet dqm4hep::DQMMonitorElementSender::m_subscribedMeList [private]
The subscribed monitor element list.
Definition at line 106 of file DQMMonitorElementSender.h.
Referenced by infoHandler(), and sendMonitorElements().
The documentation for this class was generated from the following files:
DQMMonitorElementSender.h
DQMMonitorElementSender.cc