dqm4hep::DQMEventCollectorImp Class Reference
DQMEventCollectorImp class.
#include <DQMEventCollectorImp.h>
Public Member Functions
virtual ~DQMEventCollectorImp ()
Destructor.
virtual StatusCode setCollectorName (const std::string &collectorName)=0
Set the collector name.
virtual const std::string & getCollectorName () const =0
Get the collector name.
virtual bool isRunning () const =0
Whether the collector server is running.
virtual StatusCode startCollector ()=0
Start the collector server.
virtual StatusCode stopCollector ()=0
Stop the collector server.
virtual void setEventStreamer (DQMEventStreamer *pEventStreamer)=0
Set the event streamer to serialize/deserialize the in/out-coming events.
virtual DQMEventStreamer * getEventStreamer () const =0
Get the event streamer.
Detailed Description
DQMEventCollectorImp class.
Definition at line 39 of file DQMEventCollectorImp.h.
Constructor & Destructor Documentation
virtual dqm4hep::DQMEventCollectorImp::~DQMEventCollectorImp () [inline], [virtual]
Destructor.
Definition at line 44 of file DQMEventCollectorImp.h.
{}
Member Function Documentation
virtual const std::string& dqm4hep::DQMEventCollectorImp::getCollectorName () const [pure virtual]
Get the collector name.
Implemented in dqm4hep::DQMDimEventCollector .
Referenced by dqm4hep::DQMEventCollector::getCollectorName().
virtual DQMEventStreamer* dqm4hep::DQMEventCollectorImp::getEventStreamer () const [pure virtual]
Get the event streamer.
Implemented in dqm4hep::DQMDimEventCollector .
Referenced by dqm4hep::DQMEventCollector::getEventStreamer().
virtual bool dqm4hep::DQMEventCollectorImp::isRunning () const [pure virtual]
Whether the collector server is running.
Implemented in dqm4hep::DQMDimEventCollector .
Referenced by dqm4hep::DQMEventCollector::isRunning().
virtual StatusCode dqm4hep::DQMEventCollectorImp::setCollectorName (const std::string & collectorName) [pure virtual]
Set the collector name.
Implemented in dqm4hep::DQMDimEventCollector .
Referenced by dqm4hep::DQMEventCollector::setCollectorName().
virtual void dqm4hep::DQMEventCollectorImp::setEventStreamer (DQMEventStreamer * pEventStreamer) [pure virtual]
Set the event streamer to serialize/deserialize the in/out-coming events.
Implemented in dqm4hep::DQMDimEventCollector .
Referenced by dqm4hep::DQMEventCollector::setEventStreamer().
virtual StatusCode dqm4hep::DQMEventCollectorImp::startCollector () [pure virtual]
Start the collector server.
Implemented in dqm4hep::DQMDimEventCollector .
Referenced by dqm4hep::DQMEventCollector::startCollector().
virtual StatusCode dqm4hep::DQMEventCollectorImp::stopCollector () [pure virtual]
Stop the collector server.
Implemented in dqm4hep::DQMDimEventCollector .
Referenced by dqm4hep::DQMEventCollector::stopCollector().
The documentation for this class was generated from the following file:
DQMEventCollectorImp.h