dqm4hep::DQMRun Class Reference
DQMRun class.
#include <DQMRun.h>
Public Member Functions
DQMRun (int runNumber=0, const std::string &description=``, const std::string &detectorName=``)
Constructor with run number (optional)
~DQMRun ()
Destructor.
int getRunNumber () const
Get the run number.
time_t getStartTime () const
Get the start time.
time_t getEndTime () const
Get the end time.
const std::string & getDescription () const
Get the run description.
const std::string & getDetectorName () const
Get the detector name related to this run.
void setRunNumber (int runNumber)
Set the run number.
void setStartTime (time_t startTime)
Set the start time.
void setEndTime (time_t endTime)
Set the end time.
void setDescription (const std::string &description)
Set the run description.
void setDetectorName (const std::string &detectorName)
Set the detector name related to this run.
template<typename T >
void setParameter (const std::string &key, const T &value)
Set a parameter.
template<typename T >
void getParameter (const std::string &key, T &value) const
Get a parameter.
unsigned int getNParameters () const
Get the number of parameters.
StatusCode serialize (DQMDataStream *const pDataStream) const
Serialize the object and store the result in the data stream.
StatusCode deserialize (DQMDataStream *const pDataStream)
Deserialize the object from the data stream.
Protected Attributes
int m_runNumber
time_t m_startTime
time_t m_endTime
std::string m_detectorName
std::string m_description
std::map< std::string,
*
std::string > m_parametersMap
Detailed Description
DQMRun class.
Definition at line 45 of file DQMRun.h.
Constructor & Destructor Documentation
dqm4hep::DQMRun::DQMRun (int runNumber = 0, const std::string & description = ``, const std::string & detectorName = ``)
Constructor with run number (optional)
Definition at line 37 of file DQMRun.cc.
                                                                                         :
    m_runNumber(runNumber),
    m_description(description),
    m_detectorName(detectorName),
    m_startTime(time(0)),
    m_endTime(0)
{
  /* nop */
}
dqm4hep::DQMRun::~DQMRun ()
Destructor.
Definition at line 49 of file DQMRun.cc.
{
  /* nop */
}
Member Function Documentation
StatusCode dqm4hep::DQMRun::deserialize (DQMDataStream *const pDataStream) [virtual]
Deserialize the object from the data stream.
Implements dqm4hep::DQMStreamable .
Definition at line 77 of file DQMRun.cc.
References m_description, m_detectorName, m_endTime, m_parametersMap, m_runNumber, m_startTime, dqm4hep::DQMDataStream::read(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMDimRunControlClient::handleCurrentRunRpcInfo().
{
  dqm_int runNumber = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(runNumber));
  m_runNumber = runNumber;
  dqm_uint startTime = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(startTime));
  m_startTime = startTime;
  dqm_uint endTime = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(endTime));
  m_endTime = endTime;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(m_detectorName));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(m_description));
  dqm_uint nParameters = 0;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(nParameters));
  for(unsigned int i=0 ; i<nParameters ; i++)
  {
    std::string key;
    std::string value;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(key));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->read(value));
    m_parametersMap[key] = value;
  }
  return STATUS_CODE_SUCCESS;
}
const std::string & dqm4hep::DQMRun::getDescription () const [inline]
Get the run description.
Definition at line 150 of file DQMRun.h.
References m_description.
{
  return m_description;
}
const std::string & dqm4hep::DQMRun::getDetectorName () const [inline]
Get the detector name related to this run.
Definition at line 157 of file DQMRun.h.
References m_detectorName.
{
  return m_detectorName;
}
time_t dqm4hep::DQMRun::getEndTime () const [inline]
Get the end time.
Definition at line 143 of file DQMRun.h.
References m_endTime.
{
  return m_endTime;
}
unsigned int dqm4hep::DQMRun::getNParameters () const [inline]
Get the number of parameters.
Definition at line 220 of file DQMRun.h.
References m_parametersMap.
{
  return m_parametersMap.size();
}
template<typename T > void dqm4hep::DQMRun::getParameter (const std::string & key, T & value) const [inline]
Get a parameter.
The value is converted into asked type. If the parameter is not found, the value remains unchanged
Definition at line 208 of file DQMRun.h.
References m_parametersMap, and dqm4hep::DQM4HEP::stringToType().
{
  std::map<std::string, std::string>::const_iterator findIter = m_parametersMap.find(key);
  if(m_parametersMap.end() == findIter)
    return;
  DQM4HEP::stringToType(findIter->second, value);
}
int dqm4hep::DQMRun::getRunNumber () const [inline]
Get the run number.
Definition at line 129 of file DQMRun.h.
References m_runNumber.
Referenced by dqm4hep::DQMRunControl::getCurrentRunNumber(), dqm4hep::DQMDimRunControlClient::handleCurrentRunRpcInfo(), dqm4hep::DQMAnalysisModuleApplication::run(), and dqm4hep::DQMRunControlService::startNewRun().
{
  return m_runNumber;
}
time_t dqm4hep::DQMRun::getStartTime () const [inline]
Get the start time.
Definition at line 136 of file DQMRun.h.
References m_startTime.
{
  return m_startTime;
}
StatusCode dqm4hep::DQMRun::serialize (DQMDataStream *const pDataStream) const [virtual]
Serialize the object and store the result in the data stream.
Implements dqm4hep::DQMStreamable .
Definition at line 56 of file DQMRun.cc.
References m_description, m_detectorName, m_endTime, m_parametersMap, m_runNumber, m_startTime, RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
Referenced by dqm4hep::DQMRunControlService::endCurrentRun(), dqm4hep::DQMRunControlService::handleCurrentRunRpc(), and dqm4hep::DQMRunControlService::startNewRun().
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(static_cast<dqm_int>(
      m_runNumber)));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(static_cast<dqm_uint>(
      m_startTime)));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(static_cast<dqm_uint>(
      m_endTime)));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(m_detectorName));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(m_description));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(static_cast<dqm_uint>(this->getNParameters()
      )));
  for(std::map<std::string, std::string>::const_iterator iter = m_parametersMap.begin(), endIter =
      m_parametersMap.end() ;
      endIter != iter ; ++iter)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(iter->first));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDataStream->write(iter->second));
  }
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMRun::setDescription (const std::string & description) [inline]
Set the run description.
Definition at line 185 of file DQMRun.h.
References m_description.
{
  m_description = description;
}
void dqm4hep::DQMRun::setDetectorName (const std::string & detectorName) [inline]
Set the detector name related to this run.
Definition at line 192 of file DQMRun.h.
References m_detectorName.
{
  m_detectorName = detectorName;
}
void dqm4hep::DQMRun::setEndTime (time_t endTime) [inline]
Set the end time.
Definition at line 178 of file DQMRun.h.
References m_endTime.
Referenced by dqm4hep::DQMRunControlService::endCurrentRun(), and dqm4hep::DQMAnalysisModuleApplication::run().
{
  m_endTime = endTime;
}
template<typename T > void dqm4hep::DQMRun::setParameter (const std::string & key, const T & value) [inline]
Set a parameter.
The template value is converted into string
Definition at line 200 of file DQMRun.h.
References m_parametersMap.
{
  m_parametersMap[key] = DQM4HEP::typeToString<T>(value);
}
void dqm4hep::DQMRun::setRunNumber (int runNumber) [inline]
Set the run number.
Definition at line 164 of file DQMRun.h.
References m_runNumber.
{
  m_runNumber = runNumber;
}
void dqm4hep::DQMRun::setStartTime (time_t startTime) [inline]
Set the start time.
Definition at line 171 of file DQMRun.h.
References m_startTime.
{
  m_startTime = startTime;
}
Member Data Documentation
std::string dqm4hep::DQMRun::m_description [protected]
Definition at line 122 of file DQMRun.h.
Referenced by deserialize(), getDescription(), serialize(), and setDescription().
std::string dqm4hep::DQMRun::m_detectorName [protected]
Definition at line 121 of file DQMRun.h.
Referenced by deserialize(), getDetectorName(), serialize(), and setDetectorName().
time_t dqm4hep::DQMRun::m_endTime [protected]
Definition at line 120 of file DQMRun.h.
Referenced by deserialize(), getEndTime(), serialize(), and setEndTime().
std::map<std::string, std::string> dqm4hep::DQMRun::m_parametersMap [protected]
Definition at line 123 of file DQMRun.h.
Referenced by deserialize(), getNParameters(), getParameter(), serialize(), and setParameter().
int dqm4hep::DQMRun::m_runNumber [protected]
Definition at line 118 of file DQMRun.h.
Referenced by deserialize(), getRunNumber(), serialize(), and setRunNumber().
time_t dqm4hep::DQMRun::m_startTime [protected]
Definition at line 119 of file DQMRun.h.
Referenced by deserialize(), getStartTime(), serialize(), and setStartTime().
The documentation for this class was generated from the following files:
DQMRun.h
DQMRun.cc