dqm4hep::DQMStandaloneModuleApplication Class Reference
DQMStandaloneModuleApplication class.
#include <DQMStandaloneModuleApplication.h>
Classes
class Settings
Settings class.
Public Member Functions
DQMStandaloneModuleApplication ()
Constructor.
~DQMStandaloneModuleApplication ()
Destructor.
const std::string & getType () const
Get the application type (`StandaloneModule`)
const std::string & getName () const
Get the application name (module name)
StatusCode readSettings (const std::string &settingsFile)
Read settings from a xml file.
StatusCode run ()
Run the application.
Private Member Functions
void onEventProcessed (const DQMCycle *const pCycle, const DQMEvent *const pEvent)
Call back function when an event is processed by the framework.
void onCycleStarted (const DQMCycle *const pCycle)
Call back function when the cycle is started by the framework.
void onCycleStopped (const DQMCycle *const pCycle)
Call back function when the cycle is stopped by the framework.
Private Attributes
bool m_stopFlag
bool m_isInitialized
DQMTimerCycle * m_pTimerCycle
DQMArchiver * m_pArchiver
Settings m_settings
std::string m_name
std::string m_type
StatusCode m_returnStatusCode
Additional Inherited Members
Detailed Description
DQMStandaloneModuleApplication class.
Definition at line 45 of file DQMStandaloneModuleApplication.h.
Constructor & Destructor Documentation
dqm4hep::DQMStandaloneModuleApplication::DQMStandaloneModuleApplication ()
Constructor.
Definition at line 52 of file DQMStandaloneModuleApplication.cc.
References dqm4hep::DQMModuleApplication::DQMArchiver, and m_pArchiver.
                                                               :
    DQMModuleApplication(),
    m_pTimerCycle(NULL),
    m_type("StandaloneModule"),
    m_name("Unknown"),
    m_returnStatusCode(STATUS_CODE_SUCCESS)
{
  m_pArchiver = new DQMArchiver();
}
dqm4hep::DQMStandaloneModuleApplication::~DQMStandaloneModuleApplication ()
Destructor.
Definition at line 64 of file DQMStandaloneModuleApplication.cc.
References m_pArchiver, and m_pTimerCycle.
{
  if(m_pTimerCycle)
    delete m_pTimerCycle;
  delete m_pArchiver;
}
Member Function Documentation
const std::string & dqm4hep::DQMStandaloneModuleApplication::getName () const [virtual]
Get the application name (module name)
Implements dqm4hep::DQMModuleApplication .
Definition at line 81 of file DQMStandaloneModuleApplication.cc.
References m_name.
{
  return m_name;
}
const std::string & dqm4hep::DQMStandaloneModuleApplication::getType () const [virtual]
Get the application type (`StandaloneModule`)
Implements dqm4hep::DQMModuleApplication .
Definition at line 74 of file DQMStandaloneModuleApplication.cc.
References m_type.
{
  return m_type;
}
void dqm4hep::DQMStandaloneModuleApplication::onCycleStarted (const DQMCycle *const pCycle) [private], [virtual]
Call back function when the cycle is started by the framework.
Implements dqm4hep::DQMCycleListener .
Definition at line 337 of file DQMStandaloneModuleApplication.cc.
References dqm4hep::DQMModuleApplication::getModule(), and THROW_RESULT_IF.
{
  THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->startOfCycle());
}
void dqm4hep::DQMStandaloneModuleApplication::onCycleStopped (const DQMCycle *const pCycle) [private], [virtual]
Call back function when the cycle is stopped by the framework.
Implements dqm4hep::DQMCycleListener .
Definition at line 344 of file DQMStandaloneModuleApplication.cc.
References dqm4hep::DQMModuleApplication::getModule(), and THROW_RESULT_IF.
{
  THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->endOfCycle());
}
void dqm4hep::DQMStandaloneModuleApplication::onEventProcessed (const DQMCycle *const pCycle, const DQMEvent *const pEvent) [inline], [private], [virtual]
Call back function when an event is processed by the framework.
Implements dqm4hep::DQMCycleListener .
Definition at line 103 of file DQMStandaloneModuleApplication.h.
{ /* nop */ }
StatusCode dqm4hep::DQMStandaloneModuleApplication::readSettings (const std::string & settingsFile) [virtual]
Read settings from a xml file.
Initialize the application. Declare all the services, load the shared libraries, configure the active module
Implements dqm4hep::DQMModuleApplication .
Definition at line 88 of file DQMStandaloneModuleApplication.cc.
References dqm4hep::DQMCycle::addListener(), dqm4hep::DQMFileHandlerFactory::createFileHandler(), dqm4hep::DQMPluginManager::createPluginClass(), dqm4hep::DEBUG, dqm4hep::DQMFileHandler::download(), dqm4hep::TiXmlHandle::Element(), dqm4hep::ERROR, dqm4hep::TiXmlHandle::FirstChildElement(), dqm4hep::DQMXmlHelper::getAttribute(), dqm4hep::DQMFileHandler::getLocalFileName(), dqm4hep::DQMModuleApplication::getModule(), dqm4hep::DQMModuleApplication::getModuleName(), dqm4hep::DQMModuleApplication::getModuleType(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMModule::getName(), dqm4hep::StatusCodeException::getStatusCode(), dqm4hep::DQMSingleton< DQMPluginManager >::instance(), dqm4hep::DQMModuleApplication::isInitialized(), dqm4hep::TiXmlDocument::LoadFile(), dqm4hep::DQMStandaloneModuleApplication::Settings::m_archiveDirectory, dqm4hep::DQMStandaloneModuleApplication::Settings::m_cyclePeriod, dqm4hep::DQMStandaloneModuleApplication::Settings::m_moduleName, dqm4hep::DQMStandaloneModuleApplication::Settings::m_moduleType, dqm4hep::DQMStandaloneModuleApplication::Settings::m_monitorElementCollector, m_name, dqm4hep::DQMStandaloneModuleApplication::Settings::m_openArchive, m_pTimerCycle, m_settings, dqm4hep::DQMStandaloneModuleApplication::Settings::m_settingsFileName, dqm4hep::DQMStandaloneModuleApplication::Settings::m_sleepTime, dqm4hep::MESSAGE, dqm4hep::DQMStandaloneModuleApplication::Settings::print(), RETURN_RESULT_IF, dqm4hep::DQMMonitorElementSender::setCollectorName(), dqm4hep::DQMCycle::setCycleValue(), dqm4hep::DQMModuleApplication::setInitialized(), dqm4hep::DQMModuleApplication::setModule(), dqm4hep::DQMModuleApplication::setModuleName(), dqm4hep::DQMModuleApplication::setModuleType(), dqm4hep::DQMCycle::setTimeout(), and THROW_RESULT_IF.
{
  if(this->isInitialized())
    return STATUS_CODE_ALREADY_INITIALIZED;
  size_t splitterPosition = settingsFileName.find(":");
  std::string fileHandlerType;
  std::string filePattern;
  if(splitterPosition != std::string::npos)
  {
    fileHandlerType = settingsFileName.substr(0, splitterPosition);
    filePattern = settingsFileName.substr(splitterPosition+1);
  }
  else
  {
    fileHandlerType = "";
    filePattern = settingsFileName;
  }
  streamlog_out(DEBUG) << "File handler type : " << fileHandlerType << std::endl;
  DQMFileHandlerFactory fileHandlerFactory;
  DQMFileHandler *pFileHandler = fileHandlerFactory.createFileHandler(fileHandlerType);
  if(!pFileHandler)
    return STATUS_CODE_FAILURE;
  StatusCode statusCode = pFileHandler->download(filePattern);
  if(statusCode != STATUS_CODE_SUCCESS)
  {
    delete pFileHandler;
    return statusCode;
  }
  m_settings.m_settingsFileName = pFileHandler->getLocalFileName();
  delete pFileHandler;
    TiXmlDocument xmlDocument(m_settings.m_settingsFileName);
    if (!xmlDocument.LoadFile())
    {
        std::cout << "DQMAnalysisModuleApplication::readSettings - Invalid xml file." << std::endl;
        return STATUS_CODE_FAILURE;
    }
    const TiXmlHandle xmlDocumentHandle(&xmlDocument);
    const TiXmlHandle xmlHandle = TiXmlHandle(xmlDocumentHandle.FirstChildElement().Element());
    // monitor element sender
  TiXmlElement *const pMeCollectorElement = xmlHandle.FirstChildElement("monitorelementcollector").Element(
      );
  if(NULL == pMeCollectorElement)
  {
    streamlog_out(ERROR) << "<monitorelementcollector> element not found !" << std::endl;
    return STATUS_CODE_NOT_FOUND;
  }
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pMeCollectorElement, "name",
      m_settings.m_monitorElementCollector));
  this->getMonitorElementSender()->setCollectorName(m_settings.
      m_monitorElementCollector);
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->connectToService());
  // cycle
  TiXmlElement *const pCycleElement = xmlHandle.FirstChildElement("cycle").Element();
  if(pCycleElement)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pCycleElement, "sleep",
      m_settings.m_sleepTime));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pCycleElement, "period",
      m_settings.m_cyclePeriod));
  }
  m_pTimerCycle = new DQMTimerCycle();
  m_pTimerCycle->setCycleValue(m_settings.m_cyclePeriod);
  m_pTimerCycle->setTimeout(0);
  m_pTimerCycle->addListener(this);
  // module
  TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("module").Element();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "type",
      m_settings.m_moduleType));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "name",
      m_settings.m_moduleName));
  if(this->getModuleType().empty())
    this->setModuleType(m_settings.m_moduleType);
  if(this->getModuleName().empty())
    this->setModuleName(m_settings.m_moduleName);
  streamlog_out(MESSAGE) << "Query standalone module to PluginManager ... " << std::endl;
  DQMStandaloneModule *pStandaloneModule = DQMPluginManager::instance()->
      createPluginClass<DQMStandaloneModule>(this->getModuleType());
  if(!pStandaloneModule)
    return STATUS_CODE_FAILURE;
  this->setModule(pStandaloneModule);
  streamlog_out(MESSAGE) << "Query standalone module to PluginManager ... OK" << std::endl;
  TiXmlHandle moduleHandle(pXmlElement);
  streamlog_out(MESSAGE) << "Reading settings of active module '" << this->
      getModule()->getName() << "' ..." << std::endl;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->readSettings(moduleHandle));
  streamlog_out(MESSAGE) << "Reading settings of active module '" << this->
      getModule()->getName() << "' ... OK" << std::endl;
  streamlog_out(MESSAGE) << "Initializing active module '" << this->getModule()->
      getName() << "' ..." << std::endl;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->initModule());
  streamlog_out(MESSAGE) << "Initializing active module '" << this->getModule()->
      getName() << "' ... OK" << std::endl;
  try
  {
    streamlog_out(MESSAGE) << "Configuring archiver ..." << std::endl;
    const TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("archiver").Element();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "open",
      m_settings.m_openArchive));
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "directory",
      m_settings.m_archiveDirectory));
    streamlog_out(MESSAGE) << "Configuring archiver ... OK" << std::endl;
  }
  catch(const StatusCodeException &exception)
  {
    return exception.getStatusCode();
  }
  m_name = this->getModule()->getName();
  DimBrowser browser;
  int nServers = browser.getServers();
  std::string moduleServerName = "DQM4HEP/Module/" + this->getModule()->getName();
  if(nServers)
  {
    char *serverName;
    char *node;
    while(browser.getNextServer(serverName, node))
    {
      if(moduleServerName == serverName)
      {
        streamlog_out(ERROR) << "Module '" << this->getModule()->getName() << "' already registered over
       the network.\n"
            << "Please, change the module name or stop the other module application with the same name !" <
      < std::endl;
        return STATUS_CODE_ALREADY_PRESENT;
      }
    }
  }
  DimServer::start(moduleServerName.c_str());
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->connectToService());
  this->setInitialized(true);
  m_settings.print();
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMStandaloneModuleApplication::run () [virtual]
Run the application.
Implements dqm4hep::DQMModuleApplication .
Definition at line 262 of file DQMStandaloneModuleApplication.cc.
References dqm4hep::DQMArchiver::archive(), dqm4hep::DQMArchiver::close(), dqm4hep::DQMModule::endModule(), dqm4hep::DQMArchiver::getFileName(), dqm4hep::DQMModuleApplication::getModule(), dqm4hep::DQMModuleApplication::getMonitorElementSender(), dqm4hep::DQMTimerCycle::isEndOfCycleReached(), dqm4hep::DQMModuleApplication::isInitialized(), dqm4hep::DQMStandaloneModuleApplication::Settings::m_archiveDirectory, dqm4hep::DQMStandaloneModuleApplication::Settings::m_moduleName, dqm4hep::DQMStandaloneModuleApplication::Settings::m_openArchive, m_pArchiver, m_pTimerCycle, m_settings, dqm4hep::DQMStandaloneModuleApplication::Settings::m_sleepTime, dqm4hep::MESSAGE, dqm4hep::DQMArchiver::open(), dqm4hep::DQMStandaloneModule::process(), RETURN_RESULT_IF, dqm4hep::DQMModuleApplication::shouldStopApplication(), dqm4hep::DQMCycle::startCycle(), and dqm4hep::DQMCycle::stopCycle().
{
  if(!this->isInitialized())
    return STATUS_CODE_NOT_INITIALIZED;
  bool callStartOfCycle = true;
  // get casted module for easier manipulation
  DQMStandaloneModule *pStandaloneModule = dynamic_cast<DQMStandaloneModule *>(this->
      getModule());
  // open an archive
  if(m_settings.m_openArchive)
  {
    std::stringstream archiveFileName;
    std::string directory =
        m_settings.m_archiveDirectory.at(m_settings.m_archiveDirectory.size() - 1) == '/' ?
            m_settings.m_archiveDirectory : m_settings.m_archiveDirectory + "/";
    archiveFileName << directory
        << "DQMArchive"
        << "_M" << m_settings.m_moduleName;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->open(archiveFileName.str(), "RECREATE"));
    streamlog_out(MESSAGE) << "Archive '" << m_pArchiver->getFileName() << "' opened" << std::endl;
  }
  while(!this->shouldStopApplication())
  {
    // process a cycle
    streamlog_out(MESSAGE) << "**************************************************" << std::endl;
    streamlog_out(MESSAGE) << "*** Start of cycle ***" << std::endl;
    streamlog_out(MESSAGE) << "**************************************************" << std::endl;
    m_pTimerCycle->startCycle();
    while(1)
    {
      if(m_pTimerCycle->isEndOfCycleReached())
        break;
      if(this->shouldStopApplication())
        break;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pStandaloneModule->process());
      usleep(m_settings.m_sleepTime);
    }
    m_pTimerCycle->stopCycle();
    streamlog_out(MESSAGE) << "**************************************************" << std::endl;
    streamlog_out(MESSAGE) << "*** End of cycle reached ***" << std::endl;
    streamlog_out(MESSAGE) << "**************************************************" << std::endl;
    streamlog_out(MESSAGE) << "Sending monitor elements to collector" << std::endl;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->sendMonitorElements());
    // archive publication if user asked for
    if(m_settings.m_openArchive)
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->archive(pStandaloneModule));
  }
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pStandaloneModule->endModule());
  // archive the monitor element if archive is opened
  if(m_settings.m_openArchive)
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->close());
  return STATUS_CODE_SUCCESS;
}
Member Data Documentation
bool dqm4hep::DQMStandaloneModuleApplication::m_isInitialized [private]
Definition at line 109 of file DQMStandaloneModuleApplication.h.
std::string dqm4hep::DQMStandaloneModuleApplication::m_name [private]
Definition at line 118 of file DQMStandaloneModuleApplication.h.
Referenced by getName(), and readSettings().
DQMArchiver* dqm4hep::DQMStandaloneModuleApplication::m_pArchiver [private]
Definition at line 113 of file DQMStandaloneModuleApplication.h.
Referenced by DQMStandaloneModuleApplication(), run(), and ~DQMStandaloneModuleApplication().
DQMTimerCycle* dqm4hep::DQMStandaloneModuleApplication::m_pTimerCycle [private]
Definition at line 112 of file DQMStandaloneModuleApplication.h.
Referenced by readSettings(), run(), and ~DQMStandaloneModuleApplication().
StatusCode dqm4hep::DQMStandaloneModuleApplication::m_returnStatusCode [private]
Definition at line 121 of file DQMStandaloneModuleApplication.h.
Settings dqm4hep::DQMStandaloneModuleApplication::m_settings [private]
Definition at line 116 of file DQMStandaloneModuleApplication.h.
Referenced by readSettings(), and run().
bool dqm4hep::DQMStandaloneModuleApplication::m_stopFlag [private]
Definition at line 108 of file DQMStandaloneModuleApplication.h.
std::string dqm4hep::DQMStandaloneModuleApplication::m_type [private]
Definition at line 119 of file DQMStandaloneModuleApplication.h.
Referenced by getType().
The documentation for this class was generated from the following files:
DQMStandaloneModuleApplication.h
DQMStandaloneModuleApplication.cc