dqm4hep::DQMDirectory Class Reference
DQMDirectory class.
#include <DQMDirectory.h>
Public Member Functions
DQMDirectory ()
Default constructor.
DQMDirectory (const std::string &name, DQMDirectory *pParentDir=NULL)
Constructor with name and parent dir.
~DQMDirectory ()
Destructor.
StatusCode mkdir (const std::string &dirName)
Create a new directory.
void ls (bool recursive=false) const
List the directory contents and subdirs if asked.
const std::string & getName () const
Returns the directory name.
DQMDirectory * getParentDir () const
Returns the parent directory.
const std::vector
*
< DQMDirectory * > & getSubDirList () const
Get the sub directory list.
bool containsDir (const std::string &dirName) const
Whether the directory contains the sub dir.
StatusCode findDir (const std::string &dirName, DQMDirectory *&pDirectory) const
Find the sub directory by name.
StatusCode addMonitorElement (DQMMonitorElement *pMonitorElement)
Add a monitor elements to the directory.
StatusCode findMonitorElement (const std::string &name, DQMMonitorElement *&pMonitorElement) const
Find a monitor element with a given name in the directory.
bool containsMonitorElement (const DQMMonitorElement *pMonitorElement) const
Whether the directory contains the monitor element (search by ptr compare)
bool containsMonitorElement (const std::string &monitorElementName) const
Whether the directory contains the monitor element (search by name compare)
StatusCode removeMonitorElement (DQMMonitorElement *pMonitorElement)
Remove the monitor element from the directory.
StatusCode removeMonitorElement (const std::string &monitorElementName)
Remove the monitor element from the directory.
const std::vector
*
< DQMMonitorElement * > & getMonitorElementList () const
Get the monitor element list.
StatusCode removeDir (const std::string &dirName, bool deepClean=false)
Remove the directory and its contents Delete monitor element if deepClean set to true.
StatusCode clear (bool deepClean=false)
Clear the directory by calling delete on each sub-dirs and clear the monitor element list by calling delete if asked.
DQMPath getFullPathName () const
Get the full path name of the directory.
bool isRootDir () const
Whether the directory is a root directory.
bool isEmpty () const
Whether the directory is empty.
Private Member Functions
void ls (int depth) const
Recursive print of sub directory structure (dirs and contents)
Private Attributes
std::string m_name
DQMDirectory * m_pParentDir
std::vector< DQMDirectory * > m_directoryList
std::vector< DQMMonitorElement * > m_contentsList
Detailed Description
DQMDirectory class.
A directory is the owner of its sub-directories. Monitor elements owning depends on how the method are called (default : not owner)
This interface doesn't allow moving sub-directories
Definition at line 49 of file DQMDirectory.h.
Constructor & Destructor Documentation
dqm4hep::DQMDirectory::DQMDirectory ()
Default constructor.
Definition at line 37 of file DQMDirectory.cc.
Referenced by mkdir().
                           :
  m_name(""),
  m_pParentDir(NULL)
{
  /* nop */
}
dqm4hep::DQMDirectory::DQMDirectory (const std::string & name, DQMDirectory * pParentDir = NULL)
Constructor with name and parent dir.
Definition at line 46 of file DQMDirectory.cc.
                                                                          :
  m_name(name),
  m_pParentDir(pParentDir)
{
  /* nop */
}
dqm4hep::DQMDirectory::~DQMDirectory ()
Destructor.
Delete the subdirectories but not the contents
Definition at line 55 of file DQMDirectory.cc.
References clear().
{
  clear();
}
Member Function Documentation
StatusCode dqm4hep::DQMDirectory::addMonitorElement (DQMMonitorElement * pMonitorElement)
Add a monitor elements to the directory.
Definition at line 175 of file DQMDirectory.cc.
References containsMonitorElement(), and m_contentsList.
Referenced by dqm4hep::DQMStorage::addMonitorElement().
{
  if(NULL == pMonitorElement)
    return STATUS_CODE_INVALID_PTR;
  if(containsMonitorElement(pMonitorElement))
    return STATUS_CODE_ALREADY_PRESENT;
  m_contentsList.push_back(pMonitorElement);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDirectory::clear (bool deepClean = false)
Clear the directory by calling delete on each sub-dirs and clear the monitor element list by calling delete if asked.
The operation is done recursively
Definition at line 282 of file DQMDirectory.cc.
References clear(), m_contentsList, m_directoryList, and RETURN_RESULT_IF.
Referenced by clear(), dqm4hep::DQMStorage::clear(), removeDir(), and ~DQMDirectory().
{
  if(deepClean)
  {
    for(std::vector<DQMMonitorElement*>::const_iterator iter = m_contentsList.begin(), endIter =
      m_contentsList.end() ;
        endIter != iter ; ++iter)
    {
      DQMMonitorElement *pMonitorElement = *iter;
      delete pMonitorElement;
    }
  }
  m_contentsList.clear();
  for(std::vector<DQMDirectory*>::iterator iter = m_directoryList.begin(), endIter =
      m_directoryList.end() ;
      endIter != iter ; ++iter)
  {
    DQMDirectory *pDirectory = *iter;
    // clear recursively the sub dir
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDirectory->clear(deepClean));
    // delete ptr
    delete pDirectory;
  }
  m_directoryList.clear();
  return STATUS_CODE_SUCCESS;
}
bool dqm4hep::DQMDirectory::containsDir (const std::string & dirName) const
Whether the directory contains the sub dir.
Definition at line 135 of file DQMDirectory.cc.
References dqm4hep::DQMCoreTool::containsSpecialCharacters(), getName(), and m_directoryList.
Referenced by mkdir(), and dqm4hep::DQMStorage::mkdir().
{
  if(dirName.find("/") != std::string::npos ||
      DQMCoreTool::containsSpecialCharacters(dirName) || dirName.empty())
    return false;
  for(std::vector<DQMDirectory*>::const_iterator iter = m_directoryList.begin(), endIter =
      m_directoryList.end() ;
      endIter != iter ; ++iter)
  {
    DQMDirectory *pDirectory = *iter;
    if(pDirectory->getName() == dirName)
      return true;
  }
  return false;
}
bool dqm4hep::DQMDirectory::containsMonitorElement (const DQMMonitorElement * pMonitorElement) const
Whether the directory contains the monitor element (search by ptr compare)
Definition at line 212 of file DQMDirectory.cc.
References dqm4hep::DQMMonitorElement::getName().
Referenced by addMonitorElement(), and dqm4hep::DQMStorage::monitorElementExists().
{
  return containsMonitorElement(pMonitorElement->getName());
}
bool dqm4hep::DQMDirectory::containsMonitorElement (const std::string & monitorElementName) const
Whether the directory contains the monitor element (search by name compare)
Definition at line 219 of file DQMDirectory.cc.
References findMonitorElement().
{
  DQMMonitorElement *pMonitorElement = NULL;
  return findMonitorElement(monitorElementName, pMonitorElement) == STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDirectory::findDir (const std::string & dirName, DQMDirectory *& pDirectory) const
Find the sub directory by name.
Definition at line 154 of file DQMDirectory.cc.
References getName(), and m_directoryList.
Referenced by dqm4hep::DQMStorage::cd(), dqm4hep::DQMStorage::findDir(), and dqm4hep::DQMStorage::mkdir().
{
  pDirectory = NULL;
  for(std::vector<DQMDirectory*>::const_iterator iter = m_directoryList.begin(), endIter =
      m_directoryList.end() ;
      endIter != iter ; ++iter)
  {
    DQMDirectory *pDir = *iter;
    if(pDir->getName() == dirName)
    {
      pDirectory = pDir;
      return STATUS_CODE_SUCCESS;
    }
  }
  return STATUS_CODE_NOT_FOUND;
}
StatusCode dqm4hep::DQMDirectory::findMonitorElement (const std::string & name, DQMMonitorElement *& pMonitorElement) const
Find a monitor element with a given name in the directory.
Definition at line 190 of file DQMDirectory.cc.
References dqm4hep::DQMMonitorElement::getName(), and m_contentsList.
Referenced by containsMonitorElement(), dqm4hep::DQMStorage::getMonitorElement(), and dqm4hep::DQMStorage::removeMonitorElement().
{
  pMonitorElement = NULL;
  // print contents first
  for(std::vector<DQMMonitorElement*>::const_iterator iter = m_contentsList.begin(), endIter =
      m_contentsList.end() ;
      endIter != iter ; ++iter)
  {
    DQMMonitorElement *pME = *iter;
    if(pME->getName() == name)
    {
      pMonitorElement = pME;
      return STATUS_CODE_SUCCESS;
    }
  }
  return STATUS_CODE_NOT_FOUND;
}
DQMPath dqm4hep::DQMDirectory::getFullPathName () const
Get the full path name of the directory.
Definition at line 315 of file DQMDirectory.cc.
References getName(), and getParentDir().
Referenced by dqm4hep::DQMStorage::addMonitorElement(), dqm4hep::DQMMonitorElementManager::bookCharHistogram1D(), dqm4hep::DQMMonitorElementManager::bookCharHistogram2D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram1D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram2D(), dqm4hep::DQMMonitorElementManager::bookProfile1D(), dqm4hep::DQMMonitorElementManager::bookProfile2D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram1D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram2D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram1D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram2D(), dqm4hep::DQMMonitorElementManager::getCurrentDirectoryFullPathName(), dqm4hep::DQMMonitorElementManager::getFullPathName(), and dqm4hep::DQMStorage::rmdir().
{
  DQMPath fullPath = this->getName();
  const DQMDirectory *pDir = this;
  while(1)
  {
    const DQMDirectory *pParentDir = pDir->getParentDir();
    if(NULL != pParentDir)
    {
      fullPath = pParentDir->getName() + fullPath;
      pDir = pParentDir;
    }
    else
      break;
  }
  return fullPath;
}
const std::vector< DQMMonitorElement * > & dqm4hep::DQMDirectory::getMonitorElementList () const
Get the monitor element list.
Definition at line 253 of file DQMDirectory.cc.
References m_contentsList.
Referenced by dqm4hep::DQMStorage::recursiveContentList(), dqm4hep::DQMArchiver::recursiveFill(), and dqm4hep::DQMArchiver::writeMonitorElements().
{
  return m_contentsList;
}
const std::string & dqm4hep::DQMDirectory::getName () const
Returns the directory name.
Definition at line 98 of file DQMDirectory.cc.
References m_name.
Referenced by containsDir(), findDir(), dqm4hep::DQMMonitorElementManager::getCurrentDirectoryName(), getFullPathName(), dqm4hep::DQMStorage::pwd(), dqm4hep::DQMArchiver::recursiveFill(), removeDir(), and dqm4hep::DQMStorage::rmdir().
{
  return m_name;
}
DQMDirectory * dqm4hep::DQMDirectory::getParentDir () const
Returns the parent directory.
Definition at line 105 of file DQMDirectory.cc.
References m_pParentDir.
Referenced by getFullPathName(), dqm4hep::DQMStorage::goUp(), and dqm4hep::DQMStorage::rmdir().
{
  return m_pParentDir;
}
const std::vector< DQMDirectory * > & dqm4hep::DQMDirectory::getSubDirList () const
Get the sub directory list.
Definition at line 112 of file DQMDirectory.cc.
References m_directoryList.
Referenced by dqm4hep::DQMStorage::recursiveContentList(), and dqm4hep::DQMArchiver::recursiveFill().
{
  return m_directoryList;
}
bool dqm4hep::DQMDirectory::isEmpty () const
Whether the directory is empty.
Definition at line 370 of file DQMDirectory.cc.
References m_contentsList, and m_directoryList.
{
  return (m_directoryList.empty() && m_contentsList.empty());
}
bool dqm4hep::DQMDirectory::isRootDir () const
Whether the directory is a root directory.
Definition at line 363 of file DQMDirectory.cc.
References m_pParentDir.
Referenced by dqm4hep::DQMStorage::goUp().
{
  return (m_pParentDir == NULL);
}
void dqm4hep::DQMDirectory::ls (bool recursive = false) const
List the directory contents and subdirs if asked.
Definition at line 62 of file DQMDirectory.cc.
References dqm4hep::DQMMonitorElement::getName(), ls(), m_contentsList, m_directoryList, m_name, m_pParentDir, and dqm4hep::MESSAGE.
Referenced by ls(), and dqm4hep::DQMStorage::ls().
{
  int depth = 0;
  std::string parentDirName = m_pParentDir == NULL ? "\"\"" : m_pParentDir->
      m_name;
  streamlog_out(MESSAGE) << "Directory " << m_name << " (parent = " << parentDirName << ") :" << std::endl;
  // print contents first
  for(std::vector<DQMMonitorElement*>::const_iterator iter = m_contentsList.begin(), endIter =
      m_contentsList.end() ;
      endIter != iter ; ++iter)
  {
    DQMMonitorElement *pMonitorElement = *iter;
    streamlog_out(MESSAGE) << " [ME] " << pMonitorElement->getName() << std::endl;
  }
  // print sub-directories
  for(std::vector<DQMDirectory*>::const_iterator iter = m_directoryList.begin(), endIter =
      m_directoryList.end() ;
      endIter != iter ; ++iter)
  {
    DQMDirectory *pDirectory = *iter;
    if(recursive)
    {
      pDirectory->ls(depth+1);
    }
    else
    {
      streamlog_out(MESSAGE) << " [DIR] " << pDirectory->m_name << std::endl;
    }
  }
  streamlog_out(MESSAGE) << std::endl;
}
void dqm4hep::DQMDirectory::ls (int depth) const [private]
Recursive print of sub directory structure (dirs and contents)
Definition at line 338 of file DQMDirectory.cc.
References dqm4hep::DQMMonitorElement::getName(), ls(), m_contentsList, m_directoryList, m_name, m_pParentDir, and dqm4hep::MESSAGE.
{
  std::string parentDirName = m_pParentDir == NULL ? "\"\"" : m_pParentDir->
      m_name;
  streamlog_out(MESSAGE) << std::string(depth*3, ' ') << "Directory " << m_name << " (parent = " <<
      parentDirName << ") :" << std::endl;
  // print contents first
  for(std::vector<DQMMonitorElement*>::const_iterator iter = m_contentsList.begin(), endIter =
      m_contentsList.end() ;
      endIter != iter ; ++iter)
  {
    DQMMonitorElement *pMonitorElement = *iter;
    streamlog_out(MESSAGE) << std::string(depth*3, ' ') << " [ME] " << pMonitorElement->getName() <<
      std::endl;
  }
  // print sub dirs
  for(std::vector<DQMDirectory*>::const_iterator iter = m_directoryList.begin(), endIter =
      m_directoryList.end() ;
      endIter != iter ; ++iter)
  {
    DQMDirectory *pDirectory = *iter;
    pDirectory->ls(depth+1);
  }
}
StatusCode dqm4hep::DQMDirectory::mkdir (const std::string & dirName)
Create a new directory.
Definition at line 119 of file DQMDirectory.cc.
References containsDir(), dqm4hep::DQMCoreTool::containsSpecialCharacters(), DQMDirectory(), and m_directoryList.
Referenced by dqm4hep::DQMStorage::mkdir(), and dqm4hep::DQMArchiver::recursiveFill().
{
  if(containsDir(dirName))
    return STATUS_CODE_ALREADY_PRESENT;
  if(dirName.find("/") != std::string::npos ||
      DQMCoreTool::containsSpecialCharacters(dirName) || dirName.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  DQMDirectory *pNewDirectory = new DQMDirectory(dirName, this);
  m_directoryList.push_back(pNewDirectory);
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDirectory::removeDir (const std::string & dirName, bool deepClean = false)
Remove the directory and its contents Delete monitor element if deepClean set to true.
Definition at line 260 of file DQMDirectory.cc.
References clear(), getName(), m_directoryList, and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMStorage::rmdir().
{
  for(std::vector<DQMDirectory*>::iterator iter = m_directoryList.begin(), endIter =
      m_directoryList.end() ;
      endIter != iter ; ++iter)
  {
    DQMDirectory *pDirectory = *iter;
    if(pDirectory->getName() == dirName)
    {
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDirectory->clear(deepClean));
      delete pDirectory;
      m_directoryList.erase(iter);
      return STATUS_CODE_SUCCESS;
    }
  }
  return STATUS_CODE_NOT_FOUND;
}
StatusCode dqm4hep::DQMDirectory::removeMonitorElement (DQMMonitorElement * pMonitorElement)
Remove the monitor element from the directory.
Definition at line 227 of file DQMDirectory.cc.
References dqm4hep::DQMMonitorElement::getName().
Referenced by dqm4hep::DQMStorage::removeMonitorElement().
{
  return removeMonitorElement(pMonitorElement->getName());
}
StatusCode dqm4hep::DQMDirectory::removeMonitorElement (const std::string & monitorElementName)
Remove the monitor element from the directory.
Definition at line 234 of file DQMDirectory.cc.
References dqm4hep::DQMMonitorElement::getName(), and m_contentsList.
{
  for(std::vector<DQMMonitorElement*>::iterator iter = m_contentsList.begin(), endIter =
      m_contentsList.end() ;
      endIter != iter ; ++iter)
  {
    DQMMonitorElement *pME = *iter;
    if(pME->getName() == monitorElementName)
    {
      m_contentsList.erase(iter);
      return STATUS_CODE_SUCCESS;
    }
  }
  return STATUS_CODE_NOT_FOUND;
}
Member Data Documentation
std::vector<DQMMonitorElement*> dqm4hep::DQMDirectory::m_contentsList [private]
Definition at line 154 of file DQMDirectory.h.
Referenced by addMonitorElement(), clear(), findMonitorElement(), getMonitorElementList(), isEmpty(), ls(), and removeMonitorElement().
std::vector<DQMDirectory*> dqm4hep::DQMDirectory::m_directoryList [private]
Definition at line 153 of file DQMDirectory.h.
Referenced by clear(), containsDir(), findDir(), getSubDirList(), isEmpty(), ls(), mkdir(), and removeDir().
std::string dqm4hep::DQMDirectory::m_name [private]
Definition at line 151 of file DQMDirectory.h.
Referenced by getName(), and ls().
DQMDirectory* dqm4hep::DQMDirectory::m_pParentDir [private]
Definition at line 152 of file DQMDirectory.h.
Referenced by getParentDir(), isRootDir(), and ls().
The documentation for this class was generated from the following files:
DQMDirectory.h
DQMDirectory.cc