dqm4hep::DQMFileHandler Class Reference
DQMFileHandler interface.
#include <DQMFileHandler.h>
Public Member Functions
virtual ~DQMFileHandler ()
Destructor.
virtual const std::string & type () const =0
Get the file handler type as string.
virtual StatusCode download (const std::string &pattern)=0
Download the file locally using the target pattern.
virtual const std::string & getLocalFileName () const =0
Get the full file name after the download step.
Detailed Description
DQMFileHandler interface.
Definition at line 39 of file DQMFileHandler.h.
Constructor & Destructor Documentation
virtual dqm4hep::DQMFileHandler::~DQMFileHandler () [inline], [virtual]
Destructor.
Definition at line 44 of file DQMFileHandler.h.
{}
Member Function Documentation
virtual StatusCode dqm4hep::DQMFileHandler::download (const std::string & pattern) [pure virtual]
Download the file locally using the target pattern.
Implemented in dqm4hep::DQMDBFileHandler , and dqm4hep::DQMLocalFileHandler .
Referenced by dqm4hep::DQMStandaloneModuleApplication::readSettings(), and dqm4hep::DQMAnalysisModuleApplication::readSettings().
virtual const std::string& dqm4hep::DQMFileHandler::getLocalFileName () const [pure virtual]
Get the full file name after the download step.
Implemented in dqm4hep::DQMDBFileHandler , and dqm4hep::DQMLocalFileHandler .
Referenced by dqm4hep::DQMStandaloneModuleApplication::readSettings(), and dqm4hep::DQMAnalysisModuleApplication::readSettings().
virtual const std::string& dqm4hep::DQMFileHandler::type () const [pure virtual]
Get the file handler type as string.
Implemented in dqm4hep::DQMDBFileHandler , and dqm4hep::DQMLocalFileHandler .
The documentation for this class was generated from the following file:
DQMFileHandler.h