dqm4hep::DQMEventCollectorApplication Class Reference
DQMEventCollectorApplication class.
#include <DQMEventCollectorApplication.h>
Public Member Functions
DQMEventCollectorApplication ()
Constructor with collector name.
~DQMEventCollectorApplication ()
Destructor.
StatusCode run ()
Run the application.
StatusCode exit (int returnCode)
Stop the application.
const std::string & getName () const
Get the application name.
const std::string & getType () const
Get the application type.
StatusCode setCollectorName (const std::string &collectorName)
Set the event collector name.
void setEventCollectorImp (DQMEventCollectorImp *pCollectorImp)
Set the event collector implementation.
void setEventStreamer (DQMEventStreamer *pEventStreamer)
Set the event streamer to serialize/deserialize the in/out-coming events.
DQMEventStreamer * getEventStreamer () const
Get the event streamer.
Protected Member Functions
StatusCode readSettings (const std::string &settingsFile=``)
No settings to read.
Protected Attributes
bool m_shouldExit
std::string m_type
std::string m_networkName
DQMState m_applicationState
DQMEventCollector * m_pEventCollector
Detailed Description
DQMEventCollectorApplication class.
Definition at line 44 of file DQMEventCollectorApplication.h.
Constructor & Destructor Documentation
dqm4hep::DQMEventCollectorApplication::DQMEventCollectorApplication ()
Constructor with collector name.
Definition at line 36 of file DQMEventCollectorApplication.cc.
References m_pEventCollector.
                                                           :
    m_applicationState(STOPPED_STATE),
    m_shouldExit(false),
    m_type("EventCollector"),
    m_pEventCollector(NULL)
{
  m_pEventCollector = new DQMEventCollector();
}
dqm4hep::DQMEventCollectorApplication::~DQMEventCollectorApplication ()
Destructor.
Definition at line 47 of file DQMEventCollectorApplication.cc.
References dqm4hep::DQMEventCollector::isRunning(), m_pEventCollector, and dqm4hep::DQMEventCollector::stopCollector().
{
  if(m_pEventCollector->isRunning())
    m_pEventCollector->stopCollector();
  delete m_pEventCollector;
}
Member Function Documentation
StatusCode dqm4hep::DQMEventCollectorApplication::exit (int returnCode) [virtual]
Stop the application.
Implements dqm4hep::DQMApplication .
Definition at line 79 of file DQMEventCollectorApplication.cc.
References m_applicationState, m_pEventCollector, m_shouldExit, dqm4hep::NUMBER_OF_STATUS_CODES, RETURN_RESULT_IF, and dqm4hep::DQMEventCollector::stopCollector().
{
  if(m_applicationState == STOPPED_STATE)
    return STATUS_CODE_FAILURE;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventCollector->stopCollector());
  m_shouldExit = true;
  m_applicationState = STOPPED_STATE;
  StatusCode returnStatusCode;
  if(returnCode >= 0 && returnCode < NUMBER_OF_STATUS_CODES)
    returnStatusCode = static_cast<StatusCode>(returnCode);
  else
    returnStatusCode = STATUS_CODE_FAILURE;
  return returnStatusCode;
}
DQMEventStreamer * dqm4hep::DQMEventCollectorApplication::getEventStreamer () const
Get the event streamer.
Definition at line 139 of file DQMEventCollectorApplication.cc.
References dqm4hep::DQMEventCollector::getEventStreamer(), and m_pEventCollector.
{
  return m_pEventCollector->getEventStreamer();
}
const std::string & dqm4hep::DQMEventCollectorApplication::getName () const [virtual]
Get the application name.
Implements dqm4hep::DQMApplication .
Definition at line 101 of file DQMEventCollectorApplication.cc.
References dqm4hep::DQMEventCollector::getCollectorName(), and m_pEventCollector.
{
  return m_pEventCollector->getCollectorName();
}
const std::string & dqm4hep::DQMEventCollectorApplication::getType () const [virtual]
Get the application type.
Implements dqm4hep::DQMApplication .
Definition at line 108 of file DQMEventCollectorApplication.cc.
References m_type.
{
  return m_type;
}
StatusCode dqm4hep::DQMEventCollectorApplication::readSettings (const std::string & settingsFile = ``) [inline], [protected], [virtual]
No settings to read.
Implements dqm4hep::DQMApplication .
Definition at line 90 of file DQMEventCollectorApplication.h.
{ return STATUS_CODE_SUCCESS; }
StatusCode dqm4hep::DQMEventCollectorApplication::run () [virtual]
Run the application.
Implements dqm4hep::DQMApplication .
Definition at line 57 of file DQMEventCollectorApplication.cc.
References m_applicationState, m_pEventCollector, m_shouldExit, RETURN_RESULT_IF, and dqm4hep::DQMEventCollector::startCollector().
{
  if(m_applicationState == RUNNING_STATE)
    return STATUS_CODE_FAILURE;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventCollector->startCollector());
  m_applicationState = RUNNING_STATE;
  while(!m_shouldExit)
  {
    timespec timesleep;
      timesleep.tv_sec = 0;
      timesleep.tv_nsec = 100000L;
    nanosleep(&timesleep, NULL);
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMEventCollectorApplication::setCollectorName (const std::string & collectorName)
Set the event collector name.
Definition at line 115 of file DQMEventCollectorApplication.cc.
References m_pEventCollector, and dqm4hep::DQMEventCollector::setCollectorName().
{
  return m_pEventCollector->setCollectorName(collectorName);
}
void dqm4hep::DQMEventCollectorApplication::setEventCollectorImp (DQMEventCollectorImp * pCollectorImp)
Set the event collector implementation.
Definition at line 122 of file DQMEventCollectorApplication.cc.
References m_pEventCollector, and dqm4hep::DQMEventCollector::setEventCollectorImp().
{
  if(NULL == pCollectorImp)
    return;
  m_pEventCollector->setEventCollectorImp(pCollectorImp);
}
void dqm4hep::DQMEventCollectorApplication::setEventStreamer (DQMEventStreamer * pEventStreamer)
Set the event streamer to serialize/deserialize the in/out-coming events.
Definition at line 132 of file DQMEventCollectorApplication.cc.
References m_pEventCollector, and dqm4hep::DQMEventCollector::setEventStreamer().
{
  m_pEventCollector->setEventStreamer(pEventStreamer);
}
Member Data Documentation
DQMState dqm4hep::DQMEventCollectorApplication::m_applicationState [protected]
Definition at line 95 of file DQMEventCollectorApplication.h.
Referenced by exit(), and run().
std::string dqm4hep::DQMEventCollectorApplication::m_networkName [protected]
Definition at line 94 of file DQMEventCollectorApplication.h.
DQMEventCollector* dqm4hep::DQMEventCollectorApplication::m_pEventCollector [protected]
Definition at line 96 of file DQMEventCollectorApplication.h.
Referenced by DQMEventCollectorApplication(), exit(), getEventStreamer(), getName(), run(), setCollectorName(), setEventCollectorImp(), setEventStreamer(), and ~DQMEventCollectorApplication().
bool dqm4hep::DQMEventCollectorApplication::m_shouldExit [protected]
Definition at line 92 of file DQMEventCollectorApplication.h.
Referenced by exit(), and run().
std::string dqm4hep::DQMEventCollectorApplication::m_type [protected]
Definition at line 93 of file DQMEventCollectorApplication.h.
Referenced by getType().
The documentation for this class was generated from the following files:
DQMEventCollectorApplication.h
DQMEventCollectorApplication.cc