dqm4hep::TiXmlComment Class Reference
An XML comment.
#include <tinyxml.h>
Public Member Functions
TiXmlComment ()
Constructs an empty comment.
TiXmlComment (const char *_value)
Construct a comment from text.
TiXmlComment (const TiXmlComment &)
void operator= (const TiXmlComment &base)
virtual ~TiXmlComment ()
virtual TiXmlNode * Clone () const
Returns a copy of this Comment.
virtual void Print (FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *visitor) const
Walk the XML tree visiting this node and all of its children.
Protected Member Functions
void CopyTo (TiXmlComment *target) const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Additional Inherited Members
Detailed Description
An XML comment.
Definition at line 1161 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::TiXmlComment::TiXmlComment () [inline]
Constructs an empty comment.
Definition at line 1165 of file tinyxml.h.
Referenced by Clone().
: TiXmlNode(TiXmlNode::TINYXML_COMMENT) {}
dqm4hep::TiXmlComment::TiXmlComment (const char * _value) [inline]
Construct a comment from text.
Definition at line 1167 of file tinyxml.h.
References dqm4hep::TiXmlNode::SetValue().
                                     : TiXmlNode(TiXmlNode::TINYXML_COMMENT) {
    SetValue(_value);
  }
dqm4hep::TiXmlComment::TiXmlComment (const TiXmlComment & copy)
Definition at line 1241 of file tinyxml.cc.
References CopyTo().
                                                     : TiXmlNode(
      TiXmlNode::TINYXML_COMMENT)
{
  copy.CopyTo(this);
}
virtual dqm4hep::TiXmlComment::~TiXmlComment () [inline], [virtual]
Definition at line 1173 of file tinyxml.h.
{}
Member Function Documentation
bool dqm4hep::TiXmlComment::Accept (TiXmlVisitor * visitor) const [virtual]
Walk the XML tree visiting this node and all of its children.
Implements dqm4hep::TiXmlNode .
Definition at line 1271 of file tinyxml.cc.
References dqm4hep::TiXmlVisitor::Visit().
{
  return visitor->Visit(*this);
}
TiXmlNode * dqm4hep::TiXmlComment::Clone () const [virtual]
Returns a copy of this Comment.
Implements dqm4hep::TiXmlNode .
Definition at line 1277 of file tinyxml.cc.
References CopyTo(), and TiXmlComment().
{
  TiXmlComment* clone = new TiXmlComment();
  if (!clone)
    return 0;
  CopyTo(clone);
  return clone;
}
void dqm4hep::TiXmlComment::CopyTo (TiXmlComment * target) const [protected]
Definition at line 1265 of file tinyxml.cc.
References dqm4hep::TiXmlNode::CopyTo().
Referenced by Clone(), operator=(), and TiXmlComment().
{
  TiXmlNode::CopyTo(target);
}
void dqm4hep::TiXmlComment::operator= (const TiXmlComment & base)
Definition at line 1247 of file tinyxml.cc.
References dqm4hep::TiXmlNode::Clear(), and CopyTo().
{
  Clear();
  base.CopyTo(this);
}
const char * dqm4hep::TiXmlComment::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) [virtual]
Implements dqm4hep::TiXmlBase .
Definition at line 1339 of file tinyxmlparser.cc.
References dqm4hep::TiXmlParsingData::Cursor(), dqm4hep::TiXmlNode::GetDocument(), dqm4hep::TiXmlBase::location, dqm4hep::TiXmlDocument::SetError(), dqm4hep::TiXmlBase::SkipWhiteSpace(), dqm4hep::TiXmlParsingData::Stamp(), dqm4hep::TiXmlBase::StringEqual(), dqm4hep::TiXmlBase::TIXML_ERROR_PARSING_COMMENT, and dqm4hep::TiXmlNode::value.
{
  TiXmlDocument* document = GetDocument();
  value = "";
  p = SkipWhiteSpace(p, encoding);
  if (data)
  {
    data->Stamp(p, encoding);
    location = data->Cursor();
  }
  const char* startTag = "<!--";
  const char* endTag = "-->";
  if (!StringEqual(p, startTag, false, encoding))
  {
    document->SetError(TIXML_ERROR_PARSING_COMMENT, p, data, encoding);
    return 0;
  }
  p += strlen(startTag);
  // [ 1475201 ] TinyXML parses entities in comments
  // Oops - ReadText doesn't work, because we don't want to parse the entities.
  // p = ReadText(p, &value, false, endTag, false, encoding);
  //
  // from the XML spec:
  /*
   [Definition: Comments may appear anywhere in a document outside other markup; in addition,
                they may appear within the document type declaration at places allowed by the grammar.
          They are not part of the document's character data; an XML processor MAY, but need not,
          make it possible for an application to retrieve the text of comments. For compatibility,
          the string "--" (double-hyphen) MUST NOT occur within comments.] Parameter entity
          references MUST NOT be recognized within comments.
          An example of a comment:
          <!-- declarations for <head> & <body> -->
  */
    value = "";
  // Keep all the white space.
  while (p && *p && !StringEqual(p, endTag, false, encoding))
  {
    value.append(p, 1);
    ++p;
  }
  if (p && *p)
    p += strlen(endTag);
  return p;
}
void dqm4hep::TiXmlComment::Print (FILE * cfile, int depth) const [virtual]
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements dqm4hep::TiXmlBase .
Definition at line 1254 of file tinyxml.cc.
References dqm4hep::TiXmlNode::value.
{
  assert(cfile);
  for (int i=0; i<depth; i++)
  {
    fprintf(cfile, " ");
  }
  fprintf(cfile, "<!--%s-->", value.c_str());
}
virtual void dqm4hep::TiXmlComment::StreamIn (std::istream * in, TIXML_STRING * tag) [protected], [virtual]
Implements dqm4hep::TiXmlNode .
virtual const TiXmlComment* dqm4hep::TiXmlComment::ToComment () const [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1185 of file tinyxml.h.
virtual TiXmlComment* dqm4hep::TiXmlComment::ToComment () [inline], [virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::TiXmlNode .
Definition at line 1186 of file tinyxml.h.
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc