dqm4hep::DQMMonitorElementNameListRpc Class Reference
#include <DQMMonitorElementCollector.h>
Public Member Functions
DQMMonitorElementNameListRpc (char *rpcName, DQMMonitorElementCollector *pCollector)
void rpcHandler ()
Private Attributes
DQMMonitorElementCollector * m_pCollector
DQMDataStream m_dataStream
Detailed Description
Definition at line 189 of file DQMMonitorElementCollector.h.
Constructor & Destructor Documentation
dqm4hep::DQMMonitorElementNameListRpc::DQMMonitorElementNameListRpc (char * rpcName, DQMMonitorElementCollector * pCollector)
Definition at line 1253 of file DQMMonitorElementCollector.cc.
                                                                                                           
           :
    DimRpc(rpcName, "C", "C"),
    m_pCollector(pCollector),
    m_dataStream(1024*1024)
{
  /* nop */
}
Member Function Documentation
void dqm4hep::DQMMonitorElementNameListRpc::rpcHandler ()
Definition at line 1263 of file DQMMonitorElementCollector.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), dqm4hep::DQMMonitorElementCollector::isRunning(), m_dataStream, dqm4hep::DQMMonitorElementCollector::m_moduleMeInfoMap, m_pCollector, dqm4hep::monitorElementTypeToString(), dqm4hep::DQMDataStream::reset(), dqm4hep::DQMDataStream::setBuffer(), and THROW_RESULT_IF.
{
  try
  {
    if(!m_pCollector->isRunning())
      return;
    dqm_char *pBuffer = static_cast<dqm_char *>(getData());
    dqm_uint bufferSize = getSize();
    if(NULL == pBuffer || 0 == bufferSize)
      return;
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    DQMMonitorElementListNameRequest request;
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, request.deserialize(&m_dataStream));
    // transform module name to lower for easier comparison
    std::transform(request.m_moduleName.begin(), request.m_moduleName.end(), request.m_moduleName.begin(),
      ::tolower);
    std::transform(request.m_monitorElementName.begin(), request.m_monitorElementName.end(), request.
      m_monitorElementName.begin(), ::tolower);
    DQMMonitorElementInfoList infoList;
    // loop over available contents and apply some filter to anwser the client query
    for(DQMMonitorElementCollector::ModuleMeInfoMap::const_iterator iter =
      m_pCollector->m_moduleMeInfoMap.begin(),
        endIter = m_pCollector->m_moduleMeInfoMap.end() ; endIter != iter ; ++iter)
    {
      std::string moduleName = iter->first;
      std::transform(moduleName.begin(), moduleName.end(), moduleName.begin(), ::tolower);
      // partial and lower case compare of module name
      if(moduleName.find(request.m_moduleName) == std::string::npos && !request.m_moduleName.empty())
        continue;
      const std::vector<DQMMonitorElementInfo> &availableMeList = iter->second->getAvailableMeList();
      for(std::vector<DQMMonitorElementInfo>::const_iterator meIter = availableMeList.begin(), meEndIter =
      availableMeList.end() ;
          meEndIter != meIter ; ++meIter)
      {
        std::string meName = meIter->m_monitorElementName;
        std::transform(meName.begin(), meName.end(), meName.begin(), ::tolower);
        std::string path = meIter->m_monitorElementFullPath;
        std::transform(path.begin(), path.end(), path.begin(), ::tolower);
        // partial and lower case compare of me name
        if(meName.find(request.m_monitorElementName) == std::string::npos && !request.m_monitorElementName.
      empty())
          continue;
        // partial and lower case compare of path using me name
        if(path.find(request.m_monitorElementName) == std::string::npos && !request.m_monitorElementName.
      empty())
          continue;
        // compare me type
        if(meIter->m_monitorElementType != monitorElementTypeToString(request.m_monitorElementType) &&
      NO_ELEMENT_TYPE != request.m_monitorElementType)
          continue;
        infoList.push_back(*meIter);
      }
    }
    // serialize the packet
    m_dataStream.reset();
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, infoList.serialize(&m_dataStream));
    // and set it as data to send back
    setData((void*) m_dataStream.getBuffer(), m_dataStream.getBufferSize());
  }
  catch(StatusCodeException &exception)
  {
  }
  catch(...)
  {
  }
}
Member Data Documentation
DQMDataStream dqm4hep::DQMMonitorElementNameListRpc::m_dataStream [private]
Definition at line 197 of file DQMMonitorElementCollector.h.
Referenced by rpcHandler().
DQMMonitorElementCollector* dqm4hep::DQMMonitorElementNameListRpc::m_pCollector [private]
Definition at line 196 of file DQMMonitorElementCollector.h.
Referenced by rpcHandler().
The documentation for this class was generated from the following files:
DQMMonitorElementCollector.h
DQMMonitorElementCollector.cc