dqm4hep::DQMPlugin Class Reference
DQMPlugin class.
#include <DQMPlugin.h>
Public Member Functions
DQMPlugin (const std::string &pluginName, bool shouldRegister)
Constructor.
virtual ~DQMPlugin ()
Destructor.
const std::string & getPluginName () const
Returns the plug-in name.
virtual DQMPlugin * create () const =0
Create a new instance of the wrapped class.
Private Attributes
const std::string m_pluginName
Friends
class DQMPluginManager
Detailed Description
DQMPlugin class.
Definition at line 41 of file DQMPlugin.h.
Constructor & Destructor Documentation
dqm4hep::DQMPlugin::DQMPlugin (const std::string & pluginName, bool shouldRegister)
Constructor.
Definition at line 35 of file DQMPlugin.cc.
References dqm4hep::DQMSingleton< DQMPluginManager >::instance(), and THROW_RESULT_IF.
                                                                     :
    m_pluginName(pluginName)
{
  if(shouldRegister)
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMPluginManager::instance()->registerPlugin(this));
}
dqm4hep::DQMPlugin::~DQMPlugin () [virtual]
Destructor.
Definition at line 44 of file DQMPlugin.cc.
{
  /* nop */
}
Member Function Documentation
virtual DQMPlugin* dqm4hep::DQMPlugin::create () const [pure virtual]
Create a new instance of the wrapped class.
Referenced by dqm4hep::DQMPluginManager::createPluginClass().
const std::string & dqm4hep::DQMPlugin::getPluginName () const
Returns the plug-in name.
Definition at line 51 of file DQMPlugin.cc.
References m_pluginName.
Referenced by dqm4hep::DQMPluginManager::registerPlugin().
{
  return m_pluginName;
}
Friends And Related Function Documentation
friend class DQMPluginManager [friend]
Definition at line 43 of file DQMPlugin.h.
Member Data Documentation
const std::string dqm4hep::DQMPlugin::m_pluginName [private]
Definition at line 62 of file DQMPlugin.h.
Referenced by getPluginName().
The documentation for this class was generated from the following files:
DQMPlugin.h
DQMPlugin.cc