dqm4hep::DQMXmlHelper Class Reference
DQMXmlHelper class.
#include <DQMXmlHelper.h>
Public Member Functions
template<>
StatusCode readValue (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, bool &t)
template<>
StatusCode getAttribute (const TiXmlElement *const pXmlElement, const std::string &attributeName, std::string &attributeValue)
Static Public Member Functions
template<typename T >
static StatusCode readValue (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, T &t)
Read a value from an xml element.
template<typename T >
static StatusCode readVectorOfValues (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, std::vector< T > &vector)
Read a vector of values from a (space separated) list in an xml element.
template<typename T >
static StatusCode read2DVectorOfValues (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, const std::string &rowName, std::vector< std::vector< T > > &vector)
Read a two-dimensional array of values into a vector of vectors.
template<typename T >
static StatusCode getAttribute (const TiXmlElement *const pXmlElement, const std::string &attributeName, T &attributeValue)
Get the attribute of the xml element.
template<typename T , typename Validator >
static StatusCode getAttribute (const TiXmlElement *const pXmlElement, const std::string &attributeName, T &attributeValue, Validator validator)
Get the attribute of the xml element and use a validator to validate the value.
template<typename T >
static StatusCode readParameterValue (const TiXmlHandle &xmlHandle, const std::string &parameterName, T &t)
Read a parameter value from an xml element.
template<typename T >
static StatusCode readParameterValues (const TiXmlHandle &xmlHandle, const std::string &parameterName, std::vector< T > &vector)
Read a vector of values for a parameter from a (space separated) list in an xml element.
static StatusCode createQualityTest (const DQMModule *const pModule, const TiXmlHandle &xmlHandle, const std::string &qualityTestName)
Create a quality test.
static StatusCode bookMonitorElement (const DQMModule *const pModule, const TiXmlHandle &xmlHandle, const std::string &meStringId, DQMMonitorElement *&pMonitorElement)
Create a built-in monitor element from a xml handle.
static void tokenizeString (const std::string &inputString, StringVector &tokens, const std::string &delimiter=` `)
Tokenize a string.
Detailed Description
DQMXmlHelper class.
Definition at line 43 of file DQMXmlHelper.h.
Member Function Documentation
StatusCode dqm4hep::DQMXmlHelper::bookMonitorElement (const DQMModule *const pModule, const TiXmlHandle & xmlHandle, const std::string & meStringId, DQMMonitorElement *& pMonitorElement) [static]
Create a built-in monitor element from a xml handle.
Definition at line 74 of file DQMXmlHelper.cc.
References dqm4hep::DQMModuleApi::bookMonitorElement(), dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChild(), getAttribute(), dqm4hep::TiXmlNode::NextSiblingElement(), and RETURN_RESULT_IF.
{
    for (TiXmlElement *pXmlElement = xmlHandle.FirstChild("monitorElement").Element(); NULL != pXmlElement;
        pXmlElement = pXmlElement->NextSiblingElement("monitorElement"))
    {
      std::string meId;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "ID", meId));
      if(meId != meStringId)
        continue;
      return DQMModuleApi::bookMonitorElement(pModule, pXmlElement, pMonitorElement);
    }
  return STATUS_CODE_NOT_FOUND;
}
StatusCode dqm4hep::DQMXmlHelper::createQualityTest (const DQMModule *const pModule, const TiXmlHandle & xmlHandle, const std::string & qualityTestName) [static]
Create a quality test.
Works if the quality test factory has been registered first
Definition at line 53 of file DQMXmlHelper.cc.
References dqm4hep::DQMModuleApi::createQualityTest(), dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChild(), getAttribute(), dqm4hep::TiXmlNode::NextSiblingElement(), and RETURN_RESULT_IF.
{
    for (TiXmlElement *pXmlElement = xmlHandle.FirstChild("qualitytest").Element(); NULL != pXmlElement;
        pXmlElement = pXmlElement->NextSiblingElement("qualitytest"))
    {
      std::string name;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "name", name));
      if(name != qualityTestName)
        continue;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMModuleApi::createQualityTest(pModule, pXmlElement));
      return STATUS_CODE_SUCCESS;
    }
    return STATUS_CODE_NOT_FOUND;
}
template<typename T > StatusCode dqm4hep::DQMXmlHelper::getAttribute (const TiXmlElement *const pXmlElement, const std::string & attributeName, T & attributeValue) [inline], [static]
Get the attribute of the xml element.
Definition at line 210 of file DQMXmlHelper.h.
References dqm4hep::TiXmlElement::Attribute(), and dqm4hep::DQM4HEP::stringToType().
Referenced by bookMonitorElement(), dqm4hep::DQMMonitorElementManager::bookMonitorElement(), dqm4hep::DQMAnalysisModuleApplication::configureArchiver(), dqm4hep::DQMAnalysisModuleApplication::configureCycle(), dqm4hep::DQMAnalysisModuleApplication::configureModule(), dqm4hep::DQMAnalysisModuleApplication::configureNetwork(), createQualityTest(), dqm4hep::DQMMonitorElementManager::createQualityTest(), readParameterValue(), readParameterValues(), and dqm4hep::DQMStandaloneModuleApplication::readSettings().
{
  if(NULL == pXmlElement)
    return STATUS_CODE_INVALID_PTR;
  const char *pAttributePtr(pXmlElement->Attribute(attributeName.c_str()));
  if(NULL == pAttributePtr)
    return STATUS_CODE_NOT_FOUND;
  std::string attributeStr(pAttributePtr);
  if(!DQM4HEP::stringToType(attributeStr, attributeValue))
    return STATUS_CODE_FAILURE;
  return STATUS_CODE_SUCCESS;
}
template<typename T , typename Validator > StatusCode dqm4hep::DQMXmlHelper::getAttribute (const TiXmlElement *const pXmlElement, const std::string & attributeName, T & attributeValue, Validator validator) [inline], [static]
Get the attribute of the xml element and use a validator to validate the value.
Definition at line 231 of file DQMXmlHelper.h.
References RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute<T>(pXmlElement, attributeName,
      attributeValue));
  if(!validator(attributeValue))
    return STATUS_CODE_INVALID_PARAMETER;
  return STATUS_CODE_SUCCESS;
}
template<> StatusCode dqm4hep::DQMXmlHelper::getAttribute (const TiXmlElement *const pXmlElement, const std::string & attributeName, std::string & attributeValue) [inline]
Definition at line 244 of file DQMXmlHelper.h.
References dqm4hep::TiXmlElement::Attribute().
{
  if(NULL == pXmlElement)
    return STATUS_CODE_INVALID_PTR;
  const char *pAttributePtr(pXmlElement->Attribute(attributeName.c_str()));
  if(NULL == pAttributePtr)
    return STATUS_CODE_NOT_FOUND;
  attributeValue = pAttributePtr;
  return STATUS_CODE_SUCCESS;
}
template<typename T > StatusCode dqm4hep::DQMXmlHelper::read2DVectorOfValues (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, const std::string & rowName, std::vector< std::vector< T > > & vector) [inline], [static]
Read a two-dimensional array of values into a vector of vectors.
Each row of values must be contained within <rowname></rowname> xml tags, whilst the values in the row must be space separated
Definition at line 171 of file DQMXmlHelper.h.
References dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChild(), dqm4hep::TiXmlElement::GetText(), dqm4hep::TiXmlNode::NextSiblingElement(), dqm4hep::DQM4HEP::stringToType(), and tokenizeString().
{
    TiXmlElement *pXmlElement = xmlHandle.FirstChild(xmlElementName).Element();
    if (NULL == pXmlElement)
        return STATUS_CODE_NOT_FOUND;
    TiXmlElement *pXmlRowElement = TiXmlHandle(pXmlElement).FirstChild(rowName).Element();
    if (NULL == pXmlRowElement)
        return STATUS_CODE_NOT_FOUND;
    for (; NULL != pXmlRowElement; pXmlRowElement = pXmlRowElement->NextSiblingElement(rowName))
    {
        std::vector<T> rowVector;
        StringVector tokens;
        tokenizeString(pXmlRowElement->GetText(), tokens);
        for (StringVector::const_iterator iter = tokens.begin(), iterEnd = tokens.end(); iter != iterEnd; +
      +iter)
        {
            T t;
            if (!DQM4HEP::stringToType(*iter, t))
                return STATUS_CODE_FAILURE;
            rowVector.push_back(t);
        }
        vector.push_back(rowVector);
    }
    return STATUS_CODE_SUCCESS;
}
template<typename T > StatusCode dqm4hep::DQMXmlHelper::readParameterValue (const TiXmlHandle & xmlHandle, const std::string & parameterName, T & t) [inline], [static]
Read a parameter value from an xml element.
Definition at line 262 of file DQMXmlHelper.h.
References dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChild(), getAttribute(), dqm4hep::TiXmlNode::NextSiblingElement(), RETURN_RESULT_IF, and dqm4hep::DQM4HEP::stringToType().
Referenced by dqm4hep::DQMDimEventClient::readSettings().
{
    for (TiXmlElement *pXmlElement = xmlHandle.FirstChild("parameter").Element(); NULL != pXmlElement;
        pXmlElement = pXmlElement->NextSiblingElement("parameter"))
    {
      std::string name;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "name", name));
      if(name != parameterName)
        continue;
        if (!DQM4HEP::stringToType(pXmlElement->GetText(), t))
            return STATUS_CODE_FAILURE;
        return STATUS_CODE_SUCCESS;
    }
    return STATUS_CODE_NOT_FOUND;
}
template<typename T > StatusCode dqm4hep::DQMXmlHelper::readParameterValues (const TiXmlHandle & xmlHandle, const std::string & parameterName, std::vector< T > & vector) [inline], [static]
Read a vector of values for a parameter from a (space separated) list in an xml element.
Definition at line 285 of file DQMXmlHelper.h.
References dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChild(), getAttribute(), dqm4hep::TiXmlNode::NextSiblingElement(), RETURN_RESULT_IF, dqm4hep::DQM4HEP::stringToType(), and tokenizeString().
{
    for (TiXmlElement *pXmlElement = xmlHandle.FirstChild("parameter").Element(); NULL != pXmlElement;
        pXmlElement = pXmlElement->NextSiblingElement("parameter"))
    {
      std::string name;
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::getAttribute(pXmlElement, "name", name));
      if(name != parameterName)
        continue;
        StringVector tokens;
        tokenizeString(pXmlElement->GetText(), tokens);
        for (StringVector::const_iterator iter = tokens.begin(), iterEnd = tokens.end(); iter != iterEnd; +
      +iter)
        {
            T t;
            if (!DQM4HEP::stringToType(*iter, t))
                return STATUS_CODE_FAILURE;
            vector.push_back(t);
        }
        return STATUS_CODE_SUCCESS;
    }
    return STATUS_CODE_NOT_FOUND;
}
template<typename T > StatusCode dqm4hep::DQMXmlHelper::readValue (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, T & t) [inline], [static]
Read a value from an xml element.
Definition at line 101 of file DQMXmlHelper.h.
References dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChild(), dqm4hep::TiXmlElement::GetText(), and dqm4hep::DQM4HEP::stringToType().
Referenced by dqm4hep::DQMMeanWithinExpectedTest::readSettings(), and dqm4hep::DQMChi2FitFunctionTest::readSettings().
{
    const TiXmlElement *const pXmlElement = xmlHandle.FirstChild(xmlElementName).Element();
    if (NULL == pXmlElement)
        return STATUS_CODE_NOT_FOUND;
    if (!DQM4HEP::stringToType(pXmlElement->GetText(), t))
        return STATUS_CODE_FAILURE;
    return STATUS_CODE_SUCCESS;
}
template<> StatusCode dqm4hep::DQMXmlHelper::readValue (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, bool & t) [inline]
Definition at line 117 of file DQMXmlHelper.h.
References dqm4hep::TiXmlNode::FirstChild(), and dqm4hep::TiXmlElement::GetText().
{
    const TiXmlElement *const pXmlElement = xmlHandle.FirstChild(xmlElementName).Element();
    if (NULL == pXmlElement)
        return STATUS_CODE_NOT_FOUND;
    const std::string xmlElementString = pXmlElement->GetText();
    if ((xmlElementString == "1") || (xmlElementString == "true"))
    {
        t = true;
    }
    else if ((xmlElementString == "0") || (xmlElementString == "false"))
    {
        t = false;
    }
    else
    {
        return STATUS_CODE_FAILURE;
    }
    return STATUS_CODE_SUCCESS;
}
template<typename T > StatusCode dqm4hep::DQMXmlHelper::readVectorOfValues (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, std::vector< T > & vector) [inline], [static]
Read a vector of values from a (space separated) list in an xml element.
Definition at line 145 of file DQMXmlHelper.h.
References dqm4hep::TiXmlHandle::Element(), dqm4hep::TiXmlHandle::FirstChild(), dqm4hep::TiXmlElement::GetText(), dqm4hep::DQM4HEP::stringToType(), and tokenizeString().
Referenced by dqm4hep::DQMChi2FitFunctionTest::readSettings().
{
    const TiXmlElement *const pXmlElement = xmlHandle.FirstChild(xmlElementName).Element();
    if (NULL == pXmlElement)
        return STATUS_CODE_NOT_FOUND;
    StringVector tokens;
    tokenizeString(pXmlElement->GetText(), tokens);
    for (StringVector::const_iterator iter = tokens.begin(), iterEnd = tokens.end(); iter != iterEnd; ++
      iter)
    {
        T t;
        if (!DQM4HEP::stringToType(*iter, t))
            return STATUS_CODE_FAILURE;
        vector.push_back(t);
    }
    return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMXmlHelper::tokenizeString (const std::string & inputString, StringVector & tokens, const std::string & delimiter = ` `) [static]
Tokenize a string.
Definition at line 38 of file DQMXmlHelper.cc.
Referenced by read2DVectorOfValues(), readParameterValues(), and readVectorOfValues().
{
    std::string::size_type lastPos = inputString.find_first_not_of(delimiter, 0);
    std::string::size_type pos = inputString.find_first_of(delimiter, lastPos);
    while ((std::string::npos != pos) || (std::string::npos != lastPos))
    {
        tokens.push_back(inputString.substr(lastPos, pos - lastPos));
        lastPos = inputString.find_first_not_of(delimiter, pos);
        pos = inputString.find_first_of(delimiter, lastPos);
    }
}
The documentation for this class was generated from the following files:
DQMXmlHelper.h
DQMXmlHelper.cc