dqm4hep::DQMQualityTest Class Reference
DQMQualityTest class.
#include <DQMQualityTest.h>
Public Member Functions
DQMQualityTest (const std::string &name)
Constructor with quality test name (unique identifier)
virtual ~DQMQualityTest ()
Destructor.
const std::string & getType () const
Get the quality test type.
const std::string & getName () const
Get the quality test name (unique identifier)
const std::string & getMessage () const
Get the message after quality test.
DQMQuality getQuality () const
Get the quality flag.
bool isSuccessful () const
Whether the quality test is successful.
Protected Member Functions
virtual StatusCode readSettings (const TiXmlHandle xmlHandle)=0
Read the settings from the xml handle.
virtual StatusCode init ()=0
Initialize the quality test.
virtual StatusCode run (DQMMonitorElement *pMonitorElement)=0
Runs a quality test on the given monitor element.
virtual bool canRun (DQMMonitorElement *pMonitorElement) const =0
Whether the quality test can be run on the monitor element.
Protected Attributes
std::string m_message
bool m_isSuccessful
DQMQuality m_quality
Private Member Functions
StatusCode run (DQMMonitorElement *pMonitorElement, DQMQualityTestResult &result)
Perform the quality test result and fill the quality test result object.
Private Attributes
std::string m_type
std::string m_name
Friends
class DQMMonitorElementManager
class DQMMonitorElement
Detailed Description
DQMQualityTest class.
Definition at line 78 of file DQMQualityTest.h.
Constructor & Destructor Documentation
dqm4hep::DQMQualityTest::DQMQualityTest (const std::string & name)
Constructor with quality test name (unique identifier)
Definition at line 104 of file DQMQualityTest.cc.
                                                    :
    m_name(name),
    m_quality(NO_QUALITY),
    m_isSuccessful(true)
{
  /* nop */
}
dqm4hep::DQMQualityTest::~DQMQualityTest () [virtual]
Destructor.
Definition at line 114 of file DQMQualityTest.cc.
{
  /* nop */
}
Member Function Documentation
virtual bool dqm4hep::DQMQualityTest::canRun (DQMMonitorElement * pMonitorElement) const [protected], [pure virtual]
Whether the quality test can be run on the monitor element.
Implemented in dqm4hep::DQMChi2FitFunctionTest , and dqm4hep::DQMMeanWithinExpectedTest .
Referenced by run().
const std::string & dqm4hep::DQMQualityTest::getMessage () const
Get the message after quality test.
Definition at line 135 of file DQMQualityTest.cc.
References m_message.
Referenced by run().
{
  return m_message;
}
const std::string & dqm4hep::DQMQualityTest::getName () const
Get the quality test name (unique identifier)
Definition at line 128 of file DQMQualityTest.cc.
References m_name.
Referenced by run(), and dqm4hep::DQMChi2FitFunctionTest::run().
{
  return m_name;
}
DQMQuality dqm4hep::DQMQualityTest::getQuality () const
Get the quality flag.
Definition at line 149 of file DQMQualityTest.cc.
References m_quality.
Referenced by run().
{
  return m_quality;
}
const std::string & dqm4hep::DQMQualityTest::getType () const
Get the quality test type.
Definition at line 121 of file DQMQualityTest.cc.
References m_type.
Referenced by run().
{
  return m_type;
}
virtual StatusCode dqm4hep::DQMQualityTest::init () [protected], [pure virtual]
Initialize the quality test.
Implemented in dqm4hep::DQMChi2FitFunctionTest , and dqm4hep::DQMMeanWithinExpectedTest .
Referenced by dqm4hep::DQMMonitorElementManager::createQualityTest().
bool dqm4hep::DQMQualityTest::isSuccessful () const
Whether the quality test is successful.
Definition at line 142 of file DQMQualityTest.cc.
References m_isSuccessful.
Referenced by run().
{
  return m_isSuccessful;
}
virtual StatusCode dqm4hep::DQMQualityTest::readSettings (const TiXmlHandle xmlHandle) [protected], [pure virtual]
Read the settings from the xml handle.
Implemented in dqm4hep::DQMChi2FitFunctionTest , and dqm4hep::DQMMeanWithinExpectedTest .
Referenced by dqm4hep::DQMMonitorElementManager::createQualityTest().
virtual StatusCode dqm4hep::DQMQualityTest::run (DQMMonitorElement * pMonitorElement) [protected], [pure virtual]
Runs a quality test on the given monitor element.
Implemented in dqm4hep::DQMChi2FitFunctionTest , and dqm4hep::DQMMeanWithinExpectedTest .
Referenced by run().
StatusCode dqm4hep::DQMQualityTest::run (DQMMonitorElement * pMonitorElement, DQMQualityTestResult & result) [private]
Perform the quality test result and fill the quality test result object.
Definition at line 156 of file DQMQualityTest.cc.
References canRun(), getMessage(), getName(), getQuality(), getType(), isSuccessful(), dqm4hep::DQMQualityTestResult::m_isSuccessful, dqm4hep::DQMQualityTestResult::m_message, dqm4hep::DQMQualityTestResult::m_quality, dqm4hep::DQMQualityTestResult::m_qualityTestName, dqm4hep::DQMQualityTestResult::m_qualityTestType, RETURN_RESULT_IF, and run().
{
  result.m_qualityTestType = this->getType();
  result.m_qualityTestName = this->getName();
  if(this->canRun(pMonitorElement))
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, run(pMonitorElement));
    result.m_message = getMessage();
    result.m_isSuccessful = isSuccessful();
    result.m_quality = getQuality();
  }
  else
  {
    result.m_message = "Couldn't run quality test";
    result.m_isSuccessful = false;
    result.m_quality = NO_QUALITY;
  }
  return STATUS_CODE_SUCCESS;
}
Friends And Related Function Documentation
friend class DQMMonitorElement [friend]
Definition at line 147 of file DQMQualityTest.h.
friend class DQMMonitorElementManager [friend]
Definition at line 146 of file DQMQualityTest.h.
Member Data Documentation
bool dqm4hep::DQMQualityTest::m_isSuccessful [protected]
Definition at line 137 of file DQMQualityTest.h.
Referenced by isSuccessful(), dqm4hep::DQMMeanWithinExpectedTest::run(), and dqm4hep::DQMChi2FitFunctionTest::run().
std::string dqm4hep::DQMQualityTest::m_message [protected]
Definition at line 136 of file DQMQualityTest.h.
Referenced by getMessage(), dqm4hep::DQMMeanWithinExpectedTest::run(), and dqm4hep::DQMChi2FitFunctionTest::run().
std::string dqm4hep::DQMQualityTest::m_name [private]
Definition at line 143 of file DQMQualityTest.h.
Referenced by getName().
DQMQuality dqm4hep::DQMQualityTest::m_quality [protected]
Definition at line 138 of file DQMQualityTest.h.
Referenced by getQuality(), dqm4hep::DQMMeanWithinExpectedTest::run(), and dqm4hep::DQMChi2FitFunctionTest::run().
std::string dqm4hep::DQMQualityTest::m_type [private]
Definition at line 142 of file DQMQualityTest.h.
Referenced by dqm4hep::DQMMonitorElementManager::createQualityTest(), and getType().
The documentation for this class was generated from the following files:
DQMQualityTest.h
DQMQualityTest.cc