dqm4hep::DQMRunControlClient Class Reference
DQMRunControlClient interface.
#include <DQMRunControlClient.h>
Public Member Functions
DQMRunControlClient ()
Constructor.
virtual ~DQMRunControlClient ()
Destructor.
virtual StatusCode connectToService ()=0
Connect to the service.
virtual StatusCode disconnectFromService ()=0
Disconnect from the service.
virtual bool isConnectedToService () const =0
Whether the client is connected to the service.
Additional Inherited Members
Detailed Description
DQMRunControlClient interface.
Definition at line 46 of file DQMRunControlClient.h.
Constructor & Destructor Documentation
dqm4hep::DQMRunControlClient::DQMRunControlClient () [inline]
Constructor.
Definition at line 51 of file DQMRunControlClient.h.
: DQMRunControl () {}
virtual dqm4hep::DQMRunControlClient::~DQMRunControlClient () [inline], [virtual]
Destructor.
Definition at line 55 of file DQMRunControlClient.h.
{}
Member Function Documentation
virtual StatusCode dqm4hep::DQMRunControlClient::connectToService () [pure virtual]
Connect to the service.
Implemented in dqm4hep::DQMDimRunControlClient .
Referenced by dqm4hep::DQMAnalysisModuleApplication::startServices(), and dqm4hep::DQMAnalysisModuleApplication::stopServices().
virtual StatusCode dqm4hep::DQMRunControlClient::disconnectFromService () [pure virtual]
Disconnect from the service.
Implemented in dqm4hep::DQMDimRunControlClient .
virtual bool dqm4hep::DQMRunControlClient::isConnectedToService () const [pure virtual]
Whether the client is connected to the service.
Implemented in dqm4hep::DQMDimRunControlClient .
Referenced by dqm4hep::DQMAnalysisModuleApplication::stopServices().
The documentation for this class was generated from the following file:
DQMRunControlClient.h