dqm4hep::DQMDimEventCollector Class Reference
DQMDimEventCollector class.
#include <DQMDimEventCollector.h>
Classes
class Client
Client class.
Public Member Functions
DQMDimEventCollector ()
Constructor.
virtual ~DQMDimEventCollector ()
Destructor.
StatusCode setCollectorName (const std::string &collectorName)
Set the collector name.
const std::string & getCollectorName () const
Get the collector name.
bool isRunning () const
Whether the collector server is running.
StatusCode startCollector ()
Start the collector server.
StatusCode stopCollector ()
Stop the collector server.
void setEventStreamer (DQMEventStreamer *pEventStreamer)
Set the event streamer to serialize/deserialize the in/out-coming events.
DQMEventStreamer * getEventStreamer () const
Get the event streamer.
Private Types
typedef std::map< int, Client > ClientMap
Private Member Functions
void commandHandler ()
Dim command handler.
void clientExitHandler ()
Dim client exit handler.
void handleEventReception (DimCommand *pDimCommand)
void handleEventRequest (DimEventRequestRpc *pDimRpc)
Client & getClient (int clientId)
Get a client by id.
void updateEventService ()
Update the event service for clients that have specified an update mode.
void removeClient (int clientId)
Remove a client from the map.
Private Attributes
std::string m_collectorName
bool m_isRunning
int m_state
int m_clientRegisteredId
DimService * m_pServerStateService
DimService * m_pClientRegisteredService
DimService * m_pEventUpdateService
DQMStatisticsService * m_pStatisticsService
DimCommand * m_pCollectEventCommand
DimCommand * m_pUpdateModeCommand
DimCommand * m_pSubEventIdentifierCommand
DimCommand * m_pClientRegitrationCommand
DimEventRequestRpc * m_pEventRequestRpc
DQMDataStream m_dataStream
DQMDataStream m_subEventDataStream
DQMEventStreamer * m_pEventStreamer
DQMEvent * m_pCurrentEvent
ClientMap m_clientMap
Friends
class DimEventRequestRpc
Detailed Description
DQMDimEventCollector class.
Definition at line 67 of file DQMDimEventCollector.h.
Member Typedef Documentation
typedef std::map<int, Client> dqm4hep::DQMDimEventCollector::ClientMap [private]
Definition at line 153 of file DQMDimEventCollector.h.
Constructor & Destructor Documentation
dqm4hep::DQMDimEventCollector::DQMDimEventCollector ()
Constructor.
Definition at line 53 of file DQMDimEventCollector.cc.
References m_dataStream, THROW_RESULT_IF, and dqm4hep::DQMDataStream::write().
                                           :
    m_collectorName("DEFAULT"),
    m_isRunning(false),
    m_pCollectEventCommand(NULL),
    m_pEventRequestRpc(NULL),
    m_pUpdateModeCommand(NULL),
    m_pEventUpdateService(NULL),
    m_pEventStreamer(NULL),
    m_pCurrentEvent(NULL),
    m_state(0),
    m_clientRegisteredId(0),
    m_dataStream(5*1024*1024),
    m_subEventDataStream(5*1024*1024)
{
  THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.write(std::string("EMPTY")));
  DimServer::addClientExitHandler(this);
}
dqm4hep::DQMDimEventCollector::~DQMDimEventCollector () [virtual]
Destructor.
Definition at line 73 of file DQMDimEventCollector.cc.
References isRunning(), m_pCurrentEvent, m_pEventStreamer, and stopCollector().
{
  if(isRunning())
    stopCollector();
  if(m_pEventStreamer)
    delete m_pEventStreamer;
  if(m_pCurrentEvent)
    delete m_pCurrentEvent;
}
Member Function Documentation
void dqm4hep::DQMDimEventCollector::clientExitHandler () [private]
Dim client exit handler.
Definition at line 372 of file DQMDimEventCollector.cc.
References removeClient().
{
  this->removeClient(getClientId());
}
void dqm4hep::DQMDimEventCollector::commandHandler () [private]
Dim command handler.
Definition at line 298 of file DQMDimEventCollector.cc.
References dqm4hep::DEBUG, getClient(), handleEventReception(), m_clientRegisteredId, m_pClientRegisteredService, m_pClientRegitrationCommand, m_pCollectEventCommand, m_pSubEventIdentifierCommand, m_pUpdateModeCommand, dqm4hep::DQMDimEventCollector::Client::m_subEventIdentifier, dqm4hep::DQMDimEventCollector::Client::m_updateMode, and removeClient().
{
  DimCommand *pCommand = getCommand();
  if(!pCommand)
    return;
  if(pCommand == m_pUpdateModeCommand)
  {
    bool updateMode = static_cast<bool>(pCommand->getInt());
    int clientId = getClientId();
    if(clientId < 0)
      return;
    Client &client = getClient(clientId);
    client.m_updateMode = updateMode;
    return;
  }
  if(pCommand == m_pSubEventIdentifierCommand)
  {
    char *pSubEventIdentifier = pCommand->getString();
    int clientId = getClientId();
    std::string subEventIdentifier;
    if(NULL != pSubEventIdentifier)
      subEventIdentifier = pSubEventIdentifier;
    if(clientId < 0)
      return;
    Client &client = getClient(clientId);
    client.m_subEventIdentifier = subEventIdentifier;
    return;
  }
  if(pCommand == m_pCollectEventCommand)
  {
    this->handleEventReception(pCommand);
    return;
  }
  if(pCommand == m_pClientRegitrationCommand)
  {
    int clientId = getClientId();
    if(clientId < 0)
      return;
    int registerClient = pCommand->getInt();
    if(registerClient)
    {
      Client &client = getClient(clientId);
      streamlog_out(DEBUG) << "Client " << clientId << " added to server !" << std::endl;
      int clientIds[2];
      clientIds[0] = clientId;
      clientIds[1] = 0;
      m_clientRegisteredId = clientId;
      m_pClientRegisteredService->selectiveUpdateService(m_clientRegisteredId, &clientIds[0]);
      m_clientRegisteredId = 0;
    }
    else
    {
      this->removeClient(clientId);
    }
  }
}
DQMDimEventCollector::Client & dqm4hep::DQMDimEventCollector::getClient (int clientId) [private]
Get a client by id.
Create it if not registered
Definition at line 279 of file DQMDimEventCollector.cc.
References dqm4hep::DQMDimEventCollector::Client::m_clientId, and m_clientMap.
Referenced by commandHandler().
{
  ClientMap::iterator findIter = m_clientMap.find(clientId);
  if(m_clientMap.end() != findIter)
    return findIter->second;
  Client newClient;
  newClient.m_clientId = clientId;
  newClient.m_updateMode = false;
  newClient.m_subEventIdentifier = "";
  m_clientMap.insert(std::pair<int, Client>(clientId, newClient));
  return m_clientMap.find(clientId)->second;
}
const std::string & dqm4hep::DQMDimEventCollector::getCollectorName () const [virtual]
Get the collector name.
Implements dqm4hep::DQMEventCollectorImp .
Definition at line 99 of file DQMDimEventCollector.cc.
References m_collectorName.
Referenced by startCollector().
{
  return m_collectorName;
}
DQMEventStreamer * dqm4hep::DQMDimEventCollector::getEventStreamer () const [virtual]
Get the event streamer.
Implements dqm4hep::DQMEventCollectorImp .
Definition at line 189 of file DQMDimEventCollector.cc.
References m_pEventStreamer.
{
  return m_pEventStreamer;
}
void dqm4hep::DQMDimEventCollector::handleEventReception (DimCommand * pDimCommand) [private]
Definition at line 196 of file DQMDimEventCollector.cc.
References dqm4hep::DQMEventStreamer::deserialize(), dqm4hep::ERROR, dqm4hep::StatusCodeException::getStatusCode(), m_dataStream, m_pCurrentEvent, m_pEventStreamer, m_pStatisticsService, dqm4hep::DQMDataStream::setBuffer(), THROW_RESULT_IF, dqm4hep::DQMStatisticsService::update(), and updateEventService().
Referenced by commandHandler().
{
  dqm_char *pBuffer = static_cast<char*>(pDimCommand->getData());
  dqm_uint bufferSize = pDimCommand->getSize();
  if(NULL == pBuffer || 0 == bufferSize)
    return;
  m_pStatisticsService->update(bufferSize);
  DQMEvent *pEvent = NULL;
  try
  {
    THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.setBuffer(pBuffer, bufferSize));
    // if streamer is available, de-serialize the event
    if(NULL != m_pEventStreamer)
    {
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventStreamer->deserialize(pEvent, &
      m_dataStream));
      // replace the current event
      if(NULL != pEvent)
      {
        if(NULL != m_pCurrentEvent)
          delete m_pCurrentEvent;
        m_pCurrentEvent = pEvent;
      }
    }
  }
  catch(StatusCodeException &exception)
  {
    if(NULL != pEvent)
      delete pEvent;
    streamlog_out(ERROR) << "Couldn't deserialize the buffer : " << exception.getStatusCode() << std::endl;
    return;
  }
  this->updateEventService();
}
void dqm4hep::DQMDimEventCollector::handleEventRequest (DimEventRequestRpc * pDimRpc) [private]
Definition at line 241 of file DQMDimEventCollector.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), m_dataStream, m_pCurrentEvent, m_pEventStreamer, m_subEventDataStream, dqm4hep::DQMDataStream::reset(), dqm4hep::DQMEventStreamer::serialize(), and THROW_RESULT_IF.
Referenced by dqm4hep::DimEventRequestRpc::rpcHandler().
{
  char *pSubEventIdentifier = pDimRpc->getString();
  std::string subEventIdentifier;
  if(NULL != pSubEventIdentifier)
    subEventIdentifier = pSubEventIdentifier;
  if(NULL != m_pEventStreamer && NULL != m_pCurrentEvent && !subEventIdentifier.empty())
  {
    try
    {
      m_subEventDataStream.reset();
      THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventStreamer->serialize(
      m_pCurrentEvent, subEventIdentifier, &m_subEventDataStream));
      dqm_char *pEventBuffer = m_subEventDataStream.getBuffer();
      int bufferSize = m_subEventDataStream.getBufferSize();
      pDimRpc->setData((void *) pEventBuffer, bufferSize);
    }
    catch(...)
    {
    }
  }
  else if(NULL != m_dataStream.getBuffer() && 0 != m_dataStream.getBufferSize())
  {
    pDimRpc->setData((void *) m_dataStream.getBuffer(), m_dataStream.
      getBufferSize());
  }
  else
  {
    dqm_char empty [] = "EMPTY";
    pDimRpc->setData((void *) empty, 5);
  }
}
bool dqm4hep::DQMDimEventCollector::isRunning () const [virtual]
Whether the collector server is running.
Implements dqm4hep::DQMEventCollectorImp .
Definition at line 106 of file DQMDimEventCollector.cc.
References m_isRunning.
Referenced by setCollectorName(), startCollector(), stopCollector(), updateEventService(), and ~DQMDimEventCollector().
{
  return m_isRunning;
}
void dqm4hep::DQMDimEventCollector::removeClient (int clientId) [private]
Remove a client from the map.
Definition at line 439 of file DQMDimEventCollector.cc.
References m_clientMap, and dqm4hep::MESSAGE.
Referenced by clientExitHandler(), and commandHandler().
{
  if(clientId < 0)
    return;
  ClientMap::iterator findIter = m_clientMap.find(clientId);
  if(m_clientMap.end() == findIter)
    return;
  m_clientMap.erase(findIter);
  streamlog_out(MESSAGE) << "Client " << clientId << " removed from server !" << std::endl;
}
StatusCode dqm4hep::DQMDimEventCollector::setCollectorName (const std::string & collectorName) [virtual]
Set the collector name.
Implements dqm4hep::DQMEventCollectorImp .
Definition at line 87 of file DQMDimEventCollector.cc.
References isRunning(), and m_collectorName.
{
  if(isRunning())
    return STATUS_CODE_NOT_ALLOWED;
  m_collectorName = collectorName;
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMDimEventCollector::setEventStreamer (DQMEventStreamer * pEventStreamer) [virtual]
Set the event streamer to serialize/deserialize the in/out-coming events.
Implements dqm4hep::DQMEventCollectorImp .
Definition at line 179 of file DQMDimEventCollector.cc.
References m_pEventStreamer.
{
  if(m_pEventStreamer)
    delete m_pEventStreamer;
  m_pEventStreamer = pEventStreamer;
}
StatusCode dqm4hep::DQMDimEventCollector::startCollector () [virtual]
Start the collector server.
Implements dqm4hep::DQMEventCollectorImp .
Definition at line 113 of file DQMDimEventCollector.cc.
References DimEventRequestRpc, dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), getCollectorName(), isRunning(), m_clientRegisteredId, m_dataStream, m_isRunning, m_pClientRegisteredService, m_pClientRegitrationCommand, m_pCollectEventCommand, m_pEventRequestRpc, m_pEventUpdateService, m_pServerStateService, m_pStatisticsService, m_pSubEventIdentifierCommand, m_pUpdateModeCommand, m_state, and dqm4hep::MESSAGE.
{
  if(this->isRunning())
    return STATUS_CODE_SUCCESS;
  m_pEventRequestRpc = new DimEventRequestRpc(this);
  m_pUpdateModeCommand = new DimCommand(("DQM4HEP/EventCollector/" +
      getCollectorName() + "/UPDATE_MODE").c_str(), "I", this);
  m_pCollectEventCommand = new DimCommand(("DQM4HEP/EventCollector/" +
      getCollectorName() + "/COLLECT_RAW_EVENT").c_str(), "C", this);
  m_pSubEventIdentifierCommand = new DimCommand(("DQM4HEP/EventCollector/" +
      getCollectorName() + "/SUB_EVENT_IDENTIFIER").c_str(), "C", this);
  m_pClientRegitrationCommand = new DimCommand(("DQM4HEP/EventCollector/" +
      getCollectorName() + "/CLIENT_REGISTRATION").c_str(), "I", this);
  m_pEventUpdateService = new DimService(("DQM4HEP/EventCollector/" +
      getCollectorName() + "/EVENT_RAW_UPDATE").c_str(), "C", (void*) m_dataStream.
      getBuffer(), m_dataStream.getBufferSize());
  m_pStatisticsService = new DQMStatisticsService("DQM4HEP/EventCollector/" +
      getCollectorName() + "/STATS");
  m_pClientRegisteredService = new DimService(("DQM4HEP/EventCollector/" +
      getCollectorName() + "/CLIENT_REGISTERED").c_str(), m_clientRegisteredId);
  m_pServerStateService = new DimService(("DQM4HEP/EventCollector/" +
      getCollectorName() + "/SERVER_STATE").c_str(), m_state);
  // inform clients that the server is available for registrations
  streamlog_out(MESSAGE) << "Changing server application to running !" << std::endl;
  DimServer::start(("DQM4HEP/EventCollector/" + getCollectorName()).c_str());
  // time needed for registration on dns node
  sleep(1);
  m_state = 1;
  m_pServerStateService->updateService(m_state);
  m_isRunning = true;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMDimEventCollector::stopCollector () [virtual]
Stop the collector server.
Implements dqm4hep::DQMEventCollectorImp .
Definition at line 148 of file DQMDimEventCollector.cc.
References isRunning(), m_dataStream, m_isRunning, m_pClientRegisteredService, m_pClientRegitrationCommand, m_pCollectEventCommand, m_pEventRequestRpc, m_pEventUpdateService, m_pServerStateService, m_pStatisticsService, m_pSubEventIdentifierCommand, m_pUpdateModeCommand, m_state, dqm4hep::DQMDataStream::reset(), RETURN_RESULT_IF, and dqm4hep::DQMDataStream::write().
Referenced by ~DQMDimEventCollector().
{
  if(!this->isRunning())
    return STATUS_CODE_SUCCESS;
  m_state = 0;
  // inform clients that the server is shut down
  m_pServerStateService->updateService(m_state);
  delete m_pCollectEventCommand;
  delete m_pUpdateModeCommand;
  delete m_pSubEventIdentifierCommand;
  delete m_pClientRegitrationCommand;
  delete m_pEventUpdateService;
  delete m_pStatisticsService;
  delete m_pClientRegisteredService;
  delete m_pServerStateService;
  delete m_pEventRequestRpc;
  m_dataStream.reset();
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_dataStream.write(std::string("EMPTY")));
  m_isRunning = false;
  return STATUS_CODE_SUCCESS;
}
void dqm4hep::DQMDimEventCollector::updateEventService () [private]
Update the event service for clients that have specified an update mode.
Definition at line 379 of file DQMDimEventCollector.cc.
References dqm4hep::DQMDataStream::getBuffer(), dqm4hep::DQMDataStream::getBufferSize(), isRunning(), m_clientMap, m_dataStream, m_pCurrentEvent, m_pEventStreamer, m_pEventUpdateService, m_subEventDataStream, dqm4hep::DQMDataStream::reset(), and dqm4hep::DQMEventStreamer::serialize().
Referenced by handleEventReception().
{
  // if not running, do not update
  if(!isRunning())
    return;
  // event available ?
  if(NULL == m_dataStream.getBuffer() || 0 == m_dataStream.getBufferSize())
    return;
  int *clientIds = new int[m_clientMap.size()];
  memset(&clientIds[0], 0, m_clientMap.size());
  int currentId = 0;
  for(ClientMap::iterator iter = m_clientMap.begin(), endIter = m_clientMap.end() ;
      endIter != iter ; ++iter)
  {
    // check for update mode
    if(!iter->second.m_updateMode)
      continue;
    // specific case where the client has queried a sub part of the event
    if(!iter->second.m_subEventIdentifier.empty()
    && (NULL != m_pEventStreamer && NULL != m_pCurrentEvent))
    {
      // try to serialize the sub event
      m_subEventDataStream.reset();
      if(STATUS_CODE_SUCCESS != m_pEventStreamer->serialize(m_pCurrentEvent, iter->second.
      m_subEventIdentifier, &m_subEventDataStream))
        continue;
      dqm_char *pEventBuffer = m_subEventDataStream.getBuffer();
      int bufferSize = m_subEventDataStream.getBufferSize();
      if(NULL == pEventBuffer || 0 == bufferSize)
        continue;
      int clientIdArray[2];
      clientIdArray[0] = iter->first;
      clientIdArray[1] = 0;
      m_pEventUpdateService->selectiveUpdateService((void *) pEventBuffer, bufferSize, &clientIdArray[0]);
      continue;
    }
    clientIds[currentId] = iter->first;
    currentId ++;
  }
  if(currentId != 0)
    m_pEventUpdateService->selectiveUpdateService((void *) m_dataStream.
      getBuffer(), m_dataStream.getBufferSize(), clientIds);
  delete [] clientIds;
  return;
}
Friends And Related Function Documentation
friend class DimEventRequestRpc [friend]
Definition at line 70 of file DQMDimEventCollector.h.
Referenced by startCollector().
Member Data Documentation
ClientMap dqm4hep::DQMDimEventCollector::m_clientMap [private]
Definition at line 183 of file DQMDimEventCollector.h.
Referenced by getClient(), removeClient(), and updateEventService().
int dqm4hep::DQMDimEventCollector::m_clientRegisteredId [private]
Definition at line 158 of file DQMDimEventCollector.h.
Referenced by commandHandler(), and startCollector().
std::string dqm4hep::DQMDimEventCollector::m_collectorName [private]
Definition at line 155 of file DQMDimEventCollector.h.
Referenced by getCollectorName(), and setCollectorName().
DQMDataStream dqm4hep::DQMDimEventCollector::m_dataStream [private]
Definition at line 175 of file DQMDimEventCollector.h.
Referenced by DQMDimEventCollector(), handleEventReception(), handleEventRequest(), startCollector(), stopCollector(), and updateEventService().
bool dqm4hep::DQMDimEventCollector::m_isRunning [private]
Definition at line 156 of file DQMDimEventCollector.h.
Referenced by isRunning(), startCollector(), and stopCollector().
DimService* dqm4hep::DQMDimEventCollector::m_pClientRegisteredService [private]
Definition at line 162 of file DQMDimEventCollector.h.
Referenced by commandHandler(), startCollector(), and stopCollector().
DimCommand* dqm4hep::DQMDimEventCollector::m_pClientRegitrationCommand [private]
Definition at line 170 of file DQMDimEventCollector.h.
Referenced by commandHandler(), startCollector(), and stopCollector().
DimCommand* dqm4hep::DQMDimEventCollector::m_pCollectEventCommand [private]
Definition at line 167 of file DQMDimEventCollector.h.
Referenced by commandHandler(), startCollector(), and stopCollector().
DQMEvent* dqm4hep::DQMDimEventCollector::m_pCurrentEvent [private]
Definition at line 181 of file DQMDimEventCollector.h.
Referenced by handleEventReception(), handleEventRequest(), updateEventService(), and ~DQMDimEventCollector().
DimEventRequestRpc* dqm4hep::DQMDimEventCollector::m_pEventRequestRpc [private]
Definition at line 173 of file DQMDimEventCollector.h.
Referenced by startCollector(), and stopCollector().
DQMEventStreamer* dqm4hep::DQMDimEventCollector::m_pEventStreamer [private]
Definition at line 177 of file DQMDimEventCollector.h.
Referenced by getEventStreamer(), handleEventReception(), handleEventRequest(), setEventStreamer(), updateEventService(), and ~DQMDimEventCollector().
DimService* dqm4hep::DQMDimEventCollector::m_pEventUpdateService [private]
Definition at line 163 of file DQMDimEventCollector.h.
Referenced by startCollector(), stopCollector(), and updateEventService().
DimService* dqm4hep::DQMDimEventCollector::m_pServerStateService [private]
Definition at line 161 of file DQMDimEventCollector.h.
Referenced by startCollector(), and stopCollector().
DQMStatisticsService* dqm4hep::DQMDimEventCollector::m_pStatisticsService [private]
Definition at line 164 of file DQMDimEventCollector.h.
Referenced by handleEventReception(), startCollector(), and stopCollector().
DimCommand* dqm4hep::DQMDimEventCollector::m_pSubEventIdentifierCommand [private]
Definition at line 169 of file DQMDimEventCollector.h.
Referenced by commandHandler(), startCollector(), and stopCollector().
DimCommand* dqm4hep::DQMDimEventCollector::m_pUpdateModeCommand [private]
Definition at line 168 of file DQMDimEventCollector.h.
Referenced by commandHandler(), startCollector(), and stopCollector().
int dqm4hep::DQMDimEventCollector::m_state [private]
Definition at line 157 of file DQMDimEventCollector.h.
Referenced by startCollector(), and stopCollector().
DQMDataStream dqm4hep::DQMDimEventCollector::m_subEventDataStream [private]
Definition at line 176 of file DQMDimEventCollector.h.
Referenced by handleEventRequest(), and updateEventService().
The documentation for this class was generated from the following files:
DQMDimEventCollector.h
DQMDimEventCollector.cc