dqm4hep::DQMStorage Class Reference
DQMStorage class.
#include <DQMStorage.h>
Public Member Functions
DQMStorage (bool owner=true)
Constructor.
~DQMStorage ()
Destructor.
StatusCode mkdir (const std::string &dirName)
Create a new directory.
void cd ()
Go back to root directory.
StatusCode cd (const std::string &dirName)
Go to directory.
void ls (bool recursive=false) const
List the current directory contents.
bool dirExists (const std::string &dirName) const
Whether the directory exists.
const std::string & pwd () const
Get the current directory name.
StatusCode goUp ()
Navigate backward in the directory structure.
StatusCode rmdir (const std::string &fullDirName)
Remove the given directory.
bool isOwner () const
Whether the storage is the owner of the monitor elements.
StatusCode addMonitorElement (DQMMonitorElement *pMonitorElement)
Add a monitor element to the current directory.
StatusCode addMonitorElement (const std::string &dirName, DQMMonitorElement *pMonitorElement)
Add a monitor element to the given directory.
StatusCode removeMonitorElement (const std::string &monitorElementName)
Remove a monitor element from the current directory.
StatusCode removeMonitorElement (const std::string &dirName, const std::string &monitorElementName)
Remove a monitor element from the given directory.
StatusCode getMonitorElement (const std::string &monitorElementName, DQMMonitorElement *&pMonitorElement) const
Get the monitor element in the current directory.
StatusCode getMonitorElement (const std::string &dirName, const std::string &monitorElementName, DQMMonitorElement *&pMonitorElement) const
Get the monitor element in the given directory.
StatusCode getAllMonitorElements (std::vector< DQMMonitorElement * > &monitorElementList)
Get all monitor elements in all the directories starting from the root directory.
bool monitorElementExists (DQMMonitorElement *pMonitorElement) const
Whether the monitor element exists in the current dir.
bool monitorElementExists (const std::string &dirName, DQMMonitorElement *pMonitorElement) const
Whether the monitor element exists in the current dir.
StatusCode clear ()
Clear the storage.
DQMDirectory * getRootDirectory () const
Get the root directory.
DQMDirectory * getCurrentDirectory () const
Get the current directory.
StatusCode findDir (const std::string &dirName, DQMDirectory *&pDirectory) const
Find a sub directory.
Static Public Member Functions
static StatusCode recursiveContentList (DQMDirectory *pDirectory, std::vector< DQMMonitorElement * > &monitorElementList)
Get recursively all the monitor elements in the sub dirs.
Private Attributes
DQMDirectory * m_pCurrentDir
DQMDirectory * m_pRootDir
bool m_isOwner
Detailed Description
DQMStorage class.
A simple storage class for monitor elements with a directory structure (see DQMDirectory).
All dirName strings passed in argument of this interface refers to an absolute path if it starts by the '/' character. In this case it is considered to start from the root dir and else from the current directory.
Set the storage to be the owner of the monitor elements by passing the flag owner to true in the constructor.
Definition at line 54 of file DQMStorage.h.
Constructor & Destructor Documentation
dqm4hep::DQMStorage::DQMStorage (bool owner = true)
Constructor.
Definition at line 38 of file DQMStorage.cc.
References m_pCurrentDir, and m_pRootDir.
                                 :
    m_isOwner(owner)
{
  m_pRootDir = new DQMDirectory("");
  m_pCurrentDir = m_pRootDir;
}
dqm4hep::DQMStorage::~DQMStorage ()
Destructor.
Definition at line 47 of file DQMStorage.cc.
References m_pCurrentDir, and m_pRootDir.
{
  delete m_pRootDir;
  m_pCurrentDir = NULL;
}
Member Function Documentation
StatusCode dqm4hep::DQMStorage::addMonitorElement (DQMMonitorElement * pMonitorElement)
Add a monitor element to the current directory.
Definition at line 268 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::addMonitorElement(), dqm4hep::DQMDirectory::getFullPathName(), m_pCurrentDir, and dqm4hep::DQMMonitorElement::setPath().
Referenced by dqm4hep::DQMMonitorElementManager::bookCharHistogram1D(), dqm4hep::DQMMonitorElementManager::bookCharHistogram2D(), dqm4hep::DQMMonitorElementManager::bookFloat(), dqm4hep::DQMMonitorElementManager::bookInt(), dqm4hep::DQMMonitorElementManager::bookIntHistogram1D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram2D(), dqm4hep::DQMMonitorElementManager::bookObject(), dqm4hep::DQMMonitorElementManager::bookProfile1D(), dqm4hep::DQMMonitorElementManager::bookProfile2D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram1D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram2D(), dqm4hep::DQMMonitorElementManager::bookShort(), dqm4hep::DQMMonitorElementManager::bookShortHistogram1D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram2D(), and dqm4hep::DQMMonitorElementManager::bookString().
{
  DQMPath path = m_pCurrentDir->getFullPathName();
  pMonitorElement->setPath(path);
  return m_pCurrentDir->addMonitorElement(pMonitorElement);
}
StatusCode dqm4hep::DQMStorage::addMonitorElement (const std::string & dirName, DQMMonitorElement * pMonitorElement)
Add a monitor element to the given directory.
Definition at line 278 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::addMonitorElement(), findDir(), dqm4hep::DQMDirectory::getFullPathName(), mkdir(), RETURN_RESULT_IF, and dqm4hep::DQMMonitorElement::setPath().
{
  DQMDirectory *pDirectory = NULL;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, mkdir(dirName));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, findDir(dirName, pDirectory));
  DQMPath path = pDirectory->getFullPathName();
  pMonitorElement->setPath(path);
  return pDirectory->addMonitorElement(pMonitorElement);
}
void dqm4hep::DQMStorage::cd ()
Go back to root directory.
Definition at line 93 of file DQMStorage.cc.
References m_pCurrentDir, and m_pRootDir.
Referenced by dqm4hep::DQMMonitorElementManager::cd(), and cd().
{
  m_pCurrentDir = m_pRootDir;
}
StatusCode dqm4hep::DQMStorage::cd (const std::string & dirName)
Go to directory.
If dirName starts with '/' then the path is absolute and refers to the root directory. Any directory matching `..` referes to the parent dir (unix style)
Definition at line 100 of file DQMStorage.cc.
References cd(), dqm4hep::DQMDirectory::findDir(), dqm4hep::DQMPath::getSplitPath(), dqm4hep::DQMPath::isRelative(), dqm4hep::DQMPath::isValid(), m_pCurrentDir, m_pRootDir, and RETURN_RESULT_IF.
{
  // go back to sub dir
  if(dirName.empty())
  {
    cd();
    return STATUS_CODE_SUCCESS;
  }
  DQMPath path(dirName);
  if(!path.isValid())
    return STATUS_CODE_INVALID_PARAMETER;
// bool startFromRoot = dirName[0] == '/';
// DQMDirectory *pDirectory = startFromRoot ? m_pRootDir : m_pCurrentDir;
  DQMDirectory *pDirectory = !path.isRelative() ? m_pRootDir : m_pCurrentDir;
// StringVector directoryList;
// DQM4HEP::tokenize(dirName, directoryList, "/");
  StringVector directoryList = path.getSplitPath();
  for(StringVector::iterator iter = directoryList.begin(), endIter = directoryList.end() ;
      endIter != iter ; ++iter)
  {
    std::string dirName = *iter;
    // navigate forward
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDirectory->findDir(dirName, pDirectory));
  }
  if(NULL == pDirectory)
    return STATUS_CODE_FAILURE;
  m_pCurrentDir = pDirectory;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMStorage::clear ()
Clear the storage.
If the flag 'owner' in the constructor has been passed, then the monitor elements will be deleted recursively. Users can check the flag using the method isOwner()
Definition at line 400 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::clear(), m_pCurrentDir, m_pRootDir, and RETURN_RESULT_IF.
{
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRootDir->clear(true));
  m_pCurrentDir = m_pRootDir;
  return STATUS_CODE_SUCCESS;
}
bool dqm4hep::DQMStorage::dirExists (const std::string & dirName) const
Whether the directory exists.
Definition at line 150 of file DQMStorage.cc.
References findDir().
Referenced by monitorElementExists().
{
  DQMDirectory *pDirectory = NULL;
  return findDir(dirName, pDirectory) == STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMStorage::findDir (const std::string & dirName, DQMDirectory *& pDirectory) const
Find a sub directory.
Definition at line 204 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::findDir(), dqm4hep::DQMPath::getSplitPath(), dqm4hep::DQMPath::isRelative(), dqm4hep::DQMPath::isValid(), m_pCurrentDir, and m_pRootDir.
Referenced by addMonitorElement(), dqm4hep::DQMMonitorElementManager::bookCharHistogram1D(), dqm4hep::DQMMonitorElementManager::bookCharHistogram2D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram1D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram2D(), dqm4hep::DQMMonitorElementManager::bookProfile1D(), dqm4hep::DQMMonitorElementManager::bookProfile2D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram1D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram2D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram1D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram2D(), dirExists(), dqm4hep::DQMMonitorElementManager::getFullPathName(), getMonitorElement(), monitorElementExists(), removeMonitorElement(), and rmdir().
{
  pDirectory = NULL;
  // go back to sub dir
  if(dirName.empty() || dirName == "." || dirName == "./")
  {
    pDirectory = m_pCurrentDir;
    return STATUS_CODE_SUCCESS;
  }
  DQMPath path(dirName);
  if(!path.isValid())
    return STATUS_CODE_INVALID_PARAMETER;
// bool startFromRoot = dirName[0] == '/';
// DQMDirectory *pDirectory = startFromRoot ? m_pRootDir : m_pCurrentDir;
  pDirectory = !path.isRelative() ? m_pRootDir : m_pCurrentDir;
// StringVector directoryList;
// DQM4HEP::tokenize(dirName, directoryList, "/");
  StringVector directoryList = path.getSplitPath();
  for(StringVector::iterator iter = directoryList.begin(), endIter = directoryList.end() ;
      endIter != iter ; ++iter)
  {
    std::string dirName = *iter;
    // navigate forward
    StatusCode statusCode = pDirectory->findDir(dirName, pDirectory);
    if(statusCode != STATUS_CODE_SUCCESS)
      return statusCode;
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMStorage::getAllMonitorElements (std::vector< DQMMonitorElement * > & monitorElementList)
Get all monitor elements in all the directories starting from the root directory.
Definition at line 366 of file DQMStorage.cc.
References m_pRootDir, and recursiveContentList().
Referenced by dqm4hep::DQMMonitorElementManager::getAllMonitorElements().
{
  return DQMStorage::recursiveContentList(m_pRootDir, monitorElementList);
}
DQMDirectory * dqm4hep::DQMStorage::getCurrentDirectory () const
Get the current directory.
Definition at line 254 of file DQMStorage.cc.
References m_pCurrentDir.
Referenced by dqm4hep::DQMMonitorElementManager::bookCharHistogram1D(), dqm4hep::DQMMonitorElementManager::bookCharHistogram2D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram1D(), dqm4hep::DQMMonitorElementManager::bookIntHistogram2D(), dqm4hep::DQMMonitorElementManager::bookProfile1D(), dqm4hep::DQMMonitorElementManager::bookProfile2D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram1D(), dqm4hep::DQMMonitorElementManager::bookRealHistogram2D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram1D(), dqm4hep::DQMMonitorElementManager::bookShortHistogram2D(), dqm4hep::DQMMonitorElementManager::getCurrentDirectoryFullPathName(), and dqm4hep::DQMMonitorElementManager::getCurrentDirectoryName().
{
  return m_pCurrentDir;
}
StatusCode dqm4hep::DQMStorage::getMonitorElement (const std::string & monitorElementName, DQMMonitorElement *& pMonitorElement) const
Get the monitor element in the current directory.
Definition at line 327 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::findMonitorElement(), and m_pCurrentDir.
Referenced by dqm4hep::DQMMonitorElementManager::deleteMonitorElement(), and dqm4hep::DQMMonitorElementManager::getMonitorElement().
{
  pMonitorElement = NULL;
  return m_pCurrentDir->findMonitorElement(monitorElementName, pMonitorElement);
}
StatusCode dqm4hep::DQMStorage::getMonitorElement (const std::string & dirName, const std::string & monitorElementName, DQMMonitorElement *& pMonitorElement) const
Get the monitor element in the given directory.
Definition at line 335 of file DQMStorage.cc.
References findDir(), dqm4hep::DQMDirectory::findMonitorElement(), and RETURN_RESULT_IF.
{
  DQMDirectory *pDirectory = NULL;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, findDir(dirName, pDirectory));
  return pDirectory->findMonitorElement(monitorElementName, pMonitorElement);
}
DQMDirectory * dqm4hep::DQMStorage::getRootDirectory () const
Get the root directory.
Definition at line 247 of file DQMStorage.cc.
References m_pRootDir.
Referenced by dqm4hep::DQMArchiver::archive().
{
  return m_pRootDir;
}
StatusCode dqm4hep::DQMStorage::goUp ()
Navigate backward in the directory structure.
Equivalent to cd(`..`)
Definition at line 165 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::getParentDir(), dqm4hep::DQMDirectory::isRootDir(), and m_pCurrentDir.
Referenced by dqm4hep::DQMMonitorElementManager::goUp().
{
  if(m_pCurrentDir->isRootDir())
    return STATUS_CODE_NOT_ALLOWED;
  m_pCurrentDir = m_pCurrentDir->getParentDir();
  return STATUS_CODE_SUCCESS;
}
bool dqm4hep::DQMStorage::isOwner () const
Whether the storage is the owner of the monitor elements.
Definition at line 261 of file DQMStorage.cc.
References m_isOwner.
Referenced by dqm4hep::DQMMonitorElementManager::deleteMonitorElement(), and removeMonitorElement().
{
  return m_isOwner;
}
void dqm4hep::DQMStorage::ls (bool recursive = false) const
List the current directory contents.
Definition at line 143 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::ls(), and m_pCurrentDir.
Referenced by dqm4hep::DQMMonitorElementManager::ls().
{
  m_pCurrentDir->ls(recursive);
}
StatusCode dqm4hep::DQMStorage::mkdir (const std::string & dirName)
Create a new directory.
Definition at line 55 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::containsDir(), dqm4hep::DQMDirectory::findDir(), dqm4hep::DQMPath::getSplitPath(), dqm4hep::DQMPath::isRelative(), dqm4hep::DQMPath::isValid(), m_pCurrentDir, m_pRootDir, dqm4hep::DQMDirectory::mkdir(), and RETURN_RESULT_IF.
Referenced by addMonitorElement(), and dqm4hep::DQMMonitorElementManager::mkdir().
{
  if(dirName.empty())
    return STATUS_CODE_INVALID_PARAMETER;
  DQMPath path(dirName);
  if(!path.isValid())
    return STATUS_CODE_INVALID_PARAMETER;
// bool startFromRoot = dirName[0] == '/';
// DQMDirectory *pDirectory = startFromRoot ? m_pRootDir : m_pCurrentDir;
  DQMDirectory *pDirectory = !path.isRelative() ? m_pRootDir : m_pCurrentDir;
// StringVector directoryList;
// DQM4HEP::tokenize(dirName, directoryList, "/");
  StringVector directoryList = path.getSplitPath();
  for(StringVector::iterator iter = directoryList.begin(), endIter = directoryList.end() ;
      endIter != iter ; ++iter)
  {
    std::string dirName = *iter;
    // if sub dir doesn't exists, create it
    if(!pDirectory->containsDir(dirName))
      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDirectory->mkdir(dirName));
    // navigate forward
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDirectory->findDir(dirName, pDirectory));
  }
  return STATUS_CODE_SUCCESS;
}
bool dqm4hep::DQMStorage::monitorElementExists (DQMMonitorElement * pMonitorElement) const
Whether the monitor element exists in the current dir.
Definition at line 345 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::containsMonitorElement(), and m_pCurrentDir.
{
  return m_pCurrentDir->containsMonitorElement(pMonitorElement);
}
bool dqm4hep::DQMStorage::monitorElementExists (const std::string & dirName, DQMMonitorElement * pMonitorElement) const
Whether the monitor element exists in the current dir.
Definition at line 352 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::containsMonitorElement(), dirExists(), findDir(), and RETURN_RESULT_IF.
{
  DQMDirectory *pDirectory = NULL;
  if(!dirExists(dirName))
    return false;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, findDir(dirName, pDirectory));
  return pDirectory->containsMonitorElement(pMonitorElement);
}
const std::string & dqm4hep::DQMStorage::pwd () const
Get the current directory name.
Definition at line 158 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::getName(), and m_pCurrentDir.
Referenced by dqm4hep::DQMMonitorElementManager::pwd().
{
  return m_pCurrentDir->getName();
}
StatusCode dqm4hep::DQMStorage::recursiveContentList (DQMDirectory * pDirectory, std::vector< DQMMonitorElement * > & monitorElementList) [static]
Get recursively all the monitor elements in the sub dirs.
Definition at line 373 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::getMonitorElementList(), dqm4hep::DQMDirectory::getSubDirList(), and RETURN_RESULT_IF.
Referenced by getAllMonitorElements().
{
  if(NULL == pDirectory)
    return STATUS_CODE_INVALID_PTR;
  // add directory contents
  const std::vector<DQMMonitorElement*> &directoryMonitorElementList(pDirectory->getMonitorElementList());
  monitorElementList.insert(monitorElementList.end(), directoryMonitorElementList.begin(),
      directoryMonitorElementList.end());
  // get the sub dir list ...
  const std::vector<DQMDirectory*> &subDirList(pDirectory->getSubDirList());
  if(subDirList.empty())
    return STATUS_CODE_SUCCESS;
  // ... and loop over to add the contents
  for(std::vector<DQMDirectory*>::const_iterator iter = subDirList.begin(), endIter = subDirList.end() ;
      endIter != iter ; ++iter)
  {
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMStorage::recursiveContentList(*iter, monitorElementList));
  }
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMStorage::removeMonitorElement (const std::string & monitorElementName)
Remove a monitor element from the current directory.
Definition at line 292 of file DQMStorage.cc.
References dqm4hep::DQMDirectory::findMonitorElement(), isOwner(), m_pCurrentDir, dqm4hep::DQMDirectory::removeMonitorElement(), RETURN_RESULT_IF, and dqm4hep::DQMMonitorElement::setPath().
Referenced by dqm4hep::DQMMonitorElementManager::deleteMonitorElement().
{
  DQMMonitorElement *pMonitorElement = NULL;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pCurrentDir->findMonitorElement(monitorElementName,
      pMonitorElement));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pCurrentDir->removeMonitorElement(pMonitorElement));
  pMonitorElement->setPath(DQMPath(""));
  if(isOwner())
    delete pMonitorElement;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMStorage::removeMonitorElement (const std::string & dirName, const std::string & monitorElementName)
Remove a monitor element from the given directory.
Definition at line 308 of file DQMStorage.cc.
References findDir(), dqm4hep::DQMDirectory::findMonitorElement(), isOwner(), dqm4hep::DQMDirectory::removeMonitorElement(), RETURN_RESULT_IF, and dqm4hep::DQMMonitorElement::setPath().
{
  DQMDirectory *pDirectory = NULL;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, findDir(dirName, pDirectory));
  DQMMonitorElement *pMonitorElement = NULL;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDirectory->findMonitorElement(monitorElementName,
      pMonitorElement));
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDirectory->removeMonitorElement(pMonitorElement));
  pMonitorElement->setPath(DQMPath(""));
  if(isOwner())
    delete pMonitorElement;
  return STATUS_CODE_SUCCESS;
}
StatusCode dqm4hep::DQMStorage::rmdir (const std::string & fullDirName)
Remove the given directory.
It can't be the root directory or a parent directory of the current directory. The contents will be deleted if the flag 'owner' in the constructor has been passed. Users can check the flag using the method isOwner() and take appropriate action to avoid memory leak
Definition at line 177 of file DQMStorage.cc.
References findDir(), dqm4hep::DQMDirectory::getFullPathName(), dqm4hep::DQMDirectory::getName(), dqm4hep::DQMDirectory::getParentDir(), dqm4hep::DQMPath::getPath(), m_isOwner, m_pCurrentDir, m_pRootDir, dqm4hep::DQMDirectory::removeDir(), and RETURN_RESULT_IF.
Referenced by dqm4hep::DQMMonitorElementManager::rmdir().
{
  if(dirName.empty())
    return STATUS_CODE_NOT_ALLOWED;
  DQMDirectory *pDirectory = NULL;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, findDir(dirName, pDirectory));
  if(pDirectory == m_pRootDir)
    return STATUS_CODE_NOT_ALLOWED;
  std::string fullPathDirName = pDirectory->getFullPathName().getPath();
  std::string currentFullPathDirName = m_pCurrentDir->getFullPathName().getPath();
  size_t pos = currentFullPathDirName.find(fullPathDirName);
  // this mean that the directory that we try
  // to remove is a parent of the current one.
  if(pos == 0 || pos != std::string::npos)
    return STATUS_CODE_FAILURE;
  RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pDirectory->getParentDir()->removeDir(pDirectory->getName(),
      m_isOwner));
  return STATUS_CODE_SUCCESS;
}
Member Data Documentation
bool dqm4hep::DQMStorage::m_isOwner [private]
Definition at line 177 of file DQMStorage.h.
Referenced by isOwner(), and rmdir().
DQMDirectory* dqm4hep::DQMStorage::m_pCurrentDir [private]
Definition at line 175 of file DQMStorage.h.
Referenced by addMonitorElement(), cd(), clear(), DQMStorage(), findDir(), getCurrentDirectory(), getMonitorElement(), goUp(), ls(), mkdir(), monitorElementExists(), pwd(), removeMonitorElement(), rmdir(), and ~DQMStorage().
DQMDirectory* dqm4hep::DQMStorage::m_pRootDir [private]
Definition at line 176 of file DQMStorage.h.
Referenced by cd(), clear(), DQMStorage(), findDir(), getAllMonitorElements(), getRootDirectory(), mkdir(), rmdir(), and ~DQMStorage().
The documentation for this class was generated from the following files:
DQMStorage.h
DQMStorage.cc