dqm4hep::DQMAnalysisModule Class Reference
DQMAnalysisModule class.
#include <DQMAnalysisModule.h>
Public Member Functions
DQMAnalysisModule ()
Constructor.
virtual ~DQMAnalysisModule ()
Destructor.
virtual StatusCode processEvent (DQMEvent *const pEvent)=0
Process an event.
virtual StatusCode startOfRun (DQMRun *const pRun)=0
Called at start of run.
virtual StatusCode endOfRun (DQMRun *const pRun)=0
Called at end of run.
Friends
class DQMAnalysisModuleApplication
Additional Inherited Members
Detailed Description
DQMAnalysisModule class.
Definition at line 44 of file DQMAnalysisModule.h.
Constructor & Destructor Documentation
dqm4hep::DQMAnalysisModule::DQMAnalysisModule ()
Constructor.
Definition at line 34 of file DQMAnalysisModule.cc.
                                     :
    DQMModule()
{
  /* nop */
}
dqm4hep::DQMAnalysisModule::~DQMAnalysisModule () [virtual]
Destructor.
Definition at line 42 of file DQMAnalysisModule.cc.
{
  /* nop */
}
Member Function Documentation
virtual StatusCode dqm4hep::DQMAnalysisModule::endOfRun (DQMRun *const pRun) [pure virtual]
Called at end of run.
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
virtual StatusCode dqm4hep::DQMAnalysisModule::processEvent (DQMEvent *const pEvent) [pure virtual]
Process an event.
Fill histograms in this method
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
virtual StatusCode dqm4hep::DQMAnalysisModule::startOfRun (DQMRun *const pRun) [pure virtual]
Called at start of run.
Referenced by dqm4hep::DQMAnalysisModuleApplication::run().
Friends And Related Function Documentation
friend class DQMAnalysisModuleApplication [friend]
Definition at line 46 of file DQMAnalysisModule.h.
The documentation for this class was generated from the following files:
DQMAnalysisModule.h
DQMAnalysisModule.cc