dqm4hep Namespace Reference
-- std headers
Classes
class BiggerThanValidator
class ClientInfo
ClientInfo class.
class DimEventRequestRpc
DimEventRequestRpc class.
class DimEventRpcInfo
DimEventRpcInfo class.
class DQM4HEP
DQM4HEP class.
class DQMAnalysisModule
DQMAnalysisModule class.
class DQMAnalysisModuleApplication
DQMAnalysisModuleApplication class.
class DQMApplication
DQMApplication class.
class DQMArchiver
DQMArchiver class.
class DQMCalorimeterHitStreamer
DQMCalorimeterHitStreamer class.
class DQMChi2FitFunctionTest
DQMChi2FitFunctionTest class.
class DQMClusterStreamer
DQMClusterStreamer class.
class DQMCollectorInfo
DQMCollectorInfo class.
class DQMCoreTool
DQMCoreTool class.
class DQMCurrentRunRpc
DQMCurrentRunRpc class.
class DQMCurrentRunRpcInfo
class DQMCycle
DQMCycle class.
class DQMCycleListener
DQMCycleListener class.
class DQMDataStream
DQMDataStream class.
class DQMDBFileHandler
DQMDBFileHandler class.
class DQMDBInterface
DQMDBInterface class.
class DQMDimEventClient
DQMDimEventClient class.
class DQMDimEventCollector
DQMDimEventCollector class.
class DQMDimRunControlClient
DQMRunControlClient class.
class DQMDirectory
DQMDirectory class.
class DQMEvent
DQMEvent class.
class DQMEventBase
class DQMEventClient
DQMEventClient class.
class DQMEventClientListener
DQMEventClientListener class.
class DQMEventCollector
DQMEventCollector class.
class DQMEventCollectorApplication
DQMEventCollectorApplication class.
class DQMEventCollectorImp
DQMEventCollectorImp class.
class DQMEventCounterCycle
DQMEventCounterCycle class.
class DQMEventStreamer
DQMEventStreamer class.
class DQMFileHandler
DQMFileHandler interface.
class DQMFileHandlerFactory
DQMFileHandlerFactory class.
class DQMLCCollectionStreamer
DQMLCCollectionStreamer class.
class DQMLCEvent
DQMLCEvent class.
class DQMLCEventStreamer
DQMLCEventStreamer class.
class DQMLCFloatVecStreamer
DQMLCFloatVecStreamer class.
class DQMLCGenericObjectStreamer
DQMLCGenericObjectStreamer class.
class DQMLCIntVecStreamer
DQMLCIntVecStreamer class.
class DQMLcioReaderListener
DQMLcioReaderListener class.
class DQMLCParametersStreamer
DQMLCParametersStreamer class.
class DQMLCStrVecStreamer
DQMLCStrVecStreamer class.
class DQMLocalFileHandler
DQMLocalFileHandler class.
class DQMLogger
DQMLogger interface.
class DQMMeanWithinExpectedTest
DQMMeanWithinExpectedTest class.
class DQMMeCollectorInfoRpcInfo
class DQMMeListNameRpcInfo
class DQMModule
DQMModule base class.
class DQMModuleApi
DQMModuleApi class.
class DQMModuleApplication
DQMModuleApplication class.
class DQMMonitorElement
DQMMonitorElement class.
class DQMMonitorElementClient
DQMMonitorElementClient class.
class DQMMonitorElementClientListener
DQMMonitorElementClientListener class.
class DQMMonitorElementCollector
DQMMonitorElementCollector class.
class DQMMonitorElementCollectorApplication
DQMMonitorElementCollectorApplication class.
class DQMMonitorElementCollectorInfoRpc
class DQMMonitorElementInfo
DQMMonitorElementInfo class Short summary of a DQMMonitorElement that is sent through the network.
class DQMMonitorElementInfoList
class DQMMonitorElementListNameRequest
DQMMonitorElementListNameRequest class.
class DQMMonitorElementManager
DQMMonitorElementManager class.
class DQMMonitorElementNameListRpc
class DQMMonitorElementPublication
DQMMonitorElementPublication class.
class DQMMonitorElementRequest
DQMMonitorElementRequest class.
class DQMMonitorElementSender
DQMMonitorElementSender class.
class DQMNetworkTool
DQMNetworkTool class.
class DQMParticleIDStreamer
DQMParticleIDStreamer class.
class DQMPath
DQMPath class.
class DQMPlugin
DQMPlugin class.
class DQMPluginManager
DQMPluginManager class.
class DQMQualityTest
DQMQualityTest class.
class DQMQualityTestFactory
DQMQualityTestFactory class.
class DQMQualityTestResult
DQMQualityTestResult class Hanlde the result of a quality test.
class DQMRawCalorimeterHitStreamer
DQMRawCalorimeterHitStreamer class.
class DQMRun
DQMRun class.
class DQMRunControl
DQMRunControl class.
class DQMRunControlClient
DQMRunControlClient interface.
class DQMRunControlService
DQMRunControlService class.
class DQMRunListener
DQMRunListener class.
class DQMSingleton
DQMSingleton class.
class DQMStandaloneModule
DQMStandaloneModule class.
class DQMStandaloneModuleApplication
DQMStandaloneModuleApplication class.
class DQMStatisticsClient
DQMStatisticsClient class.
class DQMStatisticsService
DQMStatisticsService class.
struct DQMStats
Stats struct.
class DQMStorage
DQMStorage class.
class DQMStreamable
DQMStreamable interface.
class DQMStreamer
DQMStreamer interface.
class DQMTimerCycle
DQMTimerCycle class.
class DQMTPCHitStreamer
DQMTPCHitStreamer class.
class DQMVersion
DQMVersion class.
class DQMXmlHelper
DQMXmlHelper class.
class DQMXmlIO
DQMXmlIO class.
class ELog
class IntervalValidator
class LessThanValidator
struct ME_REQUEST_COMPARE
ME_REQUEST_COMPARE struct.
class ModuleMeInfo
ModuleMeInfo class.
class NegativeValidator
class NonNullValidator
class PositiveValidator
class scoped_lock
scoped_mutex class
class StatusCodeException
StatusCodeException class.
class TiXmlAttribute
An attribute is a name-value pair.
class TiXmlAttributeSet
class TiXmlBase
TiXmlBase is a base class for every class in TinyXml.
class TiXmlComment
An XML comment.
struct TiXmlCursor
class TiXmlDeclaration
In correct XML the declaration is the first entry in the file.
class TiXmlDocument
Always the top level node.
class TiXmlElement
The element is a container class.
class TiXmlHandle
A TiXmlHandle is a class that wraps a node pointer with null checks; this is an incredibly useful thing.
class TiXmlNode
The parent class for everything in the Document Object Model.
class TiXmlOutStream
class TiXmlParsingData
class TiXmlPrinter
Print to memory functionality.
class TiXmlString
class TiXmlText
XML text.
class TiXmlUnknown
Any tag that tinyXml doesn't recognize is saved as an unknown.
class TiXmlVisitor
Implements the interface to the `Visitor pattern` (see the Accept() method.) If you call the Accept() method, it requires being passed a TiXmlVisitor class to handle callbacks.
class TScalarObject
TScalarObject class.
Typedefs
typedef char dqm_char
typedef uint8_t dqm_uchar
typedef int16_t dqm_short
typedef uint16_t dqm_ushort
typedef int16_t dqm_short_int
typedef uint16_t dqm_ushort_int
typedef int64_t dqm_lint
typedef uint64_t dqm_ulint
typedef float dqm_real
typedef float dqm_float
typedef double dqm_double
typedef bool dqm_bool
typedef int64_t dqm_int
typedef uint64_t dqm_uint
typedef std::vector< int > IntVector
typedef std::vector< unsigned int > UIntVector
typedef std::vector< float > FloatVector
typedef std::vector< std::string > StringVector
typedef std::set< std::string > StringSet
typedef std::map< std::string,
*
std::vector< std::string > > SubscriptionMap
typedef std::vector
*
< DQMMonitorElement * > DQMMonitorElementList
typedef std::map< const
*
std::string, DQMMonitorElement * > DQMMonitorElementMap
typedef std::queue< DQMEvent * > DQMEventQueue
typedef std::map< std::string,
*
DQMQualityTestResult > DQMQualityTestResultMap
typedef std::map< std::string,
*
DQMQualityTest * > DQMQualityTestMap
typedef std::vector< DQMStats > DQMStatsList
typedef TScalarObject< dqm_int > TScalarInt
typedef TScalarObject< dqm_float > TScalarReal
typedef TScalarObject< dqm_float > TScalarFloat
typedef TScalarObject< dqm_double > TScalarDouble
typedef TScalarObject< dqm_short > TScalarShort
typedef TScalarObject< long > TScalarLong
typedef TScalarObject< Long64_t > TScalarLong64_t
typedef TScalarObject
*
< std::string > TScalarString
typedef std::map< int, ClientInfo > ClientMap
typedef std::map< std::string,
*
std::string > LogbookEntryMap
typedef LogbookEntryMap::value_type LogbookEntry
typedef DQMStreamer
*
< EVENT::LCObject > DQMLCObjectStreamer
typedef std::map< const
*
std::string,
*
DQMLCCollectionStreamer * > DQMLCCollectionStreamerMap
Enumerations
enum StatusCode { NUMBER_OF_STATUS_CODES
 }
StatusCode enumerator.
enum DQMQuality { NUMBER_OF_DQM_QUALITIES
 }
DQMQuality enum.
enum DQMState { NUMBER_OF_DQM_STATES
 }
DQMState enum.
enum DQMMonitorElementType { NUMBER_OF_DQM_MONITOR_ELEMENT_TYPES
 }
DQMMonitorElementType enum.
enum DQMResetPolicy { NUMBER_OF_DQM_RESET_POLICIES
 }
DQMResetPolicy enum.
enum LogLevel { DEBUG = 0,
MESSAGE,
WARNING,
ERROR
 }
LogLevel enumerator.
enum UpdateMode { NO_UPDATE = 0,
REPLACE = 1,
APPEND = 2
 }
UpdateMode enumerator.
enum { TIXML_SUCCESS,
TIXML_NO_ATTRIBUTE,
TIXML_WRONG_TYPE
 }
enum TiXmlEncoding { TIXML_ENCODING_UNKNOWN,
TIXML_ENCODING_UTF8,
TIXML_ENCODING_LEGACY
 }
Functions
std::string statusCodeToString (const StatusCode statusCode)
std::string qualityToString (const DQMQuality quality)
std::string stateToString (const DQMState state)
std::string monitorElementTypeToString (const DQMMonitorElementType type)
DQMMonitorElementType stringToMonitorElementType (const std::string &str)
DQMMonitorElementType stringToMonitorElementRootType (const std::string &str)
std::string resetPolicyToString (const DQMResetPolicy policy)
DQMResetPolicy stringToResetPolicy (const std::string &str)
void printRawBuffer (char *pBuffer, int bufferSize)
Print the raw buffer.
DQMPath operator+ (const DQMPath &lhs, const DQMPath &rhs)
std::ostream & operator<< (std::ostream &out, const DQMPath &path)
bool operator== (const DQMPath &lhs, const DQMPath &rhs)
bool operator< (const DQMVersion &lhs, const DQMVersion &rhs)
bool operator<= (const DQMVersion &lhs, const DQMVersion &rhs)
bool operator> (const DQMVersion &lhs, const DQMVersion &rhs)
bool operator>= (const DQMVersion &lhs, const DQMVersion &rhs)
bool operator== (const DQMVersion &lhs, const DQMVersion &rhs)
bool operator!= (const DQMVersion &lhs, const DQMVersion &rhs)
bool operator== (const TiXmlString &a, const TiXmlString &b)
bool operator< (const TiXmlString &a, const TiXmlString &b)
bool operator!= (const TiXmlString &a, const TiXmlString &b)
bool operator> (const TiXmlString &a, const TiXmlString &b)
bool operator<= (const TiXmlString &a, const TiXmlString &b)
bool operator>= (const TiXmlString &a, const TiXmlString &b)
bool operator== (const TiXmlString &a, const char *b)
bool operator== (const char *a, const TiXmlString &b)
bool operator!= (const TiXmlString &a, const char *b)
bool operator!= (const char *a, const TiXmlString &b)
TiXmlString operator+ (const TiXmlString &a, const TiXmlString &b)
TiXmlString operator+ (const TiXmlString &a, const char *b)
TiXmlString operator+ (const char *a, const TiXmlString &b)
FILE * TiXmlFOpen (const char *filename, const char *mode)
Variables
const int TIXML_MAJOR_VERSION = 2
const int TIXML_MINOR_VERSION = 6
const int TIXML_PATCH_VERSION = 1
const TiXmlEncoding TIXML_DEFAULT_ENCODING = TIXML_ENCODING_UNKNOWN
const unsigned char TIXML_UTF_LEAD_0 = 0xefU
const unsigned char TIXML_UTF_LEAD_1 = 0xbbU
const unsigned char TIXML_UTF_LEAD_2 = 0xbfU
Detailed Description
-- std headers
Typedef Documentation
typedef std::map<int, ClientInfo> dqm4hep::ClientMap
Definition at line 184 of file DQMMonitorElementCollector.h.
typedef bool dqm4hep::dqm_bool
Definition at line 124 of file DQM4HEP.h.
typedef char dqm4hep::dqm_char
Definition at line 108 of file DQM4HEP.h.
typedef double dqm4hep::dqm_double
Definition at line 123 of file DQM4HEP.h.
typedef float dqm4hep::dqm_float
Definition at line 122 of file DQM4HEP.h.
typedef int64_t dqm4hep::dqm_int
Definition at line 125 of file DQM4HEP.h.
typedef int64_t dqm4hep::dqm_lint
Definition at line 119 of file DQM4HEP.h.
typedef float dqm4hep::dqm_real
Definition at line 121 of file DQM4HEP.h.
typedef int16_t dqm4hep::dqm_short
Definition at line 115 of file DQM4HEP.h.
typedef int16_t dqm4hep::dqm_short_int
Definition at line 117 of file DQM4HEP.h.
typedef uint8_t dqm4hep::dqm_uchar
Definition at line 114 of file DQM4HEP.h.
typedef uint64_t dqm4hep::dqm_uint
Definition at line 126 of file DQM4HEP.h.
typedef uint64_t dqm4hep::dqm_ulint
Definition at line 120 of file DQM4HEP.h.
typedef uint16_t dqm4hep::dqm_ushort
Definition at line 116 of file DQM4HEP.h.
typedef uint16_t dqm4hep::dqm_ushort_int
Definition at line 118 of file DQM4HEP.h.
typedef std::queue<DQMEvent*> dqm4hep::DQMEventQueue
Definition at line 141 of file DQM4HEP.h.
typedef std::map<const std::string, DQMLCCollectionStreamer *> dqm4hep::DQMLCCollectionStreamerMap
Definition at line 52 of file DQMLCEventStreamer.h.
typedef DQMStreamer<EVENT::LCObject> dqm4hep::DQMLCObjectStreamer
Definition at line 49 of file DQMLCEventStreamer.h.
typedef std::vector<DQMMonitorElement*> dqm4hep::DQMMonitorElementList
Definition at line 138 of file DQM4HEP.h.
typedef std::map<const std::string, DQMMonitorElement*> dqm4hep::DQMMonitorElementMap
Definition at line 139 of file DQM4HEP.h.
typedef std::map<std::string, DQMQualityTest*> dqm4hep::DQMQualityTestMap
Definition at line 144 of file DQM4HEP.h.
typedef std::map<std::string, DQMQualityTestResult> dqm4hep::DQMQualityTestResultMap
Definition at line 143 of file DQM4HEP.h.
typedef std::vector<DQMStats> dqm4hep::DQMStatsList
Definition at line 146 of file DQM4HEP.h.
typedef std::vector<float> dqm4hep::FloatVector
Definition at line 131 of file DQM4HEP.h.
typedef std::vector<int> dqm4hep::IntVector
Definition at line 129 of file DQM4HEP.h.
typedef LogbookEntryMap::value_type dqm4hep::LogbookEntry
Definition at line 39 of file ELogInterface.h.
typedef std::map<std::string, std::string> dqm4hep::LogbookEntryMap
Definition at line 38 of file ELogInterface.h.
typedef std::set<std::string> dqm4hep::StringSet
Definition at line 133 of file DQM4HEP.h.
typedef std::vector<std::string> dqm4hep::StringVector
Definition at line 132 of file DQM4HEP.h.
typedef std::map<std::string, std::vector<std::string> > dqm4hep::SubscriptionMap
Definition at line 136 of file DQM4HEP.h.
typedef TScalarObject<dqm_double> dqm4hep::TScalarDouble
Definition at line 308 of file DQMMonitorElement.h.
typedef TScalarObject<dqm_float> dqm4hep::TScalarFloat
Definition at line 307 of file DQMMonitorElement.h.
typedef TScalarObject<dqm_int> dqm4hep::TScalarInt
Definition at line 305 of file DQMMonitorElement.h.
typedef TScalarObject<long> dqm4hep::TScalarLong
Definition at line 310 of file DQMMonitorElement.h.
typedef TScalarObject<Long64_t> dqm4hep::TScalarLong64_t
Definition at line 311 of file DQMMonitorElement.h.
typedef TScalarObject<dqm_float> dqm4hep::TScalarReal
Definition at line 306 of file DQMMonitorElement.h.
typedef TScalarObject<dqm_short> dqm4hep::TScalarShort
Definition at line 309 of file DQMMonitorElement.h.
typedef TScalarObject<std::string> dqm4hep::TScalarString
Definition at line 312 of file DQMMonitorElement.h.
typedef std::vector<unsigned int> dqm4hep::UIntVector
Definition at line 130 of file DQM4HEP.h.
Enumeration Type Documentation
anonymous enum
Enumerator
TIXML_SUCCESS
TIXML_NO_ATTRIBUTE
TIXML_WRONG_TYPE
Definition at line 160 of file tinyxml.h.
{
  TIXML_SUCCESS,
  TIXML_NO_ATTRIBUTE,
  TIXML_WRONG_TYPE
};
enum dqm4hep::DQMMonitorElementType
DQMMonitorElementType enum.
Enumerator
NUMBER_OF_DQM_MONITOR_ELEMENT_TYPES
Definition at line 483 of file DQM4HEP.h.
{
  DQM_MONITOR_ELEMENT_TYPE_TABLE(GET_ENUM_ENTRY_2)
  NUMBER_OF_DQM_MONITOR_ELEMENT_TYPES
};
enum dqm4hep::DQMQuality
DQMQuality enum.
Enumerator
NUMBER_OF_DQM_QUALITIES
Definition at line 336 of file DQM4HEP.h.
{
  DQM_QUALITY_TABLE(GET_ENUM_ENTRY)
  NUMBER_OF_DQM_QUALITIES
};
enum dqm4hep::DQMResetPolicy
DQMResetPolicy enum.
Corresponds to the period at which the element have to be reset. If eNoReset is chosen then the user can call reset at any time in the processing. The default one is eResetAtEndOfCycle.
Enumerator
NUMBER_OF_DQM_RESET_POLICIES
Definition at line 525 of file DQM4HEP.h.
{
  DQM_RESET_POLICY_TABLE(GET_ENUM_ENTRY)
  NUMBER_OF_DQM_RESET_POLICIES
};
enum dqm4hep::DQMState
DQMState enum.
Enumerator
NUMBER_OF_DQM_STATES
Definition at line 445 of file DQM4HEP.h.
{
  DQM_STATE_TABLE(GET_ENUM_ENTRY)
  NUMBER_OF_DQM_STATES
};
enum dqm4hep::LogLevel
LogLevel enumerator.
Enumerator
DEBUG
MESSAGE
WARNING
ERROR
Definition at line 550 of file DQM4HEP.h.
{
  DEBUG = 0,
  MESSAGE,
  WARNING,
  ERROR
};
enum dqm4hep::StatusCode
StatusCode enumerator.
Enumerator
NUMBER_OF_STATUS_CODES
Definition at line 281 of file DQM4HEP.h.
{
  STATUS_CODE_TABLE(GET_ENUM_ENTRY)
  NUMBER_OF_STATUS_CODES
};
enum dqm4hep::TiXmlEncoding
Enumerator
TIXML_ENCODING_UNKNOWN
TIXML_ENCODING_UTF8
TIXML_ENCODING_LEGACY
Definition at line 169 of file tinyxml.h.
{
  TIXML_ENCODING_UNKNOWN,
  TIXML_ENCODING_UTF8,
  TIXML_ENCODING_LEGACY
};
enum dqm4hep::UpdateMode
UpdateMode enumerator.
Enumerator
NO_UPDATE
REPLACE
APPEND
Definition at line 562 of file DQM4HEP.h.
{
  NO_UPDATE = 0,
  REPLACE = 1,
  APPEND = 2
};
Function Documentation
std::string dqm4hep::monitorElementTypeToString (const DQMMonitorElementType type) [inline]
Definition at line 489 of file DQM4HEP.h.
References DQM_MONITOR_ELEMENT_TYPE_TABLE, and GET_NAME_SWITCH_2.
Referenced by dqm4hep::DQMMonitorElementSender::addAvailableMonitorElement(), and dqm4hep::DQMMonitorElementNameListRpc::rpcHandler().
{
  switch (type)
  {
    DQM_MONITOR_ELEMENT_TYPE_TABLE(GET_NAME_SWITCH_2)
    default : throw dqm4hep::StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
  }
}
bool dqm4hep::operator!= (const DQMVersion & lhs, const DQMVersion & rhs)
Definition at line 165 of file DQMVersion.cc.
{
  return ! (lhs == rhs);
}
bool dqm4hep::operator!= (const TiXmlString & a, const TiXmlString & b) [inline]
Definition at line 281 of file tinystr.h.
{ return !(a == b); }
bool dqm4hep::operator!= (const TiXmlString & a, const char * b) [inline]
Definition at line 288 of file tinystr.h.
{ return !(a == b); }
bool dqm4hep::operator!= (const char * a, const TiXmlString & b) [inline]
Definition at line 289 of file tinystr.h.
{ return !(b == a); }
DQMPath dqm4hep::operator+ (const DQMPath & lhs, const DQMPath & rhs) [inline]
operator
Definition at line 102 of file DQMPath.h.
References dqm4hep::DQMPath::m_path.
{
  DQMPath path(lhs.m_path);
  path += rhs;
  return path;
}
TiXmlString dqm4hep::operator+ (const TiXmlString & a, const TiXmlString & b)
Definition at line 89 of file tinystr.cc.
References dqm4hep::TiXmlString::length(), and dqm4hep::TiXmlString::reserve().
{
  TiXmlString tmp;
  tmp.reserve(a.length() + b.length());
  tmp += a;
  tmp += b;
  return tmp;
}
TiXmlString dqm4hep::operator+ (const TiXmlString & a, const char * b)
Definition at line 98 of file tinystr.cc.
References dqm4hep::TiXmlString::append(), dqm4hep::TiXmlString::length(), and dqm4hep::TiXmlString::reserve().
{
  TiXmlString tmp;
  TiXmlString::size_type b_len = static_cast<TiXmlString::size_type>(strlen(b));
  tmp.reserve(a.length() + b_len);
  tmp += a;
  tmp.append(b, b_len);
  return tmp;
}
TiXmlString dqm4hep::operator+ (const char * a, const TiXmlString & b)
Definition at line 108 of file tinystr.cc.
References dqm4hep::TiXmlString::append(), dqm4hep::TiXmlString::length(), and dqm4hep::TiXmlString::reserve().
{
  TiXmlString tmp;
  TiXmlString::size_type a_len = static_cast<TiXmlString::size_type>(strlen(a));
  tmp.reserve(a_len + b.length());
  tmp.append(a, a_len);
  tmp += b;
  return tmp;
}
bool dqm4hep::operator< (const DQMVersion & lhs, const DQMVersion & rhs)
Definition at line 111 of file DQMVersion.cc.
References dqm4hep::DQMVersion::getMajor(), dqm4hep::DQMVersion::getMinor(), and dqm4hep::DQMVersion::getPatch().
{
  if(lhs.getMajor() < rhs.getMajor())
    return true;
  if(lhs.getMinor() < rhs.getMinor())
    return true;
  if(lhs.getPatch() < rhs.getPatch())
    return true;
  return false;
}
bool dqm4hep::operator< (const TiXmlString & a, const TiXmlString & b) [inline]
Definition at line 276 of file tinystr.h.
References dqm4hep::TiXmlString::c_str().
{
  return strcmp(a.c_str(), b.c_str()) < 0;
}
std::ostream& dqm4hep::operator<< (std::ostream & out, const DQMPath & path) [inline]
Definition at line 112 of file DQMPath.h.
References dqm4hep::DQMPath::m_path.
{
  out << path.m_path;
  return out;
}
bool dqm4hep::operator<= (const DQMVersion & lhs, const DQMVersion & rhs)
Definition at line 127 of file DQMVersion.cc.
References dqm4hep::DQMVersion::getMajor(), dqm4hep::DQMVersion::getMinor(), and dqm4hep::DQMVersion::getPatch().
{
  if(lhs < rhs)
    return true;
  if(lhs.getMajor() == rhs.getMajor()
  && lhs.getMinor() == rhs.getMinor()
  && lhs.getPatch() == rhs.getPatch())
    return true;
  return false;
}
bool dqm4hep::operator<= (const TiXmlString & a, const TiXmlString & b) [inline]
Definition at line 283 of file tinystr.h.
{ return !(b < a); }
bool dqm4hep::operator== (const DQMVersion & lhs, const DQMVersion & rhs)
Definition at line 156 of file DQMVersion.cc.
References dqm4hep::DQMVersion::getMajor(), dqm4hep::DQMVersion::getMinor(), and dqm4hep::DQMVersion::getPatch().
{
  return (lhs.getMajor() == rhs.getMajor()
      && lhs.getMinor() == rhs.getMinor()
      && lhs.getPatch() == rhs.getPatch());
}
bool dqm4hep::operator== (const DQMPath & lhs, const DQMPath & rhs) [inline]
Definition at line 121 of file DQMPath.h.
References dqm4hep::DQMPath::getSplitPath().
{
  return (lhs.getSplitPath() == rhs.getSplitPath());
}
bool dqm4hep::operator== (const TiXmlString & a, const TiXmlString & b) [inline]
Definition at line 271 of file tinystr.h.
References dqm4hep::TiXmlString::c_str(), and dqm4hep::TiXmlString::length().
{
  return (a.length() == b.length()) // optimization on some platforms
         && (strcmp(a.c_str(), b.c_str()) == 0); // actual compare
}
bool dqm4hep::operator== (const TiXmlString & a, const char * b) [inline]
Definition at line 286 of file tinystr.h.
References dqm4hep::TiXmlString::c_str().
{ return strcmp(a.c_str(), b) == 0; }
bool dqm4hep::operator== (const char * a, const TiXmlString & b) [inline]
Definition at line 287 of file tinystr.h.
{ return b == a; }
bool dqm4hep::operator> (const DQMVersion & lhs, const DQMVersion & rhs)
Definition at line 142 of file DQMVersion.cc.
{
  return ! (lhs <= rhs);
}
bool dqm4hep::operator> (const TiXmlString & a, const TiXmlString & b) [inline]
Definition at line 282 of file tinystr.h.
{ return b < a; }
bool dqm4hep::operator>= (const DQMVersion & lhs, const DQMVersion & rhs)
Definition at line 149 of file DQMVersion.cc.
{
  return ! (lhs < rhs);
}
bool dqm4hep::operator>= (const TiXmlString & a, const TiXmlString & b) [inline]
Definition at line 284 of file tinystr.h.
{ return !(a < b); }
void dqm4hep::printRawBuffer (char * pBuffer, int bufferSize)
Print the raw buffer.
Definition at line 160 of file DQM4HEP.cc.
{
  std::cout << "taille : " << bufferSize << " address : " << (void *)pBuffer << std::endl;
  for(int i=0 ; i<bufferSize ; i++)
  {
    printf("%2x", pBuffer[i]);
    if(i%30 == 0)
      std::cout << std::endl;
  }
  std::cout << std::endl;
}
std::string dqm4hep::qualityToString (const DQMQuality quality) [inline]
Definition at line 342 of file DQM4HEP.h.
References DQM_QUALITY_TABLE, and GET_NAME_SWITCH.
{
  switch (quality)
  {
    DQM_QUALITY_TABLE(GET_NAME_SWITCH)
    default : throw dqm4hep::StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
  }
}
std::string dqm4hep::resetPolicyToString (const DQMResetPolicy policy) [inline]
Definition at line 531 of file DQM4HEP.h.
References DQM_RESET_POLICY_TABLE, and GET_NAME_SWITCH.
{
 switch (policy)
 {
  DQM_RESET_POLICY_TABLE(GET_NAME_SWITCH)
    default : throw dqm4hep::StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
 }
}
std::string dqm4hep::stateToString (const DQMState state) [inline]
Definition at line 451 of file DQM4HEP.h.
References DQM_STATE_TABLE, and GET_NAME_SWITCH.
{
 switch (state)
 {
  DQM_STATE_TABLE(GET_NAME_SWITCH)
    default : throw dqm4hep::StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
 }
}
std::string dqm4hep::statusCodeToString (const StatusCode statusCode) [inline]
Definition at line 426 of file DQM4HEP.h.
References GET_NAME_SWITCH, and STATUS_CODE_TABLE.
Referenced by dqm4hep::StatusCodeException::toString().
{
  switch (statusCode)
  {
    STATUS_CODE_TABLE(GET_NAME_SWITCH)
    default : throw dqm4hep::StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
  }
}
DQMMonitorElementType dqm4hep::stringToMonitorElementRootType (const std::string & str) [inline]
Definition at line 504 of file DQM4HEP.h.
References DQM_MONITOR_ELEMENT_TYPE_TABLE, and GET_STR_COMPARE_2.
Referenced by dqm4hep::DQMMonitorElementManager::bookMonitorElement().
{
  DQM_MONITOR_ELEMENT_TYPE_TABLE(GET_STR_COMPARE_2)
  else return NO_ELEMENT_TYPE;
}
DQMMonitorElementType dqm4hep::stringToMonitorElementType (const std::string & str) [inline]
Definition at line 498 of file DQM4HEP.h.
References DQM_MONITOR_ELEMENT_TYPE_TABLE, and GET_STR_COMPARE_1.
{
  DQM_MONITOR_ELEMENT_TYPE_TABLE(GET_STR_COMPARE_1)
  else return NO_ELEMENT_TYPE;
}
DQMResetPolicy dqm4hep::stringToResetPolicy (const std::string & str) [inline]
Definition at line 540 of file DQM4HEP.h.
References DQM_RESET_POLICY_TABLE, and GET_STR_COMPARE.
Referenced by dqm4hep::DQMMonitorElementManager::bookMonitorElement().
{
  DQM_RESET_POLICY_TABLE(GET_STR_COMPARE)
  else return NO_RESET_POLICY;
}
FILE * dqm4hep::TiXmlFOpen (const char * filename, const char * mode)
Definition at line 42 of file tinyxml.cc.
Referenced by dqm4hep::TiXmlDocument::LoadFile(), and dqm4hep::TiXmlDocument::SaveFile().
{
  #if defined(_MSC_VER) && (_MSC_VER >= 1400)
    FILE* fp = 0;
    errno_t err = fopen_s(&fp, filename, mode);
    if (!err && fp)
      return fp;
    return 0;
  #else
    return fopen(filename, mode);
  #endif
}
Variable Documentation
const TiXmlEncoding dqm4hep::TIXML_DEFAULT_ENCODING = TIXML_ENCODING_UNKNOWN
Definition at line 176 of file tinyxml.h.
const int dqm4hep::TIXML_MAJOR_VERSION = 2
Definition at line 98 of file tinyxml.h.
const int dqm4hep::TIXML_MINOR_VERSION = 6
Definition at line 99 of file tinyxml.h.
const int dqm4hep::TIXML_PATCH_VERSION = 1
Definition at line 100 of file tinyxml.h.
const unsigned char dqm4hep::TIXML_UTF_LEAD_0 = 0xefU
Definition at line 65 of file tinyxmlparser.cc.
Referenced by dqm4hep::TiXmlDocument::SaveFile().
const unsigned char dqm4hep::TIXML_UTF_LEAD_1 = 0xbbU
Definition at line 66 of file tinyxmlparser.cc.
Referenced by dqm4hep::TiXmlDocument::SaveFile().
const unsigned char dqm4hep::TIXML_UTF_LEAD_2 = 0xbfU
Definition at line 67 of file tinyxmlparser.cc.
Referenced by dqm4hep::TiXmlDocument::SaveFile(), and dqm4hep::TiXmlBase::SkipWhiteSpace().