dqm4hep::DQMEventBase< T > Class Template Reference
#include <DQMEvent.h>
Public Member Functions
virtual ~DQMEventBase ()
Destructor.
virtual T * getEvent () const =0
Returns the stored event.
virtual void setEvent (T *pEvent)=0
Set the handled event.
virtual void clear ()=0
Clear the handler by deleting the handled event.
Additional Inherited Members
Detailed Description
template<typename T>class dqm4hep::DQMEventBase< T >
Definition at line 39 of file DQMEvent.h.
Constructor & Destructor Documentation
template<typename T > dqm4hep::DQMEventBase< T >::~DQMEventBase () [inline], [virtual]
Destructor.
Definition at line 180 of file DQMEvent.h.
{
}
Member Function Documentation
template<typename T> virtual void dqm4hep::DQMEventBase< T >::clear () [pure virtual]
Clear the handler by deleting the handled event.
Implemented in dqm4hep::DQMLCEvent .
Referenced by dqm4hep::DQMEvent::clear().
template<typename T> virtual T* dqm4hep::DQMEventBase< T >::getEvent () const [pure virtual]
Returns the stored event.
Implemented in dqm4hep::DQMLCEvent .
Referenced by dqm4hep::DQMEvent::getEvent().
template<typename T> virtual void dqm4hep::DQMEventBase< T >::setEvent (T * pEvent) [pure virtual]
Set the handled event.
Implemented in dqm4hep::DQMLCEvent .
Referenced by dqm4hep::DQMEvent::setEvent().
The documentation for this class was generated from the following file:
DQMEvent.h